Fix #9763: Elaboration weaker with primitive projections
coq/coq pull request #10130
Opened 2019-05-09 19:26 UTC by maximedenes

Fixes / closes #9763 

- [X] Added / updated test-suite

2019-05-09 19:26 UTC, maximedenes commented
@ppedrot or @SkySkimmer can you assign? Thanks!

2019-05-09 19:27 UTC, maximedenes commented
Cc @vbgl

2019-05-09 19:36 UTC, SkySkimmer reviewed
TBH I don't know what this code does

2019-05-09 19:36 UTC, SkySkimmer commented on test-suite/bugs/closed/bug_9763.v
> +End OK.
Remove this non needed part of the test

2019-05-09 19:51 UTC, maximedenes commented on test-suite/bugs/closed/bug_9763.v
> +End OK.
Well, in case of a failure I think it could help a diagnosis: determining if it comes from the pretyper changing behavior, or from a discrepancy in the primitive projection compat layer.

And the cost is low IMHO.

2019-05-10 06:54 UTC, maximedenes commented
> TBH I don't know what this code does

Maybe @ppedrot can be the assignee, then? This is not a deep change, it is replacing `let x := proj t in u` by `(fun x => u) (proj t)` in the elaboration of the destructuring `let` on primitive records. This makes unification handle it in the expected way.

2019-05-10 07:10 UTC, ppedrot commented
Here is a test with complex let bindings, to see if that still works.
```
Set Primitive Projections.

Record foo := Foo {
  bar : nat;
  baz := S bar;
  qux : match baz
          return match baz with 0 => Set | S _ => unit -> Set end with
        | 0 => unit
        | S _ => fun (i : unit) => unit
        end tt;
}.

Definition test (f : foo) : unit :=
match f with Foo b q => q end.
```

2019-05-10 07:15 UTC, maximedenes commented
This patch changes only the code elaborating `LetTuple` (don't ask me why it's not the same code as for match). So it does not change anything on your example.

2019-05-10 08:10 UTC, gares requested changes
I guess I know what this does (since we figured out that together) but I still think you write some doc at least in the commit message (better in the code). A start could be:
```
let (x,..,z) as w return T w := t in b
```
in case of `t` begin a primitive record is no more elaborated to
```
let x := proj1 t in ... let z := projn t in b
```
but rather
```
(fun x .. z -> b : T (k x .. z)) (proj1 t) .. (projn t)
```
because:
- the match imposes a type constraint on `b` while if you just put the `let xi := proji t` in the context you don't have it (so type inference gets weaker)
- unification is weaker with let-ins in the context rather than variables since Miller-patterns don't apply

and:
- explain you conjecture why by replacing let by beta-redexes you lose no typeable terms in this case

2019-05-10 08:12 UTC, maximedenes commented
Will do. Note that I didn't even have to put a cast, at the end.

2019-05-10 08:15 UTC, gares commented
> Note that I didn't even have to put a cast, at the end.

O_o then, where does the `exists` come from in the example? The cast was the "generic constructor", dual to the "generic destructor `let () := ..`"

Even if it is not necessary in this case, I still prefer the cast to be there (so that we are sure switching primproj on does not change inference).

2019-05-10 08:18 UTC, maximedenes commented
> Even if it is not necessary in this case, I still prefer the cast to be there (so that we are sure switching primproj on does not change inference).

On the contrary, I think it is a bit dangerous since it makes the real term further away from the syntax show to the user. Think occurrences of variables etc. So if not needed, I'd rather not put it there.

Don't forget that the whole idea of this compatibility layer is broken beyond repair. This patch is certainly not claiming to fix that. We are just trying to unblock the use of primitive projections in stdlib2.

2019-05-10 08:22 UTC, maximedenes commented
> it makes the real term further away from the syntax show to the user

Although maybe it in fact reflects the presence of the `return` clause. I'll need to think more about it.

2019-05-10 08:26 UTC, gares commented
Yes, I meant: if there is a return clause, then put the cast. Otherwise you are tossing away a term written by the user.

2019-05-10 08:45 UTC, ppedrot commented
> Don't forget that the whole idea of this compatibility layer is broken beyond repair.

I am happy to witness that more and more people are subscribing to this point of view.

2019-05-16 17:11 UTC, mattam82 commented
Unification in b should be easier indeed, turning the lets into lambda abstractions is exactly what dynamic pattern unification of Abel & Pientka is doing. However with nesting you still lose a bit of sharing (e.g. repeating x.2 many times) compared to pattern-matching on non-primitive records.

2019-05-18 09:22 UTC, jashug commented
Doesn't using lambda abstractions break terms where the type of the body depends on the bound variables being convertible to the projections? Is that intended (it is closer to elaborating to a single match)?
```coq
Set Primitive Projections.
Record Foo := {a:nat; b:bool}.
Definition foo : Foo := {|a:=3; b:=true|}.
Check (let (x,y) as f return f.(a) = 3 := foo in (eq_refl : x = 3)).
Check (let x:=foo.(a) in let y:=foo.(b) in (eq_refl : x = 3)).
Fail Check ((fun x y => eq_refl : x = 3) foo.(a) foo.(b)).
```

2019-05-18 11:15 UTC, mattam82 commented
Ah you’re right, somehow I though this would only apply to abstract variables, where eta-equality would allow the transformation, but for arbitrary terms it’s not going to be type preserving

2019-05-18 13:15 UTC, gares commented
> Doesn't using lambda abstractions break terms where the type of the body depends on the bound variables being convertible to the projections? Is that intended (it is closer to elaborating to a single match)?

You are right in general: replacing a let by a beta redex (that is hiding a term) can break typing.
But note that your example also shows that the elaboration primitive projections do is fishy.

```coq
Record Foo := {a:nat; b:bool}.
Definition foo : Foo := {|a:=3; b:=true|}.
Check (let (x,y) as f return f.(a) = 3 := foo in (eq_refl : x = 3)).
```
I get, in 8.9,
```
Toplevel input, characters 50-57:
> Check (let (x,y) as f return f.(a) = 3 := foo in (eq_refl : x = 3)).
>                                                   ^^^^^^^
Error:
In environment
x : nat
y : bool
The term "eq_refl" has type "x = x" while it is expected to have type 
"x = 3" (cannot unify "x" and "3").
```
Indeed in a regular match a branch must type check whatever the scrutinee is. The type of the match can depend on the actual scrutinee value, but not the branches! 

To me the new elaboration is more "faithful" than the old one.

2019-05-22 15:46 UTC, maximedenes commented
After discussing with @vbgl and @gares, I'm starting to believe this is an XY problem. We should probably investigate if we couldn't write a small metaprogram to support the subtype notation. It seems more reasonable to find a constructor from a record projection by looking up in the record table than by relying on unification (and even more so with primitive projections, where we also rely on a compat layer in the elaboration).

2019-05-22 16:10 UTC, mattam82 commented
@gares is right, the current translation is not faithful to usual the usual ‘match’ translation. It’s an interesting difference!

2019-05-27 21:05 UTC, ppedrot commented
So, what do we do with this PR, @maximedenes ?

2019-10-11 15:57 UTC, maximedenes commented
> So, what do we do with this PR, @maximedenes ?

Not clear to me. @vbgl is currently working on trying to decorrelate primitive projections and their compatibilty layer. Let's wait to see what it gives, and whether this patch is still useful after that or not. Please keep it open meanwhile.

2019-10-11 15:58 UTC, ppedrot commented
Unassigning in the meantime then.

2021-09-01 13:44 UTC, closed without merging