Adding a function to be typically used to pass values from an OCaml "when" clause to the r.h.s of the matching clause
coq/coq pull request #1015
Opened 2017-09-01 21:31 UTC by herbelin

Who has not wanted to reuse in the right-hand side of an OCaml clause some computation done in a `when` clause?

The attached PR adds a function in `Util` which can be used to memoize on the fly such computation for reuse in the right-hand side.

This is honestly not specially elegant style. It would certainly be more elegant to have this natively provided in OCaml though I don't know with which intuitive syntax it could be provided (maybe something like `... when expr binding x1 and ... and xn -> ...` for `x1` ... `xn` already in scope?). I would hardly believe that this kind of things has not already been considered.

2017-09-02 10:29 UTC, mattam82 commented
Can you provide an example? I've been wanting that a few times too.

2017-09-02 12:20 UTC, SkySkimmer commented
If it's supposed to be used solely to provide a binding from a when clause maybe the setter should assert `!a = None`?

2017-09-02 17:37 UTC, gares commented
I think the name of the API is badly chosen.

In general I prefer to embed this pattern into the API I'm calling, eg
```
match x with
| String s when re_match s "pattern" -> ... get_re_last_capture s ...
```
otherwise the `when` clause gets too long and hence unreadable.

Last, the API is not thread safe, so it should either be said or made it so
by associating the value to a thread id.

2017-09-03 14:53 UTC, herbelin commented
@mattam82: the case I encountered was while testing a special case when the factorization of match clauses leads to only one equation (full code [here](https://github.com/herbelin/github-coq/blob/master%2Bnotation-misc-extensions/interp/notation_ops.ml#L1153-L1168)):
  ```coq
    | Name id, GCases (LetPatternStyle, None, [({ CAst.v = GVar id' },(Anonymous,None))],(_::_ as eqns))
         when Id.equal id id' && List.length (store (factorize_eqns eqns)) = 1 ->
      (match get () with
  ```
I had once this need in another part of the code I contributed to Coq, but I can't find it anymore.

@gares: I'm sorry to tell that I'm not familiar with thread safety. Could you please propose a patch to ensure thread safety or tell what is the problem and how to solve it. Thanks in advance!

As for the name, I'm not satisfy with it either, so, don't hesitate to make a proposal.

@Skyskimmer: why not.

2017-09-03 20:05 UTC, gares commented
I was wrong, your code is thread safe, since the two closures are "private".
What is not thread safe is making the ref global, as I was suggesting. Sorry for the noise

2017-09-03 20:26 UTC, herbelin commented
> Sorry for the noise

No problem, and thanks in passing for the explanation.

2017-09-11 09:32 UTC, ppedrot requested changes
I'm not very fond of complex when clauses, but assuming we use them, I understand the motivation. Thus, this patch seems rather OK to me. Just to nitpick though, I think it's better to replace the `Option.get` by a match that raises an assertion failure when the `None` branch is taken. Exceptions are a mess in the current codebase, let us not add randomly new ones when there is no need.

2017-09-12 18:23 UTC, herbelin commented
Nitpicking applied. But I see this proposal as a second-step solution, a compromise between different constraints (sharing clauses, sharing computations, not artificially introducing extra data structure) for which a proper syntax may be provided at the OCaml level, even more than the bindings to share are already in the environment when evaluating the `when` clause.

2017-10-03 09:30 UTC, maximedenes commented
@ppedrot does it look good to you know?

2017-10-03 10:00 UTC, ppedrot approved these changes
LGTM.

2017-10-03 10:20 UTC, merged