[Ltac2] Add util files for Bool, List, Option
coq/coq pull request #10219
Opened 2019-05-22 21:23 UTC by JasonGross

Most functions are taken either from the Coq standard library or the
OCaml standard library.  One (`enumerate`) is taken from Python.  Most
names are chosen according to OCaml conventions (as Coq does not have
exceptions, and so the OCaml naming conventions already distinguish
between option and exception).  Since `exists` is a keyword, we use the
Coq name `existsb` instead.  We generally favor Coq argument ordering
when there is a conflict between Coq and OCaml.

Note that `seq` matches neither Coq nor OCaml; it takes a `step`
argument for how much to increment by on each step.

Sorting functions are mostly taken from Coq's mergesort library; it
might make sense to replace them with OCaml's versions for efficiency?

**Kind:** feature.

Fixes / closes coq/ltac2#19 (mostly; I haven't ported the reimplementation of lazy_match, but I think that's okay)

Which of these should this PR get?
- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

2019-05-22 21:27 UTC, ppedrot commented on user-contrib/Ltac2/List.v
> +  | [] => Control.zero (Tactic_failure (Some (Message.of_string "hd")))
This needs to be discussed in the API guidelines, but I don't think using backtracking exceptions for anything else than proof search is a good idea. I believe that instead panics should be used when preconditions of a function call are not satisfied, which looks like this is the case here.

2019-05-22 22:05 UTC, Zimmi48 commented on user-contrib/Ltac2/Bool.v
> +(************************************************************************)
This is an outdated header. I wonder where you found it. OMG you found it in the code of Ltac2! I wonder how I could let that split. Anyway, you can find the right header in `dev/header.ml`

2019-05-23 01:13 UTC, JasonGross commented on user-contrib/Ltac2/List.v
> +  | [] => Control.zero (Tactic_failure (Some (Message.of_string "hd")))
I think there are three sorts of errors, and it is important to be able to express all of them:
1. `Control.zero` - failure in the tactic monad.  I agree that this is the wrong type of failure for this method.
2. Catchable exceptions.  I think the only catchable exceptions are currently the ones that induce backtracking,* which I think is wrong.
3. Anomalies (or uncatchable exceptions)

See, for example, https://github.com/coq/coq/issues/10094 and https://github.com/coq/coq/issues/10095, where the inability to catch an exception makes it significantly harder to implement a thing.

If you make a version of `Control.case` that can catch exceptions raised by `Control.throw` (or else a version of `Control.throw` whose exceptions can be caught by `Control.case`), then I'm happy to replace all of the `Control.zero`s here with `Control.throw`.

* For example:
```coq
Require Import Ltac2.Init.
Require Ltac2.Control.
Require Ltac2.Message.
Goal True.
  match Control.case (fun _ => Control.throw Not_found) with
  | Val a => ()
  | Err e => Message.print (Message.of_exn e)
  end.
  (* Error: Uncaught Ltac2 exception: Not_found *)
```

2019-05-23 01:14 UTC, JasonGross commented on user-contrib/Ltac2/Bool.v
> +(************************************************************************)
Is `dev/header.ml` supposed to only extend to 2018, not 2019?

2019-05-23 01:15 UTC, JasonGross commented on user-contrib/Ltac2/Bool.v
> +(************************************************************************)
In any case, I've updated the headers of the new files I added

2019-05-23 14:38 UTC, Zimmi48 commented on user-contrib/Ltac2/Bool.v
> +(************************************************************************)
We didn't update any header since 2019 :cry: But yes, it is supposed to extend.

2019-06-06 15:55 UTC, SkySkimmer commented on user-contrib/Ltac2/Option.v
> +Ltac2 lift (f : 'a -> 'b) (x : 'a option) := map f x.
What's the point of this alias?

2019-06-07 09:58 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Int.v
> +  match equal x y with
Wouldn't it be more efficient to match on "compare x y" here?

2019-06-08 08:49 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Int.v
> +  match equal x y with
Please ignore, I just learned myself that matching on integers is not yet supported in Ltac2.

2019-06-08 12:43 UTC, ppedrot commented on user-contrib/Ltac2/List.v
> +  | [] => Control.zero (Tactic_failure (Some (Message.of_string "hd")))
My take on that is that we should not reenact the exception hell of OCaml, and separate potential failure from invariant breakage via types. That is, a function that might rightfully "fail" should return options, while a function whose preconditions are violated should return a panic. In OCaml there is a pervasive confusion between these two situations, which leads to catastrophic semantics when trying to scale. (`Anomaly: Uncaught exception Not_found` might be the single most frequent anomaly raised by Coq for instance.)

There is nothing complicated in doing so, it's just a matter of sticking to a particular style. For instance, your examples could be given as pairs of functions, one to check you are in the right fragment, and one to extract the relevant date assuming the first one says it's OK.

In the case of this PR, `hd` should fail with a panic. It's your duty to ensure that the list is not empty beforehand, and if you don't know, then just use pattern-matching.

2019-06-13 15:58 UTC, MSoegtropIMC commented
@JasonGross: do you agree that most (or probably all) of the Control.zero should be replaced with Control.throw? I agree with @ppedrot that for things like an out of bounds access, a non backtrackable throw would probably help with debugging and getting things right. Also you supply option variants e.g. for hd in case one is not sure. In case you are busy right now, I could also propose a patch for your PR.

@ppedrot : are there any other points which keep this PR from merging? It is a bit hard to work with Ltac2 if basic stuff as defined here is missing.

2019-06-13 19:32 UTC, JasonGross commented
I am pretty busy, please do propose a patch and I will merge.  I am mostly sold by the reasoning ppedrot gave, and certainly sold enough to replace all the zeros with throws in this PR

2019-06-16 07:44 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Option.v
> +Ltac2 lift (f : 'a -> 'b) (x : 'a option) := map f x.
I would say the name lift is more common when it is partially applied to lift f to 'a option -> 'b option. The name map is more common when it is fully applied. I am usually not a fan of aliases but would say it makes sense in this case because it is more a coincidence that lift and map have the same implementation.

2019-06-16 07:59 UTC, MSoegtropIMC commented
@JasonGross : I took the freedom to directly push to your PR branch. This makes it easier for others to review my changes in parallel. See the commit message for the changes I did. I hope this is agreeable.

Note on Bool: I find it questionable to use the "b" extension since in Ltac2 there is no differentiation between Prop and bool. I would rather remove this (but didn't do so). The syntax is more like OCaml than like Coq so I would stick to names one would have chosen in OCaml (if these functions wouldn't be operators).

In list I removed the "b" aliases to various exist and for_all functions.

2019-06-17 16:13 UTC, Zimmi48 commented on user-contrib/Ltac2/Bool.v
> +(************************************************************************)
Note that there is #10320 now, so you could adapt this PR accordingly.

2019-06-17 16:34 UTC, MSoegtropIMC commented
@JasonGross : I take your 👍 as agreement to remove the "b" extensions in Bool.v. I think this would lead to a more regular naming since e.g. the comparison function in Int.v also don't have a "b". I will do this a separate commit.

2019-06-19 08:48 UTC, MSoegtropIMC commented
@ppedrot : would it be possible to merge this PR and later also my PRs (which depend on this)? In my view Ltac2 is very important for Coq and a standard library is very important for Ltac2. We shouldn't stall the good momentum we have right now.

I find @JasonGross approach to follow the API of the OCaml library very agreeable, because it will make it easier to port Ltac-2 to OCaml.

2019-06-19 08:54 UTC, ppedrot requested changes
I don't agree with the current scheme for failure handling. We should have only two variants, not four.
- A version that uses throw, with the default name (e.g. `hd`)
- A version that returns option, with the `_opt` suffix

Exporting backtrack in standard functions not meant for proof search is another recipe for explosive disaster (in particular as the default function), and default values contaminate the API.

2019-06-19 09:00 UTC, ppedrot commented
@MSoegtropIMC Instead, you should provide option combinators that turn them into backtracking failures and default values accordingly.

2019-06-19 09:45 UTC, MSoegtropIMC commented
@ppedrot : I agree with your comment - less functions and explicit backtracking with an option combinator will most likely help the user the get what (s)he wants. I think my Array.v PR already follows your advice (for array index bound errors it anyway makes no sense to backtrack) but I will review it again with this in mind.

@JasonGross : I will follow @ppedrot advice and reduce the number of options and add the combinators he suggested to Option.v. I hope you agree with this as well.

2019-06-19 09:54 UTC, MSoegtropIMC commented on user-contrib/Ltac2/List.v
> +
@ppedrot : I assume your comment also applies to find above. Here I could imagine that a backtracking `Control.zero Not_found` might sometimes be what people want, but I guess it is better to make the backtracking always explicit in this kind of library function. Unless I hear from you otherwise, I will change this as well.

2019-06-25 14:33 UTC, ppedrot approved these changes

2019-06-25 14:33 UTC, ppedrot commented
@MSoegtropIMC sorry for the late review, the request somewhat flew under my radar.

2019-06-25 14:36 UTC, merged

2019-07-25 06:44 UTC, MSoegtropIMC commented
@vbgl : would you mind merging this into 8.10? Ltac2 is unusable without such a mini library. The bad thing is that people would start to develop their own incompatible libraries and distribute them.

2019-07-25 06:49 UTC, MSoegtropIMC commented
@vbgl: I just saw that 8.10 has still separate ltac2, so this would get a bit tricky. If you want me to prepare a PR, please let me know.

2019-07-25 07:49 UTC, vbgl commented
There is no Ltac2 in 8.10 and the legacy repository for Ltac2 has been frozen. So I don’t understand any of your requests. Sorry.

2019-07-25 07:54 UTC, MSoegtropIMC commented
Yes, indeed it would get tricky. Well it is not that bad - since this PR didn't change anything on the ML side people can use the latest Ltac2 .v files and recompile them on their own (that's what I am doing when working with 8.10).

2019-07-25 08:01 UTC, Zimmi48 commented
FTR the reason the Ltac2 repository has been frozen is that his author won't maintain it, especially given that most changes to the ML side would require the corresponding changes in Coq's API. However, nothing would prevent us from unfreezing the repository, and let a developer (if one volunteers to do it) backport to v8.10 any Ltac2 change that can be (such as these library files), and then prepare a release.

2019-07-25 08:50 UTC, MSoegtropIMC commented
@Zimmi48 : I would be open to do that if @vbgl as release manager agrees that it makes sense. I think Ltac-2 is an important development which deserves some acceleration.

You know my opinion on Ltac-1: [Ltac-1](https://www.welt.de/kultur/plus185424296/Stil-und-Protest-Hier-bin-ich-signalisiert-die-gelbe-Weste.html#cs-Karl-Lagerfeld-posiert-mit-Neon-Weste-fuer-Verkehrssicherheit.jpg)

2019-07-25 09:18 UTC, vbgl commented
Ltac-2 is already in the CI for the 8.10 branch. If Michael volunteers to maintain the https://github.com/coq/ltac2 repository, it does make sense to unfreeze it, backport valuable contributions and make Ltac-2 for Coq 8.10 a useful plug-in.

2019-07-25 09:21 UTC, MSoegtropIMC commented
@vbgl : what is your time line for the 8.10 release?

2019-07-25 09:22 UTC, Zimmi48 commented
@MSoegtropIMC I have now unfrozen the repository and made you a collaborator. Note that even in the event that you were late for the 8.10.0 release, it would still make sense to update the v8.10 branch of Ltac2, produce a new release, and include it in the 8.10.1 Windows installer, so I would say no rush.

2019-07-25 09:34 UTC, MSoegtropIMC commented
@Zimmi48 : thanks! I will do a back port for 8.10 then.