Update pretyping to catch Not_found in empty env and evar_map
coq/coq pull request #10293
Opened 2019-06-03 15:51 UTC by tlringer

If you pass in an empty environment and `evar_map` and then intern something that Coq has already determined to be global, like `nat`, then the error that is raised at the top level is `Not_found`.

While obviously one should never pass an empty environment and `evar_map` to intern, in practice, plugins that call intern should not have to catch `Not_found` when they mess up. Currently, this means that if you define a command like `Cmd3` in [tuto1](https://github.com/coq/coq/tree/master/doc/plugin_tutorial/tuto1), if you call it on `a` you get a nice user error, but if you call it on `nat` you get `Not_found` (see [the comment in tuto1](https://github.com/coq/coq/blob/master/doc/plugin_tutorial/tuto1/src/g_tuto1.mlg) by @ybertot).

This fixes that so that it throws the same error for both `a` and `nat` without the plugin writer having to worry about catching `Not_found`.

2019-06-03 16:01 UTC, SkySkimmer commented
>plugins that call intern should not have to catch Not_found when they mess up

I think this is incorrect, the plugin is making a programming error so getting an anomaly is normal.

2019-06-03 16:02 UTC, tlringer commented
It makes no sense to a plugin developer though why they have to catch `Not_found` for only some variables (why for `nat` and not for `a`); the explanation is extremely technical.

2019-06-03 16:05 UTC, SkySkimmer commented
They should be passing a correct environment, not catching not_found.

2019-06-03 16:06 UTC, tlringer commented
Yes, but this comes up as an example in the tutorial plugin that Yves wrote, which is demonstrating what happens when you do the wrong thing.

At the least it should be consistent. If this is wrong, then intern itself should not be signalling a `user_err`. This just uses the same error for both.

2019-06-03 20:54 UTC, gares commented
Letting  Not_found escape a piece of code other than `find` is not good practice. This exception has an efficient implementation but is not informative enough and there is a concrete risk of catching the wrong one, since too much code can raise it.

Wrt the programming error, I think the right fix is to remove `empty` or put it in an `Unsafe` module since using it is always wrong (but for 1 call when creating the initial state of the system, that's not what a user plugin needs to do).

2019-06-04 07:12 UTC, tlringer commented
That makes sense to me. For just evar_map or also for environments?

I can try to make that change instead later today, but I anticipate it will break a lot of code and require a more major refactor.

2019-06-04 07:19 UTC, SkySkimmer commented
I guess we could produce an anomaly in lookup_constant/inductive, I don't think there's a use case for catching the not_found from them.

2019-06-04 07:30 UTC, gares commented
I think both `Environ.empty` and `Evd.empty` should be flagged as Unsafe.

> I guess we could produce an anomaly in lookup_constant/inductive, I don't think there's a use case for catching the not_found from them.

Last time I tried that I found out that some code expects that... :-/

2019-06-04 12:48 UTC, gares approved these changes

2019-06-04 12:48 UTC, SkySkimmer requested changes
If you are determined to catch the Not_found please turn it into an anomaly, not a user error.

2019-06-04 12:52 UTC, gares commented
I think @SkySkimmer is right, `CErrors.anomaly` is better here, since user_error can be catched by tactics while here we really face a programming errors.

2019-06-04 13:08 UTC, SkySkimmer commented
We may consider #10303 as an alternative.

2019-06-06 09:07 UTC, tlringer commented
@SkySkimmer that sounds good to me, and I've removed the relevant example, so I'm OK with that. But before I close this, do we have a consensus on moving the empty evar map and environment functions into unsafe? Is there an issue or a PR open for that already?

2019-06-17 15:48 UTC, closed without merging