Resolve 10342 : [Ltac2] Add array library
coq/coq pull request #10343
Opened 2019-06-08 13:07 UTC by MSoegtropIMC

This PR adds an array library for Ltac2.

I copied the Invalid_argument exception from PR #10219, so that it passes CI. I will remove it if 10219 is merged before.

The `mem` function is not compatible with the OCaml standard library, it requires an equality function since Ltac2 doesn't seem to have a generic equality functions. Otherwise it should be compatible except for names of low level functions.

I generally made the recursive low level functions global and generic in the sense that they can also be applied to parts of an array, in case someone needs this. In some cases this might lead to minor performance losses for handling both a current index and a length.

I have test cases for all high level function, but I am not sure where I would put these.

2019-06-08 14:47 UTC, gares commented on user-contrib/Ltac2/Array.v
> +      set dst posdst (get src possrc);
@ppedrot is `set` unsafe? (as in no boundary check?)

2019-06-08 15:04 UTC, ppedrot commented on user-contrib/Ltac2/Array.v
> +      set dst posdst (get src possrc);
Nope. It'll throw an out-of-bounds panic if misused.

2019-06-08 15:49 UTC, gares commented on user-contrib/Ltac2/Array.v
> +      set dst posdst (get src possrc);
The these functions shall not be called unsafe I guess

2019-06-08 20:58 UTC, ppedrot commented on user-contrib/Ltac2/Array.v
> +  | true => Control.throw (Invalid_argument (Some (Message.of_string "Array.init")))
You should define a helper function `invalid_argument : string -> 'a` for this sequence of compositions, it seems to be used quite a bit in the rest. It should probably live in `Init`.

2019-06-08 20:58 UTC, ppedrot commented on user-contrib/Ltac2/Array.v
> +Ltac2 make_matrix (sx : int) (sy : int) (v : 'a) :=
I don't think that this function makes sense. Already in OCaml it is quite dubious.

2019-06-08 20:58 UTC, ppedrot commented on user-contrib/Ltac2/Array.v
> +  match Int.equal l 0 with
So we're missing the `empty` function. It should be implemented before merging this PR, otherwise we'll get fancy behaviours as witnessed below.

2019-06-08 20:58 UTC, ppedrot commented on user-contrib/Ltac2/Array.v
> +Ltac2 concat (al : 'a array list) :=
IIRC the OCaml stdlib has a fast, C implementation for this. I guess we can just reflect the OCaml function in Ltac2, I'll do it with the addition of `empty`.

2019-06-08 21:01 UTC, ppedrot commented
> The mem function is not compatible with the OCaml standard library, it requires an equality function since Ltac2 doesn't seem to have a generic equality functions.

This is actually a defect of the OCaml API, at least according to me. We're struggling not to rely on the generic equality in OCaml, because it's a real can of worms. It breaks opacity invariants and can behave nonsensically sometimes (most notably for mutable data).

2019-06-09 08:08 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +  | true => Control.throw (Invalid_argument (Some (Message.of_string "Array.init")))
I though about having a function which includes the match on bool, so something like `assert_invalid_argument : bool -> string -> unit` which either throws when the first argument is false or does nothing when it is true. This would allow to have more specific tests and error messages without writing 20 lines of code. Some functions have longish orb chains which I would split in several tests with specific messages.

As is the error messages follow closely what OCaml does, but since debugging in OCaml might be nicer, it would make sense to have nicer error messages in Ltac2.

2019-06-09 08:09 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +Ltac2 make_matrix (sx : int) (sy : int) (v : 'a) :=
Removing it would be the only deviation from the OCaml library. I think it doesn't hurt to keep it and I might even have uses for it in automation for score tables.

2019-06-09 08:10 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +  match Int.equal l 0 with
I am looking forward to it :-)

2019-06-09 08:13 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +      set dst posdst (get src possrc);
It is a good question how checks should be handled - possibly I was following to much the OCaml library. The idea is that the "safe" functions give nicer error message at least mentioning the name of the function which failed. For the low level "unsafe" functions give less specific errors. The options are:

- leave all checks away and call the recursive helper functions _aux or _lowlevel. Performance wise this would be best and I don't know (yet) how helpful the additional error messages are.
- keep it as is with more specific error messages, possibly renaming the low level functions as suggested above.

2019-06-09 08:17 UTC, MSoegtropIMC commented
P.S.: CI fails because also the Bool library from #10219 is missing (I am using orb). I will wait until this is merged before I take care of CI, unless this would take a long time.

2019-06-13 15:23 UTC, MSoegtropIMC commented
I fixed the issues mentioned above. Most notably I added an empty, blit and fill function to Ltac2. This are all functions which iterate over the array and don't require an Ltac2 function as argument. The Ltac2 code has been adjusted to allow empty arrays and to use the new low level functions.

Note: CI still won't pass because I use the Bool and Int extensions from Jason's PR.

2019-06-25 14:36 UTC, ppedrot commented
@MSoegtropIMC can you rebase on a fresh master?

2019-06-26 16:52 UTC, MSoegtropIMC commented
@ejgallego : can you help me with the Azure Windows failure? It just says:
```
Cmd.exe exited with code '1'.
```
I am a bit lost ...

2019-06-26 16:56 UTC, SkySkimmer commented
> It just says:

at https://dev.azure.com/coq/coq/_build/results?buildId=3845&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3 I see
~~~
Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
At line:1 char:1
+ (New-Object Net.WebClient).DownloadFile('http://www.cygwin.com/setup- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
'setup-x86_64.exe' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
##[error]Cmd.exe exited with code '1'.
~~~
ie the cygwing download failed (probably a transient error)

2019-06-26 17:00 UTC, MSoegtropIMC commented
@SkySkimmer : thanks! I missed the tiny grayish "more information" link.

2019-06-26 17:13 UTC, MSoegtropIMC commented
@ppedrot : please review this already while I take care of the minor CI issues.

2019-07-02 10:21 UTC, ppedrot commented on user-contrib/Ltac2/Array.v
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
The API doesn't let you do that (yet) but this primitive shouldn't be a closure, it should return `'a array` directly as this is not a problematic value w.r.t. sharing. I'll write a preliminary patch to let you write this.

2019-07-06 12:27 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
> this primitive shouldn't be a closure, it should return `'a array` directly as this is not a problematic value w.r.t. sharing

I am not deep enough in OCaml internals to know if the "CA" in OCaml goes so far that arrays of different types can share the same binary object. Interesting to know that this is the case.

One more point: I am not sure if it is required to make empty a primitive. One should be able to construct an empty function from Array.init and a throw. Of cause one still might want to have it but I wonder why the OCaml library doesn't have an Array.empty function.

Would it be agreeable to add the string functions from my system function PR to this PR, that is:<https://github.com/coq/coq/pull/10370/commits/d67fce58ea66fffc47cd755f50a410ea7ce3be46>. I also need this at other places without system functions and I guess others might need this as well. I would add conversion in both directions then.

2019-07-06 12:29 UTC, SkySkimmer commented
ocaml has `[||]` to produce empty arrays

Gaëtan Gilbert

On 06/07/2019 14:27, MSoegtropIMC wrote:
> *@MSoegtropIMC* commented on this pull request.
> 
> ------------------------------------------------------------------------
> 
> In user-contrib/Ltac2/Array.v 
> <https://github.com/coq/coq/pull/10343#discussion_r300829861>:
> 
>>  
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
> 
>     this primitive shouldn't be a closure, it should return |'a array|
>     directly as this is not a problematic value w.r.t. sharing
> 
> I am not deep enough in OCaml internals to know if the "CA" in OCaml 
> goes so far that arrays of different types can share the same binary 
> object. Interesting to know that this is the case.
> 
> One more point: I am not sure if it is required to make empty a 
> primitive. One should be able to construct an empty function from 
> Array.init and a throw. Of cause one still might want to have it but I 
> wonder why the OCaml library doesn't have an Array.empty function.
> 
> Would it be agreeable to add the string functions from my system 
> function PR to this PR, that is:d67fce5 
> <https://github.com/coq/coq/commit/d67fce58ea66fffc47cd755f50a410ea7ce3be46>. 
> I also need this at other places without system functions and I guess 
> others might need this as well. I would add conversion in both 
> directions then.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/10343?email_source=notifications&email_token=AASZB3BFOTJLSBEDVEUXMKLP6CFUDA5CNFSM4HWHG6P2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5U3ZOY#discussion_r300829861>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AASZB3AWYBMRNRS7TI77EJTP6CFUDANCNFSM4HWHG6PQ>.
>

2019-07-06 12:34 UTC, ppedrot commented on user-contrib/Ltac2/Array.v
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
> One more point: I am not sure if it is required to make empty a primitive. One should be able to construct an empty function from Array.init and a throw.

No, you can't do that. If you throw inside init, you'll get an exception due to the call-by-value semantics.

2019-07-06 12:36 UTC, MSoegtropIMC commented
> ocaml has `[||]` to produce empty arrays

Good point - I was just looking at <https://caml.inria.fr/pub/docs/manual-ocaml/libref/Array.html> and forgot the built-in functionality. Can you think of other primitive/built-in array functionality in OCaml I missed?

2019-07-06 12:48 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
> No, you can't do that. If you throw inside init, you'll get an exception due to the call-by-value semantics.

I meant a thunked throw, so it it never gets called for an empty array. Actually this does work:
```
Require Import Ltac2.Init.
Require Import Ltac2.Message.
Require Import Ltac2.Array.

Ltac2 print2 m1 m2 := print (Message.concat m1 m2).
Ltac2 print3 m1 m2 m3 := print2 m1 (Message.concat m2 m3).

Ltac2 print_int_array a :=
  iteri (fun i x => print3 (of_int i) (of_string "=") (of_int x)) a.

Ltac2 myempty _ := init 0 (fun _ => (Control.throw_invalid_argument "myempty: internal")).

Goal True.
  let a := myempty () in print_int_array a.
  let a := append (myempty ()) (init 4 (fun i => (Int.add i 10))) in print_int_array a.
```

2019-07-06 12:49 UTC, SkySkimmer commented on user-contrib/Ltac2/Array.v
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
Look at the definition of init, it uses empty inside so all you did was define `myempty := empty`

2019-07-06 12:56 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
Ok, that was indeed silly - I forgot that `init` is not a primitive function.

2019-07-16 14:34 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
@silene : how shall we proceed here? For me as a user it is not so bad that empty is a function while it could be a value if Ltac2 would support that. A lack of standard array functions in general is much more of an issue for me. Maybe we can for the time being rename it to say `lowlevel_empty` to indicate that it is not intended to be used directly, or that people have to expect changes? If it has a name like this it would be no issue to search and replace `lowlevel_empty ()` with empty later.

2019-12-31 18:48 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +  | true => Control.throw (Invalid_argument (Some (Message.of_string "Array.init")))
I added already in #10219 a functions like Control.assert_valid_argument and use them throughout to give fine grain error messages.

2019-12-31 18:58 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +  match Int.equal l 0 with
I added the empty array function and fixed all the 0 cases.

2020-01-01 09:44 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +Ltac2 concat (al : 'a array list) :=
And indeed it is much simpler this way. I first though that I need some translation from Coq lists to OCaml lists, but apparently this is already built into Ltac2, so just these 3 lines:
```
let () = define1 "array_concat" (list block) begin fun l ->
  wrap (fun () -> v_blk 0 (Array.concat (List.map snd l)))
end
```
with the declaration
```
Ltac2 @external concat : ('a array) list -> 'a array := "ltac2" "array_concat".
```
do the trick - I like it ;-)

2020-01-01 10:19 UTC, MSoegtropIMC commented
@ppedrot : I made concat an OCaml function as you suggested and it works as expected. But I have to leave it to you to fix the empty function - as you said this requires some extension to the framework. Right now empty always produces an int array (not sure why int and not anythign else or an error). I hope you find some time for this after 8.11.

2020-01-01 10:31 UTC, MSoegtropIMC commented on user-contrib/Ltac2/Array.v
> +Ltac2 @external empty : unit -> 'a array := "ltac2" "array_empty".
> The API doesn't let you do that (yet) but this primitive shouldn't be a closure, it should return `'a array` directly as this is not a problematic value w.r.t. sharing. I'll write a preliminary patch to let you write this.

Ehmm sorry - I made a mistake in testing the empty function. Actually the empty function does what I would expect. See e.g. the following snippet:
```
Require Import Ltac2.Ltac2.
Import Ltac2.Message.
Import Ltac2.Array.

Ltac2 print2 m1 m2 := print (Message.concat m1 m2).
Ltac2 print3 m1 m2 m3 := print2 m1 (Message.concat m2 m3).

Ltac2 print_int_array a :=
  iteri (fun i x => print3 (of_int i) (of_string "=") (of_int x)) a.

Ltac2 of_bool b := match b with true=>of_string "true" | false=>of_string "false" end.

Ltac2 print_bool_array a :=
  iteri (fun i x => print3 (of_int i) (of_string "=") (of_bool x)) a.

Goal True.
  (* test empty with int *)
  let a := append (empty ()) (init 3 (fun i => (Int.add i 10))) in print_int_array a.
  let a := append (init 3 (fun i => (Int.add i 10))) (empty ()) in print_int_array a.

  (* test empty with bool *)
  let a := append (empty ()) (init 3 (fun i => (Int.ge i 2))) in print_bool_array a.
  let a := append (init 3 (fun i => (Int.ge i 2))) (empty ()) in print_bool_array a.

  (* test init with int *)
  let a := init 0 (fun i => (Int.add i 10)) in print_int_array a.
  let a := init 4 (fun i => (Int.add i 10)) in print_int_array a.

  (* test init with bool *)
  let a := init 0 (fun i => (Int.ge i 2)) in print_bool_array a.
  let a := init 4 (fun i => (Int.ge i 2)) in print_bool_array a.
```
So what does not work with the empty function - despite the fact that it shouldn't be a function but a value?

2020-01-29 14:59 UTC, ppedrot commented
@MSoegtropIMC can you rebase this on a recent master? In the end, I think this can be merged as-is and refined by further PRs.

2020-01-29 19:18 UTC, JasonGross submitted a review, later dismissed
I don't think making `user-contrib/Ltac2/tac2core.ml` executable (100644 → 100755) is correct...

2020-01-30 18:23 UTC, MSoegtropIMC commented
> I don't think making `user-contrib/Ltac2/tac2core.ml` executable (100644 → 100755) is correct...

Thanks! I fixed this and Array.v as well.

2020-01-30 18:40 UTC, MSoegtropIMC commented
@ppedrot : I also have a file with testcases. Should I add this to the commit and the Ltac make test or do you think this is not required?

2020-01-30 21:18 UTC, ppedrot commented
Tests are always better to ship with the corresponding feature.

2020-01-30 21:44 UTC, MSoegtropIMC commented
> Tests are always better to ship with the corresponding feature.

OK, I will add the test file tomorrow. Please wait with the merge.

2020-02-01 11:59 UTC, MSoegtropIMC commented
@ppedrot : I add test test-file, so ready t go.

You might want to leave a note in the user-contrib/ltac2 folder on where examples and test cases are. It is a bit odd that this is under user-contrib and the tests and examples are under test-suite/ltac2. @SkySkimmer explained to me on gitter why this is, but it is not obvious to users looking for the esamples.

2020-02-01 19:45 UTC, MSoegtropIMC commented
@ppedrot : the fiat crypto failure seems unrelated (it fails also for other PRs and some master commits, but not all). I fixed the filemode issues spotted by @JasonGross and also added a test file. So from my point of view this is good to go.

2020-02-02 17:47 UTC, ppedrot approved these changes

2020-02-04 09:34 UTC, ppedrot requested changes
@MSoegtropIMC sorry, I just realized that this PR is lacking a changelog. Can you add one please?

2020-02-07 14:10 UTC, MSoegtropIMC commented
> I just realized that this PR is lacking a changelog. Can you add one please?

I wonder into which folder under doc/chaneglog this should go. I was looking at #10219 but this doesn't have one either - should I create a change log for that as well?

2020-02-07 14:19 UTC, ppedrot commented
This should go in `05-tactic-language/`. Although the name is not pluralized, this doesn't read *Ltac1*.

2020-02-08 12:22 UTC, ppedrot approved these changes

2020-02-08 12:24 UTC, merged