Restore safety mechanisms on kernel names.
coq/coq pull request #1034
Opened 2017-09-08 14:49 UTC by silene

As it stands, even with the most recent OCaml compiler (4.05.0), a plugin
that uses only non-buggy non-malicious code can wreak havoc in the kernel
data structures. Until the time the compiler/linker actually enforces the
separation between mutable and immutable strings (at least by giving them
different types in .cmi files), these string copies are to stay.

2017-09-08 16:13 UTC, ppedrot commented
Just for the record, you can easily wreak havoc in kernel data structures using *only non-buggy non-malicious code* that is similar to this and that nobody seems to be concerned about. Just like that:

```
let mess_with_me c = match kind c with
| App (c, args) -> args.(0) <- mkProp
| _ -> c
```
So I don't know why we're afraid of mutable strings but not mutable arrays...

2017-09-08 16:31 UTC, silene commented
There is a difference though. The code you exhibit has always wreaked havoc in kernel data structures, so I have a hard time agreeing with you that it is non-buggy. On the other hand, the piece of code I am concerned about is part of an existing plugin, it has been working fine for 4 years now (in fact, the plugin still works with Coq 8.4), yet 8.7 breaks badly on it. You believe the fix belongs to the plugin; I don't.

2017-09-08 18:20 UTC, ejgallego requested changes
I think that `safe-string` is mandatory in Coq and its plugins and it should remain so given that at some point OCaml may make it too. Code/API/makefiles breaking the `safe-string` invariant should be fixed instead.

2017-09-08 18:42 UTC, silene commented
The unfortunate thing is that you don't even get a warning telling you there is an impedance mismatch. I tried to modify the `DECLARE_PLUGIN` macro to detect the issue at either compile time or execution time, but I didn't succeed in finding a way to achieve it. So until we get better support from the compiler to prevent this class of bugs, we have to keep the copies around. Why the hurry to remove them? They have always been there.

2017-09-08 19:02 UTC, ejgallego commented
I am afraid that without an example of the actual problem I cannot assess why the patch is needed.

`String.copy` is deprecated upstream, so your build will likely fail in Travis.

2017-09-08 19:25 UTC, gares commented
My impression is that we should provide 2 ways of building ids
- from bytes (we do the copy for obvious reasons)
- from strings (we still do the copy, without using deprecated API, i.e. going trough bytes)
When OCaml enforces strings immutability we remove to the copy from the latter constructor.

Then
- gappa is ported to use bytes intead of strings
- if possible, gappa stops mutating strings and is ported to immutable strings. If not, it can live with the byets API

Any problems with the approach I propose?

2017-09-08 19:26 UTC, gares commented
FTR, the same approach could be used if/when OCaml introduces immutable arrays.

2017-09-08 20:25 UTC, ejgallego commented
> Any problems with the approach I propose?

Yes, first, we already provide the API you propose. Second, `String.copy` is deprecated and not to be used anymore.

2017-09-08 20:29 UTC, ejgallego commented
Gappa should be compiled with `-safe-string` if it is to be used in 8.7. Indeed I agree that it is an OCaml bug that you can mix modules in this way.

2017-09-08 20:35 UTC, ppedrot commented
I'm not even sure that coq_makefile sets this flag. Ltac2 is bravely using the string type mutably, and uses coq_makefile, and nobody complains. We should probably fix it at least there.

2017-09-08 21:06 UTC, ejgallego commented
Indeed `coq_makefile` used to set the flag, unfortunately I think that the `coq_makefile` 2 merge undid that. It is a serious bug!

2017-09-08 21:17 UTC, ejgallego commented
Submitted #1039 to fix this problem.

2017-09-09 08:01 UTC, gares commented
> we already provide the API you propose

Oh, I did not know that.

Wrt the String.copy warning, can't one go `string -> byte -> copy -> string` to avoid it?

2017-09-09 10:30 UTC, silene commented
> Wrt the String.copy warning, can't one go `string -> byte -> copy -> string` to avoid it?

We can just use the `[@warning]` construct, as elsewhere in Coq's code base.

2017-09-09 10:41 UTC, silene commented
> gappa stops mutating strings and is ported to immutable strings. If not, it can live with the bytes API

You misunderstood the issue with the `gappa` tactic. It never calls the `id_of_string` API, since it does not need to create any new identifier. That is why the bug is so insidious! The simple fact of reading ids from the kernel was modifying them by side-effect. Fixing Gappa is the easy job, it is a one liner that is already done. What is so complicated is debugging the actual bug when it occurs.

2017-09-09 11:26 UTC, ejgallego commented
> Wrt the String.copy warning, can't one go string -> byte -> copy -> string to avoid it?

Yes, but I remain unconvinced that we want everyone to pay that price; the `coq_makefile` problem was indeed serious and a matter of life [hard to coordinate so many parallel changes]

I still didn't see/understand the actual problem with Gappa, so it remain hard to judge whether the blame is; @silene , could you point out to the one-liner in Gappa please ?

2017-09-11 13:29 UTC, silene commented
> could you point out to the one-liner in Gappa please ?

    let s = String.copy (string_of_id x) in

And since I am sure that you will loudly complain that I should not be using `String.copy`, let me remind you that I still support versions of OCaml that predates `Bytes`. (Yes, I do care about my users.)

2017-09-11 13:50 UTC, ejgallego commented
> let s = String.copy (string_of_id x) in

I guess that is the fixed version, right? So indeed the original code would have been correctly warned in Coq 8.7 if we hadn't had the `coq_makefile` bug. Thus, I propose to discard this PR.

I won't loudly complain that you should be using `Bytes`, neither I will get into a flamewar.

The `Bytes` stuff came from OCaml upstream, and it is what it is. String ain't going back to being mutable and we'll have to adapt, such is life.

2017-10-05 17:13 UTC, maximedenes commented
Since the `coq_makefile` fix was integrated, can I close this one?

2017-10-05 21:36 UTC, ejgallego commented
`-safe-string` is the default in OCaml 4.06.0 so IMHO indeed no point on going back.

2017-10-18 13:37 UTC, closed without merging