Kernel-side delaying of polymorphic opaque constants
coq/coq pull request #10362
Opened 2019-06-11 15:07 UTC by ppedrot

This PR allows for the kernel-side handling of delayed polymorphic opaque constants in a way similar to the monomorphic ones. It doesn't actually delay them in practice though, because this feature depends on the upper layers, but it provides the infrastructure to do so.

I had to move the private universe constraint code introduced by @SkySkimmer into the opaque proof mechanism. I don't find the API is not very elegant, but this will eventually be solved by cleaning up the interface between the proof declaration and the kernel, and in particular while implementing CEP 40.

The current code does make some invariants more explicit, at least.

2019-06-12 10:45 UTC, SkySkimmer approved these changes
Looks OK

2019-06-12 13:55 UTC, gares commented
I'm not familiar with the user facing syntax of universes, so bare with me if I'm saying something silly.
In particular I'd like to understand if this pattern matching
```ocaml
  | DefinitionEntry ({ const_entry_type = Some typ;
                       const_entry_opaque = true;
                        const_entry_universes = Polymorphic_entry (nas, uctx); _ } as c) ->
```
corresponds to a universe polymorphic term where the arity (wrt universes) is know, eg
```coq
Lemma foo@{i j k} : type. ... Qed.
```
And what about the eventual constraints `foo@{i j | ...}`?

2019-06-12 14:08 UTC, ppedrot commented
@gares in the current architecture, the universe arity is computed by the upper layers by forcing the term when the constraints are not fully specified. Thus, when an entry reaches the kernel this information is already known.

2019-06-12 14:17 UTC, SkySkimmer commented
>@gares in the current architecture, the universe arity is computed by the upper layers by forcing the term when the constraints are not fully specified.

Actually I think we always force in universe polymorphic mode, even if the user provided a fully strict universe_decl

2019-06-12 14:20 UTC, ppedrot commented
> Actually I think we always force in universe polymorphic mode, even if the user provided a fully strict universe_decl

True, but the goal is to ultimately get rid of this behaviour.

2019-06-13 16:05 UTC, gares commented
> is computed by the upper layers

My point is that the line I quoted should tell the kernel if typechecking can be delayed or not.
If I understand correctly what you say, then some of the fields of Polymorphic should become an option, and we do `DelayedPolymorphic` only if that field is `Some arity` (exactly as we check that the type is given , eg `Some typ` and that the proof is upaque, eg `..._opaque = true`). Then, if today it is always `Some arity` because the upper layers "forced" the proof term already an computed it, or if (tomorrow) don't force the proof but just use the `@{stuff}` annotations, is another story.

2019-06-13 16:08 UTC, SkySkimmer submitted a review, later dismissed
DelayedPolymorphic is a bad name. They're private universes in the sense that they cannot be observed outside the body. That this allows them to be delayed is a secondary consideration.

2019-06-14 06:57 UTC, ppedrot commented
@SkySkimmer Do you have an alternative proposal? I'd like to keep a symmetric name between both constructors.

2019-06-14 09:00 UTC, SkySkimmer commented
>@SkySkimmer Do you have an alternative proposal? I'd like to keep a symmetric name between both constructors.

They don't have symmetric uses though.

2019-06-14 10:01 UTC, ppedrot commented
> They don't have symmetric uses though.

Depends on the exact time you use them. The reason we store the monomorphic constraints in the opaque proof is a bad engineering one. As you can see, as soon as we store these proofs we drop the constraints, so that this effectively encodes an option type.

2019-06-14 10:19 UTC, ppedrot commented
@SkySkimmer following the naming in the previous code, what about `PrivateMonomorphic` / `PrivatePolymorphic`?

(Ultimately I think I'll merge this type with the Declarations.universes one by parameterizing the contents, but this requires more factorization first.)

2019-06-14 10:45 UTC, SkySkimmer commented
>@SkySkimmer following the naming in the previous code, what about PrivateMonomorphic / PrivatePolymorphic?

Sounds OK to me

2019-06-14 10:51 UTC, gares requested changes
Make it explicit, in the DefinitionEntry, which data is necessary in order to delay the type checking

2019-06-14 12:03 UTC, ppedrot commented
@gares I am afraid I do not understand your comment. Where do you want me to make this explicit, and do you mean by a human-readable comment or via typing?

2019-06-14 14:41 UTC, gares commented
In the data type of the entry, in the code I've quoted. I expect to see a pattern like `Some arity` (so that if it is `None` we don't `DelayedPolymorphic`)

2019-06-15 08:09 UTC, ppedrot commented
@gares An invariant that is enforced dynamically (and soon statically) is that opaque entries should always have an non-empty type. So in practice it is "enough" to be opaque to be delayed, but that is not quite true due to the fact that `Future.chain` is eager if the argument has been already forced. So, in the end, delaying is not decided by the kernel but by the upper layers.

(Note that the current situation is only temporary though, since I'm about to enforce many such properties via typing.)

Thus, I don't really think it is worth it documenting, since this is not the code that is actually responsible for the delaying feature.

2019-06-15 08:11 UTC, SkySkimmer approved these changes

2019-06-15 09:06 UTC, ppedrot commented
I feel like I am being unclear in my above explanation, so let me retell the plan.

- The kernel should not be in charge of delaying the typing after CEP 40 is implemented.
- In particular, we will separate the action of providing an opaque declaration and its body.
- This means that the kernel should not try to perform any kind of fancy inference, it should be given a fully annotated opaque definition, in particular with full (external) universe quantification, full section variable annotation, etc.
- Conversely, it is the role of the upper layer to compute this data whenever they're not provided by the user, effectively deciding whether to delegate or not.

In the current situation, part of the decision is taken by the upper layer, part of it by the kernel (i.e. `Future.chain` and section variable checking). I am removing the latter tiny bit by tiniy bit.

2019-06-15 13:10 UTC, gares approved these changes

2019-06-15 13:11 UTC, gares commented
OK then

2019-06-15 13:19 UTC, ppedrot commented
@SkySkimmer Do you want to assign?

2019-06-17 12:08 UTC, SkySkimmer commented
Funind conflicts ;)

2019-06-17 19:16 UTC, ppedrot commented
@SkySkimmer everything green.

2019-06-17 20:58 UTC, merged