Add a script for pinning third-party developments
coq/coq pull request #10371
Opened 2019-06-13 12:51 UTC by vbgl

The “pin-plugins.ml” program, to be called in its own directory, can be used at
release time to fix the references to third-party developments to their current
version; these developments are used in CI and in the Windows installer.

Ping @MSoegtropIMC

2019-06-13 12:59 UTC, ejgallego commented
Actually I'm not so sure we want to start adding this kind of crafty custom-build stuff for managing our repos; I'd rather favor a more principled approach that can integrate with overlay management.

I was looking into this set of tools as streamline my process but I didn't still have time to complete a full-fledged overlay management prototype:
  + https://github.com/mateodelnorte/meta
  + https://github.com/TankerHQ/tsrc
  + http://mixu.net/gr/
  + http://fabioz.github.io/mu-repo/

2019-06-13 13:02 UTC, ejgallego reviewed
Parsing this file back in this form doesn't seem like a good idea; IMHO we'd rather have a proper ML-based script for generating the shell version of the overlay file if needed by the shell.

2019-06-13 15:43 UTC, MSoegtropIMC commented
@vbgl : in case the head ref on the branch has a tag, would this script pick the tag or the ref hash? In case I picked the ref hash in the past, I always got - legitimate - review comments about this.

@ejgallego : I completely agree that long term we need a more proper solution, one which also feeds information to opam. But until we have this, I think we can be a bit pragmatic. This script is called only once every few months to automates something which takes manually one or two hours. It doesn't make that much sense to invest say one day into such a script if there is anyway an outlook to replace it with something much better. Worst case if the script doesn't work, one has to do it manually again.

2019-06-13 15:45 UTC, ejgallego commented
@MSoegtropIMC note that my review is not "blocking", however it would take almost the same effort to migrate the overlays file to OCaml and add a little printer.

2019-06-13 16:15 UTC, vbgl commented
>  in case the head ref on the branch has a tag, would this script pick the tag or the ref hash?

The script always picks the hash.

Not sure how to easily turn the hash into a human-readable tag name when
it exists…

2019-06-14 08:04 UTC, MSoegtropIMC commented
> note that my review is not "blocking", however it would take almost the same effort to migrate the overlays file to OCaml and add a little printer.

Ok, then we are aligned. It could be nicer, but since we long term want to have something else anyway, and as you also suggested should look into existing tools, it is acceptable as is.

But I would insist on a solution for the tags vs refs problem. Please let me know if you need support with this (since I want it, I am happy to do it).

2019-06-14 08:16 UTC, vbgl commented
I’ll give a try to the tags vs refs issue.

2019-06-14 11:45 UTC, MSoegtropIMC commented
I gave it a test run and got the below output, which shows that it picked only one tag. The 8.9.1 pick at <https://github.com/coq/coq/blob/v8.9/dev/ci/ci-basic-overlay.sh> has 15 tags. This difference is much larger than I expected. E.g. for VST I would have picked the tagged version 2.4 from April 23rd. My manual approach is more to prefer the latest tag. If this tag is rather old and/or does not build, I typically write an email to the author asking for her/his opinion on what to pick. Of cause this cannot be automated, but it is rare, typically one or two cases per release.

In general I think that people create tags for a reason and that we should respect this. Even with CI passing, master could be in the middle of some intermediate work. It is also nicer to say we have VST 2.4 rather than VST "some hash".

Of cause I am not the one to decide what policy to follow here. I just describe what policy I used so far.

```
sed -i \
-e "s/HoTT_CI_REF:=master/HoTT_CI_REF:=e91ddeb5d25f11ee23e4ad2ecbe384b01c9f412d/" \
-e "s/compcert_CI_REF:=master/compcert_CI_REF:=ddb2c968e6c57d2117434f169471d87f643d831a/" \
-e "s/verdi_raft_CI_REF:=master/verdi_raft_CI_REF:=3fc8d5223865e80e97d6f90ff39700f8977a1eae/" \
-e "s/lambdaRust_CI_REF:=master/lambdaRust_CI_REF:=8304869457a6453db081beb31aecfa194bc7048b/" \
-e "s/mathcomp_CI_REF:=master/mathcomp_CI_REF:=3df66cf26c7a50cfbfbb837659658e49010dde1d/" \
-e "s/quickchick_CI_REF:=master/quickchick_CI_REF:=9d3914b47aea20f7b97ac510903cd9d43fc4a2c1/" \
-e "s/simple_io_CI_REF:=master/simple_io_CI_REF:=533e02ed746eeb0e1600122c82ff62d8d776da60/" \
-e "s/aac_tactics_CI_REF:=master/aac_tactics_CI_REF:=4869852b949e4256310a484e8282779b5c607f2f/" \
-e "s/bignums_CI_REF:=master/bignums_CI_REF:=V8.10+beta1/" \
-e "s/struct_tact_CI_REF:=master/struct_tact_CI_REF:=4b9229f9678c7360d07a9e96318950800b369257/" \
-e "s/relation_algebra_CI_REF:=master/relation_algebra_CI_REF:=aaab2097f7da6f0909f01367e3abd77f87e0005b/" \
-e "s/fiat_crypto_legacy_CI_REF:=sp2019latest/fiat_crypto_legacy_CI_REF:=847b18bf8f38f7262331181f25ca96aee0423f52/" \
-e "s/vst_CI_REF:=master/vst_CI_REF:=2f92105372f16f2d021a13d6e9f7641a1bffb1b3/" \
-e "s/fcsl_pcm_CI_REF:=master/fcsl_pcm_CI_REF:=581d17078eb2e813cda3db42070b8d0c67beba53/" \
-e "s/cross_crypto_CI_REF:=master/cross_crypto_CI_REF:=ab65a8834528d677f8f59477a4e15d8ee4f2560e/" \
-e "s/verdi_CI_REF:=master/verdi_CI_REF:=163b9d0039ba6de2c72b77728136e45ba3f93623/" \
-e "s/Flocq_CI_REF:=master/Flocq_CI_REF:=3cba812be9541200ff1c353814b2011a2909bc4b/" \
-e "s/oddorder_CI_REF:=master/oddorder_CI_REF:=ca602a4638a9fe8ac30780095543d861f60fbfa0/" \
-e "s/fourcolor_CI_REF:=master/fourcolor_CI_REF:=0851d498d9a06ab81cf978494b6d41fbeb5f6631/" \
-e "s/ext_lib_CI_REF:=master/ext_lib_CI_REF:=f27a18a679b09b884f3ab63581c0048de9fa9089/" \
-e "s/tlc_CI_REF:=master/tlc_CI_REF:=6dc379c6c7a306be6b7ef1b3774bdb9ea2c94330/" \
-e "s/coq_dpdgraph_CI_REF:=coq-master/coq_dpdgraph_CI_REF:=879fbcd7e901e60d34e3bee05c6ae9c86cb3f32f/" \
-e "s/GeoCoq_CI_REF:=master/GeoCoq_CI_REF:=2b4cf1129fd566e14a64eaa651e941b90b1925e9/" \
-e "s/fiat_parsers_CI_REF:=master/fiat_parsers_CI_REF:=b8accbfda377ba82298ff7a279cbee5c2170aeda/" \
-e "s/Corn_CI_REF:=master/Corn_CI_REF:=db29aed4b2d378721715bfff258e59968207331f/" \
-e "s/equations_CI_REF:=master/equations_CI_REF:=b020ec613736de280554f84812b905bc7467be60/" \
-e "s/color_CI_REF:=master/color_CI_REF:=b6c9486a8a6379a5faad8f47afda3dc3f7fcbb15/" \
-e "s/inf_seq_ext_CI_REF:=master/inf_seq_ext_CI_REF:=dd91f4eb8be379bb1591fc565b376727ef97abe6/" \
-e "s/paramcoq_CI_REF:=master/paramcoq_CI_REF:=1aeb53dc6af9b17979a600bc91acacc321977444/" \
-e "s/coquelicot_CI_REF:=master/coquelicot_CI_REF:=b488d25b68759b0ede744079e574f09a339cc894/" \
-e "s/cheerios_CI_REF:=master/cheerios_CI_REF:=f512bfcb9c8d0b211a72b9f2b195ad46ced7df76/" \
-e "s/argosy_CI_REF:=master/argosy_CI_REF:=68674f1c36c812b088d4429792446d018dc27dc2/" \
-e "s/menhirlib_CI_REF:=master/menhirlib_CI_REF:=ca0655b2f96057a271fb5c9a254a38d195b4a7f9/" \
-e "s/unicoq_CI_REF:=master/unicoq_CI_REF:=1bfb474f11123f277722eaeaca1b28eaa4abb633/" \
-e "s/unimath_CI_REF:=master/unimath_CI_REF:=d1977361edf6b7719ebcecbb54289282e34c8aaf/" \
-e "s/coqhammer_CI_REF:=master/coqhammer_CI_REF:=64938440d0d1f4407ad10a5e6ddcd95cdbf5e833/" \
-e "s/elpi_CI_REF:=coq-master/elpi_CI_REF:=1c43ef1311f83d9b2499a4d6a22ba34dece9144f/" \
-e "s/fiat_crypto_CI_REF:=master/fiat_crypto_CI_REF:=8517e5f3afe079e7b42220088ca0c8e79e5e4343/" \
-e "s/math_classes_CI_REF:=master/math_classes_CI_REF:=4d19c6bf11739a7541c8c3afed871603d2b4395e/" \
../ci/ci-basic-overlay.sh

````

2019-06-14 12:15 UTC, vbgl commented
What I’ve implemented is the following: get the hash of the most recent commit on the given branch and use the tag associated with that commit if any. Of course, I don’t expect this strategy to pick many tags for the development version of Coq. However, we may expect more tags in the “v8.10” branch when plug-in developers release their work.

2019-06-14 12:41 UTC, MSoegtropIMC commented
I just tried it on the 8.10 branch and it also has only one tag (for bignums). It has more warning messages:
```
warning: redirecting to https://gitlab.mpi-sws.org/FP/LambdaRust-coq.git/
Warning: no head matching simple_io at https://github.com/Lysxia/coq-simple-io.
Warning: no head matching relation_algebra at https://github.com/damien-pous/relation-algebra.
warning: redirecting to https://gitlab.inria.fr/flocq/flocq.git/
warning: redirecting to https://scm.gforge.inria.fr/anonscm/git/tlc/tlc/
Warning: no head matching coq_dpdgraph at https://github.com/Karmaki/coq-dpdgraph.
Warning: no head matching equations at https://github.com/mattam82/Coq-Equations.
warning: redirecting to https://gitlab.inria.fr/coquelicot/coquelicot.git/
warning: redirecting to https://gitlab.inria.fr/fpottier/coq-menhirlib.git/
Warning: no head matching unicoq at https://github.com/unicoq/unicoq.
Warning: ignoring Iris.
Warning: no head matching coqhammer at https://github.com/lukaszcz/coqhammer.
Warning: ignoring stdpp.
```
The "Warning: no head matching" warnings to appear in master.

2019-06-14 12:45 UTC, vbgl commented
The text of the warning is a bit misleading, I agree. It shows up when said plug-in is already pinned.

2019-06-14 12:58 UTC, MSoegtropIMC commented
> The text of the warning is a bit misleading, I agree. It shows up when said plug-in is already pinned.

Ah, ok - makes sense.

How can we get forward here? Looking at the tag vs ref ratio we get, I think this method is not usable. I would suggest this method:

- pick the latest tag
- if this tag is older than say 90 days, pick the latest ref and issue a warning message.

2019-06-14 13:18 UTC, vbgl commented
What about urging plug-in developers to release for Coq 8.10? Little change is expected in their “8.10” branch after tagging.

2019-06-14 14:27 UTC, Zimmi48 commented
FTR longer term, the plan is to define an official "Coq platform" (or "Coq live distribution") and have a strict policy about release management to get in there. But before creating this policy, we need to be able to distribute this "Coq platform" for more than just Windows.

2019-06-14 15:28 UTC, MSoegtropIMC commented
> It is vain to try hard at picking tags if developers do not create the tags we need.

This doesn't match my experience. In 8.9.0 and 8.9.1 only 2 or 3 addons have been problematic. Did you check how many fail with the policy I suggested? If your tools picks the right think for everything except 2 addons, this would be good enough for me. The remaining stuff probably needs some human judgement anyway.

2019-06-14 15:31 UTC, MSoegtropIMC commented
P.S.: you might want to test your tool on 8.9.0 and 8.9.1 and compare your results with my manual picks. Also I can still do manual picks for 8.10 and we can develop a picking tool in parallel.

2019-11-29 16:06 UTC, JasonGross requested changes

2019-11-29 16:06 UTC, JasonGross commented on dev/tools/pin-plugins.ml
> +  Format.printf "sed -i \\@.";
```suggestion
  Format.printf "sed -i'' \\@."; (* use -i'' for compatibility with MacOS; see https://stackoverflow.com/a/7573438/377022 *)
```

2019-11-29 16:31 UTC, SkySkimmer commented
I think dynamically producing sh code is worse than the approach in #11214 of writing the code directly.

2020-01-19 21:01 UTC, SkySkimmer commented
Replaced by https://github.com/coq/coq/pull/11214

2020-01-19 21:02 UTC, closed without merging