[ci] [azure] python package is obsoleted by python2
coq/coq pull request #10466
Opened 2019-07-02 15:08 UTC by ejgallego

This should fix #10465

Let's see.

2019-07-02 15:25 UTC, Zimmi48 reviewed
Huh! We are not supposed to depend on python2, are we? @JasonGross?

2019-07-02 15:30 UTC, ejgallego commented
> Huh! We are not supposed to depend on python2, are we? @JasonGross?

Sure we do, check the nix file.

2019-07-02 15:33 UTC, Zimmi48 commented
The Nix file was never updated after we removed the dependency on python2 in #7990. I wanted to clean it and never did it, and I obviously should have if you are telling me that we accidentally reintroduced such a dependency. I would have never willingly merged a PR that did.

2019-07-02 15:35 UTC, SkySkimmer commented
The failure isn't caused by a dependency on python2, just look at the error message. I don't know why you think this would fix it.

2019-07-02 15:37 UTC, ejgallego commented
@Zimmi48 certainly #7790 seems bogus at various levels, as `/usr/bin/env python` is bound to python2 by default, for example in Ubuntu 19.04

2019-07-02 15:40 UTC, Zimmi48 commented
Please don't insult contributors' work for no reason. Nowadays, some distributions bind `python` to `python2` and others to `python3`. Using a generic shebang is just supposed to carry the meaning that you can use either because you made your script compatible, which is what this PR did.

2019-07-02 15:44 UTC, ejgallego commented
> Please don't insult contributors' work for no reason.

@Zimmi48 calm down I'm not insulting anyone, indeed the PR does look incorrect to me, for one, there are a few uses of `python2` in the codebase; I could be wrong of course, but there seem to be more problems. Using the generic shebang is also a serious problems these days [python experts tell me]

2019-07-02 15:46 UTC, ejgallego commented
p.s: [bogus -> incorrect] edited in my previous comment, "bogus" for me is a playful informal word but my apologies if anyone found it "insulting"

2019-07-02 15:57 UTC, ejgallego commented
> The failure isn't caused by a dependency on python2, just look at the error message. I don't know why you think this would fix it.

I'm not sure what you mean, but indeed this PR fixes the problem. Intended or not, we still depend on python2 , as least all the testing for these scripts has been done using python2 even after #7990

2019-07-02 15:58 UTC, SkySkimmer commented
>The failure isn't caused by a dependency on python2, just look at the error message. I don't know why you think this would fix it.

Apparently I was wrong. I have decreasingly less of a clue what's going on.

2019-07-02 15:59 UTC, ejgallego commented
> I have decreasingly less of a clue what's going on.

What happened is that cygwin deprecated the generic python alias, now you need to use python2, which is what we were using before. Of course it'd be great to complete #7990 and move everything to P3, but IMHO that should go in a different PR.

2019-07-02 16:00 UTC, Zimmi48 commented
I didn't say you insulted anyone but the *work* (that was done by an external contributor), by making false claims (or at the very least these less than convincing claims).

>Using the generic shebang is also a serious problems these days [python experts tell me]

If so, then the same would apply to using generic shell shebangs. It carries pretty much the same kind of meaning, and it has the same problems: we only test them with whatever shell is installed (probably bash). Anyway, if you really wanted to pin shebangs, then you should pin them to `python3`.

2019-07-02 16:01 UTC, Zimmi48 requested changes
>Of course it'd be great to complete #7990 and move everything to P3, but IMHO that should go in a different PR.

Where do you see any hint that this work needs anything more to be complete?

If you don't want to use the generic alias, that's fine, but then use `python3` everywhere, not `python2`.

2019-07-02 16:05 UTC, ejgallego commented
> Where do you see any hint that this work needs anything more to be complete?

That PR forgot to do 3 things:
- switch the docked image so the timing tests are run using python3 [they are run using python2 as of today]
- switch the azure image so the timing tests are run using python3 [they are run using python2 as of today]
- remove python2 from the nix files.

I disagree with your request for changes, what this PR does is to document what's being actually tested. Please update the shebangs in a different PR, thanks.

2019-07-02 16:06 UTC, ejgallego commented
> If so, then the same would apply to using generic shell shebangs

The situation with shell shebangs is quite different from the one with python shebangs, even tho you have people proposing to remove `/usr/bin/sh` as cygwin did with `/usr/bin/python`

2019-07-02 16:13 UTC, ejgallego commented
> I didn't say you insulted anyone but the _work_ (that was done by an external contributor), by making false claims (or at the very least these less than convincing claims).

IMVHO you are a bit off the line here, first, in a development / scientific context criticizing a work is not an insult, even if my critic turns out to be wrong. I am human and I do have the right to be wrong and I am actually wrong most of the time.

Also, I have a hard time following how who did the work is relevant if your comment was about the work itself.

About the claims, I'm unsure why they are not convincing, it seems to me that the 3 problems I pointed out above do hold, but I could be wrong of course.

2019-07-02 16:24 UTC, Zimmi48 commented
I'll stop debating on the question of criticizing the work, and accept that you have reasons to think it was incomplete.

However, I maintain my request for changes because changing the shebangs like you did is not just a matter of documenting the preexisting situation, it is a breaking change that means that suddenly all developers will need to have python2 installed in their machines, and typically I don't, and once #10467 is merged, I really won't, even within a `nix-shell` environment. And there is no reason why the fix you are proposing to the Windows testing infrastructure should affect the ability of merging #10467.

2019-07-02 17:25 UTC, ejgallego commented
Indeed that seems like a more sensible approach; updated. Test suite passes locally, let's see if the rest still works.

2019-07-02 17:47 UTC, ejgallego commented
Some confusion here came from the fact than in the debian world, python is always python2 TTBOMK.

2019-07-02 22:29 UTC, ejgallego commented
So `update-compat.sh` is broken in linux for python3, I see no other short-term option than reverting the python3 removal for that script.

2019-07-02 23:33 UTC, ejgallego commented
> So `update-compat.sh` is broken in linux for python3, I see no other short-term option than reverting the python3 removal for that script.

Ok, that seems to have worked, @Zimmi48 is that tradeoff acceptable to you?

2019-07-03 07:15 UTC, SkySkimmer commented
>So update-compat.sh is broken in linux for python3, I see no other short-term option than reverting the python3 removal for that script.

Do you know why it works in https://github.com/coq/coq/pull/10467 ?

2019-07-03 10:33 UTC, ejgallego commented
> Do you know why it works in #10467 ?

I have no idea, likely differences with env locale variables?

2019-07-03 12:51 UTC, Zimmi48 commented
I'd like to get the help of @JasonGross to understand what's going on. In the meantime, I propose an alternative temporary fix which is to create a symlink `python` to `python2` in Azure to mimic what cygwin doesn't do anymore. Even assuming that it is indeed recommended today in the Python world to always use `python2` or `python3` (and I kind of doubt that this is consensual), I think it was probably a bad move from Cygwin to remove `python` entirely, and it has probably broken lots of software.

2019-07-03 12:55 UTC, SkySkimmer commented
They didn't just change it to point to python3?

2019-07-03 12:56 UTC, ejgallego commented
> I propose an alternative temporary fix which is to create a symlink `python` to `python2` in Azure to mimic what cygwin doesn't do anymore.

What's the point of that? Shouldn't we instead document the actual status-quo w.r.t. testing?

The script is run in python2 not only in Azure, but in the Docker containers.

IMHO this PR should not fix the Python code, it is just improving what was an underspecification in the CI that created many problems, and fixing our CI system.

Already we are changing the python version for the timing scripts at your request, thing which I am pretty uncomfortable to do as this should be done by Python people not by accident by me.

2019-07-03 12:57 UTC, ejgallego commented
> They didn't just change it to point to python3?

I dunno, but I am pretty certain that we don't want to do that kind of hack and create more problems.

2019-07-03 13:16 UTC, ejgallego commented
> What's the point of that?

Oh I see, python2 is not more on Nix. I insisted that such removal was premature as there were at least 4 scripts being tested on python2. We were lucky in that we only discovered problems in one of them.

As of now, this PR + reverting #10467 is the right thing to do.

2019-07-03 13:43 UTC, ejgallego commented
Anyways folks IMHO we should not get very entangled in trying to solve this issue. Let me propose a plan of action that should hopefully solve the situation.

## Current situation

We have a discrepancy on the python version used for running scripts that declare a "generic" `/usr/bin/python` shebang:
- in Nix they were tested using python3
- in Docker images and Azure they were tested using python2
- the `update-compat.py` python script doesn't work with python3 in Docker

## Analysis

Using the generic shebang seems like a bad idea, particularly as some environments have deprecated it.

## Plan of action

1. make all scripts use a versioned shebang.
2. make all the environments install python2 and python3
3. solve the remaining problem with `update-compat.sh`, remove python2 from envs

Steps 1 and 2 could be done in this PR, step 3 would be its own PR, by the Python maintainers.

WDYT?

2019-07-03 16:40 UTC, Zimmi48 commented
Since the only urgency is to fix the failing Windows test, I don't get what you have against my proposal as *a temporary solution*. Again, I would view pinning to python2 as a regression. So this proposed solution avoids this issue and give some time to knowledgeable people to understand and fix the underlying issue. I don't see why some unreasonable decision from the Cygwin maintainers should have any impact on our Linux users/developers.

2019-07-03 17:08 UTC, ejgallego commented
> I don't get what you have against my proposal as _a temporary solution_.

I think that your proposal has many drawbacks, including doing a non-supported hack that we don't know what would it break. Moreover, we don't gain a lot by avoiding the pinning, as this is the status-quo on master.

> Again, I would view pinning to python2 as a regression.

I fail to see why is a regression, as testing is done today already with python2, and #10467 was merged without taking into consideration CI.


> So this proposed solution avoids this issue and give some time to knowledgeable people to understand and fix the underlying issue.

So does mine, without doing any hack.

> I don't see why some unreasonable decision from the Cygwin maintainers should have any impact on our Linux users/developers.

IMO we have no choice other than go with that. I don't get what impact my proposal would have on Linux users / developers, I see it as zero impact, however maintaining the current undefined behavior does have a negative impact.

2019-07-03 18:43 UTC, JasonGross commented
I think I'm with @ejgallego on this one, given that the only script we're pinning to python2 is the update-compat script, which apparently does not work with python3, which means that developers without python2 already cannot run it, and so pinning it to python2 does not seem to me to be a breaking change.

As for why it doesn't work with python3, I'm not sure, and I don't have time to dig into it right now.  What's the error message?  Is the issue Unicode characters / bytes?

2019-07-03 22:25 UTC, ejgallego commented
> Is the issue Unicode characters / bytes?

Looks like it @JasonGross , for some reason it only failed on Linux / Ubuntu.

2019-07-03 23:36 UTC, ejgallego commented
Here's the log @JasonGross 
```
Traceback (most recent call last):
  File "dev/tools/update-compat.py", line 481, in <module>
    update_compat_notations(known_versions, new_versions, **args)
  File "dev/tools/update-compat.py", line 413, in update_compat_notations
    with open(os.path.join(root, fname), 'r') as f: contents = f.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1390: ordinal not in range(128)
==========> FAILURE <==========
    tools/update-compat/run.sh...Error!
```
https://gitlab.com/coq/coq/-/jobs/244148789/artifacts/browse/test-suite/logs/tools/

2019-07-04 08:10 UTC, vbgl commented
Is the `update-compate.py` python2 program run at some point in CI?

2019-07-04 08:22 UTC, ejgallego commented
> Is the `update-compate.py` python2 program run at some point in CI?

Yes.

2019-07-04 08:30 UTC, vbgl commented
When?

2019-07-04 08:33 UTC, ejgallego commented
> When?

IIRC the test suite has a test for it.

2019-07-04 08:37 UTC, vbgl commented
Then how come that job succeeded: https://gitlab.com/coq/coq/-/jobs/244075110? The log shows the following lines:

> TEST      tools/update-compat
> …
> NO FAILURES

There was no python2 available there…

2019-07-04 08:41 UTC, ejgallego commented
> There was no python2 available there…

I have no idea what the Nix setup is, in Debian it does fail, as pointed out above.

2019-07-04 09:01 UTC, vbgl commented
> I have no idea what the Nix setup is

Therefore, why do you try to mess up with it in this PR?

2019-07-04 09:01 UTC, ejgallego commented
The thing is that I don't see a big problem in pinning python2 for while more, while the remaining script and the missing test suite entry are fixed.

2019-07-04 09:02 UTC, ejgallego commented
> Therefore, why do you try to mess up with it in this PR?

Because the guilty script now explicitly uses a /usr/bin/python2 shebang.

2019-07-04 09:04 UTC, ejgallego commented
So it seems more sensible to me document the status quo by always using versioned shebangs, then fix the script later. The other choice is fixing the script first then pinning to python3 only.

2019-07-04 09:16 UTC, ejgallego commented
Real underlying problem here tho is that the windows CI infrastructure is setup in a non reproducible way, but that's a big task to tackle I'm much afraid.

2019-07-04 09:29 UTC, Zimmi48 commented
The difference could also have to do with the version of Python3. In Nix, it is 3.7.3. According to https://packages.ubuntu.com/bionic/python3, the version on our Ubuntu Docker image is 3.6.5. Maybe this version has a bug...

2019-07-05 11:25 UTC, ejgallego commented
> Maybe this version has a bug...

Could be, I dunno, I'm not a Python expert.

Anyways IMHO it is time to process this, given that @JasonGross agrees in that pinning python2 is a better overall strategy, can we proceed to merge?

2019-07-05 13:52 UTC, Zimmi48 commented
I'm still not convinced that this is the right way to proceed, but I will let @vbgl decide.

2019-07-05 13:55 UTC, ejgallego commented
> I'm still not convinced that this is the right way to proceed

Why? Théo I don't understand where you see the problem, maybe I'm missing something, care to explain more?

2019-07-05 13:55 UTC, ejgallego commented
Chat on Gitter?

2019-07-05 16:04 UTC, Zimmi48 approved these changes
Following this PR, we won't any longer accept scripts with generic python shebangs. This is the only way to ensure that we don't accidentally reintroduce a dependency on Python2. And I hope we can upgrade the update script to Python3 sooner than later.

Reminder: the Python2 clock is ticking https://pythonclock.org/

2019-07-06 00:18 UTC, ejgallego commented
Thanks to all, PR title and commit message updated. Hopefully this should be good until we can fix #10491

2019-07-06 09:47 UTC, ejgallego commented
@SkySkimmer can you assign? Thanks!

2019-07-06 09:49 UTC, SkySkimmer commented on default.nix
> +    python2 # update-compat.sh
Isn't it .py?

2019-07-06 09:50 UTC, ejgallego commented on default.nix
> +    python2 # update-compat.sh
Yup.

2019-07-08 10:32 UTC, ejgallego commented
@SkySkimmer this is ready to go.

2019-07-08 11:02 UTC, merged

2019-07-08 11:08 UTC, ejgallego commented
Merci !