[dune] More to Dune 1.10, use coqpp directive.
coq/coq pull request #10515
Opened 2019-07-14 17:43 UTC by ejgallego

We use the `(coqpp ...)` dune directive which will produce correct
error messages for `.mlg` files.

Unfortunately we cannot yet use the automatic opam generation features
of Dune 1.10, as this does require a fully native Dune build.

2019-07-15 18:14 UTC, Zimmi48 requested changes
Here is the diff to apply to update `default.nix` to use the dune build:

```diff
diff --git a/dev/nixpkgs.nix b/dev/nixpkgs.nix
index 8dfe1e7833..8736c0f9b8 100644
--- a/dev/nixpkgs.nix
+++ b/dev/nixpkgs.nix
@@ -1,4 +1,4 @@
 import (fetchTarball {
-  url = "https://github.com/NixOS/nixpkgs/archive/bc9df0f66110039e495b6debe3a6cda4a1bb0fed.tar.gz";
-  sha256 = "0y2w259j0vqiwjhjvlbsaqnp1nl2zwz6sbwwhkrqn7k7fmhmxnq1";
+  url = "https://github.com/NixOS/nixpkgs/archive/31c38894c90429c9554eab1b416e59e3b6e054df.tar.gz";
+  sha256 = "1fv14rj5zslzm14ak4lvwqix94gm18h28376h4hsmrqqpnfqwsdw";
 })
```

2019-07-15 18:14 UTC, Zimmi48 commented on dune-project
> +; We cannot set this to true until the build is not bootstrapped
```suggestion
; We cannot set this to true so long as the build is not bootstrapped
```

or

```suggestion
; We cannot set this to true until the build is bootstrapped
```

2019-08-22 00:36 UTC, ejgallego commented on dune-project
> +; We cannot set this to true until the build is not bootstrapped
Merci.

2019-08-22 07:08 UTC, vbgl approved these changes
The nix-related change is fine.

2019-08-22 08:58 UTC, Zimmi48 approved these changes
Great!

2019-08-22 16:24 UTC, Zimmi48 commented
Sorry, I had merged this, but forgot to push.

2019-08-22 16:25 UTC, merged

2019-08-22 16:27 UTC, ejgallego commented
Thanks, note that this PR may require indeed cleaning of old dune files :S when crossing its boundaries.

There is no easy way to avoid that I'm afraid, as we don't version the generated dune files.