Print canonical projections as soon as they are registered
coq/coq pull request #10747
Opened 2019-09-11 03:50 UTC by pi8027

To see how canonical projections work and which head symbols they involve, we needed to use `Print Canonical Projections` even if it is just after declaring a new projection. When we do advanced canonical structure programming, we needed to find a projection from hundreds of canonical projections printed. Therefore, printing new canonical projections immediately by `Canonical` command would help us a lot to understand how they work and to find wrong canonical projections as soon as they are declared.

**Kind:** feature.

- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

2019-09-11 08:38 UTC, ejgallego commented on pretyping/recordops.ml
>  let register_canonical_structure ~warn env sigma o =
Indeed that's the wrong place to add this print statement.

2019-09-11 08:41 UTC, ejgallego submitted a review, later dismissed
I don't think the core of Coq should be noisy by default, in particular printing what amounts to debug information. If a user needs to see info they can always call the corresponding `Print` command, hover on the UI, etc...

2019-09-11 13:26 UTC, pi8027 commented on pretyping/recordops.ml
>  let register_canonical_structure ~warn env sigma o =
Yes. I didn't expect this behavior when I start this.

2019-09-11 13:32 UTC, pi8027 commented
@ejgallego So could we have a new option to control this verbosity, or change the `About` command to print canonical projections associated with the given constant? (But `object_table` in `recordops.ml` isn't designed in this way so now I don't see how to do it.)

2019-09-11 13:34 UTC, SkySkimmer commented
We can always add a table if it's useful

Gaëtan Gilbert

On 11/09/2019 15:32, Kazuhiko Sakaguchi wrote:
> @ejgallego <https://github.com/ejgallego> So could we have a new option 
> to control this verbosity, or change the |About| command to print 
> canonical projections associated with the given constant? (But 
> |object_table| in |recordops.ml| isn't designed in this way so now I 
> don't see how to do it.)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/10747?email_source=notifications&email_token=AASZB3AXBKSXMD7Q3DLZM6LQJDXQHA5CNFSM4IVO5EM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6OPZWY#issuecomment-530382043>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AASZB3D7TO73R32JNE22AV3QJDXQHANCNFSM4IVO5EMQ>.
>

2019-09-11 14:15 UTC, ejgallego commented
Yeah improving the table/`About` command seems right.

2019-09-11 14:17 UTC, pi8027 commented
@SkySkimmer @ejgallego I will do so. Thanks!

2019-09-23 15:00 UTC, pi8027 commented
I have almost finished the implementation, but I'm still not sure about my design. I will discuss with someone to make sure of it. (Maybe I need to change `Print Canonical Projection` to take a constant optionally rather than changing the `About` command.)

2019-12-15 09:17 UTC, pi8027 commented
Since I have no idea on how this should work with PR #10984 (declaring multiple instances at once), I would like to have comments from @gares and @CohenCyril.

2019-12-15 16:53 UTC, gares commented
If you want to scale this to the other pr you should make the other pr keep a link between what the user wrote and the derived cs instances I'm afraid.

2019-12-16 20:02 UTC, pi8027 commented
So IIUC, I should extend the object table ‘obj_typ’ with a gref. Using ‘o_DEF’ for this purpose seems to be a bad idea anyway.

2019-12-17 08:13 UTC, gares commented
Maybe o_ORIGIN : gref option. But you should not wait for the other pr, this change morally belongs to the other one.

2019-12-18 14:40 UTC, pi8027 commented
@gares Since I didn't see why you prefer `option`, I put `o_ORIGIN : Constant.t`.

2019-12-18 17:26 UTC, gares commented
It is OK.

I was proposing option because for regular CS you have o_DEF = o_ORIGIN, and you have != for multiple CS. With option you could have None for the first case, and (Some origin) for the second.
Your code tests for equality, while it could match on the option... not very different.

2019-12-22 16:17 UTC, herbelin commented
Looks relevant and very good to me. (But I must confess that I did not understand @ejgallego's objection about noisiness. Isn't the PR only allowing to reduce the verbosity of the `Print Canonical Projections` query?)

2019-12-23 01:17 UTC, ejgallego commented
> But I must confess that I did not understand @ejgallego's objection about noisiness. Isn't the PR only allowing to reduce the verbosity of the `Print Canonical Projections` query?

My comment was referring to the original proposal of print the projections after each `Canonical` commands, I think the current proposal doesn't do that so my review can be disregarded.

2019-12-23 09:11 UTC, pi8027 commented
@ejgallego @herbelin Yes. I changed the design of this feature twice. Old implementations were discarded but they can be seen in the changes of the title.

I have just added a comment and rebased again. I think this is ready to merge if CI succeeds.

2019-12-27 09:47 UTC, CohenCyril requested changes
The feature, documentation and test suite together with its output all look good and useful to me.
The ocaml code is clean enough for me to read and understand.

I am all in favor of merging up to the small remark I am making, and then as soon as it passes CI.

2019-12-27 09:47 UTC, CohenCyril commented on doc/sphinx/language/gallina-extensions.rst
> +   synthesized from given constants will be shown.
I suggest the following
```suggestion
   synthesized from simultaneously all given constants will be shown.
```
to disambiguate that all constraints must be satisfied and not at least one.

2019-12-27 11:23 UTC, gares commented
@pi8027 if you rebase and implement the fix requested by Cyril I'll happily merge (CI failure is unrelated)

2019-12-27 17:16 UTC, pi8027 commented
@gares Done.

2019-12-27 21:50 UTC, CohenCyril approved these changes

2019-12-28 01:20 UTC, ejgallego approved these changes

2019-12-28 08:48 UTC, merged