[aux files] Remove dot from aux files.
coq/coq pull request #10767
Opened 2019-09-19 09:26 UTC by ejgallego

It seems to me that the convention for such kind of files is not to
have a dot, `.glob` files don't, and OCaml's helper files neither.

2019-09-19 10:54 UTC, Zimmi48 commented
cc @JasonGross as I think he is a user of `.aux` files.

2019-09-19 11:05 UTC, gares commented
I think it would make more sense to add the leading . to glob files, since they are of no interest to the user, but only accessed by the tools. Note that also .coq-native/ has a leading do, for the very same reason.

It would be even better to have that piece of info inside the .vo, but this is surely harder to do.

2019-09-19 11:05 UTC, gares requested changes
don't do that

2019-09-19 11:27 UTC, ejgallego commented
> I think it would make more sense to add the leading . to glob files, since they are of no interest to the user, but only accessed by the tools. Note that also .coq-native/ has a leading do, for the very same reason.

Umm, if you follow this reasoning then `.vo` files should also get a dot, as they are of no interest to the user either. Anyways the build system should not place object files in the same directory where source files are.

I am still supporting this change, standard practice on most compilers I know is that object files are not prefixed by dot, so I don't see why Coq has to be different.

2019-09-19 11:58 UTC, Zimmi48 commented
I am also not very fond of a change that is made only for the purpose of uniformity with standard practice, if no additional benefits are expected from it. I also don't think it is even worth having a debate over it.

2019-09-19 11:59 UTC, SkySkimmer commented
I think the idea is that .aux survive make clean so they're special. eg you don't `rm *` them.

2019-09-19 12:59 UTC, JasonGross commented
I don't think I use .aux files (though maybe if they contain the Proof using information I should make a tool that can read them to update Proof to Proof using).  By bug minimizer makes essential use of the .glob files, though, to fully qualify Requires.

2019-09-19 13:24 UTC, ejgallego commented
> I think the idea is that .aux survive make clean so they're special. eg you don't `rm *` them.

Maybe, I am not very familiar with the supposed workings; but this scheme seems quite fragile to me, what's the motivation to do `make clean` if you want to have an incremental build.

@Zimmi48 indeed only benefit is uniformity, so all object files can be found by `Foo.*`, whether that's important or not I dunno. I tend to value it.

2019-09-19 13:41 UTC, gares commented
Right, dune will put these file in the _build folder, so we won't see them anyway. Who cares how they are named. This change can only break third party script for no gain in the long term.

2019-10-12 15:36 UTC, tchajed commented
Please don't do this, it breaks current gitignores, and also user scripts as @gares pointed out.

Also, it adds even more cruft to `ls` over Coq sources (which may eventually be fixed by switching to dune, but in the short term and for projects not using dune will be a problem).

2019-10-13 17:49 UTC, ejgallego commented
@tchajed what user scripts do use `.aux` files? AFAICT they are for Coq internal use only.

2019-10-13 17:49 UTC, closed without merging

2019-10-13 17:53 UTC, tchajed commented
I was thinking of trivial but pervasive things, like my `make clean` code would break, not programs that actually need the contents of the `.aux` files.