CI: remove VST
coq/coq pull request #10799
Opened 2019-09-28 15:38 UTC by SkySkimmer

I propose we remove VST until and unless their upstream has some CI to
prevent breaking from their side.

2019-10-03 09:17 UTC, maximedenes requested changes
Please discuss it with them first.

2019-10-06 18:40 UTC, ejgallego requested changes
Indeed this needs to be discussed with them, them using Travis made it difficult to test master, but Docker should alleviate that.

2019-10-07 08:42 UTC, Zimmi48 commented
FTR, the concern they expressed at the time was not how to test master but how to debug in case CI does catch an incompatibility. Cf. https://github.com/PrincetonUniversity/VST/issues/161.

2019-10-11 11:39 UTC, closed without merging

2019-10-11 11:39 UTC, SkySkimmer commented
Don't have time for this.