[ide] Avoid duplicate error printing (BZ#5583)
coq/coq pull request #1090
Opened 2017-09-24 14:01 UTC by ejgallego

See the discussion in the bug tracker, basically the STM delays the
feedback error message to a point where CoqIDE has forgotten about the
sentence, thus we were processing such errors in the generic case,
printing them twice as the Fail case will also do it.

We could indeed revert back to the 8.6 strategy for error (print
always from Fail and ignore Feedback), however I feel that time will
be better spent by fixing the STM than adding more CoqIDE workarounds.

2017-09-25 18:54 UTC, psteckler commented on ide/coqOps.ml
> +          log_pp Pp.(str "Msg without a sentence " ++ msg);
Should the wording be "without *a* sentence" for both lines 485 and 487?

2017-09-29 08:50 UTC, gares requested changes

2017-09-29 08:50 UTC, gares commented on ide/coqOps.ml
> +          log_pp Pp.(str "Error Msg without sentence" ++ msg)
add `a `

2017-09-29 09:47 UTC, ejgallego commented
Fixed, thanks guys!

2017-10-01 20:25 UTC, gares approved these changes

2017-10-03 13:30 UTC, merged