Fix flambda instructions (tentative)
coq/coq pull request #10975
Opened 2019-10-27 03:17 UTC by Blaisorblade

**Kind:** documentation / performance.

Apparently, `-native-compiler no` might be needed to actually get the speedup, based on [forum discussion](https://coq.discourse.group/t/does-flambda-slow-down-coq/484/6?u=blaisorblade).
However, I still don't understand why that'd happen, according to the documentation I found.

2019-10-28 14:43 UTC, ejgallego requested changes
I don't follow the rationale here, nor the performance numbers, it is expected that compiling Coq with native compute and flambda is slower. We are not worried about how long it does take Coq to compile, if we use an optimizing compiler it is normal that we are slower.

FLambda works fine with native compute, so we should not disable it.

2019-10-28 15:37 UTC, Blaisorblade commented
> I don't follow the rationale here, nor the performance numbers, it is expected that compiling Coq with native compute and flambda is slower. We are not worried about how long it does take Coq to compile, if we use an optimizing compiler it is normal that we are slower.

We haven't measured compiling Coq itself (which is expected to be slower). We have measured running Coq, and in our case Coq + flambda + enabled native-compute is slower than plain Coq, which is slower than Coq + flambda + disabled native-compute, at least in our experiment on Mac.

Thanks for clarifying that's not supposed to happen. In this case, it'd be great to confirm and diagnose the bug, fix it, and document here instead which versions are affected.

2019-10-28 15:40 UTC, SkySkimmer commented
What about Coq with native compute disabled and no flambda?

Gaëtan Gilbert

On 28/10/2019 16:37, Paolo G. Giarrusso wrote:
>     I don't follow the rationale here, nor the performance numbers, it
>     is expected that compiling Coq with native compute and flambda is
>     slower. We are not worried about how long it does take Coq to
>     compile, if we use an optimizing compiler it is normal that we are
>     slower.
> 
> We haven't measured compiling Coq itself (which is expected to be 
> slower). We have measured running Coq, and in our case Coq + flambda + 
> enabled native-compute is slower than plain Coq, which is slower than 
> Coq + flambda + disabled native-compute, at least in our experiment on Mac.
> 
> Thanks for clarifying that's not supposed to happen. In this case, it'd 
> be great to confirm and diagnose the bug, fix it, and document here 
> instead which versions are affected.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/10975?email_source=notifications&email_token=AASZB3GL6MAYJUUJG46ZDATQQ4BMDA5CNFSM4JFP2UPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECNKISQ#issuecomment-547005514>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AASZB3CRXFGKM37OERWBT5DQQ4BMDANCNFSM4JFP2UPA>.
>

2019-10-28 15:45 UTC, ejgallego commented
I see, thanks @Blaisorblade ; I am having a look myself to the stdpp build.

2019-10-28 19:17 UTC, ejgallego commented
Using 4.07.1 I cannot reproduce any slowdown, maybe the compiler version is the problem?

I'm gonna check with 4.09.0.

2019-10-28 20:06 UTC, llelf commented
> What about Coq with native compute disabled and no flambda?

I see these numbers:
`time make -j1` for stdpp master. Coq master, ocaml 4.09.0, macOS 10.13.

||  | ¬ native-compiler
-|-|-
vanilla | 1m48s | 1m23s
flambda | 2m21s | 1m23s (the same)

2019-10-29 00:30 UTC, ejgallego commented
So indeed there is no problem here?

2019-10-29 01:18 UTC, Blaisorblade commented
@ejgallego Hm? @llelf has flambda slower than vanilla (normally) and them equal (without native-compiler) when compiling Coq code which doesn't use native_compute. That doesn't seem expected? I guess this PR is the wrong thing and should be an issue, but why should ¬ native-compiler speed things up?

2019-10-29 02:35 UTC, ejgallego commented
Oh indeed, sorry, I misread the numbers; the numbers indeed are pretty weird, I tried to reproduce but I didn't get a significant difference. There could be a few factors:
- environment variables 
- operating system? [I'm on Linux]

what does the native build says when `-debug` is passed to `coqc`?

AFAICS stdpp does not call native_compute, am I correct?

2019-10-29 02:45 UTC, ejgallego commented
Are `.coq_native` directories being produced in your build?

The only significant difference between `-native-compute yes` and `-native-compute no` should be an extra filesystem lookup per required library; that shouldn't produce such differences.

Given the timings you are getting it looks like the native version of `stdpp` is being compiled.

2019-10-29 03:19 UTC, Blaisorblade commented
I'm indeed on Mac.

> Are .coq_native directories being produced in your build?

With make it isn't — I just rechecked with — I get `theories/.coq-native/` with `coqc -native-compiler yes`, but not when compiling with plain `make` (which still gives slow results).

> AFAICS stdpp does not call native_compute, am I correct?

Correct — the string `native` appears nowhere in the project, so they also don't use `-native-compiler yes`.

> what does the native build says when `-debug` is passed to `coqc`?

"The native build"? Can you please be more specific? Here's a partial attempt.

Passing `COQDEBUG=-debug` when building stdpp shows searching for stdpp native object code fails, and that does disappear when native code is disabled.

```
gtime -f "theories/proof_irrel (real: %e, user: %U, sys: %S, mem: %M ko)" "coqc" -debug  -q -w -undeclared-scope  -Q theories stdpp  theories/proof_irrel.v
Debug:
Cannot find native compiler file /Users/pgiarrusso/git/Coq/stdpp/theories/.coq-native/Nstdpp_base.cmxs
```

2019-10-29 16:05 UTC, ejgallego commented
> Passing `COQDEBUG=-debug` when building stdpp shows searching for stdpp native object code fails, and that does disappear when native code is disabled.

Indeed, I meant that; the message you have gotten is correct.

As far as I can see the only difference in the codebase is indeed an extra lookup for each required library, that should not create this huge slowdown.

Unfortunately I cannot reproduce on Linux, so I am at a loss here; any other developer on OSX that could help?

Maybe you folks can produce a per-file time [with the time target of the makefiles] and see if the slowdown is spread out or concentrated in one file.

2019-10-29 16:06 UTC, ejgallego commented
I also suggest we turn this PR into an issue "Using `-native-compiler yes` in configure produces slowdown on general Coq use" or something like that.

2019-11-06 12:35 UTC, Blaisorblade commented
This should definitely be an issue not a PR.

My `env` has `TIMED=1`, plus the `opam env` output, but nothing jumps to mind.

Either way, I'd want to improve my reproduction scripts (when I find time — been traveling) — I can `opam pin edit` to add the needed option, but variant coq-flambda-like packages (at least in some local repo) seems a better idea. (It might also help users anyway).

2019-11-06 12:41 UTC, maximedenes commented
If native compute is set to "ondemand" (which should be the default), we shouldn't see a slowdown with flambda. So there probably is an issue somewhere.

2019-11-12 17:18 UTC, Blaisorblade commented
I've filed an issue and I'm closing this PR; I'm not sure when I'll have time to get back to it — or at least to prepare extra packages.

> before closing this PR in favor of an issue, I think we need some more data.

Feel free to reopen/ask for more data/... either way — but I filed an issue anyway since progress might take a while (nobody has both hardware and expertise).

2019-11-12 17:18 UTC, closed without merging

2019-11-12 17:30 UTC, ejgallego commented
Thanks for taking care of this @Blaisorblade .