Bugfix vos 11057
coq/coq pull request #11075
Opened 2019-11-08 10:51 UTC by charguer

**Kind:** bug fix 
Fixes / closes #11057 

This PR contains three commits.
- From CoqIDE or -vos or -vok compilation, load .vo when .vos is missing.
- No longer install .vos files in user contribs from coq_makefile.
- Compilation of a .vo touches an empty .vok file in addition to the .vos file (we might later choose to produce none of them, and let the build system touch these two files, however it seems a bad idea to have an asymmetry between touching .vos and .vok).

2019-11-08 10:52 UTC, SkySkimmer commented
>Compilation of a .vo touches an empty .vok file in addition to the .vos file (we might later choose to produce none of them, and let the build system touch these two files, however it seems a bad idea to have an asymmetry between touching .vos and .vok).

How about touching none of them?

2019-11-08 11:03 UTC, charguer commented
> How about touching none of them?

At the very least, you need when you call `coqc foo.v` to remove the file `foo.vos`. Otherwise you'll end up loading stale files from CoqIDE.

But then, it seems preferable to touch an empty `foo.vos` file, because then subsequent `make *.vos` calls will not need to recompile proofs that have already been processed.

If you go that route, you would change the `CoqMakefile.in` to something along the lines of:
```
$(VOFILES): %.vo: %.v
	$(SHOW)COQC $<
	$(HIDE)$(TIMER) $(COQC) $(COQDEBUG) $(TIMING_ARG) $(COQFLAGS) $(COQLIBS) $< $(TIMING_EXTRA)
       $(HIDE)touch $@s
       $(HIDE)touch $@k
```
(I'm not sure this is valid syntax though)
(Also, it would require an update to the documentation to remove the paragraphs about "creating empty files").

Given the existence of .glob and .aux and .native etc..., I personally don't worry for two extra files, given the benefits that it brings.

2019-11-08 12:08 UTC, SkySkimmer commented
Maybe it's coqc -vos that should produce the empty file if the vo already exists? I don't know.
The vok target could be a PHONY rather than produce an empty file.

Or maybe the stuff we produce should be inverted somehow, we would produce a .vos with the public data and a .vopaque with the opaque proofs, with the .vo being just a witness that the union of opaque universes are OK? That might fight the build system less (or not?)

2019-11-08 12:37 UTC, charguer commented
> Maybe it's coqc -vos that should produce the empty file if the vo already exists? I don't know.

No. You want to delete whatever vos file exists when producing a vo file, else the rule that says "load vos file first if possible" will lead you to loading stale files.

> The vok target could be a PHONY rather than produce an empty file.
I don't think so, you want the markers to persist from one call to make to the other.

> Or maybe the stuff we produce should be inverted somehow, we would produce a .vos with the public data and a .vopaque with the opaque proofs, with the .vo being just a witness that the union of opaque universes are OK? That might fight the build system less (or not?)

The issue is that universes must be globally OK across all vo files. Even if a totally different design was possible, we aimed for minimal changes to add the vos feature, to avoid breaking/reimplementing too many things.

2019-11-08 12:45 UTC, SkySkimmer commented
OK

2019-11-08 13:25 UTC, ejgallego requested changes
I'd like to finish review of the original PR and this one before we implement further tweaks.

2019-11-08 13:30 UTC, proux01 commented
It also seems to me that the first point (first commit) in this PR got a wide consensus and expectation whereas things remain much less clear for the remaining points (two other commits).

@charguer sorry to insist but would it be possible that this PR include only its current first commit. Other changes could go in a subsequent PR once the discussion reaches a consensus.

2019-11-08 13:57 UTC, charguer commented
I understand your concerns, but I would hate leaving the code base for a while in an awkward inconsistent state.
- if .vo are loaded when .vos are missing, there is no reason for libraries to export .vos files.
- if empty .vos are produced then .vok should also be produced (@gares agreed with this). (It was an omission from my original implementation.)

2019-11-13 15:22 UTC, silene approved these changes

2019-11-13 15:22 UTC, gares approved these changes

2019-11-13 15:29 UTC, ejgallego commented
> I understand your concerns, but I would hate leaving the code base for a while in an awkward inconsistent state.

The PR doesn't pass the test-suite, that needs to be fixed first.

> * if .vo are loaded when .vos are missing, there is no reason for libraries to export .vos files.
> * if empty .vos are produced then .vok should also be produced (@gares agreed with this). (It was an omission from my original implementation.)

2019-11-13 15:47 UTC, charguer commented
> The PR doesn't pass the test-suite, that needs to be fixed first.

I have no clue how to fix these messages. (Sorry, it's just beyond my expertise.)

2019-11-13 16:03 UTC, silene commented
Just take a look at the following files:

    test-suite/coq-makefile/coqdoc1/run.sh
    test-suite/coq-makefile/coqdoc2/run.sh
    test-suite/coq-makefile/mlpack1/run.sh
    test-suite/coq-makefile/mlpack2/run.sh
    test-suite/coq-makefile/multiroot/run.sh
    test-suite/coq-makefile/plugin1/run.sh
    test-suite/coq-makefile/plugin2/run.sh
    test-suite/coq-makefile/plugin3/run.sh

They contain an explicit list of all the files that are supposedly created by some calls to `coq_makefile`. Just adjust the list by adding or removing `.vos` and `.vok` files according to your new semantics.

2019-11-13 16:15 UTC, charguer commented
Thanks @silene. I just removed the lines mentioning the .vos files. (I don't know who or what process added them, that's why I couldn't figure out that I had to remove them from the list.)
Hope this will work better now.

2019-11-13 21:44 UTC, gares commented
I did to make your other pass ci :-)

2019-11-19 18:27 UTC, ejgallego commented
IMHO the problem stems in that both `.vo` and `.vos` do provide an interface implementation. OCaml has similar problems and there is no other solution than to clean up.

I think producing the empty files is wrong; coq should rather clean up stale files instead, but that is hard due to make? Ideally we would remove the empty file rule.

So what would break if we choose to always remove `a.vos` when outputting `a.vo` ? Cannot make track this kind of conditional dependency to reflect the loading rule?

Funnily enough Dune has no problem with this; if the set of targets change, it will correctly clean up the stale ones.

2019-11-19 18:43 UTC, SkySkimmer commented
With the empty .vos we can just say "foo.vos depends on bar.vos", and in the case where we previously built var.vo coqc sneakily (i.e. make isn't informed about this production) produces empty .vos so we don't need so redundantly build the vos.
Without the empty .vos the dependency is "foo.vos depends on bar.vos OR bar.vo" which I don't know how to do in make. In a way it's really "foo.vos depends on bar.vos, but you can forget it if bar.vo is up to date", ie if neither exists we have a preference as to which we make (but if we invoke `make foo.vos bar.vo` what is make expected to do?)
It's kinda messy.

>Funnily enough Dune has no problem with this; if the set of targets change, it will correctly clean up the stale ones.

I don't see how you can get dune to behave as (where build is either `make` or `dune build`)
~~~
$ build foo.vo
coqc bar
coqc foo
$ edit foo.v
$ build foo.vos # no need to rebuild bar
coqc -vos foo
$ edit bar.v 
$ build foo
coqc -vos bar
coqc -vos foo
~~~
which is what the current system tries to provide.

2019-11-19 18:58 UTC, ejgallego commented
> With the empty .vos we can just say "foo.vos depends on bar.vos", and in the case where we previously built var.vo coqc sneakily (i.e. make isn't informed about this production) produces empty .vos so we don't need so redundantly build the vos.

I understand that part, however that is bad for two reasons, which are IMO a bit serious:
- first, the make rules don't correspond to the rules `coqc` implements; that's a recipe for problems;
- second, if we are not installing the `.vos`, then compositionality of `coq_makefile` becomes even weaker; as the dependency rules are not valid for libraries located outside of the global scope.

> Without the empty .vos the dependency is "foo.vos depends on bar.vos OR bar.vo" which I don't know how to do in make. In a way it's really "foo.vos depends on bar.vos, but you can forget it if bar.vo is up to date", ie if neither exists we have a preference as to which we make 

Yeah that messy, you'd need to use some short of pattern in the deps to select the right mode, and a variable controlling whether you are in vos mode or not.

> (but if we invoke `make foo.vos bar.vo` what is make expected to do?)

in this case it should build `bar.vo` then use it to satisfy the dep of `foo.vos`

> I don't see how you can get dune to behave as (where build is either `make` or `dune build`)

I'm not sure I understand your example; what I mean is that once you teach Dune about the `.vos` flag [which is not hard to do], it will declare a different set of targets; then it is possible to check if the `.vo / .vos` files are up to date and if not remove them; the question on flag persistence does remain tho.

2019-11-19 19:00 UTC, ejgallego commented
I guess that we should lean towards merge, let's wait for tomorrow after the call to see what more comes to the discussion.

@SkySkimmer , do you approve this PR in its current form, or do you have a request for changes?

2019-11-19 19:04 UTC, SkySkimmer commented
It's OK.
Maybe the commit fixing the test suite should be squashed with the commit changing coq_makefile

2019-11-19 19:10 UTC, ejgallego commented
> Maybe the commit fixing the test suite should be squashed with the commit changing coq_makefile

@charguer mind rebasing and squashing?

I'll merge tomorrow evening if no further comments.

2019-11-20 10:29 UTC, charguer commented
> @charguer mind rebasing and squashing?
Let me try...

2019-11-20 11:04 UTC, charguer commented
>@charguer mind rebasing and squashing?

Ok, believe it or not, it looks like I suceeded to rebase.

(In case it did not, @SkySkimmer I gave you access to my repo so you can fix things; thanks)

2019-11-21 10:05 UTC, ejgallego approved these changes

2019-11-21 10:06 UTC, merged