[CI] Test latest artifacts of SF instead of the stable version
coq/coq pull request #11165
Opened 2019-11-22 12:45 UTC by maximedenes

Fixes #11137.

2019-11-22 12:54 UTC, SkySkimmer commented on dev/ci/ci-sf.sh
> +sf_lf_CI_TARURL=`curl https://circleci.com/api/v1.1/project/gh/DeepSpec/sfdev/latest/artifacts?circle-token=${CIRCLE_SF_TOKEN} | jq '.[].url' | grep \/lf.tgz`
```suggestion
sf_lf_CI_TARURL=`curl https://circleci.com/api/v1.1/project/gh/DeepSpec/sfdev/latest/artifacts?circle-token=${CIRCLE_SF_TOKEN} | jq '.[] | select (.path == "lf.tgz") | .url'`
```
and so on for the others

2019-11-22 12:56 UTC, SkySkimmer commented
Is the plan to test the SF dev version for 8.11 too? (ie what should be the milestone)
cc @ppedrot

2019-11-22 15:30 UTC, ppedrot commented
I think so, let me put it into the appropriate milestone.

2019-11-25 13:02 UTC, SkySkimmer submitted a review, later dismissed
SF should stop being allow_failure. Also see my previous comment (not required if you dislike the proposed change).

2019-11-25 14:04 UTC, Zimmi48 commented
Fails with:

```
 /builds/coq/coq/dev/ci/ci-sf.sh: line 8: curl: command not found
```

2019-11-25 14:13 UTC, SkySkimmer commented
Pushed change.

2019-11-25 14:41 UTC, SkySkimmer commented
Doesn't actually work, with curl I get not output when fetching the tgz, with wget I get `400 Bad Request`

2019-11-25 15:00 UTC, maximedenes commented
> with wget I get `400 Bad Request`

Really? It works for me.

2019-11-25 15:10 UTC, SkySkimmer commented
Maybe you have some login stuff on your system beyond the token?

2019-11-25 15:12 UTC, maximedenes commented
> Maybe you have some login stuff on your system beyond the token?

It could be, but I have no idea how it works, then.

2019-11-25 15:13 UTC, maximedenes commented
> Maybe you have some login stuff on your system beyond the token?

Also, shouldn't it be a 401 for you, then?

2019-11-25 15:18 UTC, SkySkimmer commented
Real pipeline is https://gitlab.com/coq/coq/pipelines/98395393 btw, coqbot got confused as I had to do the manual dance since we need to add jq to docker.

2019-11-25 17:07 UTC, SkySkimmer commented
Pipeline also got bad request.

2019-11-26 18:42 UTC, ejgallego requested changes
Downloading artifacts from circle requires auth.

2019-11-26 18:42 UTC, ejgallego commented on dev/ci/ci-sf.sh
> +wget -O - "${sf_lf_CI_TARURL}" | tar xvz
Indeed this step requires authentication, artifacts are not public so we will get a "must be logged in" message.

2019-11-26 20:37 UTC, Zimmi48 commented
A solution around this would be to download fresh artifacts only when run on a protected branch (with a secret) and to store these as artifacts in our builds, and reuse them in the PR builds.

2019-11-27 10:04 UTC, ejgallego commented
> A solution around this would be to download fresh artifacts only when run on a protected branch (with a secret) and to store these as artifacts in our builds, and reuse them in the PR builds.

Yup, that's seems like the good option for short-term, but that is still quite messy; maybe we should drop SF from CI and move it to platform?

2019-11-29 17:00 UTC, ppedrot commented
If this is not solved very soon, I'll have to postpone.

2019-11-29 17:19 UTC, ejgallego commented
@maximedenes , could we maybe put a temporary tar somewhere and use that for the moment?

2019-12-02 12:15 UTC, ejgallego commented
I've added authentication to the artifact download, at least locally that did the trick for me.

2019-12-02 13:04 UTC, ejgallego approved these changes
This seems to be working now!! I can merge myself tho maybe I should get approval from @SkySkimmer

2019-12-02 13:49 UTC, SkySkimmer approved these changes

2019-12-02 14:20 UTC, merged