Updating citing Coq in FAQ.
coq/coq pull request #1116
Opened 2017-10-03 22:46 UTC by herbelin

This is [BZ5766](https://coq.inria.fr/bugs/show_bug.cgi?id=5766) for its doc part. (But no change of Readme.md)

2017-10-05 08:13 UTC, gares approved these changes

2017-10-05 08:39 UTC, ejgallego commented
Regarding README.md , it is common practice in "research" github projects to indicate that information in the landing page; I suggest we add a quick note indeed.

2017-10-05 10:56 UTC, herbelin commented
@ejgallego: regarding the README.md, could you make a proposal of what you have in mind?

2017-10-05 11:00 UTC, ejgallego commented
@herbelin I'd take some inspiration from what Clément does here: https://github.com/cpitclaudel/company-coq regading zenodo, bibtex, etc... What do you think?

2017-10-05 11:27 UTC, herbelin commented
@ejgallego: you mean this [item](https://github.com/cpitclaudel/company-coq#citing). No objection (on my side).

Afaiu, `company-coq-cite` in coq-company has to be aware of the Coq bibtex. Do we have something to do here or @cpitclaudel (Hi!) is taking care of dynamically extracting from somewhere a relevant bibtex?

2017-10-05 12:16 UTC, ejgallego commented
> @ejgallego: you mean this item. No objection (on my side).

Cool, what do you think about having a Zenodo entry for the manual?

> Afaiu, company-coq-cite in coq-company has to be aware of the Coq bibtex. Do we have something to do here or @cpitclaudel (Hi!) is taking care of dynamically extracting from somewhere a relevant bibtex?

Oh interesting! Maybe we should add a canonical "bib" file to the repository or website so people could depend on it? [Maybe getting a zenodo entry serves this purpose, so you can do \cite{zenodo:XXXX}]

2017-10-05 12:23 UTC, herbelin commented
No opinion on Zenodo which I'm just discovering. What is this?

2017-10-05 12:26 UTC, ejgallego commented
@herbelin it is a "paper" repository, aimed to improve access to scientific documents; I am not expert either, and there are other alternatives [I just picked Zenodo as Clément uses it]

The main advantage is that it would provide a DOI for the latest Coq Reference manual.

2017-10-05 13:25 UTC, Zimmi48 commented
I'd suggest you have a look at the Coqdev thread "Citing Coq" from May 11th, 2015, started by @cpitclaudel himself.

2017-10-05 14:19 UTC, ejgallego commented
Cool @Zimmi48 , here's the link to the archive: https://sympa.inria.fr/sympa/arc/coqdev/2015-05/msg00025.html

2017-10-05 17:10 UTC, herbelin commented
All the directions mentioned there look worth to me. If it is a fatigue duty for each of us to register the manual on HAL, and to get a DOI at Zenodo, shall we draw straws? (And add an item on the list of release todos).

2017-10-05 23:24 UTC, cpitclaudel commented
Hi @herbelin! It's a static string, hardcoded into company-coq; happy to update it!

2017-10-06 13:14 UTC, Zimmi48 commented
> If it is a fatigue duty for each of us to register the manual on HAL, and to get a DOI at Zenodo, shall we draw straws? (And add an item on the list of release todos).

In fact, Zenodo looks pretty awesome. There is a GitHub feature which allows to automatically generate a new DOI at each release. I've activated it to test it. Normally we should thus get a DOI when we release Coq 8.7+beta2 later today. Once we have a DOI, we also get a badge that we can add to the README (like on Company-Coq's README). If instead of updating the FAQ after each release, we say something along the lines of "To get the latest information on how to cite Coq, please refer to the following page..." we won't even have to add a new item in the release to-do list.

2017-10-06 16:00 UTC, herbelin commented
> If instead of updating the FAQ after each release, we say something along the lines of "To get the latest information on how to cite Coq, please refer to the following page..." we won't even have to add a new item in the release to-do list.

Indeed, that would certainly make maintenance easier.

> It's a static string, hardcoded into company-coq; happy to update it!

And maybe, a file containing the bibtex entry could be put somethere in the `distrib` directory of each version, and in the install directory of each coq package so that a tool like coq-company can automatically get the  bibtex entry corresponding to the Coq version the user is using.

2017-10-06 17:34 UTC, aspiwack commented
> There is a GitHub feature which allows to automatically generate a new DOI at each release. I've activated it to test it.

Just an side advice: do take note somewhere in the coq repository of _everything_  that you've configured in Github. It will help whoever's in charge at the time where the config is lost (crash on github, hack, migration) not to go completely insane (hey, who knows, it may be you, indefinite reader!).

2017-10-10 08:15 UTC, Zimmi48 requested changes
Given how we are just about to release 8.7.0 let's make sure this is not almost immediately outdated.

I have another question: why do you have to update both this file and open coq/www#47? What is the purpose of the present file?

2017-10-10 08:15 UTC, Zimmi48 commented on doc/faq/FAQ.tex
> +  title       = {The {Coq} Proof Assistant Reference Manual, version 8.6},
Can you put 8.7.0 instead?

2017-10-10 08:15 UTC, Zimmi48 commented on doc/faq/FAQ.tex
> +  year        = {2016},
Oct 2017.

2017-10-10 13:01 UTC, herbelin commented
> I have another question: why do you have to update both this file and open coq/www#47? What is the purpose of the present file?

The present file is/was the original source of the FAQ. It is still used to produce the FAQ.pdf for instance.

At some time, Denis Cousineau made a nice-looking html version of the FAQ, but he made it by hand, so that the synchronization between the "master" tex copy and the copy on the web site is not any more mechanized.

> Given how we are just about to release 8.7.0 let's make sure this is not almost immediately outdated.

Done, but knowing that this is still not a very robust way of proceeding.

> Just an side advice: do take note somewhere in the coq repository of everything that you've configured in Github. It will help whoever's in charge at the time where the config is lost (crash on github, hack, migration) not to go completely insane (hey, who knows, it may be you, indefinite reader!)

Anyone github expert willing to do that?

2017-10-10 13:08 UTC, Zimmi48 commented
On the Zenodo topic, I'll open an issue to discuss it. I don't think it would be wise to do a last minute change on the way we recommend citing Coq just before the 8.7.0 release.

I pretty worried about the non-synchronization between the HTML and TeX FAQ... (that's not going to help keeping it up-to-date if changes have to be duplicated). What about just dropping the TeX version? I suppose no one compiles it to PDF anymore...

2017-10-10 13:22 UTC, herbelin commented
> What about just dropping the TeX version? I suppose no one compiles it to PDF anymore...

Yes, that's probably ok. I don't know the general opinion though.

(Note the dependency in an xfig figure though, as master for an eps file - doc/FAQ/axioms.fig. I was pretty proud of this synthesis of the dependency graph of axioms that can be added to Coq. It should be updated, extended, and put on the web site too.)

2017-10-10 13:46 UTC, Zimmi48 approved these changes

2017-10-10 13:49 UTC, Zimmi48 commented
OK let's merge this as a temporary fix for 8.7, but then discuss the future of the FAQ, and in particular its removal from the sources, trying to save as much as can be (in particular this figure that you mentioned).

2017-10-10 21:05 UTC, merged