Additional statements in List.v
coq/coq pull request #11249
Opened 2019-12-06 14:36 UTC by olaure01

Adds various lemmas to file List.v of the standard library.
These lemmas look natural and happen to be useful in practice.

**Kind:** feature

2020-01-04 11:39 UTC, olaure01 commented
@coq/stdlib-maintainers no assignee yet, should I do something?

2020-01-04 12:13 UTC, herbelin approved these changes
Sorry, @olaure01, I missed it.

That looks welcome and good to me, thanks a lot. Will merge say on Tuesday, leaving some extra time for comments.

2020-01-04 17:08 UTC, herbelin commented
@anton-trunov:

> Do you think we should keep `in_inv` as a resolve hint? (it's currently declared as such)

It is indeed questionable since it is conversion lemma. I don't have a strong opinion but for compatibility, it is maybe better to keep it though, so that e.g., the following kind of lemma is solved by `auto with datatypes`:
```
Require Import List.
Lemma foo : forall l, (True -> In 1 (0 :: l)) -> 0 = 1 \/ In 1 l.
Proof. auto with datatypes. Qed.
```

2020-01-04 20:47 UTC, anton-trunov requested changes
Looks great! Thank you. I hope you do have time to address some comments.

2020-01-04 20:47 UTC, anton-trunov commented on theories/Lists/List.v
> +Lemma nth_nth A : forall (l : list A) n d ln dn, n < length ln \/ length l <= dn ->
The name `nth_nth` seems to be too short for this lemma and does not reflect fully what it is about. This could provoke name clashes in the future.

2020-01-04 20:51 UTC, anton-trunov commented
> it is maybe better to keep it though, so that e.g., the following kind of lemma is solved by auto with datatypes:

@herbelin Indeed! Thank you for that example -- very helpful.

2020-01-05 09:54 UTC, olaure01 commented on theories/Lists/List.v
> +  Lemma app_inv_tail:
Note the 3 considered lemmas `app_inj_tail` `app_inv_head` and `app_inv_tail` are not introduced or named by this PR. The modification appears here just because of some code moving in the file.
I think more natural names for `app_inj_tail` would indeed be `app_inj_last` or `app_inv_last`. Such a renaming would allow us to use `app_inj_head` and `app_inj_tail` here.
However this means renaming 3 existing lemmas and reusing one name for a different statement.
Is it really something we should consider?

2020-01-05 09:59 UTC, anton-trunov commented on theories/Lists/List.v
> +  Lemma app_inv_tail:
@olaure01 Indeed, you are right. I tried to track the actual changes vs code-move changes, but in this case I missed it.

2020-01-05 10:15 UTC, olaure01 commented on theories/Lists/List.v
> +Lemma nth_nth A : forall (l : list A) n d ln dn, n < length ln \/ length l <= dn ->
OK, I propose `nth_nth_nth_map`, the rest of the statement being only sanity conditions on length.

2020-01-05 10:17 UTC, anton-trunov commented on theories/Lists/List.v
> +Lemma nth_nth A : forall (l : list A) n d ln dn, n < length ln \/ length l <= dn ->
Great!

2020-01-05 10:23 UTC, olaure01 commented on theories/Lists/List.v
> +    intros a b l H; inversion_clear H; auto.
done

2020-01-05 10:24 UTC, olaure01 commented on theories/Lists/List.v
> +    Qed.
Absolutely! I used the `remove_remove_comm` name.

2020-01-05 10:26 UTC, olaure01 commented on theories/Lists/List.v
> +  Qed.
Sure.
I have just modified the proofs a bit to avoid introducing additional dependencies on `auto with arith` in the spirit of #11356.

2020-01-05 10:27 UTC, anton-trunov commented on theories/Lists/List.v
> +  Qed.
Awesome, thank you!

2020-01-05 10:28 UTC, anton-trunov approved these changes

2020-01-14 20:05 UTC, herbelin commented
It seems that comments have been addressed. Will merge soon.

2020-01-14 21:06 UTC, merged