Fix issue #11396 : Rlist hides standard list constructors cons and nil
coq/coq pull request #11398
Opened 2020-01-14 12:54 UTC by MSoegtropIMC

This PR fixes the hiding of the standard list cons and nil constructors by Rlist cons and nil when Reals is imported. This is done by not exporting Rlist from Reals and instead importing it (in the two places) where it is needed as suggested by @ppedrot.

2020-01-14 12:55 UTC, MSoegtropIMC commented
Note: I tested locally that this builds, but I didn't test as yet if it fixes the issues I see. This will take until today evening.

2020-01-14 12:57 UTC, ppedrot requested changes
This needs a changelog before merging, but let's first run the CI to get an idea of the breakage.

2020-01-14 14:32 UTC, ppedrot commented
So far, only coquelicot looks broken. I wrote a 3-line patch that makes it compile, and which is most likely backwards compatible. I'll submit a PR there.

2020-01-14 14:35 UTC, ppedrot commented
See the [gitlab.inria.fr merge request](https://gitlab.inria.fr/coquelicot/coquelicot/merge_requests/2).

2020-01-14 17:08 UTC, ppedrot commented
AFAIU, fiat-crypto failure is unrelated.

2020-01-14 17:15 UTC, Zimmi48 commented
Yeah, seems broken on master too.

2020-01-14 20:32 UTC, MSoegtropIMC commented
@ppedrot : thanks for fixing Coquelicot! I will see tomorrow morning if Gappa works now and adjust the patch for Interval (90% of the patch can be removed now) and see if I can find a better pick for interval (which is much quicker with a smaller patch).

2020-01-15 10:15 UTC, MSoegtropIMC commented
I did my best to write a changelog entry looking at others and also using the provies script, but somehow I messed it up. Can someone have a look and tell me what is wrong?

@ppedrot : shall I redirect Coquelicot to your fork/branch in the picking CI or shall I wait for upstream?

2020-01-15 15:17 UTC, ppedrot commented
I'll try to get the upstream PR merged, but if that takes too long you can probably pick my repo instead. Let's see whether @silene is more responsive on GitHub.

2020-01-16 12:51 UTC, ppedrot commented
The CI failures look somewhat spurious btw, maybe a rebase would suffice.

2020-01-16 13:18 UTC, MSoegtropIMC commented
@ppedrot : my assumption is that I messed up the changelog entry. Most failing jobs ore doc jobs. Can you please have a look and see what I did wrong?

2020-01-16 13:19 UTC, ppedrot commented
At first sight, the changelog does look correct though.

2020-01-16 13:19 UTC, ppedrot commented
Ah, maybe it's missing a newline.

2020-01-16 13:34 UTC, Zimmi48 commented
Right, this is what says the linter, and all failing jobs that build the doc. The only other failure is Coquelicot.

2020-01-16 13:58 UTC, MSoegtropIMC commented
OK, I will fix that.

2020-01-17 14:59 UTC, ejgallego commented
As I suggested on Gitter, there is no need to wait for Coquelicot to apply the trivial patch if you folks want to be done with 8.11 [cc @ppedrot ] , you can just point the CI variable to the merge request and once the patch arrives upstream we undo.

The way I see CI overlays is pretty dynamic, at least for trivial patches like this.

2020-01-17 16:14 UTC, Zimmi48 commented
So FTR, the file to modify is `dev/ci/ci-basic-overlays.sh`.

2020-01-17 16:17 UTC, MSoegtropIMC commented
@ejgallego : yes, I will do this in the picking PR if everything else in finished and this is not yet in upstream.

2020-01-17 17:44 UTC, Zimmi48 commented
You will also need to do it here so that CI is not broken on master...

2020-01-17 18:22 UTC, ejgallego commented
Yes it has to be done here, I may push to the PR doing that and fixing the trivial mistake as not to delay the release more.

2020-01-17 18:35 UTC, Zimmi48 commented
This will need at least one approval from another member of @coq/reals-library-maintainers.

2020-01-17 18:38 UTC, Zimmi48 approved these changes

2020-01-17 20:59 UTC, herbelin approved these changes
> This will need at least one approval from another member of @coq/reals-library-maintainers.

This seems indeed to be the natural way to go.

2020-01-17 21:06 UTC, herbelin commented
Actually, #11404 is proposing another solution, namely to just redefine `Rlist` from `list`. It is bit more radical but this is factorization which makes sense to me.

2020-01-17 22:14 UTC, Zimmi48 commented
This one is the short-term fix.

2020-01-17 22:41 UTC, MSoegtropIMC commented
OK, I will do it here and cherry pick it for the picking PR tomorrow. Since Gappa is working now all which is left is a bit of cleanup and maybe an improvement for the picking of interval.

2020-01-18 07:32 UTC, ybertot commented
I confirm that PR #11404 is intended to describe a possible long term solution, leading to more streamlined standard libraries.  I made the pull request to make sure ci would tell me how much damage it would make to depending packages.

2020-01-19 18:00 UTC, ppedrot approved these changes

2020-01-19 18:01 UTC, merged

2020-01-21 09:12 UTC, Zimmi48 commented
This PR was already backported as part of #11393.