Add reduction-effects to the CI
coq/coq pull request #11469
Opened 2020-01-28 04:51 UTC by JasonGross

**Kind:** infrastructure.

Blocked on https://github.com/coq-community/reduction-effects/pull/5

2020-01-28 05:28 UTC, JasonGross commented
I'm confused by the CI failure:
```
+ tar xvfz b8dd8290f0648751cbf64456435cc284144cb0d2.tar.gz --strip-components=1
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/.circleci/
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/.circleci/config.yml
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/.gitignore
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/.gitmodules
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/CHANGELOG.md
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/LICENSE
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/Makefile
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/PrintingEffect.v
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/README.md
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/_CoqProject
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/coq-reduction-effects.opam
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/meta.yml
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/redeffect.mlg
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/redeffect_plugin.mlpack
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/templates/
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/tests/
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/tests/Makefile
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/tests/Makefile.coq.local
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/tests/PrintEffect.expected
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/tests/PrintEffect.v
 reduction-effects-b8dd8290f0648751cbf64456435cc284144cb0d2/tests/_CoqProject
 + rm -f b8dd8290f0648751cbf64456435cc284144cb0d2.tar.gz
 + cd /builds/coq/coq/_build_ci/reduction-effects
 /builds/coq/coq/dev/ci/ci-reduction-effects.sh: line 8: cd: /builds/coq/coq/_build_ci/reduction-effects: No such file or directory
 Makefile.ci:75: recipe for target 'ci-reduction-effects' failed
```
Did I do something wrong?

2020-01-28 08:43 UTC, SkySkimmer requested changes
See comments, and also change the .sh name to `ci-reduction_effects.sh`

2020-01-28 08:43 UTC, SkySkimmer commented on .gitlab-ci.yml
> +plugin:ci-reduction-effects:
```suggestion
plugin:ci-reduction_effects:
```

2020-01-28 08:43 UTC, SkySkimmer commented on Makefile.ci
> +    ci-reduction-effects \
```suggestion
    ci-reduction_effects \
```

2020-01-28 08:43 UTC, SkySkimmer commented on dev/ci/ci-reduction-effects.sh
> +( cd "${CI_BUILD_DIR}/reduction-effects" && make && make test && make install)
```suggestion
( cd "${CI_BUILD_DIR}/reduction_effects" && make && make test && make install)
```

2020-01-29 01:18 UTC, JasonGross commented
@SkySkimmer Thanks, should be fixed now

2020-01-29 04:00 UTC, JasonGross commented
CI passes now

2020-01-29 09:30 UTC, SkySkimmer approved these changes

2020-01-29 09:36 UTC, merged

2020-01-29 17:57 UTC, ppedrot commented
Is this really supposed to go into 8.11?

2020-01-29 18:43 UTC, JasonGross commented
I don't see why it shouldn't go into 8.11 (and it would be nice to have a version of it distributed with the Windows Coq installer, if that's on the table), but if you think it's a bad idea or not work it, feel free to drop it from 8.11.

2020-01-29 19:14 UTC, ppedrot commented
Merely backporting this PR will not add it to the Windows installer, and furthermore this will require clever pinning of the dev in 8.11. So, I don't think it is worth it.