Remove Goptions.opt_name field
coq/coq pull request #11521
Opened 2020-02-04 16:09 UTC by SkySkimmer

The standard use is to repeat the option keywords in lowercase, which
is basically useless.

En passant add doc entry for Dump Arith.

2020-02-04 16:11 UTC, SkySkimmer commented
We probably don't need quite so many reviewers ;)

2020-02-06 11:54 UTC, ppedrot approved these changes
Fine.

2020-02-06 11:54 UTC, ppedrot commented
You need a lot of overlays though...

2020-02-06 13:19 UTC, SkySkimmer commented
>You need a lot of overlays though...

It's not that bad.

2020-02-12 12:02 UTC, SkySkimmer commented
Are we merging this before overlays get out of date?

2020-02-12 12:06 UTC, ppedrot commented
OK, will merge when CI passes.

2020-02-12 14:31 UTC, ppedrot commented
Suspicious CI failures, did you rebase the overlays?

2020-02-12 14:32 UTC, SkySkimmer commented
There's no overlay for quickchick

2020-02-12 14:35 UTC, ppedrot commented
Right, that's unrelated overlay desynchronization. Will disregard the failure then.

2020-02-12 15:22 UTC, Zimmi48 requested changes

2020-02-12 15:22 UTC, Zimmi48 commented on doc/sphinx/addendum/micromega.rst
> +.. flag:: Dump Arith
This is an option, not a flag.

2020-02-13 12:30 UTC, Zimmi48 approved these changes

2020-02-13 13:46 UTC, merged