Helping issue #11659 by leaving only the Cast hack in the grammar.
coq/coq pull request #11668
Opened 2020-02-24 12:18 UTC by Zimmi48

The `CLocalPattern` hack is moved to `comDefinition.ml`.

**Kind:** clean-up.

Closes #11659

(prepared by @herbelin)

2020-02-24 12:21 UTC, maximedenes requested changes

2020-02-24 12:21 UTC, maximedenes commented on vernac/comDefinition.ml
> +let pattern_in_binder_hack bl c ctypopt =
Please add a description of what this function does.

2020-02-24 15:57 UTC, ejgallego approved these changes

2020-02-24 16:00 UTC, SkySkimmer commented
Why are we leaving the Cast hack in the mlg?

2020-02-24 16:11 UTC, herbelin commented
> Why are we leaving the `Cast` hack in the mlg?

Why deconstructing the `Cast`: It is a design choice, doing such that if the user writes `Definition d bl := c : t`, then the body of the definition in the kernel is `fun bl => c` and not `fun bl => c : t`. 

Maybe we could remove it, on the assumption that if the user does not want a cast in the body, it uses the syntax `Definition d bl : t := c`. Which one is most intuitive? Which one is simplest to explain?

Why in the `mlg`: no particular reason, it could be in `comDefinition.ml` too.

2020-02-25 08:19 UTC, herbelin commented
I fixed the failures of the patch and improved it so that `Eval` applies exactly on what it was supposed to apply.

> Please add a description of what this function does.

Done (and don't hesitate to suggest more details if you think it is worth).

2020-02-25 08:51 UTC, Zimmi48 commented
There are some slight changes in `test-suite/output/PatternsInBinders`:

```diff
@@ -4,7 +4,7 @@
      : A * B -> B * A
 forall '(x, y), swap (x, y) = (y, x)
      : Prop
-proj_informative = fun '(exist _ x _) => x : A
+proj_informative = fun '(exist _ x _) => x
      : {x : A | P x} -> A
 foo = fun '(Bar n b tt p) => if b then n + p else n - p
      : Foo -> nat
@@ -29,8 +29,7 @@
 ∀ '(x, y), swap (x, y) = (y, x)
      : Prop
 both_z = 
-fun pat : nat * nat =>
-let '(n, p) as x := pat return (F x) in (Z n, Z p) : F (n, p)
+fun pat : nat * nat => let '(n, p) as x := pat return (F x) in (Z n, Z p)
      : forall pat : nat * nat, F pat
 fun '(x, y) '(z, t) => swap (x, y) = (z, t)
      : A * B -> B * A -> Prop
```

2020-02-25 10:58 UTC, herbelin commented
> There are some slight changes in `test-suite/output/PatternsInBinders`:

This is because I improved the "hack" so that it also removes the cast that it had introduced. I approved the new output and committed.

2020-02-25 13:24 UTC, Zimmi48 commented
@maximedenes can you check the comment and maybe self-assign?

2020-03-03 15:03 UTC, Zimmi48 commented
@maximedenes Your comment has been addressed. Do you want to review, and perhaps merge this PR?

2020-03-24 11:13 UTC, Zimmi48 commented
ping @maximedenes

2020-03-27 13:31 UTC, maximedenes approved these changes
LGTM modulo CI

2020-03-27 13:31 UTC, maximedenes commented
I'll rebase to trigger a fresh CI run.

2020-03-27 13:33 UTC, maximedenes commented
@herbelin for some reason I don't have permission to push the rebased branch to your fork. Can you do it?

2020-03-27 13:55 UTC, Zimmi48 commented
> @herbelin for some reason I don't have permission to push the rebased branch to your fork. Can you do it?

The reason is that I was the one who opened the PR, so GitHub couldn't ask *me* to give push rights to maintainers.

2020-03-27 21:24 UTC, herbelin commented
> @herbelin for some reason I don't have permission to push the rebased branch to your fork. Can you do it?

Done.

2020-03-31 08:15 UTC, maximedenes commented
> The reason is that I was the one who opened the PR, so GitHub couldn't ask _me_ to give push rights to maintainers.

I see, thanks for the explanation.

2020-03-31 08:18 UTC, merged