[ci] Allow failure in `validate:quick`
coq/coq pull request #11682
Opened 2020-02-25 19:16 UTC by ejgallego

This is a common failure, moreover, `build:quick` is `allow_failure:
true` so it seems this should be too.

2020-02-25 19:40 UTC, SkySkimmer commented
>build:quick is allow_failure: true so it seems this should be too.

Conclusion does not follow from premise.

2020-02-25 19:54 UTC, ejgallego commented
> Conclusion does not follow from premise.

We don't know the inference rules in the first place, do we?

2020-02-26 12:09 UTC, SkySkimmer commented
The point is that I don't follow your reasoning.

2020-02-26 12:56 UTC, maximedenes commented
Do you have a pointer to the issue reporting `validate:quick` failures?

2020-02-26 17:23 UTC, ejgallego commented
> The point is that I don't follow your reasoning.

My argument was more in the line of "this is a common failure" ; the second part of the sentence was a hypothesis.

> Do you have a pointer to the issue reporting `validate:quick` failures?

https://gitlab.com/gitlab-org/gitlab/issues/202505

2020-02-26 17:24 UTC, maximedenes commented
> https://gitlab.com/gitlab-org/gitlab/issues/202505

But what is specific to `validate:quick`, then?

2020-02-26 17:31 UTC, ejgallego commented
> But what is specific to `validate:quick`, then?

I don't understand the question?

The reasoning for this is:
- `validate:quick` fails very often and creates a lot of noise
- `validate:quick` has provided so far limited utility in terms of detecting real bugs

thus the tradeoff is clear, disable for now; we may re-enable when gitlab fixes the bug.

Moreover, `build:quick` is already marked allow_failure, so there is a possibility that marking this allow_failure would workaround the bug itself tho.

2020-02-26 17:33 UTC, maximedenes requested changes
I'm not convinced, this looks like an independent CI issue, please keep `validate:quick` as it is until we know the source of the problem.

2020-02-26 17:35 UTC, maximedenes commented
> `build:quick` is already marked allow_failure

I'd like to work on that at some point, but I'd need to extract say the 10 last `build:quick` failures on master (to study them). Is there a way to do it?

2020-02-26 17:36 UTC, ejgallego commented
> I'm not convinced, this looks like an independent CI issue, please keep `validate:quick` as it is until we know the source of the problem.

Sorry, keeping a target that is not reliable goes against CI policy; regardless of the cause of the bug. This has a big impact to usability of the CI itself.

2020-02-26 17:39 UTC, maximedenes commented
> Sorry, keeping a target that is not reliable goes against CI policy; regardless of the cause of the bug.

What if the problem is not specific to `validate:quick`? Are you going to remove all CI targets impacted by the same issue? For example, https://gitlab.com/coq/coq/-/jobs/450980551 seems to be a similar pb on SF. Should we remove SF too?

2020-02-26 17:51 UTC, ejgallego commented
> What if the problem is not specific to `validate:quick`?

That would be indeed a totally different scenario; so far we only saw this bug in `validate:quick` so my rationale is that it was making too much noise.

Seeing this in `sf` is worrying thou, it is the first time I see that particular one outside of the `validate:quick`, but if that starts to happen then it means that the CI is deeply broken.

I wonder if the increases failure rate has to do with our massive job re-scheduling due to roquableu being broken for week [cc @Zimmi48 , cc #10542]

Do you think folks we could fix roquableu? Otherwise it may be wise to remove it from the runner list ASAP.

2020-02-26 18:56 UTC, Zimmi48 commented
> > `build:quick` is already marked allow_failure
> 
> I'd like to work on that at some point, but I'd need to extract say the 10 last `build:quick` failures on master (to study them). Is there a way to do it?

I should be able to help with this (next week).

> I wonder if the increases failure rate has to do with our massive job re-scheduling due to roquableu being broken for weeks [cc @Zimmi48 , cc #10542]
> 
> Do you think folks we could fix roquableu? Otherwise it may be wise to remove it from the runner list ASAP.

I don't have access to this machine but I support disabling the runner preventively if it is causing trouble.

2020-02-26 22:49 UTC, maximedenes commented
> due to roquableu being broken for weeks

Note that I was notified only two days ago of this problem, on the issue you linked to.

2020-02-26 23:41 UTC, ejgallego commented
> Note that I was notified only two days ago of this problem, on the issue you linked to.

Indeed there were discussions in some places [including gitter] but nothing structured.

2020-03-13 12:23 UTC, SkySkimmer commented
see also https://gitlab.com/gitlab-org/gitlab/issues/202505

2020-04-01 07:03 UTC, ejgallego commented
This seems to have improved, right folks? Should we close?

2020-04-01 07:59 UTC, maximedenes commented
> This seems to have improved, right folks? Should we close?

I think so.

2020-04-01 08:11 UTC, ejgallego commented
Umm, actually I just checked and the issue is still there.

2020-04-10 05:38 UTC, ejgallego commented
@SkySkimmer what do we do with this? Still seeing the failure but if you folks prefer spurious failures as to the workaround then let's close.

2020-04-10 07:57 UTC, SkySkimmer commented
I don't know, I feel like if we make it allow_failure we may miss bugs like the vio issue in https://github.com/coq/coq/pull/11916

2020-04-10 07:58 UTC, SkySkimmer commented
Maybe we could allow transform the spurious failure into a spurious success by putting `if ! [ -d _install_ci ]; then exit 0; fi` at the beginning of the script

2020-04-10 21:28 UTC, ejgallego commented
> Maybe we could allow transform the spurious failure into a spurious success by putting `if ! [ -d _install_ci ]; then exit 0; fi` at the beginning of the script

That's a choice, I can implement that if you want.

2020-04-17 14:20 UTC, closed without merging

2020-04-17 14:20 UTC, ejgallego commented
Superseded by #12111