[ci] elpi 1.10.2
coq/coq pull request #11708
Opened 2020-02-28 09:41 UTC by gares

2020-02-28 10:01 UTC, gares commented
Dear @coq/ci-maintainers the docker build fails with message ` [ERROR] dune = 2.0.0 unmet availability conditions: false`. Help!

2020-02-28 16:09 UTC, gares commented
According to https://opam.ocaml.org/packages/dune/dune.2.0.0/ opam 2.0.0 only works on ocaml 4.06, while we install 4.05.

How did we manage to build the docker image with opam 2.0.0 in the first place?

2020-02-28 16:13 UTC, gares commented
Worse, dune 2.0.0 was *removed*

  https://github.com/ocaml/opam-repository/commit/e150d3bb48a4dcadb5d7837029e6a39e8455fb3a

2020-02-29 19:23 UTC, ejgallego reviewed
Yup we are in a rough spot here; but we should not bump OCaml in this PR, as that implies shifting the base OCaml we support.

Actually dune is installable with OCaml 4.02.3 , the problem in this case is `dune-configurator` which may be pulled by lablgtk3, this forces OCaml 4.06 and in newer versions up to OCaml 4.08.

This is a serious problem for us, and it is being discussed here: https://github.com/ocaml/dune/pull/3187

The easiest solution for this PR is to install a different version of dune for edge and base; dune is only needed in base for lablgtk3, in this case 1.11.4 should work.

Any of 2.2.0 / 2.3.1 should work for edge.

2020-02-29 19:25 UTC, ejgallego commented
Actually dune 2.0.1 + dune-configurator 1.11.4 should work for base; this was the original setup and the recommended path here.

2020-02-29 19:26 UTC, ejgallego requested changes
- don't bump the OCaml version
- bump Dune to 2.0.1

2020-02-29 20:18 UTC, gares commented
According to: https://opam.ocaml.org/packages/dune/dune.2.0.1/ dune 2.0.1 needs 4.06.
Anyway, I'm doing as you say, let's see

2020-02-29 20:39 UTC, ejgallego commented
> According to: https://opam.ocaml.org/packages/dune/dune.2.0.1/ dune 2.0.1 needs 4.06.
> Anyway, I'm doing as you say, let's see

Read the constraints carefully, there is and "or" there. If OCaml is less than 4.06 then it installs the OCaml secondary compiler, so the problem does indeed come with the interface of dune <-> dune configurator but only in Dune 2.3

Note that we recommend you bump the cachekey further, if the previous image was already built the infrastructure may pick the old one. In fact, if you have two commits modifying dockerfile you should bump in each of them.

You may also may want to squash both elpi commits.

2020-02-29 20:40 UTC, ejgallego commented
> if the previous image was already built the infrastructure may pick the old one.

Yup, indeed your build is bogus for that reason.

2020-02-29 20:42 UTC, gares commented
Ah, I misread. It seems to work (for docker). I'll check if elpi worked tomorrow.

2020-03-01 18:52 UTC, ejgallego commented
> Ah, I misread. It seems to work (for docker). I'll check if elpi worked tomorrow.

The docker setup is incorrect as I mentioned above, you reused the old image.

2020-03-01 18:53 UTC, ejgallego commented on dev/ci/docker/bionic_coq/Dockerfile
> +ENV BASE_OPAM="num ocamlfind.1.8.1 dune.2.0.1 ounit.2.0.8 odoc.1.4.2" \
This commit is incorrect, you change the docker image but don't bump the version.

2020-03-01 18:54 UTC, ejgallego commented on .gitlab-ci.yml
> +  CACHEKEY: "bionic_coq-V2020-02-28-V83"
The CACHEKEY is incorrect [you are reusing an image, so you either bump of delete the old image in the interface]. Also, the bump is incorrect as it results in a non-buildable image due to dune problems.

2020-03-01 18:55 UTC, ejgallego commented
I'll fix this myself as it is going to be quicker.

2020-03-01 20:52 UTC, gares commented
thanks

2020-03-02 00:36 UTC, ejgallego commented
Ok @gares you can update the upstream branch.

2020-03-02 00:36 UTC, ejgallego approved these changes

2020-03-02 00:36 UTC, merged