Added the NoDup_cut function and two auxiliary lemmas, In_inv and NoDup_tail
coq/coq pull request #11713
Opened 2020-02-28 20:08 UTC by llee454

This patch provides a function named `NoDup_cut` and two auxiliary lemmas, `In_inv` and `NoDup_tail`.

The `NoDup_cut` function accepts a value, x, and a list, xs, and cuts xs at x. This is a very natural list operation and allows a number of other important functions and lemmas about element deletion to be derived easily.

Additionally, the `NoDup_cut` function fills a significant gap in the current List module. All of the `NoDup_remove*` functions assume that the given list can be decomposed into the form `xs ++ y :: ys`. For example:

```
Lemma NoDup_remove_1 l l' a : NoDup (l++a::l') -> NoDup (l++l').
```

But, the current module does not provide a function to perform this decomposition. `NoDup_cut` fills this gap by performing this decomposition.

The `In_inv` lemma is a natural analogue of `in_inv` that I have seen implemented independently in a number of projects.

**Kind:** feature.

2020-02-28 23:19 UTC, herbelin approved these changes
Thanks a lot for your contribution, these are clearly relevant lemmas for the `List` library.

I have a superficial remark: it is unusual to put parentheses in `(list A) * (list A)`, as it is standard that application binds stronger than operators.

Note that mixing term syntax and `ltac:()` in a proof is unusual in the standard library, but I believe that this is a quite natural move and that we would certainly want to freely mix more often term syntax and tactics. So, I'm rather positive about it.

Let's give time for comments.

2020-02-29 06:37 UTC, JasonGross requested changes

2020-02-29 06:37 UTC, JasonGross commented on theories/Lists/List.v
> +      * contradict n0; destruct H; [contradiction | assumption].
Please don't use autogenerated names in new proofs.

2020-02-29 06:37 UTC, JasonGross commented on theories/Lists/List.v
> +    - destruct (in_dec decA x xs).
`right; destruct (in_dec decA x xs), H; try assumption; congruence` do the job?  (Feel feel not to use this proof of you don't want to)

2020-02-29 06:37 UTC, JasonGross commented on theories/Lists/List.v
> +    Qed.
This Qed is indented too much

2020-02-29 06:37 UTC, JasonGross commented on theories/Lists/List.v
> +          match In_inv H0 return U (b :: l) with
`In_inv` is opaque, but this definition is transparent.  Either make them both transparent, or both opaque.  And if you name them both transparent, be careful not to block the computational bits on opaque things.

2020-02-29 06:37 UTC, JasonGross commented on theories/Lists/List.v
> +  Fixpoint NoDup_cut (a : A) (ys : list A) : NoDup ys -> In a ys -> {x : (list A) * (list A) | ys = (fst x) ++ (a :: (snd x))} :=
I'm not convinced by this style.  I think either you should prove an `exists` statement (as a `Qed`ed theorem), or you should define the computational fixpoint separately from the proof of its properties.

This is a stylistic choice, however, and I won't block the merging of this PR on it.

2020-03-01 00:44 UTC, llee454 commented
Thanks @JasonGross for your feedback! I'm in the processing of making changes and will post and edit soon.

2020-03-01 13:22 UTC, olaure01 commented on theories/Lists/List.v
> +  Fixpoint NoDup_cut (a : A) (ys : list A) : NoDup ys -> In a ys -> {x : (list A) * (list A) | ys = (fst x) ++ (a :: (snd x))} :=
As a function, the NoDup hypothesis is indeed useless and the more general:
```Fixpoint list_cut (a : A) (ys : list A) : In a ys -> {'(x1,x2) | ys = x1 ++ a :: x2}```
could be defined, and then properties proved in the particular case where NoDup holds.
Note I think `{'(x1,x2) | ys = x1 ++ a :: x2}` is often more comfortable to use than `{x | ys = fst x ++ a :: snd x}`.

2020-03-01 13:33 UTC, olaure01 commented
I think there is a gap between `NoDup_cut` and the `NoDup_remove*`: the later do not assume decidability of equality.

2020-03-02 07:01 UTC, llee454 commented
Hey @olaure01  and @JasonGross. Thanks for your feedback. I also noticed that the NoDup hypothesis wasn't being used in the draft that I submitted Saturday and removed it from the draft that I submitted today. Since the new function no longer uses this hypothesis, I've removed the NoDup prefix from its name and now simply call it `cut`.

@JasonGross, I followed your suggestion and divided the `cut` function into a fixpoint and a companion lemma. I also cleaned up the indenting in `NoDup_tail`, made `In_inv` transparent, and used your ltac to prove the second case in `In_inv`.

I still believe that the `cut` function fills an important gap in the List function w.r.t the `NoDup_delete*` functions. While it is true that these functions do not make any assumptions about the decidability of equality over list elements, it is also true that this is a common property and that these functions require us to decompose lists into the form `l1 ++ a :: l2`. As far as I know, the `cut` function is the only function that performs this decomposition in the List module.

Let me know if you guys see any other potential improvements.
Thanks!

2020-03-02 08:37 UTC, olaure01 commented
It looks to me there are two different points here:

- splitting a list which contains a given element, which is already what `in_split` is doing;
- turning some statements in `Prop` into analogues in `Type` which can be given in the case of `In` by either assuming decidability of equality, or by defining a variant `In_Type` as given in [olaure01/ollibs/List_Type.v](https://github.com/olaure01/ollibs/blob/master/List_Type.v). In the later case one can move between `In` and `In_Type` by using decidability of equality, if necessary (but often replacing `In` by `In_Type` in developments does the job).

I plan to make a PR for integration of [olaure01/ollibs/List_Type.v](https://github.com/olaure01/ollibs/blob/master/List_Type.v) into stdlib in near future.

2020-03-02 08:41 UTC, olaure01 commented on theories/Lists/List.v
> +
This is now independent from the `cut` part and happens to be a particular case of both `NoDup_remove_1` and `NoDup_cons_iff`.

2020-03-02 13:05 UTC, Zimmi48 commented
@llee454 It seems that something has gone wrong while rebasing your PR. The PR should only contain commit 674587cc11ba459b21df91edbebb5d8e87b3e738 but it contains a bunch of additional commits. Make sure that your local master branch is up-to-date with upstream (in particular the top commit hash should be the same) before rebasing once again your branch on top. We can guide you in more detail if you want (then the best is to go to Gitter to get some synchronous communication) or even force-push directly to your branch.

2020-03-02 14:45 UTC, llee454 commented on theories/Lists/List.v
> +
I agree that `NoDup_tail` proves a special case of `NoDup_remove_1` and `NoDup_cons_iff`. I still think that it might be worth providing however as a convenience lemma. For example, to prove `NoDup_tail a l H` using `NoDup_remove_1` would require `NoDup_remove_1 [] l a H1` where `H1 : NoDup ([] ++ a :: l)` has to be derived from `H : NoDup (a :: l)`. While certainly doable, its less elegant.

2020-03-02 14:47 UTC, llee454 commented
@olaure01 thanks for checking for potential overlaps with other StdLib functions and lemmas.

The proposed `cut` function overlaps with `in_split`, but they are not equivalent. `in_split` is not computable. It only proves an existential property. For example, you cannot use `in_split` to do the following:

2020-03-02 14:54 UTC, llee454 commented
Hey @Zimmi48. I rebased my commit. Let me know if anything is still amiss.

2020-03-02 14:58 UTC, SkySkimmer commented
Commit message could use more newlines.

2020-03-02 19:03 UTC, JasonGross commented on theories/Lists/List.v
> +
> where H1 : NoDup ([] ++ a :: l) has to be derived from H : NoDup (a :: l)

Since `++` is structural in it's first argument, these types are judgmentally the same, and you don't need to do anything to derive one from the other.

2020-03-02 19:05 UTC, JasonGross approved these changes

2020-03-02 21:44 UTC, ppedrot commented on theories/Lists/List.v
> +  Fixpoint cut (a : A) (l : list A) : In a l -> list A * list A :=
Is is really a typical stdlib design choice to take a proof argument? AFAIK, most of the library is designed around the separation between code and proofs, and in this case there is a clear contender for a proof-free `cut`  implementation...

2020-03-02 23:19 UTC, JasonGross commented on theories/Lists/List.v
> +  Fixpoint cut (a : A) (l : list A) : In a l -> list A * list A :=
Ah, yes, indeed, I agree with @ppedrot, please just make `cut a l` return `(l, [])` in case `a` is not in `l`

2020-03-03 03:52 UTC, llee454 commented on theories/Lists/List.v
> +  Fixpoint cut (a : A) (l : list A) : In a l -> list A * list A :=
Ok. That sounds like a good default.

2020-03-03 19:39 UTC, llee454 commented on theories/Lists/List.v
> +  Fixpoint cut (a : A) (l : list A) : In a l -> list A * list A :=
@JasonGross and @ppedrot I removed the proof argument and modified `cut` so that it returns `(l, [])` when `l` does not contain `a`.

2020-03-03 19:39 UTC, llee454 commented
Hey @SkySkimmer, I revised the commit message to improve its readability.

2020-03-04 10:30 UTC, ppedrot commented on theories/Lists/List.v
> +  Lemma cut_destr : forall (a : A) (l : list A) (H : In a l), let x := cut a l in l = (fst x) ++ (a :: (snd x)).
Now that I think about it, is it common to factor out expressions with let-bindings in proof statements in the stdlib?

2020-03-04 23:41 UTC, llee454 commented on theories/Lists/List.v
> +  Lemma cut_destr : forall (a : A) (l : list A) (H : In a l), let x := cut a l in l = (fst x) ++ (a :: (snd x)).
@ppedrot I personally prefer to have the let expression in the type signature, but I'm willing to remove it if others also feel that it should be removed.

2020-03-05 02:11 UTC, JasonGross commented on theories/Lists/List.v
> +  Lemma cut_destr : forall (a : A) (l : list A) (H : In a l), let x := cut a l in l = (fst x) ++ (a :: (snd x)).
I would prefer to have it removed.  It will be easier to Search about the lemma and maybe easier to rewrite with it, without the let

2020-03-05 15:48 UTC, llee454 commented on theories/Lists/List.v
> +  Lemma cut_destr : forall (a : A) (l : list A) (H : In a l), let x := cut a l in l = (fst x) ++ (a :: (snd x)).
Ok.

2020-03-07 02:20 UTC, llee454 commented on theories/Lists/List.v
> +  Lemma cut_destr : forall (a : A) (l : list A) (H : In a l), let x := cut a l in l = (fst x) ++ (a :: (snd x)).
I removed the let expression from the cut_destr lemma's statement.

2020-03-07 02:25 UTC, JasonGross commented on theories/Lists/List.v
> +          | right H1 => False_rec _ ltac:(destruct H as [H2|H2]; contradiction)
```suggestion
          | right H1 => False_rec _ ltac:(destruct H; contradiction)
```

2020-03-07 02:27 UTC, JasonGross approved these changes

2020-03-07 23:53 UTC, llee454 commented on theories/Lists/List.v
> +          | right H1 => False_rec _ ltac:(destruct H as [H2|H2]; contradiction)
Ok

2020-03-11 15:15 UTC, llee454 commented on theories/Lists/List.v
> +          | right H1 => False_rec _ ltac:(destruct H as [H2|H2]; contradiction)
I removed this expression.

2020-03-12 10:52 UTC, herbelin commented on theories/Lists/List.v
> +  Lemma cut_destr : forall (a : A) (l : list A) (H : In a l), l = (fst (cut a l)) ++ (a :: (snd (cut a l))).
This is a cosmetic point, but I would suggest by consistency of style that `H` is removed from the statement and that a few parentheses are dropped (I know that the precedence of applications wrt symbols is not obvious a priori but all the statements are supposed to know it, so why not to use it here also).
```suggestion
  Lemma cut_destr : forall (a : A) (l : list A), In a l -> l = fst (cut a l) ++ a :: snd (cut a l).
```

2020-03-12 10:53 UTC, herbelin commented
To all who contributed to this fruitful discussion: are you ok with the current situation?

2020-03-16 16:11 UTC, llee454 commented on theories/Lists/List.v
> +  Lemma cut_destr : forall (a : A) (l : list A) (H : In a l), l = (fst (cut a l)) ++ (a :: (snd (cut a l))).
@herbelin Sorry for the late response. I'll make the change you suggested.

2020-04-02 08:34 UTC, anton-trunov commented
@llee454 I just checked the discussion and it seems that most of the comments were resolved by deleting code. Is this intentional?

2020-06-18 22:37 UTC, llee454 commented on theories/Lists/List.v
> +  Lemma cut_destr : forall (a : A) (l : list A) (H : In a l), l = (fst (cut a l)) ++ (a :: (snd (cut a l))).
@herbelin Fixed.

2020-06-18 22:37 UTC, llee454 commented
Hi all, I fixed the last request from @herbelin. Please let me know if I should make any further revisions. Thanks.

2020-07-12 22:09 UTC, llee454 commented
Hey everyone,

Just following up. The last review request was submitted 21 days ago. Please let me know if there's anything I can do to move this forward.

Thanks,

2020-07-19 16:04 UTC, anton-trunov requested changes

2020-07-19 16:04 UTC, anton-trunov commented on theories/Lists/List.v
> +  Definition In_inv (x x0 : A) (xs : list A) (H : In x (x0 :: xs)) : {x0 = x} + {In x xs} :=
And I would prefer this definition to be moved to somewhere near the `in_dec` theorem (in the facts-about-`In` part of the file).

2020-07-22 19:28 UTC, llee454 commented
@anton-trunov, Thanks for reviewing this PR.

2020-07-22 19:32 UTC, anton-trunov commented
@llee454 Hi thanks for your contribution, I assigned myself to this PR, let's see if we can get it to Coq 8.12.0!

2020-07-22 19:33 UTC, llee454 commented on theories/Lists/List.v
> +  Definition In_inv (x x0 : A) (xs : list A) (H : In x (x0 :: xs)) : {x0 = x} + {In x xs} :=
I'll happily move In_inv to the Facts section, but In_inv depends on the local eq_dec hypothesis. Are you OK with me moving this hypothesis to the Facts section as well?

2020-07-22 19:35 UTC, llee454 commented on theories/Lists/List.v
> +
I'm OK with removing NoDup_tail, I only added it because it seemed to be a natural complement to NoDup_cons.

2020-07-22 19:56 UTC, anton-trunov commented on theories/Lists/List.v
> +
Ok, let's then remove it for now to make the PR more focused. We can certainly go back and revisit this in the future.

2020-07-22 19:58 UTC, anton-trunov commented on theories/Lists/List.v
> +  Definition In_inv (x x0 : A) (xs : list A) (H : In x (x0 :: xs)) : {x0 = x} + {In x xs} :=
We can either adopt the `in_dec` way:
```
Theorem in_dec :
    (forall x y:A, {x = y} + {x <> y}) ->
    forall (a:A) (l:list A), {In a l} + {~ In a l}.
```
or make refactor `in_dec`'s statement to depend on the hypothesis you are proposing to introduce.

2020-07-22 20:39 UTC, llee454 commented
Thanks @anton-trunov, I just pushed an update with several of the revisions that you recommended. I additionally responded to two of your comments for clarification. Let me know if you need anything.

2020-07-23 07:19 UTC, Zimmi48 commented
No @anton-trunov, only bug fixes, documentation PRs and improvements to error messages are acceptable for 8.12.0. This is a feature PR so it should target 8.13.

2020-07-23 18:53 UTC, anton-trunov commented
@llee454 Sorry, but I don't see your changes. Please let's not not force-push them for now, this way I can see what has been done.

2020-11-13 09:15 UTC, gares commented
Ping @llee454

2020-11-16 10:39 UTC, gares commented
last call

2021-02-09 14:43 UTC, llee454 commented
Just following up on this. I accepted the change recommendations given above. Please let me know if anything else needs to be done for this PR to be closed.

2021-03-16 18:33 UTC, anton-trunov commented
@llee454 Could you please try again? CI weren't happy that time.

2021-08-11 16:53 UTC, Alizter commented
Will this close #11704 ?

2021-10-22 15:13 UTC, closed without merging