Extending to TACTIC EXTEND and Ltac Notation the ability to assign a binding role to an ident in the tactic syntax tree
coq/coq pull request #11721
Opened 2020-03-01 09:17 UTC by herbelin

**Kind:** enhancement

#### General presentation

In Ltac interpretation, some arguments of tactics are recognized as declaring binding variables. This is e.g. the case of `intros x [H1|H2]` which declares `x`, `H1` and `H2` as binding variable in the continuation of the tactic expression, where the "continuation" is defined to be the `; tac` continuation of the tactic if any.

This interpretation was hard-wired for tactics primitively in the abstract syntax tree for tactics. This PR extends the support to `TACTIC EXTEND` and `Tactic Notation`, that is, all uses of `ident(x)` or `intropatterns(pat)` in a new tactic definition are now declaring the corresponding variables as binding variables. (If this is not what is intended, one should use `hyp(x)`, for a variable of the context, or `ref(x)`/`reference(x)`, for a global reference, or `quantified_hypothesis(x)`, for a variable which is either in the context or quantified in the current goal, or `pre_ident(x)` for an uninterpreted ident.)

It allows for instance to have `Ltac f := intro x; apply x` working, the same way as `Ltac f := intros x; apply x` was already working, removing a surprising inconsistency.

Combined with #11679, it will also allow to do a stricter check on `ltac:()` quotations, meaning that it will be able to recognize the binding role of `x` in `ltac:(intro x; apply x)`. (Currently, `strict_check` is off for `ltac:()` notations which are not themselves parts of a bigger `Ltac` definition.)

Of course, we could go further. In an `intro x`, we indeed do two things: binding an ltac variable `x` to a name `x` and adding the name `x` in the environment. We could also recognize `clear x` as having the side effect of altering the second effect (i.e. `x` is still an ltac variable, so that we can do `clear x; intro x` reusing the same name as a binding name, but `x` is known to be no longer usable as a bound variable, thus rejecting e.g. `clear x; apply x`). For such analysis to scale, so that e.g. `let f x := clear x in f x; apply x` fails, this would need some effectful typing though, hence rather targetting Ltac2.

#### Summary 

This PR is modest wrt what could be done further. It basically aims at:
- fixing the inconstency between the failing `Ltac f := intro x; apply x` and the succeeding `Ltac f := intros x; apply x`; this is because ` x` was not recognized as binding in `intro x` due to `intro` not being primitive but defined by `TACTIC EXTEND`;
- later allowing a strict check on `ltac:()`, knowing that the CI for #11679 showed that the only two instances of `ltac:()` tested in CI which are not compatible with a strict check are in the test-suite, and precisely related to this limitation of `TACTIC EXTEND`.

#### Relation with Ltac2

Another way to look at this PR is that it basically tells to interpret `intro x ; apply x` as `let x := ipat:(x) in intro x ; apply x`, the same way as it was already doing for `intros` (where the dual role of `x` as a tactic language name and as constr name is made explicit). As it is, Ltac2 makes an explicit difference between the two roles so I believe that this does not apply but I may be wrong and if it can apply, I would gladly port it to Ltac2.

- [X] Added / updated test-suite (further tests could be done when #11679 will allow to pass the strict_check flag as an argument to the tactic interpreter)

2020-03-01 14:59 UTC, JasonGross requested changes
I think this deserves a changelog entry.  Something like:
> All uses of `ident(x)` or `intropatterns(pat)` in a new tactic definition now declare the corresponding variables as binding variables. (If this is not what is intended, one should use `hyp(x)`, for a variable of the context, or `ref(x)`/`reference(x)`, for a global reference, or `quantified_hypothesis(x)`, for a variable which is either in the context or quantified in the current goal, or `pre_ident(x)` for an uninterpreted ident.). Hence `Ltac f := intro x; apply x` now succeeds like `Ltac f := intros x; apply x` always has.

I'm a bit confused by the "global" in "global reference", though; these can bind context variables, right?  (Context variables do not to me seem to be global.  But if they are not bound by `ref`, then it seems we're missing something that can bind both context variables and global references.)

Also, does the documentation not mention this bit of how Ltac works at all?

2020-03-01 15:55 UTC, herbelin commented
@jasongross: thanks a lot for the feedback and for the proposed changelog.

> I'm a bit confused by the "global" in "global reference", though; these can bind context variables, right? (Context variables do not to me seem to be global. But if they are not bound by ref, then it seems we're missing something that can bind both context variables and global references.)

In the parser, `global` includes goal variables. In the ltac interpreter, they don't:
```
Tactic Notation "f" reference(x) := idtac x .
Goal forall n, n=0.
f n.
(* Error: The reference n was not found in the current environment. *)
```
Note that `global` is not provided in `Tactic Notation`.

Otherwise, I can't resist about reporting the funny reason of the failure of this PR in vst. It is basically related to this change of behavior:
```
Ltac f x :=
  let n := fresh "n" in
  intros n.
  
Goal nat -> nat -> nat.
intros n; clear n; f n.
(* n:nat |- nat *)
Undo.
intro n; clear n; f n.
(* before: n0:nat |- nat *)
(* now: n:nat |- nat *)
```
The technical reason is that, from the moment `n` is not detected as bound in `f n`, it is considered (this is the default) to be a binding ident for `f`, thus, `x` is bound to `ipattern:(n)` and `fresh` avoids it.

> Also, does the documentation not mention this bit of how Ltac works at all?

The documentation is rather terse on this subject. Let's remind that Ltac has growned organically w/o prior clear semantics in mind and, even now, there are still heuristics around the interpretation of names about which it is not clear whether they participate to a story clear enough to be told, unfortunately...

PS to @coq/ci-maintainers:  `make ci-vst` fails on MacOS X (it looks for a Darwin version of compcert which it does not find). Changing the target in `ci-vst.sh` to `make IGNORECOQVERSION=true ARCH=x86` fixes it. Don't know if it is moral to do the change or not though.

2020-03-01 16:03 UTC, JasonGross commented
The vst failure is indeed amusing.  Certainly the changelog entry should also mention that this sort of change can occur in rare cases.

The case I'm interested in is not the one you wrote, but instead
```coq
Tactic Notation "f" reference(x) := idtac x .
Goal forall n, n=0.
intro n.
f n.
```
Does this work, even though `n` is local to the proof rather than global?  (I would test it myself, but I'm not in front of a computer right now.)

2020-03-01 17:42 UTC, herbelin commented
> ```coq
>  Tactic Notation "f" reference(x) := idtac x .
>  Goal forall n, n=0.
>  intro n.
>  f n.
>  ```
Sorry, this is what I actually meant (I forgot the `intro`). It does not work.

2020-03-01 18:16 UTC, JasonGross commented
> It does not work.

That's unfortunate.  What should be used to denote, for example, anything that can be passed to `cbv delta` / `unfold`?  Just `constr`?  Or should we expose `smart_global` as in https://github.com/coq/coq/pull/11029 ?

2020-03-01 22:17 UTC, ppedrot requested changes
Please, no, no, no, please, seriously. I have been advocating a long time against this *feature* of Ltac, gave a lengthy account of why it did not make sense, and that we were tolerating it in very specific cases for historical reasons. Having Ltac2 around is not a reason to make the Ltac1 implementation any more crazy than it is currently.

2020-03-01 23:38 UTC, herbelin commented
@ppedrot, I don't get your arguments. What's the problem in investigating how to give an intuitive (and eventually clearly explainable) semantic to variables referring to binder names? Please point me again towards a "lengthy account of why it did not make sense"? As far as I can judge, the question is a question of giving rules about what binds what in an expression mixing object and meta levels of binders. I don't see why telling to the user that we don't want to recognize any binding status to the object level of binders, use names at your own risk, would be better than giving somes rules which acknowledge that the object level has binders (even more that Ltac2 has types and that types can eventually help to track the binding effect of tactics like `clear`, if this is what you have in mind). I'm not saying that I have already now a fully ready effectful type system allowing to control object-level names, so my claim is at the moment a theoretical claim, but I'm saying that there are basic things which seems natural and expected and that we should not prevent us to work on them.

For instance, are you saying that if Ltac2 accepts the following
```
Ltac2 f () := intro y; apply &x.
```
it is because that, if it would forbid it, it would not be able to forbid as easily the following:
```
Ltac2 f () := intro x; clear x; apply &x.
```
and, therefore, there would be no point to test something which is anyway an approximation? Is that your position? Why not to instead work at a typing system which would track the behavior of `intro`, `clear` and `rename`?

Moreover, regarding this PR, how do you justify that the behavior of `intro` is different from the one of `intros`? If you disagree with this PR, does this mean that you would prefer that it is instead the behavior of `intros` which is changed?

I think that we need to serialize questions. I'd like to defend Ltac2 and to develop a strategy towards moving all Ltac code to Ltac2, but, I assume, the point of Ltac2 is not to offer less guarantee than Ltac, so, we cannot just say, transform `Ltac f := intros x; apply x` into `Ltac2 f () := intros x; apply &x` because at the end this provides less guarantee. This is why I'm pushing so that we teach `Ltac2` a bit of the underlying object-level binding structure. (And in the meantime, I don't think we should remain with inconsistent Ltac situations such as the current `intro`/`intros` discrepancy.)

2020-03-02 07:29 UTC, ppedrot commented
> lengthy account of why it did not make sense

A CUDW, whose year I don't remember, where I convinced the whole assembly several times that "auto-generated name" was not a meaningless concept in Ltac, and as a side-product that intro-like "static-but-actually-kind-of-dynamic binding" was out as well. You kept coming back to the charge, despite a plentiful amount of evidence, and this is the last installment of your come back to the topic. I am really tired to have to debate the same things over and over.

> there would be no point to test something which is anyway an approximation

Something that is neither an over-approximation nor an under-approximation. Thus, at best, a lint. Not a type system, or at least not what we call a type system in our community.

> If you disagree with this PR, does this mean that you would prefer that it is instead the behavior of intros which is changed?

In an ideal world, yes. But please, as a development team, let us stop messing with the Ltac runtime. I am fine with tweaking tactics or really corner case behaviours, but there is a time when one has to realize what it means to beat a dead horse.

2020-03-02 07:32 UTC, ppedrot commented
> Ltac2 is not to offer less guarantee than Ltac
> I can't resist about reporting the funny reason

Pick one.

2020-03-02 08:13 UTC, herbelin commented
@ppedrot: I'm coming back to the charge because I'm not convinced. I see things that seem to make sense to me and I don't see why we should not clarify these "things". Answering to myself, I also agree that `Ltac f := intros x; apply x` is not what we want anyway as a function. What we want is rather `Ltac f x := intros x; apply x`, or `Ltac f := intros ?x; apply x` (whose equivalents in Ltac2 I don't know).

> let us stop messing with the Ltac runtime. I am fine with tweaking tactics or really corner case behaviours, but there is a time when one has to realize what it means to beat a dead horse.

I'm not considering that I'm messing with the Ltac runtime, nor that I'm beating a dead horse, I'm considering that I'm trying to better understand the organically-growned logic of Ltac and to understand what is applicable of this logic to Ltac2, with the hope to be able to design an effectful type system tracking bindings applicable to Ltac2.

Propose me a transition strategy of the existing database of Ltac functions to Ltac2 and I'll contribute at it.

> Thus, at best, a lint.

Even if just a lint at the current time, why to reject it?

PS1: I don't understand what you exactly mean by "auto-generated name".

PS2: It seems to me that there is way to move from a "static-but-actually-kind-of-dynamic binding" slogan to a "statically-tracked binding" slogan, by tracking in a type system the renaming and clearing effects that happen, so that the current tests done in Ltac eventually become more than just a lint.

2020-03-02 08:27 UTC, herbelin commented
>  I can't resist about reporting the funny reason

By the way, how would look the above example formulated in Ltac2?

2020-03-02 13:00 UTC, ppedrot commented
> by tracking in a type system the renaming and clearing effects that happen

Perfectly fine with me.

But hacking an already fragile language is not the legitimate way to do that. Please first write a paper on the topic, with a proof (even a sketch would do!) that the type system enjoys some reasonable properties like "subject reduction". Assuming you manage to define a reduction semantics for Ltac1, actually.

Your "funny example" shows that the semantics is broken for a naive function unfolding.

> By the way, how would look the above example formulated in Ltac2?

```
Require Import Ltac2.Ltac2.
Require Ltac2.List.

Ltac2 f _ :=
  let hyps := List.map (fun (id, _, _) => id) (Control.hyps ()) in
  let n := Fresh.fresh (Fresh.Free.of_ids hyps) @n in
  intros $n.
  
Goal nat -> nat -> nat.
Proof.
intros n; clear n; f @n.
Undo.
intro n; clear n; f @n.
```

2020-03-05 20:07 UTC, herbelin commented
@ppedrot: Here is a sketch of what a typing system tracking when object-level names are bound or unbound could look like. I did not prove any properties, nor fully double-check at this time. It is merely an idea, if ever you are interested we investigate it further.

Effects
```
s ::= +     (a name which refers to an hypothesis of the context)
   | -      (a name which does not refer to an hypothesis of the context)
e ::= ε
   | e,xs   (a change of status to s)
   | e,x†   (a deletion of x)
   | e,x↦y  (a renaming of x to y)
l ::= ε
   | l,x    (a name refers to an hypothesis of the context)
```
Tactic types
```
T, U ::= ∀x:T. U
      | name_s           (a name which possibly also refers to an hypothesis of the context)
      | (unit ; e)       (a tactic with side effect e)
      | (constr[l] ; e)  (a term whose free variables are in l,
                          and with side-effects e in its evars)
```
where only `x:name_s` is dependent in practice.

Tactic typing context:
```
Γ ::= ε | Γ, x : T
```
Context of effective object-level names:
```
Θ ::= ε | Θ, p
```
Tactic and CIC expressions:
```
t, u ::= clear | rename | intro       (context management)
      | let x := fresh l in t | t; u  (sequences)
      | x | t u | λx:T. u
      | [... ti ...]                  (dispatching)
      | refine c | ...                (primitive tactics)
      | constr:(c)                    (CIC terms)
      | rec_x t
c ::= x
   | _
   | ltac:(t)
   | fun x : c' => c
   | c c'
```
LtacX definitions context:
```
Ω ::= ε | Ω, x := t : T
```
Tactic typing uses sequents of the form `Ω; Θ; Γ ⊢ t : T`:
```
——————————————————————————————-—————————
Ω; Θ; Γ ⊢ clear : ∀x:name_+. (unit ; x-)

————————————————————————————————————————————————————————
Ω; Θ; Γ ⊢ rename : ∀x:name_+.∀y:name_-. (unit ; x↦y, y+)

——————————————————————————————-—————————
Ω; Θ; Γ ⊢ intro : ∀x:name_-. (unit ; x+)

Ω; Θ; Γ ⊢ l : name_s list         Ω; Θ; Γ, x : name_- ⊢ t : (unit ; e)
————————————————————————————————————————-—————————————————-———————————
Ω; Θ; Γ ⊢ let x := fresh l in t : (unit ; e\x)

where, at runtime, x is fresh among the object-level names bound to the tactic
variables of l, among the object-level names bound to the tactic variable of type
name_s in Γ, and among the object-level names of Θ.

p ∈ Θ
———————————————————
Ω; Θ; Γ ⊢ p : name-

(x : T) ∈ Γ
———————————————
Ω; Θ; Γ ⊢ x : T

(x := t : T) ∈ Ω
————————————————
Ω; Θ; Γ ⊢ x : T

FV(c) ⊂ l   ∀x∈l, (x:name+) ∈ Γ    Ω; Θ; Γ ⊢_term c : e
———————————————————————————————————————————————————————
Ω; Θ; Γ ⊢ constr:(c) : (constr[l] ; e)

Ω; Θ; Γ ⊢ u : ∀x:T. U     Ω; Θ; Γ ⊢ t : T
—————————————————————————————————————————
Ω; Θ; Γ ⊢ u t  : U[x:=t]

Ω; Θ; Γ ⊢ t : T → U
———————————————————————————
Ω; Θ; Γ ⊢ λx:T. u  :  T → U

Ω; Θ; Γ ⊢ t : (unit ; e)    Ω; Θ; Γ ∪ e ⊢ u : U
———————————————————————————————————————————————
Ω; Θ; Γ ⊢ t ; u  :  U

where Γ ∪ e is Γ where, for each x+ in e, x:name_s' in Γ is changed to x:name_+, 
similarly for x-, together with the removal of all y:(constr[l];e) with x in l, and, 
for each x↦y in e, x:name_s' is changed to y:name_s', and the substitution is applied
to each free name of each l of each (constr[l];e) occurring in each type U of
the context, for each x†, x:name_s' is renamed (and all y:(constr[l];e) with x in l).
Note that we could also remember the xs that occur only applied to evars in terms
of type (constr[l];e) and restrict these evars rather than clearing the whole term.

Γ ⊢ ti : (unit ; e_i)
————————————————————————————————
Γ ⊢ [... ti ...] : (unit ; ∩ e_i)

where for each name `x` in `Γ`, `∩ e_i` builds the maximum consistent information
for each name (using † when no consistent information can be found).

Ω; Θ; Γ ⊢_term c : e
—————————————————————————————————
Ω; Θ; Γ ⊢ refine c : (unit ; e_i)

Ω; Θ; Γ, x : ∀α1..∀an. T ⊢ t : ∀α1..∀an. T
——————————————————————
Ω; Θ; Γ ⊢ rec_x t : T[
```

Typing rules for terms:
```
Ω; Θ; Γ ⊢ c : (constr[l] ; e)
—————————————————————————————————
Ω; Θ; Γ ⊢_term c : e

—————————————————————————————————
Ω; Θ; Γ, x : name+ ⊢_term x : ε

Ω; Θ; Γ, x : name+ ⊢_term c : e
————————————————————————————————— when x not declared in Γ
Ω; Θ; Γ ⊢_term (fun x => c) : e

Ω; Θ; Γ, x:name+, Γ' ⊢_term c : e
——————————————————————————————————————————————————————————
Ω; Θ; Γ, x:name-, Γ' ⊢_term (fun x => c) : (x:name+) ▹ e

where (x:name+) ▹ e is e, x+ if x not in e and e otherwise.

Ω; Θ; Γ ⊢_term t : e   Ω; Θ; Γ ⊢_term u : e'
————————————————————————————————————————————————
Ω; Θ; Γ ⊢_term (t u) : e ∩ e'

——————————————————————
Ω; Θ; Γ ⊢_term _ : ε

Ω; Θ; Γ ⊢ t : (unit ; e)
—————————————————————————————
Ω; Θ; Γ ⊢_term ltac:(t) : e 
```

Typing rule for toplevel tactic expressions:
```
Ω; Θ; a1:name+, ..., a_n:name+ ⊢ t : (unit ; e)
—————————————————————————————————————
a1:A1, ..., an:A_n ⊨ t ok
```
where `Θ` is an arbitrary list of distinct object-level names known to be distinct and where `a1:A1, ..., an:An` is a CIC environment (and its variables are turned into tactic variables denoting them).

Typing rule for toplevel tactic definitions:
```
α1 : hyps, ..., an : hyps ⊢ t : T
———————————————————————————————————
(LtacX f := t : ∀α1. ... ∀αn. T) ok
```
i.e., a tactic definition has to be of closed type (all names are quantified).
A few abbreviations:
```
Ω; Θ; Γ, x:name+  ⊢ t : (unit; e)
———————————————— when x not declared
Ω; Θ; Γ ⊢ intro ?x; t  :=  (let x := fresh nil "x" in intro x; t) : (unit ; e\x)

Ω; Θ; Γ ∪ (x:name+)  ⊢ t : (unit; e)
———————————————— when x declared of type name_- in Γ
Ω; Θ; Γ ⊢intro ?x; t  := (let x := fresh nil x in intro x; t) : (unit ; e\x)
```

I'm stopping here at the moment, but here are possible perspectives.

A useful extra primitive:
```
————————————————————————————————————————————————————
Ω; Θ; Γ ⊢ release_name : forall x:name-. (unit ; x†)
```

We could probably also consider row variables so that for instance the following (using Ltac syntax but Ltac2 is I guess similar):
```
Ltac f n x := match n with
              | 0 => x
              | S ?n => fun y => ltac:(let x := f n constr:(x y) in exact x)
              end
```
could be typed of type:
```
f : ∀ α. constr → constr[α] → constr[α]
```
where omitted information means ε.

The extended syntax would look like
```
l ::= ...
   | l,α    (a row variable refers to an abstract list of hypotheses)
```
Tactic schemes
```
S ::= T
   | ∀α. S  (generalization over a row variable)
```
and a generalization of the type would be done in `let`, or something like that.

We may also need subtyping of `constr[l]` ≤ `constr[l']` when `l` ⊂ `l'`.

2020-03-05 20:24 UTC, herbelin commented
> Your "funny example" shows that the semantics is broken for a naive function unfolding.

I did not get what `unfolding` means in your sentence.

In any case, that `fresh` takes a list of names to avoid is clearly an improvement.

-----

```coq
Require Import Ltac2.Ltac2.
Require Ltac2.List.

Ltac2 f _ :=
  let hyps := List.map (fun (id, _, _) => id) (Control.hyps ()) in
  let n := Fresh.fresh (Fresh.Free.of_ids hyps) @n in
  intros $n.
  
Goal nat -> nat -> nat.
Proof.
intros n; clear n; f @n.
Undo.
intro n; clear n; f @n.
```
Thanks, that helps to get familiar with Ltac2. With the conclusion on which we certainly agree: how to make it clear in the syntax of the language that `@n` in `f @n` is intended to be the name of the hypothesis that we cleared.

> But hacking an already fragile language is not the legitimate way to do that.

Making less fragile a language which is widely used does not seem wrong to me. It is a way to understand how things work and, ideally, we could be able to make the moves that will eventually make Ltac and Ltac2 different only in the syntax.

> Please first write a paper on the topic, with a proof (even a sketch would do!) that the type system enjoys some reasonable properties like "subject reduction".

I put some ideas above, where constraints are put on the typing so that the system is expected to be stable by substitution. The problem is however that I'm working on different things at the same time and I will not to reasonably be able to work full time on this specific question. So, at the current time, it is a "bottle in the sea".

2020-03-19 14:16 UTC, ppedrot commented
@herbelin good luck trying to prove any property for this system in a language that does not even have a proper notion of substitution. In the meantime, I think this PR can be closed.

2020-03-19 14:22 UTC, herbelin commented
@ppedrot: Could we please have a serious discussion?
1. This PR fixes an inconsistency between `intro` and `intros` and in this sense, I consider that it is good.
2. When I'm discussing a typing system, I'm not particularly targetting Ltac1 but Ltac2, which do have typing. I'm not saying that this does not need more thinking, I'm saying that this is an interesting discussion to have. Don't you really think?

2020-03-19 14:26 UTC, herbelin commented
PS: If the worry is to have too many open PRs, which I sympathetize with, then:
- regarding this one: I'm planning to continue to address the concerns of @jasongross and to defend that this PR is merged
- regarding typing with effects, this can of course go elsewhere than in this PR

2020-03-19 14:28 UTC, ppedrot commented
> This PR fixes an inconsistency between intro and intros and in this sense, I consider that it is good.

OK, but the correct fix is the dual one, I believe. Also, I am not wasting any more time in convincing you that static-ish binders don't make any sense, but you would be kind enough not trying to add more technical debt when I am in parallel trying to decrease it in other places.

> I'm not saying that this does not need more thinking, I'm saying that this is an interesting discussion to have.

A *pull request* is not the place for that, though.

2020-03-19 18:32 UTC, herbelin commented
> OK, but the correct fix is the dual one, I believe.

If you mean:
1. that we should reject also `Ltac f := intros x; apply x.`, I actually agree, in the sense that forcing a name to be exactly `x` is against universal applicability of the function;
2. that we should not preserve the binding between the two occurrences of `x` in `Ltac f := intros ?x; apply x` or `Ltac f := refine (fun x => ltac:(apply x))`, both to be interpreted as `Ltac f := let x := fresh "x" in intros x; apply x.` (*), - also taking into account possible `clear`s inbetween -, then, I'm less convinced;

   (*) that is, as far as I could see:
   ```
   Ltac2 f _ := let hyps := map (fun (id, _, _) => id) (Control.hyps ()) in
     let n := Fresh.fresh (Fresh.Free.of_ids hyps) @n in
     let nc := Control.hyp n in
     intros $n; apply $nc.
   ```

As for the toplevel tactics, I'd like a better story than dynamically interpreting a name depending on the runtime context, but I agree that this would break a lot of existing scripts.

I will think at an intermediate solution which takes 1. above into account.

2020-03-21 15:22 UTC, herbelin commented
> Also, I am not wasting any more time in convincing you that static-ish binders don't make any sense, but you would be kind enough not trying to add more technical debt when I am in parallel trying to decrease it in other places.

@ppedrot: I appreciate all the work you are doing in building the code around better invariants, in avoiding too heterogeneous behaviors, in taking extremely seriously the challenge of a safe, robust and well-thought system.

My point is not against these objectives to which I rally. The point here is only that binders are anyway there in a tactic language, including the issues of erasure and renaming, and we cannot escape that fact. In particular, until I see a proof of the contrary, I'll continue to consider that we have a story to tell about binders in Ltac2 which we could be proud about (as an example, why couldn't we try to statically reject the following code `Ltac2 g n := let nc := Control.hyp n in intros $n; clear $n; apply $nc.`?).

2020-04-15 18:02 UTC, herbelin commented
I agree that allowing `Ltac f := intro x; tac` or `Ltac f := intros x; tac` is not what we want compared to instead rejecting both because `x` should be taken fresh for more robustness (and thus recommending either `Ltac f := let x := fresh "x" in intros x; apply x.` or `Ltac f := intros ?x; tac.`, but in the current state, I don't find satisfactory the discrepancy between `intro` and `intros` and I'm still thinking that the PR is better than the status quo. Moreover, I'm also confident that the investigations made in this PR about managing the side effects of context-modifying tactics will be benefitable for Ltac2.

2021-09-04 19:31 UTC, closed without merging