Ltac2: Add notation for enough and eenough
coq/coq pull request #11740
Opened 2020-03-03 13:51 UTC by MSoegtropIMC

This PR adds notations for `enough` and `eenough`. I reused the parser for assert which extends the syntax for enough to also accept a pose via `enough (H:=witness)` but I don't see a good reason why this should be possible in assert and not in enough. `enough by` is supported in the traditional tactic language, which has similar semantics to `enough (H:=witness)` and there is also no difference between `assert by` and `enough by`.

**Kind:** feature

- [ ] Added / updated test-suite

- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

2020-03-04 08:45 UTC, MSoegtropIMC commented
Can someone help me with restarting the gitlab CI? I even tried to start a pipeline manually but it does not work. It says the merge request does not exist, but it looks correct to me. @Zimmi48 : some coqbot issue?

I think coqbot or gitlab doesn't like the quick pushes but one has to do it if one adds a change log entry, because the change log entry can only be added after creating the PR since one needs the PR number. So I always do 2 commits in quick succession and around 1/4 of them then have this issue. How do others do this? Should I not do squashes?

2020-03-04 10:18 UTC, ppedrot commented
My personal experience is that the CI gets stuck quite often, regardless of the time elapsed between the different pushes. It was conjectured that that was due to some quota exhaustion, but I have no real idea.

2020-03-04 10:52 UTC, Zimmi48 commented
> Can someone help me with restarting the gitlab CI? I even tried to start a pipeline manually but it does not work. It says the merge request does not exist, but it looks correct to me. @Zimmi48 : some coqbot issue?
> 
> I think coqbot or gitlab doesn't like the quick pushes but one has to do it if one adds a change log entry, because the change log entry can only be added after creating the PR since one needs the PR number. So I always do 2 commits in quick succession and around 1/4 of them then have this issue. How do others do this? Should I not do squashes?

The problem is known (#11320). It is a new GitLab limitation. We have a workaround which is to click on the big "Cancel" button for the pipeline and then "Retry". We could try to change the way @coqbot pushes to GitLab to avoid triggering this limitation. I haven't yet had time to look into this but I will eventually.

2020-03-04 14:23 UTC, MSoegtropIMC commented
@Zimmi48 : thanks for the hint and for restarting!

2020-03-05 11:34 UTC, ppedrot requested changes
The Ltac1 syntax also accepts a `by tac` argument, you should handle that as well.

2020-03-05 18:15 UTC, MSoegtropIMC commented
> The Ltac1 syntax also accepts a `by tac` argument, you should handle that as well.

That is handled, see the 3rd test case. The only difference I know of compared to ltac1 is that this also handles `enough(H := term)` which is translated to `pose proof term as H`. Ltac1 does not support this (afaik).

2020-03-06 07:23 UTC, ppedrot commented
Oops, sorry, I am not even able to read the code properly. Looks fine then. As for the extended syntax, it probably makes it more uniform compared to `assert` so it cannot hurt. It is actually one of the advantage, I believe, of Ltac2, namely that it forces to reuse a smaller set of primitive scopes, thus forcing to have a uniform syntax.

2020-03-06 07:23 UTC, ppedrot approved these changes

2020-03-06 08:22 UTC, MSoegtropIMC commented
> It is actually one of the advantage, I believe, of Ltac2, namely that it forces to reuse a smaller set of primitive scopes, thus forcing to have a uniform syntax.

Indeed I like Ltac2 very much - it is a very substantial improvement for industrial users where maintainable domain specific automation is key. It is much cleaner and easier to understand than Ltac1, it is much faster in execution, it is easier to extend, it is strongly typed and thus easier to maintain and to develop larger systems and it allows full access to the Coq term structure. I remember the times when I needed a quod libet sandbox to supply arguments to a function just to see if I get something in the end I can destruct and all that just to decide if that function was a constructor symbol. It was sort of fun, but I don't really miss it. Ltac2 is so much more fun ;-)

Well done - many thanks!

2020-03-07 23:29 UTC, merged