[ltac] Remove compat tactic notation entry mechanism
coq/coq pull request #11777
Opened 2020-03-08 07:25 UTC by ejgallego

This seems unnecessary as the same can be achieved in `Tacarg`.

It seems that going thru a deprecation phase could be convenient.

- [ ] Entry added in the changelog

2020-03-08 11:35 UTC, ppedrot commented
What do you mean by "the same can be achieved in `Tacarg`"? Also, as you can see from the CI, there is a reason for these compat notations to be there. Removing them requires a deprecation phase.

2020-03-08 18:02 UTC, JasonGross requested changes
Replacing `hyp` (documented at https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#tactic-notations ) with `var` (undocumented) requires more justification than is given here.  I personally think the documented names are fine, and would be in favor of removing the undocumented aliases of the documented names.

2020-03-08 19:32 UTC, ppedrot commented
@ejgallego also, engineering-wise, I think it is better not to rely on the genarg name for user-facing tactic notation entries. That is, everything should go through the indirection map. This ensures better separation of concern, potential implementation via kernames instead of strings, genargs not reachable from tactic notations and so on so forth.

2020-03-08 20:15 UTC, ejgallego commented
> @ejgallego also, engineering-wise, I think it is better not to rely on the genarg name for user-facing tactic notation entries. That is, everything should go through the indirection map. This ensures better separation of concern, potential implementation via kernames instead of strings, genargs not reachable from tactic notations and so on so forth.

Ok let me think; that's another possibility indeed. I'm just a bit wary of that as it seems we'd basically re-declare most genars at the tactic notation level tho, right?

2020-03-30 23:03 UTC, ejgallego commented
After thinking a bit more, let's delay this for now.

2020-03-30 23:03 UTC, closed without merging