Grants #11692: clear dependent knows about let-in
coq/coq pull request #11822
Opened 2020-03-13 17:27 UTC by herbelin

**Kind:** small enhancement

Fixes / closes #11692

The code was in Ltac and we simply add the missing cases for let-ins. This does not fix #11691 (error message) nor #11689 (efficiency) though, which I don't know well how to address in pure Ltac.

Could it be written in Ltac2 instead?

- [X] Added / updated test-suite
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

2020-03-13 18:19 UTC, JasonGross requested changes
Thanks!

2020-03-13 18:19 UTC, JasonGross commented on theories/Init/Tactics.v
> +   | H := [ ?x ] : context [ h ] |- _ => depclear H; depclear h
This line is not needed, and should be removed.  The first branch catches every case that this catches; this branch is looking for hypotheses whose bodies are singleton lists with `h` in the context of the type...

2020-03-13 18:31 UTC, JasonGross commented
> Could it be written in Ltac2 instead?

Indeed it could be transcribed to Ltac2, but I don't see the point right now (unless we want to start slowly migrating tactics to Ltac2?)  We could indeed write a version of this tactic in Ltac2, but it would be quite slow.  The "correct" behavior is to look not just for `h` in the context of the type/body, but also to look for any section-local definition mentioned in the type/body, and to check if any of those definitions (recursively) mention `h`.  There is currently no way, from Ltac(2), to check if a definition is section-local.  I can code up a hacky alternate version of the code that supports section definitions, but I'm not sure if it's worth it.

2020-03-13 18:45 UTC, JasonGross commented
Here is a version that handles more edge cases, but it's not clear to me if it should go in: https://github.com/coq/coq/issues/11691#issuecomment-598863282  I think this deciding whether or not the more powerful version should go in should not block this PR, which is a clear improvement for basically no cost.

2020-03-13 23:09 UTC, JasonGross approved these changes

2020-03-19 11:30 UTC, ppedrot approved these changes

2020-03-19 11:30 UTC, ppedrot commented
Let's merge this fix for the time being.

2020-03-19 11:31 UTC, merged