Allow empty expressions in `coqpp` rules.
coq/coq pull request #11910
Opened 2020-03-25 16:23 UTC by kindaro

**Kind:** feature

`coqpp` is based on `camlp5`, but there is a distinction. Unlike `camlp5`, `coqpp` does not allow rules without associated expressions. That is, `meow: [ [ "meow" ] ];` seems to be legal as per `camlp5` docs, but `coqpp` gives parser error and requires me to write the more verbose `meow: [ [ "meow" -> { [ ] } ] ];` with an explicit expression.

It would seem a pointless change, but I will shortly present a fix for #4446 and other similar changes that would altogether be cleaner with this feature.

I tried my best, but I am new to Coq and Ocaml, so I hope someone with more familiarity with the code base would be available to help me bring this effort to fruition.

2020-03-25 16:27 UTC, kindaro commented
See #11911 for why this may be useful.

2020-03-25 17:53 UTC, ppedrot requested changes
I think it complicates the parser for no good reason. Actually, this was one of the features of campl5 I found puzzling. `coqpp` should strive for simplicity, let's not reintroduce all the campl5 historical code...

2020-03-25 17:54 UTC, Zimmi48 commented
@ppedrot Did you read the PR that relies on this?

2020-03-25 17:55 UTC, ppedrot commented
> `meow: [ [ "meow" -> { [ ] } ] ];`  with an explicit expression.

BTW, actually this should read `{ () }` because `[]` is the empty list, not the unit constructor.

2020-03-25 17:55 UTC, Zimmi48 commented
I was also expecting this to work recently and discovered that it didn't. The feature feels very intuitive to me.

2020-03-25 17:56 UTC, ppedrot commented
@Zimmi48 yes, and this is irrelevant to the PR. It only requires adding 12 more non-blank characters.

2020-03-25 19:13 UTC, kindaro commented
@ppedrot  It is a single principled change against any amount of noise throughout the code base. If you `grep -r '{ *( *) }' **/*.mlg`, you will see that this feature applies in several places already.

2020-04-11 00:14 UTC, herbelin commented
> The feature feels very intuitive to me.

Idem for me. The feature is common and expected. The complication in the parser is light. I think it makes sense to balance it with the change of habits it induces.

2020-04-11 08:40 UTC, kindaro commented
In case this will be considered for merging: should we also simplify the code identified by grep? I suppose it may make sense to add a commit to that end here.

2020-04-12 11:06 UTC, ppedrot commented
If this is candidate for merging, it still needs to be tweaked. The current grammar does not allow having an empty list of symbols when returning unit. For uniformity with the other rule, it should also allow parsing zero symbols.

2020-04-12 11:28 UTC, kindaro commented
@ppedrot  I cannot understand what _«current grammar»_ and what _«other rule»_ you are referring to. Can you explain in more detail?

2020-04-12 11:35 UTC, ppedrot commented
The original rule with an arrow allows `| -> { foo }` but the rule you added forces you to write at least one symbol as in `| s`. I believe that this should be uniform, thus the rule you added should also parse `| `.

2021-06-01 11:27 UTC, herbelin commented
@ppedrot: what is your expectation with this PR, are you willing to support it or are you afraid that it would make the code less robust? An additional remark is that the PR would restore a symmetry with the gramlib printer, as output by `Print Grammar`.

About parsing `|` alone, camlp5 actually used to allow it also (it is just about replacing `symbols` with `symbols_opt` then, right?).

2022-10-17 14:39 UTC, SkySkimmer commented
Doesn't seem likely to be merged without interest from parser maintainers.

2022-10-17 14:39 UTC, closed without merging