No more local reduction functions in Reductionops.
coq/coq pull request #11922
Opened 2020-03-26 14:03 UTC by ppedrot

This is extracted from #9710, where we need the environment anyway to compute iota rules on inductive types with let-bindings. The commit is self-contained, so I think it could go directly in to save me a few rebases.

Furthermore, this is also related to #11707. Assuming we split cbn from the other reduction machine, this allows to merge the "local" machine with the general one, since after this PR they will have the same type. One less reduction machine should make people happy.

2020-03-26 14:07 UTC, Matafou approved these changes

2020-03-30 11:10 UTC, SkySkimmer commented on pretyping/reductionops.ml
> +let local_whd_state_gen flags env sigma =
```suggestion
let local_whd_state_gen flags _env sigma =
```
to make it clear that env is deliberately ignored

2020-03-31 20:03 UTC, ppedrot commented
This is ready.

2020-04-01 15:12 UTC, gares requested changes
please

2020-04-01 15:12 UTC, gares commented on pretyping/reductionops.mli
>  type local_reduction_function = evar_map -> constr -> constr
remove this

2020-04-01 15:41 UTC, ppedrot commented on pretyping/reductionops.mli
>  type local_reduction_function = evar_map -> constr -> constr
Done.

2020-04-02 10:11 UTC, gares approved these changes

2020-04-29 10:45 UTC, ppedrot commented
@maximedenes ping

2020-05-06 20:12 UTC, herbelin commented
Do we try to merge this before the 8.12 branching since after all it is ready?

2020-05-06 20:18 UTC, gares commented
It needs a rebase. It @maximedenes is busy I can take care of this, after all I reviewed it

2020-05-06 22:18 UTC, ppedrot commented
Rebase performed, let's see how it fares.

2020-05-10 09:28 UTC, maximedenes commented
@ppedrot there seems to be a lot of failures

2020-05-10 13:02 UTC, ppedrot commented
Something went wrong with the CI infrastructure, they are all weird timeouts. I'll rebase again.

2020-05-10 20:50 UTC, ppedrot commented
SF is broken, but this is unrelated to this PR. So this looks good to me.

2020-05-12 14:34 UTC, Zimmi48 commented
@maximedenes Time to merge?

2020-05-14 14:35 UTC, merged

2020-05-14 17:58 UTC, ejgallego commented
@maximedenes you forgot to notify the overlay's upstream to merge.