[stdlib] update sigma-type notations
coq/coq pull request #11957
Opened 2020-03-29 17:02 UTC by olaure01

Some spaces were missing in sigma-type notations.
Some missing notations are also added.
Summary:
```
Check { x | x = 1 }.
Check { x | x = 1 & 0 < x }.
Check { x : nat | x = 1 }.
Check { x : nat | x = 1 & 0 < x }.
Check { x & x = 1 }.
Check { x & x = 1 & 0 < x }.                 (* new *)
Check { x : nat & x = 1 }.
Check { x : nat & x = 1 & 0 < x }.

Check {'(x,y) | x = 1 }.
Check {'(x,y) | x = 1 & y = 0 }.             (* add space after & *)
Check {'(x,y) : nat * nat | x = 1 }.
Check {'(x,y) : nat * nat | x = 1 & y = 0 }. (* add space after & *)
Check {'(x,y) & x = 1 }.                     (* new *)
Check {'(x,y) & x = 1 & y = 0 }.             (* new *)
Check {'(x,y) : nat * nat & x = 1 }.         (* add space after & *)
Check {'(x,y) : nat * nat & x = 1 & y = 0 }. (* add space after both & *)
```

**Kind:** feature.

2020-03-29 17:22 UTC, JasonGross commented on theories/Init/Specif.v
>  Notation "{ x : A  & P  & Q }" := (sigT2 (A:=A) (fun x => P) (fun x => Q)) :
```suggestion
Notation "{ x  &  P  &  Q }" := (sigT2 (fun x => P) (fun x => Q)) : type_scope.
Notation "{ x : A  &  P }" := (sigT (A:=A) (fun x => P)) : type_scope.
Notation "{ x : A  &  P  &  Q }" := (sigT2 (A:=A) (fun x => P) (fun x => Q)) :
```

2020-03-29 17:22 UTC, JasonGross commented on theories/Init/Specif.v
>  Notation "{ ' pat : A  & P  & Q }" := (sigT2 (A:=A) (fun pat => P) (fun pat => Q)) :
```suggestion
Notation "{ ' pat  &  P }" := (sigT (fun pat => P)) : type_scope.
Notation "{ ' pat  &  P  &  Q }" := (sigT2 (fun pat => P) (fun pat => Q)) : type_scope.
Notation "{ ' pat : A  &  P }" := (sigT (A:=A) (fun pat => P)) : type_scope.
Notation "{ ' pat : A  &  P  &  Q }" := (sigT2 (A:=A) (fun pat => P) (fun pat => Q)) :
```

2020-03-29 17:33 UTC, olaure01 commented on theories/Init/Specif.v
>  Notation "{ x : A  & P  & Q }" := (sigT2 (A:=A) (fun x => P) (fun x => Q)) :
I just did minimal copy-paste and modifications using already defined stuff.
Do these additional spaces make any difference?

2020-03-29 18:20 UTC, JasonGross commented on theories/Init/Specif.v
>  Notation "{ x : A  & P  & Q }" := (sigT2 (A:=A) (fun x => P) (fun x => Q)) :
I think either the spacing in the notation should match the spacing in the reserved notation, or else there should just be one space everywhere in the notation itself.  I *think* the spacing doesn't matter in the notation when there's also a `Reserved Notation` with either extra spaces or a format specifier, but I'm not sure; I think we'd either need to test it or have @herbelin clarify.
Either way, I think it's a bit confusing to have extra spaces in only some places but not others in the `Notation` when they serve no purpose.

2020-03-30 15:54 UTC, olaure01 commented
This new version has a more uniform use of spaces.
It works as expected for the tests in the top of this PR.
Maybe an expert in `Notation` should have a look to make sure everything is done appropriately.

2020-03-30 15:59 UTC, JasonGross requested changes
I should have asked for this before, but please update the test-suite in `test-suite/output` (either pick a file that has an appropriate name or make a new one) with all the examples from the PR comment, so that we don't accidentally backtrack on this.

2020-03-30 17:14 UTC, olaure01 commented
No problem, done.

2020-03-30 17:21 UTC, JasonGross approved these changes

2020-03-30 17:21 UTC, JasonGross commented on theories/Init/Notations.v
> +Reserved Notation "{ x | P }" (at level 0, x at level 99).
I'm a bit confused about why this one doesn't need spaces.  @herbelin ?

2020-04-11 00:01 UTC, herbelin commented on theories/Init/Notations.v
> +Reserved Notation "{ x | P }" (at level 0, x at level 99).
There is a heuristic to add spaces by default around symbols which are not parentheses. When no `format` is given, the `|` and `&` take spaces around by default (this is in `Metasyntax.make_hunks` but the rules are a bit complex).

2020-04-11 00:06 UTC, herbelin commented
I like the changes. So, I guess I can assign and plan a merge say for Tuesday.

Incidentally, on another topic, we should really provide notations for `existT` (maybe `(x;y)`).

Another question is also to support n-ary `sigT`. This was discussed at some time, suggesting to use `sigma x y z, T` by analogy with `exists` (but this would be a radically different style than `{x y z & T}`).

2020-04-11 08:44 UTC, olaure01 commented
@herbelin 
> Incidentally, on another topic, we should really provide notations for `existT` (maybe `(x;y)`).

It is a local notation in `Specif.v`:
```coq
Local Notation "( x ; y )" := (existT _ x y) (at level 0, format "( x ;  '/  ' y )").
Local Notation "x .1" := (projT1 x) (at level 1, left associativity, format "x .1").
Local Notation "x .2" := (projT2 x) (at level 1, left associativity, format "x .2").
```

2020-04-14 20:25 UTC, merged