Adding a Declare ML Module in empty file Ltac.v
coq/coq pull request #12023
Opened 2020-04-05 12:19 UTC by herbelin

Indeed, it would be intuitive that `Require Import Ltac` is parallel to `Require Import Ltac2.Ltac2` for `Ltac`??

Also declaring the classic proof mode.

**Kind:** bug fix

Fixes / closes #10746

- [ ] Entry added in the changelog (not needed?)

2020-04-05 12:58 UTC, Zimmi48 commented
See also #11026.

2020-04-05 13:01 UTC, Zimmi48 reviewed
Shouldn't this module contain a comment explaining its use case (loading the `Ltac` plugin in `-no-init` mode)?

2020-04-05 13:02 UTC, Zimmi48 commented
To me this PR is a feature, so more appropriate for 8.12 (even if harmless) and it would be useful to have a changelog entry (see use case in #11026).

2020-04-05 14:07 UTC, herbelin commented
No opinion on 8.11 or 8.12, nor on whether this is the good fix. I let it to @ppedrot.

2020-04-05 18:33 UTC, ejgallego requested changes
If you load this here please remove it from `Notations.v`.

2020-04-05 19:09 UTC, herbelin commented
> If you load this here please remove it from `Notations.v`.

Very good point indeed. Now done.

2020-04-05 19:24 UTC, ejgallego approved these changes

2020-04-05 19:25 UTC, ejgallego commented
Umm, this complicates the build setup quite a bit, not sure it is worth it maybe.

2020-04-05 19:27 UTC, Zimmi48 commented
Indeed, not so clear. That's why I didn't request this.

2020-04-05 21:06 UTC, ppedrot commented
I support this change, and was actually pondering about it recently. But I think I remember that last time we tried, when integrating Ltac2, we faced troubled and gave up.

2020-04-05 21:08 UTC, ppedrot commented on theories/ltac/Ltac.v
> +Global Set Default Proof Mode "Classic".
`Export` should probably used instead of `Global`, since anybody importing the prelude will also export this.

2020-04-05 21:08 UTC, ppedrot commented on theories/ltac/Ltac.v
> +Global Set Default Proof Mode "Classic".
`Export` should probably used instead of `Global`, since anybody importing the prelude will also export this.

2020-04-05 21:13 UTC, ejgallego commented
> Indeed, not so clear. That's why I didn't request this.

Yeah, let's not complicate more the `-noinit` rules; a way to do it is place the `Ltac.v` file in `Init`.

2020-04-05 21:17 UTC, ejgallego commented
Personally I wouldn't add this 8.11.2

2020-04-05 21:54 UTC, herbelin commented on theories/ltac/Ltac.v
> +Global Set Default Proof Mode "Classic".
Done.

2020-04-05 21:55 UTC, herbelin commented
> Personally I wouldn't add this 8.11.2

OK, moved to 8.12.

> a way to do it is place the Ltac.v file in Init.

Wouldn't this create an asymmetry with Ltac2?

> when integrating Ltac2, we faced troubled and gave up.

Apparently, this changes some global names of atomic tactics (such as `Coq.Init.Notations.reflexivity`), but that seems for the good...

2020-04-05 23:37 UTC, ejgallego commented
> Wouldn't this create an asymmetry with Ltac2?

Prelude doesn't depend on `Ltac2` so indeed I think they are far from comparable; also, `Ltac2` is compiled with the prelude in scope [even I think it doesn't need it].

2020-04-06 07:59 UTC, Zimmi48 commented
> > Wouldn't this create an asymmetry with Ltac2?
> 
> Prelude doesn't depend on `Ltac2` so indeed I think they are far from comparable; also, `Ltac2` is compiled with the prelude in scope [even I think it doesn't need it].

But at some point in some far away future, we might want to remove Ltac1 from the prelude and make parts of the standard library (possibly even the prelude) depend of Ltac2.

2020-04-06 14:21 UTC, Zimmi48 commented
> Apparently, this changes some global names of atomic tactics (such as `Coq.Init.Notations.reflexivity`), but that seems for the good...

This change seems indeed to make sense. OTOH, this is what causes the failures in fiat-crypto and MetaCoq, and explains the need for overlays.

2020-04-06 19:38 UTC, ejgallego commented
> But at some point in some far away future, we might want to remove Ltac1 from the prelude and make parts of the standard library (possibly even the prelude) depend of Ltac2.

Indeed, but that'd be far from trivial I think, moreover this change would help little with that.

As for what this PR is concerned I backtrack on my original advice and indeed I'd rather prefer we keep `theories/Init` as the only folder with special build rules.

2020-04-10 22:33 UTC, herbelin commented
I got a bit lost. Is the conclusion to have `Ltac.v` in `Init` and the paths to atomic ML-defined tactics be of the form `Coq.Init.Ltac`? By the way, is it expected that it defines tactic names qualified by the name of the file that loaded the Ltac plugin. Any file which loads the plugin would thus define its name space for ML atomic tactics?

2020-04-10 22:36 UTC, ejgallego commented
Sorry for the confusion @herbelin ,

> I got a bit lost. Is the conclusion to have `Ltac.v` in `Init` and the paths to atomic ML-defined tactics be of the form `Coq.Init.Ltac`?

This is my suggestion for now, given how linked these two are; of course this should not block future improvements / refactoring.

IMO having a single "init" directory for now is pretty convenient.

> By the way, is it expected that it defines tactic names qualified by the name of the file that loaded the Ltac plugin. Any file which loads the plugin would thus define its name space for ML atomic tactics?

Good question.

2020-04-11 11:13 UTC, Zimmi48 commented
That makes sense to me.

2020-04-12 13:45 UTC, ppedrot commented
For backwards compatibility, you can probably redeclare the atomic tactics in Notations. But as for myself, I indeed prefer having these tactics be called `Coq.Init.Ltac.X`.

2020-04-15 17:53 UTC, herbelin commented
OK, then I moved `Ltac.v` in `Init` and removed the ad hoc `Makefile.build` rule.

I did not put compatibility with `Coq.Init.Notations` names (I don't know how to do it actually). So, I'd be leaning to instead provide overlays, unless someone has a suggestion!

2020-04-15 20:40 UTC, ejgallego commented
I'll help with as this is more in the realm of the build part than the stdlib itself. Let's see the compat impact.

2020-04-16 11:06 UTC, ppedrot commented
> I don't know how to do it actually

Just redeclare all the tactics declared by the ML code as aliases, e.g. `Ltac intro := intro`.

2020-04-16 11:18 UTC, herbelin commented
> Just redeclare all the tactics declared by the ML code as aliases, e.g. Ltac intro := intro.

As a temporary solution with deprecation you mean?

2020-04-16 11:23 UTC, ppedrot commented
@herbelin yes.

2020-04-18 05:19 UTC, ejgallego commented
Doc is broken, fix should be easy. Fiat crypto can be fixed either way with the compat or an overlay.

2020-04-18 12:34 UTC, herbelin commented
@ppedrot: would an overlay be so bad? I doubt a lot of people use qualified atomic tactics outside plugins and I'm afraid that a deprecation would not do what we expect. I.e., if I do:
```
#[deprecated( note = "Use ...")]
Ltac intro := intro.
Ltac h tac := tac.
Goal nat -> nat.
h intro. 
(* Warning: Tactic intro is deprecated. *)
```
the warning is issued even though the name is not qualified.

2020-04-18 13:15 UTC, ppedrot commented
@herbelin if it's too problematic, an overlay is fine indeed.

2020-04-19 08:43 UTC, herbelin commented
I initially put `Require Export Ltac` in `Notations`, but it seems to me that it would be better to add it in `Prelude.v`, together with enough `Require Import Ltac` in the other files of `Init`, wherever it is necessary. I added a commit in this direction. Tell me if not ok.

2020-04-19 11:11 UTC, Zimmi48 commented
This new change seems to have broken Unimath and the test-suite (VST failure is unrelated).

2020-04-19 11:51 UTC, herbelin commented
> This new change seems to have broken Unimath and the test-suite (VST failure is unrelated).

Hum, there are indeed some files loaded with `-noinit` and followed by the `Require` of one of the `Init` files.  What to do? Backtracking or turning all `Require Import Ltac` in those files into `Require Export`?

2020-04-19 11:54 UTC, Zimmi48 commented
If that's the issue, I feel like this change is still OK. I guess a simple `From Coq Require Import Ltac.` should be a backward compatible fix for Unimath.

2020-04-19 11:55 UTC, Zimmi48 commented
The incompatibilities, even if they are relevant to only very few projects, should be documented in the changelog.

2020-04-19 14:45 UTC, herbelin commented
I added a change log but I'm not very courageous to make an extra overlay. Let's give more time for a decision.

2020-04-20 10:13 UTC, Zimmi48 commented on doc/changelog/04-tactics/12023-master+fixing-empty-Ltac-v-file.rst
> +  qualifed with prefix ``Coq.Init.Ltac``
I would also add something like:

>Users of the `-noinit` option should now import `Coq.Init.Ltac` if they want to use Ltac.

2020-04-20 10:13 UTC, Zimmi48 commented on doc/changelog/04-tactics/12023-master+fixing-empty-Ltac-v-file.rst
> +  by Hugo Herbelin; source of incompatibilities).
```suggestion
  by Hugo Herbelin; minor source of incompatibilities).
```

2020-04-20 13:36 UTC, Zimmi48 commented
There's something odd. It seems that you have pushed two overlay files. Probably the previous one should be removed.

2020-04-22 11:01 UTC, ejgallego commented
This turned out to be trickier than anticipated but I guess we are ready to merge finally, thanks @herbelin .

Let's see what the CI says.

2020-04-22 11:21 UTC, ejgallego commented
@herbelin unfortunately it seems that you need to rebase your mtac2 branch; you can do so without rebasing this PR tho [and I will re-run the job]

2020-04-22 11:23 UTC, ejgallego commented
Failure seem a bit bizarre, on the other hand I'm wondering if this needs a changelog entry; I'd say yes, WDYT folks?

2020-04-22 11:26 UTC, herbelin commented
> This turned out to be trickier than anticipated

Indeed :phew:

>  it seems that you need to rebase your mtac2 branch

Done.

2020-04-22 11:48 UTC, ejgallego commented
Metacoq and Coqhammer are broken due to bad merge of #11896. 

Thus, modulo the changeset question this should be ready, let me known @herbelin what would you like to do w.r.t. it.

2020-04-22 11:55 UTC, ejgallego commented
> Metacoq and Coqhammer are broken due to bad merge of #11896.

Sorry I stand corrected, `metacoq` is also an overlay and also needs a rebase it seems; sorry @herbelin :/

2020-04-22 13:32 UTC, Zimmi48 commented
> I'm wondering if this needs a changelog entry; I'd say yes, WDYT folks?

Yes, and @herbelin has already written one.

2020-04-22 13:34 UTC, herbelin commented
> Sorry I stand corrected, metacoq is also an overlay and also needs a rebase it seems; sorry @herbelin :/

Done, ci restarted, now green for metacoq.

2020-04-22 16:36 UTC, ejgallego commented
> Yes, and @herbelin has already written one.

Sorry, I missed it indeed.

2020-04-22 16:39 UTC, merged