proposed fix for the issue #12015 (String_as_OT)
coq/coq pull request #12044
Opened 2020-04-07 16:42 UTC by formalize

**Kind:** bug fix

Fixes / closes #12015 

- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

2020-04-07 19:28 UTC, JasonGross requested changes
I would suggest moving all of the `ascii` comparison into its own module, `Ascii_as_OT`.  This module might be independently useful, and there's no reason to hide it inside the `String_as_OT` module.

2020-04-07 19:31 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +    end.
I think this might be a bit clearer as
```suggestion
    match a, b with
    | EmptyString, EmptyString => Eq
    | EmptyString, _ => Lt
    | String _ _, EmptyString => Gt
    | String a_head a_tail, String b_head b_tail =>
      match ascii_compare a_head b_head with
      | Lt => Lt
      | Gt => Gt
      | Eq => cmp a_tail b_tail
      end
    end.
```

2020-04-07 19:36 UTC, JasonGross requested changes
Here are some optional suggestions to clean up the proofs a bit.  Also, please consider indenting all the proofs by two spaces (see the other proofs in the file for comparison).)

2020-04-07 19:36 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +  generalize b. clear b.
```suggestion
  revert b.
```

2020-04-07 19:36 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +  destruct b. { easy. }
```suggestion
  induction a, b; cbn; try easy.
```

2020-04-07 19:36 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +  remember (ascii_compare _ _) as cmp. symmetry in Heqcmp.
Please don't use autogenerated names
```suggestion
  remember (ascii_compare _ _) as cmp eqn:Heqcmp. symmetry in Heqcmp.
```

2020-04-07 19:36 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +  generalize b. clear b.
```suggestion
  revert b.
```

2020-04-07 19:36 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +  intro b. destruct b. { easy. }
```suggestion
  induction a, b; try easy.
```

2020-04-07 19:36 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +  remember (ascii_compare _ _) as cmp. symmetry in Heqcmp.
```suggestion
  remember (ascii_compare _ _) as cmp eqn:Heqcmp. symmetry in Heqcmp.
```

2020-04-07 19:36 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +  generalize b. clear b.
```suggestion
  revert b.
```

2020-04-07 19:36 UTC, JasonGross commented on theories/Structures/OrderedTypeEx.v
> +  remember (ascii_compare _ _) as cmp. symmetry in Heqcmp.
```suggestion
  remember (ascii_compare _ _) as cmp eqn:Heqcmp. symmetry in Heqcmp.
```

2020-04-07 20:12 UTC, formalize commented
Thanks for the suggestions, I've committed them and written Ascii_as_OT.

2020-04-07 20:13 UTC, JasonGross approved these changes

2020-04-07 20:14 UTC, JasonGross commented
Thanks for the contribution, and LGTM!   I'll leave this for @coq/stdlib-maintainers to review and assign (though if no-one assigns after a couple days or a week, I can assign).

2020-04-07 20:15 UTC, JasonGross commented
Though you should probably also add a changelog entry, as the TODO list indicates.

2020-04-07 20:32 UTC, herbelin commented
> Thanks for the contribution, and LGTM! I'll leave this for @coq/stdlib-maintainers to review and assign (though if no-one assigns after a couple days or a week, I can assign).

Same as @anton-trunov. It looks good to me and you can go ahead.

2020-04-08 14:54 UTC, JasonGross commented
@herbelin Should we wait for a changelog entry?

@formalize Are you planning to add a changelog entry soon?

2020-04-08 15:50 UTC, formalize commented
Maybe next time. I don't want to do it yet.

2020-04-08 22:47 UTC, JasonGross commented
Okay, I'll write a changelog entry and open a separate PR for it

2020-04-08 22:48 UTC, merged