[stdlib] [Permutation] Declare more instances as Global
coq/coq pull request #12190
Opened 2020-04-27 17:29 UTC by olaure01

Because of `Section`s some instances are useless. They should be `Global Instance`s.

**Kind:** feature.

2020-04-30 15:00 UTC, olaure01 commented
This is mosly a patch on #11946. CI is ok (overlay merged in corn).
I think it should be merged before 8.12. @anton-trunov?

2020-05-06 20:15 UTC, anton-trunov approved these changes
I propose to merge this PR on May, 9th, if nobody has objections.

2020-05-06 20:26 UTC, JasonGross requested changes
Please don't make `_ : Equivalence _` resolve to `Equivalence Permutation_transp` rather than `Equivalence eq`.  Also, this needs benchmarking, typeclass resolution is notoriously sensitive to which instances are present and the order in which they are used, so I wouldn't be surprised if this adds a great deal of overhead to any developments which `Require` this file and don't make these instances themselves.

2020-05-06 20:26 UTC, JasonGross commented on theories/Sorting/Permutation.v
>   Proper ((@Permutation A) ==> (@Permutation B)) (flat_map g).
```suggestion
 Proper ((@Permutation A) ==> (@Permutation B)) (flat_map g) | 10.
```
Please don't make this instance global without giving it a higher-than-zero priority.  The default instance for `Proper _ (flat_map _)` should be `Proper (eq ==> eq) (flat_map g)`, and the default instance for `Proper _ (@flat_map A B)` should be either `Proper (pointwise_relation _ eq ==> eq ==> eq) (@flat_map A B)` or `Proper ((eq ==> eq) ==> eq ==> eq) (@flat_map A B)`.

2020-05-06 20:26 UTC, JasonGross commented on theories/Sorting/Permutation.v
> +Global Instance Permutation_transp_equiv : Equivalence Permutation_transp.
No!  Don't make it so that every instance search for `Equivalence ?R` tries to instantiate `?R` with `Permutation_transp` *first*.  (Really we should be adding a `Hint Mode` to `Equivalence` or something.  See also https://github.com/coq/coq/issues/4978
If you really want to do this as an instance, do
```suggestion
Global Instance Permutation_transp_equiv : Equivalence Permutation_transp | 100.
```
otherwise just add a hint
```coq
Hint Extern 0 (Equivalence Permutation_transp) => simple apply Permutation_transp_equiv : typeclass_instances.
```
to ensure that we only pick this up when we already know the relation.

2020-05-06 20:26 UTC, JasonGross commented on theories/Sorting/Permutation.v
>   Proper ((@Permutation A) ==> Basics.impl) (Forall P).
I'm not sure we want this to be picked up first, so I'm inclined to suggest
```suggestion
 Proper ((@Permutation A) ==> Basics.impl) (Forall P) | 1.
```
, but I won't push as strongly here as in the others

2020-05-06 20:26 UTC, JasonGross commented on theories/Sorting/Permutation.v
>   Proper ((@Permutation A) ==> Basics.impl) (Exists P).
idem.
I'm not sure we want this to be picked up first, so I'm inclined to suggest
```suggestion
 Proper ((@Permutation A) ==> Basics.impl) (Exists P) | 1.
```
, but I won't push as strongly here as in the others

2020-05-06 20:48 UTC, Zimmi48 commented
@olaure01 The documentation of the benchmarking infrastructure is here: https://github.com/coq/coq/wiki/Jenkins-(automated-benchmarking)
Do not hesitate to ask for help!

2020-05-08 12:55 UTC, olaure01 commented
@JasonGross Thanks a lot: it seems I have been playing with something I do not really understand... sorry.
The [benchmarking results](https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/934/console) do not look so bad for what I can see/understand.
However it looks clear that priorities have to be settled. This is done in the new version.

2020-05-08 12:57 UTC, olaure01 commented on theories/Sorting/Permutation.v
> +Global Instance Permutation_transp_equiv : Equivalence Permutation_transp.
I have not been able to use the `Hint Extern` approach for examples like:
```coq
Goal forall l : list nat, Permutation_transp l l.
reflexivity.
```
so I have put a high number as priority for the instance.

2020-05-10 23:13 UTC, JasonGross approved these changes

2020-05-11 10:28 UTC, ppedrot commented
FTR, our benchmarks are not good at catching the kind of problem potentially introduced by this PR. It might be the case that we catch a regression this way, but adding typeclass instances usually has an effect that is both limited in scope (w.r.t. the code affected) and serious (w.r.t. performance). More generally, typeclasses are well-known not to scale, neither for performance nor modularity.

(Not to say we shouldn't merge though. But you can be sure that somewhere there merely exists somebody who is going to complain about this PR...)

2020-05-11 10:32 UTC, olaure01 commented
Just to clarify:

- [benchmark](https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/934/console) is for the initial version of the PR: **without** instance priorities
- current PR is **with** priorities (not benchmarked)

2020-05-11 10:55 UTC, olaure01 commented
@Zimmi48 you put the label "needs: benchmarking" back, is there something precise I should do?

2020-05-11 10:59 UTC, Zimmi48 commented
I only removed it and backtracked on the removal when I saw your comment that you posted at the same time. Feel free to remove it again if benchmarking the new version is not needed.

2020-05-11 11:05 UTC, olaure01 commented
@Zimmi48 OK thanks, I thought it had been removed before.
I remove the label again since AFAIK new version can only go faster for development not using the new instances.

2020-05-12 14:58 UTC, Zimmi48 commented
@anton-trunov This seems ready to merge.

2020-05-12 15:02 UTC, merged

2020-05-12 15:03 UTC, anton-trunov commented
@Zimmi48 Thanks, done.