Make .merlin PHONY
coq/coq pull request #12212
Opened 2020-04-29 22:32 UTC by JasonGross

I presume making the non-existent merlin target PHONY was just a typo.

**Kind:** bug fix

Fixes / closes #????

- [ ] Added / updated test-suite (does this really need a test-suite case?)
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

2020-04-30 04:35 UTC, silene requested changes
This does not make sense at all. `.merlin` is an actual generated file. Do not make it `PHONY`!

If there really is a typo here, that is not the missing dot, that is the whole line.

2020-04-30 04:49 UTC, JasonGross commented
It does not make sense to have a non-PHONY target with no dependencies if the target is expected to ever change.  PHONY doesn't mean "this target is not a file"; it means "consider this target to be always out-of-date".  I don't think a user will ever want to "make .merlin only if it doesn't exist, regardless of whether or not it's out of date".  There aren't any targets that depend on .merlin, and I don't think it costs much more time to make .merlin than it does to spin up make.

2020-04-30 05:06 UTC, silene commented
You seem confused about the actual meaning of `.PHONY`. So, let me quote the documentation:

> A phony target is one that is not really the name of a file; rather it
> is just a name for a recipe to be executed when you make an explicit
> request.  There are two reasons to use a phony target: to avoid a
> conflict with a file of the same name, and to improve performance.

2020-04-30 05:17 UTC, silene commented
Also, I should mention that, if you really want `.merlin` to be always remade, then the solution is to use a double-colon rule, not a phony target. And I will again quote the documentation:

> Each double-colon rule's
> recipe is executed if the target is older than any prerequisites of that
> rule.  If there are no prerequisites for that rule, its recipe is always
> executed (even if the target already exists).

2020-04-30 09:08 UTC, SkySkimmer commented on doc/changelog/08-tools/12212-fix-merlin.rst
> +  (`#PRNUM <https://github.com/coq/coq/pull/12212>`_, by Jason Gross).
```suggestion
  (`#12212 <https://github.com/coq/coq/pull/12212>`_, by Jason Gross).
```

2020-04-30 11:47 UTC, gares commented
The point of having a PHONY `merlin` target was to be able to type `make merlin` even if a directory `merlin/` existed.

2020-04-30 11:49 UTC, gares commented
> If there really is a typo here, that is not the missing dot, that is the whole line.

So yes, either you remove the whole line (I don't think it is likely you have a merlin folder in a Coq project), or you leave things as they are, since there is not typo IMO.

2020-05-01 00:35 UTC, JasonGross commented
Thanks, @silene , indeed, I was mistaken, and I stand corrected.

> The point of having a PHONY `merlin` target was to be able to type `make merlin` even if a directory `merlin/` existed.

Ah, okay.  I think it's better to remove the whole line, then, as users who want a `merlin` target can make it `PHONY` on their own if they want.  I'll perhaps remove it in another PR.

I do think `.merlin` should either be double-colon, then, or else should depend on `Makefile.coq.conf` or something.

2020-05-01 00:35 UTC, closed without merging