Move CoqIDE to its own folder
coq/coq pull request #12337
Opened 2020-05-16 15:38 UTC by maximedenes

The will make it possible to put a VsCoq toplevel in `ide/vscoq`.

It's funny to compare what I had to do to adapt the `Makefile` build (see the patch below), compared to just moving the folder for Dune.

2020-05-16 16:38 UTC, MSoegtropIMC approved these changes
LGTM - will merge as soon as CI passes

2020-05-16 16:39 UTC, MSoegtropIMC commented
@maximedenes : let me know if you need help with the windows build ... I am way busy with 8.12+beta though, so it might take a few days.

Btw.: how is VSCoq doing? Is it usable meanwhile?

2020-05-16 16:57 UTC, Zimmi48 requested changes
This is not a hard request but I would prefer that the `protocol` files are not moved to a CoqIDE-specific folder since they are not CoqIDE-specific (despite what the name `coqidetop` seems to indicate). You could rename the `protocol` folder into `xmlprotocol` if you want.

BTW, I hope that you are not planning to call your VSCoq toplevel `vscoqtop` since it won't be VSCoq-specific either. What about reusing `coqidetop` instead and making it use a different protocol when the command-line flag `-lsp` is passed?

2020-05-16 17:15 UTC, ejgallego commented
> The will make it possible to put a VsCoq toplevel in `ide/vscoq`.

Why it is not possible to do this right now?

2020-05-16 17:23 UTC, ejgallego commented
Let's not super rush to merge this, but discuss a bit more about the folder org; anyways this kind of PR cannot be merged until we branch.

2020-05-16 17:25 UTC, ejgallego commented
> LGTM - will merge as soon as CI passes

@MSoegtropIMC note that our merging policy requires such large PRs to be open for a bit longer, so people can comment / provide feedback. In cases where the change is trivial we may try to sped up the process as to reduce workload, but this seems to qualify as a large change.

2020-05-16 17:42 UTC, MSoegtropIMC commented
> but this seems to qualify as a large change.

Thanks for the hint! I qualified this as just moving files and adjusting paths in the makefile, so with just dune it would have been a very small change, but I see now that there are discussions, so next time I will wait longer.

2020-05-16 17:43 UTC, ejgallego commented
> Why it is not possible to do this right now?

And, what is exactly supposed to go in the `vscode` folder?

2020-05-16 17:46 UTC, Zimmi48 commented
> > 
> 
> And, what is exactly supposed to go in the `vscode` folder? [I likely missed some discussion sorry]

IIUC this is the toplevel for the LSP protocol.

2020-05-16 17:52 UTC, ejgallego commented
> IIUC this is the toplevel for the LSP protocol (that's why I was saying it shouldn't be called `vscoq` or `vscode` since it will not be VSCoq-specific).

I see thanks; I guess we should see some more details then; writing a working coq-lsp server that works properly is an extremely difficult task; certainly I'd recommend developing such project outside of the Coq tree at least for the alpha phase.

2020-05-16 19:48 UTC, gares approved these changes
The patch is OK

2020-05-16 19:49 UTC, maximedenes commented
> I see thanks; I guess we should see some more details then; writing a working coq-lsp server that works properly is an extremely difficult task; certainly I'd recommend developing such project outside of the Coq tree at least for the alpha phase.

I don't see why this would be a requirement for moving CoqIDE-specific files to a dedicated folder.

2020-05-16 19:49 UTC, gares commented
>  I qualified this as just moving files and adjusting paths in the makefile

Indeed this change seems totally trivial to me. What is your concern @ejgallego ?

2020-05-16 19:51 UTC, gares commented
From: https://coq.gitlab.io/-/coq/-/jobs/555567955/artifacts/artifacts/buildlogs/coq-local-make_err.txt
```
make[1]: *** No rule to make target 'ide/ide_win32_stubs.o', needed by 'bin/coqide.exe'.  Stop.
make: *** [Makefile.make:178: submake] Error 2
```

2020-05-16 19:52 UTC, maximedenes commented
> This is not a hard request but I would prefer that the `protocol` files are not moved to a CoqIDE-specific folder since they are not CoqIDE-specific

AFAIK, that protocol is on the contrary very CoqIDE-specific. About naming the toplevel, no strong opinion, I did name it `vscoqtop` for now, but I'm open to other, more general names. Making it a `coqidetop` flag is possible, but it would probably amount to launching two different programs depending on the flag value...

2020-05-16 19:54 UTC, maximedenes commented
> Let's not super rush to merge this, but discuss a bit more about the folder org; anyways this kind of PR cannot be merged until we branch.

I agree this should be merged after branching. I opened the PR since the change is a bit cumbersome to maintain (it already cost me a few hours). I would appreciate if it gets merged reasonably quickly after branching.

2020-05-16 20:45 UTC, ejgallego commented
> I don't see why this would be a requirement for moving CoqIDE-specific files to a dedicated folder.

Well the PR starts with "The will make it possible to put a VsCoq toplevel in ide/vscoq." so I wonder, why it is not possible now?

> What is your concern @ejgallego ?

I don't have any concrete concern, just curious as why this change is needed; so far coqide-specific files are already in `ide` ; maybe a different organization would be better? Hard to tell without knowing more about the needs for `vscoq`.

2020-05-16 21:54 UTC, maximedenes commented
> Well the PR starts with "The will make it possible to put a VsCoq toplevel in ide/vscoq." so I wonder, why it is not possible now?

I see. My phrasing was incorrect, since it is obviously already possible to create an `ide/vscoq` folder. However, I find it better to separate CoqIDE-specific files from VsCoq files. If you think it is better to mix the two (even if they don't share anything), we can drop this PR as it becomes pointless.

2020-05-16 22:27 UTC, ejgallego commented
> My phrasing was incorrect, since it is obviously already possible to create an `ide/vscoq` folder. However, I find it better to separate CoqIDE-specific files from VsCoq files. If you think it is better to mix the two (even if they don't share anything), we can drop this PR as it becomes pointless.

I had no idea there was a plan to put vscoq in the Coq repos; indeed it could make sense to reorganize things; but I guess a bit more info on the vscoq plan would help.

What you propose here does make a lot of sense I think; in fact I already did propose this change (to follow the structure in https://github.com/ejgallego/coqide-exp) but concerns over file renaming were raised so I had to undo part of my changes in a costly rebase.

2020-05-16 22:41 UTC, maximedenes commented
> I had no idea there was a plan to put vscoq in the Coq repos

Not everything from VsCoq, of course, just the toplevel. This was discussed at the WG in Nantes. Anyway, this PR can be seen as a straightforward reorganization which is independent from VsCoq, and will benefit any UI that needs some first-class support from Coq.

2020-05-17 09:10 UTC, herbelin commented
> IIUC this is the toplevel for the LSP protocol (that's why I was saying it shouldn't be called vscoq or vscode since it will not be VSCoq-specific).

I'd be glad to real more details on the plans, or to read a page with relevant information. Here are a few questions to start with:

As far as I understand, vscode currently runs by calling `coqtop` directly. How will it work with LSP? Will there be a `coq-lsp` binary installed next to coqtop? Will there be two versions of vscoq, or a setting to choose the protocol? What features planned to be implemented? I'd be particularly interested in a graphical searching tool, completion, showing implicit information (disambiguation of notation, type of subterms, full name, implicit arguments, explicitation of coercions, ...), a switch between coqdoc/script views. Are there any plans regarding some of these? More generally, what is the roadmap and how can we help?

2020-05-17 09:36 UTC, maximedenes commented
This discussion feels out of place for a PR which is simply moving CoqIDE to a dedicated folder. @herbelin, can you post your questions in an issue on the VsCoq repo? Thanks!

2020-05-17 12:37 UTC, Zimmi48 commented
> As far as I understand, vscode currently runs by calling `coqtop` directly.

It calls `coqidetop`. Currently, there is a VSCoq toplevel that sits between the XML protocol and the UI itself. It is written in Typescript. The goal is simply to rewrite it in OCaml and to have it call the Coq API directly to avoid some quirks of the XML protocol. Because of how OCaml code requires being built with the exact same version of OCaml than Coq, etc., distributing VSCoq with an OCaml toplevel would be much more difficult if this OCaml toplevel was not part of Coq itself. And this would put a barrier to the use of VSCoq, which is something we'd like to avoid. But this VSCoq toplevel should really be viewed as a part of VSCoq more than a part of Coq, even if it is distributed with Coq.

2020-05-17 12:42 UTC, Zimmi48 approved these changes
I amend my earlier suggestion: I propose to rename the current `protocol` directory into `coqidetop`. Therefore, the new structure in `ide` would be `ide/coqidetop`, `ide/coqide` and `ide/vscoqtop`. But again, this is only a soft suggestion, which is why I'm turning my review into an "Approve" (I don't think this PR should be blocked as long as the `v8.12` branch has been created.)

2020-05-17 15:18 UTC, ppedrot approved these changes
This change is trivial and as a CoqIDE maintainer, I fully support it.

Actually, I also like @Zimmi48's idea of moving up the `protocol` folder into `coqidetop`, but this can be performed after the merge of this PR if this is deemed a worthy change.

2020-05-17 16:58 UTC, herbelin commented
@Zimmi48: In your previous [comment](https://github.com/coq/coq/pull/12337#issuecomment-629682421) you were talking about LSP. So, I thought the objective was about LSP, which I'm looking forward very much. If it is instead your last comment that I should believe, then, it is just about making a custom variant of coqidetop for vscoq, which of course is good also. In particular, no objection on a `ide/coqidetop`, `ide/coqide` and `ide/vscoqtop` architecture (or whatever structure which reflects the diversity of interfaces and protocols). Thanks for the clarification.

@maximedenes: I'm sorry if you felt my question out of scope. There are a lot of expectations about LSP and I think it is important that we synchronize altogether from time to time on our directions. If you prefer to answer elsewhere I'd be happy to see answers e.g. at the LSP meta issue #9012. This does not have necessarily to be answers from you actually if you feel uncomfortable in answering. Maybe @Zimmi48 or @ppedrot know the answers and may explain. I don't propose a reply at the VsCode repo, since my questions are really more about LSP, which as far I understood from what you and others already said is the optimal way to provide UI features (first because a Coq-based client has more informations about the logical structure of a document than the UI and is more liable to provide interesting feedback, second because this would be applicable at once to all UIs supporting LSP). In any case, if needs to be said, be assured that I'm glad and supportive of your contribution to vscoq.

2020-05-17 17:36 UTC, gares commented
I don't see the `needs: branching` label I saw mentioned elsewhere. Anyway, the build on windows needs fixing, I hope I pointed you in the right direction.

2020-05-17 18:10 UTC, Zimmi48 commented
@herbelin
>In your previous comment you were talking about LSP. So, I thought the objective was about LSP, which I'm looking forward very much. If it is instead your last comment that I should believe, then, it is just about making a custom variant of coqidetop for vscoq, which of course is good also.

The two comments are not contradictory. This custom toplevel that VSCoq uses which is currently written in Typescript is the one that speaks the LSP protocol. However, the way it is currently written is very clumsy since it converts this protocol into the XML protocol (despite the two being misaligned) in order to talk to `coqidetop`. The toplevel `vscoqtop` written in OCaml will speak the exact same LSP as the one of today that is written in Typescript. What it will avoid is the indirection.

I changed a bit my language between the two comments because in the first I was talking about LSP generically, whereas the goal of this PR (and the forthcoming PRs) is more specifically about VSCoq support (as @maximedenes made clear). In particular, the goal here is not to redesign the LSP support in the smartest way but just to improve the support for what is already there. As a consequence, it makes sense that the toplevel is called `vscoqtop` instead of `coqidetop -lsp` which I was suggesting earlier. But in the long run, this could be a good basis of experimentation, to make this protocol evolve and support the need of many UIs.

>which as far I understood from what you and others already said is the optimal way to provide UI features

That's not fully clear yet. But what is clear is that at least VSCoq needs this LSP support, and later on it could simplify the implementation of Coq support in other editors.

2020-05-17 18:34 UTC, herbelin commented
Thanks for this new clarification. There are things I still don't understand though.

At the last WG, it was told that the point of LSP is that features (such as completion, information about a subexpression at some location of a document, classification and highlighting of tokens, ...) were done by a coq server (the coq-lsp you were talking about previously I guess) and the UI was only requesting informations from the server using a standardized protocol.

Thus, as far as I understand, there are two aspects in using LSP: first to implement the communication/protocol, second to implement the features.

For the first part, what is specific to vscode? If specific to vscode (and why?), what will have to be done so that other LSP-compliant UIs can communicate to the server?

For the second part, what features are already implemented and what others are planned to be implemented?

Note that I don't exclude that I misunderstood some points of the story. But I think it is worth to explain where we are going, and eventually to tell how others can contribute, typically by adding new features.

2020-05-18 13:14 UTC, Zimmi48 commented
> At the last WG, it was told

I don't recall a discussion about LSP at the last WG, so I'm assuming you are referring to the Nantes WG which I missed.

>first to implement the communication/protocol, second to implement the features

A number of such standard features are even already implemented in editors with LSP support. However, proof assistants like Coq also need to extend the standard LSP, so some editor-specific code is still needed to handle these extensions. Nonetheless, one could dream of a standardization of these proof-assistant extensions (we are very far from this point though). Then, a single editor-support package would handle all the proof assistants providing this standard extended LSP (going back to the initial vision of Proof General).

>For the first part, what is specific to vscode?

AFAIU nothing is specific to VsCode. However, the pragmatic approach was to acknowledge that there was a strong need for VsCode support and that there already existed a VsCode package (VSCoq). Thus, last summer, I encouraged @maximedenes to take over VSCoq to fill this need quickly (even if we knew that it was far from perfect). That's when the fork in coq-community was created.

Now that @maximedenes has fixed the most urgent things in VSCoq, the next step (that he's currently undertaking) is to remove the fragility coming from the intermediate toplevel between `coqidetop` and VSCoq. At that point, we are still not talking about introducing new features, just about having a more robust implementation for those that are already provided.

Only after this initial phase, will it make sense to start a wider discussion (hopefully involving many UI maintainers) about the ideal design for LSP support in Coq. It could result in something close to the experimental `vscoqtop` or from something that differs significantly. This will also be the time to talk about all the features that we wish to provide.

Does this answer your questions?

2020-05-18 14:06 UTC, gares commented
> Only after this initial phase, will it make sense to start a wider discussion

I agree, only once we have a minimal working lsp toplevel we can really start playing with extensions.

2020-05-19 17:24 UTC, herbelin commented
@Zimmi48, @gares: Thanks for these comments. Somehow, my point is that it is hard for me to visualize the kind of work which is needed. I can visualize what it means to highlight, to provide completion, to provide a graphical search tool. I see how the CoqIDE completion tool works. I see how highlighting is done in CoqIDE and how it could be done by relying instead on what the Coq parser provides. I see what a graphical search tool can look like and how it could translate the graphical input into Coq `Search` requests.

On the other side, LSP looks to me very abstract, both in what it means to implement the protocol and in how features like highlighting, completion, or search would be implemented over LSP. The only thing I (believed to) understand (from the last WG, around the end) is that Coq would have a copy of the document with locations and would answer requests of the form "give me information about the segment of the document at location foo".

More generally, any simple hint explaining how LSP works, what it provides, and how a proof assistant can use the LSP API (for instance, randomly, how Coq could exploit the `DocumentSymbol` feature of LSP?) would be helpful to get a better understanding at the situation.

2020-05-19 17:46 UTC, Zimmi48 commented
>The only thing I (believed to) understand (from the last WG, around the end) is that Coq would have a copy of the document with locations and would answer requests of the form "give me information about the segment of the document at location foo".

AFAIK, this is correct.

But given the goal of this PR, this discussion on the features that LSP could provide feels out of place and should be moved to the LSP issue.

Furthermore, IMHO these questions don't need to be answered before proceeding with the first steps of the plan I sketched above, and it is only with enough experimentation that it will be possible to properly answer them. That being said, as a CoqIDE maintainer, you should feel welcome to take part in this experimentation.

2020-05-19 18:24 UTC, herbelin commented
> But given the goal of this PR, this discussion on the features that LSP could provide feels out of place and should be moved to the LSP issue.

Sure.

> That being said, as a CoqIDE maintainer, you should feel welcome to take part in this experimentation.

Yes, that's part of my point. As everyone keeps saying, UIs are very important for proof assistants, with many original ideas ahead to develop, with specificities which make them an autonomous field of investigation, and I'd be glad to take part to the experimentation.

2020-06-03 07:32 UTC, maximedenes commented
@gares the failure looks unrelated, doesn't it?

2020-06-03 13:12 UTC, merged