[declare] Remove some unused `fix_exn`
coq/coq pull request #12357
Opened 2020-05-18 17:56 UTC by ejgallego

In the current proof save path, the kernel can raise an exception when
checking a proof wrapped into a future.

However, in this case, the future itself will "fix" the produced
exception, with the mandatory handler set at the future's creation
time.

Thus, there is no need for the declare layer to mess with exceptions
anymore, if my logic is correct. Note that the `fix_exn` parameter to
the `Declare` API was not used anymore.

This undoes 77cf18eb844b45776b2ec67be9f71e8dd4ca002c which comes from
pre-github times, so unfortunately I didn't have access to the
discussion.

This needs some manual testing.

2020-05-18 18:13 UTC, ejgallego commented
> This needs some manual testing.

After a few minutes of manual testing in CoqIDE it seems to work fine.

2020-05-19 14:03 UTC, gares commented
Try to make an unguarded fixpoint with the fix tactic inside an opaque proof, then jump to the end of the file and then hit the wheels. This is a case where fix_exn is actually needed.

2020-05-19 14:13 UTC, gares commented
Sorry, I messed up with the comment. I think you should make a non guarded fix inside an opaque proof, then jump to the end of the file so that the proof is delegated to the worker. There `perform_buildp` will run `close_future_proof` without the `fix_exn`, so that we see what happens.

To my understanding all other code paths should not be affected.

2020-05-19 14:59 UTC, ejgallego commented
> I think you should make a non guarded fix inside an opaque proof, then jump to the end of the file so that the proof is delegated to the worker. There `perform_buildp` will run `close_future_proof` without the `fix_exn`, so that we see what happens.

Thanks, I'll try, but reading the current code this case should be fine, in the sense that the chained future there is already forced [a bit upwards], so the code of chain in this case doesn't propagate the `fix_exn` I think. We have this path:

```
     let proof = Future.force fp in
     let fix_exn = Future.fix_exn_of fp in
     let checked_proof = Future.chain fp (fun p ->
```
so if `fp` raises, the chain won't be reached AFAICT, right?

Let me do the test you propose.

Semantics of exceptions and futures are indeed tricky, and to my understanding they differ in the OCaml world even between versions of the same library (ex. Lwt)

2020-05-19 15:10 UTC, SkySkimmer commented
>Sorry, I messed up with the comment. I think you should make a non guarded fix inside an opaque proof, then jump to the end of the file so that the proof is delegated to the worker. There perform_buildp will run close_future_proof without the fix_exn, so that we see what happens.

Should a fake_ide tests be added for this?

2020-05-19 15:25 UTC, gares commented
> Should a fake_ide tests be added for this?

It would be nice, but I don't think we have the infrastructure to test this. The fix_enx thing is about having the feedback be attached to the right state id (the right line). fake_id does not have support for that. Maybe if we check the output we could see a different line number, but I've never tried.

2020-05-19 15:59 UTC, ejgallego commented
I did some testing with
```
Lemma a (n : nat) : nat.
Proof using.
  revert n.
  fix f 1.
  apply f.
Qed.
```
I've pushed an additional commit.

In master, I get a the `Qed` in red in both occasions [before and after the gear] ; that seems bizarre right? It seems the checking should be delayed and it is not?

With only the first commit I get the `Qed` delayed, however it seems indeed that the gears don't work properly. I think this is not due to a change in the semantics of chain, but indeed the lower layer was doing a workaround grabbing the fix_exn. IMO this logic should be pushed into `perform_buildp` itself. Note this results in a broken check for that case.

The second commits tries to amend that, I refactor `perform_buildp` as not chain the future needlessly, on go to end I get a proper delayed qed, after clicking I get the error but the info is missing; if I amend the try ... with block I get a better result, but still not exactly what I wanted, maybe you can help to see what the `None` case on the with block should do? As it stands now it is broken.

2020-05-19 16:04 UTC, gares commented
> In master, I get a the `Qed` in red in both occasions [before and after the gear] ; that seems bizarre right? It seems the checking should be delayed and it is not?

This is expected. Workers are proactive in building the proof and checking it goes trough a Qed (locally performed in the worker). The wheels performs the Qed in master, where all universe constraints are gathered.

2020-05-19 16:08 UTC, gares commented
I don't recall the use case of @mattam82 which your commit seems to remove. Before trying to fix the code I think we should check if the use case is still relevant.

2020-05-19 19:53 UTC, ejgallego commented
OK, I think I figured the problem out, now your test case works; the thing is that `fix_exn` was doing more than just modifying the exception, now we call `State.exn_on` if the Qed fails and the behavior in your use case seems correct.

Regarding the obligations case, indeed it is likely due to this code path:
```
Program Definition foo := _.

Next Obligation.
Proof. by tac. Qed.
```
The second `Qed` will actually also trigger a `Qed` for `foo` when it is solved, I'll analyze this code path.

2020-05-19 19:55 UTC, ejgallego commented
> Should a fake_ide tests be added for this?

It would be good, it is a bit subtle as you want to do things like editing the proof and trying to check the `Qed` again.

2020-05-19 20:17 UTC, ejgallego commented
I've added an interactive test case for both behaviors, I'm unsure what should happen in the next obligation case, but it seems to work OK in my manual testing.

2020-05-25 10:49 UTC, ejgallego commented
This is ready I think; needs assignee.

2020-05-26 09:42 UTC, SkySkimmer commented
I'm removing all review requests except stm-maintainers as I think they're the only ones who understand this fix_exn stuff.

2020-05-26 09:55 UTC, ejgallego commented
@gares , could you the assignee then?

2020-05-26 14:37 UTC, gares commented
I'd like to hear from @mattam82 since he had a use case

2020-06-03 14:47 UTC, ejgallego commented
Ping @mattam82 ?

2020-06-08 10:44 UTC, mattam82 commented
The hack was used to report errors at the right place, and avoid an anomaly the STM used to raise about not having a proper fix_exn in place AFAIR. I like this PR's code much better, so if your test-case works I'd say go for it!

2020-06-08 10:51 UTC, ejgallego commented
> The hack was used to report errors at the right place, and avoid an anomaly the STM used to raise about not having a proper fix_exn in place AFAIR. I like this PR's code much better, so if your test-case works I'd say go for it!

Thanks for the review @mattam82 , indeed I think that problem should not happen anymore.

As things stand today, obligations are not delayed [with #11836 would be possible I think, even with the current API if one is careful] , so errors on the final type-checking will be attributed to the obligation crafting the last hole, IMHO that's OK. [See the interactive test for some play]

This is IMO thus ready to merge, in view of @SkySkimmer 's comment we need an assignee from @coq/stm-maintainers .

2020-06-08 10:54 UTC, mattam82 commented
Note that in my original patch I used "get_fix_exn ()" for the definition entry of the whole program. I guess this attached the exception to the original definition. However the problems usually come from ill-formed recursive calls in the obligations so the proposed fix sounds actually better.

2020-06-08 11:05 UTC, ejgallego commented
> However the problems usually come from ill-formed recursive calls in the obligations so the proposed fix sounds actually better.

Indeed, that's the idea. I'm trying to make the API here a bit more fine-grained so indeed the document manager can have a bit more control on the continuations [for example presenting a better UI for obligations progress] , that should allow the upper layers to attribute errors better if they want.

2020-06-10 12:33 UTC, gares requested changes
Looks good, I request a few minor changes

2020-06-11 18:09 UTC, ejgallego commented on stm/stm.ml
> +               this is actually wronly named fix_exn as it does _way_
Amended thanks.

2020-06-11 18:10 UTC, ejgallego commented on vernac/declare.ml
>  let definition_entry =
Umm, this is unrelated to this PR, right? If we do this then Coq won't compile as the type of `definition_entry` won't match the exported one (`definition_entry_core` is used to hide some internal parameters)

2020-06-11 18:18 UTC, gares commented on vernac/declare.ml
>  let definition_entry =
I see

2020-06-11 18:19 UTC, gares approved these changes

2020-06-12 08:55 UTC, merged