Defined arbitrary base logarithms (Rlog) and added natural lemmas to the Real library
coq/coq pull request #12542
Opened 2020-06-18 23:15 UTC by llee454

Defined arbitrary base logarithms (Rlog) and added natural lemmas concerning ln, exp, and Rlog to the Real library. Additionally made the real exponent notation nonlocal.

**Kind:** feature

2020-06-21 21:13 UTC, VincentSe commented
@MSoegtropIMC This PR looks good to me and the build error is probably unrelated. How do we restart the continuous integration to verify ?

2020-06-22 15:03 UTC, Zimmi48 commented
I don't think the error is unrelated because it failed three times and the error log says:

```
2884 COQC      theories/Reals/Rpower.v
2885 File "./theories/Reals/Rpower.v", line 314, characters 4-23:
2886 Error: Unused introduction pattern: m [unused-intro-pattern,tactics]
```

so it looks very related to reals to me.

2020-06-22 15:09 UTC, VincentSe commented
@llee454 Your PR probably does not build on the master branch. Can you rebase and rebuild ?

2020-06-24 19:59 UTC, llee454 commented
Hey @VincentSe, I believe that I fixed the error. Let me know if there's anything else you need.

2020-06-25 20:56 UTC, VincentSe commented
@Zimmi48 What do you think this time, this PR probably didn't break metacoq ?

2020-06-25 21:11 UTC, Zimmi48 commented
Indeed, that error seems unrelated.

2020-06-25 21:41 UTC, VincentSe commented
@Zimmi48 How can I restart metacoq in the CI ?

2020-06-26 07:11 UTC, MSoegtropIMC reviewed
> @Zimmi48 How can I restart metacoq in the CI ?

You click on `Details` right to the failed test in the test list and then in the upper right corner of the page is a Retry button. You need to be logged into Gitlab for this. I restarted it.

2020-06-26 08:50 UTC, Zimmi48 commented
MetaCoq is broken for everyone: https://github.com/MetaCoq/metacoq/issues/431

2020-06-26 09:16 UTC, MSoegtropIMC requested changes
I would insist at least on a discussion on the naming of the operator `^R`. I don't agree with this naming, because it doesn't match common naming schemes.

2020-06-26 17:05 UTC, VincentSe commented
@MSoegtropIMC There is also notation `^Z` in file Rfunctions.v. What do you propose instead of those 2 notations `^Z` and `^R` ?

2020-07-02 20:32 UTC, llee454 commented
Hi all, I agree that the notation ^Z and ^R are somewhat inconsistent. But, does this issue necessitate blocking this merge?

2020-07-02 21:22 UTC, MSoegtropIMC commented
> Hi all, I agree that the notation ^Z and ^R are somewhat inconsistent. But, does this issue necessitate blocking this merge?

Consistency is of some importance in a standard library but then other types don't have the issue to distinguish between integer and real powers.

@VincentSe : what is your opinion on this?

2020-07-02 22:10 UTC, MSoegtropIMC commented
Btw.: besides consistency there is another reason why these notations might not be a good idea. Afaik the tokenizer of Coq is not scope dependent. This means that once you define this notation, even if it is not in scope,  you can't parse A^R any more in a scope which has the usual ^ operator, because ^R is then one token. You should test if this is the case - it might be that this changed meanwhile. @herbelin should know.

I didn't find the ^Z operator you mentioned. Does it already exist?

2020-07-03 07:59 UTC, MSoegtropIMC requested changes

2020-07-03 07:59 UTC, MSoegtropIMC commented on theories/Reals/Rpower.v
> +Infix "^R" := Rpower (at level 30, right associativity) : R_scope.
I am not sure how this solves the possible parsing issue I mentioned. Please check the following in a context where the above notation is defined:
- Close Scope R_scope.
- open another scope with a usual ^ operator, say Z scope
- check if e.g. the expression `forall A,R:Z, A^R=A^R` still parses.
If yes I am still not a fan of this notation, but would be OK if others accept it. In cases this does not parse any more, I strongly object against having this notation in the standard library.

Please post the code and results of your test here.

2020-07-03 09:27 UTC, silene commented on theories/Reals/Rpower.v
> +Infix "^R" := Rpower (at level 30, right associativity) : R_scope.
As pointed out by @MSoegtropIMC, please do not make this notation non-local. Otherwise, it will cause `^R` to become a keyword, and thus force users to type `^ R` (with a space) even outside `R_scope`.

2020-07-03 10:31 UTC, MSoegtropIMC commented
@llee454 : first let me apologize that I thought you introduced the `^R` notation - somehow I got confused by Github's presentation of the diff.

I had a discussion today with @herbelin, @silene and @VincentSe on this topic and we decided that it would be best to remove this notation and replace it with the function call. Since you didn't introduce the notation, we can of cause also first merge your PR (with the notation being Local) and removing the notation in a second step, but you could also do it as part of this PR. Please let me know what you prefer.

The rationale is as follows:
- the `^R` notation cannot be a global notation, because it breaks parsing of ^ and R as separate tokens
- notations should be consistent - if users see the definitions of theorems using this notation, they would also try to use this notation in their work, but it would not work since it is a local notation
As a result this notation brings more confusion than clarity.

2020-07-05 17:01 UTC, llee454 commented
Hey @MSoegtropIMC, I removed the `^R` notation from theories/Reals/Rpower.v and pushed an update. Let me know if this is what you had in mind.

2020-07-08 20:21 UTC, MSoegtropIMC commented
@llee454 : sorry I was busy the last days (also cause of the Coq Workshop Su/Mo). I will look into it tomorrow.

2020-07-09 08:28 UTC, MSoegtropIMC approved these changes
Looks good to me - I will merge today.

Thanks for removing the ^R notation - this way the lemmas will be easier to apply for users.

2020-07-09 17:46 UTC, merged