[exn] Add missing info to tclZEROMSG / tclFAIL
coq/coq pull request #12630
Opened 2020-07-02 13:35 UTC by ejgallego

When debugging some problems with evar modification (in #12629) I found some
missing backtraces originating from tactic code, so it seems useful to
require the two missing primitives to carry backtrace information.

AFAICT there are no more cases of missing backtrace information on
tactic code, so we should be finally done with this.

2020-07-02 14:41 UTC, ppedrot requested changes
Rather than polluting the code with debug info, I think it should be better to compute this directly in the tactic primitives. Not that it makes much more sense in general, but at least it will be less invasive.

2020-07-02 14:46 UTC, ejgallego commented
> Rather than polluting the code with debug info, I think it should be better to compute this directly in the tactic primitives. Not that it makes much more sense in general, but at least it will be less invasive.

Can you elaborate a bit more on that? I'll be happy to implement it.

While I agree this kind of patch is ugly, it is _very_ useful for debugging [and it is really the last one remaining]

2020-07-02 14:48 UTC, ppedrot commented
Instead of writing `let info = Exninfo.reify () in tclZERO e` everywhere, define `tclZERO e = let Exninfo.reify () in tclZERO e`. The stack traces should be essentially the same.

2020-07-02 14:52 UTC, ejgallego commented
> Instead of writing `let info = Exninfo.reify () in tclZERO e` everywhere, define `tclZERO e = let Exninfo.reify () in tclZERO e`. The stack traces should be essentially the same.

Ummm, they are not, look at the changes in `tacticals`, that's the whole point, once we enter (thru bind) tclZero, the original raising context is lost.

2020-07-02 14:53 UTC, ejgallego commented
> Ummm, they are not, look at the changes in `tacticals`, that's the whole point, once we enter (thru bind) tclZero, the original raising context is lost.

We need to capture the backtrace before creating the monadic thunk, once we are inside it, we have lost.

2020-07-02 15:03 UTC, ejgallego commented
Example:

```ocaml
Raised at file "plugins/ssr/ssrequality.ml", line 385, characters 54-98
Called from file "engine/proofview.ml", line 1205, characters 10-43
Called from file "engine/evd.ml", line 1311, characters 15-20
Called from file "engine/proofview.ml", line 1217, characters 25-73
Re-raised at file "clib/exninfo.ml", line 82, characters 4-38
Called from file "proofs/proof.ml", line 383, characters 4-42
Called from file "proofs/proof.ml", line 557, characters 31-52
Called from file "plugins/ltac/g_ltac.mlg", line 371, characters 8-83
```
vs
```ocaml
Raised by primitive operation at file "clib/exninfo.ml", line 123, characters 13-38
Called from file "tactics/tacticals.ml", line 479, characters 16-32
Called from file "engine/logic_monad.ml", line 205, characters 55-61
Called from file "engine/logic_monad.ml", line 117, characters 8-12
Called from file "engine/proofview.ml", line 229, characters 12-42
Called from file "proofs/proof.ml", line 383, characters 4-42
Called from file "proofs/proof.ml", line 557, characters 31-52
Called from file "plugins/ltac/g_ltac.mlg", line 371, characters 8-83
```

2020-07-02 15:44 UTC, ppedrot commented
> We need to capture the backtrace at the point monadic thunk is created

I definitely agree on first principles, but the fact it fails on your examples is highly suspicious though, since we do split the construction of the CPS closure in two parts in this code. Is the compiler inlining stuff where it shouldn't, thus changing the semantics?

2020-07-02 15:49 UTC, ejgallego commented
I think this is due the way or/bind work, right? [I need to carefully reason on paper to be sure]

2020-07-02 15:57 UTC, ppedrot commented
This is breaking my mental model of the ML semantics, even accounting for the fact that backtraces are not semantically stable by the CBV equational theory. Extruding the call to the backtrace should just shave off the top frame of the result, since `tclZERO e` returns a closure, and thus a value.

2020-07-03 15:18 UTC, ejgallego commented
Actually @ppedrot I think it makes sense, precisely when you are in:
```
f >>= tclZero
```
where `tclZero = let e = bt () in fun n _ -> n e)` indeed, the bt captured is in the context of bind, not of the inner lambda and here thus the above backtrace. Pushing the `bt ()` inner in the closure is not gonna help with functions that do:
```
let f = .... in
tclZero (Error ...)
```
I think.

2020-10-15 11:31 UTC, ejgallego commented
@ppedrot any comment on my above explanation?

I still believe that this PR is the lesser of the two evils, but indeed no option is nice; I still think that given that this is the last one in this series I would go ahead, but if you can we can chat about it in the call.

2021-11-17 15:06 UTC, SkySkimmer reviewed
I don't understand why 
~~~ocaml
let tclZEROMSG msg = 
  let info = Exninfo.reify () in 
  tclZERO ~info (UserError msg)

let bla = 
 ...
  tclZEROMSG msg
~~~
doesn't work but
~~~ocaml
let tclZEROMSG ~info msg = 
  tclZERO ~info (UserError msg)

let bla = 
 ...
  let info = Exninfo.reify () in 
  tclZEROMSG ~info msg
~~~
works

2021-11-17 15:32 UTC, ejgallego commented
> I don't understand why

There are some cases where `f >>= tclzero "msg"` is bound to an evalutation context then you are in problems.

Will provide a concrete example as requested in the call.

2022-02-09 02:16 UTC, closed without merging