Sligthly reorganising the test suite to follow its documentation
coq/coq pull request #12835
Opened 2020-08-13 12:33 UTC by Mbodin

**Kind:** documentation / infrastructure.

This is a split of PR #12821 containing only the parts touching the documentation and the test suite.

Fixes #10902.

2020-08-13 12:39 UTC, Mbodin commented
I feel that I shouldn’t squash the first commit with the others: it fixes a separate issue and only touches documentation. Maybe leaving the second commit unsquashed is fine too as it only adds a test and does not reorganise anything?

I think that it is safe to squash the last two, adding @herbelin as co-author. Would that be fine?

2020-08-13 12:42 UTC, Mbodin commented
(Sorry for the multiple forced-push: I kept getting the wrong commit message for the first commit.)

2020-08-13 13:58 UTC, SkySkimmer commented
The test for #5996 is wrong btw (compare with the examle in the issue)

2020-08-13 15:46 UTC, Mbodin commented
Good catch! I didn’t change it: I just moved it so that it would be tested by the continuous integration system (it is currently ignored by it).

The current test is as follows:
```coq
Goal Type.
  let c := constr:(prod nat nat) in
  let c' := (eval pattern nat in c) in
  let c' := lazymatch c' with ?f _ => f end in
  let c'' := lazymatch c' with fun x : Set => ?f => constr:(forall x : Type, f) end in
  let _ := type of c'' in
  exact c''.
Defined.
```
It basically corresponds to https://github.com/coq/coq/issues/5996#issuecomment-338405694 Do you think that it should be like https://github.com/coq/coq/issues/5996#issuecomment-338406360 instead? I’m afraid that I don’t know anything about #5996 to have an opinion here.

2020-08-13 16:58 UTC, herbelin commented
The current test is basically one that I cooked at some time. Indeed, it does not fully solve the original issue. I don't know what to do. @skyskimmer, would you like we add the original example to the file, with a `Fail` on the `Defined`, and move the whole file to `bugs/opened` (thus also keeping the first - current - part of the file as a working example)?

2020-08-13 21:18 UTC, jfehrle approved these changes
Approving the doc change. I'll leave it to others to approve the test changes.

These are small changes and somewhat related.  There's no code change that affects users.  I suggest squashing these commits after review is complete, just before merging.  

There's a tradeoff between giving many detailed commits and having a concise, readable commit history.  For code changes, we're more careful about not combining unrelated changes into a single commit.  This makes the commit history more understandable and it's easier to back out changes if unexpected issues arise afterward.

When I'm submitting a PR with changes that are complex and there may multiple rounds of review, I often put the review-related changes into a new commit, imaginatively names "Review # N" so the reviewers can easily verify the incremental changes.  And then squash them just before merging.

2020-08-18 09:41 UTC, herbelin approved these changes
Looks good and as expected. Shall merge tomorrow if no more comments by then.

2020-08-18 10:03 UTC, SkySkimmer requested changes
5996 is still wrong.

2020-08-18 10:03 UTC, SkySkimmer commented on doc/sphinx/addendum/extraction.rst
> +   it contains the raw ML term produced as an intermediary target.
This doesn't belong in this PR.

2020-08-18 10:04 UTC, SkySkimmer commented
>@SkySkimmer, would you like we add the original example to the file, with a Fail on the Defined, and move the whole file to bugs/opened (thus also keeping the first - current - part of the file as a working example)?

Sure that sounds fine

2020-08-18 10:54 UTC, Mbodin commented on doc/sphinx/addendum/extraction.rst
> +   it contains the raw ML term produced as an intermediary target.
Should I split the PR again?

2020-08-18 11:02 UTC, Mbodin commented
I added the original example. Please double-check as I’m not familiar with issue 5996.

2020-08-18 11:20 UTC, SkySkimmer commented on test-suite/bugs/opened/bug_5996.v
> +(* Alternative example. *)
```suggestion
(* Workaround *)
```

2020-08-18 11:21 UTC, SkySkimmer commented on doc/sphinx/addendum/extraction.rst
> +   it contains the raw ML term produced as an intermediary target.
Yes, and then squash.

2020-08-18 19:52 UTC, herbelin commented
@skyskimmer: Do we split the PR again in two? If yes, maybe can we do it ourselves to avoid adding a burden on @Mbodin who already helped a lot?

2020-08-18 22:46 UTC, jfehrle commented
> Do we split the PR again in two?

Meaning splitting it into 2 commits, not into 2 PRs?  One with the doc change, one with the test changes?

2020-08-19 11:27 UTC, Mbodin commented
I’m fine with doing it, actually ☺ (I’m learning the way PR works along the way, and I actually did appreciate the learning curve ☺)
I will first try squashing into two commits (with the documentation change, and the test-suite change), then we can split the PR or leave it as-is, depending on which is better for the git history (I don’t have much opinion on which is better).

2020-08-19 11:33 UTC, SkySkimmer commented
>I will first try squashing into two commits (with the documentation change, and the test-suite change)

No, you should split first imo

2020-08-19 11:40 UTC, Mbodin commented
I just did the PR split ☺

2020-08-19 11:41 UTC, SkySkimmer approved these changes

2020-08-24 14:41 UTC, merged