Update sigma instead of erasing it in `update_global_env`
coq/coq pull request #12878
Opened 2020-08-23 15:54 UTC by maximedenes

The current implementation of `update_global_env` breaks `run_tactic` when we move more data to the evar_map (shelf, goals).

We simply make it update the evar_map instead of erasing it with the global one, so that only relevant components are touched.

@ppedrot can you confirm it looks ok?

2020-08-23 17:25 UTC, SkySkimmer commented
It may be better to just have a `Proof.update_sigma_env` function instead of implementing it through `run_tactic`

2020-08-23 17:26 UTC, maximedenes commented
> It may be better to just have a `Proof.update_sigma_env` function instead of implementing it through `run_tactic`

Yes, that's another possibility.

2020-08-24 11:43 UTC, SkySkimmer requested changes
Please make a `Proof.update_sigma_env` instead of going through `run_tactic`

2020-08-24 13:37 UTC, maximedenes commented
@SkySkimmer should look better now, thanks for the suggestion!

2020-08-24 13:39 UTC, SkySkimmer approved these changes

2020-08-25 07:45 UTC, SkySkimmer commented
@coqbot: merge now

2020-08-25 07:46 UTC, SkySkimmer commented
@Zimmi48 was coqbot supposed to do something when I pinged it here?

2020-08-25 08:30 UTC, Zimmi48 commented
OK, so it still doesn't work. Weird.

2020-08-25 08:32 UTC, merged

2020-08-25 08:33 UTC, Zimmi48 commented
OK, so I just hadn't properly clicked on the save button when I added @coqbot-app to the people and apps allowed to push into `master`.