[ci] [docker] Up testing to OCaml 4.11.1
coq/coq pull request #12972
Opened 2020-09-02 15:13 UTC by ejgallego

2020-09-04 10:23 UTC, SkySkimmer submitted a review, later dismissed
Didn't update CACHEKEY

2020-09-07 13:16 UTC, Zimmi48 commented on doc/changelog/11-infrastructure-and-dependencies/12972-ocaml+4_11.rst
> +  Coq is tested now against OCaml 4.11.1
```suggestion
  Coq is now tested against OCaml 4.11.1
```

2020-09-07 15:02 UTC, ejgallego commented
> Didn't update CACHEKEY

Ups.

2020-09-07 16:35 UTC, Zimmi48 commented
Pipeline with Docker image build running here: https://gitlab.com/coq/coq/-/pipelines/186947960

2020-09-08 09:06 UTC, Zimmi48 requested changes
Please backtrack on the update of ocamlformat. This is an unrelated change, that is not backportable (whereas the rest of the PR would have been) and that would significantly delay the merging of the PR (which was otherwise completely ready).

2020-09-08 14:21 UTC, ejgallego commented
> Please backtrack on the update of ocamlformat. This is an unrelated change, that is not backportable (whereas the rest of the PR would have been) and that would significantly delay the merging of the PR (which was otherwise completely ready).

What do you propose, 4.11 is not compatible with ocamlformat 0.14.x

2020-09-08 14:27 UTC, ejgallego commented
successful pipeline https://gitlab.com/coq/coq/-/pipelines/186972021

2020-09-08 15:31 UTC, Zimmi48 commented
> What do you propose, 4.11 is not compatible with ocamlformat 0.14.x , indeed the PR was not ready as not even the docker image completed.

OK then, I was not aware of this and did not look carefully enough at your commit message. Please apply the following change so that the 0.15.0 version is available in `nix-shell` as well:

```diff
diff --git a/dev/nixpkgs.nix b/dev/nixpkgs.nix
index bfb25e72dd..e798645ed0 100644
--- a/dev/nixpkgs.nix
+++ b/dev/nixpkgs.nix
@@ -1,4 +1,4 @@
 import (fetchTarball {
-  url = "https://github.com/NixOS/nixpkgs/archive/17812e653d89c46d68b7b10e290b1c16758f4e47.tar.gz";
-  sha256 = "1zcb70dyfqc8l2ywpbvxmpfshapdi0g365m3rhmwpagqg47pnyxs";
+  url = "https://github.com/NixOS/nixpkgs/archive/3c0e3697520cbe7d9eb3a64bfd87de840bf4aa77.tar.gz";
+  sha256 = "1vx7kyaq0i287dragjgfdj94ggwr3ky2b7bq32l8rkd2k3vc3gl5";
 })
```

2020-09-08 15:32 UTC, Zimmi48 commented
I'll try to backport this nonetheless, possibly by removing the `ocamlformat` dependency from `v8.12`.

2020-09-08 15:36 UTC, ejgallego commented
> I'll try to backport this nonetheless, possibly by removing the `ocamlformat` dependency from `v8.12`.

Indeed, I think that's not a problem for the backport; on the other hand 4.11 didn't see a lot of testing yet with Coq so IMHO we should also tweak the changelog as to suggest the support is experimental or something similar.

Let's see anyways what happens with ocamlformat as if #12985 is merged then no point in keeping it in the docker image.

2020-09-10 20:00 UTC, Zimmi48 commented
This PR has waited long enough, especially with the 8.12.1 release scheduled for next week. Please apply the patch I gave you and I'll merge.

2020-09-10 20:05 UTC, Zimmi48 approved these changes

2020-09-10 20:06 UTC, ejgallego commented
> This PR has waited long enough, especially with the 8.12.1 release scheduled for next week. Please apply the patch I gave you and I'll merge.

Done thanks!

2020-09-11 08:46 UTC, Zimmi48 commented
Unfortunately that did not work because the nixpkgs version that has ocamlformat 0.15.0 has Sphinx 3, which we are not compatible with yet :disappointed:

2020-09-11 09:32 UTC, Zimmi48 commented
Fortunately, we are quite close to being compatible with Sphinx 3, so I'll prepare a PR about this.

2020-09-11 10:34 UTC, Zimmi48 commented
See #13011.

2020-09-12 10:16 UTC, Zimmi48 commented
OK, this should now work if you rebase the PR

2020-09-14 14:49 UTC, Zimmi48 commented
ping @ejgallego: this PR just needs a rebase to pass CI

2020-09-14 16:32 UTC, ejgallego commented
Done, thanks @Zimmi48

2020-09-15 07:13 UTC, Zimmi48 commented
@coqbot: merge now

2020-09-15 07:13 UTC, merged