Documenting Set Printing Goal Names and Set Printing Unfocused + a small goal display fix + coqide support
coq/coq pull request #13140
Opened 2020-10-05 11:37 UTC by herbelin

**Kind:** documentation / bug fix

We document the 3-year old options `Set Printing Goal Names` and `Set Printing Unfocused` which I find useful in `coqtop` interaction. I'd actually be tempted to set the first one on by default (??).

We also a fix a small redundancy in goal printing without first goal:

```
    2 subgoals, subgoal 1 (?Goal)
    
    subgoal 1 (?Goal) is:
     True
    subgoal 2 (?Goal0) is:
     True
```
is replaced by
```
    2 subgoals
    
    subgoal 1 (?Goal) is:
     True
    subgoal 2 (?Goal0) is:
     True
```

We finally add the support for printing names in CoqIDE.

- [X] Corresponding documentation was added
- [ ] Entry added in the changelog (advertising the options?).

Incidentally, this invites to concoct names more informative than `?Goal`, `?Goal0` ...

2020-10-05 12:20 UTC, Zimmi48 commented
Strictly speaking, the last commit is a new feature, but at least the first commit who be eligible to be backported if you submitted it through a separate PR. Your call though. Despite being a small addition, I believe the new CoqIDE menu entry still deserves to be advertised with a changelog entry.

2020-10-05 12:39 UTC, Zimmi48 commented
The compilation error in the reference manual is due to `Printing Unfocused` being already documented: https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:flag.printing-unfocused

2020-10-06 06:36 UTC, herbelin commented
> The compilation error in the reference manual is due to `Printing Unfocused` being already documented

Ah, interesting! It seems then that there is an overlap of topics between section `Controlling display` of `vernacular-commands.rst` and section `Controlling the effect of proof editing commands` of `proof-handling.rst`. At least do I now remove my redundant `Printing Unfocused`.

> Strictly speaking, the last commit is a new feature

I moved the CoqIDE part to independent PR #13145 then.

Thanks for the comments.

2020-10-06 07:49 UTC, Zimmi48 commented
Yes, the plan is anyway to split the vernacular chapter and spread out its contents where it makes most sense.

2020-10-06 07:54 UTC, Zimmi48 approved these changes
Approving the doc part. Don't you want to include an output test for the goal display fix?

2020-10-06 20:02 UTC, herbelin commented
> Don't you want to include an output test for the goal display fix?

Done... and it allowed me to detect yet another situation with redundant output!

2020-10-08 21:22 UTC, ejgallego requested changes
Hi @herbelin , the documentation is fine, however I am not very comfortable updating the goal printing in 8.12.1 as for example PG has a lot of code parsing that output and who knows what could break [there is really a lot of different flags combinations to try]

So please target the printing change to `master` so it can get wider testing.

2020-10-15 11:14 UTC, ejgallego approved these changes

2020-10-15 11:14 UTC, ejgallego commented
Ok, merging; the doc fix could be backported to 8.12 but I guess not worth it then.

@coqbot: merge now

2020-10-15 11:15 UTC, merged

2023-02-05 19:11 UTC, herbelin commented
Wouldn't it be more useful in practice to turn the `Set Printing Goal Names` on by default (and inform the UI developers of the activation)?