Protect caml_process_pending_actions_exn with caml_something_to_do.
coq/coq pull request #13676
Opened 2020-12-26 16:46 UTC by silene

When using OCaml >= 4.10, function `caml_process_pending_actions_exn` is called whenever the bytecode interpreter tries to apply a term. This function exits immediately when `caml_something_to_do` is not set. But since term application happens every few opcodes, even exiting immediately still accounts between 5% and 10% of the whole interpreter. So, this commit makes sure the function is not called unless `caml_something_to_do` is already set (i.e., when the user presses Ctrl+C). This means that this conditional branch is perfectly predicted by the processor.

On the following benchmark, this commit makes the VM 13% faster.

```coq
Time Eval vm_compute in Pos.iter (fun x => x) tt 100000000.
```

Note that, before OCaml 4.10, the VM code was checking the value of `caml_signals_are_pending` before calling `caml_process_pending_signals`. So, this commit actually fixes a regression.

2021-01-07 17:12 UTC, ppedrot reviewed
I don't feel qualified to review this PR, and would actually prefer OCaml people to do it.

2021-02-19 14:47 UTC, silene commented
Invoking some OCaml developers: @gadmm @gasche @xavierleroy

2021-02-19 15:29 UTC, gasche approved these changes
I confirm that `caml_process_pending_actions_exn` is a no-op if `caml_something_to_do` is not set, so this change is correct.

2021-02-19 15:29 UTC, gadmm commented
That might work for OCaml 4.10 to 4.12 but `caml_something_to_do` is an internals; and it is better if it stays that way (being a global is an implementation detail, it is unlikely to remain that way with multicore, and I also have a PR that removes it).

The functionality of checking `caml_something_to_do` is already provided by `caml_check_pending_actions` since 4.12, would that work or is the function call overhead a problem too? If not, you can test caml_something_to_do for 4.10 and 4.11, and introduce a call to `caml_check_pending_actions` for 4.12 onwards

In any case your problem is that you poll too often, and a solution that is robust and does not rely on internals is to only check every few times:
```c
unsigned int check = 0;
...
if ((++check & 32) == 0) exn = caml_process_pending_actions_exn();
```

2021-02-19 15:32 UTC, gadmm requested changes
This depends on an internals, and I am not convinced that this is a limitation of the OCaml API—instead, you can use a counter to avoid polling too often. Otherwise, use `caml_check_pending_actions` for 4.12 onwards.

2021-02-19 16:20 UTC, silene commented
> This depends on an internals, and I am not convinced that this is a limitation of the OCaml API—instead, you can use a counter to avoid polling too often. Otherwise, use caml_check_pending_actions for 4.12 onwards.

Here is the breakdown:

- When always calling `caml_process_pending_actions_exn`, overhead is 13%.
- When calling `caml_process_pending_actions_exn` once every 32 steps, overhead is 7%.
- When calling `caml_process_pending_actions_exn` only after `caml_check_pending_actions`, overhead is 3%.

So, the counter idea is bad. (I guess that the misprediction due to the counter kills much of the gain due to not calling the function.) Calling `caml_check_pending_actions` is better but still not that good.

2021-02-19 16:30 UTC, gadmm commented
Is it a processor misprediction of a compiler misprediction? You can you please try __builtin_expect((++check & 32) == 0, 0) and also see if bugger numbers than 32 make a difference? (with 1024 you should still be in the µs scale between polls).

2021-02-19 16:47 UTC, xavierleroy approved these changes
This looks correct to me.  Yes, `caml_something_to_do` is part of the internals of OCaml, but other bits of Coq's VM depend on OCaml internals already...  Just be ready to add some more `#if OCAML_VERSION` if OCaml's signal handling machinery changes again in the future.

2021-02-19 16:54 UTC, silene commented
> Is it a processor misprediction of a compiler misprediction?

Neither of them. We are just both idiots. Using `& 31` gives much saner results.

That said, the overhead is still large and I have to increase the mask up to `& 255` to eliminate it.

2021-02-19 17:01 UTC, gadmm commented
Ah yes, you are right. Checking every 256 times sounds reasonable. A long-term solution sounds better to me, as for finding the right OCaml API it comforts me in the idea that the user should be responsible for not polling too often. (Not that it would be impossible to support, say, something similar to caml_something_to_do but via a proper domain variable.)

2021-02-25 09:44 UTC, ppedrot commented
So, what should be done @silene?

2021-02-25 09:56 UTC, silene commented
Let us go for the simple one-line patch. That seems the most efficient solution for now.

By the time `caml_something_to_do` disappears, the OCaml API might have evolved in unforeseen ways. If the counter solution is still the best long-term solution by then, then we will benchmark it anew (for the mask) and switch to it.

2021-02-25 09:58 UTC, ppedrot commented
Fine with me. Merging soon.

2021-02-26 12:33 UTC, ppedrot approved these changes

2021-02-26 12:34 UTC, merged