[stdlib] [Vectors] add results on to_list
coq/coq pull request #13671
Opened 2020-12-24 11:52 UTC by olaure01

Add results about `Vector.to_list`.

**Kind:** feature.

- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

2020-12-28 13:36 UTC, olaure01 commented
CI errors seem to come from previous  [changelog](https://github.com/coq/coq/pull/13582#discussion_r549349562) in #13582.

2021-03-16 18:42 UTC, anton-trunov requested changes
Looks very useful to me, thank you! I just have a minor comment to address.

2021-03-16 18:42 UTC, anton-trunov commented on theories/Vectors/VectorSpec.v
> +Proof. revert m v2; induction v1; intros m v2; [ auto | now simpl; rewrite IHv1 ]. Qed.
Here the proof relies on an autogenerated name, viz. `IHv1`. There is an ongoing effort to make the standard compile with `-mangle-names` CLI option. I'd suggest introducing this name explicitly.

2021-03-16 19:46 UTC, olaure01 commented on theories/Vectors/VectorSpec.v
> +Proof. revert m v2; induction v1; intros m v2; [ auto | now simpl; rewrite IHv1 ]. Qed.
You are absolutely right, I missed this one.

2021-03-19 07:50 UTC, anton-trunov approved these changes

2021-03-19 07:52 UTC, anton-trunov commented
LGTM! Let's merge this PR Tuesday next week to give some time for comments.

2021-03-23 08:01 UTC, anton-trunov commented
@coqbot merge now

2021-03-23 08:01 UTC, merged