Remove the Hide Obligations flag (deprecated in 8.12)
coq/coq pull request #13758
Opened 2021-01-19 05:27 UTC by jfehrle

List of 8.14 deprecation removals is in #13538.

2021-01-19 07:15 UTC, Zimmi48 approved these changes

2021-01-19 07:15 UTC, Zimmi48 commented on vernac/declare.ml
> -    ( replace_appvars subst prg.prg_body
CI is failing because this was the only place this function was used, so it should be removed as well.

2021-01-19 17:51 UTC, jfehrle commented
Got it.  Updated.

2021-01-25 12:50 UTC, SkySkimmer requested changes

2021-01-25 12:50 UTC, SkySkimmer commented on vernac/declare.ml
> -    (Coqlib.lib_ref "program.tactics.obligation")
The gallina side https://github.com/coq/coq/blob/0a6444c522c18c634fe1030436ea82f326bada9a/theories/Program/Tactics.v#L323-L325 should also be removed.

2021-01-25 18:01 UTC, jfehrle commented
Updated.

2021-01-26 11:08 UTC, SkySkimmer approved these changes

2021-01-26 11:08 UTC, SkySkimmer commented
@coqbot: merge now

2021-01-26 11:08 UTC, merged