Fixes #14151: coqdoc error on ill-bracketed begin details/show
coq/coq pull request #14162
Opened 2021-04-23 13:09 UTC by herbelin

**Kind:** bug fix

We report a regular located error rather than a "fatal error".

Fixes / closes #14151

- [ ] Entry added in the changelog

2021-05-31 18:02 UTC, Lysxia commented on tools/coqdoc/cpretty.mll
> +        if is_none !formatted then true else body_bol lexbuf }
Is that really the best place to handle this? (And it seems to be missing the `Output.indentation` and newline increment.)

2021-05-31 18:31 UTC, Lysxia commented on tools/coqdoc/cpretty.mll
> +        if is_none !formatted then true else body_bol lexbuf }
OK I see the idea though maybe the regex should be `space* ('-`+ | ...) space*` to let newlines be handled elsewhere. Is there also not some bad interaction with negative numbers?

2021-06-14 12:51 UTC, silene requested changes

2021-06-14 12:51 UTC, silene commented on tools/coqdoc/cpretty.mll
> +    with Stack.Empty -> eprintf "%a, Error: ill-bracketed 'end show'\n" print_position lexbuf
This seems like a bad idea. The execution will continue as if nothing wrong happened. At the very least, the exception should be reraised of `exit 1` should be called.

2023-03-01 02:32 UTC, closed without merging