Moved lemmas from Reals/Cauchy/QExtra.v to a proper place in QArith
coq/coq pull request #14293
Opened 2021-05-09 15:45 UTC by MSoegtropIMC

This PR cleans up the various QArith lemmas proven as part of the constructive reals in the standard library. They are moved to the proper file in `theories/QArith` and in a few cases renamed and extended for completeness.

The remaining lemmas in Reals/Cauchy/QExtra.v are about:
- log2 for positives - it will be merged with Pos.size in a separate step
- some power of 2 upper/lower bound lemmas which are not generally useful cause of the lower limit hack for the rational number 0. To make this nicer one probably has to introduce the concept of scale minus infinite in the constructive reals e.g. by using a Z option as scale or some Z type extended with infinities. This will also be done in a separate PR.

The Qpower file I reordered a bit to separate the Qpower_positive from the Qpower functions.

Some lemmas from Qextra have been renamed, but these lemmas are rather new and the file was undocumented (explicitly excluded from the library documentation) before, so I guess this will not break anything.

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

2021-05-10 11:34 UTC, MSoegtropIMC commented
Btw.: wouldn't it be time to do the same name change as done for Z in Q, that is use a `Q.` prefix? Also one could better align similar lemmas between Z and Q.

2021-05-11 10:57 UTC, koraa commented
Thank you for linking the PR in the other issue! I don't really know enough about development in Coq (yet) to be a good judge of how useful/good the code is, but I do think they seem useful, especially the simple ones like Qabs_le/Qabs_gt…

Qabs strikes me as particularly useful as it allows one to reason about positive rationals; putting Zabs into relation to `Z.of_N n / p` and beyond that similar modules for `Zpos z # p`, `Zneg z # p`. `Z.of_N n # p`, `(z % d) # d` might be very helpful modeling a variety of problems but that's certainly not something for this PR…

2021-05-12 09:41 UTC, MSoegtropIMC commented
@koraa : I guess you mean the relation of `Qabs` with the various forms of rationals you mentioned. I am not sure if a lemma just relating the sign of the numerator with the result of Qabs and chaining such lemmas with e.g. `Z.of_N>=0` wouldn't be more useful - it depends on how frequently specific forms are used and also what people search for. A more generic lemma might be harder to find than `Search (Qabs (Zpos _ # _))`. Probably one should have both - generic and specific forms.

What I am missing (also in Z and R) is a complete set of interval arithmetic lemmas - the few I added are just special cases for multiplication I needed. The same applied to Z and R. Another thing which is useful sometimes is a complete set of lemmas for `high school style equation and inequality manipulation` with consistent names - say multiply inequality from the right by ... . This would work together nicely with field_simplify. Most of these lemmas exist, but with all sorts of not so obvious names.

2021-05-17 15:32 UTC, MSoegtropIMC commented
@herbelin, @silene, @thery : can someone please review this?

2021-05-17 23:19 UTC, herbelin reviewed
This is very useful and relevant to me, both in the move of lemmas in proper files and in extensions.

I have comments but mostly related to `QArith` as it was before:
- I think it would be nicer if more homogeneity could be achieved in the naming of variables (say `x`, `y` for `Q`; `p`, `q` for `positive`; `n` or `z` for `Z`), and in the order of arguments (say the numerator, denominator and exponents, in this order). That would make the lemmas easier to read and to compare.
- Also, with discriminating variables, `Qpower_positive` could probably be a notation `^` too, using the name of variables, thus their type, to understand what underlying power it is about.

A remark in the PR is about lemmas with name ended by a prime. I believe that a more explicit name would be clearer, e.g.
  -  `Qpower_pos` -> `Qpower_pos_strict` (or `Qpower_gt_0`, by analogy with `Qpower_gt_1`), 
  -  or `Qpower_gt_1`/`Qpower_gt_1'` -> `Qpower_gt_1_pos`/`Qpower_gt_1`,
  - and same for the pair `Qpower_ge_1`/`Qpower_ge_1'`.
  - `Qpower_decomp`/`Qpower_decomp'` -> `Qpower_positive_decomp`/`Qpower_positive_decomp` (since the lemmas do not very used yet)

2021-05-17 23:21 UTC, herbelin commented
> Btw.: wouldn't it be time to do the same name change as done for Z in Q, that is use a Q. prefix? Also one could better align similar lemmas between Z and Q.

Absolutely. I believe a compatibility layer would work.

2021-05-18 06:47 UTC, MSoegtropIMC commented
@herbelin : thanks for the review! I will do the changes you suggest except:

- a notation for Qpower_positive: I see this more as an implementation vehicle and don't expect users to see this a lot - and if they see it it is probably more confusing than helpful if it uses the same notation as Qpower.
- I will clean up variable naming for existing lemmas but not parameter order - this should be done in a separate step together with renaming. For the new lemmas I will review parameter order.

2021-05-19 07:31 UTC, MSoegtropIMC commented
@herbelin : thinking about this I wonder if I shouldn't go the whole way right away. Doing partial cleanup like parameter naming doesn't seem that sensible. Do you think I should make a complete overhaul of the Q library as part of this PR, including adjusting lemmas names and structure to Z and R and using a Q. prefix? It might get a bit hard to review the changes of the PR as is then, but you already did this. Or would it make more sense to first merge this as is (except for the naming of the new lemmas you mentioned in your review) and plan to do the overhaul immediately after (I have some time for this in the next days).

A question on a compatibility layer: should the notations in the compatibility layer be by default `deprecated` and should the compatibility layer be included by default as part of QArith or explicitly imported?

Does someone have an efficient and reasonably reliable Coq symbol renamer tool?

2021-05-26 08:06 UTC, MSoegtropIMC commented
@herbelin : I implemented your review comments as follows:

- `Qpower_pos` renamed to `Qpower_0_le` and added a (in 8.14 not yet deprecated) notation
- renamed the new lemmas to `Qpower_0_lt`, `Qpower_1_lt_pos`, `Qpower_1_lt`, `Qpower_1_le_pos`, `Qpower_1_le`. I also changed all lemmas such that the constant in the comparison is consistently on the left side and that the comparison mentioned in the lemmas name matches the resulting direction. Note that for Q gt and ge are just notations for lt and lw with swapped arguments, so that it doesn't really make a difference, but the names should still be consistent with the visible lemma statement.
- renamed `Qpower_decomp` to `Qpower_decomp_positive` and added a notation
- renamed the new lemma to `Qpower_decomp_pos` and added two additional lemmas `Qpower_decomp_neg_pos` and `Qpower_decomp_neg_neg` for decomposition with negative exponent and positive and negative numerator.
- added a change log entry.

I think it doesn't make a lot of sense to do further work in a hurry just before the branch of 8.14.

I think the further path is to create lists of lemmas for Q, Z, N and R, discuss how to make these consistent in a meeting and then do it with a compatibility layer (see my previous post for a first step in this direction).

2021-05-26 12:06 UTC, silene commented on theories/QArith/Qabs.v
> +Lemma Qabs_diff_Qlt_condition x y r: Qabs (x - y) < r <-> x - r < y < x + r.
I am not too happy with this statement. I understand that it mirrors the one of `Qabs_diff_Qle_condition`. But in my experience, the lemma would be more useful if the right-hand side was `y - r < x < y + r`. Sure, one can obtain it by first rewriting `Qabs (x - y)` into `Qabs (y - x)`, but if the user has to do this rewriting systematically, then it means the statement is inefficient.

2021-05-26 13:06 UTC, MSoegtropIMC commented on theories/QArith/Qabs.v
> +Lemma Qabs_diff_Qlt_condition x y r: Qabs (x - y) < r <-> x - r < y < x + r.
I think we should either change both, `Qabs_diff_Qle_condition` and `Qabs_diff_Qlt_condition` or keep this as is. I anyway plan a larger cleanup + alignment round after the 8.14 branch. I think it might be better to keep it like this until then. It might be easier to do a compatibility layer after a name alignment round, since the name possibly changes. One can't create compatibility notations for lemmas with the same name but different statement.

2021-05-26 21:14 UTC, herbelin commented
> I think it doesn't make a lot of sense to do further work in a hurry just before the branch of 8.14.

I agree.

And thanks for the detailed analysis Q vs R. That's very interesting. I will comment later.

2021-05-27 07:25 UTC, MSoegtropIMC commented on theories/QArith/QArith_base.v
> +Lemma Qreduce_den_Zinject_r : forall (a : Z) (b : positive),
I changed the naming - thanks for spotting this!

I am not so sure about preferring `(a#1)` vs. `(inject_Z a)`. One argument to prefer `2#1` is that this is printed as just `2` while `inject_Z 2` is printed as `inject_Z 2`. This is different from the Reals, where `IZR 2` is printed as `2` - and I would say simply is the most sensible representation of 2 in the reals. I checked that both ring and field can handle `inject_Z` - they can, so I don't have strong feelings about this. My gut feeling is that in Q `2#1` is a more natural representation, but it is more a 60%/40% thing. If your score is higher in the opposite direction, I can swap the short name vs. long name. But I think one should then print `inject_Z 2` as `2` as in the reals (as a separate PR). I wonder if this would be confusing to users, though - in reals `Q2R (2#1) is not printed as 2`.

Btw.: doing some tests I found that real field cannot solve `Q2R (2#1) = IZR 2` - I think it should.

2021-05-27 07:30 UTC, MSoegtropIMC commented on theories/QArith/QArith_base.v
> +  Z.pos a # b == / (Z.pos b # a).
Makes sense - I changed this and shortened the name as you suggested.

2021-05-27 15:54 UTC, MSoegtropIMC commented
@silene, @herbelin : this should be ready to merge. I just wonder if I should mention in the change log entry, that lemmas have been moved from QExtra and partly renamed. I didn't do so because QExtra is not documented (explicitly excluded from the library documentation) and I guess few people included the constructive real files and found them via Search.

2021-05-27 16:08 UTC, silene commented
> I guess few people included the constructive real files and found them via `Search`.

Unfortunately, you do not need to explicitly mention constructive real numbers:
```coq
Require Import Reals QArith.
Search (_ + _ < _ + _)%Q.
(* QExtra.Qplus_lt_compat: forall x y z t : Q, x < y -> z < t -> x + z < y + t *)
```

2021-05-27 16:23 UTC, MSoegtropIMC commented
That is true. Still I don't think anybody used this - this was only available in Coq 8.13. None of the developments in Coq CI used any of the renamed lemmas. But if you prefer, I can add compatibility notations for the lemmas for which I changed the name.

2021-05-27 16:27 UTC, silene commented
I don't think that the deprecation lemmas are needed. But the changelog entry is worth it, just in case someone did use the lemmas.

2021-05-27 16:40 UTC, MSoegtropIMC commented
Agreed - I will write a better changelog entry.

2021-05-28 06:19 UTC, MSoegtropIMC commented
@silene : I added a detailed description of the changes in the change log entry. I didn't do any other changes.

2021-05-28 13:11 UTC, MSoegtropIMC commented
@silene @herbelin : as far as I can tell the CI error is unrelated since:

- the same error happened on master commits 2x today
- CI passed before and I just changed the change log entry and as far as I can tell the failing job does not depend on changelog entries (like a doc task would).

So I would say this is ready to merge.

2021-05-28 15:51 UTC, silene requested changes

2021-05-28 15:51 UTC, silene commented on theories/QArith/Qpower.v
> +  forall (q : Q) (n m : Z), (n < m)%Z -> (1<q)%Q -> (q ^ n < q ^ m)%Q.
This should be named `Qpower_lt_compat_l`. See `Zmult_le_compat_l`, `Rmult_le_compat_l`.

2021-05-28 15:51 UTC, silene commented on theories/QArith/Qpower.v
> +Lemma Qmult_power : forall a b n, (a*b)^n == a^n*b^n.
This should be named `Qpower_mult`. See `Z.pow_mul_l`, `Rpow_mult_distr`.

2021-05-28 16:56 UTC, MSoegtropIMC commented on theories/QArith/Qpower.v
> +  forall (q : Q) (n m : Z), (n < m)%Z -> (1<q)%Q -> (q ^ n < q ^ m)%Q.
Ah yes, I would intuitively name it by the interesting side and not by the constant side, but indeed my naming is here incompatible with the rest of the standard library. I will change it.

2021-05-30 06:32 UTC, MSoegtropIMC commented on theories/QArith/Qpower.v
> +Lemma Qmult_power : forall a b n, (a*b)^n == a^n*b^n.
This lemma did exist before - I just moved it when I split the lemmas on Q_power and Q_power_positive. So we should do this rename with a general rework, since this would require a compatibility notation.

2021-05-30 06:42 UTC, MSoegtropIMC commented
@silene : I did the `_r`/`_l` renaming but not the `Qmult_power` and `Qmult_power_positive` one, because these are pre-existing lemmas (I just moved the second one around in `Qpower.v`).

2021-06-02 07:19 UTC, silene approved these changes

2021-06-02 15:29 UTC, silene commented
@coqbot merge now

2021-06-02 15:29 UTC, merged