[primitive ints] Add a <? b <? c and Sint63.abs
coq/coq pull request #14384
Opened 2021-05-25 16:16 UTC by ana-borges

I was missing the `a <? b <? c` and related notations in `Int63` and `Sint63`. I also included a definition for `Sint63.abs` and its specification w.r.t. `Z`.

**Kind:** feature.

- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).
- [ ] Overlay pull requests (if this breaks 3rd party developments in CI, see
https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md for details)

2021-06-01 12:08 UTC, ana-borges commented on test-suite/micromega/sint63.v
> +Qed.
@fajb, is this expected, or can I change some definitions to make it work directly?

2021-06-01 12:51 UTC, fajb commented on test-suite/micromega/sint63.v
> +Qed.
The problem is non-linear so it is expected that `lia` fails.
After case analysis, `lia` is able to linearise the problem.
I do not see any fix except improving `nia` -- don't hold your breath...

2021-06-01 14:19 UTC, ana-borges commented on test-suite/micromega/sint63.v
> +Qed.
Ok, thanks.

2021-06-02 06:54 UTC, herbelin commented
@proux01: would you like to have a look at this PR which seems otherwise rather straightforward to the outsider I'am? (cc @maximedenes too)

2021-06-02 19:44 UTC, silene requested changes
The changes to `Int63.v` seem wrong now that `Uint63.v` exists, don't they?

2021-06-02 19:44 UTC, silene commented on theories/Numbers/Cyclic/Int63/Sint63.v
> +    to_Z min_int < to_Z x <= to_Z max_int ->
Is the upper bound really needed?

2021-06-03 02:12 UTC, ana-borges commented
> The changes to `Int63.v` seem wrong now that `Uint63.v` exists, don't they?

Yeah. I wasn't sure which PR would end up being merged first. I'll update this one as soon as #13895 is merged.

2021-06-03 03:19 UTC, ana-borges commented on theories/Numbers/Cyclic/Int63/Sint63.v
> +    to_Z min_int < to_Z x <= to_Z max_int ->
Nope, good catch.

2021-06-03 03:21 UTC, ana-borges commented on theories/Numbers/Cyclic/Int63/Sint63.v
> +  intros neq_x_max; apply succ_bounded.
The `to_Z_*` versions I just added are strictly stronger than their `*_bounded` counterparts, so we may consider deleting the latter.

2021-06-03 03:29 UTC, ana-borges commented on theories/Numbers/Cyclic/Int63/Sint63.v
> +  intros neq_x_max; apply succ_bounded.
Hmm never mind, I guess they are equivalent. Still, I used `succ_bounded` to prove `to_Z_succ`. It's up to you whether to leave both or turn `succ_bounded` into an `assert` or something.

2021-06-03 06:15 UTC, silene commented on theories/Numbers/Cyclic/Int63/Sint63.v
> +  intros neq_x_max; apply succ_bounded.
Indeed, as it stands, `succ_bounded` is kind of useless and not worth keeping around. Now, there are two questions.

1. What naming should be used? We cannot have `mul_bounded` on one side and `to_Z_succ` on the other. In my personal projects, I tend to favor the later, but I would also be fine with the former.
2. What is the best antecedent for `to_Z_succ`. We have three choices: `x <> max_int`, `to_Z x <> to_Z max_int`, and `to_Z < to_Z max_int`. I have the feeling that the first one will be the most practical for the user, but I am not completely sure.

2021-06-03 12:02 UTC, ana-borges commented on theories/Numbers/Cyclic/Int63/Sint63.v
> +  intros neq_x_max; apply succ_bounded.
1. I agree.

2. I have the same feeling. If the user has `to_Z x <> to_Z max_int` in the context and must prove `x <> max_int`, they can do so without any lemmas, whereas to go from `x <> max_int` to `to_Z x <> to_Z max` one needs injectivity.

2021-06-03 14:00 UTC, proux01 reviewed
Could you rebase over #13895 so that once it is merged, we can proceed easily with this one?

The addition of abs is definitely nice.

I have no strong opinion about the `_ <? _ <? _` notations. I would rather not add them since I view primitive integers as a type used for programs rather than proofs and programming languages usually don't provide such notations.

2021-06-03 15:00 UTC, ana-borges commented
> Could you rebase over #13895 so that once it is merged, we can proceed easily with this one?

Yep.

> I have no strong opinion about the `_ <? _ <? _` notations. I would rather not add them since I view primitive integers as a type used for programs rather than proofs and programming languages usually don't provide such notations.

In principle I agree, but this was specifically requested by a friend who is trying `Sint63` out. He wanted it for a tool that solves a goal by computing it for all `x` bounded by some constants. Thus the `a <? x <? b` notation.

2021-06-04 09:58 UTC, silene commented
> In principle I agree, but this was specifically requested by a friend who is trying Sint63 out. He wanted it for a tool that solves a goal by computing it for all x bounded by some constants. Thus the `a <? x <? b` notation.

But is that notation useful in the general case? For example, if I were to write `0 <=? f x <? 10`, I would expect the value of `f x` to be computed only once. I would be annoyed if I had to remember that I need to write `let y := f x in 0 <=? y <? 10`.

2021-06-04 15:37 UTC, ana-borges commented
> But is that notation useful in the general case? For example, if I were to write `0 <=? f x <? 10`, I would expect the value of `f x` to be computed only once. I would be annoyed if I had to remember that I need to write `let y := f x in 0 <=? y <? 10`.

Fair. So your point is that adding the notation is misleading because it looks like it is doing more work than it is actually doing?

2021-06-04 15:56 UTC, silene commented
> So your point is that adding the notation is misleading because it looks like it is doing more work than it is actually doing?

Right, as defined, it is misleading. But I have no opinion either way on the notation itself. So, if you feel the notation is worth having, you should back it up with an actual definition to avoid the issue, e.g.,

```coq
Definition ltltb (m n p : int63) := m <? n && n <? p.
Notation "m <? n <? p" := (ltltb m n p).
```

2021-06-04 18:16 UTC, ana-borges commented
> So, if you feel the notation is worth having, you should back it up with an actual definition to avoid the issue

This is good at solving the problem you identified, but I don't fully like it as a solution either. It would mean that using lemmas about `_ && _` could only happen once the definition was unfolded (unless I'm missing something?), which is annoying. Short of reproving all the `&&` lemmas for these notations (which sounds like a bad idea), is there a way to have both features?

2021-06-04 18:42 UTC, silene commented
> is there a way to have both features?

None that I know of, unfortunately. Or rather, I know some, but they are so heavy that they are not worth it. For example, you can define a `let_in` function and prove that it is compatible with pointwise equality (and declare the corresponding `Proper` instance), so that you can use `setoid_rewrite` to rewrite `&&` under the binder:
```coq
Definition let_in {T U} (v:T) (w:T -> U) := w v.
Notation "m <? n <? p" := (let_in n (fun v => m <? v && v <? n)).
```

2021-06-04 18:53 UTC, proux01 commented
Maybe an alternative could be to use ssreflect's rewrite which tends to unfold automatically (haven't tested though).

2021-06-05 11:44 UTC, ana-borges commented
> Maybe an alternative could be to use ssreflect's rewrite which tends to unfold automatically (haven't tested though).

Yes, this does work.

As someone who mostly uses ssr, I would be fine with this solution. But I just realized that the `bool` version of this notation is a mathcomp thing, and it doesn't otherwise appear in the stdlib. So I guess it doesn't make sense to add it, as it would be lonely.

2021-06-05 17:06 UTC, proux01 approved these changes
LGTM

2021-06-06 17:02 UTC, silene commented
Please rebase and squash, so that we have a clearer view of whether this is ready to merge.

2021-06-07 08:42 UTC, silene approved these changes

2021-06-07 08:42 UTC, silene commented
@coqbot merge now

2021-06-07 08:42 UTC, merged