Correctly set prefix when no default is given.
coq/coq pull request #14775
Opened 2021-08-12 15:22 UTC by Alizter

The behavior before was defaulting on the deprecated "local"
option. This doesn't make sense since "-local" is just an alias for
"-profile devel" which sets the prefix anyway. Therefore, when no
prefix is given, as is often the case, we should use the default
prefix which can be found in `do_one_instdir`. Of course, this is only
a hack to get things working for the time being. The correct solution
would be to rewrite the entire configure.ml file to not have such
ad-hoc reasoning.

Fixes / closes #14468

2021-08-12 15:25 UTC, SkySkimmer commented
No prefix should be the same as devel, not pick some arbitrary global location imo

2021-08-12 15:34 UTC, Alizter commented
That's not what I gathered from #14468. It is said here that no prefix defaults to the "arbitrary location" as done for coq <= 8.13. The problem at the moment is that the configure script actually says it will install binaries here, but proceeds to not do that.

2021-08-16 10:08 UTC, SkySkimmer requested changes
Breaks the test suite eg when doing `dune build && cd test-suite && make unit-tests`

2021-08-17 22:22 UTC, Alizter commented
No clue how to fix this, hopefully another PR can.

2021-08-17 22:22 UTC, closed without merging