Prefilter unfold hints without an associated head global.
coq/coq pull request #14876
Opened 2021-09-11 11:07 UTC by ppedrot

For some reason, undiscriminated hint bases associate no head constant to unfold hints over transparent constants. A consequence is that they are applied to any goal. This cannot be changed without breaking everything, but this leads to exponential proof searches that attempt to perform dummy unfoldings on goals without the constant.

In order to speed up the search, we simply prefilter such hints depending on whether the constant appears on the goal. If not, we know that applying the hint is actually useless, so this should not change the observable behaviour of auto tactics, except for a change in search depth.

Fixes #14874: Exponential blowup with Hint Unfold.

2021-09-11 11:08 UTC, ppedrot commented
Bench: https://gitlab.com/coq/coq/-/jobs/1582072482

2021-09-11 13:56 UTC, ppedrot commented
The math-classes failure is a nasty interaction with βι-normalization. Since `unfold` performs full βι-reduction, it might change the shape of the goal even if the constant does not appear. I guess I could check for progress as argued in the original bug report but this does not seem right either. I'd be inclined to attribute the old behaviour as a bug exploit, but I don't feel like performing βι all the time on the goal either...

2021-09-11 14:46 UTC, ppedrot commented
Note that, as usual for hint tactics, [the documentation lies](https://coq.inria.fr/refman/proofs/automatic-tactics/auto.html#coq:cmd.Hint-Unfold). It claims that `Hint Unfold` only applies to goals whose head is the unfolded reference but this is obviously not true for discriminated hint databases.

2021-09-11 18:17 UTC, cpitclaudel commented
Thanks!!

> For some reason, undiscriminated hint bases associate no head constant to unfold hints over transparent constants.

But isn't the original example using a discriminated hint db?

2021-09-11 22:59 UTC, JasonGross requested changes
This needs a changelog entry describing how `Hint Unfold` no longer introduces pervasive beta-iota(?) normalization, and the solution is to add `Hint Extern 1 => progress cbv beta iota` or similar.

2021-09-13 08:09 UTC, ppedrot commented
See also #14679 which was a different take at the same issue. In that PR, instead of looking for the presence of the constant everywhere we looked at the head of the goal, as in undiscriminated mode.

2021-09-13 11:06 UTC, ppedrot commented
In the end I think I'll close this PR in favour of #14679. That PR is a slight variant on the theme, where we only unfold the constant when it's a the head of the conclusion. The major advantage of the latter is that this makes the behaviour of Hint Unfold uniform between discriminated and undiscrimited databases. It also removes a bit of cruft linked to this dedicated side-stepping. It is slightly less backwards compatible, but the fixes are very similar.

2021-09-13 11:08 UTC, closed without merging