Separate nametabs for open modules/modtypes/sections vs closed modules
coq/coq pull request #15078
Opened 2021-10-27 14:36 UTC by SkySkimmer

Fix #14529

Overlays:
- https://github.com/coq-community/paramcoq/pull/86

2021-10-28 17:00 UTC, ejgallego approved these changes
LGTM, @herbelin maybe you wanna have a look too?

2021-11-02 14:41 UTC, ppedrot requested changes
This needs a changelog.

2021-11-03 19:10 UTC, ppedrot approved these changes

2021-11-03 19:11 UTC, ppedrot commented
@coqbot merge now

2021-11-03 19:11 UTC, merged