Replace P_Rmin with Rmin_case (fixes #15382)
coq/coq pull request #15388
Opened 2021-12-20 13:12 UTC by olaure01

Fixes #15382 

- [ ] Added **changelog**.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

2021-12-20 14:39 UTC, silene requested changes

2021-12-20 14:39 UTC, silene commented on theories/Reals/Rpower.v
> -Lemma P_Rmin : forall (P:R -> Prop) (x y:R), P x -> P y -> P (Rmin x y).
I doubt it was ever used in the wild. But just to be on the safe side, you should write something like
```coq
Definition P_Rmin_subdef (P:R -> Prop) (x y:R) := Rmin_case x y P.
#[deprecated(since = "8.16", note = "Use Rmin_case instead.")]
Notation P_Rmin := P_Rmin_subdef.
```

2021-12-20 14:44 UTC, olaure01 commented on theories/Reals/Rpower.v
> -Lemma P_Rmin : forall (P:R -> Prop) (x y:R), P x -> P y -> P (Rmin x y).
You are right, this was just a first run to test CI.
I have prepared a "deprecation version" very similar to what you suggest, without the intermediate `P_Rmin_subdef` though.

2021-12-20 14:52 UTC, silene commented on theories/Reals/Rpower.v
> -Lemma P_Rmin : forall (P:R -> Prop) (x y:R), P x -> P y -> P (Rmin x y).
`P_Rmin_subdef` is just there because only notations can be deprecated, not definitions, as far as I know. But if you can make it work without the auxiliary definition, all the better.

2021-12-20 14:56 UTC, olaure01 commented on theories/Reals/Rpower.v
> -Lemma P_Rmin : forall (P:R -> Prop) (x y:R), P x -> P y -> P (Rmin x y).
I was simply linking `P_Rmin` to `Rmin_case` through a notation, but your approach is more robust wrt types.
I let the current CI run finish and I push the new version.

2021-12-21 06:51 UTC, silene commented
@coqbot merge now

2021-12-21 06:51 UTC, silene approved these changes

2021-12-21 06:51 UTC, silene commented
@coqbot merge now

2021-12-21 06:51 UTC, merged