Use anonymous primitive projections in the VM.
coq/coq pull request #15401
Opened 2021-12-24 19:15 UTC by ppedrot

This patch changes the PROJ VM opcode to only take the projection index as argument, rather than both the index and the high-level Projection.Repr.t representation. This allows removing the code for global registering of projections in the VM, thus reducing the size of relocations. Since this also makes the bytecode slightly shorter, this is a net gain in memory and vo size.

The only place where this has an effect is during reification of accumulated projections. One could think that this makes the process more expensive since we now have to reconstruct the projection, but in reality we were already accessing the environment there to fetch the inductive block (and doing so several times, actually). The new code only accesses the environment once, so even there this should be faster on average.

2021-12-24 19:16 UTC, ppedrot commented
Bench: https://gitlab.com/coq/coq/-/jobs/1919336897

2021-12-25 08:08 UTC, silene requested changes
The interpreter and compiler parts look good. I cannot, however, vouch for the `Vnorm` part, and I doubt this code path is exercised anywhere in the testsuite or in the CI. Could you please add some tests for it, e.g., in `test-suite/success/primitiveproj.v`?

2021-12-25 12:59 UTC, ppedrot commented
Indeed, we do have conversion tests in `success/vm_records.v` but I didn't find any convincing example of a check for VM normalization of primitive records. I'll add one.

2021-12-25 14:04 UTC, ppedrot commented
@silene done

2021-12-25 17:30 UTC, silene approved these changes

2021-12-25 17:32 UTC, silene commented
@coqbot merge now

2021-12-25 17:32 UTC, merged