[stdlib] [Arith] Integrate deprecated results from Arith.Even and Arith.Div2
coq/coq pull request #15411
Opened 2021-12-30 10:29 UTC by olaure01

Following #14736, deprecated results not already available in `Arith.PeanoNat` are integrated in `PeanoNat.Nat`.
Results about `Even.even` are integrated as results about `Nat.Even`.
The induction definition `Even.even` is integrated as the new `Nat.Even_alt`.

- [ ] Added **changelog**.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

2021-12-30 10:29 UTC, olaure01 commented
@palmskog let see how this works.

2021-12-30 13:03 UTC, palmskog commented
To me, this is definitely an improvement on the current state of `Arith.*` deprecations in that one no longer needs to refactor a whole file that uses `Even.odd`/`Even.even`/`Div2.odd_double`, etc., since switching to `Nat.Odd_alt` is viable.

However, if I'm reading the diff correctly, Coq project maintainers are still forced to do awkward switches between `Nat.Odd_alt` and `Nat.Odd` in places, e.g.,
```coq
destruct (Even.even_odd_dec n) as [H_parity|H_parity]; apply H_parity in H.
```
must be rewritten as
```coq
destruct (Nat.Even_Odd_dec n) as [H_parity|H_parity].
- apply Nat.Even_alt_Even in H_parity; apply H_parity in H.
- apply Nat.Odd_alt_Odd in H_parity; apply H_parity in H.
```

I would prefer that the decision procedure directly for `Nat.Odd_alt` would instead become available in `Nat` directly, but I realize this could be viewed as clogging up `Nat` with "redundant" content.

2021-12-30 15:07 UTC, olaure01 commented
> However, if I'm reading the diff correctly, Coq project maintainers are still forced to do awkward switches between `Nat.Odd_alt` and `Nat.Odd` in places, e.g.,
> 
> ```coq
> destruct (Even.even_odd_dec n) as [H_parity|H_parity].
> - apply H_parity in H0.
> - apply H_parity in H1.
> ```
> 
> must be rewritten as
> 
> ```coq
> destruct (Nat.Even_Odd_dec n) as [H_parity|H_parity].
> - apply Nat.Even_alt_Even in H_parity; apply H_parity in H0.
> - apply Nat.Odd_alt_Odd in H_parity; apply H_parity in H1.
> ```

Maybe the more compact:
```coq
destruct (Nat.Even_Odd_dec n) as [H_parity%Nat.Even_alt_Even|H_parity%Nat.Odd_alt_Odd].
- apply H_parity in H0.
- apply H_parity in H1.
```
could be closer to the original proof.
Moreover would it be a big trouble to do kind of a dual approach: replacing all `Even.even` directly with `Nat.Even`, and going back to `Nat.Even_alt` only when the inductive structure is really required? Maybe adding an induction principle for `Nat.Even` and `Nat.Odd` in `PeanoNat.Nat` would make it even easier:
```coq
Lemma Even_ind : forall P : nat -> Prop,
  P 0 -> (forall n : nat, Nat.Odd n -> P (S n)) ->
  forall n : nat, Nat.Even n -> P n.
```

2021-12-30 16:03 UTC, palmskog commented
OK, if `Nat.Odd_alt` and `Nat.Even_alt` are to be "second-class" definitions, then I would propose doing the following additions to the PR for a smoother transition:
1. Explicitly say in the release notes that the theory of `Even.odd`/`Even.even` is expire in the future, and maintainers are advised to access needed results by first converting their statements that use `Even.odd`/`Nat.Odd_alt` and `Even.even`/`Nat.Even_alt` via `Nat.Even_alt_Even`/`Nat.Odd_alt_Odd` to instead be about `Nat.Odd` and `Nat.Even`. I don't think that's currently as clear as it can be.
2. Provide some canonical induction priniciple(s) for `Nat.even`/`Nat.odd` and mention it or them in the release notes. Is the example `Even_ind` the most general principle? I thought one had to do something like the following to get the highest generality:
```coq
Scheme even_odd_ind := Induction for Even.even Sort Prop
   with odd_even_ind := Induction for Even.odd Sort Prop.
```

2021-12-30 17:13 UTC, olaure01 commented
> 1. Explicitly say in the release notes that the theory of `Even.odd`/`Even.even` is to expire in the future

That is mostly the meaning of "deprecated" or "obsolete". However I agree the changelog can be more explicit and I think I will merge the changelog for #14736 and #15411 to get something more clear and explicit.

> 2. Provide some canonical induction priniciple(s) for `Nat.even`/`Nat.odd` and mention it or them in the release notes. Is the example `Even_ind` the most general principle?

This was just the basic principle generated by the inductive. If we agree it is good to provide such induction principles for `Nat.Even`, it seems indeed necessary to prove the more general mutual inductive principles (apparently they cannot be easily generated from the basic ones), however the combined scheme does not seem to be necessary since `Combined Scheme` allows to generate it.

2021-12-30 18:05 UTC, olaure01 commented
@palmskog could you have a look at the new [changelog](https://github.com/coq/coq/blob/c351a9af1123c65e1a5047c1ba522aa726cb459b/doc/changelog/10-standard-library/14736-Arith2.rst) and tell me what you think?

2021-12-30 18:50 UTC, palmskog reviewed
Looks good, but I found some types and made some suggestions.

2021-12-30 18:50 UTC, palmskog commented on doc/changelog/10-standard-library/14736-Arith2.rst
> +  Concerning the defintions of parity properties (even and odd), it is recommanded to use ``Nat.Even`` and ``Nat.Odd``.
```suggestion
  Concerning the definitions of parity properties (even and odd), it is recommended to use ``Nat.Even`` and ``Nat.Odd``.
```

2021-12-30 18:50 UTC, palmskog commented on doc/changelog/10-standard-library/14736-Arith2.rst
> +  The equivalence between the two definitions are provided as ``Nat.Even_alt_Even`` and ``Nat.Odd_alt_Odd``.
```suggestion
  If an inductive definition of parity is required, the mutually inductive ``Nat.Even_alt`` and ``Nat.Odd_alt`` can be used. However, induction principles for ``Nat.Odd`` and ``Nat.Even`` are also available as ``Nat.Even_Odd_ind`` and ``Nat.Odd_Even_ind``.
  The equivalence between the non-inductive and mutually inductive definitions of parity is expressed in ``Nat.Even_alt_Even`` and ``Nat.Odd_alt_Odd``.
```

2021-12-31 15:01 UTC, palmskog approved these changes
Purely from the perspective of a Coq project maintainer, these are positive changes that make it easier to migrate away from `Arith.*` definitions towards `Nat.*` equivalents.

2022-01-03 13:03 UTC, Alizter requested changes
Looks good to me. While you are poking around in PeanoNat.v could you give the indentation a pass? Currently I am seeing 1 space indentation in a lot of places, we should make this 2 space indentation.

2022-01-03 13:48 UTC, Alizter approved these changes

2022-01-03 13:48 UTC, Alizter commented
will merge soon

2022-01-03 17:17 UTC, Alizter commented
@coqbot merge now

2022-01-03 17:17 UTC, merged