Stop caring about unfolding state of primproj in constr_matching
coq/coq pull request #15559
Opened 2022-01-27 12:53 UTC by SkySkimmer

Fix #15554

2022-01-27 12:58 UTC, SkySkimmer commented
Note all 9 combinations of matching with primitive projections in the added test.

2022-01-27 13:01 UTC, SkySkimmer commented
In this PR all the variants (compatibility constant, folded, unfolded) are equated by constr_matching (following the previous decision to equate compatibility constant and folded projection), other choices are possible.

2022-01-27 13:47 UTC, SkySkimmer commented
Not sure what the other tests were trying to do, the code I removed seems to test bugs(?)

2022-01-27 15:10 UTC, SkySkimmer commented
I guess this reverts https://github.com/coq/coq/commit/b6e39ade125862ba41ca17b06b8e35726b9b0d7d

2022-01-27 15:14 UTC, ppedrot commented
A good first step towards the removal of the unfolded flag if you ask me... But there is still quite a bit here and there.

2022-01-27 15:20 UTC, mattam82 commented
In particular, equating the constant to the projection in evarconv when the constant is not delta-reducible, is giving me another headache (because whd_state_gen will not push a Zproj on the stack if it is not delta-reducible or does not have the unfolded flag)...

2022-01-27 22:08 UTC, ppedrot commented
To be honest I am very surprised nobody relies on that in the CI.

2022-01-28 09:19 UTC, mattam82 commented
Me too, I would have thought some of Jason's developments would rely on it.

2022-01-28 12:59 UTC, JasonGross commented on test-suite/bugs/bug_3656.v
> -Proof. intro. progress unfold setT.
Does `progress` no longer see unfolding status as progress?

2022-01-28 13:17 UTC, ppedrot commented on test-suite/bugs/bug_3656.v
> -Proof. intro. progress unfold setT.
`progress` uses term equality, not matching. This PR shouldn't change this behaviour (but it will eventually, when we get rid of the unfolding flag).

2022-01-28 16:13 UTC, ppedrot requested changes
This needs a changelog.

2022-02-01 16:54 UTC, ppedrot approved these changes

2022-02-02 09:56 UTC, ppedrot commented
@coqbot merge now

2022-02-02 09:56 UTC, merged