Excluding Variant and Record from function find_inductive
coq/coq pull request #15625
Opened 2022-02-05 16:24 UTC by herbelin

**Kind:** clarification of semantics

This simplifies the description of the condition about when a fixpoint is allowed (see #407, 7ceed3c76e), and let the tactic `fix` follows the same rule as the term constructor `fix`.

More precisely, `find_inductive` becomes a check of `mind_finite = Finite` (which at the current time means defined with the keyword `Inductive`; eventually, it could rather mean truly-recursive Inductive, excluding e.g. `prod`, `unit`, ...).

- [x] Added / updated **test-suite**

2022-02-05 16:46 UTC, SkySkimmer requested changes
This is the wrong direction IMO, fix on a variant or fakerecord should be allowed (with not-truly-recursive warning).

2022-02-05 21:07 UTC, herbelin commented
> This is the wrong direction IMO, fix on a variant or fakerecord should be allowed (with not-truly-recursive warning).

The PR is aligning the definition of `find_inductive` and of the tactic `fix` to what `check_fix` allows. A side effect of the PR is also to symmetrizing `find_inductive` and `find_coinductive`. It was not its intent to take position and change the current rule deciding on which non-recursive types the `fix` constructor applies.

But even if the question of which non-recursive types should accept `fix` and `cofix` was for me beyond the intent of this PR, this does not mean that we should not take a decision, on the contrary.

In particular, I like the view that a `fix` is like a `match`, so only for positive types, which I presume is the line you have in mind. (If so, do you actually go as far as to recommend that we dually accept `cofix` also on non-recursive negative types?)

While at it, two other points should be discussed:
- it seems that we are missing a terminology for a type which is either truly-recursive inductive, truly-recursive coinductive, variant or negative record. I'm thinking to the confusingly-named `Inductive.find_rectype` which includes variants and records. We should find an alternative.
- `mind_finite` currently mostly reflects the keyword used at definition time rather than the effective recursive or non-recursive nature of the type; we should clarify it (as I suggested in the header).

Hoping that this clarifies things.

2022-02-06 17:49 UTC, herbelin commented
PS: Even if the positive/negative, colimit/limit, initial-algebra/terminal-coalgebra is a very nice model, I'm curious (as already said somewhere else) to understand if we can get in the context of intuitionistic logic an interesting hybrid positive/negative notion of conjunction that has both "match" and projections. It looks a bit strange, but it seems interesting computationally to have both kinds of elimination at the same time. This remark is not directly related to the PR though (except to say that one day, one may perhaps imagine merging primitive and non primitive records).

2022-02-06 22:48 UTC, ppedrot commented
First thing first, we should not have the kernel behave differently on high-level concepts like Variant and Record. I don't really understand why we make such a distinction between BiFinite and Finite. CoFinite types are something completely different, and the choice to represent them with constructors is a historical error that shouldn't be taken into consideration for this kind of discussion.

IMO we should warn for fixpoints on BiFinite types and forbid it inside the kernel, instead replacing Fix nodes by Case nodes on the fly during pretyping.

2022-02-06 23:02 UTC, SkySkimmer commented
>IMO we should warn for fixpoints on BiFinite types and forbid it inside the kernel

Isn't that a distinction between Finite and BiFinite?

2022-02-07 10:39 UTC, herbelin commented
> First thing first, we should not have the kernel behave differently on high-level concepts like Variant and Record. I don't really understand why we make such a distinction between BiFinite and Finite. CoFinite types are something completely different, and the choice to represent them with constructors is a historical error that shouldn't be taken into consideration for this kind of discussion.

In the above, is your mental model the following:
- BiFinite = Variant + destructor-based Record (i.e. PrimRecord)
- Finite = Inductive = initial algebra
- CoFinite = CoInductive = terminal co-algebra
- Variant = colimit = non-recursive initial algebra
- destructor-based Record = limit = non-recursive terminal co-algebra

In particular, do you see PrimRecord to be to CoFinite what Variant is to Finite, or do you see them differently?

> IMO we should warn for fixpoints on BiFinite types and forbid it inside the kernel, instead replacing Fix nodes by Case nodes on the fly during pretyping.

Do you mean here BiFinite in the current "keyword" sense (i.e. `Variant` or `Record`) or BiFinite in the semantic sense (i.e. non-recursive inductive or coinductive type, i.e., in terms of user keywords, either `Variant`, `Record`, or non-recursive `Inductive`, non-recursive `CoInductive`)?

Assuming you're referring to the semantic sense, are Fix on semantic BiFinite really used in the large? If no, an alternative is to ask users to replace them themselves by Case?

Part of the confusion comes from that Coq can stamp a non-recursive inductive either as FakeRecord/NotRecord BiFinite, or as FakeRecord/NotRecord Finite with impact on what is allowed to do with it; similarly, it can stamp a non-recursive "primitive" coinductive type either as PrimRecord BiFinite or as PrimRecord CoFinite; of course, this reflects the fact that a non-recursive type can be seen either as a (co)limit or as (co)algebra, but this impacts the decisions we take later on these types, especially when building schemes, or support Fix/CoFix on them.

> we should not have the kernel behave differently on high-level concepts like Variant and Record

You mean seeing everything as initial algebra / terminal coalgebra even when non-recursive. Yes, why not. Then, we would allow Fix on all inductive (recursive or not) and CoFix on all coinductive (recursive or not). As for schemes, we would check if the type is really recursive or not to decide if we need a Fix/CoFix.

2022-02-07 10:43 UTC, SkySkimmer commented
>Assuming you're referring to the semantic sense, are Fix on semantic BiFinite really used in the large? If no, an alternative is to ask users to replace them themselves by Case?

It doesn't matter if it's used, we should keep the kernel simple and IMO that means matching the restriction on fixpoints to where it's needed, ie types with eta.

2022-02-07 10:48 UTC, herbelin commented
@skyskimmer: I would say yes and no...

In my long-term model, we should have support for eta on _all_ non-recursive types (i.e. also on `Variant` and "fake" records). It is decidable and intuitive. With this respect, the question of when supporting fix is not so much about eta than about being "negative" (first possible criterion) or being non-recursive (second possible criterion).

2022-02-07 11:07 UTC, SkySkimmer commented
>the question of when supporting fix

We support fix when we can, and currently we can't for types with eta. It has nothing to do with being recursive except that we don't allow eta for recursive types. I don't know what negative means or what it has to do with coq.

2022-02-07 12:46 UTC, herbelin commented
> I don't know what negative means or what it has to do with coq.

Sorry about it, I thought this was a terminology commonly used at Gallinette. By "negative", I meant the distinction in linear logic between positive (sums, bool, option, nat, inductive types, match-based records, ...) and negative types (forall, implication, projection-based records, coinductive types, ...). It does not fully apply to CIC because CIC is intuitionistic, but it provides with a very good basis to understand the structure of types (for instance, negative types have eta on terms, but positive types have eta on "co-terms", that is on evaluation contexts).

> > the question of when supporting fix
> 
> We support fix when we can, and currently we can't for types with eta. It has nothing to do with being recursive except that we don't allow eta for recursive types.

I would again say yes and no. The purpose of "fix" is to do recursion. So it seems a legitimate question to wonder whether it makes sense to propose to do a recursion on a type for which no recursive call is actually possible.

The issue arises also when building schemes which are supposed to canonically follow the structure of the type. Up to know, if you define `Inductive bool := true | false`, it sees `Inductive`, then, because of the `Finite` flag coming from the `Inductive` keyword, `Scheme Boolean Equality` thinks `bool` is recursive and defines
```
bool_beq := fix bool_eqrec (X Y : bool) {struct X} : bool :=
  if X then if Y then true else false else if Y then false else true
```
which is a bit strange. So, "somewhere" (at least when writing schemes), the information of being actually non-recursive or not should matter.

2022-02-07 13:32 UTC, ppedrot commented
> It is decidable

Proof required...

2022-02-11 19:07 UTC, herbelin commented
@ppedrot, @SkySkimmer: At the call (@SkySkimmer was not yet there I think), the question was discussed of changing `mind_finite` so that it tells if the type is non-recursive or not rather than telling what keyword was used by the user.

I don't remember the decision on warnings, I believe it was to keep a warning for fixpoints on non truly recursive non-primitive-record types (consistently with @SkySkimmer's remark above).

We did not discuss about what the definition of `find_inductive` should be (i.e. including non-recursive types or not), nor about the definition of `find_coinductive` (i.e. including primitive records or not in cases `find_inductive` itself includes non-recursive match-based types).

They are actually used very little (compared to `find_rectype`), so a possible solution I see which is consistent with the concerns of @ppedrot above would be to simply modify their type so that they additionally return a Boolean telling if the type is truly recursive or not, since after all, this is what their clients (the fix/cofix tactics and schemes construction functions) are waiting for.

----
On a side and amazing note, fixpoints on types with non-linear constraints on indices directly within the `fix` context are somehow wrong as suggested [here](https://github.com/coq/coq/pull/407#issuecomment-275138455), with details by Marc in issue coq-community/paramcoq#4. This is not about recursivity or not though, so I don't know what criterion to apply if we ever want to exclude them.

2023-03-06 14:01 UTC, ppedrot commented
This PR is trivial code-wise, is disagreed upon by at least two core devs and has been untouched for a year. I don't think there is much point in keeping it open, so forcefully closing it.

2023-03-06 14:01 UTC, closed without merging