Add variants of lemmas that do not care about the inverse of zero
coq/coq pull request #15644
Opened 2022-02-08 08:37 UTC by silene

Consider the following lemma from the standard library:
```coq
Lemma powerRZ_mult_distr :
  forall m x y, (0 <= m)%Z \/ (x * y <> 0) -> powerRZ (x*y) m = powerRZ x m * powerRZ y m.
```
The precondition is actually spurious and the following much more usable lemma holds:
```coq
Lemma powerRZ_mult :
  forall m x y, powerRZ (x*y) m = powerRZ x m * powerRZ y m.
```

This first commit of this pull request adds variants of numerous existing lemmas. (See the third commit for the actual list.) Naming of lemmas was done according to Coquelicot's conventions. If the standard library was already using the correct name by chance, a prime has been suffixed to the names of the new lemmas.

The second commit makes use of the variants across the standard library, which removes 300 lines of proof that were use to prove the pointless preconditions.

2022-02-08 08:45 UTC, MSoegtropIMC commented
This is really an improvement, thanks! From your comment I guess I should wait a bit with the review - please let me know when it is ready. Btw.: you might want to mark the PR as draft if you plan for substantial additional commits.

2022-02-08 08:52 UTC, thery commented
is there a plan to deprecate some theorems?

2022-02-08 09:09 UTC, silene commented
> From your comment I guess I should wait a bit with the review

I am not sure what gave this impression, but the pull request is complete.

> is there a plan to deprecate some theorems?

Not from me. We could, I guess.

2022-02-08 09:13 UTC, MSoegtropIMC commented
> I am not sure what gave this impression, but the pull request is complete.

You wrote in the comment "This **first commit of this pull** request adds variants ..." - this gave me the impression there will be further commits.

Fine, I will do the review then.

2022-02-08 09:44 UTC, MSoegtropIMC commented
I agree with @thery that the now redundant lemmas should be deprecated.

What I need to check is if the naming of lemmas is consistent with Q (and Z) - if we change the naming we should check if consistency improves or gets worse by the changed names.

I somewhere have a list of equivalent lemmas in R Q and Z - if I can find it.

2022-02-09 18:31 UTC, MSoegtropIMC commented
I had a look at the R vs Q vs Z naming for division lemmas and would say that the status quo is that there is very little similarity between naming and existence of division lemmas between Z, Q and R. This PR doesn't make it worse or better than it is.

@silene: is the naming convention of Coquelicot explicitly described somewhere? What is your opinion on the deprecation question?

2022-02-10 12:56 UTC, silene commented
> is the naming convention of Coquelicot explicitly described somewhere?

It is in the documentation: http://coquelicot.saclay.inria.fr/html/Coquelicot.Coquelicot.html. But for some reason, there is only part of the rules (which is a bit surprising). I guess one would need to read Catherine Lelay's PhD thesis to get all the rules, but it is in French.

To summarize, the naming convention that was applied here is the one for rewriting rules. It states that they should be named by their left-hand side. It also states that, if the operator names are prefixed (i.e., `R` in this case), this prefix does not have to be repeated for subsequent operators. Finally, it states that the right-hand side should be more elementary than the left-hand side.

The last rule is a bit subjective, but still, it helps. For example, `pow_inv` is `(/ x)^n = / x^n`, and not the converse, because there are more parentheses on the left-hand side that way. And it is named `pow_inv` because that is the exact description of the left-hand side.

> What is your opinion on the deprecation question?

I am fine with it. I am just unsure whether it is a good idea to deprecate old symbols during the same release new symbols are introduced.

2022-02-11 21:03 UTC, MSoegtropIMC commented
@silene: thanks for the link - a very nice PhD thesis with a lot of overview information - unfortunately a bit outdated, but it might still serve as a base for the reals overview we once discussed with Hugo.

Give me a bit more time to ponder over the naming question. I am a bit hesitant because I prefer a naming where the lemma name contains some mathematical concept, as in `Rinv_involutive` or `Rinv_mult_distr`, because this makes it easier to search. I frequently search for a combination of structure and pieces of the name, say:
```
Search (/ _) "invol".
Search (/ _) "distr".
```
I would think that the names you chose are easier to remember, but I memorize only very few lemma names - I almost always search for them. And for searching it is not much of a help of the lemma name matches the structure - I can search for the structure right away.

Of course I likely would have ended up with a different approach if there would be a nice naming scheme in the standard library.

May I ask what your approach to finding lemmas is?

2022-02-14 07:50 UTC, silene commented
> May I ask what your approach to finding lemmas is?

I never use the name. I either use several operators or a single more complicated pattern:
```coq
Search (/_) (_<_).
Search (/(_*_)).
```

By the way, I have now pushed a commit with the deprecation warning.

2022-02-14 09:18 UTC, MSoegtropIMC requested changes
LGTM, except for the one missing deprecation warning (I possibly just couldn't find). About the other commends I don't have strong feelings - they are just thoughts you might want to consider.

2022-02-14 09:18 UTC, MSoegtropIMC commented on theories/Reals/R_sqr.v
>  Lemma Rsqr_div : forall x y:R, y <> 0 -> Rsqr (x / y) = Rsqr x / Rsqr y.
Shouldn't this have a deprecation message as well?

2022-02-14 09:18 UTC, MSoegtropIMC commented on theories/Reals/Rfunctions.v
> +Lemma pow_inv x n : (/ x)^n = / x^n.
I am not sure I like this name. Yes it is consistent with the inconsistent naming of `pow` (vs. `Rmult`...), but I would think that most people use the notations and don't even know that `pow` is named like this. I would actually vote for deprecating the name `pow` and change it to `Rpow`.

2022-02-14 10:18 UTC, silene commented on theories/Reals/RIneq.v
> +Hint Resolve Rinv_involutive_depr: real.
I guess so. Let us try.

2022-02-14 10:18 UTC, silene commented on theories/Reals/R_sqr.v
>  Lemma Rsqr_div : forall x y:R, y <> 0 -> Rsqr (x / y) = Rsqr x / Rsqr y.
Good catch.

2022-02-14 10:19 UTC, silene commented on theories/Reals/Rfunctions.v
> +Lemma pow_inv x n : (/ x)^n = / x^n.
I do not have a strong opinion either way. But if you are telling me that you intend to submit a pull request that renames `pow` to `Rpow`, then yes, I do not mind renaming the theorem preemptively.

2022-02-14 10:30 UTC, MSoegtropIMC commented on theories/Reals/Rfunctions.v
> +Lemma pow_inv x n : (/ x)^n = / x^n.
For sure I would be fine doing a PR which cleans up R function and lemma naming, but I would prefer to do a larger move and probably go for `R.func` then. If there is interest, we should meet and discuss the naming rules and things like ordering of premises.

My argument was more that the name "pow" is for the majority of users hidden behind notations, so that making the lemma name consistent with the hidden inconsistent name rather than consistent with other user visible lemma names might not be helpful.

2022-02-15 04:58 UTC, silene commented on theories/Reals/RIneq.v
> +Hint Resolve Rinv_involutive_depr: real.
For the record, this caused a failure in Flocq, since less subgoals were left after executing `auto with real`. I have applied a backward compatible fix to Flocq.

2022-02-15 05:01 UTC, silene commented
The MetaCoq failure is completely unrelated. It happens on other pull requests too.

2022-02-15 08:36 UTC, MSoegtropIMC commented on theories/Reals/Rfunctions.v
> +Lemma pow_inv x n : (/ x)^n = / x^n.
@silene : what is your preference here:

- leave it as is

- change the name to Rpow_inv and I do a PR to change pow to Rpow by next weekend (or add a commit to your branch if you prefer)

2022-02-15 10:22 UTC, silene commented on theories/Reals/Rfunctions.v
> +Lemma pow_inv x n : (/ x)^n = / x^n.
I was about to rename `pow_inv` and then I noticed that there are already about 20 theorems that are named `pow_foo`, while only one is `Rpow_foo`. (And there is one broken `RPow_foo`.) So, renaming it to `Rpow_inv` does not seem a good idea anymore, as it would stick like a sore thumb.

2022-02-15 10:31 UTC, MSoegtropIMC commented on theories/Reals/Rfunctions.v
> +Lemma pow_inv x n : (/ x)^n = / x^n.
Indeed - I didn't think of that. So this is good to go and I will merge.

2022-02-15 10:32 UTC, MSoegtropIMC approved these changes

2022-02-15 10:50 UTC, MSoegtropIMC commented
@coqbot merge now

2022-02-15 10:51 UTC, merged