ltac2 apply/eapply: use open_constr in place of constr (fixes #15691)
coq/coq pull request #15741
Opened 2022-02-27 12:45 UTC by artagnon

As Gaëtan and Pierre-Marie hinted in the issue, `open_constr` seems to fix the bug. I'm not an expert, and I _think_ it is correct, because the Notations for `exact` and `eexact` use `open_constr`; from my black-box usage of Coq, `apply` and `eapply` seem to be better at unifying things than `exact` and `eexact`, and `open_constr` is a generalization of `constr`.

[x] Added test.

2022-02-27 19:42 UTC, ppedrot commented
Since 8.15 (?) Ltac1 uses what amounts to `uconstr` (or `preterm` in Ltac2 parlance). It's slightly different to use an `open_constr` because the goal type cannot be taken into account when inferring the type. For uniformity we may consider using `preterm` directly instead, but that means tweaking both the ML and the exposed primitive API.

2022-02-28 09:37 UTC, ppedrot requested changes
This needs a changelog, because it's changing the observable behaviour of the tactic.

2022-02-28 09:58 UTC, artagnon commented
Thanks; added.

2022-02-28 10:00 UTC, ppedrot commented on doc/changelog/05-tactic-language/15741-ltac2-apply.rst
> +  unification inconsistent with `exact` and `eexact`.
Nitpick, but I've read the warning message enough to have been traumatized: there shouldn't be a dot finishing this sentence, it's already there two lines below.

2022-02-28 10:11 UTC, ppedrot approved these changes

2022-02-28 10:47 UTC, ppedrot commented
@coqbot merge now

2022-02-28 10:47 UTC, merged