Fix extraction of max/min to Stdlib.max/min
coq/coq pull request #16092
Opened 2022-05-28 21:11 UTC by Alizter

Turns out in https://github.com/coq/coq/pull/15333 that `Stdlib.Int.max` and `Stdlib.Int.min` only appear in OCaml 4.14. So we revert the versions already there.

Thanks for the catch @liyishuai!

https://github.com/coq/coq/pull/15333#discussion_r884177773

cc @ppedrot I would like to push this for 8.16.

2022-05-28 21:34 UTC, liyishuai requested changes

2022-05-28 21:34 UTC, liyishuai commented on theories/extraction/ExtrOcamlNatInt.v
>  Extract Constant minus => "fun n m -> Stdlib.Int.max 0 (n-m)".
```suggestion
Extract Constant pred => "fun n -> Stdlib.max 0 (n-1)".
Extract Constant minus => "fun n m -> Stdlib.max 0 (n-m)".
```

2022-05-29 09:49 UTC, ana-borges commented
What's up with the test-suite timing out? Unrelated issues?

2022-05-29 09:54 UTC, Alizter commented
Async is unrelated and gappa is broken/waiting for an overlay.

2022-05-29 10:54 UTC, ana-borges approved these changes
LGTM

2022-05-29 11:18 UTC, ana-borges commented
@coqbot merge now

2022-05-29 11:18 UTC, merged