Additional patterns for ltac2: "as", records, ints, strings
coq/coq pull request #16179
Opened 2022-06-13 14:32 UTC by SkySkimmer

2022-06-13 17:41 UTC, jfehrle reviewed
Suggestions

2022-06-13 17:41 UTC, jfehrle commented on doc/changelog/05-tactic-language/16179-tac2pat.rst
> +  patterns for Ltac2 matches: ``as``, records and literal ints and strings
```suggestion
  patterns for Ltac2 matches: ``as``, records and literal integers and strings
```

We haven't been using the abbreviation in the doc.

2022-06-13 17:41 UTC, jfehrle commented on doc/tools/docgram/orderedGrammar
> +
For readability, please move these lines to just before line 2361 ("ltac2_tactic_atom: [")

2022-06-18 21:47 UTC, ppedrot requested changes
This is missing a more comprehensive test suite.

2022-06-20 13:37 UTC, SkySkimmer commented
Added some tests

2022-06-21 07:27 UTC, ppedrot approved these changes

2022-06-21 07:28 UTC, ppedrot commented
@coqbot merge now

2022-06-21 07:28 UTC, merged