[stdlib] stronger div, mod lemmas via module type
coq/coq pull request #16203
Opened 2022-06-17 11:22 UTC by mrhaandi

As an alternative to https://github.com/coq/coq/pull/16189, this is a less intrusive way to introduce stronger `div` and `mod` lemmas. This also is a work in progress / request for comments.

The basic idea is to introduce extra module type specifications in `NZDiv0` and `NDiv0` to cover specifications satisfying
```coq
a / 0 == 0
a mod 0 == 0
```

This draft starts with `Nat.mod_same_full` from `PeanoNat.v`.

Closes https://github.com/coq/coq/issues/16186

  

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

2022-06-17 13:29 UTC, mrhaandi commented
For `PeanoNat` this approach seems to work really well. It provides the strongest `Nat.xyz_full` lemmas and uses only a single `Include NDivProp0.`.

2022-06-17 13:50 UTC, olaure01 commented
Could it be possible to rely on the module system to keep the same name for strong statements as for weak ones? thus avoiding the use of `_full`.
Under a given name, you import `NZDiv` you get the weak statement, you import `NZDiv0` you get the strong one.

2022-06-17 14:07 UTC, mrhaandi commented
> Could it be possible to rely on the module system to keep the same name for strong statements as for weak ones? thus avoiding the use of `_full`. Under a given name, you import `NZDiv` you get the weak statement, you import `NZDiv0` you get the strong one.

I'm not sure what is the best way here and I am open to suggestions. Shadowing the existing `Nat` module by a different one upon an extra import is possible, but I rather prefer not to. This would lead to a lot of confusion.

A good compromise is still to have the weak lemmas marked as deprecated (as in the other PR) and after a transition rename the strong ones to their proper names.
At an early point one can hide weak lemmas from `Search`, so the user is not overwhelmed by duplicates.

2022-06-17 15:47 UTC, olaure01 commented
> I'm not sure what is the best way here and I am open to suggestions. Shadowing the existing Nat module by a different one upon an extra import is possible, but I rather prefer not to. This would lead to a lot of confusion.

Talking about the final target (not considering the deprecation phase yet), I would imagine for example creating a `NExtraProp0` in `Numbers.Natural.Abstract.NProperties` which uses `NDivProp0` instead of `NDivProp`, and then to include `NExtraProp0` instead of `NExtraProp0` in `PeanoNat.Nat`. `NDivProp0` could redefine weak statements from `NDivProp` into strong ones as it is the case currently for example with `NDiv.mod_same : forall a, a~=0 -> a mod a == 0.` overloading `NZDiv.mod_same : forall a, 0<a -> a mod a == 0.`.

2022-06-17 15:57 UTC, mrhaandi commented
> Talking about the final target (not considering the deprecation phase yet)

Oh yes, replacing weak lemmas in `PeanoNat.Nat` by strong ones using the module system is easy; almost everything is already in place. So the final target is not a problem. Next week I will look deeper into the `Z` counterpart.

2022-06-21 08:53 UTC, mrhaandi commented
I now added stronger `_full` lemmas via inclusion of `ZDivFloor0.v` to the `Z` module. This is cleaner than https://github.com/coq/coq/pull/16189.

@olaure01 What is the status of `ZArith/Zdiv.v`? It contains all kinds of (sometimes incoherently named) lemmas, sometimes just restating facts from `Z`. Some of the lemmas could have (without this PR) already been deprecated in favor of `Z` lemmas.

I see two options.
1) Deprecate as many `ZArith/Zdiv.v` lemmas as possible now in favor of `_full` lemmas.
2) Do not touch `ZArith/Zdiv.v`. Only deprecate weak lemmas in `Z`. After this first deprecation phase, rename strong lemmas (removing `_full` suffix). Then deprecate as many `ZArith/Zdiv.v` using strong lemmas (without the `_full` suffix).

Option 2 would be easier on the users. Option 1 would entail e.g. the `Zdiv.Zdiv_0_l` => `Z.div_0_l_full` => `Z.div_0_l` dance.

2022-06-21 10:06 UTC, olaure01 commented
> What is the status of `ZArith/Zdiv.v`?

I am not sure. Similar files like `ZArith/Zmin.v` are explicitly mentioned as deprecated/obsolete (thus probably subject to the analogue of #14736).

> 1. Deprecate as many `ZArith/Zdiv.v` lemmas as possible now in favor of `_full` lemmas.

Since deprecation phases are long (in particular when we want to reuse old names), I am in general in favor of starting them as soon as possible.

> 2. Do not touch `ZArith/Zdiv.v`. Only deprecate weak lemmas in `Z`. After this first deprecation phase, rename strong lemmas (removing `_full` suffix). Then deprecate as many `ZArith/Zdiv.v` using strong lemmas (without the `_full` suffix).

I agree that in the present situation going back and forth through `_full` names would be painful, and option 2 looks better.

Would it be reasonable to consider settling now the architecture of the final target of the process (with strong statements available under `_full`-free names) and declaring temporary modules `PeanoNatFull.Nat` and `BinIntFull.Z` to make this architecture accessible immediately? This could allow users interested in adapting now their development towards the target situation to:
 1. import now these new modules to directly use final names for strong statements;
 2. in the next step, reach the final situation by just replacing `PeanoNatFull` with `PeanoNat` and `BinIntFull` with `BinInt`.

2022-06-21 12:17 UTC, mrhaandi commented
> `PeanoNatFull.Nat` and `BinIntFull.Z`

I'm not sure whether I like the idea. It creates a third competing module, which will surely take over a year to again deprecate.
A newcomer will have the (sometimes uninformed) choice between
1) `ZDiv` (currently often used, mostly deprecated)
2) `BinInt.Z` (partially deprecated)
3) `BinIntFull.Z` (handy, but will be deprecated shortly)

2022-06-21 15:07 UTC, mrhaandi commented
> to be used only by project maintainers willing to prepare for future

I am such a developer of a (undecidability) library with over 100K LOC. `PeanoNatFull.Nat` would shadow `PeanoNat.Nat`, which makes imports order sensitive (also via some transitive exports). So I would not use `PeanoNatFull.Nat` for reasons of error locality.

2022-06-22 09:54 UTC, mrhaandi commented
While trying to sideways refactor `NDivProp` I noticed that the whole module tower in `PeanoNat` is then starting to fall over. Mainly because further up module types such as `NLcmProp` contain weak lemmas e.g. `Lemma mod_divide : forall a b, b~=0 -> (a mod b == 0 <-> (b|a)).` with a dependence on the weak division lemmas. The main consequence is that `NLcmProp` and others will need a `NLcmProp0` counterpart. Otherwise, we cannot use `Notation` to deprecate weak `nat` lemmas.

Also, we cannot deprecate the module types such as `NDivProp` or `NLcmProp` but only their use in `PeanoNat`.
Otherwise, the abstract module types will become incompatible with other division by zero conventions.

I will shift my focus solely on `nat` and `N` now. `Z` has an even larger module type tower and will require further investigation.

2022-06-28 08:55 UTC, mrhaandi commented
@olaure01 I finally figured out (for `Nat`/`N`) a module structure which has almost no code duplication and allows for deprecation via `Notation`. The overall approach is now solid for `Nat`/`N` and quire useful. I consider this close to done and will not touch `Z` in this PR. If ci agrees, I will switch the status to "Ready for review".

2022-06-28 15:30 UTC, Alizter commented
@mrhaandi I would suspect that some boolean equality is not found and the boolean equality scheme tries to go and derive it automatically. Are you able to observe slow down in that file when you run it manually in an editor?

cc @herbelin

2022-06-28 16:28 UTC, mrhaandi commented
> Are you able to observe slow down in that file when you run it manually in an editor?

In the editor I see no slowdown in `success/SchemeEquality.v` and the overall `test-suite` compilation time is basically the same.
To be sure, I use a clean checkout (to have no caches present). Although I doubt it, but maybe my OCaml `4.12.0` behaves differently than `4.09.0` from the ci?

2022-06-28 17:35 UTC, mrhaandi commented
@Alizter What did you change in the ci that `success/SchemeEquality.v` passed? Or was it just a rerun?

2022-06-29 05:49 UTC, Alizter commented
@mrhaandi I rerun it yesterday. Sometimes the CI takes its time. It was unrelated to SchemeEquality.v.

2022-07-09 14:20 UTC, Alizter approved these changes

2022-07-09 14:21 UTC, Alizter commented
@olaure01 Did you want to have a look?

2022-07-09 14:29 UTC, olaure01 commented
@Alizter I planned to have look next week or the week after, but if it is OK with you, please go.

2022-07-09 14:30 UTC, Alizter commented
@olaure01 In that case I will wait for your review. No rush.

2022-07-27 15:26 UTC, olaure01 requested changes
I think the work on induction in `NZOrder` and on Bezout in `NGcd` should be documented in changelog.
You could also mention more about the future in changelog: planned deprecation phases, and the trick to directly go close to the end following: `Module Nat := Nat.Div0.`

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NGcd.v
> +#[deprecated(since="8.17",note="Use Nat.divide_antisym instead.")]
Could be `N.xxx` when using `BinNat`.

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NGcd.v
> +Definition gcd_mul_diag_l n m := gcd_mul_diag_l n m (le_0_l n).
This induces a type change: would it require a deprecation phase?
At least a mention in changelog I think.

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.mod_divide instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.mod_divide instead.")]
```

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.divide_div_mul_exact instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.divide_div_mul_exact instead.")]
```

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.gcd_div_factor instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.gcd_div_factor instead.")]
```

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.gcd_mod instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.gcd_mod instead.")]
```

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.gcd_mod instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.gcd_mod instead.")]
```

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.lcm_equiv2 instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.lcm_equiv2 instead.")]
```

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.divide_div instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.divide_div instead.")]
```

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.lcm_unique instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.lcm_unique instead.")]
```

2022-07-27 15:26 UTC, olaure01 commented on theories/Numbers/Natural/Abstract/NLcm0.v
> +#[deprecated(since="8.17",note="Use Nat.Lcm0.lcm_unique_alt instead.")]
```suggestion
#[deprecated(since="8.17",note="Use Lcm0.lcm_unique_alt instead.")]
```

2022-07-27 15:29 UTC, olaure01 commented on theories/Numbers/NatInt/NZOrder.v
> +intros x1 x2 H1 x3 x4 H2; unfold Rlt. rewrite H1; now rewrite H2.
```suggestion
intros x1 x2 H1 x3 x4 H2; unfold Rlt. now rewrite H1, H2.
```

2022-07-27 15:29 UTC, olaure01 commented on theories/Numbers/NatInt/NZOrder.v
> +intros x1 x2 H1 x3 x4 H2; unfold Rgt; rewrite H1; now rewrite H2.
```suggestion
intros x1 x2 H1 x3 x4 H2; unfold Rgt; now rewrite H1, H2.
```

2022-07-28 12:49 UTC, mrhaandi commented on theories/Numbers/Natural/Abstract/NGcd.v
> +#[deprecated(since="8.17",note="Use Nat.divide_antisym instead.")]
Yes.

2022-07-28 12:50 UTC, mrhaandi commented on theories/Numbers/Natural/Abstract/NGcd.v
> +Definition gcd_mul_diag_l n m := gcd_mul_diag_l n m (le_0_l n).
I added this fact to the changelog.

2022-07-28 12:50 UTC, mrhaandi commented on theories/Numbers/NatInt/NZOrder.v
> +intros x1 x2 H1 x3 x4 H2; unfold Rlt. rewrite H1; now rewrite H2.
Done.

2022-07-28 12:51 UTC, mrhaandi commented on theories/Numbers/NatInt/NZOrder.v
> +intros x1 x2 H1 x3 x4 H2; unfold Rgt; rewrite H1; now rewrite H2.
Done.

2022-07-28 12:53 UTC, mrhaandi commented
> I think the work on induction in `NZOrder` and on Bezout in `NGcd` should be documented in changelog.

Yes, I forgot to add a note on `measure_induction` which is a uniform way to have `Wf_nat.induction_ltof1` and is compatible with the `induction` tactic. I added the info to the changelog, thank you.

> You could also mention more about the future in changelog: planned deprecation phases, and the trick to directly go close to the end following: `Module Nat := Nat.Div0.`

Yes.

2022-07-29 08:34 UTC, olaure01 commented
@coq/doc-maintainers This PR both adds, removes, changes and deprecates things. Is the changelog OK, or would it be better to split it into separated **Added** / **Changed** / **Deprecated** / ... entries?

2022-07-29 16:58 UTC, Alizter commented on doc/changelog/11-standard-library/16203-concise_mod_type.rst
> +  :g:`divide_gcd_iff`, :g:`gcd_mul_diag_l` is removed.
```suggestion
  :g:`divide_gcd_iff`, :g:`gcd_mul_diag_l` is removed
```

2022-07-29 16:58 UTC, Alizter commented
I think splitting up the changelog entry would be a good idea.

2022-08-05 06:30 UTC, mrhaandi commented on doc/changelog/11-standard-library/16203-concise_mod_type.rst
> +  :g:`divide_gcd_iff`, :g:`gcd_mul_diag_l` is removed.
Yes.

2022-08-05 06:31 UTC, mrhaandi commented
> I think splitting up the changelog entry would be a good idea.

I now split the changelog entries into three orthogonal bullet points. Is this the standard approach, or should I create distinct changelog files?

2022-08-05 06:43 UTC, proux01 commented
That's fine, no need for distinct files.

2022-08-06 07:50 UTC, olaure01 approved these changes

2022-08-06 13:58 UTC, Alizter commented
I will merge this soon. @proux01 are you still having a look?

2022-08-06 16:56 UTC, mrhaandi commented
> I will merge this soon.

Squashed and rebased to be on the safe side.

2022-08-07 08:05 UTC, proux01 commented
> I will merge this soon. @proux01 are you still having a look?

@Alizter nope, feel free to merge

2022-08-07 09:46 UTC, Alizter commented
@coqbot merge now

2022-08-07 09:46 UTC, merged

2023-08-31 20:24 UTC, JasonGross commented
@mrhaandi Has any investigation been done into removing the useless hypotheses from the Z lemmas?

2023-09-01 07:30 UTC, mrhaandi commented
> Has any investigation been done into removing the useless hypotheses from the Z lemmas?

Unfortunately, the situation with `Z` is more complicated than with `nat`. Also, the current solution for `nat` has drawbacks regarding usability, in order to be backwards compatible. Since for my work `nat` is most important, I have little motivation to put comparable (or even more) effort into `Z`.

2023-09-24 19:51 UTC, JasonGross commented
@mrhaandi would you be willing to describe what the drawbacks and considerations are?  I've been considering doing this work myself, if I ever find the time for it, and would be interested in not retreading known dead-ends and having a better sense up front what the rough design trade-offs are.