[ustate] api to declare binders and purge them
coq/coq pull request #16280
Opened 2022-07-04 13:50 UTC by gares

This are the APIs which I'm currently implementing with Obj.magic to make https://github.com/LPCIC/coq-elpi/pull/315 work

2022-07-18 08:25 UTC, SkySkimmer requested changes
Implementation looks wrong

2022-07-18 08:25 UTC, SkySkimmer commented on engine/uState.ml
> +  restrict { uctx with names = (names,names_rev) } vars
Why not
```suggestion
  let vars = Level.Set.union vars uctx.seff_univs in
  let uctx' = restrict_universe_context ~lbound:uctx.universes_lbound uctx.local vars in
  { uctx with local = uctx' }
```
?
ie same as `restrict` but without adding named univs to `vars`

2022-07-18 12:20 UTC, gares commented
Thanks, your code works for me

2022-07-18 12:39 UTC, SkySkimmer approved these changes

2022-07-18 12:40 UTC, SkySkimmer commented
squash?

2022-07-18 12:49 UTC, gares commented
done

2022-07-19 11:57 UTC, SkySkimmer commented
@coqbot merge now

2022-07-19 11:57 UTC, merged