According to suggestion in issue #16479 three lemmata have been added to FinFun and ListDec
coq/coq pull request #16489
Opened 2022-09-14 15:58 UTC by bodoai

According to suggestion in issue #16479 the following lemmata have been added:

* in coq/theories/Logic/FinFun.v:
  + Lemma Listing_decidable_eq {A:Type} (l:list A): Listing l -> decidable_eq A.
  + Lemma Finite_dec {A:Type}: Finite A /\ decidable_eq A <-> Finite' A.
* in coq/theories/Lists/ListDec.v:
  + Lemma NoDup_list_decidable A (l:list A) : NoDup l -> forall x y:A, In x l -> In y l -> decidable (x=y).

The first two lemmata clarify the role of decidable A in the relationship between Finite and Finite' and  provide an easy way to derive decidable A from Listing l and Finite' A

The third lemma provides the actual core of the proof for Listing_decidable_eq.

- [ ] Added / updated **test-suite**.

2022-09-18 16:12 UTC, olaure01 requested changes

2022-09-18 16:12 UTC, olaure01 commented on theories/Lists/ListDec.v
> +Section Dec_in_Prop_NoDup.
This section does not seem useful.
The statement could naturally go in the `Dec_in_Prop` section.

2022-09-18 16:12 UTC, olaure01 commented on theories/Lists/ListDec.v
> +  induction l as [|h t HInd].
Induction over the `NoDup l` assumption could give a slightly simpler proof.

2022-09-18 16:12 UTC, olaure01 commented on theories/Logic/FinFun.v
> +  eapply NoDup_list_decidable; try (apply Hnodup); auto.
```suggestion
  now apply (NoDup_list_decidable Hnodup).
```

2022-09-18 16:12 UTC, olaure01 commented on theories/Logic/FinFun.v
> +    split; try (exists l); auto.
```suggestion
    split; [ exists l | ]; assumption.
```
we know `exists l` is useful only in the first branch.

2022-09-18 16:12 UTC, olaure01 commented on theories/Logic/FinFun.v
> +    intros ((l, Hfull) & Hdec).
```suggestion
  - intros ((l, Hfull) & Hdec).
```
I would rather explicitly prove `Finite_alt` afterwards by relying on this new stronger `Finite_dec`.
One could even think about deprecating `Finite_alt` which only requires to modify the proof of `Endo_Injective_Surjective` to use `Finite_dec` instead of `Finaite_alt`.

2022-09-20 12:05 UTC, bodoai commented on theories/Lists/ListDec.v
> +  induction l as [|h t HInd].
The proof can be reduced substantially:
Proof.
  intros ND.
  induction ND; intros; apply dec.
Qed.

2022-09-20 12:30 UTC, bodoai commented on theories/Lists/ListDec.v
> +  induction l as [|h t HInd].
Indeed, the this gives a simpler proof.

2022-09-21 09:12 UTC, bodoai commented on theories/Logic/FinFun.v
> +    intros ((l, Hfull) & Hdec).
What is the state-of-the-art way to mark `Finite_alt` as `deprecated`?

1. Simply adding a comment like `(* Deprecated since 8.17.0. Use Finite_dec instead *)`?
2. Introducing a deprecated compatibility alias using Notation?

In case (2)  there seem to exist at least two possibilities:

(2a) Rename `Finite_alt` to something like `Finite_alt_deprecated` and add a `deprecated` attribute plus a Notation alias, e.g.:
```
- Lemma Finite_alt ...
+ Lemma Finite_alt_deprecated ...
...
Qed.

+ (* #[deprecated(since="18.7.0", note="Use Finite_dec instead.")] *)
+ Notation Finite_alt := Finite_alt_deprecated.

```
(2b) Remove `Finite_alt` and hide the lemma inside a proof object which is aliased by the Notation, e.g.:

```
- Lemma Finite_alt ...
- ...
- Qed.
+ (* #[deprecated(since="18.7.0", note="Use Finite_dec instead.")] *)
+ Notation Finite_alt := (fun (A:Type) (d:decidable_eq A) =>
+  (fun (Q P R : Prop) (H : P /\ Q <-> R) (H0 : Q) =>...)
+  (decidable_eq A) (Finite A) (Finite' A) Finite_dec d).
```

2022-09-21 09:19 UTC, olaure01 commented on theories/Logic/FinFun.v
> +    intros ((l, Hfull) & Hdec).
> (2a) Rename Finite_alt to something like Finite_alt_deprecated and add a deprecated attribute plus a Notation alias, e.g.:
> 
>```
> - Lemma Finite_alt ...
> + Lemma Finite_alt_deprecated ...
> ...
> Qed.
> 
> + (* #[deprecated(since="18.7.0", note="Use Finite_dec instead.")] *)
> + Notation Finite_alt := Finite_alt_deprecated.
> ```
This is what I would recommend.

2022-09-23 11:58 UTC, bodoai commented on theories/Lists/ListDec.v
> +  induction l as [|h t HInd].
It seems that this proof has to rely on the hypothesis `dec:decidable_eq A` (stated at the beginning of `Section Dec_in_Prop` and defined as: `forall x y:A, decidable (x=y)`). The hypothesis `dec` directly implies the desired result (`forall x y:A, In x l -> In y l -> decidable (x=y)`). However, the objective of the lemma is to prove this weakened variant of `dec` relying only on the hypothesis `NoDup l`.

Should this maybe be clarified by a corresponding comment?

2022-09-25 12:13 UTC, olaure01 requested changes

2022-09-25 12:13 UTC, olaure01 commented on theories/Lists/ListDec.v
> +  induction ND; intros x' y' Hinx Hiny.
```suggestion
  induction ND as [|h t Hin Hnd IHND]; intros x' y' Hinx Hiny.
```
This is for compatibility with name mangling.
By the way, the two modified files are not 100% compatible with name mangling. We can take the opportunity to make the corresponding adjustments here, or I will do an other PR afterwards.

2022-09-25 12:13 UTC, olaure01 commented on theories/Lists/ListDec.v
> +  - simpl in Hinx; destruct Hinx.
```suggestion
  - destruct Hinx.
```

2022-09-25 12:13 UTC, olaure01 commented on theories/Lists/ListDec.v
> +    + right; intros Hcontra; subst; congruence.
```suggestion
    + right; intros ->; contradiction.
    + right; intros ->; contradiction.
```

2022-09-25 12:16 UTC, olaure01 commented on theories/Lists/ListDec.v
> +  induction l as [|h t HInd].
The current proof does the job. You could also use the more compact suggestion of @mrhaandi with appropriate context constraints:
```coq
Proof using A. clear dec; intros Hl; induction Hl; firstorder congruence. Qed.
```

2022-09-26 13:16 UTC, bodoai commented on theories/Lists/ListDec.v
> +  induction ND; intros x' y' Hinx Hiny.
I took the opportunity and changed the proofs to explicitly name all hypotheses generated by `induction` and `destruct` in `ListDec.v`. If this is what you meant by "corresponding adjustments", I could go ahead and adjust `Finfun.v` accordingly.

2022-09-26 13:30 UTC, olaure01 commented on theories/Lists/ListDec.v
> +  induction ND; intros x' y' Hinx Hiny.
That's it, but in fact you need it only when those names are used later in the proof.
You can find what is missing for example by adding `Set Mangle Names.` in the beginning of the file or by compiling with `coqc -mangle-names "_" file.v`.

2022-09-27 08:23 UTC, bodoai commented on theories/Lists/ListDec.v
> +  induction ND; intros x' y' Hinx Hiny.
Thanks for the info. I will proceed accordingly.

2022-09-27 09:36 UTC, bodoai commented on theories/Lists/ListDec.v
> +  induction ND; intros x' y' Hinx Hiny.
Applied the "minimum" adjustments, i.e. provided only the missing identifiers in the cases that were flagged by `Set Mangle Names`. (Consequently, I reverted all the `induction` and `destruct` instances in `ListDec.v` that were not flagged by `Set Mangle Names` to the previous state.)

2022-09-27 09:39 UTC, bodoai commented on theories/Lists/ListDec.v
> +  induction ND; intros x' y' Hinx Hiny.
Just to make sure that I have not forgotten anything: The name mangling cleanup should not be visible to the users of stdlib. Therefore, this kind of change does not have to be documented in the changelog?

2022-09-27 09:42 UTC, olaure01 commented on theories/Lists/ListDec.v
> +  induction ND; intros x' y' Hinx Hiny.
> Therefore, this kind of change does not have to be documented in the changelog?

Indeed.

2022-09-27 13:22 UTC, olaure01 approved these changes

2022-09-27 13:23 UTC, olaure01 commented
@bodoai you can squash your commits and I will merge by Thursday if there is no more comments.

2022-09-29 09:18 UTC, olaure01 commented
@coqbot: merge now

2022-09-29 09:18 UTC, merged