[stdlib] add `NoDup (l++l') <-> NoDup (l'++l)`
coq/coq pull request #16588
Opened 2022-09-30 20:28 UTC by haansn08

Re-opening of https://github.com/coq/coq/pull/16563 because GitHub does not allow me to rename the source branch for a PR.

This PR adds follwing lemmata for lists:
* `Lemma in_app_comm: forall l l' (a:A), In a (l++l') -> In a (l'++l).`
* `Lemma NoDup_cons_remove l a : NoDup (a::l) -> NoDup l.`
* `Lemma NoDup_app_remove1 l l': NoDup (l++l') -> NoDup l'.`
* `Lemma NoDup_app_remove2 l l': NoDup (l++l') -> NoDup l.`
* `Lemma NoDup_app_comm l l': NoDup (l++l') -> NoDup (l'++l).`

2022-10-01 18:13 UTC, Alizter commented on theories/Lists/List.v
> +  Qed.
```suggestion
  Lemma in_app_comm l l' (a:A) : In a (l++l') -> In a (l'++l).
  Proof.
    intro H. apply in_or_app, or_comm, in_app_or. exact H.
  Qed.
```

2022-10-01 18:13 UTC, Alizter commented on theories/Lists/List.v
> +  Lemma NoDup_app_remove1 l l': NoDup (l++l') -> NoDup l'.
```suggestion
  Lemma NoDup_app_remove1 l l' : NoDup (l++l') -> NoDup l'.
```

2022-10-01 18:13 UTC, Alizter commented on theories/Lists/List.v
> +  Lemma NoDup_app_remove2 l l': NoDup (l++l') -> NoDup l.
```suggestion
  Lemma NoDup_app_remove2 l l' : NoDup (l++l') -> NoDup l.
```

2022-10-01 18:13 UTC, Alizter commented on theories/Sorting/Permutation.v
> +Lemma NoDup_app_comm l l': NoDup (l++l') -> NoDup (l'++l).
```suggestion
Lemma NoDup_app_comm l l' : NoDup (l++l') -> NoDup (l'++l).
```

2022-10-02 09:37 UTC, olaure01 commented
> @olaure01 Thank you, I didn`t know about the NoDup theorems in Permutation.v. This makes this proof very easy and maybe not a good candidate for inclusion in the stdlib. Maybe there is still some merit to include the other lemmata?

Similarly, `in_app_comm` is also a direct consequence of results about permutations:
```coq
Require Import List Permutation.

Lemma in_app_comm A l l' (a:A) : In a (l++l') -> In a (l'++l).
Proof. apply Permutation_in, Permutation_app_swap. Qed.
```
Since there are many other possible direct consequences of applying a permutation to `In` or `NoDup`, it is not clear to me if we should add them to stdlib.
Lemma `Lemma NoDup_cons_remove l a : NoDup (a::l) -> NoDup l.` is an immediate application of `NoDup_remove_1`, not clear to me either it is important to have it as a dedicated statement.
The last two `NoDup_app_remove1` and `NoDup_app_remove2` look more interesting to me.

2022-10-02 09:41 UTC, olaure01 requested changes

2022-10-02 09:41 UTC, olaure01 commented on theories/Lists/List.v
> +  Lemma NoDup_app_remove1 l l' : NoDup (l++l') -> NoDup l'.
```suggestion
  Lemma NoDup_app_remove_l l l' : NoDup (l++l') -> NoDup l'.
```

2022-10-02 09:41 UTC, olaure01 commented on theories/Lists/List.v
> +  + exact H.
```suggestion
  - exact H.
```

2022-10-02 09:41 UTC, olaure01 commented on theories/Lists/List.v
> +  + eapply IHl, NoDup_cons_remove. exact H.
```suggestion
  - apply IHl, (NoDup_remove_1 nil _ _ H).
```

2022-10-02 09:41 UTC, olaure01 commented on theories/Lists/List.v
> +  Lemma NoDup_app_remove2 l l' : NoDup (l++l') -> NoDup l.
```suggestion
  Lemma NoDup_app_remove_r l l' : NoDup (l++l') -> NoDup l.
```

2022-10-02 09:41 UTC, olaure01 commented on theories/Lists/List.v
> +  - apply IHl'. eapply NoDup_remove_1. exact H.
```suggestion
  - apply IHl', (NoDup_remove_1 _ _ _ H).
```

2022-10-02 09:41 UTC, olaure01 commented on theories/Lists/List.v
> +  induction l; intro H.
```suggestion
  induction l as [|a l IHl]; intro H.
```
for name mangling

2022-10-02 09:41 UTC, olaure01 commented on theories/Lists/List.v
> +  induction l'; intro H.
```suggestion
  induction l' as [|a l' IHl']; intro H.
```
for name mangling

2022-10-03 07:45 UTC, haansn08 commented
@olaure01 I have now removed `in_app_comm` and `NoDup_app_comm`.

2022-10-03 11:53 UTC, olaure01 commented on theories/Lists/List.v
> +  apply (NoDup_remove_1 []).
```suggestion
  now intro H; inversion H.
```
avoids relying on multiple intermediary results.

2022-10-04 12:22 UTC, haansn08 commented on theories/Lists/List.v
> +  apply (NoDup_remove_1 []).
Since `inversion` seems to cover this lemma, I have now removed it.

2022-10-04 12:26 UTC, olaure01 commented
@haansn08 the content looks good to me, could you squash your commits and add a changelog?

2022-10-04 13:02 UTC, haansn08 commented
@olaure01 Done. Thank you for your help :)

2022-10-04 13:43 UTC, olaure01 approved these changes

2022-10-04 13:46 UTC, olaure01 commented
If we get [full green CI](https://github.com/coq/coq/pull/16600#issuecomment-1265773392) and there is no more comments, I will merge by Thursday.

2022-10-06 13:53 UTC, Zimmi48 commented
Re-running since the last CI run had a lot of errors for unrelated reasons:

@coqbot run CI now

2022-10-07 05:54 UTC, olaure01 commented
remaining CI failures look unrelated
@coqbot merge now

2022-10-07 05:54 UTC, merged