Move the Prod case from native atoms to values.
coq/coq pull request #16697
Opened 2022-10-19 13:36 UTC by ppedrot

We had to cheat a bit to abuse the value representation of blocks of tag 0 in the native compiler. There used to be two possible kinds of 0-tagged blocks:

- Either they had size >= 2 in which case they were accumulators coded as closures, where the tag 0 was the well-known hack to make them behave as an ADT constructor at runtime.
- Or they had size 1, in which case they were persistent arrays. The fact this works was abusing the internal representation of persistent arrays, which are a reference on some ADT with 2 non-constant constructors.

In order to extend this, we simply wrap Prod values into a dummy 0-tagged block and encode them as a 3-uple with a tag that is distinct from the ones defined by the PArray implementation.

2022-10-19 13:37 UTC, ppedrot commented
cc @silene who was the one pushing for this change

2022-10-19 13:39 UTC, ppedrot commented
@coqbot bench native

2022-10-20 07:03 UTC, silene requested changes

2022-10-20 09:00 UTC, ppedrot commented
@silene crazy hack implemented.

2022-10-20 09:36 UTC, SkySkimmer commented
>Is there any reason you're not benching fiat-crypto-with-bedrock2?

I don't think that's a real package.

2022-10-20 10:05 UTC, JasonGross commented
> > Is there any reason you're not benching fiat-crypto-with-bedrock2?
> 
> I don't think that's a real package. There's only -with-bedrock

Sorry, I meant -with-bedrock

2022-10-20 12:08 UTC, silene commented
And the same thing needs to be done for `nf_type`. (I guess this is in fact the one that corresponds to the removed `Aprod` case. For `nf_type_sort`, it should be more straightforward.)

2022-10-20 12:10 UTC, ppedrot commented
@silene fixed

2022-10-20 16:35 UTC, silene commented
@coqbot run full ci

2022-10-20 16:36 UTC, silene approved these changes

2022-10-21 08:27 UTC, ppedrot commented
The CI failures are unrelated, the CI is quite wobbly these days. Anyways @silene you should probably assign.

2022-10-21 09:13 UTC, silene commented
@coqbot merge now

2022-10-21 09:14 UTC, merged