Generalize Add Zify to accept terms not just refs
coq/coq pull request #16868
Opened 2022-11-21 14:01 UTC by SkySkimmer

Help with https://github.com/coq/coq/issues/16404

This is like the "Specialize Zify" suggested there, but there is no need for a new command. So instead of `Specialize Zify FooOp FooInst v` we can do `Add Zify FooOp (FooInst v)`

2022-11-21 16:21 UTC, SkySkimmer commented
@coqbot run full co

2022-11-21 16:21 UTC, SkySkimmer commented
@coqbot run full ci

2022-12-06 14:57 UTC, SkySkimmer commented
@coqbot run full ci

2022-12-06 19:16 UTC, jfehrle commented
Changelog would be nice.

2022-12-06 19:48 UTC, SkySkimmer commented
that's why there's the label

2022-12-13 12:19 UTC, SkySkimmer commented
@coqbot run full ci

2022-12-17 20:00 UTC, jfehrle reviewed
wording suggestions

2022-12-17 20:00 UTC, jfehrle commented on doc/changelog/04-tactics/16868-zify-term.rst
> +  an intermediate definition for ``inj_thing`` (`#16868
```suggestion
  This lets you avoid creating intermediate definitions for terms
  that include section variables (such as ``x`` in ``(inj_thing x)``).
  Now you can use ``Add Zify InjTyp (inj_thing x)`` instead (`#16868
```

WDYT?  A bit more readable if the benefit appears at the beginning of the sentence so the reader immediately knows why they would care.

2022-12-17 20:14 UTC, SkySkimmer commented on doc/tools/docgram/orderedGrammar
> -| "Add" "Zify" add_zify qualid      (* Micromega plugin *)
This is autogenerated, I don't know why the order changed

2022-12-17 20:48 UTC, jfehrle commented on doc/tools/docgram/orderedGrammar
> -| "Add" "Zify" add_zify qualid      (* Micromega plugin *)
doc_grammar can't always match up the old and new productions, in which case it ends up in a semirandom spot.  Thus it's fine and at times necessary to reorder items in `orderedGrammar`.

2023-01-03 09:35 UTC, SkySkimmer commented
Integrated @jfehrle comments

2023-01-03 09:35 UTC, SkySkimmer commented
@coqbot run full ci

2023-01-31 11:05 UTC, Zimmi48 commented
@coq/micromega-maintainers It looks like this PR is just waiting to get reviewed.

2023-02-03 13:28 UTC, ppedrot requested changes
I think this is a regression. Allowing to store arbitrary terms in a map in a trick just waiting to blow at the face of users. As a matter of fact I have been pushing right in the other direction for features like hints. Like it or not, there is no universally agree upon equality function on terms, let alone a comparison function. Forcing the user to write an intermediate definition is the only sane semantics I can think of.

2023-02-03 13:56 UTC, SkySkimmer commented
The thing that is put in the map is not the lemma `Inj_bv_Z w` which could be OK to have an intermediate definition for, it is the `bitvector w`. Forcing intermediate definitions for this is rather painful and also unstable as if they get unfolded lia breaks.

2023-02-03 13:59 UTC, fajb commented
> I think this is a regression. 
Indeed, I remember `zify` used to take terms.

In this specific case, I guess the user does not wish to make an intermediate definition for say, int16, add16 etc.

What if the registered terms is checked to be an application of refs?
In that case, would the operations on terms be sufficiently well-behaved?
 =  : app_of_refs -> term -> bool 
<   : app_of_refs ->  term -> bool etc
That looks relatively lightweight to implement: a sanity check at registration time.

2023-02-03 14:11 UTC, ppedrot commented
Recursive application of references is better, but there is still the (maybe not very relevant right now but that may be in the future) annoying issue of universe polymorphic definitions.

2023-02-03 14:34 UTC, fajb commented
Could polymorphic definitions be ruled out ?
Are not they out-of-scope, anyway?  Given  `zify`  is mostly first-order logic.

2023-02-03 14:40 UTC, ppedrot commented
> Could polymorphic definitions be ruled out?

Yes, but this is basically the confession that we're stuck forever with the current stdlib and the wealth of issues with monomorphic constants.

2023-02-03 14:44 UTC, ppedrot commented
From what I gather from the code, we need some kind of dedicated pattern type + an efficient matching function. Storing terms in a map that are furthermore generated by calls to unsafe_to_constr is a literal recipe for an impending disaster.

2023-07-05 08:23 UTC, gares commented
Not ready for 8.18, postponing to 8.19

2023-11-21 15:01 UTC, closed without merging