Register orders on R as reflexive and transitive so that reflexivity and transitivity tactics apply
coq/coq pull request #16873
Opened 2022-11-22 08:59 UTC by herbelin

Useful for teaching using the Real library.

- [x] Added **changelog**.

2022-11-22 12:20 UTC, Zimmi48 commented
@herbelin I don't know what's up with your setup, but you have linter errors in the two PRs you just submitted.

2022-12-01 20:28 UTC, herbelin commented
It is not a universal solution since applying mixed transitivity lemmas such as `Rlt_le_trans` and `Rle_lt_trans` are not covered by `transitivity` (one would e.g. need idioms such as `left-strict transitivity` or `right-strict transitivity`, and it would start to be disputable if it is more too ad hoc than useful). However, it is still quite convenient in my view and it does not harm.

2022-12-05 13:44 UTC, Zimmi48 commented
@herbelin The last CI run is broken for some reason:

```
File "./Rfunctions.v", line 917, characters 0-39:
Error: Rdist already exists.
```

2022-12-05 20:01 UTC, herbelin commented
There was a collision with the commits of #16874. Thanks for noticing. Now fixed.

2022-12-15 21:03 UTC, Zimmi48 commented
Moving to 8.18 because this still hasn't been reviewed and the rc1 is close.

2023-07-05 08:24 UTC, gares commented
postponing to 8.19

2023-07-05 09:36 UTC, herbelin commented
This elementary PR only needs feedback.

@coq/reals-library-maintainers, @coq/stdlib-maintainers, would you have time to have a look?

2023-07-20 07:58 UTC, silene requested changes

2023-07-20 07:58 UTC, silene commented on theories/Reals/RIneq.v
> +Require Export RelationClasses.
In my opinion, it would be better not to export random unrelated libraries.

2023-07-20 07:58 UTC, silene commented on theories/Reals/Raxioms.v
> +Require Export RelationClasses.
Same here.

2023-07-20 08:54 UTC, silene commented on theories/Reals/RIneq.v
> +Require Export RelationClasses.
Neither of them. What I mean is that it should just be `Import`. A library should not `Export` the files of another library. When a user at some point decided that they needed to import the theory of real arithmetic (i.e., `RIneq`), they never agreed to have their namespace polluted by the content of `RelationClasses`.

2023-07-20 09:12 UTC, herbelin commented on theories/Reals/RIneq.v
> +Require Export RelationClasses.
Oh, of course! I should have thought to it. Done.

2023-07-20 09:19 UTC, silene approved these changes

2023-09-27 20:04 UTC, herbelin commented
Subsumed by #18059.

2023-09-27 20:04 UTC, closed without merging