Remove the instantiate tactic.
coq/coq pull request #16910
Opened 2022-11-25 13:00 UTC by ppedrot

It was deprecated and turned into a noop in 8.16.

2022-11-25 13:02 UTC, Alizter approved these changes

2022-11-25 13:02 UTC, Alizter commented
@coqbot run full ci

2022-11-28 23:46 UTC, jfehrle commented on doc/tools/docgram/common.edit_mlg
>  | WITH "instantiate" OPT ( "(" ident ":=" lglob ")" )
These 2 lines should be removed, too.  The effect of these plus the DELETE was to merge 2 productions.  No merge is needed if you delete the no-arg instantiate.

2022-12-08 17:56 UTC, jfehrle requested changes
Please address my earlier comment "These 2 lines should be removed, too." before you submit this, thanks.

2022-12-30 14:57 UTC, Zimmi48 commented
I've pushed a commit fixing the remaining issues with the documentation.

2022-12-30 21:31 UTC, jfehrle approved these changes
LGTM

2023-01-10 09:23 UTC, SkySkimmer commented
@coqbot run full ci

2023-01-10 16:07 UTC, ppedrot commented
CI is failing due to missing overlay https://github.com/DeepSpec/sf/pull/8.

2023-03-15 18:02 UTC, ppedrot commented
After the merge of the sf overlay, this is now ready to merge. This needs an assignee, @SkySkimmer maybe?

2023-03-15 18:27 UTC, jfehrle reviewed
wording suggestion

2023-03-15 18:27 UTC, jfehrle commented on doc/changelog/04-tactics/16910-rm-instantiate.rst
> +  the no-argument `instantiate` tactic, deprecated since 8.16
```suggestion
  the no-argument form of the :tacn:`instantiate` tactic, deprecated since 8.16
```

2023-03-17 12:54 UTC, SkySkimmer commented
@coqbot merge now

2023-03-17 12:54 UTC, merged