Separate interpretation and syntax declaration in tactic notations
coq/coq pull request #16946
Opened 2022-12-05 19:15 UTC by maximedenes

This is a step towards #15409.

2022-12-05 19:48 UTC, herbelin reviewed
Maybe more for @ppedrot in general. In any case, Ltac part looks good.

2022-12-06 12:34 UTC, maximedenes commented
@coqbot run full CI

2022-12-06 12:54 UTC, ppedrot approved these changes

2022-12-07 10:19 UTC, maximedenes commented
@ppedrot do you mind assigning yourself? What should I do about the unrelated failures?

2022-12-07 10:23 UTC, ppedrot commented
The failures are missing overlays, but it should be fixed now, I'll relaunch the CI.

2022-12-07 10:42 UTC, Zimmi48 requested changes
Your update to the `rst` file is wrong. Was it auto-generated? (cc @jfehrle) In any case, you should check what you commit and adapt the surrounding documentation text when there are legitimate documentation changes.

Was it even supposed to be a user-visible change in the first place? If not, then the documentation should not have been updated. `common.edit_mlg` should have been fixed so that `orderedGrammar` is left unchanged.

2022-12-07 10:44 UTC, Zimmi48 commented
Note that I'd be willing to help more, but the lack of PR description / label, etc. would result in spending more time than I'm willing to looking at the code changes to try to decipher your intentions.

2022-12-07 13:47 UTC, maximedenes commented
No user-visible change is intended.

2022-12-07 15:42 UTC, Zimmi48 approved these changes
For a PR with no intended user-visible change like this one, the objective should be to get `orderedGrammar` to stay unchanged even after running ~~`make doc_gram` or~~ `make doc_gram_rsts`.

I've force-pushed to amend your commit.

2022-12-07 15:42 UTC, Zimmi48 commented on doc/tools/docgram/common.edit_mlg
> +| ltac2def_syn
The trick was that you needed to replace the token being spliced here, removing it wasn't sufficient.

2022-12-07 23:19 UTC, maximedenes commented
@Zimmi48 Is the "Error: doc/tools/docgram/orderedGrammar is not current" spurious?

2022-12-08 06:46 UTC, Zimmi48 commented
Not likely. I'll look at it (I thought I had tested it locally though).

2022-12-08 09:24 UTC, maximedenes commented
Note to self: overlays are needed for equations and serapi.

2022-12-08 13:03 UTC, ppedrot commented
@Zimmi48 Is this PR now ready to merge?

2022-12-08 14:01 UTC, Zimmi48 commented
From my side, yes, but I haven't followed if it got a full CI before making the doc fixes.

2022-12-08 14:04 UTC, ppedrot commented
Let's have a CI then, even if there are some devs which will fail due to missing overlays. @coqbot run full ci

2022-12-09 07:50 UTC, ppedrot commented
@coqbot run full ci

2022-12-09 13:38 UTC, maximedenes commented
@ppedrot The failures look spurious or unrelated, don't they?

2022-12-09 13:40 UTC, ppedrot commented
They indeed are. @coqbot merge now

2022-12-09 13:40 UTC, merged

2022-12-09 13:40 UTC, maximedenes commented
Thanks a lot!