Zbitwise: basic relationships between bitwise and arithmetic operations
coq/coq pull request #17022
Opened 2022-12-26 00:08 UTC by andres-erbsen

This PR adds proofs of basic relationships between bitwise and arihtmetic operations on Z. The top-level lemmas are as foolows:

```coq
(~ x) + 1 = - x
(~ x - 1) = - x
- x - 1 = (~ x)
- (~ x) = x + 1
(~ - x) = x - 1
x + y = x - (~ y) - 1
x + y = x .^ y + 2 * (x & y)
x + y = x | y + x & y
x + y = 2*(x | y) - x .^ y
x + y = x - (~ y) - 1
x - y = x .^ y - 2*((~ x) & y)
x - y = x & (~ y) - (~ x) & y
x - y = 2*(x & (~ y)) - x .^ y
x | y - x & y = x ^ y
x | y - y = x & (~ y)
x & (~ y) = x - x & y
(~ x - y) = y - x - 1
(~ x - y) = (~ x) + y
```

The building blocks `addcarries`, `addcarries'` and `addcarryeqn` are also exported as they are simple enough to vendor in case it is later decided that we don't want them. The bitwise-reasoning tactics and notations used to prove the lemmas are not exported; more thought and testing would be required to ensure the interface they provide is as desired.

This PR is on top of https://github.com/coq/coq/pull/17021 because `btauto` depends on `DecidableClass` which without that PR depends on `ZArith`.

- [ ] Added **changelog**.

2022-12-27 10:08 UTC, MSoegtropIMC requested changes
Very useful! I just had a few editorial comments.

2022-12-27 10:08 UTC, MSoegtropIMC commented on theories/ZArith/Zbitwise.v
> +Definition addcarries' (x y : Z) (c : bool) := (x + y + Z.b2z c) .^ (x .^ y).
It is not obvious what these functions are good for and the following lemmas are not that enlighting either. I would say they deserve a motivating comment.

2022-12-27 10:08 UTC, MSoegtropIMC commented on theories/ZArith/Zbitwise.v
> +Lemma lnot_sub' x y : Z.lnot (x - y) = y - x -1.
I would say this follows trivially from `pred_opp` and lia, so I don't quite see the point of introducing extra lemmas (this also applies to the next). Going through the result lists of Search is a vital part of writing proofs, and making these lists longer should come with a value which is larger than the extra time it takes to go through the results.

2022-12-27 10:14 UTC, MSoegtropIMC commented
@andres-erbsen : I recently wrote a reflective tactic to compute bounds of integer expressions (similar to coq-interval, but tailored for integers). One open point I have is proofs for the functions which compute the ranges of land and lor - that is you have ranges for a and b and compute the ranges for `land a b` or `lor a b`. The functions I came up with are rather intricate and so far I didn't have time to make proofs for them. You addition here might help in that, but looking at this I wonder if you have been working one something similar or maybe more which might help here.

I plan to add the Z interval arithmetic lemmas to the standard library (division is also not that trivial).

2022-12-27 10:57 UTC, JasonGross commented
@MSoegtropIMC you might be interested in the bounds and proofs we have in fiat-crypto for `Z.land` and `Z.lor`: https://github.com/mit-plv/fiat-crypto/blob/69d00c4bc376dde1ebcc7bb6f1e2e06f4f458df3/src/Util/ZRange/Operations.v#L171-L199 and proofs at https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/ZRange/LandLorBounds.v with helper lemmas at https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/ZUtil/LandLorBounds.v and https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/ZUtil/LandLorShiftBounds.v

Division, by contrast, is quite simple, both to [state](https://github.com/mit-plv/fiat-crypto/blob/69d00c4bc376dde1ebcc7bb6f1e2e06f4f458df3/src/Util/ZRange/Operations.v#L230) and to [prove](https://github.com/mit-plv/fiat-crypto/blob/69d00c4bc376dde1ebcc7bb6f1e2e06f4f458df3/src/Util/ZRange/OperationsBounds.v#L67).  The idea is that if you take the lower bound, -1, 0, 1, and the upper bound, drop whichever numbers are not between the lower and upper bounds, and then evaluate the operation at all possible combinations of these points, you will find the bounds for the operation.  So, e.g., if we have `lba <= a <= uba` and `lbb <= b <= ubb`, then `a/b` is bounded below by `min(lba/lbb, uba/lbb, lba/ubb, uba/ubb, -1/lbb, -1/ubb, 0/lbb, 0/ubb, 1/lbb, 1/ubb, lba/-1, uba/-1, lba/0, uba/0, lba/1, uba/1, -1/-1, 0/-1, 1/-1, 0/-1, 0/0, 0/1, 1/-1, 1/0, 1/1)` and bounded above by `max` of the same arguments.  (And you can, e.g., drop all the terms involving `-1` if all input bounds are non-negative.). Then to prove this you only need to show that division is monotone in each of its arguments separately as long as the sign doesn't change, and I think `nia` is capable of this when div-mod handling is turned on, possibly with a bit of help.

2022-12-27 11:03 UTC, JasonGross commented
We also have an open issue in fiat-crypto (https://github.com/mit-plv/fiat-crypto/issues/835) about making the bounds on bitwise operations tighter

2022-12-27 15:32 UTC, andres-erbsen commented
The bounds in fiat-crypto are a bit arbitrary and I am not sure whether we should include them. If you have simpler and looser bounds, we could do that. I believe the tight bounds for bitwise operations are quite intricate and rely more than the tricks here. I could dig them up if you'd like, but they'd be a mouthful to prove and I haven't done it.

2022-12-27 15:53 UTC, andres-erbsen commented on theories/ZArith/Zbitwise.v
> +Lemma lnot_sub' x y : Z.lnot (x - y) = y - x -1.
I use Search a lot too, but most of my annoyance is when there is no lemma for rewriting the pattern I search for. That the proofs look simple once known doesn't really do it, and thinking of `pred_opp` when the LHS of this lemma pops up in a goal is a bit of a fetch. (I agree it's obvious when reading this file, though).

2022-12-27 15:54 UTC, andres-erbsen commented on theories/Arith/PeanoNat.v
> +  Decidable_spec := Nat.eqb_eq x y
We could; I'm not sure though. Standard library has a lot of redundant names, and most users seem to import everything.

2022-12-27 16:16 UTC, andres-erbsen commented
`Require Btauto` in `ZArith` seems to have substantial compat fallout from `intuition auto with *`.

2022-12-27 17:46 UTC, MSoegtropIMC commented on theories/ZArith/Zbitwise.v
> +Lemma lnot_sub' x y : Z.lnot (x - y) = y - x -1.
It is in general difficult to balance this. But IMHO `lnot_sub'` goes in the direction of having a commutativity lemma like `(x-y)+z=z+(x-y)`. It is an application of `pred_opp` with `x=x-y`. I guess it might be more obvious if sides would be swapped in `pred_opp` (which I would recommend anyway).

2022-12-27 17:47 UTC, MSoegtropIMC commented
> The bounds in fiat-crypto are a bit arbitrary and I am not sure whether we should include them. If you have simpler and looser bounds, we could do that. I believe the tight bounds for bitwise operations are quite intricate and rely more than the tricks here. I could dig them up if you'd like, but they'd be a mouthful to prove and I haven't done it.

In the standard library I would prefer to include only tight bounds.

2022-12-27 17:52 UTC, andres-erbsen commented
Makes sense, let's not add any bounds right now. Ido  think there is a real argument for non-tight bounds such as `x | y <= bx + by` and `x & y <= min(bx, by)`: they are useful even if `bx` and `by` are not concrete, whereas bounds based on scanning for the first unconstrained bit would be unlikely to be of use even without evaluating the scan.

2022-12-27 18:02 UTC, MSoegtropIMC commented
> Makes sense, let's not add any bounds right now. I do think there is a real argument for non-tight bounds such as `x | y <= bx + by` and `x & y <= min(bx, by)`: they are useful even if `bx` and `by` are not concrete, whereas bounds based on scanning for the first unconstrained bit would be unlikely to be of use even without evaluating the scan.

True - such lemmas can be found e.g. in CompCert and they are useful. One should just make clear that this are not tight bounds. This might not be obvious.

2022-12-27 18:08 UTC, andres-erbsen commented on theories/ZArith/Zbitwise.v
> +Lemma lnot_sub' x y : Z.lnot (x - y) = y - x -1.
Ah, I see. Let's flip `pred_opp` then. Is there already a precedent for naming lemmas where a function `f` can be alternatively expressed in terms of a different function `g` without referencing `f`?

2022-12-27 18:30 UTC, MSoegtropIMC commented on theories/ZArith/Zbitwise.v
> +Lemma lnot_sub' x y : Z.lnot (x - y) = y - x -1.
Naming in the standard library is not very consistent, so it it is hard to be consistent with it. Look e.g. at the odd even lemmas in https://coq.inria.fr/library/Coq.ZArith.Zeven.html#. There is e.g. [Zodd_even_bool](https://coq.inria.fr/library/Coq.ZArith.Zeven.html#Zodd_even_bool) and [Zeven_pred](https://coq.inria.fr/library/Coq.ZArith.Zeven.html#Zeven_pred).

I like explicit lemma names like `lnot_eq_pred_opp` but have no strong opinion about the naming.

2023-02-06 21:13 UTC, andres-erbsen commented on theories/ZArith/Zbitwise.v
> +Lemma sub_lnot_r x y : x - Z.lnot y = x + y + 1.
I agree the clutter is a concern, but leaving out the lemma does not seem like a good solution.

2023-02-06 21:18 UTC, andres-erbsen commented
@MSoegtropIMC please take another look

2023-02-06 22:11 UTC, andres-erbsen commented
@coqbot run full ci

2023-02-10 14:23 UTC, MSoegtropIMC commented on theories/ZArith/Zbitwise.v
> +Lemma sub_lnot_r x y : x - Z.lnot y = x + y + 1.
@andres-erbsen : can you please explain why one would want to have a lemma like `sub_lnot_r` - that is why leaving it out is not a good solution? It is simply the difference of the equations `x=x` and `lnot_eq_pred_opp y`. I mean we can make a lemma which adds "x=x" for a new variable x to any Z equation lemma we have, but I don't see the point of it.

is it so that you need it below and can't use lia yet? If so I would make it a local lemma.

2023-02-12 22:01 UTC, andres-erbsen commented on theories/ZArith/Zbitwise.v
> +Lemma sub_lnot_r x y : x - Z.lnot y = x + y + 1.
From the perspective of use in a rewrite loop, `lnot_eq_pred_opp` is not a substitute as using it does not result in a clean right-hand side. Here is a transcript of my actual Coq session trying to prove this lemma itself by rewriting:

```coq
Lemma sub_lnot_r x y : x - Z.lnot y = x + y + 1.
Proof.
  rewrite lnot_eq_pred_opp.
  Search (- (- _)).
  Search (- (_ - _)).
  Fail rewrite Z.opp_sub_distr.
  Search (- (- _)).
  Fail rewrite Z.opp_involutive.
  Set Printing Parentheses.
  Fail rewrite <-Z.sub_sub_distr.
  rewrite Z.sub_sub_distr.
  Unset Printing Parentheses.
  Fail rewrite Z.opp_opp.
  Search (- (- _)).
  Fail rewrite Z.opp_involutive.
  Set Printing Parentheses.
  Search (_ - (- _)).
  rewrite Z.sub_opp_r.
  Unset Printing Parentheses.
  trivial.
Qed.
```

Yes, the above has a confused detour and can overall be compressed to a one-liner similar to many proofs I submit coq stdlib and my other projects, but it seems valuable to help users avoid this experience.

2023-02-13 08:13 UTC, MSoegtropIMC commented on theories/ZArith/Zbitwise.v
> +Lemma sub_lnot_r x y : x - Z.lnot y = x + y + 1.
Well I still don't quite agree, but this gets in the direction about discussing opinions. So I will approve the PR.

2023-02-13 08:14 UTC, MSoegtropIMC approved these changes
Thanks for this useful addition! Looks good to me!

2023-02-13 12:36 UTC, Alizter approved these changes
Lgtm I have one question about reserving those notations here in the file, but I don't think in the stdlib we make an effort to do this separately so I guess it's fine.

2023-02-14 20:19 UTC, andres-erbsen commented
@Alizter What do you have in mind about reserving notations? IIUC notations don't follow `Require` anymore.

CI fixups (from `Require Btauto`):

- [ ] bedrock2 https://github.com/mit-plv/kami/pull/33 https://github.com/mit-plv/bedrock2/pull/326
- [ ] rewriter https://github.com/mit-plv/rewriter/pull/96
- [ ] metacoq https://github.com/MetaCoq/metacoq/pull/845
- [ ] color https://github.com/fblanqui/color/pull/44
- [ ] CompCert, VST: @MSoegtropIMC could you please adapt these developments?
- [ ] itauto: @fajb, please apply the following patch:
<details>

```patch
From d9b30b5b506c4ee70bbd86e193bb362623bba34f Mon Sep 17 00:00:00 2001
From: Andres Erbsen <andres-github@andres.systems>
Date: Tue, 14 Feb 2023 19:29:03 +0000
Subject: [PATCH] adapt for coq/coq#17022

---
 theories/PatriciaR.v | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/theories/PatriciaR.v b/theories/PatriciaR.v
index 2d2e00c..6f0c6dc 100644
--- a/theories/PatriciaR.v
+++ b/theories/PatriciaR.v
@@ -140,8 +140,8 @@ Module PTrie.
             - apply testbit_spec; intros.
               rewrite land_spec.
               destruct (Nat.eq_dec n0 n).
-              + subst n0. rewrite (proj2 (P n)); auto.
-                rewrite H1; auto.
+              + subst n0. rewrite (proj2 (P n)); auto;
+                try (rewrite H1; auto).
               + rewrite H; auto. destruct (Keys_Base.testbit k n0); simpl; auto.
             - simpl; auto. }
           { elim e. apply testbit_spec.
-- 
2.39.1.581.gbfd45094c4
```

</details>

2023-02-14 20:40 UTC, Alizter commented
In other Coq developments, an explicit `Notations.v` file is kept so that notations can be reserved in a single file without introducing clashes. We apparently don't do this in the standard library except in the prelude: https://github.com/coq/coq/blob/master/theories/Init/Notations.v.

2023-02-24 14:14 UTC, andres-erbsen commented
Now on top of https://github.com/coq/coq/pull/17281 as a path of least resistance in adapting CI developments.

2023-03-06 20:51 UTC, andres-erbsen commented
@MSoegtropIMC I think this is ready to merge. The review requests to `typeclasses-maintainers` and `btauto-maintainers` were due to dependent PRs that have already been merged.

2023-03-07 07:51 UTC, MSoegtropIMC commented
@andres-erbsen : yes - I had this on my ToDo list cause of the CI failures, but these appear to be fixed meaneehile. I will have a final look today and merge then.

2023-03-07 18:03 UTC, MSoegtropIMC commented
@coqbot merge now

2023-03-07 18:04 UTC, MSoegtropIMC commented
@coqbot merge now

2023-03-07 18:04 UTC, merged