Work on `Reals/RIneq.v`
coq/coq pull request #17036
Opened 2022-12-29 19:51 UTC by Villetaneuse

This is a (too) big PR about RIneq.v. At the start I only wanted to add a handful of lemmas after a course of mathematics with coq at undergraduate level, but in the end most of the file has been rewritten.
To sum up the changes (the details are in the attached file):
- about a hundred lemmas added for consistency and/or quality of life, some of them with teaching in mind
- the proofs are rewritten using almost no automation and more consistency (this makes possible to suppress the importation of RealField)
- about a dozen of lemmas are deprecated (changes made accordingly in the rest of the lib)
- documentation added at the start of the file and reorganization of the file in order to have a better coqdoc
- removed references to CReals, for better encapsulation and faster compilation

The attached file contains more information, questions and ideas for further work.
[work_ineq.txt](https://github.com/coq/coq/files/10321840/work_ineq.txt)

- [ ] Added / updated **test-suite**.

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

2022-12-29 20:03 UTC, SkySkimmer commented on theories/Reals/RIneq.v
> +(* We should use Rtotal_order in proofs and total_order_T in definitions. *)
Why not always use total_order_T?

2022-12-29 20:13 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +(* We should use Rtotal_order in proofs and total_order_T in definitions. *)
For teaching purposes, you might want not to dive into differences between predicative and impredicative types. Also (but this is minor) the associativity is not the same, so it is sometimes tedious to destruct differently sumbools and ors.

2023-01-02 15:15 UTC, thery requested changes
Impressive work! It clearly improves the Real library. Should be merged

2023-01-02 15:15 UTC, thery commented on theories/Reals/RIneq.v
> +Lemma IZR_POS_xI : forall p, IZR (Zpos (xI p)) = 1 + (1 + 1) * IZR (Zpos p).
would be nice to have 2 but maybe this breaks too many things?

2023-01-02 16:18 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +(** Reflexivity of the large orders *)
There should be reflexivity of Rge too... but you just made me realize that Rge_refl is the same as Rle_refl (it was already broken before). What should I do about it? Do you think fixing Rge_refl will break things in some libraries?

2023-01-02 16:20 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Req_EM_T : forall r1 r2:R, {r1 = r2} + {r1 <> r2}.
This name was already there. I was trying to be somewhat conservative (I am afraid to break external libraries). `Req_dec` is already the "or version". Maybe alias it to something like `Req_dec_strong`?

2023-01-02 16:29 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rplus_simpl_r : forall r1 r2, r1 + r2 - r2 = r1.
For this new lemma, I borrowed the name from the `Z` module. But it can be changed (then also change the names of the corresponding lemmas for multiplication/division). It's hard to think of a good name for this lemma, but if you want I will think harder about it.

2023-01-02 16:29 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rplus_plus_simpl_r_r : forall r r1 r2, (r1 + r) - (r2 + r) = r1 - r2.
Same thing, the name is borrowed from the `Z` module.  I can try to find a better name if you want.

2023-01-02 16:32 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rplus_nneg_pos_not_0 : forall r1 r2, 0 <= r1 -> 0 < r2 -> r1 + r2 <> 0.
The problem is that there are many different reasons for an addition to be `<> 0` and it is only one of them. This lemma was `tech_plus` before. To be honest, I'd rather deprecate it because it is very ad hoc (a combination of, for instance Rplus_nneg_pos and Rgt_not_eq gives the same result). But there is a hint attached to it, so I don't know what the policy is.

2023-01-02 16:35 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rle_lt_0_plus_1 : forall r, 0 <= r -> 0 < r + 1.
This was already there. I would happily remove/deprecate it, but I fear that it might break external libraries.

2023-01-02 16:51 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rmiddle_order : forall r1 r2, r1 < r2 -> r1 < (r1 + r2) / 2 < r2.
Yes, you're right, I should have found a better name. Average mean scares me a little bit, I would reserve it to a stronger lemma like `~(all_eq v) -> Rmin_vect v < Ravg_vect v < Rmax_vect v` where `v` is a real vector (or even a stronger version with a weighted average!). But maybe something like `Rlt_middle_between` is clear enough?

2023-01-02 16:51 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rmiddle_order : forall r1 r2, r1 < r2 -> r1 < (r1 + r2) / 2 < r2.
ok, on my todo-list.

2023-01-02 16:53 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma S_O_plus_INR : forall n, INR (1 + n) = INR 1 + INR n.
This was already there. If you're ok with it, we can decide to deprecate it.

2023-01-02 16:57 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma IZR_POS_xI : forall p, IZR (Zpos (xI p)) = 1 + (1 + 1) * IZR (Zpos p).
I can try to investigate this point. Maybe the idea was not to rely on the notation `2` which is actually `IZR(2)` (but then why not write R1 + R1... ?) There are still some mysteries for me in this library.

2023-01-02 17:00 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rplus_sqr_eq_0_l : forall r1 r2, Rsqr r1 + Rsqr r2 = 0 -> r1 = 0.
This was already there. What you think of is also there as `Rplus_sqr_eq_0`. If you want we can deprecate it (`apply` will find which part of the `/\` to unify anyway).

2023-01-02 17:02 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rmult_mult_simpl_r_r :
Same issue as Rplus_plus_simpl_r_r, need to think hard of a better name if we decide to go against the naming conventions in `Z`.

2023-01-02 17:02 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +(** ** Order and substraction                            *)
Sorry for that, I will correct it.

2023-01-02 17:10 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rmult_neg_cases :
Yes, nice catch it reduces the proof to 5 lines.

2023-01-02 17:12 UTC, thery commented on theories/Reals/RIneq.v
> +Lemma Rplus_nneg_pos_not_0 : forall r1 r2, 0 <= r1 -> 0 < r2 -> r1 + r2 <> 0.
It is clearly a consequence of Rplus_le_lt_0_compat.
Maybe Rplus_lt_le_neq0?

2023-01-02 17:13 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rplus_npos_le : forall r1 r2, r2 <= 0 -> r1 + r2 <= r1.
Same as above, I liked that the name says that adding a non-positive number yields a less or equal result. But you decide.

2023-01-02 17:14 UTC, Villetaneuse commented on theories/Reals/RIneq.v
> +Lemma Rplus_pos_gt : forall r1 r2, r2 > 0 -> r1 + r2 > r1.
I wanted to convey in the name the intuitive fact that when you add a positive number you get something greater... but if you want I can change the name as you suggest.

2023-01-02 17:19 UTC, thery commented on theories/Reals/RIneq.v
> +Lemma Rmiddle_order : forall r1 r2, r1 < r2 -> r1 < (r1 + r2) / 2 < r2.
Rlt_plus_half?

2023-01-02 17:20 UTC, thery commented on theories/Reals/RIneq.v
> +Lemma S_O_plus_INR : forall n, INR (1 + n) = INR 1 + INR n.
I would, this has nothing to do in a library

2023-01-02 17:21 UTC, thery commented on theories/Reals/RIneq.v
> +Lemma IZR_POS_xI : forall p, IZR (Zpos (xI p)) = 1 + (1 + 1) * IZR (Zpos p).
Yes, I think it is not nice to have theorems that are too cryptic.

2023-01-02 17:22 UTC, thery commented on theories/Reals/RIneq.v
> +(** Reflexivity of the large orders *)
I think it is convertible, so should be ok

2023-01-02 17:25 UTC, thery commented on theories/Reals/RIneq.v
> +Lemma Rplus_simpl_r : forall r1 r2, r1 + r2 - r2 = r1.
I would prefer a more precise name, simpl is very generic. The name should includes plus and minus at least I think

2023-01-02 17:29 UTC, thery commented on theories/Reals/RIneq.v
> +Lemma Rle_lt_0_plus_1 : forall r, 0 <= r -> 0 < r + 1.
deprecate would be nice

2023-01-04 09:04 UTC, thery commented
Thinking it over I think it should be better to leave Req_dec as it is and to have the one on sumbool  as
Req_dec_something

2023-01-04 11:08 UTC, thery commented
@coqbot: run full CI

2023-01-04 11:29 UTC, thery approved these changes

2023-01-04 13:08 UTC, thery commented
@coqbot: run full CI

2023-01-04 17:11 UTC, thery commented
@coqbot ci minimize

2023-01-04 17:12 UTC, thery commented
@coqbot: run full CI

2023-01-04 23:11 UTC, thery commented
ready to be merged

2023-01-06 12:45 UTC, thery commented
@Villetaneuse you should also add an entry in the [changelog](https://github.com/coq/coq/tree/master/doc/changelog)

2023-01-06 15:29 UTC, herbelin commented
Side remark about "decidability" in Type: terminologies already in use (at least in stdlib) include `_dec_type` (in `Logic/Eqdep_dec.v`), `_informative` (in `Logic/ClassicalEpsilon.v`), `_decide` (in `Arith/EqNat.v`), but none of them can really be considered standard. There is also the `ind`/`rec`/`rect` rule for elimination schemes.

2023-01-07 09:37 UTC, thery commented
@herbelin Would be nice if these naming conventions would be written somewhere. Any do you have any objection for this PR to be merged as is?

2023-01-07 10:04 UTC, herbelin commented
@thery: I think that the examples I gave could hardly be called "naming conventions". These were only other (non-standard) isolated examples of naming `{A}+{~A}` here and there in the "standard library".

But, I agree that there is a need to write naming conventions, or at least to collect usages, as a guideline for contributors. (Several library contributors have naming conventions from which inspiration could probably be taken.)

About `Req_EM_T` in this PR, I feel that the name `Req_dec_T` chosen by @Villetaneuse is optimal because it follows the `total_order_T` pattern and thus gives an internal consistency of naming within `Reals` which I think is the most important thing to do.

About the "standard library" in general: my feeling is that it is now somehow hopeless to get a consistency between the different parts of what is called "standard library". My feeling is that we should think more in terms of a collection of standard components. E.g. I think it would make sense to integrate to the "standard library" a component on category theory, another on basic homotopy type theory, another on basic big operators, etc., all kinds of basic things which are worth being made available in a "standard" way. Then, naming consistency between the components would be anyway more and more hopeless to get (*). Moreover, this seems to me that it matches what users do in general, that is combining components of the Coq platform and accepting that these components have their own internal conventions.

(*) Based on the observation that different naming patterns coexist in practice, I think it also makes sense to eventually accept that, like in the real world, the same object can have different names, i.e. that it makes sense to formally introduce a notion of synonyms in the system.

2023-01-07 11:26 UTC, Villetaneuse commented
I have added an entry in the changelog. Tell me if I should change it to include more or less information. This is a very useful exercise since by doing so, I noticed a typo in `Ropp_div_den_depr`. However, I had to modify my local `doc/dune` file to produce html pages (I needed to suppress the "warning as error").

2023-01-07 13:44 UTC, Villetaneuse commented
@thery @herbelin For what it's worth, here is the (soft) method I used.
- Some existing lemmas form a family, sometimes a family has missing members. In that case, add missing members with the same naming patterns as the family. Example : `ROPERATION_PREDICATE_[compat | eq]_[l|r]`
- Some lemmas form a new family. In that case, I often used corresponding names in module `Z`, which looks more polished that `Reals` at this point, with the following translations
  - add -> plus
  - mul -> mult
  - sub -> minus
  - lemmas about an operation/predicate in `RIneq` start with the full operation or predicate name *with its leading `R`*, other operation or predicates appearing in the name of the lemma are stripped off their leading `R`.
- When I think that some names are bad (e.g. `tech_Rplus`), they are renamed, and a notation is given for backward compatibility, without deprecation (but maybe we should ?)
- Variable names also follow some rules: they are named r, r1, r2, ... and, mostly, `r` is used if it is the only variable or, it appears in both sides of a binary relation, in which case it plays a central role and should be the first variable (as it eases the writing of partial instantiation of the lemma).
- lemmas with bad variable names and not that good or bad names have been deprecated. A good version with a completely new name is given with consistent variable names (examples: `double`, `Rlt_Rminus`).
- a problem I could not solve was the case of lemmas with bad variable names but a perfect name (example: `Rdiv_opp_r`), I just added a commentary, because just changing variable names will break proofs relying on `apply (...) with (x := ...)`
- Some lemmas are deprecated because they are too ad-hoc.
- Some lemmas should have been deprecated, but were not because they have a Hint attached to them.

2023-01-07 13:48 UTC, Villetaneuse commented
@coqbot run full CI

2023-01-07 15:46 UTC, Villetaneuse commented
@herbelin This "alternative arguments" (or something like that would) would indeed solve this problem and would be a nice addition.

2023-01-07 19:13 UTC, thery commented
> Tell me if I should change it to include more or less information

@Villetaneuse  look good to me. Will wait to monday to merge it. Thanks!

2023-01-09 15:17 UTC, thery commented
@coqbot: merge now

2023-01-09 15:25 UTC, thery commented
@coqbot: merge now

2023-01-09 15:25 UTC, merged

2023-01-16 14:26 UTC, Zimmi48 commented
It's too late for such big PRs for 8.17. This will have to wait for 8.18.

2023-01-16 14:45 UTC, Villetaneuse commented
You're right and it's certainly better to field-test the changes with the clean-up of other parts of Reals before releasing them.