Add a tactic "show" to help debugging tactic scripts
coq/coq pull request #17086
Opened 2023-01-07 20:00 UTC by herbelin

This PR proposes a `show` tactic to be used to show a goal in the middle of a script without having to reorganize the script.

Example:
```coq
Goal forall n m, n+m = n+m. induction n, m; show; auto.
(*
============================
(0 + 0 = 0 + 0)

m : nat
============================
(0 + S m = 0 + S m)

n : nat
IHn : (forall m : nat, n + m = n + m)
============================
(S n + 0 = S n + 0)

n : nat
IHn : (forall m : nat, n + m = n + m)
m : nat
============================
(S n + S m = S n + S m)
*)
```

- [x] Added / updated **test-suite**.
- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

2023-01-08 18:57 UTC, jfehrle commented
You can use the Ltac debugger for this.  Just put a breakpoint on `auto` and `Set Ltac Debug`.  You won't need to modify the script, either.  And CoqIDE will soon let you turn on the debugger from the menus.  So `show` is probably not needed.

2023-01-09 10:06 UTC, ppedrot requested changes
This is a very hackish implementation for a feature that is only for debugging purposes. Also, this is adding more cruft to the Ltac definitions that are available by default, so this is a no from me.

2023-01-09 10:52 UTC, herbelin commented
I can get the same behavior in Coqide with the debugger, so from my point of view, I have an alternative.

I don't see why, @ppedrot, you say "very hackish". Is it because of the extra parentheses (printing at constr rather than lconstr level). Otherwise, it is rather short and directly to the point. Would you be ok if written instead in Ltac2?

2023-01-09 10:53 UTC, ppedrot commented
It's hackish because it's printing the goal line by line. Many things can occur in the meantime.

2023-01-09 12:36 UTC, ppedrot commented
Ignoring the hack part, I think this should go into a module not required by default. In terms of code quality I don't know how to do better in Ltac1, but this could be implemented as a primitive instead.

2023-01-09 12:41 UTC, MSoegtropIMC commented
> I think this should go into a module not required by default.

How about "LtacAutomation" as module name?

2023-01-09 15:07 UTC, ejgallego commented
@herbelin would it make more sense to allow UIs to show this on hover?

We can easily hack this for coq-lsp if you would like to.

2023-01-09 15:11 UTC, ejgallego commented
> Why not to do it as a primitive instead. Then it could also take an `int` argument, as "Show".

What's a primitive?

2023-01-09 15:17 UTC, herbelin commented
> @herbelin would it make more sense to allow UIs to show this on hover?

That would be very nice.

> What's a primitive?

I think we meant in ocaml using a `TACTIC EXTEND`.

2023-01-09 15:21 UTC, ejgallego commented
> I think we meant in ocaml using a `TACTIC EXTEND`.

That could work, however IMHO I think we could add something more flexible that could allow for a more interactive exploration of the tactic state (at some cost tho, I guess would need some instrumentation).

But a kind of tracing primitive could be interesting sure.

2023-02-03 21:57 UTC, herbelin commented
What to do about this? Do we consider for coqide that putting a breakpoint is enough and, in vscoq/coq-lsp, that hovering will eventually display the goals in the middle of a sequence of tactics, even when the sequence is failing?

2023-02-03 22:08 UTC, andres-erbsen commented
These two mechanisms do not sound like "enough" to me and I expect to continue maintaining my own local `show` if that is the conclusion.

2023-02-03 22:14 UTC, SkySkimmer commented
>It's hackish because it's printing the goal line by line. Many things can occur in the meantime.

What things? Isn't ltac single threaded?

2023-02-04 11:07 UTC, ppedrot commented
> What things? Isn't ltac single threaded?

Ltac is indeed, but we have no guarantee that the Feedback messages are not processed asynchronously with other warnings. Also, there might be weird interactions with backtrack although I'm not sure about this.

2023-02-04 15:25 UTC, herbelin commented
@ppedrot: If `show` were provided with a special caution saying that it is primarily proposed for convenience, w/o the Coq developers endorsing the responsibility of maintaining it, nor claiming that it is an optimal implementation, would that be ok to you?

Actually, if we started to make such distinctions, other tactics that you'd prefer not to take the responsibility of could also join too?

2023-02-04 15:47 UTC, JasonGross commented
> What to do about this? Do we consider for coqide that putting a breakpoint is enough and, in vscoq/coq-lsp, that hovering will eventually display the goals in the middle of a sequence of tactics, even when the sequence is failing?

In Fiat Crypto we have a local implemention at https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/Tactics/PrintGoal.v and https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/Tactics/PrintContext.v, which is primarily used in automation that is both heuristic and supposed to fully solve all goals.  The purpose is getting to see leftover goals from the command line, without having to interactively edit the script, if something changes somewhere and makes the tactic not succeed at all goals.  This usecase is not covered by the two methods you mention.

2023-02-04 15:50 UTC, JasonGross commented on theories/Init/Tactics.v
> +  | H:?T |- _ => idtac H ":" T; fail
Please also print bodies
```suggestion
  | H:?T |- _ => first [ let v := eval cbv delta [H] in H in idtac H ":" T ":=" v | idtac H ":" T ]; fail
```
maybe worth more line breaks though

2023-02-04 15:55 UTC, ejgallego commented
Indeed, while I don't oppose to this as it is pretty harmless in terms of code-base, I wonder about what methodology we are following here.

From my point of view the way this is supposed to work is both not satisfying from the user and document manager developer, there are several points to address:

- it seems to me a terrible UI to have the user insert `show` in their scripts, this should work with tactic scrips as is
- there is the question of overhead, in particular, when do we keep the tactic intermediate state? If we don't, asking for it would require a re-execution. Both choices seem bad. Maybe we can implement this kind of tracing in a very lightweight way tho (for most use cases) by just keeping a pointer locally.
- question of uniformity, why only `;` and not other tactics
- what is the relation with debugging?

@herbelin I believe we could prototype a tactic execution exploration engine pretty quickly if you would be interested; we could enable this in a per-proof or per-sentence basis (or for the whole document and measure overhead) and have it work in coq-lsp.

2023-02-04 19:15 UTC, herbelin commented
> Indeed, while I don't oppose to this as it is pretty harmless in terms of code-base, I wonder about what methodology we are following here.

The question of methodology is a question, yes.

> From my point of view the way this is supposed to work is both not satisfying from the user and document manager developer, there are several points to address:
> 
>   it seems to me a terrible UI to have the user insert `show` in their scripts, this should work with tactic scrips as is

Sure, UI could do a lot (and what I've seen of coq-lsp is very very nice)!

But it is also a question of compromise between now and some time later, as time has a thickness!

As the discussion showed, there is a need. Facing this need, we can say that it is up to everyone to define its own copy of `show`, and that we do not need to provide a version ourselves. We can even be explicit, saying that our objective is to only provide a UI version of `show`, why not.

Or we can say, let's provide a temporary pragmatic/textual version of `show` which we will remove when it will be made obsolete by the UI approach.

>   there is the question of overhead, in particular, when do we keep the tactic intermediate state? If we don't, asking for it would require a re-execution. Both choices seem bad. Maybe we can implement this kind of tracing in a very lightweight way tho (for most use cases) by just keeping a pointer locally.

Maybe.

>   question of uniformity, why only `;` and not other tactics

I don't think that it is specifically about `;`.

>   what is the relation with debugging?

This was explained in the discussion. A typical situation for me is about adapting a proof script to a change. An Ltac code does not work as before, possibly deep inside a nesting of calls, and I want to know where the change induced a different behavior.

So, shortly, it is an equivalent to "printf" debugging, but for Ltac/Ltac2.

> @herbelin I believe we could prototype a tactic execution exploration engine pretty quickly if you would be interested; we could enable this in a per-proof or per-sentence basis (or for the whole document and measure overhead) and have it work in coq-lsp.

Of course I'm interested, and I'm certainly not the only one! Let's look at our agenda and priorities and see if we have some free slot to work on it. (And if not, maybe can we dispatch the work.)

2023-02-04 19:34 UTC, ejgallego commented
Thanks for the comments @herbelin ; as I said I don't oppose this.

I'm glad you found this usable, indeed that answers my question at least if it works for you; but I'm still afraid that wouldn't work too well for some other users. But this is an important feature, and often requested, so this is why I wonder if we could make it a bit more general, and more lightweight and running a full debugger session.

2023-02-04 21:08 UTC, jfehrle commented
This tactic would be helpful for reporting failures in Ltac match constructs.  It would be friendly to show the goal that wasn't solved.  It complements the debugger.

Showing the context in a tooltip may not be ideal.  Contexts can have many lines and may not even fit on the screen.  So tooltips should support scrolling.  Users should be able to copy the text of the tooltip.

Alternatively, a GUI could provide a way to navigate backward and forward in the already executed tactics without discarding what's been proven, highlighting the step being examined.  That may be less confusing for users and wouldn't require duplicating certain code paths, e.g. to generate show proof diffs.

2023-02-06 21:39 UTC, andres-erbsen commented
The implementation in this PR (with Jason's fix) reads as intuitive and desirable to me. I imagine an alternative implementation in Ltac2 or OCaml would be possible, but if I had to guess these would likely be longer and more complex. @ppedrot could you please explain the concrete contexts where you expect the proposed state-of-practice Ltac solution would cause problems?

2023-02-07 09:46 UTC, ppedrot commented
@andres-erbsen in interactive mode, you can get messages from other parallel-running instances that may disrupt the display of the goal by interleaving with it. The printing function should generate a single Feedback message, which is not possible (or at least really not easy) in Ltac1.

2023-02-07 09:49 UTC, ppedrot commented
Also, my point about blindly adding Ltac definitions to the globally available scope still stands. I am still baffled that this is still the norm in Ltac programming and Coq stdlib design.

2023-02-07 12:24 UTC, herbelin commented
@ppedrot: so your wish is:
- that it is either available with a qualified name or activated via a specific `Require`?
- written in ocaml (so I guess in an mlg module, in which case, either we need to extend `TACTIC EXTEND` with ability to qualify names or the activation is by some `Require`)?
- with the printing done in one go?

Correct?

Or is it that you consider that it is not the job of Coq to provide such feature?

As for the long-term maintenance, this is not supposed to be used in final documents, so I guess it is easy to remove whenever the developers want without big consequences.

(More generally, how should Ltac programming and Coq stdlib be better designed?)

2023-02-07 12:45 UTC, ppedrot commented
> that it is either available with a qualified name or activated via a specific Require?

Yes.

> written in ocaml (so I guess in an mlg module, in which case, either we need to extend TACTIC EXTEND with ability to qualify names or the activation is by some Require)?

Yes for the OCaml part, no for the TACTIC EXTEND except if you ensure this does not create a parsing rule. (This is the case if the tactic sits alone in its block without arguments, but there is some dark magic around this.)

> with the printing done in one go?

Yes. Only one call to Feedback.msg_notice.

> Or is it that you consider that it is not the job of Coq to provide such feature?

Maybe not for this tactic, but I'm still desperate that we have no guideline for contribution to the stdlib and basic tactics. We haphazardly merge half-baked stuff of our own and let contributions from external users bitrot without any consideration. My take is that the stdlib is doomed anyways, but this doesn't solve the problem with tactics.

> this is not supposed to be used in final documents

Oh, yeah, just like Restart, Undo and other ungodly commands like Require inside proofs. Can we have a serious reality check before wreaking havoc?

2023-02-07 13:34 UTC, herbelin commented
> > that it is either available with a qualified name or activated via a specific Require?
> 
> Yes.
> 
> > written in ocaml (so I guess in an mlg module, in which case, either we need to extend TACTIC EXTEND with ability to qualify names or the activation is by some Require)?
> 
> Yes for the OCaml part, no for the TACTIC EXTEND except if you ensure this does not create a parsing rule. (This is the case if the tactic sits alone in its block without arguments, but there is some dark magic around this.)
>
> 
> > with the printing done in one go?
> 
> Yes. Only one call to Feedback.msg_notice.

Actually, I don't think I have the courage to write it in OCaml, at least in the short term. The best I could do in the short term is to embed it in a module.

> > Or is it that you consider that it is not the job of Coq to provide such feature?
> 
> Maybe not for this tactic, but I'm still desperate that we have no guideline for contribution to the stdlib and basic tactics. We haphazardly merge half-baked stuff of our own and let contributions from external users bitrot without any consideration. My take is that the stdlib is doomed anyways, but this doesn't solve the problem with tactics.

The stdlib is de facto what users primarily use, so we have no other choices that having to design a methodology for the future of the stdlib.

About bitrotting of user contributions to the stdlib, what is your analysis? (I would say that, in my perception, this is in part due to the difficulty to find a consensus between developers. In particular, some strong opinions among developers are not always easy to turn into constructive actions.)

Actually, I more and more feel that the energy to take care of the stdlib is not among the Coq developers but about the users.

Also, I think that it is a mistake to consider the current stdlib as a monolithic object. The hope for a consistency of style and design over dozens of contributors is vain. We should think in terms of thematic standard components (e.g. bool, arith, lists, sets, ...) small enough to be manageable by a small group, without expecting all the components to necessarily follow the same guidelines.

We should take the diversity of approaches as an ineluctable fact and rather think at how to smoothly combine different styles of library (e.g. by supporting synonymy, by making naming schemes configurable, by supporting better ways to let a library evolve, by adding support for isomorphism between structures or concepts, ...).

> > this is not supposed to be used in final documents
> 
> Oh, yeah, just like Restart, Undo and other ungodly commands like Require inside proofs. Can we have a serious reality check before wreaking havoc?

Are `Restart` and `Undo` used in other final documents than teaching material? And `show` has not the same infrastructure requirements as `Restart` and `Undo`, it would just be 5 lines of Ltac code to add to the few files that would need it.

This being said, I don't see the problem in supporting `Restart`, `Undo` and `Require` inside proofs. They are convenient on a daily basis, and this is enough for me to justify that we support them, even if not intended to be present in final documents. As for UIs, they can forbid these commands whenever they want.

2023-02-07 15:14 UTC, Alizter commented
>Actually, I more and more feel that the energy to take care of the stdlib is not among the Coq developers but about the users.

Spot on @herbelin. I wish that in the shortest time we will put the stdlib in it's own project with its own (non-core) maintainers.

The situation for commands like `Restart` is somewhat unfortunate, but I think we need to (as developers) have a more serious discussion about how these concerns can be lifted to UI design and not kept inside core coq.

I have sympathy with many of PMP's points regarding half baked solutions, and I should point out he is not alone in these opinions amongst the other developers. I do however consider blocking of features to be confusing for contributors (and devs) , but the burden of a constructive solution is not on PMP but rather on the devs as a whole.

We need to start a serious discussion about these kinds of things and come up with a solution to keep both parties happy. I think the up coming user interfaces workshop might be a good place to voice these concerns.

2023-02-07 17:21 UTC, JasonGross commented
> > with the printing done in one go?
> 
> Yes. Only one call to Feedback.msg_notice.

This is also possible in Ltac2, right?  Map over Control.hyps, building a message with Ltac2.Printf.printf, then join the messages with newlines, and Printf.print with the goal.

2023-02-07 19:15 UTC, herbelin commented
> > Yes. Only one call to Feedback.msg_notice.
> 
> This is also possible in Ltac2, right? Map over Control.hyps, building a message with Ltac2.Printf.printf, then join the messages with newlines, and Printf.print with the goal.

Then, would an Ltac2-based solution, encapsulated in a module, with only one call to the printer, a consensual solution, as good as an OCaml-based solution?

2023-02-07 19:39 UTC, herbelin commented
> The situation for commands like `Restart` is somewhat unfortunate

What are the concerns about `Restart`? It is not useful in the PG/coqide model or in the interactive document-based model, but it makes senses in coqc-based testing or in pedagogical context. And isn't the implementation for free? Or are there maybe issues with parallelism? What am I missing? This being said, I probably did not use `Restart` myself for years. On the other side, I'm using `Undo`, quite regularly, for testing.

> I have sympathy with many of PMP's points regarding half baked solutions, and I should point out he is not alone in these opinions amongst the other developers. I do however consider blocking of features to be confusing for contributors (and devs) , but the burden of a constructive solution is not on PMP but rather on the devs as a whole.

Without giving examples of half-baked solutions, it is difficult to comment. As a general rule, I would say that there are many half-backed things in Coq but, among these ones:
- which ones are considered today as half-baked only because it is now that we know, with hindsight and new expertise, how to do them better?
- and which ones are compromises, because time is limited, and sometimes a half-baked solution is better than nothing?

2024-04-17 14:06 UTC, SkySkimmer commented
So what do we do with this?

2024-04-17 14:07 UTC, ppedrot commented
I vocally advocate for closing.

2024-04-17 15:51 UTC, andres-erbsen commented
@ppedrot would you be okay with merging if we added a warning that this tactic is for troubleshooting only? I rely on copies of essentially this tactic in a number of repos, and not being able to recommend it to Coq users in general makes helping them harder.

2024-04-18 08:17 UTC, ppedrot commented
I really want the two following points to be addressed:
- A decent implementation, which probably means in OCaml.
- Put this behind a qualified scope.

It takes about 5 minutes to get this done.

2024-04-18 08:19 UTC, ppedrot commented
Also, I think that this conversation is very much related to the stdlib CEP / discussion that is going on. A standard library should also provide a rich set of tactics, the prelude is really there for very specific stuff.

2024-04-18 11:47 UTC, andres-erbsen commented
Okay: I would be willing to invest much more than 5 minutes to get this in, the criteria seem clear enough, and it's high time I try writing an ML tactic. What ML tactic should I read as a reference for the use of the ML API?

Would `From Coq Import Troubleshooting` be a path that makes everyone happy?

2024-04-18 12:16 UTC, ejgallego commented
It seems to me that having a tactic for this is still horrible; being able to inspect a composed tactic is basic functionality that the tactic engine should provide at core level, not requiring users to insert some random stuff like a hacky tactic, that by the way, provides a horrible UI experience to the user.

2024-04-18 12:55 UTC, ejgallego commented
Sure, printf debugging is still useful in many scenarios _when a regular debugger is not enough_, for example, in highly concurrent systems.

However, that doesn't mean that the large majority of users still need a regular working debugger so they can just click on a tactic and see some intermediate state, that a very pressing priority of Coq that cannot be replaced by printf debugging.

A quote I recently posted on Zulip from the LeanSSR folks:
> I can very much relate to that. So let me note that one of the key advantages of LeanSSR compared to Coq/SSReflect is that the former truly allows for the "small-step" proof debugging (this is what we consider one of the main features).
>
> That is, if you open any of our proofs in a project that has been compiled and step between the symbols, you'll see the changes in the tactic state. This, hopefully, will provide additional intuition on what is the meaning of each operation.

So imagine how things are for Coq when people has to port a complex tactic language in order to get a reasonable user experience.

2024-04-18 15:19 UTC, Alizter commented
What about documenting the tactic in the reference manual? That way it doesn't get plopped in the stdlib and people interested in tips for debugging ltac can find it together with explanations.

2024-04-18 18:16 UTC, jfehrle commented
> @ejgallego It seems to me that having a tactic for this is still horrible; being able to inspect a composed tactic is basic functionality that the tactic engine should provide at core level, not requiring users to insert some random stuff like a hacky tactic, that by the way, provides a horrible UI experience to the user as the printing happens outside the usual `proof/goals` calls in UIs.

Horrible, indeed, but it a good intermediate step and far less work.  I could have implemented the more sophisticated functionality a couple years ago as an extension of the Ltac debugger, but the contribution process is not sufficiently focused on efficiently delivering improvements to the users.  Look in the mirror.

2024-06-10 02:17 UTC, closed without merging