Adding "assumption id" to tell explicitly which assumption to use
coq/coq pull request #17202
Opened 2023-02-03 12:05 UTC by herbelin

This is motivated by teaching (e.g. in classes which identify the axiom rule with `assumption`). It seems also rather natural. It also useful to tell explicitly which hypotheses to use when there are several of them, w/o having to switch to the concept of `exact`.

Internally, it is however interpreted as `exact id`.

- [ ] Added / updated **test-suite**.
- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

2023-02-03 12:13 UTC, ppedrot commented
This looks like pure noise to me, especially given that it can be implemented directly by whoever wants to provide a teaching-oriented wrapper for the stdlib.

2023-02-03 12:14 UTC, ppedrot commented
And also it's messing with the parser, since before that assumption was just a pure Ltac definition.

2023-02-03 12:20 UTC, ppedrot requested changes
To be explicit, this is a big no from me.

2023-02-03 12:35 UTC, Alizter commented
I also agree with PMP that we shouldn't have this in core coq. @herbelin is there anything stopping you from having an ltac notation in a library?

2023-02-03 12:41 UTC, ejgallego commented
While indeed this particular addition may not belong to that part of the code, IMHO such needs are very important for teaching; WaterProof has many useful notations and tactics like this, and have been extensively testing in teaching.

Maybe we could indeed embrace (and extend) some parts of WaterProof ?

2023-02-03 12:49 UTC, Alizter commented
My point is about teaching coq in general. A common complain I have recieved from students is that: "Coq documentation is hard to read; there are 50 different ways to do the same thing".

2023-02-03 17:04 UTC, herbelin commented
Hum, I don't know what to conclude from this discussion. My point was it is natural to do `assumption id`, like sometimes, we may prefer `apply H`, `exact H`, `easy`/`trivial`,`auto`, each with a different intent.

The question of the parsing is important. There are efforts towards proposing an "intuitive" syntax but this somehow goes against efforts towards having a more "regular" ("simpler" ?, more "programming"-style) grammar? Does this mean having different levels of language depending on needs?

For instance, why to keep `assumption` at all, as it can be made from simpler components.

About a Tactic Notation or an ltac definition rather than an mlg definition, I don't care. As said in the header, my purpose is to explore ideas that look intuitive and easy to teach (and `assumption id` looks like so to me).

That documentation is hard to read is a point. My feeling is that it improved a lot in the recent years, but I'm not reading it regularly so, it is not me to say. Redundancies exist in all languages. Maybe, what is missing is less about removing some redundancies but about giving guidance about how to choose between the different possibilities?

Actually, what would each of you in the discussion recommend to a student facing the goal `H:A, H0:B |- A`?

I'd like to see proposals and directions about where to go: if we aim at simplifying further the syntax or removing the redundancies, let's do it really. If we aim at better guiding the newcomers, let's do it. If we think that we should have different languages depending on needs, let's do it. I feel bad with a status quo that go nowhere.

2023-02-03 17:07 UTC, SkySkimmer commented
>Hum, I don't know what to conclude from this discussion. My point was it is natural to do assumption id, like sometimes, we may prefer apply H, exact H, easy/trivial,auto, each with a different intent.

Is there really an intent when using apply instead of exact? IMO when facing this choice exact should always be picked.
Using the automatic tactics is about not wanting to type/depend on the name, so adding the name `assumption` does not make sense to me.

2023-02-03 17:10 UTC, ejgallego commented
@herbelin my own understanding of the discussion is that teaching-oriented languages can live (like waterproof) in their own library of tactic notations, so they are more tweakble, and even translatable.

2023-02-03 17:41 UTC, herbelin commented
> > Hum, I don't know what to conclude from this discussion. My point was it is natural to do assumption id, like sometimes, we may prefer apply H, exact H, easy/trivial,auto, each with a different intent.
> 
> Is there really an intent when using apply instead of exact?

I would say yes: `apply` has only the intent to use the lemma or hypothesis, w/o caring about whether it is exactly it or not.

Otherwise, an example where I would use `apply` over `exact` is `apply H1, H2, H3.` when the last hypotheses has no arguments.

> IMO when facing this choice exact should always be picked. Using the automatic tactics is about not wanting to type/depend on the name, so adding the name `assumption` does not make sense to me.

Iiuc, you are seeing `assumption` as an automation tactic, why not.

In any case, questions such as how to resolve the tension between being more generic (e.g. not mentioning a name, thus `assumption` or `auto`), or being more constraining (e.g. preferring `exact` to `apply`) seem to include a large part of personal appreciation. Would we really be able to defend an absolute rule?

> my own understanding of the discussion is that teaching-oriented languages can live (like waterproof) in their own library of tactic notations, so they are more tweakble, and even translatable.

It seems indeed that this would be the best way to address such teaching issues w/o triggering fights. (Still, 1: I don't see how the current status quo could be considered as satisfactory even for those defending that `assumption id` a bad idea. 2: `assumption id` does make intuitive and logical sense to me even outside a teaching context, and this cannot be ignored on the altar of "parsing")

2023-02-03 18:07 UTC, herbelin commented
Compare:
- `subst`/ `subst id`
- ssreflect `apply:` which has a meaning without arguments
- `injection`/`injection id`
- `contradiction`/`contradiction id` (even if the latter is possibly too weak compared to what we would intuitively expect)

Would we like to remove `injection id` or `subst id`? Are we sure that finding `assumption id` bad is not before all because we are not used to it?

2023-02-03 18:26 UTC, ppedrot commented
Because `assumption id` is literally an artificially weaker variant of exact.

2023-02-03 18:34 UTC, herbelin commented
> Because assumption id is literally an artificially weaker variant of exact.

That's only one way to look at it.

2023-02-03 19:39 UTC, herbelin commented
Just in case there is an ambiguity on the context of the PR. I did not propose the PR in order to teach `assumption id`. I proposed the PR after a student tried `assumption id` then came to me asking why it did not work and whether he was doing something wrong. I told him that he was not wrong, that this was indeed a good idea to have tried that syntax but that it was not supported by Coq and that it had to do instead `exact id`. The syntax would have existed, the student, who followed his intuitions, would not have needed for help.

2023-02-20 19:23 UTC, maximedenes requested changes
Also a no for me, for exactly the same reasons as mentioned by PMP.

2023-02-20 19:25 UTC, maximedenes commented
I used to teach students to read documentation in these cases ;) but of course the Coq manual is a bit hard to digest, partly because the tactic language is already very redundant.

2023-02-20 19:27 UTC, maximedenes commented
On the other hand, I also agree that a teaching mode for Coq would be very nice. But not by adding even more constructions to the core language, rather as a separate thing.

2023-02-21 08:48 UTC, herbelin commented
@maximedenes , @ppedrot:  I still don't buy the arguments.

- The objective of not declaring tactics without declaring scoping sounds legitimate. 
- The objective of not defining ad hoc syntaxes ("messing with the parser") eventually blocking extensibility sound legitimate too.
- But dismissing the existence of a proper language of tactics, deliberatedly designed with a proper grammar, and  dismissing the advantages of rounding angles of this language (vs subjectively asserting that it is "pure noise"), while `Require Import Ltac` is anyway optional, and while other approaches not extending the grammar can also live in parallel, does not look sound to me.

Adding `assumption id` would no more prevent anyone to redefine the meaning of neither `assumption` nor `assumption id` if they want. Similarly as when only `assumption` is provided.

On the other side, I would be happy to:

- support the objective of adding qualification to tactic base names if that's the purpose, 
- or to reduce the number of redundant implementations of the same concept if that's the purpose (which is not the case here: the concepts of `exact` and `assumption` are different),
- or reduce the number of ways to do the same thing (e.g. `exact c` vs `apply c` vs `refine c`, but that's apparently not what you are proposing neither),
- or to provide a way to move scripts to a language with purely applicative syntax (Ltac2?), if that's one of the objective,
- or to move any "pedagogical" contents to an external module if that's the objective.
 
But I don't understand the advantages of staying in the middle of the way. We need directions, not negations of directions!

2023-08-05 09:02 UTC, herbelin commented
As an example, the Villetaneuse class decided to not mention `assumption` and to advertize `exact` instead.

Closing this PR about which I could not convince.

2023-08-07 11:00 UTC, closed without merging