Document open critical bugs
coq/coq pull request #17245
Opened 2023-02-09 16:20 UTC by SkySkimmer

2023-02-09 16:35 UTC, Alizter approved these changes

2023-02-09 16:36 UTC, Alizter commented
@ppedrot @silene Could you have a look through?

2023-02-09 16:50 UTC, silene commented on dev/doc/critical-bugs
> +  GH issue number: ocaml/ocaml#6385, #11170
See #13439.

2023-02-09 16:52 UTC, Zimmi48 commented on dev/doc/critical-bugs
>  To add: #7723 (vm_compute universe polymorphism), #7695 (modules and algebraic universes), #7615 (lost functor substitutions)
Maybe move this to the closed bug section?

2023-02-09 17:20 UTC, SkySkimmer commented on dev/doc/critical-bugs
> +  GH issue number: ocaml/ocaml#6385, #11170
changed

2023-02-22 13:54 UTC, silene requested changes

2023-02-22 13:54 UTC, silene commented on dev/doc/critical-bugs
> +  fixed in: v8.13 (#13431)
This whole entry should be removed, as it is a duplicate of the very first entry. This specific mention of #13431 could be applied to the previous entry.

2023-02-22 13:54 UTC, silene commented on dev/doc/critical-bugs
> +  risk: middle if not using coqchk, none if using coqchk (coqchk rejects the produced file)
I am a bit confused by this entry (and the previous one). There exists another entry about `Print Assumptions` in the file and I find it to be better classified. Applying the same principle here, it would give:
```
  component: module functors
  summary: Print Assumptions does not report Unset Universe Checking used during functor application
  introduced: v8.11 (#10291) or earlier
  impacted versions: V8.11-NOW
  impacted coqchk versions: none (coqchk rejects affected files)
  found by: Gaëtan Gilbert
  GH issue number: #16646
  exploit: see issue
  risk: low as it needs the use of explicit unsafe flags
```

2023-02-22 13:54 UTC, silene commented on dev/doc/critical-bugs
> +  risk: low
I would classify it as "risk: none, as it requires crafted .vo files". I consider that our risk assessment should only apply to non-adversarial users, that is, what is the chance that a standard user triggers the bug inadvertently. (When the user is adversarial, the risk is always "critical" anyway.)

2023-02-22 15:33 UTC, silene commented on dev/doc/critical-bugs
> +  summary: buffer overflow on large accumulators, large records and closures
The old summary is fine, as it is really "a buffer overflow on large accumulators".

This new summary should be put on the very first entry instead of "memory corruption", that is, "buffer overflow on large records and closures".

2023-02-22 15:33 UTC, silene commented on dev/doc/critical-bugs
> +  GH issue number: #13439
```suggestion
  component: VM reduction machine
  summary: buffer overflow on large records and closures (infinite loop with OCaml 5)
  introduced: 8.1
  impacted versions: 8.1-NOW
  impacted coqchk versions: none (no VM in coqchk)
  fixed in: NONE
  found by: Dolan, Roux, Melquiond
  GH issue number: ocaml/ocaml#6385, #13439
```

2023-02-22 16:00 UTC, silene approved these changes

2023-02-22 16:20 UTC, Alizter commented
@coqbot merge now

2023-02-22 16:20 UTC, merged