Reimplement the specialize with tactic using evar clauses.
coq/coq pull request #17322
Opened 2023-03-01 22:12 UTC by ppedrot

Instead of relying on the legacy meta mechanism and ad-hoc combinators, we use instead an evar-based approach that is more principled and in particular type-safe.

2023-03-02 08:13 UTC, ppedrot commented
@coqbot ci minimize

2023-03-02 10:29 UTC, ppedrot commented
Reduced test from coqutils:
```coq
Axiom key : Type.
Axiom value : Type.
Axiom eqb : key -> key -> bool.
Axiom remove : list value -> key -> list value.
Axiom sorted : list value -> bool.
Axiom lookup : list value -> key -> value.

Goal forall (l : list value) (k : key),
(sorted l = true -> forall k' : key, eqb k k' = false -> lookup (remove l k') k = lookup l k) ->
sorted l = true -> False
.
Proof.
intros l k IHl ST.
specialize IHl with (1 := ST).
```

2023-03-02 14:45 UTC, ppedrot commented
@coqbot ci minimize

2023-03-02 15:02 UTC, JasonGross commented
Did the artifacts of either the base job or the tip job expire or something?

2023-03-02 15:48 UTC, JasonGross commented
Ah, I see, I missed the bot message, sorry for the noise

2023-03-02 16:11 UTC, ppedrot commented
Small example:
```coq
Axiom tuple : Type.
Axiom mem : Type.
Axiom unchecked_store_bytes : tuple -> mem.
Axiom load_bytes : mem -> Prop.

Goal forall
(m : mem)
(IHn : forall (m' : mem) (w : tuple),
  unchecked_store_bytes w = m' -> load_bytes m' -> load_bytes m),
True.
Proof.
intros.
specialize IHn with (1 := eq_refl).
```
IMHO this is a bug on current master. In this example on master the variable w is intantiated to an evar that is left dangling after specialize returns, but this PR complains about not being able to make refl succeed because the variable w is out of scope. I'd recommend keeping the new behaviour, or even better to requantify over w by delaying the interpretation of the binders to the point they're referring to so that they live in the right context. The latter is harder to implement because it requires more in-depth changes to the API. In any case this is incompatible with the current behaviour, so I guess we should just adapt riscv accordingly.

BTW while you're around @JasonGross I think I'd be interested to here your opinion on this one.

2023-03-02 16:12 UTC, ppedrot commented
FTR this kind of scope-breaking property of meta-based unification is responsible for horrible bugs such as the recent #17314.

2023-03-02 16:28 UTC, JasonGross commented
Is the interpretation the same as `let p := open_constr:(eq_refl) in specialize IHn with (1 := p).`, or is there magic going on that delays the interpretation of holes in `eq_refl`?

If we are delaying the interpretation of holes until we have traversed the binders, then we should regeneralize as you say.  If instead we interpret holes at top level, then we should instantiate `w` with a fresh (sub)evar, resulting from unifying `?e = ?e` with `unchecked_store_bytes ?w = ?m'`.  I guess the former is more general, so I'm inclined to say the ideal behavior is to regeneralize.  I think failing with "w not bound" is incorrect in either case, though I guess it's fine as a transitory state.

2023-03-02 16:35 UTC, ppedrot commented
@JasonGross on master the evar is created once for all at toplevel, so I suspect it's mostly equivalent to your first encoding. But like other non-e variants, specialize is expected not to create stray evars. This is really a corner-case so for the time being I think I'll just write a trivial fix for riscv-coq.

2023-03-02 17:34 UTC, JasonGross commented
Yeah, I guess we should maybe have `especialize` as well?

2023-03-11 11:33 UTC, ppedrot commented
Overlays merged, this should be ready now.

2023-03-14 14:27 UTC, SkySkimmer requested changes
We should probably have a changelog since CI found changes.

2023-03-15 09:17 UTC, ppedrot commented
@SkySkimmer done

2023-03-15 09:20 UTC, SkySkimmer approved these changes

2023-03-17 14:13 UTC, SkySkimmer commented
@coqbot merge now

2023-03-17 14:13 UTC, merged