Add instances for rewriting in pairs.
coq/coq pull request #17493
Opened 2023-04-14 13:14 UTC by HaoYang670

Fixes / closes #17060

- [ ] Added / updated **test-suite**.

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.
  
  - [ ] Documented any new / changed **user messages**.
  - [ ] Updated **documented syntax** by running `make doc_gram_rsts`.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

2023-04-19 05:12 UTC, HaoYang670 commented
Could someone please help to reivew this?

2023-04-19 07:12 UTC, Alizter commented
@coqbot run full ci

2023-04-19 07:12 UTC, Alizter commented
@coqbot bench

2023-04-19 21:29 UTC, JasonGross commented on theories/Classes/RelationPairs.v
> +#[export] Instance proper_pair1: forall A B RA1 RA2 RB1 RB2 (RA : relation A) (RB : relation B),
I would call this `Proper_RelProd_flip_impl` and the other one `Proper_RelProd_impl`.

2023-04-20 08:21 UTC, HaoYang670 commented on theories/Classes/RelationPairs.v
> +#[export] Instance proper_pair1: forall A B RA1 RA2 RB1 RB2 (RA : relation A) (RB : relation B),
Good suggestion! Renamed them.

2023-04-20 17:03 UTC, JasonGross approved these changes
This looks good to me.  It might be worth it to also add an `iff` instance.  Given the Coq bench results and the fact that these are export rather than global, I think it's relatively unlikely that this will cause issues.

2023-04-21 12:42 UTC, HaoYang670 commented
Thank you for review @JasonGross.

>  It might be worth it to also add an iff instance.

Do you mean to prove 
```coq
#[export] Instance Proper_RelProd_flip_impl: forall A B RA1 RA2 RB1 RB2 (RA : relation A) (RB : relation B),
    (Proper (RA1 ==> RA2 ==> Basics.flip Basics.impl) RA /\ Proper (RB1 ==> RB2 ==> Basics.flip Basics.impl) RB)
    <-> Proper (RA1 * RB1 ==> RA2 * RB2 ==> Basics.flip Basics.impl) (RA * RB)%signature.
```
?

I got `iff is not a declared type class.` error when trying to instance it.

2023-04-22 02:43 UTC, JasonGross commented
No, I mean something like
```coq
#[export] Instance Proper_RelProd_iff: forall A B RA1 RA2 RB1 RB2 (RA : relation A) (RB : relation B),
    Proper (RA1 ==> RA2 ==> iff) RA
    -> Proper (RB1 ==> RB2 ==> iff) RB
    -> Proper (RA1 * RB1 ==> RA2 * RB2 ==> iff) (RA * RB)%signature.
```

2023-04-23 13:37 UTC, HaoYang670 commented
Thank you, @JasonGross. I've added the `iff` instance. Please help to reivew.

2023-04-23 18:36 UTC, JasonGross requested changes

2023-04-23 18:36 UTC, JasonGross commented on theories/Classes/RelationPairs.v
> +  cbv; intuition eauto; destruct y, y0;
Please don't use autogenerated names.  Is `firstorder eauto` enough to solve the goal?  If not, please name the variables explicitly with `intros <names>`

2023-04-24 05:25 UTC, HaoYang670 commented on theories/Classes/RelationPairs.v
> +  cbv; intuition eauto; destruct y, y0;
Unfortunately, only `firstorder eauto` cannot solve the goal. 
I have explicitly `intros` with names. Please review

2023-04-24 06:24 UTC, JasonGross approved these changes

2023-04-24 06:25 UTC, JasonGross commented
@coqbot run full ci

2023-04-24 06:25 UTC, JasonGross commented
@coqbot bench

2023-04-26 01:48 UTC, HaoYang670 commented
The bench failed.

2023-04-26 03:55 UTC, JasonGross commented
Maybe we should just try again? @coqbot bench

2023-04-27 01:42 UTC, HaoYang670 commented
How should we analyze the bench result?

2023-04-27 01:51 UTC, Alizter commented
@HaoYang670 There is no observable slowdown, everything is within noise range. The reason I asked for one was to check that we didn't cause any problems with hint databases causing longer build times.

2023-04-27 01:52 UTC, Alizter commented
@JasonGross will you assign?

2023-04-27 01:55 UTC, JasonGross commented
I can assign, but do we need reviews from @coq/typeclasses-maintainers and @coq/stdlib-maintainers ?

2023-04-27 16:29 UTC, Alizter approved these changes

2023-04-27 16:29 UTC, Alizter commented
The PR has been open long enough with not much activity from those maintainers so I think that it is fine to go ahead with it.

2023-04-27 19:19 UTC, JasonGross commented
@coqbot merge now

2023-04-27 19:19 UTC, merged

2023-09-04 10:38 UTC, Zimmi48 commented
FTR, it would have been preferable if these commits had been squashed together, and in particular to use a git rebase operation instead of a git merge to resolve conflicts.

2023-09-04 15:48 UTC, JasonGross commented
Would it be possible to give coqbot a "squash and merge" option, as well as a "rebase and then force push to the branch" option?

2023-09-06 12:45 UTC, Zimmi48 commented
I don't think rebasing can be automated in general when there are conflicts, even if the conflicts were fixed in a merge commit. We could implement a coqbot rebase feature (there is an issue about this: https://github.com/coq/bot/issues/105), but it would only work when the conflicts can be auto-fixed or when there are no conflicts.

Regarding the "squash and merge" option, currently we require merge commits, so this would require first force-pushing the squashed commit to the PR branch, then merging the PR. I'm also a bit worried about contributors starting to abuse this and squashing too much. But this is doable indeed.