[stdlib] Some injectivity lemmas for lists
coq/coq pull request #17787
Opened 2023-06-29 14:54 UTC by haansn08

This PR adds following fact to stdlib:
* `rev_inj: rev l1 = rev l2 -> l1 = l2`
* `app_eq_cons: x ++ y = a :: z -> (x = nil /\ y = a :: z) \/ exists x', x = a :: x' /\ z = x' ++ y`
* `app_inj_pivot: x1++a::x2 = y1++a::y2 -> ((In a x1 /\ In a y2) \/ (In a x2 /\ In a y1)) \/ (x1 = y1 /\ x2 = y2)`

The last lemma can be used like this: if `a|b = c|d` for some separator `|` then we have `a=b` and `b=d`. This holds if the separator is not contained in (x1,x2) or (x1,y1) or (y2,x2) or (y2,y1).

2023-07-03 15:21 UTC, SkySkimmer commented
@coqbot run full ci

2023-07-06 15:37 UTC, haansn08 commented
A friend just noticed that the last lemma also holds when the separator is not contained in `a` and not contained in `b`. I now added this fact as `app_inj_pivot2`. I didn't include a `_tail` version since it is trivially obtained from `app_inj_pivot2` by the symmetry of equality.

2023-07-30 17:52 UTC, haansn08 commented on theories/Lists/List.v
> +  Qed.
Removed.

2023-07-30 17:53 UTC, haansn08 commented on theories/Lists/List.v
> +  Qed.
Also removed.

2023-07-30 17:54 UTC, haansn08 commented on theories/Lists/List.v
> +    lx1++a::lx2 = ly1++a::ly2 -> lx1 = ly1 /\ lx2 = ly2.
I proved the general statement and removed the other ones, as requested.

2023-07-31 08:35 UTC, olaure01 requested changes
It looks good to me. Could you:
- [x] update PR description
- [x] squash commits
- [x] add changelog

Then we will run a full CI before merging.

2023-07-31 08:35 UTC, olaure01 commented on theories/Lists/List.v
> +  Qed.
Just about ordering of statements: maybe keep all `*_eq_unit` grouped or all `app_eq_*` grouped.

2023-07-31 08:35 UTC, olaure01 commented on theories/Lists/List.v
> +        * right. split; congruence.
Suggestion of a slightly more compact proof:
```
    induction y1 as [|b y1 IHy] in x1 |- *; intros [[-> H]|[x' [-> H]]]%app_eq_cons.
    - right. now injection H.
    - subst y2.
      left; left. split; [apply in_eq | apply in_elt].
    - injection H as -> ->.
      left; right. split; [ apply in_elt | apply in_eq ].
    - symmetry in H. apply IHy in H as [[[]|[]]|[]].
      + left; left. split; [apply in_cons|]; assumption.
      + left; right. split; [|apply in_cons]; assumption.
      + right. split; congruence.
```
It avoids mixing the `destruct y1` and the use of `app_eq_cons`: both approaches work but mixing them looks over complicated.

2023-08-01 09:44 UTC, haansn08 commented
I applied your suggestions, thank you. I also added a changelog and squashed the commits.

2023-08-01 12:01 UTC, olaure01 approved these changes

2023-08-01 12:01 UTC, olaure01 commented on doc/changelog/11-standard-library/17787-app_inj_pivot.rst
> +  by Stefan Haan and Olivier Laurent).
```suggestion
  by Stefan Haan, with help of Olivier Laurent).
```
I think this is the [recommended format](https://github.com/coq/coq/tree/master/doc/changelog#how-to-add-an-entry).

2023-08-01 14:11 UTC, olaure01 commented
@coqbot run full ci

2023-08-02 22:41 UTC, haansn08 commented
@olaure01 Done!

2023-08-03 06:13 UTC, olaure01 commented
@coqbot merge now

2023-08-03 06:13 UTC, merged