add Z.divide support for Z.to_euclidean_division_equations
coq/coq pull request #17927
Opened 2023-08-04 13:10 UTC by doctor-kaliy

Solves  #17918 according to the description provided in the Issue.

2023-08-04 16:09 UTC, JasonGross requested changes
Thank you!  Please add a small test to the test suite at the bottom of
https://github.com/coq/coq/blob/d95cb47c4f338b8ee18dcbcb5f18ba5622cfe028/test-suite/success/Nia.v#L919 (something like `Lemma test_divide : forall x y, Z.divide x y -> x mod 0 = 0. Proof. intos; nia. Qed.`, maybe?), add a changelog entry with `dev/tools/make-changelog.sh`, and I'll be happy to approve and merge

2023-08-05 14:37 UTC, doctor-kaliy commented
> Thank you! Please add a small test to the test suite at the bottom of
> 
> https://github.com/coq/coq/blob/d95cb47c4f338b8ee18dcbcb5f18ba5622cfe028/test-suite/success/Nia.v#L919
> (something like `Lemma test_divide : forall x y, Z.divide x y -> x mod 0 = 0. Proof. intos; nia. Qed.`, maybe?), add a changelog entry with `dev/tools/make-changelog.sh`, and I'll be happy to approve and merge

Thank you for your feedback.

### Here is what I found out trying to add some tests

This could have been a good test ``` Lemma Z_divide_test (x y : Z) (H : (y | x)) : x <> 0 \/ y <> 0 -> x mod y = 0. ```
I tried to prove it by ``` intros; nia. ``` and it didn't work. ``` Tactic failure:  Cannot find witness. ```
But this lemma can be proved by ``` intros. Z.to_euclidean_division_equations; assert (x0 = q); nia. ```(or by any other "by hand proof") Here we prove that ```x0``` we get from destructing ```(y | x)```, and ```q``` from ```Z.div_mod_to_equations'``` are equal.

Though, nia is able to handle cases like:
```
Lemma Z_divide_test_5 (z: Z) (H : (5 | z)) : z mod 5 = 0. Proof. intros. nia. Qed.
Lemma Z_divide_test_neg_5 (z: Z) (H : ((-5) | z)) : z mod (-5) = 0. Proof. intros. nia. Qed.
Lemma Z_divide_test_5_neg_5 (z: Z) (H : (5 | z)) : z mod (-5) = 0. Proof. intros. nia. Qed.
```
but these don't look meaningful enough :( .

Now I'm a bit confused about the test to add. Tests with constant values are too simple and test that checks divisibility can't be proved automatically.

### One more thing worth flagging
 ```Lemma Z_divide_test' (x y : Z) : Z.rem x y = 0 -> x mod y = 0. Proof. intros. nia. Qed.``` also doesn't work. It can be done with ```Z.to_euclidean_division_equations; assert (q0 = q); nia.```, for instance.

2023-08-05 20:30 UTC, JasonGross commented
That's a good point.  I've created https://github.com/coq/coq/pull/17934 to assert such "equal quotient" equations when they are obvious.  If you add
```coq
(* Make the direction of [Z.divide] line up with the rest of the Euclidean equation facts *)
Local Lemma divide_alt x y : Z.divide x y -> exists z, y = x * z.
Proof. intros [z H]; exists z; subst; apply Z.mul_comm. Qed.
```
and handle `Z.divide` with
```coq
match goal with
| [ H : Z.divide _ _ |- _ ] => try apply divide_alt in H; destruct H
end.
```
then the improvement from #17934 should be sufficient to handle it.  I guess without #17934 and without a fix for #17935 (I was considering that `(x | y) -> (y | x) -> x = y \/ x = -y` might be good, but `nia` can't even prove `x * y = 1 -> x = 1 \/ x = -1`...) this PR doesn't actually add more power, so we should wait for #17934.  (Or you can rebase on #17934, but #17934 breaks the test-suite and I've run out of time today to fix it.)

Also, would you add ```:g:`Z.divide` ``` to the list at https://github.com/coq/coq/blob/e78e90d219e66ce00bf9e78e228ac51b5ab17020/doc/sphinx/addendum/micromega.rst?plain=1#L371

2023-11-22 17:14 UTC, JasonGross commented
This is blocked on https://github.com/coq/coq/pull/17934.  Once https://github.com/coq/coq/pull/17934 is merged all this needs is to make sure test-suite examples work

2023-12-19 15:38 UTC, JasonGross commented
Now that https://github.com/coq/coq/pull/17934 has finally been merged, if you want to rebase this @doctor-kaliy it should be possible to add some actual tests.

2023-12-23 05:59 UTC, jfehrle approved these changes
wording suggestions

2023-12-23 05:59 UTC, jfehrle commented on doc/changelog/04-tactics/17927-divide_to_euclidean_division_equations.rst
> +  by doctor-kaliy).
```suggestion
  When using :g:`Z.to_euclidean_division_equations`, you can now pose
  equations of the form ``x = y * q`` using :g:`Z.divide`.
  (`#17927 <https://github.com/coq/coq/pull/17927>`_,
    by Evgenii Kosogorov).
```

Nice to use real names.

2023-12-23 06:54 UTC, JasonGross approved these changes

2023-12-23 06:56 UTC, JasonGross commented
@coqbot run full ci

Once you respond to @jfehrle 's review, assuming CI passes, I'll plan to merge by Monday

2023-12-23 06:56 UTC, JasonGross commented
@coqbot bench

2023-12-23 10:23 UTC, SkySkimmer commented
machine was missing python-is-python3
@coqbot bench

2023-12-23 16:47 UTC, JasonGross commented
@coqbot run full ci

2023-12-23 17:12 UTC, JasonGross commented
@coqbot run full ci

2023-12-24 01:58 UTC, JasonGross commented on doc/changelog/04-tactics/17927-divide_to_euclidean_division_equations.rst
> +  equations of the form ``x = y * q`` using :g:`Z.divide`.
```suggestion
  equations of the form ``x = y * q`` using :g:`Z.divide`
```

2023-12-26 01:19 UTC, JasonGross requested changes

2023-12-26 15:53 UTC, jfehrle commented on doc/changelog/04-tactics/17927-divide_to_euclidean_division_equations.rst
> +    by Evgenii Kosogorov).
I believe so.  I suppose `unreleased.rst` is created by some script from this file and others.

2023-12-30 02:30 UTC, JasonGross approved these changes

2023-12-30 02:30 UTC, JasonGross commented
quickchick is also failing in the same way on master, so let's merge.  Thanks @doctor-kaliy !

@coqbot merge now

2023-12-30 02:31 UTC, JasonGross commented
@coqbot merge now

2023-12-30 02:31 UTC, merged

2023-12-30 02:32 UTC, JasonGross commented
Oh, oops, I guess this should not be targeted at 8.19, but at 8.20