[release] minimalistic changes for 8.18
coq/coq pull request #17997
Opened 2023-08-31 09:38 UTC by gares

I got to write this by personal communication with @mattam82 

I trimmed some info which in my opinion don't belong to the changelog.

2023-08-31 12:46 UTC, proux01 commented
It seems this could highlight:
* work on Ltac2 (but I'm no expert and don't know what to put forward)
* improvements on the warning system, enabling finer control of warnings, particularly for deprecations
* some work on the stdlib (but again, I don't know what to put forward)

2023-08-31 13:01 UTC, gares commented
I don't know exactly how Matthieu was doing his selection of items.

IMO we should put forward items which may have a big impact (on porting the code, or writing new code).  This is what I'd like to see in the changelog foreword. So I selected a change of default (long awaited, announced in advance, etc...), but maybe there are other change any user should be aware of.

There is also another document some projects produce at release time, which is somewhat mixed with the changelog in Coq. Examples that come to mind are GNOME, FireFox and VSCode which give a page with a few highlights, typically with a short video or screenshot to show "cool stuff". They really do a good job, but I'd keep advertisements out of the changelog.

2023-08-31 15:47 UTC, Zimmi48 requested changes, later dismissed
We've merged the release highlights and the changelog indeed. Maybe this was a bad idea. I personally find it easier to browse the changelog and have the highlights at the beginning. However, what you propose here is a break from this tradition, and it doesn't allow figuring out the most important changes in the release or to give due credit to their authors.

2023-08-31 15:48 UTC, Zimmi48 commented
Note that the release summary (or highlights) is also what I typically copy over to Zenodo:

https://zenodo.org/record/8161141

2023-08-31 21:16 UTC, gares commented
Then tell me what to write there, since I don't know.

2023-09-01 07:22 UTC, herbelin commented
I have two remarks in passing:

- soundness fix -> soundness fixes

  Maybe also tell in the summary in which part of the kernel are the soundness bugs.

- change Miscellaneous into Extraction, since there is only one item there, which is about extraction

  By the way, regarding changes in extraction, I'm regularly hesitating about which category to use (typically between vernac-commands-and-options and misc). What about having an explicit Extraction category?

2023-09-01 07:25 UTC, herbelin commented
By the way, still in passing, the quality of the release job is impressing.

2023-09-01 08:45 UTC, Zimmi48 commented
> * What about having an explicit Extraction category?

Sure, that's a good idea. We can remove the category from the changelog when it is empty anyway.

2023-09-01 13:19 UTC, herbelin commented
> Sure, that's a good idea.

Do you want me to do it?

2023-09-01 13:24 UTC, Zimmi48 commented
Yes, please!

2023-09-01 14:24 UTC, herbelin commented
Maybe an excès de zèle, but since I had the opportunity to look at the change log, I seized it (the opportunity) to apply the `Describe your change here but do not end with a period` rule of `dev/tools/make-changelog.sh` (even retroactively, if nobody objects to this syntactic instance of "historical revisionism"). This is PR #18001.

2023-09-04 09:06 UTC, gares commented
> Then tell me what to write there, since I don't know.

Dear @coq/doc-maintainers here my attempt at identifying some highlights. Quick feedback is welcome.

2023-09-04 09:13 UTC, proux01 commented on doc/sphinx/changes.rst
> +with a host of improvements. We highlight a few impactful change above all:
```suggestion
with a host of improvements. We highlight a few impactful changes above all:
```

2023-09-04 09:23 UTC, herbelin commented on doc/sphinx/changes.rst
> +    This should be particularly usful to handle deprecations.
```suggestion
    This should be particularly useful to handle deprecations.
```

2023-09-04 09:25 UTC, Zimmi48 reviewed
Thanks! And sorry for not helping more.

2023-09-04 09:25 UTC, Zimmi48 commented on doc/sphinx/changes.rst
> +    sort (the alrithm used to pick `Type`). Thanks to this feature many `Prop`
```suggestion
    sort (the algorithm used to pick `Type`). Thanks to this feature many `Prop`
```

2023-09-04 09:25 UTC, Zimmi48 commented on doc/sphinx/changes.rst
> +    as names (of contants, inducticve types, etc) and finally fine grained
```suggestion
    as names (of contants, inductive types, etc) and finally fine-grained
```

2023-09-04 09:27 UTC, Zimmi48 commented
Unless we discuss it in a Coq Call (at the very least), I would keep the other parts of the release summary, however. In particular, we do not currently have another place to give credits (that would be kept up-to-date). The permalinks to this particular version documentation are useful and the number of merged PRs and closed issues in the milestone is also interesting information (even if very approximate).

2023-09-04 09:40 UTC, gares commented on doc/sphinx/changes.rst
> +    This should be particularly usful to handle deprecations.
Apparently it is broken (see https://github.com/coq/coq/issues/17982) so I'm not putting it forward.

2023-09-04 09:42 UTC, Zimmi48 commented on doc/sphinx/changes.rst
> +    This should be particularly usful to handle deprecations.
OK that makes sense, although it works for quite a few useful things.

2023-09-04 09:44 UTC, herbelin commented on doc/sphinx/changes.rst
> +    as names (of contants, inductive types, etc) and finally fine-grained
```suggestion
    as names (of constants, inductive types, etc) and finally fine-grained
```

2023-09-04 09:46 UTC, Zimmi48 commented
For tasks other than committing code (to the Coq repository) basically.

>All PR are listed with their authors

Note that even this is not true since many PRs are silent ones (from a changelog perspective) because they do not contain user-facing changes, although it is true that the committers will still be listed in the list that you've put in the summary.

2023-09-04 10:05 UTC, gares commented
> For tasks other than committing code (to the Coq repository) basically.

I'm not competent for doing this.
I did not follow everything that happened in the Coq community and I'm not qualified to pick the most valuable contributions. After all I'm managing the release, not the community nor coordinating the project.

So you can either live with a technical foreword written and signed by me, or find someone coauthoring it (quickly).

The fact that it does not take 1h to complete this task and that this task is in the critical path for the release is, to me, a sign that something is off with it. We organized the release so that this task has weeks to complete, but if it does not for any good or bad reason, we should just live with it.

2023-09-04 10:19 UTC, Zimmi48 approved these changes
Will leave a bit of time before merging, so that others can finish reviewing / commenting.

2023-09-04 10:21 UTC, gares commented
Nothing prevents you or Matthieu to update the doc after the tag.

2023-09-04 10:25 UTC, mattam82 commented
I think it would be better to let the release manager write the highlights in the future as well, as they are already familiar with all the changes and probably are aware of the main changes / compat issues. I’m also ok to remove the mentions on work on opam/platform/website etc in the changes, which are not really release-specific. But the stats on PRs and issues give a rough idea of the amount of changes and I think it would be good to keep them here.

2023-09-04 10:27 UTC, mattam82 commented
Also I would not become a blocking point here, and it feels fairer that I don’t take credit for releases I barely contributed to in practice while the release managment work is non-trivial.

2023-09-04 10:36 UTC, gares commented on doc/sphinx/changes.rst
> +Enrico Tassi, Hao Yang, Théo Zimmermann.
```suggestion
The 41 contributors to the 8.18 version are:
Reynald Affeldt, Tanaka Akira, Matthieu Baty, Yves Bertot,
Lasse Blaauwbroek, Ana Borges, Kate Deplaix, Ali Caglayan, Cyril Cohen, Maxime Dénès,
Andrej Dudenhefner, Andres Erbsen, Jim Fehrle, Yannick Forster,
Paolo G. Giarrusso, Gaëtan Gilbert, Jason Gross, Samuel Gruetter,
Stefan Haan, Hugo Herbelin, Yoshihiro Imai, Emilio Jesús Gallego Arias,
Olivier Laurent, Meven Lennon-Bertrand, Rodolphe Lepigre, Yishuai Li,
Guillaume Melquiond, Karl Palmskog, Pierre-Marie Pédrot, Stefan Radziuk,
Ramkumar Ramachandra, Pierre Rousselin, Pierre Roux, Julin S,
Kazuhiko Sakaguchi, Weng Shiwei, Michael Soegtrop, Matthieu Sozeau,
Enrico Tassi, Hao Yang, Théo Zimmermann.
```

2023-09-04 10:40 UTC, Zimmi48 commented
Sounds good. We should probably also improve the tooling so that writing this summary is easier, including to highlight non-code specific tasks (e.g., starting with reviews).

2023-09-04 10:58 UTC, gares commented on doc/sphinx/changes.rst
> +Coq 8.17.0. Maxime Dénès and Enrico Tassi were the release managers.
```suggestion
We are very grateful to the Coq community at large for the help in making this
new version of Coq. Version 8.18's development spanned over 6 months from the release of
Coq 8.17.0. Maxime Dénès and Enrico Tassi were the release managers.
```

2023-09-04 21:51 UTC, jfehrle reviewed
Wording suggestions

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +with a host of improvements. We highlight a few impactful changes above all:
```suggestion
with a host of improvements. We highlight a few impactful changes:
```

Doesn't add anything that "highlighting" doesn't cover

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +  - the universe unification algorithm is now able to delay the commitment to a
```suggestion
  - the universe unification algorithm can now delay the commitment to a
```

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +    sort (the algorithm used to pick `Type`). Thanks to this feature many `Prop`
```suggestion
    `Sort` (the algorithm used to pick `Type`). Thanks to this feature many `Prop`
```

IINM

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +    as names (of constants, inductive types, etc) and finally fine-grained
```suggestion
    as names (of constants, inductive types, etc) and fine-grained
```

Not needed.

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +  - The warning system offers new categories, enabling finer (dis)activation of specific warnings.
```suggestion
  - The warning system offers new categories, enabling finer (de)activation of specific warnings.
```

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +  - many new lemmas considered useful to teach analysis with Coq are now part of
```suggestion
  - many new lemmas useful for teaching analysis with Coq are now part of
```

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +Ramkumar Ramachandra, Pierre Rousselin, Pierre Roux, Julin S,
@ju-sh, would you like us to include your full name in the 8.18 contributors list?

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +new version of Coq. Version 8.18's development spanned over 6 months from the release of
```suggestion
We are very grateful to the Coq community for their help in creating 8.18
in the 6 months since the release of
```

2023-09-04 21:51 UTC, jfehrle commented on doc/sphinx/changes.rst
> +| Sophia-Antipolis, August 2023,
```suggestion
| Sophia-Antipolis, September 2023,
```

2023-09-05 07:21 UTC, gares commented on doc/sphinx/changes.rst
> +Ramkumar Ramachandra, Pierre Rousselin, Pierre Roux, Julin S,
```suggestion
Ramkumar Ramachandra, Pierre Rousselin, Pierre Roux, Julin Shaji,
```

2023-09-05 07:23 UTC, gares commented on doc/sphinx/changes.rst
> +
```suggestion
  - Many new lemmas useful for teaching analysis with Coq are now part of
    the standard library about real numbers.
  - The `#[deprecated]` attribute can now be applied to definitions.
  
```

2023-09-05 07:26 UTC, gares commented
should be good to go

2023-09-05 11:07 UTC, gares commented
please merge so that I can backport

2023-09-05 12:39 UTC, maximedenes commented
@Zimmi48 merging because @gares is asking

2023-09-05 12:39 UTC, maximedenes commented
@coqbot merge now

2023-09-05 13:14 UTC, maximedenes commented
sudo @coqbot merge now

2023-09-05 13:14 UTC, maximedenes commented
@coqbot Ok, fair enough, you won

2023-09-05 13:21 UTC, proux01 commented
@coqbot merge now

2023-09-05 13:21 UTC, merged