Attribute #[native_compile=no] per definition
coq/coq pull request #18033
Opened 2023-09-11 10:02 UTC by SkySkimmer

Close #4790

2023-09-11 10:03 UTC, SkySkimmer commented
May need some checking of the attribute use.

2023-09-11 10:03 UTC, SkySkimmer commented
cc @JasonGross

2023-09-11 16:30 UTC, JasonGross commented
> > We should try adapting [#17899 (comment)](https://github.com/coq/coq/pull/17899#issuecomment-1711786569) on top of this PR
> 
> @JasonGross can I let you do it?

@proux01 Done

2023-09-11 16:33 UTC, JasonGross commented
> May need some checking of the attribute use.

What about
```coq
Definition foo := I.
#[native_compile=no] Definition bar := I.
Definition baz := bar.
Definition qux := foo.
Eval native_compute in foo. (* sanity check *)
Fail Eval native_compute in bar. (* check failure of native_compute *)
Fail Eval native_compute in baz. (* check correct handling of transitive dependency on native uncompilable *)
Eval native_compute in foo. (* check that native compiler not left in an inconsistent state *)
```
?

There's also now some testing in https://github.com/coq/coq/pull/17899

2023-09-11 16:36 UTC, SkySkimmer commented
I mean more like 
~~~coq
#[native_compile=no] Definition bar : True.
Proof.
exact I.
Qed. (* attribute doesn't make sense with Qed *)
~~~
, checking that the attribute isn't dropped if we did Defined instead, checking Lemma etc

2023-09-11 18:52 UTC, ejgallego approved these changes
Vernac LGTM

2023-09-12 00:54 UTC, JasonGross commented
Would `#[native_compile=ondemand]` also make sense, for "separate compilation should skip this constant, but `native_compute` should not error"?

2023-09-12 01:06 UTC, JasonGross commented
I've added this attribute in my project, so if you merge https://github.com/coq/coq/pull/18028 and then bench with native on, you should see a speedup here.

2023-09-12 07:11 UTC, silene commented
> Would `#[native_compile=ondemand]` also make sense, for "separate compilation should skip this constant, but `native_compute` should not error"?

Since Coq compiles `.v` files into OCaml modules, if the module already exists (due to separate compilation), you cannot add a missing definition afterwards. It has to be there from the start. So, supporting this feature would require a large redesign. A smaller redesign would be to allow `#[native_compile=ondemand]` at the scope of an entire file, since then the OCaml module would no longer preexist.

2023-09-12 09:00 UTC, SkySkimmer commented
>Since Coq compiles .v files into OCaml modules, if the module already exists (due to separate compilation), you cannot add a missing definition afterwards.

I don't think so, native_compute doesn't care that definitions from a coq module are all in the same ocaml module or not.
Indeed if you do eg
~~~coq
Module M.
Definition foo := 1 + 1.
Definition bar := foo + foo.
End M.

Eval native_compute in M.foo.
Eval native_compute in M.bar.
~~~
M.bar is compiled in the second Eval and refers to the M.foo compiled in the first IIRC.

2023-09-12 09:13 UTC, silene commented
First, I said Coq "files", not "modules". Second, the current module is handled in a special way, which is not impacted by separate compilation.

2023-10-03 09:08 UTC, proux01 commented
@JasonGross what's the status of this?

2023-10-03 13:53 UTC, JasonGross commented
I have not been tracking, but am quite interested in having this go in.  @SkySkimmer what's the status?

2023-10-04 11:43 UTC, SkySkimmer commented
I added some tests.

>Would #[native_compile=ondemand] also make sense, for "separate compilation should skip this constant, but native_compute should not error"?

It's more complicated to implement so let's worry about it some other time.

2023-10-04 12:32 UTC, SkySkimmer commented
@JasonGross neural net is failing with
~~~
- COQNATIVE theories/MaxOfTwoNumbers/Computed/AllAttnPattern.vo
- Error: Cannot native compile reference to constant NeuralNetInterp.MaxOfTwoNumbers.Computed.AllAttnPattern.all_tokens_attn_pattern_concrete_value:
-        it was declared with #[native_compile=no].
~~~
When a constant is marked native-off all (transparent) users must also be native-off

I guess in this case it's missing on https://github.com/JasonGross/neural-net-coq-interp/blob/6c8ea48f24ee37d059638d81d66d9c1ddafa6964/theories/MaxOfTwoNumbers/Computed/AllAttnPattern.v#L15-L18

2023-10-04 12:34 UTC, SkySkimmer commented
>Do I understand correctly that the user has to manually put the attribute on any definition that happens to transitively depend on a definition with the attribute? I am not even talking about the case of native_compute here, just plain compilation of separate .vo files. If so, that will be quite painful for the user.

Yes

2023-10-04 13:38 UTC, JasonGross commented
> > Do I understand correctly that the user has to manually put the attribute on any definition that happens to transitively depend on a definition with the attribute? I am not even talking about the case of native_compute here, just plain compilation of separate .vo files. If so, that will be quite painful for the user.
> 
> Yes

I think this is untenable.  Such definitions should be automatically marked as disabled for native compilation, with a warning that can be turned into an error if the user desires

2023-10-04 13:47 UTC, SkySkimmer commented
That's not so easy to implement, especially if we want to be sound wrt the module system.

2023-10-04 13:57 UTC, JasonGross commented
It doesn't need to be sound with respect to modules, I'm fine getting the current error message if someone tries to apply a functor to a module with an omitted constant or whatever (though I imagine it'll be a different error).  The warning I'm suggesting should just be a best-effort thing, where any definition whose body directly contains a constant marked native_compile no also becomes marked that way automatically, and a warning is emitted if the user has not already specified native_compile no on this definition.  This should automatically take care of transitive dependencies.  I guess it would be nice for this to also happen at functor application time, but it's not necessary (certainly not necessary in this PR, possibly not necessary at all, though maybe at least we should be able to mark entire modules with disabled native compilation?), I'm mostly fine with users having to decide at functor declaration time whether a constant should have native or not

2023-10-20 12:44 UTC, proux01 commented
@JasonGross what about merging this as it is, that would already enable merging https://github.com/coq/coq/pull/17899 and could still be improved later following your suggestion?

2023-10-20 15:29 UTC, JasonGross commented
I'd be pretty happy merging this as-is, though I guess that means NNI needs an overlay, which I can prepare

2023-10-23 11:22 UTC, proux01 commented
@JasonGross great, please ping me once you've done the NNI overlay

2023-10-23 11:53 UTC, SkySkimmer commented
let's have a bench before merging once the overlay is ready

2023-11-08 21:01 UTC, JasonGross commented
@SkySkimmer I've pushed https://github.com/JasonGross/neural-net-coq-interp/commit/e2a4b0ec3b2744b68575bb3b8085bad022513274, hopefully it'll work.  Do you want to merge https://github.com/coq/coq/pull/18028, rebase this PR, and run the CI and bench again?

2023-11-08 21:05 UTC, JasonGross commented
I can rebase this PR and set a bench running, I guess

2023-11-08 21:08 UTC, JasonGross commented
@coqbot bench

2023-11-09 13:21 UTC, SkySkimmer commented
Bench https://gitlab.inria.fr/coq/coq/-/jobs/3577788

2023-11-09 13:40 UTC, SkySkimmer commented
~~~
- File "./theories/MaxOfTwoNumbers/Computed/AllAttnPattern.v", line 25, characters 0-4:
- Error: Cannot use #[native_compile=no] with opaque definitions.
~~~

2023-11-10 05:37 UTC, JasonGross commented
I will fix that, but does this mean that `#[native_compile=no]` is unusable with `Program Definition` / `Derive` + `Qed`?  It seems like this should be a warning, though, like "native_compile=no has no effect on opaque definitions"

2023-11-10 05:53 UTC, JasonGross commented
I've pushed https://github.com/JasonGross/neural-net-coq-interp/commit/c7220936fc501ad22b6a7563bb76595321271de2 which removes `#[native_compile=no]` from opaque definitions.

I think a test-case should be added to the test-suite for compatibility with `Program` and `Derive`, like,
```coq
From Coq Require Import Derive Program.

#[native_compile=no] Derive foo SuchThat (foo = 10) As foo_eq.
Proof.
  refine eq_refl.
Qed.

#[native_compile=no] Program Definition bar : nat * nat * nat := (0, _, _).
#[native_compile=no] Next Obligation.
exact 0.
Qed.
#[native_compile=no] Next Obligation.
exact 0.
Defined.
```

2023-11-10 05:54 UTC, JasonGross commented
@coqbot run full ci

2023-11-10 05:56 UTC, JasonGross requested changes

2023-11-10 05:56 UTC, JasonGross commented on test-suite/success/no_native.v
> +Fail Eval native_compute in bar. (* check failure of native_compute *)
test-suite fails with
```
==========> TESTING success/no_native.v <==========
     = I
     : True
     = I
     : True
Error: Cannot native compile reference to constant bar:
it was declared with #[native_compile=no].
0m0.000000s 0m0.000000s
0m0.130000s 0m0.110000s
==========> FAILURE <==========
```
What's going on?

2023-11-10 09:52 UTC, SkySkimmer commented on test-suite/success/no_native.v
> +Fail Eval native_compute in bar. (* check failure of native_compute *)
The test suite does native compile so baz also needs to be marked native-no

2023-11-10 13:40 UTC, SkySkimmer commented
~~~
- COQNATIVE theories/MaxOfTwoNumbersSimpler/Computed/AllLogitsAccuracy.vo
- Error: Cannot native compile reference to constant NeuralNetInterp.MaxOfTwoNumbersSimpler.Computed.AllLogits.all_tokens_logits:
-        it was declared with #[native_compile=no].
~~~
Please test your changes with this branch before asking for a bench

2023-11-10 23:41 UTC, JasonGross commented
> Please test your changes with this branch before asking for a bench

Sorry about that, testing it locally now

2023-11-11 00:03 UTC, JasonGross commented
@SkySkimmer Could you add support for `Derive` (any maybe `Program`)?  I've pushed an update to nnci, but it's still going to fail, and the current failure is due to the lack of support for `Derive`.

Here's a test-case
```coq
From Coq Require Import Derive Program.

Set Warnings "unsupported-attributes".

#[native_compile=no] Definition bar := 10.

#[native_compile=no] Derive foo SuchThat (foo = bar) As foo_eq.
Proof.
  subst foo; reflexivity.
Qed.

#[native_compile=no] Program Definition baz : nat * nat * nat := (bar, _, _).
#[native_compile=no] Next Obligation.
exact 0.
Qed.
#[native_compile=no] Next Obligation.
exact 0.
Defined.
```

Also, btw, is it easy for plugins that add commands that emit constants to support this attribute?  (e.g., `#[native_compile=no] Equations ...`)

2023-11-22 15:11 UTC, closed without merging