[CI] List points of contact in ci-basic-overlay.sh
coq/coq pull request #18321
Opened 2023-11-15 09:34 UTC by proux01

Following [yesterday's weekly call](https://github.com/coq/coq/wiki/Coq-Call-2023-11-14), it appears it would be nice to list points of contact for each CI dev.

2023-11-15 09:38 UTC, proux01 commented
@affeldt-aist, @aleksnanevski, @andres-erbsen, @arthuraa, @bcpierce00, @benediktahrens, @beta-ziliani, @bgregoir, @Blaisorblade, @clayrat, @CohenCyril, @co-dan, @damien-pous, @ejgallego\
, @erikmd, @fajb, @fpottier, @gares, @gmalecha, @huynhtrankhanh, @Janno, @JasonGross, @jellooo038, @jim-portegies, @Karmaki, @LasseBlaauwbroek, @Lysxia, @liyishuai, @lukaszcz, @mattam82\
, @maximedenes, @minkiminki, @mrhaandi, @nmvdw, @palmskog, @pi8027, @RalfJung, @rmatthes, @samuelgruetter, @silene, @SkySkimmer, @spitters, @strub, @tchajed, @thery, @upamanyus, @vbgl, \
@whonore, @xavierleroy, @ybertot, @yforster  sorry to bother you, we'd like to maintain points of contact for each dev in Coq CI and you seem to be a regular maintainer of one of them, please complain if this is not the case (you can check to which dev your login is related there: https://github.com/coq/coq/pull/18321/files )

2023-11-15 10:26 UTC, fpottier commented
Indeed, @jhjourdan and I are the maintainers of `coq-menhirlib`.

2023-11-15 10:37 UTC, palmskog commented on dev/ci/ci-basic-overlay.sh
> +# Contact @maximedenes, @huynhtrankhanh, @thery, @Blaisorblade on github
```suggestion
# Contact @rtetley on github
```
I think for this part of VsCoq it's only @rtetley these days, maybe @gares as well?

2023-11-15 11:33 UTC, erikmd commented
Cc @yforster FYI (because it seems @proux01's comment did not trigger a **mention** for your username)

2023-11-15 12:31 UTC, SkySkimmer approved these changes

2023-11-15 12:54 UTC, RalfJung commented on dev/ci/ci-basic-overlay.sh
> +# Contact @RalfJung on github
You can also add @robbertkrebbers  (for Iris and std++ and iris_examples)

2023-11-15 12:56 UTC, RalfJung commented on dev/ci/ci-basic-overlay.sh
> +# Contact @upamanyus, @RalfJung on github
@tchajed could also help with Perennial issues

2023-11-15 14:49 UTC, JasonGross requested changes, later dismissed

2023-11-15 14:49 UTC, JasonGross commented on dev/ci/ci-basic-overlay.sh
> +# Contact @andres-erbsen, @JasonGross on github
```suggestion
# Contact @andres-erbsen on github
```
I don't have merge bits anymore on this repo

2023-11-15 14:49 UTC, JasonGross commented on dev/ci/ci-basic-overlay.sh
> +# Contact @JasonGross on github
```suggestion
# Contact @JasonGross, @samuelgruetter on github
```

2023-11-15 14:49 UTC, JasonGross commented on dev/ci/ci-basic-overlay.sh
> +# Contact @samuelgruetter on github
```suggestion
# Contact @samuelgruetter, @andres-erbsen on github
```

2023-11-15 14:53 UTC, nmvdw approved these changes

2023-11-15 16:27 UTC, liyishuai requested changes

2023-11-15 16:27 UTC, liyishuai commented on dev/ci/ci-basic-overlay.sh
> +# Contact @Lysxia on github
```suggestion
# Contact @Lysxia @liyishuai on github
```

2023-11-15 16:27 UTC, liyishuai commented on dev/ci/ci-basic-overlay.sh
> +# Contact @liyishuai on github
```suggestion
# Contact @lemonidas @Lysxia @liyishuai on github
```

2023-11-15 16:27 UTC, liyishuai commented on dev/ci/ci-basic-overlay.sh
> +# Contact @bcpierce00 on github
```suggestion
# Contact @bcpierce00 @liyishuai on github
```

2023-11-15 23:17 UTC, gares approved these changes

2023-11-16 07:30 UTC, LasseBlaauwbroek approved these changes

2023-11-16 08:26 UTC, mrhaandi commented on dev/ci/ci-basic-overlay.sh
> +# Contact @mrhaandi, yforster on github
it should say @yforster

2023-11-16 10:17 UTC, liyishuai approved these changes

2023-11-20 10:44 UTC, rmatthes requested changes

2023-11-20 10:44 UTC, rmatthes commented on dev/ci/ci-basic-overlay.sh
> +# Contact @benediktahrens, @nmvdw, @rmatthes on github
```suggestion
# Contact @benediktahrens, @m-lindgren, @nmvdw, @rmatthes on github
```

2023-11-23 13:22 UTC, SkySkimmer approved these changes

2023-11-23 13:23 UTC, SkySkimmer commented
@coqbot merge now

2023-11-23 13:24 UTC, SkySkimmer commented
@coqbot merge now

2023-11-23 13:24 UTC, merged