Ensure that names of constants, inductive types or constructors have distinct names and that binders are named
coq/coq pull request #18394
Opened 2023-12-09 16:50 UTC by herbelin

The PR does the following:
- do not forbid `Arguments` on section variables (though maybe this is a too early allowance because it does not propagate in goals)
- ensure that Coq objects have distinct names, e.g.:
   ```coq
    Definition f (a a:nat) := a.
    About f.
    (* Before: Arguments f (a a)%nat_scope *)
    (* With the PR: Arguments f (a a0)%nat_scope *)
  ```
  Possible alternative: failing instead of renaming silently
- ensure that binders are named:
   ```coq
   Definition g (_:nat) (P:nat -> Prop) (x : P ltac:(auto)) := x.
   About g.
   (* Before: Arguments g _%nat_scope P%function_scope x *)
   (* With the PR: Arguments g n%nat_scope P%function_scope x *)
   ```
   Note: The alternative to force naming user-side would require several changes in the CI 

The last point will be useful for #14597 which requires named binders but for which CI showed that this is sometimes not the case.

See also issue #6786 about non-distinct names in inductive types.
 
Depends on #18393.

- [x] Added / updated **test-suite**
- [ ] Added **changelog**.

2023-12-15 09:17 UTC, ppedrot commented
I think that autogenerated names in general are really bad. It's extremely annoying for tactics, but here it's affecting vernacular definitions. The fix goes in the wrong direction for #14597. If one wants to name bound variables, it's the responsibility of the user to name the corresponding definition correctly.

2023-12-15 09:26 UTC, herbelin commented
> it's the responsibility of the user to name the corresponding definition correctly.

Yes.

It might be quite a lot of overlays though. We could make an evaluation of the number of changes to do and if too much have a warning as compromise? (Or ask upstreams to do the changes?)

2023-12-15 09:37 UTC, ppedrot commented
I think a warning is a good idea, regardless of the chosen solution.

2024-05-23 16:19 UTC, ppedrot requested changes
This PR is doing the wrong change. Never ever should we rename binders explicitly given by the user using an freshening algorithm, that would drive people crazy and make the code very much not modular (e.g. when metaprogramming). Similarly, anonymous binders should similarly remain anonymous. Instead, Coq should warn when there are two variables names that conflict and let the user fix the issue, not try to be clever.

2024-05-23 16:23 UTC, ppedrot commented
This is going the wrong way and there is no point in keeping zombie PRs, we should close.

2024-05-23 16:23 UTC, closed without merging

2024-05-23 18:49 UTC, herbelin commented
"zombie PR" is your terminology that I don't endorse! Personally, I would name it an experience which suggests that another approach should be done (in particular in relation to #14597). But that will require some concentration on the topic that I don't have now.