windows CI: Fix path after platform update
coq/coq pull request #18645
Opened 2024-02-08 16:36 UTC by SkySkimmer

2024-02-08 16:39 UTC, MSoegtropIMC approved these changes
LGTM to adjust to the path changes in Coq Platform

2024-02-08 16:44 UTC, MSoegtropIMC commented
@SkySkimmer : sorry, on second though you also need to change
```
%BASH% --login -c "pwd && ls -la && cd platform
```
The `cd platform` needs to be `cd /platform`

2024-02-08 16:45 UTC, MSoegtropIMC requested changes

2024-02-08 16:45 UTC, MSoegtropIMC commented on dev/ci/platform/coq-pf-04-installer.bat
> +COPY /v /b %CYGROOT%\platform\windows_installer\*.exe %GITHUB_WORKSPACE%\artifacts || GOTO ErrorExit
In addtion the `cd platform` needs to be changed to `cd /platform`

2024-02-08 19:05 UTC, SkySkimmer commented
seems to work

2024-02-08 19:23 UTC, MSoegtropIMC approved these changes
LGTM

2024-02-08 19:23 UTC, MSoegtropIMC commented
> seems to work

Yes, I think you already changed it, while I was doing my comment. It looks good now.

2024-02-08 20:28 UTC, SkySkimmer commented
merge?

2024-02-09 09:14 UTC, MSoegtropIMC commented
@coqbot merge now

2024-02-09 09:14 UTC, merged