zify nat and N by default
coq/coq pull request #18730
Opened 2024-02-28 22:55 UTC by andres-erbsen

This was left as future work in https://github.com/coq/coq/pull/14037 due to increased power of zify breaking a few CI developments; I have now managed to get everything that builds with my installed packages to pass.

- [ ] Added **changelog**.
- [ ] Opened **overlay** pull requests.
    - [ ] bbv
    - [ ] kami
    - [ ] bedrock2
    - [ ] bignums

2024-02-29 00:16 UTC, andres-erbsen commented
Given current implementation quirks this actually makes zify weaker in some cases, because saturation does not run on divisions that are converted to euclidean equations. Example from Rupicola:


```coq
  Lemma Nat_mod_eq'' a n:
    n <> 0%nat ->
    (n * (a / n) = a - (a mod n))%nat.
  Proof.
    intros H; pose proof Nat.mul_div_le a n H.
    rewrite Nat.mod_eq; try lia.
    (*
H0 : (n * (a / n) <= a)%nat

========================= (1 / 1)

(n * (a / n))%nat = (a - (a - n * (a / n)))%nat
     *)
    Fail lia.
    Import Zify.
    intros; Zify.zify_pre_hook; zify_elim_let; zify_op; Zify.zify_iter_specs; zify_saturate;
    Zify.zify_to_euclidean_division_equations; Zify.zify_post_hook; xlia zchecker.
  Qed.
```

I think this pass ordering is wrong independently of this PR.

2024-02-29 09:41 UTC, fajb commented on theories/micromega/ZifyN.v
Can you explain how  `N.div`, `N.modulo` and `N.pow` are handled?
Should not they be moved.

2024-02-29 14:19 UTC, andres-erbsen commented on theories/micromega/ZifyN.v
They seem to be already handled:
https://github.com/coq/coq/pull/18730/files#diff-90580bcabbf0cbdb5c50a09b1412bbe210a1a0510f34bf7fceff0baf70f0761fR397
https://github.com/coq/coq/pull/18730/files#diff-90580bcabbf0cbdb5c50a09b1412bbe210a1a0510f34bf7fceff0baf70f0761fR402
https://github.com/coq/coq/pull/18730/files#diff-90580bcabbf0cbdb5c50a09b1412bbe210a1a0510f34bf7fceff0baf70f0761fR440

This matches my recollections of using zify.

2024-02-29 16:49 UTC, fajb requested changes
Could you update the doc, I think the `zify` part should be updated to stop mentioning `ZifyNat` etc
After that, let's go for it.

2024-03-01 15:53 UTC, andres-erbsen commented
@coqbot run full ci

2024-03-01 20:45 UTC, andres-erbsen commented
The test-suite failure seems to be due to saturate adding many implications to the context, causing the naive SMT solver in nia to go haywire:

```coq
Require Import ZArith Lia. Local Open Scope Z_scope.
Ltac Zify.zify_convert_to_euclidean_division_equations_flag ::= true.
Goal forall
(x y : Z)
(H : x mod y / y = 0 \/ x mod y / y <> 0)
(H0 : x / y = 0 \/ x / y <> 0)
(H1 : y = 0 \/ y <> 0)
, (x mod y) mod y = x mod y.
Proof.
  intros.
  Time assert_succeeds (assert (y = 0 \/ y < 0 \/ 0 < y) as [|[|]] by nia; nia). (* 0.1s *)
  Time assert_succeeds (clear H0 H1; nia). (* 0.8s *)
  Time assert_succeeds (clear H0; nia). (* 2.4s *)
  zify.
  repeat match goal with H : ?A -> ?B |- _ => idtac A "->" B; revert H end; intros.
  (*
(y = 0) -> (r0 = x)
(y = 0) -> (q0 = 0)
(y < 0) -> (y < r0 <= 0)
(0 < y) -> (0 <= r0 < y)
(y <> 0) -> (x = y * q0 + r0)
(y = 0) -> (r = r0)
(y = 0) -> (q = 0)
(y < 0) -> (y < r <= 0)
(0 < y) -> (0 <= r < y)
(y <> 0) -> (r0 = y * q + r)
(0 <= r0) -> (0 <= y -> 0 <= q)
(0 <= r0) -> (0 <= y -> 0 <= r)
(0 <= x) -> (0 <= y -> 0 <= q0)
(0 <= x) -> (0 <= y -> 0 <= r0)
   *)
  Timeout 10 xnia zchecker. (* Timeout! *)
Qed.
```

@fajb is this the expected behavior for saturate? I was thinking the hypotheses would only be added if the premises were provable without case analysis or similar.

2024-03-02 17:38 UTC, andres-erbsen commented
Looks like we'll need a knob to be able to turn off the saturation for the test suite. My current plan is to add a post hook that clears implication hypotheses named `__sat` (or something similarly hacky) locally in the test-suite file; better suggestions are welcome.

2024-03-05 09:51 UTC, fajb commented
> 
> @fajb is this the expected behavior for saturate? I was thinking the hypotheses would only be added if the premises were provable without case analysis or similar.
> 

A few releases back, that was the case that saturate would only add the conclusion 
if the premises were found in the context. But, that changed after a regression report.

I was aware that this could blow-up. 

Yet, could you explain why this happens now?
I looks like a bad idea to hack the test-suite, this just hides the regression...

2024-03-06 14:50 UTC, fajb commented
Using only known premises by default  looks reasonable.
I suspect there will be a few regressions due to `Saturate Z.pow` but this is probably an acceptable price.
Next question is how to turn the knob: option or Ltac flag ?

2024-03-06 16:26 UTC, andres-erbsen commented
I think a global Vernac flag probably wouldn't do the job for use of lia from tactics. Ltac2 and division handling now use flag packages like [here](https://github.com/coq/coq/pull/17934/commits/1024d79ab34cb487eb456f2dcc796e34c6e49d6d), for which I get the general idea but fail to grok the code. Maybe that's the way to go regardless.

2024-03-06 18:30 UTC, JasonGross commented
> for which I get the general idea but fail to grok the code

To add a new flag:
1. Add the field to the record https://github.com/coq/coq/blob/26fbe83cafff74ed98a8ef1e2f26a853a0ac9812/theories/omega/PreOmega.v#L171-L172
2. Add a default value in Ltac (which can be overridden in a test-suite file, etc, if desired) at https://github.com/coq/coq/blob/26fbe83cafff74ed98a8ef1e2f26a853a0ac9812/theories/omega/PreOmega.v#L173
3. Add the default value to the default record at https://github.com/coq/coq/blob/26fbe83cafff74ed98a8ef1e2f26a853a0ac9812/theories/omega/PreOmega.v#L174-L177
4. Import the field name at https://github.com/coq/coq/blob/26fbe83cafff74ed98a8ef1e2f26a853a0ac9812/theories/omega/PreOmega.v#L217 so that you can
5. Guard your pass as in https://github.com/coq/coq/blob/26fbe83cafff74ed98a8ef1e2f26a853a0ac9812/theories/omega/PreOmega.v#L221

------

Ah, but you are suggesting replicating the code to work for zify in general.  

Let me describe what the code does.

The biggest chunk is a helper method for klidgily implementing record update in Ltac.  The helper method has the spec: given two `constr`s `x` and `y`, excise all subtrees which are evar-free in both terms, and demand that the remaining partial terms unify.
https://github.com/coq/coq/blob/26fbe83cafff74ed98a8ef1e2f26a853a0ac9812/theories/omega/PreOmega.v#L178-L198

This is used to implement record update at
https://github.com/coq/coq/blob/26fbe83cafff74ed98a8ef1e2f26a853a0ac9812/theories/omega/PreOmega.v#L200-L204

Plausibly we should pull this out into a tactics utility file, or even better if we can use Ltac2 in the stdlib we should maybe merge some implementation of the Ltac2 part of coq-record-update into the stdlib (or merge coq-record-update into the stdlib?) and use that.

2024-06-17 02:17 UTC, closed without merging