[experiment] Slightly tweak the interpretation of using clause for eauto tactics.
coq/coq pull request #18909
Opened 2024-04-07 12:52 UTC by ppedrot

We intercept the definition of terms that look like global reference and generate a true global reference instead.

This exposes what is arguably a bug in the interpretation of using clauses, namely that typeclass resolution can be run to fill in some arguments of global references from the using clauses. At least this contradicts the documentation, [which states the following](https://coq.inria.fr/doc/V8.19.0/refman/proofs/automatic-tactics/auto.html?highlight=auto#coq:tacn.auto):
> hints passed through the using clause are used in the same way as if they were passed through a hint database

2024-04-09 16:47 UTC, JasonGross requested changes, later dismissed
For coverage, I think we should add some test that will fail if we revert to the old behavior.

2024-04-09 17:36 UTC, ppedrot commented
@JasonGross I'm not sure I want this into master so far, I'm mostly trying to assess the uses in the CI and fix them. (The test-suite actually captures the change of behaviour so it's mostly a matter of tweaking it.)

2024-04-09 19:14 UTC, JasonGross commented
> The test-suite actually captures the change of behaviour so it's mostly a matter of tweaking it.

The test-suite captures the current behavior, but, if I'm reading correctly, your changes to the test-suite are all backwards compatible and hence the test-suite after these commits will no longer distinguish between the new and old behavior.  Is this correct?  If so, I'm suggesting that, if we do want to merge this PR, we should add a new test that succeeds after this change and is *not* backwards-compatible, i.e., one that fails on the current master.

2024-04-10 08:44 UTC, Janno commented
We (BedRock) also just noticed the problem although our current issue isn't exactly universe polymorphism or resolved implicit variables but rather the fact that our own logging infrastructure does not get access to a name for the hints that end up being `IsConstr` instead of `IsGlobRef`. (`name_of_hint` is used to compute the hint names and returns `None` for `IsConstr`). Universes and resolved implicits will probably become an issue at some point, though.

2024-04-10 10:09 UTC, ppedrot commented
FTR there are still two sources of IsConstr in Coq, these are the using clauses (as in this PR) and the vernacular hint declarations with non-globref terms. The latter triggers a warning but there are still users out there (see #18895). I guess that the next step after this PR is to change the implementation of IsConstr. I was thinking about replacing these with Extern hints, but there are some subtleties involved. Ideally we should just forbid non-globref using clauses and hint declarations, but I'm not sure all users would be happy.

2024-04-14 11:59 UTC, ppedrot commented
This will also require somebody with write access to update sf with the fixed version of tcl. I think @SkySkimmer can do this, am I right?

2024-04-15 07:42 UTC, SkySkimmer commented
cc  @bcpierce00, @liyishuai

2024-04-20 07:21 UTC, ppedrot commented
Ping @bcpierce00 @liyishuai, sf needs a backport of the tlc changes.

Hopefully some variant of this should go into 8.20 and we can get rid of longstanding ugly hint internals in then next version.

2024-04-20 16:35 UTC, liyishuai commented
@ppedrot I've invited you to join the upstream respository of SF, so that you can propose the fix directly. Please review the copyright notice here: https://softwarefoundations.cis.upenn.edu/lf-current/Preface.html#lab17

2024-04-20 20:44 UTC, ppedrot commented
I've read the copyright transfer notice and I agree with it. Should I still send it to @bcpierce00 and sign it with my blood or is it implicit when I start writing the (menial, not copyright-qualifying) fix PR?

2024-04-22 05:55 UTC, liyishuai commented
> I've read the copyright transfer notice and I agree with it. Should I still send it to @bcpierce00 and sign it with my blood or is it implicit when I start writing the (menial, not copyright-qualifying) fix PR?

You may submit the PR immediately. An asynchronous email to Benjamin is still useful for legal purposes.

2024-04-23 06:36 UTC, liyishuai commented
@coqbot run full CI

2024-04-23 12:09 UTC, ppedrot commented
I am undrafting this, as this makes the actual behaviour of the tactic closer to the documentation, while being a step towards the removal of the infamous IsConstr hint kind. In a second PR I'll just make non-global `using` arguments deprecated, but for now this atomic PR is easier to get in.

The test-suite concerns from @JasonGross have been addressed, there is a Fail test with the old code.

2024-05-02 11:57 UTC, SkySkimmer approved these changes

2024-05-02 11:57 UTC, SkySkimmer commented
@coqbot merge now

2024-05-02 11:57 UTC, merged