[8.20] Update compat infrastructure prior to branching
coq/coq pull request #19026
Opened 2024-05-15 09:52 UTC by proux01

In a PR on master, call [dev/tools/update-compat.py](https://github.com/coq/coq/tools/update-compat.py) with the --release flag; this sets up Coq to support three -compat flag arguments including the upcoming one (instead of four). To ensure that CI passes, you will have to decide what to do about all test-suite files that mention -compat U.U or Coq.Compat.CoqUU (which is no longer valid, since we only keep compatibility against the two previous versions), and you may have to ping maintainers of projects that are still relying on the old compatibility flag so that they fix this.

(c.f. https://github.com/coq/coq/issues/18882 )

2024-05-15 16:09 UTC, JasonGross requested changes

2024-05-15 16:09 UTC, JasonGross commented on theories/Compat/AdmitAxiom.v
I don't think we want to be deleting this file, it's a useful tactic that was only removed due to limitations in the proof engine, I believe.

2024-05-15 16:10 UTC, JasonGross commented on theories/Compat/AdmitAxiom.v
(the script should not have removed this file automatically; did it?)

2024-05-15 17:22 UTC, proux01 commented on theories/Compat/AdmitAxiom.v
Well, according to the comment in there it dates back from 8.5 so I wanted to see if it was still use in the CI (answer: it's not outside of bedrock2 and fiat-crypto*).
Anyway, let's keep it.

2024-05-15 18:15 UTC, JasonGross commented on theories/Compat/AdmitAxiom.v
It's a convenience for works in progress, not something that should be used in finished work, so I'm not surprised that it's not used outside bedrock2 and fiat-crypto.  And I guess the use-cases are rare for wanting this particular flavor, rather than the `admit. Admitted.` flavor (which I think now correctly tracks section dependencies, though I'm not sure).  (I think the primary use-case is so that in `Print Assumptions` you can see the shape of the all the goals you've admitted, rather than just the overall theorem statements)

2024-05-17 16:45 UTC, proux01 commented on theories/Compat/AdmitAxiom.v
Ok, thanks for the explanation.

2024-05-17 16:47 UTC, proux01 commented
@silene (8.20 coRM) this is ready

@JasonGross please update your review status

2024-05-17 17:04 UTC, silene commented
I don't understand why you are removing the file `CompatOldOldFlag.v` instead of updating it.

2024-05-17 17:21 UTC, proux01 commented
The script removes it because then it would become identical to `CompatOldFlag.v`

2024-05-17 18:00 UTC, JasonGross approved these changes

2024-05-21 06:43 UTC, silene commented
@coqbot merge now

2024-05-21 06:43 UTC, merged