Export side effects of transparent obligations
coq/coq pull request #19184
Opened 2024-06-08 10:33 UTC by herbelin

Works for interactively built transparent obligations, but not clear that it works as intended for automatically solved obligations (we see `*** [ foo : nat ]`).

- [x] Added / updated **test-suite**.

2024-06-10 12:04 UTC, SkySkimmer commented
>not clear that it works as intended for automatically solved obligations (we see `*** [ foo : nat ]`).

Sounds like https://github.com/coq/coq/issues/13324

2024-06-10 12:05 UTC, SkySkimmer commented on test-suite/success/Abstract.v
> +Print dfoo. (* cfoo = true *)
what's the point of putting Print in non output tests?

2024-06-10 12:09 UTC, SkySkimmer requested changes
I don't think it's correct to just reexport, we need to control the inlining. ie
~~~coq
Program Definition foo : nat := _.
Next Obligation. abstract exact 0 using bar. Defined.
Print foo_obligation_1.
~~~
should print `foo_obligation_1 = bar`

and `Eval cbv in foo` should also print `bar` (in current master it breaks the opacity of abstract and prints `0`).

2024-06-29 06:26 UTC, herbelin commented
> I don't think it's correct to just reexport, we need to control the inlining. ie
> 
> ```coq
> Program Definition foo : nat := _.
> Next Obligation. abstract exact 0 using bar. Defined.
> Print foo_obligation_1.
> ```
> 
> should print `foo_obligation_1 = bar`
> 
> and `Eval cbv in foo` should also print `bar` (in current master it breaks the opacity of abstract and prints `0`).

Am I right or wrong that the inlining done in `Safe_typing.inline_side_effects` is no longer necessary and that we could instead always export?

At least, if we replace inlining by exporting, your example works.

2024-06-29 09:22 UTC, SkySkimmer commented
We probably shouldn't export in the Qed case

2024-06-29 09:39 UTC, herbelin commented
And what do we do in:
```coq
Require Program.
Program Definition foo : nat := _.
Next Obligation. abstract exact 0 using bar. Qed.
```
The abstracted proof being named, should it be exported?

2024-06-29 09:41 UTC, herbelin commented on test-suite/success/Abstract.v
> +Print dfoo. (* cfoo = true *)
To test whether the abstracted proof was exported in the global environment.

A test of the form `Check eq_refl : dfoo = true` might be better though.

2024-06-29 09:45 UTC, SkySkimmer commented
no

2024-06-29 11:43 UTC, herbelin commented
I committed a new version, but it is not fully satisfactory:
- some choices about when to inline/export look a bit arbitrary (e.g. what to do when solving automatically and producing a transparent body, as in the `cfoo` example of the test `Abstract.v`?),
- the choice to inline/export should morally be made at the same time while currently inlining is done early and exporting is done at `declare_constant` time (but coq/ceps#89 should help moving inlining closer to `declare_constant`).

Related to the automatic solving question, is it clear that we want `build_by_tactic` to always inline its side effects (even schemes and named `abstract`, and even when the term is used in a transparent proof)? That would not be difficult to otherwise explicitly returns the effects and ask the callers of `build_by_tactic` to take a decision themselves.

2024-12-11 02:31 UTC, closed without merging