prove UIP_None in Eqdep_dec
coq/coq pull request #19483
Opened 2024-08-30 16:16 UTC by andres-erbsen

This is a standard hott-style proof that is sometimes useful in non-hott work when `x = None` appears as an argument to a dependently typed function. It is also a relatively self-contained example about how to prove UIP for decidable cases of a type that does not necessarily have decidable equality.

- [x] Added **changelog**.

2024-08-30 16:44 UTC, SkySkimmer requested changes, later dismissed
I don't think this is useful, we already have `eq_proof_unicity_on` (ie
~~~coq
Require Import Eqdep_dec.

Lemma UIP_None {A} (x : option A) (p1 p2 : x = None) : p1 = p2.
Proof.
  apply eq_proofs_unicity_on.
  intros [|];constructor;congruence.
Qed.
~~~
)

2024-08-30 16:46 UTC, SkySkimmer commented
(I know the file already has non-generalized proofs for unit / bool / nat but TBH I don't think that's the appropriate place for them, it should be in some example doc not in stdlib)

2024-08-30 17:49 UTC, andres-erbsen commented
Thank you for pointing out that we have the general case already. Still, I'd like to add the None instance somewhere so that it shows up in search. If not in Eqdep_dec, then where?

2024-08-30 19:00 UTC, SkySkimmer commented
I object more to doing a from-scratch proof than to having the lemma. If you want it, use the general eq_proofs_unicity_on lemma to prove it.

2024-08-30 19:05 UTC, andres-erbsen commented
So would an instantiation of the general lemma in the same file be fine by you? (Or where else?)

2024-08-30 19:32 UTC, SkySkimmer commented
yes in this file

2024-09-02 12:36 UTC, gares commented on theories/Logic/Eqdep_dec.v
> +Lemma UIP_None {A} (x : option A) (p1 p2 : x = None) : p1 = p2.
May I suggest: `UIP_None_None`, `UIP_None_x`, UIP_x_None` instead?
We have a similar convention in math-comp.

2024-09-04 12:03 UTC, andres-erbsen commented on theories/Logic/Eqdep_dec.v
> +Lemma UIP_None {A} (x : option A) (p1 p2 : x = None) : p1 = p2.
Thank you for the suggestion, I agree a change would be good. Another option I am now contemplating is `UIP_None_None`, `UIP_None_l`, `UIP_None_r` -- this looks similar to stdlib conventions, except UIP isn't actually the head symbol of the lemma. But the lemmas match that idea conceptually, e.g. if we were to define `UIP [T : Type] (x y : T) := forall p1 p2 : x = y, p1 = p2` naming them using `_l` and `_r` would be exactly what I expect in stdlib. This is not the same definition as proposed [here](https://github.com/coq/coq/pull/18671/files#diff-945d779c82bcb763e8e542a931f971fa2fe98176b948848992409407080d25eaR46) though. Wdyt?

2024-09-05 20:55 UTC, andres-erbsen commented
@coqbot run full ci

2024-09-06 03:16 UTC, andres-erbsen commented
I have addressed the comments and the CI is green. Please merge.

2024-09-19 08:23 UTC, proux01 approved these changes

2024-09-19 08:24 UTC, proux01 commented
Will merge next week if there are no further comments.

2024-09-23 09:16 UTC, merged