Use the release Dune profile when running `configure` during opam package installation
coq/coq pull request #19805
Opened 2024-11-04 14:40 UTC by dra27

Spotted while doing some testing for opam-repository w.r.t. old(er) Coq releases and the `effect` keyword. In the opam files for Coq's packages, the `dune build` is always correctly `dune build -p ...`. Amongst other things, `-p` enables the release profile which disables warnings as errors.

The `configure` script contains a `dune exec` call which should also be enabling the release profile when executing as part of a package build. This minor tweak takes advantage of the fact that opam defines `OPAM_PACKAGE_NAME` and `OPAM_PACKAGE_VERSION` strictly during the building of a package, and uses that to add `--profile=release` to the `dune exec` call.

2024-11-12 16:22 UTC, ejgallego commented
Thanks @rlepigre !

I'd swear we had fixed this, because indeed we had observed re-compilation due to this; my head is a big foggy right now, I'll try to think about this tomorrow to see if I can recall what we did last time we found this issue.

2024-11-12 16:25 UTC, ejgallego commented
Oh never mind, I recall now. The problem was not configure, but in the generation of `dune` files via `make dunestrap` cc: #18287

2024-11-12 16:25 UTC, SkySkimmer commented
It could also make sense to always use release profile when calling configure through this wrapper script

2024-11-14 15:42 UTC, SkySkimmer commented
>By the way, I think I prefer the fix were we pass the mode from the opam file

yes

2024-11-15 15:27 UTC, ejgallego requested changes
Thanks a lot for the fix, we'd prefer if we could add this variable to the call to configure in the opam file itself, see how we do for other options.

2025-01-11 13:27 UTC, ppedrot commented
This PR is part of the 9.0+rc1 milestone. This is a fix so it can be backported into the rc after the branch, but ideally this PR should be merged *before* the branch expected to occur next Tuesday. To whomever is involved, please act accordingly.

2025-01-16 14:14 UTC, SkySkimmer commented
I think your push is what was wanted indeed.

2025-01-16 14:33 UTC, ejgallego approved these changes
That's exactly what we meant, thanks a lot @dra27 !

2025-01-16 14:33 UTC, ejgallego commented
@SkySkimmer should we run full-ci ? I'd think no.

2025-01-16 14:40 UTC, SkySkimmer commented
We could if we worry about the pkd:opam job but probably no point

2025-01-16 16:25 UTC, ejgallego commented
Actually indeed we had a bug, so let's rebase, squash, and fix, and build the opam job.

2025-01-16 16:35 UTC, SkySkimmer commented
Indeed the opam.template files need fixing

2025-01-16 20:47 UTC, dra27 commented
Oops, how silly of me not to spot the .opam.template files 🤦 Hopefully all correct this time!

2025-01-17 14:57 UTC, ejgallego commented
@coqbot: merge now

Thanks again @dra27 !

2025-01-17 14:57 UTC, merged