Add relocatable mode
coq/coq pull request #19901
Opened 2024-12-05 14:11 UTC by SkySkimmer

Fix https://github.com/coq/coq/issues/19900

2024-12-05 14:35 UTC, SkySkimmer commented
doc is failing because it's calling `coqdoc` from PATH (so Sys.argv.(0) = "coqdoc") which is _build/install/default/bin/coqdoc but that file is a symlink to _build/default//tools/coqdoc/main.exe so Sys.executable_name is that.

2024-12-05 16:32 UTC, SkySkimmer commented on boot/util.ml
> +  (* avoid following symlinks if possible (Sys.executable_name followed symlinks) *)
not sure if this is the right way to work
maybe we should be following symlinks and special case when they point in the dune build layout?

2024-12-05 16:32 UTC, andres-erbsen commented
Why is this optional, and seemingly exclusive with -prefix? Having the build tooling install coq to some location shouldn't mean it cannot be relocated later. (I realize I'm probably missing some constraint on the design here.)

2024-12-05 16:34 UTC, SkySkimmer commented
configure -prefix tells coq where to expect to find its stuff, it is not used to tell dune where to install coq

2024-12-05 16:37 UTC, andres-erbsen commented
Ah, that makes more sense. But a build with -prefix could still work if the entire prefix is moved? Or is it somehow specifically important for these paths to be absolute?

2024-12-05 17:34 UTC, SkySkimmer commented
If relative they would be relative to the directory from which coq is called, not very useful behaviour

2024-12-05 17:43 UTC, andres-erbsen commented
Why is relative to coqc not a useful behavior? What is the use case?

2024-12-05 19:35 UTC, SkySkimmer commented
The easy way to interpret relative paths is relative to $PWD not anything using coqc

2024-12-06 08:25 UTC, rlepigre commented
> The easy way to interpret relative paths is relative to $PWD not anything using coqc

I believe that I have seen the trick of using the path to the executable to deduce derived paths somewhere, and it seems to me like a reasonable approach (but I might be missing something). Of course, this requires a consistent installation layout, so only the prefix can be changed (not where the binaries are installed under the prefix for example). Under this constraint, for any Coq executable to find the library path, it could first obtain the directory it lives in, and then append to it something like `../lib/coq-core` for example.

2024-12-06 10:25 UTC, SkySkimmer commented
That's just the relocatable mode. What I don't understand is what it would mean to have both -prefix and -relocatable.

2024-12-06 10:39 UTC, ejgallego commented
Can we document this mode a little bit more @SkySkimmer ? Maybe in `dev/doc`?

I think we should have a spec of how is this mode supposed to work in addition to the code.

2024-12-06 11:07 UTC, rlepigre commented
> That's just the relocatable mode. What I don't understand is what it would mean to have both -prefix and -relocatable.

OK, I have not looked at the code very closely, I thought you were arguing against this approach.

From my point of view, the relocatable mode should be the default, and `-prefix` should probably not exist. The choice of the installation prefix should be left to the build system, and the particular choice should probably not be depended on in the code.

2024-12-06 11:13 UTC, ejgallego commented
Note that the original restriction of `-prefix` being an absolute path was due to makefile hell in the test suite, it was just not practical to do all the path shifting in make.

We used to have "the local" mode also, but that's now replaced by the `_build/install` layout which is more uniform w.r.t. install locations.

@rlepigre , I hear you. I suggest we indeed write down the spec of this mode in some doc first, so we can try to understand all the possible modes and what the implications are. As they say, in my experience, the devil is in the details.

2025-01-09 17:06 UTC, SkySkimmer commented
Doesn't quite work because we need to relocate paths from `rocq` and `rocqworker` which exist in different locations

2025-01-10 16:45 UTC, SkySkimmer commented
Opened https://github.com/coq/coq/pull/20013 with just the preliminary cleanups

2025-01-15 14:05 UTC, SkySkimmer commented
may be working now, let's see CI

2025-01-16 12:58 UTC, SkySkimmer commented
Not sure how well this works, notably the overlay for coq_lsp needs to look for `rocq` in PATH since the coq_lsp executable while running CI is not next to the rocq executable and so has no way to locate Rocq's directories without finding the rocq executable.

2025-01-16 13:10 UTC, ejgallego requested changes, later dismissed
I think this should be documented, so we can check the specification matches the code.

Either the reference manual or dev/doc/build would work for me.

2025-01-16 13:11 UTC, ejgallego commented
> Not sure how well this works, notably the overlay for coq_lsp needs to look for `rocq` in PATH since the coq_lsp executable while running CI is not next to the rocq executable and so has no way to locate Rocq's directories without finding the rocq executable.

I'll be happy to make it work for coq-lsp, however I'd like we have a little spec in the documentation, otherwise is very hard to guess what the intent of the code is.

2025-01-16 13:12 UTC, ejgallego commented
@SkySkimmer as noted in the overlay, I'm happy to take care of that client side in coq-lsp, so we can just update the type we use there of coq-lib and I will have coq-lsp follow the spec we document here.

Would be great to share more code, but we can do that in a second phase, there are some more advanced features that we try to support there w.r.t. workspace config.

2025-02-14 17:17 UTC, Janno commented
What is the status of this PR? It could save our team hours per week per person. I would really love for it to be merged soon.

2025-02-17 15:19 UTC, SkySkimmer commented
I think the doc I put in the refman is accurate, but the code could stand to be cleaned up so that it is clearer that it matches with its description. 

For instance IIUC if an absolute configure -libdir is used, we get its value at https://github.com/coq/coq/blob/16d7350de90f7f7fa9fad1c29895341d41df16ea/boot/env.ml#L79 and if the prelude doesn't exist there we go in the other branch of check_file_else which will return the same thing.
So the code looks like there are 2 paths for absolute libdir but they're equivalent.

2025-02-18 11:28 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +
Maybe worth saying something like "unless -boot, Rocq acts as though the command line arguments included `-R $libdir/theories Corelib -Q $libdir/user-contrib ""`"

2025-02-24 15:46 UTC, ejgallego commented on doc/sphinx/practical-tools/coq-commands.rst
> +
I'd be great to actually specify / document that indeed.

2025-02-24 15:51 UTC, ejgallego commented on doc/sphinx/practical-tools/coq-commands.rst
> +cannot find certain expected files (except for subcommands like
Maybe we should document which files too?

2025-02-24 15:54 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +
I did add it below (line 130)

2025-02-24 15:55 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +cannot find certain expected files (except for subcommands like
That's what the rest of this section does (mostly it's the Prelude.vo)

2025-02-24 15:56 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +Unless `-boot` was passed, Rocq acts as though `-R $libdir/theories
It's still -R AFAICT

2025-02-24 16:00 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +Unless `-boot` was passed, Rocq acts as though `-R $libdir/theories
https://github.com/coq/coq/blob/ec2f1325b513ba9540f4a93e80a8d59d32bd08a4/sysinit/coqloadpath.ml#L17 
`implicit` means -R

2025-02-24 16:08 UTC, ejgallego commented on boot/env.ml
> +   XXX we should be using -boot in build layout so is that dead code? *)
The whole stuff about coqcorelib and plugins should go away and instead ocamlfind be queried, I think, also I am not sure the code that adds the plugins_dir to `ocamlfind` should be kept.

Both changes shouldn't go here tho.

2025-02-24 16:10 UTC, ejgallego commented on doc/sphinx/practical-tools/coq-commands.rst
> +
I'm not sure we need `runtimelib`, IIRC you locate the worker using OCAMLPATH? There is some interaction with OCAMLPATH here that we should document right?

2025-02-24 16:13 UTC, ejgallego commented on config/dune
> +  (env_var PWD))
Why do we need this here?

2025-02-24 16:13 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +
The process goes like

- (in rocq.exe) add -I $runtimelib (unless -boot)
- (in rocq.exe) locate worker in findlib rocq-runtime dir
- call worker
- (in worker) add -I $runtimelib (unless -boot)
- (in worker) locate plugins as needed (unless -noinit this will need rocq-runtime to be located by findlib)

2025-02-24 16:15 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +
also it's actually adding $runtimelib/.. as there doesn't seem to be a way to just add $runtimelib containing META and have it work (since findlib gets the package name from the directory name)

2025-02-24 16:23 UTC, ejgallego commented on doc/sphinx/practical-tools/coq-commands.rst
> +
Yes, my point is that we already call rocq.exe with the right `OCAMLPATH`, so maybe we should avoid setting it twice? (findlib is kinda `O(length(OCAMLPATH))` which is not good, I also recall seeing warnings of duplicated entries?

I guess the main case to do `-I $runtimelib` is to help stuff like in #15663 (see also #17158, which I think you fix in this PR?) where the users don't want to set ocamlpath but do `/path/to/rocq.exe ....`

I guess we may not see the duplicate path bug so easily as we always call rocq with `-boot`, but it wouldn't hurt to double check the directory is not double-added in other settings.

2025-02-24 16:24 UTC, ejgallego commented on boot/env.ml
> +   XXX we should be using -boot in build layout so is that dead code? *)
I mean we are still passing `-I runtimelib` even if most of the time is already in `OCAMLPATH`

2025-02-24 16:24 UTC, ejgallego commented on doc/sphinx/practical-tools/coq-commands.rst
> +
I can actually test this easy, one sec.

2025-02-24 16:24 UTC, SkySkimmer commented on dev/ci/scripts/ci-coq_lsp.sh
> +fi
we can see in this ci script (and the one for vscoq) that executables not installed in a shared layout with rocq need to be told where to find rocq
this is guarded to GITLAB_CI because ci-common when not GITLAB_CI already exports ROCQLIB/ROCQRUNTIMELIB

2025-02-24 16:33 UTC, ejgallego commented on boot/util.ml
> +  (* avoid following symlinks if possible (Sys.executable_name followed symlinks) *)
Whether to follow symlinks or not is a hard question. I tend to think that we should not follow symlinks, but there are some (IMHO marginal) use cases.

2025-02-24 16:33 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +
>findlib is kinda O(length(OCAMLPATH)) which is not good

We only add +1 to that though, unlike when we added arbitrary amounts of user-contrib or whatever paths

Adding -I $runtimelib means we can install Rocq in a non findlib path and it will still work 
#15663 can be considered part of it
also #15607

2025-02-24 16:41 UTC, ejgallego commented
> What is the status of this PR? It could save our team hours per week per person. I would really love for it to be merged soon.

@Janno , did you already test this PR to see if it works in your use case?

2025-02-24 16:46 UTC, ejgallego commented on doc/sphinx/practical-tools/coq-commands.rst
> +
Indeed this is what we get on master:

```
$ _build/install/default/bin/rocq c k.v
OCAMLPATH:
  /home/egallego/external/coq-master/_build/default/./../install/default/lib/coq/../rocq-runtime/..
  /home/egallego/.opam/coq-v8.20/lib
...

# simulate install env
$ dune exec -- _build/install/default/bin/rocq c k.v
OCAMLPATH: 
  /home/egallego/external/coq-master/_build/default/./../install/default/lib/coq/../rocq-runtime/..
  /home/egallego/external/coq-master/_build/install/default/lib
  /home/egallego/.opam/coq-v8.20/lib
...
```
gonna test with this PR.

2025-02-24 16:49 UTC, ejgallego commented on doc/sphinx/practical-tools/coq-commands.rst
> +
With this PR:
```
$ _build/install/default/bin/rocq c k.v
OCAMLPATH:
 /home/egallego/external/coq-master/_build/install/default/lib/coq/../rocq-runtime/..
 /home/egallego/.opam/coq-v8.20/lib

$ dune exec -- _build/install/default/bin/rocq c k.v
OCAMLPATH:
 /home/egallego/external/coq-master/_build/install/default/lib/coq/../rocq-runtime/..
 /home/egallego/external/coq-master/_build/install/default/lib
 /home/egallego/.opam/coq-v8.20/lib
```
IMHO not a big deal but something to cleanup.

2025-02-24 16:55 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +
I don't have access, but I use the first case personally

2025-02-24 17:20 UTC, ejgallego commented on dev/ci/scripts/ci-coq_lsp.sh
> +fi
> IDK if it can be considered a bug

Seems so to me, I'll fix it on my side and update the CI code.

2025-02-25 13:34 UTC, Janno commented
> @Janno , did you already test this PR to see if it works in your use case?

I was waiting for things to settle. I just tried it and, as hoped, it does completely fix our problem. With this change we can create new git worktrees for rocq and our entire composed build hits the dune cache. I can't emphasize how much time this will save us. Ever since we moved rocq into our workspace (to be able to rely on patches that haven't been merged yet) our worktree-based workflow basically meant a 30min-1hr recompilation penalty for new feature branches just because rocq was now located in a different directory.

2025-02-25 14:37 UTC, ejgallego commented
@Janno , thanks for confirming, from discussion with you folks I was under the impression that the only problem you were having was the absolute path changing the checksum of the coq_config.cmx file, right?

I now realize that there may be a workaround for older Coq versions, just set the same path in `./configure` maybe to something like `/this/path/does/not/exist/in/purpose`.

Then, set `COQLIB` to the right place as an environment variable, tho note that this variable has little effect if you are using a fully composed build (`dune` will also override it)

2025-02-25 14:51 UTC, Janno commented
AFAICT there are `_build/default/coq/config/coq_config.ml` and `_build/default/coq/revision`. Both contain references to the absolute path. I am not sure if `revision` is used. I suspect it is not affected by `./configure`.

In any case, is there any reason not to merge this PR here and simply rely on that?

2025-02-25 15:03 UTC, SkySkimmer commented
I think it's ready to merge, we need users to find bugs now

2025-02-25 17:40 UTC, SkySkimmer commented
@coqbot bench

2025-02-26 13:01 UTC, ejgallego commented on doc/sphinx/practical-tools/coq-commands.rst
> +
@SkySkimmer maybe you'd like to close the two issues I linked above in the changelog here too.

2025-02-26 14:23 UTC, SkySkimmer commented on doc/sphinx/practical-tools/coq-commands.rst
> +
I set #17158 to auto close (no changelog though, I don't think we do changelog for this kind of missing doc issue).
Not sure if #15663 can be considered fixed by this, I'd rather ask the reporter to have a look again after merge.

2025-03-12 11:34 UTC, SkySkimmer commented
@coqbot run full ci

2025-03-12 13:36 UTC, SkySkimmer commented
Not sure what dune is doing, we see `Sys.argv.(0) = _build/install/default/bin/rocq` and `Sys.getcwd() = /path/to/user-contrib`.

2025-03-12 13:40 UTC, SkySkimmer commented on boot/env.ml
> +  if Filename.basename Sys.argv.(0) <> Sys.argv.(0) then
(about `cd user-contrib && dune exec`)
We could add a file_exists check here, but then find_in_PATH fails so we use executable_name which follows symlinks into the build layout, so we would need to understand the build layout.
Maybe in a followup PR but for now I'd rather get this merged.

2025-03-12 14:32 UTC, Janno commented on boot/env.ml
> +  if Filename.basename Sys.argv.(0) <> Sys.argv.(0) then
FWIW I now suspect this is actually a dune bug. I filed https://github.com/ocaml/dune/issues/11527. AFAICT `argv.(0)` is not *guaranteed* to actually contain a useful value but there's no reason to not pass a useful path if it exists.

2025-03-12 15:17 UTC, ejgallego commented
> > That's a bit strange @Janno , what's the diff between `dune show contexts --verbose` and `cd user-contrib && dune show contexts --verbose` ?
> 
> Let's discuss in [ocaml/dune#11527](https://github.com/ocaml/dune/issues/11527)

Ok, but please post the results for this Rocq example too, I feel that there may be several issues at play here, one specific to Rocq setup.

2025-03-12 15:23 UTC, Janno commented
AFAICT there is no difference except for one extra line of `Entering directory '/home/janno/src/coq'` in the second case.

<details><summary>Outputs</summary>

```
$ dune show contexts --verbose
Shared cache: enabled
Shared cache location: /home/janno/.cache/dune/db
Workspace root: /home/janno/src/coq
Auto-detected concurrency: 12
Dune context:
 { name = "default"
 ; kind = "default"
 ; profile = Dev
 ; merlin = true
 ; fdo_target_exe = None
 ; build_dir = In_build_dir "default"
 ; instrument_with = []
 }
Scanned 300 directoriesdefault
```

```
$ cd user-contrib && dune show contexts --verbose
Entering directory '/home/janno/src/coq'
Shared cache: enabled
Shared cache location: /home/janno/.cache/dune/db
Workspace root: /home/janno/src/coq
Auto-detected concurrency: 12
Dune context:
 { name = "default"
 ; kind = "default"
 ; profile = Dev
 ; merlin = true
 ; fdo_target_exe = None
 ; build_dir = In_build_dir "default"
 ; instrument_with = []
 }
Scanned 300 directoriesdefault
```

</summary>

2025-03-17 10:00 UTC, ppedrot commented
If nobody complains I'll merge this soon.

2025-03-17 10:00 UTC, ppedrot approved these changes

2025-03-18 15:16 UTC, andres-erbsen commented
I tested it with build, mv, coqtop, 1+1 and it worked for me. :tada: :raised_hands:

2025-03-18 19:32 UTC, ejgallego commented
@ppedrot as I told Gaëtan by private message this is ready IMHO

2025-03-18 21:06 UTC, ppedrot commented
All right, no reason to postpone this then. @coqbot merge now

2025-03-18 21:06 UTC, merged

2025-03-28 15:05 UTC, Zimmi48 commented
@SkySkimmer Great stuff! I think the new `-relocatable` configure option would have deserved to be advertised in a changelog entry.