CI: upload _install_ci instead of _build_ci
coq/coq pull request #19925
Opened 2024-12-12 13:07 UTC by SkySkimmer

This means we shouldn't run dependencies of the current job, so we stop going through Makefile.ci.

Also remove duplicated transitive deps.

Probably won't work on jobs like elpi_test which expect to run in the build dir of its dependencies, but let's see how it does for the rest.

2024-12-16 13:56 UTC, SkySkimmer commented
@coqbot run full ci

2024-12-17 16:19 UTC, SkySkimmer commented
This works by also uploading _build_ci (by setting SAVE_BUILD_CI) for a few jobs (eg equations because equations_test expects to run in equations's build dir). 
Also jobs which run multiple ci-* scripts (eg elpi_hb) need to list them in CI_TARGETS instead of just having the job name as a target in Makefile.ci which depends on the others.

Benefits:
- less artifacts (3.69GiB -> 2.58GiB / pipeline)
- cleaner logs as we don't get the install step of dependencies
- enforces that dependencies are correct in the gitlab-ci.yml instead of silently recompiling them

Costs:
- the minimizer will need adapting (cc @JasonGross) and I guess will be slower when the error is in a non SAVE_BUILD_CI job
- slight added complexity for jobs which need SAVE_BUILD_CI 
- slight added complexity for jobs which need CI_TARGETS

We need to decide on if it's worth merging, with the minimizer being the main issue.
(it's not urgent so if we decide to merge we should wait for the minimizer to be adapted)

2025-02-11 13:02 UTC, SkySkimmer commented
>Once coq/bot#332 is taken care of, though, the only adaptation needed here, I believe, is to change https://github.com/coq-community/run-coq-bug-minimizer/blob/5b224ccb46d02714ae9bf9c42c238800f604be6a/coqbot-ci.sh#L85 and https://github.com/coq-community/run-coq-bug-minimizer/blob/5b224ccb46d02714ae9bf9c42c238800f604be6a/coqbot-ci.sh#L93; what should make -f Makefile.ci GITLAB_CI=1 ${CI_TARGET} be replaced with?

it is replaced by `for target in $CI_TARGETS; do GITLAB_CI=1 dev/ci/ci-wrapper.sh "$target"; done`
with CI_TARGETS defaulting to the part after ci- (eg `hott` for `ci-hott`)

2025-02-18 12:36 UTC, SkySkimmer commented
Recent other pipeline https://gitlab.inria.fr/coq/coq/-/jobs/5337893 3.44GiB total
This PR https://gitlab.inria.fr/coq/coq/-/jobs/5338165 2.37GiB total

2025-02-18 12:38 UTC, SkySkimmer commented
@coq/ci-maintainers I think this is worth merging, can I get an assignee?

2025-02-24 13:03 UTC, proux01 commented on .gitlab-ci.yml
>  plugin:ci-autosubst_ocaml:
Apparently not (i.e., compiles fine locally without Stdlib)

2025-02-25 15:55 UTC, SkySkimmer commented
@JasonGross is there a way to fix the minimizer before merging this or do we have to merge first?

2025-02-25 16:21 UTC, JasonGross commented
I believe the changes above are backwards compatible, and we also need to do the same "if the saved build ci folder exists, move it" dance that is done here in https://github.com/coq-community/run-coq-bug-minimizer/blob/5b224ccb46d02714ae9bf9c42c238800f604be6a/coqbot-ci.sh#L42 and the loop a bit further down.  Let's please get the changes into the minimizer runner before merging this.

2025-02-25 17:28 UTC, SkySkimmer commented
Can you prepare a PR?

2025-02-25 23:09 UTC, JasonGross commented
Yes, I will aim to do that by the end of the week, please ping me again on Friday if I haven't managed it by then.  (Also feel free to prepare a PR yourself)

Has coqbot been updated yet to ensure the information about `CI_TARGETS` is set/available to the minimizer?

2025-02-26 12:06 UTC, SkySkimmer commented
>Has coqbot been updated yet to ensure the information about CI_TARGETS (rather than just CI_TARGET) is set/available to the minimizer?

I don't think so

2025-02-28 16:29 UTC, JasonGross commented
I think we need to add a target to `Makefile.ci` that allows printing the dependencies of a ci target, e.g., `make print-ci-deps CI_TARGET=ci-foo` or `make print-ci-foo-deps`.  Do you have an idea about how to do this?  Do we need to parse `.gitlab.yml` or something?  (It's fine to print only direct dependencies and have the runner invoke the targets recursively to get recursive deps.)

2025-02-28 16:31 UTC, SkySkimmer commented
What for?

2025-02-28 16:48 UTC, JasonGross commented
Perhaps I was misremembering

> > what should make -f Makefile.ci GITLAB_CI=1 ${CI_TARGET} be replaced with?
> 
> it is replaced by `for target in $CI_TARGETS; do GITLAB_CI=1 dev/ci/ci-wrapper.sh "$target"; done` with CI_TARGETS defaulting to the part after ci- (eg `hott` for `ci-hott`)

I was assuming this meant that we need to invoke the wrapper for multiple targets, but it sounds like I'm wrong.  I guess we need to make the change with _saved_build_ci (can be merged before this PR), and then need to make this change to build via the CI wrapper (should be merged synchronously with this PR).  It would be possible to do in a backwards compatible way, but this requires first adding targets to Makefile.ci that are "ci-foo-from-artifact" which copies the dependencies of ci-foo on master and then is changed in this PR, which seems not worth it

2025-03-01 04:51 UTC, JasonGross commented
PR prepared at https://github.com/coq-community/run-coq-bug-minimizer/pull/39

2025-03-01 15:08 UTC, JasonGross requested changes
Please make the CI_TARGETS associated to a job easily programmatically available

2025-03-12 03:02 UTC, JasonGross approved these changes

2025-03-12 03:02 UTC, JasonGross commented
@coqbot merge now

2025-03-12 03:02 UTC, merged