Univs: fix bug #4180
coq/coq pull request #377
Opened 2016-11-28 17:42 UTC by mattam82

UnivInconsistency in infer_conv can be backtracked on (due to unfolding
heuristic).

2016-11-29 06:30 UTC, silene commented
It seems like it is falling in the trivial-bugfix category. Are you expecting something specific from a review?

2016-11-29 07:12 UTC, maximedenes commented
Just a note: I guess opening a PR is still good practice, because we want to test the fix, and we tend to forget to merge :) But we could indicate if we are expecting a review or not (there is a "needs_review" label, though).

2016-11-29 08:19 UTC, mattam82 commented
Indeed it's not really up for review, just to check and not forget about it :) Here's the ci job: https://ci.inria.fr/coq/view/coq-contribs/job/coq-contribs/614/console

2016-11-29 15:20 UTC, mattam82 commented
I'm slightly worried about timing with this one, it seems math-comp took a small hit, overall the contribs took 10 min more than for #378 ... Any idea how to test this precisely, @ppedrot maybe?

2016-11-29 15:20 UTC, mattam82 commented
Note however that it really fixes a bug.

2016-11-29 15:34 UTC, JasonGross requested changes

2016-11-29 15:34 UTC, JasonGross commented on test-suite/bugs/closed/5180.v
> +Fail Definition lift' {n} : TypeOfTypei' (Typei n) -> TypeOfTypei' (Typei (S n))
This should be `Definition lift''`, not `Fail Definition lift'`

2016-11-29 15:34 UTC, JasonGross commented on test-suite/bugs/closed/5180.v
> +  exact x. (* The command has indeed failed with message:
Shouldn't there be an `Undo` after this line?

2016-11-29 15:56 UTC, ppedrot commented
@mattam82 As of today there is no simple way to do per-contrib timing, and that's a real issue. I've been repeatedly asking for this for a while, but maybe the new bench infrastructure promised by @maximedenes is going to provide this?

2016-11-30 10:15 UTC, mattam82 commented on test-suite/bugs/closed/5180.v
> +Fail Definition lift' {n} : TypeOfTypei' (Typei n) -> TypeOfTypei' (Typei (S n))
Ok

2016-11-30 10:15 UTC, mattam82 commented on test-suite/bugs/closed/5180.v
> +  exact x. (* The command has indeed failed with message:
Right, both work and I didn't realize it.

2016-11-30 10:20 UTC, mattam82 commented
Fixed the test-suite file according to @JasonGross comments

2016-11-30 12:02 UTC, maximedenes commented
Matej and I started to work on a new benchmark suite tracking timings. However, the first experiments seem to show that it is not so easy to measure precise timings when the machine can be under CPU load from other sources. Matej will make a status report during the working group.

2016-11-30 14:47 UTC, mattam82 commented
Trying again with better fix: https://ci.inria.fr/coq/view/coq-contribs/job/coq-contribs/620/console

2016-12-02 17:01 UTC, merged