Univs: fix bug #5188
coq/coq pull request #378
Opened 2016-11-28 18:06 UTC by mattam82

Parameter was implemented the wrong way trying to separate the universes
of the telescope.

2016-11-29 08:51 UTC, mattam82 commented
Updated commit, it was missing a nf_constraints

2016-11-29 08:52 UTC, mattam82 commented
https://ci.inria.fr/coq/view/coq-contribs/job/coq-contribs/615/console

2016-11-29 15:19 UTC, mattam82 commented
Seems ok to me.

2016-11-29 15:32 UTC, JasonGross requested changes

2016-11-29 15:32 UTC, JasonGross commented on test-suite/bugs/closed/5188.v
> +Print Universes.
Presumably this should either go in output/, or there should be a comment about what we should see here and from `Inspect 5`.  (What does `Inspect` do?)

2016-11-30 10:15 UTC, mattam82 commented on test-suite/bugs/closed/5188.v
> +Print Universes.
It's a spurious line.

2016-12-02 14:58 UTC, maximedenes commented
Could this PR ship with a least a few comments in the code? It is as hard to know what the code does now as it was before. So how do we know it got more correct, and not less? :)

2016-12-02 15:47 UTC, mattam82 commented
I added a few comments and removed the spurious code in the test-suite.

2016-12-02 15:49 UTC, maximedenes commented
Thanks!

2016-12-04 11:17 UTC, merged