Proposing improvement to the CI targets for local use
coq/coq pull request #456
Opened 2017-03-07 11:56 UTC by Zimmi48

I was delighted to hear that it is possible to take advantage of the CI targets on a local machine (example: `make ci-coquelicot`). But I have been observing a few problems with the current configuration (which was thought mainly to build on Travis servers).

A first problem is that if the build encounters an error (for instance I forget to build Coq before, or I don't have the autoconf package installed on my machine in the case of Coquelicot), I can't just relaunch `make ci-coquelicot` because `git clone` will now fail since the clones already exist. This is solved by checking if the folder exist, and by doing `git pull` just to make sure the clone is up-to-date. It has the inconvenient that if the base branch or link changes, it will go unnoticed. In case this info is updated, the easy solution is `rm _build_ci` (see next paragraph).

Another problem is the polluting of the main folder. This is solved by moving the cloning into a `_build_ci` folder.

A third problem was the use of `#!/bin/bash`. I changed it to `#!/bin/sh` instead, because my Linux distribution (NixOS) does not have `/bin/bash`. If this is a problem (because the scripts are relying on specific Bash features), I can instead change it to `#!/bin/env bash`.

2017-03-07 14:37 UTC, ejgallego commented
Thanks for the PR, a few questions:

> A third problem was the use of #!/bin/bash. I changed it to #!/bin/sh instead, because my Linux distribution (NixOS) does not have /bin/bash. If this is a problem (because the scripts are relying on specific Bash features), I can instead change it to #!/bin/env bash

I would rather prefer we use a concrete shell, `/bin/sh` may wildy vary between configurations and produce hard-to-track errors (like Travis may use `dash` others may use `bash` etc...).

I have no clue about what `/bin/env` is supposed to do, other than in my distro it is called `/usr/bin/env`. I would be fine with such a change once we figure out why the discrepancy in paths.

> Another problem is the polluting of the main folder. This is solved by moving the cloning into a _build_ci folder.

Please make this into a variable.

2017-03-07 14:41 UTC, ejgallego commented
> I have no clue about what /bin/env is supposed to do, other than in my distro it is called /usr/bin/env. I would be fine with such a change once we figure out why the discrepancy in paths.

Ok it seems that `/usr/bin/env` is the FHS-sanctioned location.

2017-03-07 14:46 UTC, ejgallego requested changes
- Update to `/usr/bin/env bash`
- Make build dir a variable.

2017-03-07 14:50 UTC, Zimmi48 commented
Thanks @ejgallego for your comment. Indeed, on my distrib too, it is `/usr/bin/env` (it is in fact the only command in `/usr/bin`, while `sh` is the only command in `/bin`).

2017-03-07 15:17 UTC, Zimmi48 commented
Done. Note that I made the build dir a variable but still had to hard-code it into `.gitignore`.

2017-03-07 17:04 UTC, ejgallego commented
> Note that I made the build dir a variable but still had to hard-code it into .gitignore.

That should work, the variable is in case somebody wants to redirect the dir with `make BUILD_CI=...`. By the way I would prefer a more descriptive name `CI_BUILD_DIR` which is in line with the `CI_*` variables.

An issue with the old approach that the PR highlights is the handling of the current dir. I am not sure the current way is correct, it seems to me that calling `git_checkout` twice will give incorrect results, won't it?

2017-03-07 19:17 UTC, ejgallego commented
We agreed on some minor changes, when done this should be ready for merge.

2017-03-07 22:47 UTC, Zimmi48 commented
This last commits implement an idea we discussed with Emilio.
Mainly the idea is to create a new variable for the location of the clones. Because this variable is defined relatively to `CI_BUILD_DIR` which itself is an absolute path, that gives more guarantee on what the script is doing.
At the same time, this commit provides a bit more uniformity (all git targets define variables for branch, URL, and location of the clone). We also provide a template to create new CI targets.

2017-03-08 00:01 UTC, ejgallego commented on dev/ci/ci-common.sh
>  # git_checkout branch
Please add a comment with the intended semantics of the function, something such as:
> `git_checkout branch url dest` will checkout a git repository to branch blah or update it if it exists....

Indeed, the semantics of the fucntion is not yet clear to me.

2017-03-08 00:04 UTC, ejgallego commented on dev/ci/ci-common.sh
> +  ( cd ${_DEST} && git pull &&
After thinking a bit more I am not sure I am yet happy with the current behavior if `${CI_BUILD_DIR}/${_DEST}` exists. For instance, imagine you run `make ci-blah` in some branch `b1`. Then, you checkout branch `b2` that sets some different branch for the contrib, the `git pull` won't checkout the correct branch and repository.

That is to say, `git checkout b1 repo2 CompCert` may end up really checking out branch `b2` in `repo3`.

What do you think?

2017-03-08 00:05 UTC, ejgallego commented
It is looking great. After thinking a bit more I am not sure about the semantics of `git_checkout` when the target already exists. @Zimmi48 Can you take a look to my comments?

2017-03-08 08:58 UTC, Zimmi48 commented on dev/ci/ci-common.sh
> +  ( cd ${_DEST} && git pull &&
I actually had the same concern. Let me know what you think of the alternative version I just pushed. I think it should do what we expect from it (I have lightly tested it), but I am not a git kung-fu master so I would appreciate feedback.

2017-03-08 12:39 UTC, ejgallego commented
Wow fantastic, great job!

2017-03-08 12:39 UTC, ejgallego approved these changes

2017-03-08 15:00 UTC, Zimmi48 commented
This updated commit is essentially the same as before but I went back to using `git clone` instead of `git init` because it makes `git fetch` more intelligent (does not fetch anything if the remote has not changed).

This PR is ready in my eyes, and can be merged as soon as the Travis build finishes.

2017-03-10 15:14 UTC, ejgallego commented
Yup this is ready to go.

2017-03-11 17:51 UTC, Zimmi48 commented
Rebased to make sure Travis tests were passing. This is the case.

2017-03-13 10:35 UTC, merged