Adding a documentation for the new proof engine.
coq/coq pull request #488
Opened 2017-03-19 19:32 UTC by ppedrot

Here is a quick and dirty tutorial for people wishing to write low-level refining ML tactics. It mostly comments the use of the simple 'cut' tactic that features all the basic blocks of tactic writing.

2017-03-20 00:07 UTC, ejgallego commented on dev/doc/proof-engine.txt
> +meta-based engine which had a lot of drawbacks. The latter is deprecated and is
I would be more specific in the "had a lot of drawbacks". As written, I left me wondering what the drawbacks were. I'd either enumerate them, and remove the "a lot", or maybe the more positive phrasing "replacing the old meta-based engine, improving the proof paradigm in these key areas: xxxxx"

2017-03-20 00:14 UTC, Zimmi48 commented
Could we start using Markdown for new files in `dev/doc/`? That's much nicer to read in the GitHub interface and it doesn't really hinder the reading in plain-text.

2017-03-20 01:32 UTC, JasonGross requested changes

2017-03-20 01:32 UTC, JasonGross commented on dev/doc/proof-engine.txt
> +as goals at a level high enough, they are actually no more than evars. The API
Grammar: I think you mean "are referred *to* as goals at a *high-enough level*"

2017-03-20 01:32 UTC, JasonGross commented on dev/doc/proof-engine.txt
> +Tactics are naturally operating on several goal at once, so that is is usual to
Grammar: several goal*s*

2017-03-20 01:32 UTC, JasonGross commented on dev/doc/proof-engine.txt
> +evars that have been create by the invokation of this thunk are then turned into
Grammar: been create*d*

2017-03-20 11:20 UTC, Zimmi48 commented
If by template you are asking how to mark titles and section titles, I would say:

    This is the title
    =================

    This is the section title
    -------------------------

        (* This is some code
        block *)

    For the rest *just* use what `Markdown` **gives** you.

This style reads pretty well as plain-text too.

2017-03-20 13:24 UTC, ppedrot commented
Done.

2017-03-22 17:22 UTC, psteckler commented
`we are focussed on one goal at a time which is materialized by the gl variable`

Would it be simpler to say:

`we focus on the goal indicated by gl`

2017-03-22 19:31 UTC, aspiwack reviewed
Thanks for that.

Some remarks below.

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +meta-based engine which had a lot of both expressivity and soundness drawbacks.
I think the most important change from the point of view of this tutorial is that the new proof engine uses an opaque type, so as to allow changing the underlying representation.

This permits some gains both in expressiveness and soundness. But they are not that huge, all things considered:

- Dependent subgoals (the original motivation)
- Multiple-goal tactics
- More consistent treatment of evar updates
- Avoid bug duplication by implementing one more type-checking algorithm (in particular several bug of `refine` closed)
- Stuff about metas
- Easier management of evar_maps

All of these were problems. But not major ones (not to everybody at any rate: at least some of them were for me, obviously). So maybe emphasising the gain in flexibility in the code would make for a better _entrée en matière_.

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +can contain typed holes, called evars. An evar is essentially defined by its
Using « evar » throughout the document is fine. But at least here, better remind that it means « existential variable ».

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +produce a term of type `A`, which is done by applying `mkEvar`, and which we
`mkEvar` -> `Constr.mkEvar`?

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +module. Tactics are naturally operating on several goals at once, so that is is
« that is is » -> « it is »

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +Here, `'a Sigma.run` is morally `evar_map -> 'a * evar_map`. What the function
« Here `'a Sigma.run` is morally » -> « In a first approximation, we can think of `'a Sigma.run` as »

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +does is to evaluate the `Constr.t Sigma.run` argument in the current proof
« is to evaluate » -> « is evaluate »

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +state, and to use the resulting term as a filler for the proof under focus. All
I'm not sure about « filler » here: it sounds a bit pejorative, like something to fill the void by lack of something actually useful. I don't have a replacement to suggest yet though.

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +evars that have been created by the invokation of this thunk are then turned
« invokation » -> « invocation »

2017-03-22 19:31 UTC, aspiwack commented on dev/doc/proof-engine.md
> +special use cases, e.g. whenever one wants a non-identity substitution. One
Yoctonitpick: « _e.g._ » is Latin, so it should be italicised.

2017-03-22 19:47 UTC, ppedrot commented on dev/doc/proof-engine.md
> +produce a term of type `A`, which is done by applying `mkEvar`, and which we
That's going to change when we merge the EConstr branch, so that I don't want to insist too much on that.

2017-03-22 20:08 UTC, aspiwack commented on dev/doc/proof-engine.md
> +produce a term of type `A`, which is done by applying `mkEvar`, and which we
Then, how about writing the doc as if the EConstr branch were merged. It's not particularly controversial, is it?

2017-04-06 20:10 UTC, merged