Fix warnings
coq/coq pull request #582
Opened 2017-04-21 18:40 UTC by SkySkimmer

This fixes warnings `+a-4-9-27-41-42-44-45-48-50` and adds configure options for those who want to enable that set (the default has not changed).
I'm not sure what warning 29 (unescaped end of line) is about so maybe that commit should be removed or isn't right.
Micromega had a surprising amount of unused values, I'm not sure if that's normal.

2017-04-21 18:41 UTC, SkySkimmer commented on kernel/nativecode.ml
> +[@@@ocaml.warning "-32-37"]
37 is unused constructor, probably manipulated where ocaml can't see.
32 is unused value, I'm less sure that this one is spurious.

2017-04-21 18:42 UTC, SkySkimmer commented on kernel/nativevalues.ml
> +[@@@ocaml.warning "-34"]
I don't know why this type is unused.

2017-04-21 18:59 UTC, ejgallego commented
Cool! You may want to update the .merlin file too.

2017-04-22 06:42 UTC, silene commented
Commit dbf3f00 is plain wrong. Indeed,

    "A
        B"

is parsed as `"A\n    B"` (for some reason, github is eating my spaces, there are four of them here), while

    "A\
        B"

is parsed as `"AB"`. Notice how you lost both `\n` and the indentation. So using `\` is especially wrong for usage strings and for `coq_makefile`. But this also shows a place where the current code was broken.

2017-04-22 08:28 UTC, SkySkimmer commented
So it should be 
```
"foo\
\nbar"
```
as in the usage.ml rather than 
```
(* warns *)
"foo
bar"
```
as in coq_makefile's usage string?

2017-04-22 10:18 UTC, silene commented
Yes, putting `\n` in front of a line is damn ugly, but it is the only way I know of to ensure that indentation is not discarded by the compiler.

2017-04-22 17:08 UTC, SkySkimmer commented
Fixed the newlines.
I tried to add a travis target which runs the tests but couldn't figure it out and I'm tired of spamming. My last attempt is at https://github.com/SkySkimmer/coq/commit/b66b020920e5a2147425bc6286d4307ae5cf3c93 if anyone wants to look.

2017-04-23 00:36 UTC, ejgallego commented
I am not sure the set of enabled warnings should be a configure option. IMHO this usually leads to ineffective warnings as people will just not enable them. In my opinion strengthening the set of defaults warnings is OK.

2017-04-24 11:41 UTC, SkySkimmer commented
Sounds good to me.
If someone wants a warning disabled they can say so here, or if they encounter it after this PR is merged they can disable it at that point and make it part of their own PR.

2017-04-24 11:56 UTC, ejgallego commented
Sounds good, let's enable them by default then !! We can always refine in the beta phase.

2017-04-24 11:58 UTC, ejgallego commented
Indeed the biggest problem with warnings is that different compiler versions may produce slightly different results. Our testing should help with that, but IMHO we will need to place this in the wild and react to the real world until the set of warnings is refined into a workable subset.

2017-04-24 11:59 UTC, SkySkimmer commented
Had to rebase on trunk since #538 left an unused open.

2017-04-24 12:01 UTC, SkySkimmer commented
I'm making the deprecated warning into a non error since otherwise 4.04 deprecates things like Char.uppercase in favor of uppercase_ascii which doesn't exist yet for 4.02.3.

2017-04-24 13:43 UTC, Zimmi48 reviewed
Do I understand correctly that following @ejgallego's suggestion, warnings are turned into errors by default? It feels a bit radical and dangerous to me because we won't test all compiler versions. Also it will encourage developers to just pass the `no-warn-error` option to not be bothered in the middle of a development. That no new warning is introduced should be checked in a clean-up phase only. So why not just add a Travis target to test for warnings as was the original suggestion?

2017-04-24 13:43 UTC, Zimmi48 commented on configure.ml
> +(** Explanation of disabled warnings in -warn-more mode:
Does the `-warn-more` mode exist or are you talking about the state where `-no-warn-error` option is not passed?

2017-04-24 13:45 UTC, SkySkimmer commented on configure.ml
> +(** Explanation of disabled warnings in -warn-more mode:
oops

2017-04-24 13:57 UTC, SkySkimmer commented
>Do I understand correctly that following @ejgallego's suggestion, warnings are turned into errors by default?

yes
>It feels a bit radical and dangerous to me because we won't test all compiler versions.

I'm not sure what you mean by that.
>Also it will encourage developers to just pass the no-warn-error option to not be bothered in the middle of a development.

That's not a problem, is it?
>That no new warning is introduced should be checked in a clean-up phase only.

I'm not sure what you mean by "clean-up phase".
>So why not just add a Travis target to test for warnings as was the original suggestion?

I think even if -no-warn-error ends up the default it would be better to just add -warn-error to the already present travis targets.

2017-04-24 14:02 UTC, Zimmi48 commented
> > It feels a bit radical and dangerous to me because we won't test all compiler versions.
>
> I'm not sure what you mean by that.

I mean I wouldn't like the compilation of Coq to fail on some user's machine because of a stupid warning.

> > Also it will encourage developers to just pass the `no-warn-error` option to not be bothered in the middle of a development.
>
> That's not a problem, is it?

If the developers deactivate the mode and the users are just bothered by it, what is the point of having it turn on by default?

> I think even if `-no-warn-error` ends up the default it would be better to just add `-warn-error` to the already present travis targets.

+1

2017-04-24 14:04 UTC, ejgallego commented
I see @Zimmi48's point, I think `-warn-on-error` should be the default for Travis and development builds, but indeed user tarballs and OPAM should disable this flag.

2017-04-24 14:05 UTC, ejgallego commented
I think having it as a default for the dev tree makes sense as most developers will just forget to pass -warn-on-error

2017-04-24 14:08 UTC, Zimmi48 commented
> I see @Zimmi48's point, I think -warn-on-error should be the default for Travis and development builds, but indeed user tarballs and OPAM should disable this flag.

Today, lots of users do `git clone` instead of downloading a tarball.

> I think having it as a default for the dev tree makes sense as most developers will just forget to pass -warn-on-error

Yeah but developers sometimes forget to test the test-suite as well. This is what Travis is there for...

2017-04-24 14:22 UTC, SkySkimmer commented
configure.ml can't figure out if someone is a user or a developer so it makes sense to have -warn-error be an explicit choice.
Now I'm enabling warnings but not warn-error by default, and travis enables warn-error.
There are a bunch of builds waiting due to recent merges so it will take some time until travis gets to this PR.

2017-04-24 14:28 UTC, SkySkimmer commented
I'm not sure if it's a problem, but merges from 8.6 into trunk seem like an easy way to introduce warnings without being detected.

2017-04-24 14:32 UTC, Zimmi48 commented
> I'm not sure if it's a problem, but merges from 8.6 into trunk seem like an easy way to introduce warnings without being detected.

Well, no. Travis also tests direct commits to trunk. There is even a Travis badge in the README now. So if such a merge introduced a warning. This badge would turn from "Build passing" to "Build failed".

2017-04-24 15:25 UTC, ejgallego commented
> configure.ml can't figure out if someone is a user or a developer so it makes sense to have -warn-error be an explicit choice.

Once the version system is in place indeed it would be able to detect if it is a clone of a git tree or a tarball. IMHO people cloning the tree can bear with tweaking configure; of course `warn-on-error` is easy to tweak later, but I am not comfortable with the different modes on Travis and dev, I would rather have them sync'ed.

In a sense this is a deeper question, what is the goal of CI? So CI is for testing that builds are reproducible, and general sanity checks, but IMHO assigning the CI the role of the warnings curator is the wrong one.

2017-04-24 15:26 UTC, ejgallego commented
> I'm not sure if it's a problem, but merges from 8.6 into trunk seem like an easy way to introduce warnings without being detected.

This is IMHO another argument to support a default `error-on-warn`. The release managers build-check the merges before pushing, so it makes sense to make them aware of new warnings.

2017-04-24 15:34 UTC, Zimmi48 commented
@ejgallego We do already detect in the configure file if we are in a git tree (cf. https://github.com/Zimmi48/coq/blob/trunk/configure.ml#L431).

2017-04-24 15:38 UTC, ejgallego commented
Indeed we could use this and enable warn-on-error. Maybe I am too paranoid but I feel a pile of problems if Travis has it enabled and our normal workflow doesn't. I hope we can do better once we make more progress on #483

2017-04-24 15:38 UTC, ejgallego commented
But I fully agree with your concerns on `-warn-on-error`

2017-04-24 15:41 UTC, Zimmi48 commented
I feel that indeed you are a bit paranoid ;-) but my concern was a minor one so I won't block merging of this PR whatever the default is chosen to be.

2017-04-24 15:50 UTC, ejgallego commented
It is more of a "state problem" I think. I feel like my head can only hold at most 2 bits of state, so now adding another bit "is -warn-on-error" enabled?" when I need to diagnose travis failures tends to overload my stack, but dunno, I'd love to hear what others think.

2017-04-25 11:52 UTC, SkySkimmer commented
Compiling with OCaml 4.04 is failing due to warning 52. Some of them are internal to Coq and I'll replace them with specific exceptions, but I'm not sure what to do about these:
- matching `Sys_error "Is a directory"` to print a custom error in coqwc https://github.com/coq/coq/blob/trunk/tools/coqwc.mll#L250, git blame says it was there from the start in 9dd608e78fb7d392ea88b47f396f5077021337d5 (@backtracking)
- matching `Invalid_argument "equal: functional value"` in https://github.com/coq/coq/blob/trunk/lib/cErrors.ml#L128 to make that exception critical (for canaries), introduced 2a0d260c9c80c07844605fcb6844bb9cfdfeb0fd (@ppedrot)

There are basically 2 solutions:
- locally disable the warning
- remove the custom behaviour, ie say "system error: is a directory" instead of "system error: foo is a directory" and make all `Invalid_argument`s critical errors.

(Compilation also fails due to new merges in trunk, and in 4.04 due to some unused modules like Hsorts in constr.ml, but those are simple)

2017-04-25 12:22 UTC, JasonGross commented
Note that if warnings are errors by default, bisecting Coq will require disabling this behavior as we move to newer compilers.

2017-04-25 12:37 UTC, SkySkimmer commented on parsing/pcoq.ml
> -open Pp
4.04 seems more sensitive for preexisting warnings, like this unused open.

2017-04-25 14:04 UTC, ejgallego commented
@SkySkimmer indeed warning 52 is a pain.

I suggest we try to have a quick course of action with this patch because we seems to be losing loads of time blocking and rebasing PRs instead of doing actual development.

My proposal is then:
- Let's merge this patch now, with `-warn-on-error` disabled.
- Let's keep Travis building things with `-warn-on-error` disabled by default.
- Let's postpone the discussion on whether `-warn-on-error` should be enabled by default to a WG.

2017-04-25 14:33 UTC, mattam82 approved these changes
I didn't catch any more issues, I agree with @ejgallego that we should rather quickly merge this and leave the warn-error decision for later.

2017-04-25 14:33 UTC, mattam82 commented on vernac/record.ml
> -
This should rather be used in the code below, I think that's an overlook

2017-04-25 14:33 UTC, mattam82 commented on kernel/names.ml
>    end
What's the warning here, out of curiosity?

2017-04-25 14:41 UTC, SkySkimmer commented on kernel/names.ml
>    end
Unused type t
Looking at it more I should just remove Projection.SyntacticOrd.t since it doesn't appear in the mli and is the same as Projection.t

2017-04-25 14:45 UTC, ejgallego approved these changes

2017-04-25 14:47 UTC, ejgallego requested changes
Please make this match the default configuration

2017-04-25 14:56 UTC, SkySkimmer commented
@ejgallego 
>Please make this match the default configuration

What do you mean by "this"? (I think your message was supposed to be attached to some part of the diff?)

2017-04-25 14:57 UTC, ejgallego commented
@SkySkimmer yup sorry I messed up.

2017-04-25 14:59 UTC, ejgallego commented on .travis.yml
> +- ./configure -local -usecamlp5 -native-compiler yes -warn-error ${EXTRA_CONF}
Please make the `-warn-error` setting match the default configuration. You could use `EXTRA_CONF` if you wanna create an optional allow fail target, but I suggest we tweak travis in a new PR, we could also cleanup the IDE building by using YAML refs.

2017-04-25 14:59 UTC, SkySkimmer commented
- disabled -warn-error in travis (ie left default)
- used `warn_cannot_define_projection` in vernac/record.ml instead of deleting it
- removed type copies in kernel/names.ml SyntacticOrd submodules

2017-04-25 15:00 UTC, ejgallego approved these changes

2017-04-25 15:01 UTC, ejgallego commented
Great, thanks! LGTM.

2017-04-26 06:10 UTC, SkySkimmer commented
Travis passed!

2017-04-27 15:25 UTC, maximedenes commented on engine/evd.ml
> +(* module RelDecl = Context.Rel.Declaration *)
Should this go away?

2017-04-27 15:25 UTC, maximedenes commented on kernel/constr.ml
> -(* let hcons_sorts = Hashcons.simple_hcons Hsorts.generate hcons_univ *)
@mattam82 was it expected that this was disabled?

2017-04-27 15:25 UTC, maximedenes commented on plugins/ltac/tauto.ml
> +let _tauto_legacy_flags = {
Is this unused? If yes, why do we keep it?

2017-04-27 15:25 UTC, maximedenes commented on printing/prettyp.ml
> +(* module RelDecl = Context.Rel.Declaration *)
Should we remove this?

2017-04-27 15:37 UTC, SkySkimmer commented on kernel/constr.ml
> -(* let hcons_sorts = Hashcons.simple_hcons Hsorts.generate hcons_univ *)
It's in sorts.ml

2017-04-27 15:42 UTC, herbelin commented on plugins/ltac/tauto.ml
> +let _tauto_legacy_flags = {
Personally, it is relevant to me to remember how it worked in 8.4. And having it type-checked by ocaml ensures a better correctness than if it were a comment. But if it is cluttering too much for others, I can also live with `git log`.

2017-04-27 15:43 UTC, SkySkimmer commented on plugins/ltac/tauto.ml
> +let _tauto_legacy_flags = {
It was introduced in e1f5180e88bf02a22c954ddbdcbdfeb168d264a6 (@herbelin) and was already not used at that time.
I don't know.

2017-04-27 15:46 UTC, SkySkimmer commented on engine/evd.ml
> +(* module RelDecl = Context.Rel.Declaration *)
I think it doesn't look bad next to the `NamedDecl` but it could go away if someone wants it to.

2017-04-27 15:56 UTC, maximedenes commented on plugins/ltac/tauto.ml
> +let _tauto_legacy_flags = {
@herbelin I see, thanks for the explanation! If it is an 8.4 setting, maybe 8.7 is the right time to remove it, I guess.

2017-04-28 14:58 UTC, SkySkimmer commented
@maximedenes so do I remove the things you commented on?

2017-05-02 08:01 UTC, maximedenes commented
I think it can be merged as it is, we'll remove that later if we want to. I'm having a last look at the native_compiler ones.

2017-05-02 14:10 UTC, merged

2017-05-08 12:44 UTC, herbelin commented
I just found a problem with the `[@@@ocaml.warning "-32"]` in trace mode of `coqtop.byte`. Probably because of camlp5 which does not support it (yet?), the standard debugging protocol `Drop. #use"include";;` fails with a syntax error. Is it ok if we (temporarily) remove this attribute from the file `top_printers.ml`?

2017-05-08 13:23 UTC, SkySkimmer commented
I'll make a PR to remove it permanently, putting it there was a mistake (I saw the unused value warning and thought it was because of some strange debug thing I didn't know about, but in fact it's because a couple lets are shadowed).

2017-05-08 13:28 UTC, SkySkimmer commented
See #619.

2017-05-08 17:01 UTC, herbelin commented
@SkySkimmer: Great!