Fixes #6129 (declaration of coercions made compatible with local definitions)
coq/coq pull request #6132
Opened 2017-11-10 07:13 UTC by herbelin

Declaration of coercions had actually never been made compatible with local definitions in the premisses of the coercion.

2017-11-10 09:25 UTC, JasonGross submitted a review, later dismissed

2017-11-10 09:25 UTC, JasonGross commented on test-suite/bugs/closed/6129.v
> +Record foo2 (x : Type) (y:=1) (z t: Type) := { foo_nat2 :> nat }.
You're missing a case: this tests when the let-binder is the last argument, and when it's a middle argument, but it doesn't test when the let-binder is the first argument.

2017-11-10 10:23 UTC, herbelin commented on test-suite/bugs/closed/6129.v
> +Record foo2 (x : Type) (y:=1) (z t: Type) := { foo_nat2 :> nat }.
I added a test (it works), but the test is anyway an approximation. We could have tested dependent contexts, presence of section variables, and many various situations. You're right in wanting more tests. Feel free to add as many tests as you want.

2017-11-10 11:14 UTC, JasonGross commented on test-suite/bugs/closed/6129.v
> +Record foo2 (x : Type) (y:=1) (z t: Type) := { foo_nat2 :> nat }.
Thanks.  I thought the first/last tests were particularly salient as corner cases because I got different error messages for each of them.

2017-11-10 11:50 UTC, herbelin commented on test-suite/bugs/closed/6129.v
> +Record foo2 (x : Type) (y:=1) (z t: Type) := { foo_nat2 :> nat }.
OK, I see.

2017-11-13 16:03 UTC, gares requested changes
The code looks good, but I'd like to have the test not only check that the coercions are declared, but also inserted. Could you please add a few invocation to `Check (fun x : foo{1,2,3} => x : nat)`?

2017-11-13 22:15 UTC, herbelin commented
@gares: done. (Please feel free to push directly to this branch if you want to add more test.)

2017-11-14 18:28 UTC, gares approved these changes

2017-11-16 15:14 UTC, merged