[interp] [ast] Make raw_cases_pattern_expr private + small cleanup
coq/coq pull request #630
Opened 2017-05-15 00:45 UTC by ejgallego

The type `raw_cases_pattern_expr` is used only in the interpretation
of notation patterns. Indeed, this should be a private type thus we
make it local to `Constrintern`; it makes no sense to expose it in the
public AST.

The patch is routine, except for the case used to interpret primitives
in patterns. We now return a `glob_constr` representing the raw
pattern, instead of the private raw pattern type. This could be
further refactored but have opted to be conservative here.

We also include a small cleanup on a pattern error case.

See the commit logs for further details.

2017-05-15 02:24 UTC, JasonGross requested changes

2017-05-15 02:24 UTC, JasonGross commented on interp/constrintern.ml
> +  (** [CPatCstr (_, c, l1, l2)] represents ((@c l1) l2) *)
Do you mean `RCPatCstr`?

2017-05-15 02:24 UTC, JasonGross commented on interp/constrintern.ml
> +         here and not in the parser because it would require to
Grammar nit: "require duplicating"

2017-05-15 02:49 UTC, ejgallego commented on interp/constrintern.ml
> +  (** [CPatCstr (_, c, l1, l2)] represents ((@c l1) l2) *)
Indeed, thanks.

2017-05-15 02:49 UTC, ejgallego commented on interp/constrintern.ml
> +         here and not in the parser because it would require to
Indeed thanks.

2017-05-15 12:44 UTC, herbelin commented on interp/constrintern.ml
> +         are supportted only in local binders and only at top
Typo.

2017-05-15 12:45 UTC, herbelin commented
Looks ok to me.

BTW, I often wondered whether this `raw_cases_pattern_expr` is really necessary or not. But anyway, it is here and seems to work, in spite of all the subtleties with symmetric and asymmetric patterns. So I renounced to answer the question.

2017-05-15 13:28 UTC, ejgallego commented on interp/constrintern.ml
> +         are supportted only in local binders and only at top
Thanks, fixed.

2017-05-15 13:31 UTC, ejgallego commented
Thanks Hugo. I think `raw_cases_pattern_expr` is not really "necessary", but it was quite helpful to me when trying to understand constrintern as I could put that logic in a separate module and get a better view of the rest of the file.

2017-05-17 07:12 UTC, maximedenes commented
@ejgallego Could you rebase? There is a trivial conflict, no pain expected. Thanks!

2017-05-17 07:12 UTC, maximedenes commented
In fact, I'm gonna resolve the conflict in the merge commit, sorry for the noise.

2017-05-17 07:15 UTC, merged