[econstr] Removal of unsafe 3: occur_evar_upto
coq/coq pull request #6349
Opened 2017-12-08 03:51 UTC by ejgallego

This is a minor cleanup in `evarutil`.

2017-12-08 07:26 UTC, ppedrot commented
This is wrong. If the evar you're checking for is already defined, you can get a loop. I precisely remember a bug in `refine` of that kind, and reading the code of this tactic shows it can indeed occur that a term becomes ill-founded.

2017-12-08 09:06 UTC, maximedenes commented
@ppedrot can you request changes on the PR through the proper interface? This way, it will be filtered in an appropriate way. Thanks!

2017-12-08 09:11 UTC, ppedrot commented
@maximedenes I don't think there are changes to make, more precisely, I believe this PR is fundamentally invalid.

2017-12-08 09:13 UTC, ppedrot commented
Put otherwise: checking for well-foundedness of the "points-to" relation is, by definition, requiring to observe the pointers individually. It's a low-level function that *has* to be written without the insensitive API.

2017-12-08 14:47 UTC, ejgallego commented
Uh, all that you say sounds very strange, first, if the evar is defined, it should not be observable; much less should the occur check be positive in that case. Are you saying that `occurs "X" "p(X:=true)"` should return true?

The more I look at this "sensitive" stuff the more I fail to make a sense of it, sorry.

By the way, travis passes on this PR.

2017-12-08 14:50 UTC, maximedenes commented
There are many implementations of occur checks in Coq, and a lot of them indeed don't make sense, AFAIU.

2017-12-08 15:02 UTC, ejgallego commented
So I'd like to dismiss this PR as invalid, but I am afraid at the moment I don't follow @ppedrot 's argument. So let's tag it.

2017-12-08 15:18 UTC, SkySkimmer commented
I don't know if the PR is valid but this is just the termops occur so if it's valid the definitions should be merged.

2017-12-08 15:23 UTC, ejgallego commented
Yeah it looks like this function should be removed, as the semantics "occur X p(X:=true) == true" is non-sense.

2017-12-08 19:22 UTC, herbelin commented
I understand the question of @ppedrot as: what is the expected semantics of "occur ?X p(?X:=S ?X)"?

2017-12-08 19:32 UTC, ejgallego commented
> I understand the question of @ppedrot as: what is the expected semantics of "occur ?X p(?X:=S ?X)"?

In my very limited understanding of the issue, with the current model you are SOL the moment you build a cyclic term anyways due to other paths in the code. Such check should happen _before_ `?X:=S ?X` is added to the evar_map.

2017-12-08 20:33 UTC, herbelin commented
> Such check should happen before ?X:=S ?X is added to the evar_map.

I agree, but this is not necessarily easy. In particular, I'm unsure that we currently correctly detect circularities involving mutual dependencies of evars into other evars. I remember for instance the case of an instantiation `?x := f ?y` while we already had a postponed constraint say `?y = ?z ?x`. This kind of situation can and should certainly be addressed, but this requires some policy on when to do the occur-check.

2017-12-08 20:50 UTC, ejgallego commented
You make a very good point with regards different styles of substitution in the system, and indeed the introduction of `EConstr` means indeed much less flexibility wrt variables as it imposes a "lazy" [or maybe by-need] substitution process that is morally at odds with other styles in the system.

I am personally not a fan of that approach indeed but I think it was a good compromise among all the realistic possibilities.

But IMHO what we are seeing now is a conflict between the "EConstr" style of handling substitutions and some other parts of the system that want to be more algebraic. And it looks like it is hard to preserve both due to the large number of invariants at hand. I dunno, hopefully we can close the gap a bit somehow, but not looking easy.

2017-12-11 14:10 UTC, ppedrot commented
> Such check should happen before ?X:=S ?X is added to the evar_map.

I fully agree with that, but it doesn't make this PR righter anyway, you still have to open the unsafe pointer-level hatch for this kind of check.

2017-12-11 14:16 UTC, ejgallego commented
> I fully agree with that, but it doesn't make this PR righter anyway, you still have to open the unsafe pointer-level hatch for this kind of check.

Uh, I don't see how? `?X` and `f ?X` are perfectly safe to check. I still think that the PR is right [and doesn't break anything] the old function just doesn't make any sense. Let me stress this:

`occur ?X p(?X:=S ?X)` doesn't make sense in the current model. Ever.

2018-01-17 14:29 UTC, ppedrot commented
My final take on this PR is that there is a real problem as highlighted by @ejgallego, but the fix is currently wrong. We should instrument `Evd.define` to check for loops before performing the body update, otherwise we'll get into nasty loops with this PR. So I'd personally flag it as *depending on another fix* or something.

2018-01-17 15:12 UTC, ejgallego commented
> otherwise we'll get into nasty loops with this PR

well, that is theoretical anyways, as you can see the PR works in all contribs. My claim is that the behavior that would be problematic in this PR would also cause havoc in quite a few other parts of the system, so indeed, it is not happening now.

2018-03-07 10:37 UTC, maximedenes commented
The discussion hasn't converged, so postponing to 8.9.

2018-03-31 21:19 UTC, ppedrot requested changes
This PR is an incorrect solution to a real problem: Coq can badly screw up evar instantiation and produce cyclic terms. Instead of modifying the `occur_evar_upto` function, we need to modify `Evd.define` instead to ensure that no cycle appear when filling the body of an evar. Unluckily, it is easier said than done because the fact that a term contains a given evar is not stable by other evar instantiations. I already tried to write such a patch and IIRC it broke many uses of refine. A typical example of a broken behaviour is the following interaction:
```
{ e₀ : [ x : nat, y : nat ⊢ nat ], e₁ : [ ⊢ nat ], e₂ : [ ⊢ nat ] }
e₁ := ⊢ e₀[e₂[], 0]
e₂:= ⊢ e₁[] (** This is a formal cycle  e₂ → e₁ → e₀ → e₂ *)
e₀ := x, y ⊢ y (** No cycle anymore after instantiation of e₀ *)
```
Currently such behaviours happen in the wild, so we need a heuristic in functions using `Evd.define` to prevent similar situations by restricting the context of evar cycles.

2018-03-31 21:24 UTC, ejgallego commented
I see your point but I think you are confusing the scope of this PR. This PR just removes a useless function. No observable effect happens, and the rationale was that it is better not to have nonsensical functions in the codebase.

2018-03-31 21:43 UTC, ppedrot commented
@ejgallego But it's not mere refactoring, you did change the semantics of this function!

2018-03-31 21:47 UTC, ejgallego commented
I see your point, but mine is that the semantics before this patch in the first place were broken and never triggered [well at least the CI seems to agree]. And in fact I think that if that case would be even used, then you'd be in large trouble.

Anyways, that was just a kind of "oh, this code makes no sense at all it can't be the case anyone is relying on it", so I did the test and the PR.

Feel free to close if you think the nonsense serves any purpose.

2018-04-01 15:12 UTC, ppedrot commented
I mean, we can merge it, but we also need to remember to fix `Evd.define` before the next release. The fact that the CI doesn't break is a valuable indicator, but it doesn't cover some crazy unification loop cases that have already been reported in the bugtracker. Don't know what to do.

2018-04-01 15:17 UTC, ejgallego commented
> Don't know what to do.

I'd say if you are not sure let's just leave this is as-is, then we can reevaluate in a couple of months seeing how other parts have evolved.

2018-04-01 15:57 UTC, maximedenes commented
@ppedrot My advice: merge PRs if and only if you think it is an improvement over the current situation.

2018-04-01 17:15 UTC, Zimmi48 commented
And if you think this PR can produce a regression in some edge cases, could a new test be added to the test-suite that demonstrates this change of semantics?

2018-04-01 17:57 UTC, herbelin commented
Sorry to intervene again.

The change of semantics is only when `n` is already defined in `sigma`, i.e. when "the evar you're checking for is already defined"? Is there an agreement on that?

Otherwise, looking at the history of `occur_evar_upto` (namely 964024bf), its purpose was precisely to do the occur check in every `?X[subst]` after expansion of `?X`, what `Termops.occur_evar` was not doing at this time (i.e. `Termops.occur_evar` was looking in `subst` but not in the body of such defined `?X`).

But the semantics of `Termops.occur_evar` changed with the `EConstr` move (see 5143129) so that it got the intended semantics of `occur_evar_upto` (i.e. so that it expands defined evars before doing the occur check).

So, iiuc, there is no point in keeping the current `occur_evar_upto` except if calling it with a `n` already defined in `sigma` matters? But are there interesting scenarios which can lead to that? No need for an occur-check if the evar is already instantiated, no?

So, I'd be leaning towards making true the hypothesis of the conditional reasoning expressed by @skyskimmer and to simplify this PR even further. (Or do I miss something?)

I also have side remarks:

I used to think at `Evd.define` as the low-level API for assigning a body to an evar. In @ppedrot's naming scheme, that should be called `Unsafe` I guess. To be compared to `Evarsolve.solve_simple_eqn` and `Evarsolve.evar_define` which do checks. So, we should "accord our violins" about how to think at `Evd.define`.

The example
```
{ e₀ : [ x : nat, y : nat ⊢ nat ], e₁ : [ ⊢ nat ], e₂ : [ ⊢ nat ] }
e₁ := ⊢ e₀[e₂[], 0]
e₂:= ⊢ e₁[] (** This is a formal cycle  e₂ → e₁ → e₀ → e₂ *)
e₀ := x, y ⊢ y (** No cycle anymore after instantiation of e₀ *)
```
is otherwise interesting. I agree that for instantiating `e₂` in a valid way, we need first to restrict `e₀`.

2018-04-01 18:43 UTC, ejgallego commented
Thanks @herbelin for the comments. The main problem I guess of having better checks here would be performance.

2018-05-04 20:31 UTC, ejgallego commented
The function still has quite nonsensical semantics, however this PR has long surpassed the time allocation I can use for it, thanks to all for the comments!

2018-05-04 20:31 UTC, closed without merging