Fix #6404 - Print tactics called by ML tactics
coq/coq pull request #6407
Opened 2017-12-12 19:13 UTC by JasonGross

This fixes #6404.

Note that this changes the test-case of #6406, so whichever one is merged first, the other will have to be updated accordingly.

I'm tag this as `needs: discussion` because it seems like the behavior I'm changing was intentional, and it can lead to more verbose error messages in some cases (such as `intuition` and `tauto`, but not, e.g., `congruence`):
```coq
Goal False.
  tauto.
(* current master: Error:
In nested Ltac calls to "tauto" and "<Coq.Init.Tauto.with_uniform_flags>",
last call failed.
Tactic failure: tauto failed. *)
(* with this PR: Error:
In nested Ltac calls to "tauto", "<Coq.Init.Tauto.with_uniform_flags>",
"<tauto_plugin::with_uniform_flags@0>",
"<tauto_plugin::with_uniform_flags@0>", "f" (bound to
fun flags => <Coq.Init.Tauto.tauto_gen> flags),
"<Coq.Init.Tauto.tauto_gen>" and "<Coq.Init.Tauto.tauto_classical>", last
call failed.
Tactic failure: tauto failed. *)
```
and
```coq
Goal False.
  intuition fail.
(* current master: Error:
In nested Ltac calls to "intuition (tactic)",
"<Coq.Init.Tauto.intuition_then>" and "<Coq.Init.Tauto.with_uniform_flags>",
last call failed.
Tactic failure. *)
(* with this PR: Error:
In nested Ltac calls to "intuition (tactic)",
"<Coq.Init.Tauto.intuition_then>", "<Coq.Init.Tauto.with_uniform_flags>",
"<tauto_plugin::with_uniform_flags@0>",
"<tauto_plugin::with_uniform_flags@0>", "f" (bound to
fun flags => <Coq.Init.Tauto.intuition_gen> flags tac),
"<Coq.Init.Tauto.intuition_gen>", "<Coq.Init.Tauto.tauto_intuit>",
"t_tauto_intuit" (bound to
<Coq.Init.Tauto.simplif> flags;
 <Coq.Init.Tauto.axioms> flags ||
   match reverse goal with
   | id:(?X1 -> ?X2) -> ?X3
     |- _ =>
         cut X3;
          [ intro; clear id; t_tauto_intuit
          | cut (X1 -> X2);
             [ exact
             id
             | generalize (fun y : X2 => id (fun x : X1 => y)); intro; clear
                id; (solve [ t_tauto_intuit ]) ] ]
   | id:~ ?X1 -> ?X3
     |- _ =>
         cut X3;
          [ intro; clear id; t_tauto_intuit
          | cut (~ X1);
             [ exact id | clear id; intro; (solve [ t_tauto_intuit ]) ] ]
   | |- ?X1 =>
         <Coq.Init.Tauto.is_disj> flags X1; (solve
          [ left; t_tauto_intuit | right; t_tauto_intuit ])
   end ||
     match goal with
     | |- _ -> _ => intro; t_tauto_intuit
     | |- _ => t_reduce; t_solver
     end || t_solver) and "t_solver" (bound to fail), last call failed.
Tactic failure. *)
```

Also, perhaps I am messing something up, because the initial commit 21bbdd6b3cea2a2d9763bfc786b56a4b9e95ad06 by @herbelin seems to be about locations, not strictly about traces (and the issue I am solving here is only about improving backtraces, not error locations (unless I am mixing up terminology)).

2017-12-28 18:49 UTC, SkySkimmer commented
There's a merge conflict with CHANGES.

2017-12-29 05:09 UTC, JasonGross commented
I will rebase and fix conflicts with CHANGES once relevant discussion happens.  I'd still like to hear from @herbelin about this PR before taking any further steps with it.

2018-03-23 19:50 UTC, herbelin commented
I changed my mind a couple of times about the code for reporting errors in ltac code. One of my worry was that I wanted to avoid reporting about "internal" developer-level function such as, here, `tauto_plugin::with_uniform_flags@0` which a user is not supposed to have to know (and even if he can know about it, there is no reason to see a `::` and a `@0` which looks like debugging jargon).

Another worry was to avoid too verbose reports.

However, the main direct users of the messages are not me (at least not these days), so if @JasonGross considers that it is more useful like this, I'm all supporting it.

Maybe something should be done to avoid the (IMO) ugly `@0` though. As for the `foo::tac`, maybe rather printing `ML:foo.tac` (but I know that this is subjective)?

2018-03-24 19:03 UTC, JasonGross commented
> However, the main direct users of the messages are not me (at least not these days), so if @JasonGross considers that it is more useful like this, I'm all supporting it.

Indeed, I think the benefit of this for tactics like `transparent_abstract` outweighs the unpleasantness of this for tactics like `tauto`.



And we can always make the error message for `tauto` nicer by doing something like
```coq
Ltac tauto_verbose := false.
Ltac tauto :=
  let be_verbose := tauto_verbose in
  lazymatch be_verbose with
  | true => old_tauto
  | false => tryif old_tauto then idtac else fail "tauto failed"
  end.
```
Ideally, we could catch specific errors and let others through.... maybe that's a thing for Ltac2.

> Maybe something should be done to avoid the (IMO) ugly @0 though. As for the foo::tac, maybe rather printing ML:foo.tac (but I know that this is subjective)?

Sure, those both seem reasonable to me, but I think they belong in a different PR.

2018-03-27 16:26 UTC, herbelin commented
> Sure, those both seem reasonable to me, but I think they belong in a different PR.

Yes.

Any more comments? @ppedrot, do you want to take it as the assignee?

2018-03-27 20:28 UTC, ppedrot requested changes
The output test for bug 5778 needs to be updated accordingly.

2018-04-02 19:37 UTC, JasonGross commented
Rebased and fixed the output test for #5778

2018-04-04 06:43 UTC, ppedrot approved these changes
Good to merge.

2018-04-04 11:41 UTC, merged