Add equality schemes for bool, ascii, string
coq/coq pull request #6596
Opened 2018-01-16 10:28 UTC by JasonGross

This means that we can now use `Scheme Equality` for types depending on
these without getting fresh copies of the equality decision in whichever
file we're working in.

This is one approach to #6595 

- [x] Entry added in CHANGES.

2018-01-16 11:47 UTC, JasonGross commented
This breaks floq because floq is relying on the fact that `Bool.eqb b false` and `negb b` unify.  What should be done here? I can restore the old definition of `Bool.eqb` and leave `Bool.bool_beq` as something which doesn't unify with it, or I can define all of the things given by `Scheme Equality` by hand, or I can make an overlay for floq and stick a thing in `Coq.Compat.Coq87`.  (It also breaks fiat-parsers because fiat-parsers depends on the fact that `Scheme Equality for bool` is not run anywhere in the standard library.  This is silly, and I'll go fix it.)

2018-01-16 12:51 UTC, JasonGross commented
I've added overlays to compcert, vst, and flocq.  Is there a way to submit PRs to flocq (https://github.com/JasonGross/flocq/tree/equality-schemes)?

2018-01-16 12:53 UTC, SkySkimmer commented on theories/Bool/Bool.v
> +Notation eqb_lb := internal_bool_dec_lb.
What are these _bl values?

2018-01-16 12:54 UTC, SkySkimmer commented
Do we intend to keep the aliases or should we deprecate them?

2018-01-16 12:56 UTC, JasonGross commented on theories/Bool/Bool.v
> +Notation eqb_lb := internal_bool_dec_lb.
"boolean leibniz"  These are the correctness lemmas for `bool_beq`.  I think it's wrong to have them named as `internal_bool_dec_{bl,lb}` (see https://github.com/coq/coq/issues/4178), so I gave them alternate names here.  I'm fine with replacing them with better names, I'd accede to stronger opinions if others think that we should have only the `internal` ones, and I think a better solution is to not have `Scheme Equality` generate `internal_` prefixed lemmas, and instead generate more accessible ones.

2018-01-16 12:59 UTC, JasonGross commented
> Do we intend to keep the aliases or should we deprecate them?

I think that the aliases of the `internal_*_{bl,lb}` lemmas should be kept.  I would be in favor of deprecating the other aliases, on the principle of consistency, but it's not clear to me that `bool_beq` is better than `Bool.eqb`, just that we should pick one style for uniformity and have `Scheme Equality` generate that style.

I will add a commit to deprecate them, and I'm curious what you and others think.

2018-01-16 17:00 UTC, JasonGross commented
@silene Could you merge https://github.com/JasonGross/flocq/tree/equality-schemes into flocq?

2018-01-17 08:52 UTC, silene commented
> Could you merge https://github.com/JasonGross/flocq/tree/equality-schemes into flocq?

Done.

2018-01-17 09:13 UTC, JasonGross commented
Thanks!

2018-01-17 09:15 UTC, JasonGross commented
@silene I don't see it at https://gforge.inria.fr/scm/browser.php?group_id=1715, though; does gforge take a while to update?

2018-01-17 09:28 UTC, silene commented
> does gforge take a while to update?

No, gforge is instant. But only Flocq's webpage is on gforge, the actual repository is hosted on gitlab: https://gitlab.inria.fr/flocq/flocq

2018-01-17 19:07 UTC, herbelin commented
> I think that the aliases of the internal_*_{bl,lb} lemmas should be kept. I would be in favor of deprecating the other aliases, on the principle of consistency, but it's not clear to me that bool_beq is better than Bool.eqb, just that we should pick one style for uniformity and have Scheme Equality generate that style.
> 
> I will add a commit to deprecate them, and I'm curious what you and others think.

Long-standing request which I think was rather consensual (and that Lean implemented actually): that declaration of inductive types open namespaces from the names of the declared inductive types, so that the name is here `bool.beq`.

About the `internal_` prefix: not very elegant.

2018-02-20 19:28 UTC, letouzey requested changes
For `ascii` and `string`, ok.  But for `bool`, I'm not in favor of using `Scheme Equality`. I think we really want there a definition we could read without playing with some `Print`. And `bool` equality is at the same time easy to do and delicate enough (see indeed the `Bool.eqb b false = negb b` issue) to have it done by a human. We should rather design a way to teach `Scheme Equality` that an equality function already pre-exists for `bool` (and also for `nat` and a few other).

2018-02-20 19:33 UTC, maximedenes commented
> design a way to teach Scheme Equality that an equality function already pre-exists for bool (and also for nat and a few other).

Isn't that called type classes?

2018-02-20 19:36 UTC, JasonGross commented
> But for bool, I'm not in favor of using Scheme Equality. 

The issue is that `Scheme Equality for ascii` will generate a scheme for `bool` if it doesn't already exist.  And while I agree that having a way to register schemes is preferable to having `Scheme` for `Bool.bool_beq`, I think having `Scheme` for `Bool.bool_beq` is preferable to having `Ascii.bool_beq`.

> We should rather design a way to teach Scheme Equality that an equality function already pre-exists for bool (and also for nat and a few other).

That sounds good.  I'm not sure how to do it, though...

2018-03-08 09:28 UTC, maximedenes commented
It seems this needs to be refined a bit, so let's postpone to 8.9.

2018-07-25 19:56 UTC, JasonGross commented
Superseded by #8063

2018-07-25 19:56 UTC, closed without merging