Ssr merge
coq/coq pull request #669
Opened 2017-05-22 23:17 UTC by maximedenes

This is a merge of the current ssreflect plugin. It does not introduce the "ssr2" new features, nor a notion of proof modes (by lack of time), but does clean the code (separation in components with interfaces, etc.).

The point of this merge is 1) to address user demand and 2) make it easier to transfer some functionality to Coq, while keeping things in sync.

@amahboubi is working on a cleanup of ssr's documentation, which will be integrated in 8.7 as a chapter of the Coq manual.

2017-05-22 23:47 UTC, maximedenes commented
@ejgallego Can you be more specific on the points you'd like to discuss?

2017-05-22 23:50 UTC, ejgallego commented
What about the libraries?

2017-05-23 00:30 UTC, maximedenes commented
> What about the libraries? Does the plugin make sense without them?

Yes, althought we discussed the inclusion of `ssrbool.v`, which may be added to this PR.

> What about Travis, can this work without an overlay?

Yes, although I have a mathcomp branch ready that removes duplication.

2017-05-23 05:00 UTC, Zimmi48 commented
@maximedenes Does your math-comp branch preserve compatibility by having a `ssreflect.v` file re-exporting `Coq.ssreflect`?
Would it be alright to rename `ssreflect.v` in `SSReflect.v` so as to be consistent with the Coq convention of having the first letter capitalized? (I know math-comp does not follow the convention and I'm fine with it but here it would become the first `.v` file of `plugins/` and `theories/` together which does not follow the convention, so I'm not sure that historical justification is enough as a reason to keep it like that).

2017-05-23 05:55 UTC, Zimmi48 commented on plugins/ssr/ssreflect.v
> +Global Set Bullet Behavior "None".
Assuming that you keep a `ssreflect.v` in math-comp that re-exports this file, I would really appreciate if you could move the above line over there, so that people who wish to use SSReflect with bullets can do so by importing this file (people who want compatibility will continue to load the math-comp file anyway).

2017-05-23 08:30 UTC, ejgallego commented
> Would it be alright to rename ssreflect.v in SSReflect.v

IMHO not worth the loss of compatibility with all the code snippets out there.

2017-05-23 08:32 UTC, Zimmi48 commented
@ejgallego Bullshit. This creates no loss of compatibility.

2017-05-23 09:48 UTC, maximedenes commented
> Bullshit.

Let's stay respectful of each other.

> Would it be alright to rename ssreflect.v in SSReflect.v so as to be consistent with the Coq convention of having the first letter capitalized?

I wasn't aware of this convention, I thought it was a historical legacy. Where is it documented and what is the point of this convention? I don't know of any other language that imposes a convention on the capitalization of file names, do you?

> so that people who wish to use SSReflect with bullets can do so by importing this file (people who want compatibility will continue to load the math-comp file anyway).

Disabling the "strict" behavior of bullets is not a compatibility flag, it is part of the ssr proof mode. We've discussed already why it was.

2017-05-23 10:24 UTC, Zimmi48 commented
> I wasn't aware of this convention, I thought it was a historical legacy. Where is it documented and what is the point of this convention? I don't know of any other language that imposes a convention on the capitalization of file names, do you?

The language is not imposing anything on the users, but we can try to have uniformity in the standard library. For now, the standard library is 100% respecting this implicit convention. You perfectly know that there is almost no documentation on such things so don't oppose this argument to me.

The compatibility concern raised by Emilio isn't founded: the integration in the Coq standard library already means that we can load the plugin with `From Coq Require Import ssreflect.`
For compatibility when you remove SSReflect from math-comp, you will have anyways to keep a `ssreflect.v` which will contain `From Coq Require Export ssreflect.`
So it costs you nothing to follow my suggestion. This would mean that users can either do `From mathcomp Require Import ssreflect.` or `From Coq Require Import SSReflect.`

I am fully aware that this is completely minor but please tell me what is the point in refusing this. If you do not provide a serious argument, this just looks like the usual "we are SSR, we want to do things in our way". (I know this isn't fair to you to say this but I just want to highlight how it feels from my point of view.)

2017-05-23 10:37 UTC, ejgallego commented
> we can load the plugin with From Coq Require Import ssreflect.

IMO if this happens this is wrong, it should still live in its own namespace.

2017-05-23 10:42 UTC, ejgallego commented
> I am fully aware that this is completely minor but please tell me what is the point in refusing this. If you do not provide a serious argument, this just looks like the usual "we are SSR, we want to do things in our way".

Well it really looks to me like you are trolling or otherwise I fail to understand what is going on, since when file naming got so important? There are many other sources of non-uniformity in the system.

As for math-comp, it indeed looks like a very uniform development in style, and the convention there is to use lower case, which I personally like. And now we come to the central non-issue here, naming is a matter of taste and I am glad Coq allows freedom in that sense (for now).

2017-05-23 18:03 UTC, Zimmi48 commented
@maximedenes Actually I was wrong, there is already one file not respecting this implicit convention which is the one in the ssrmatching plugin :/ So let's forget about my suggestion and let's keep the lower-case convention in the ssr* files.

As for the bullet suggestion, I would like to come back to it, but in person since apparently PR discussion is never a suitable medium to talk about SSReflect.

2017-05-24 08:22 UTC, gares requested changes
A few minor points:
- (new) files don't have a license banner
- `test.v` is not relevant and should go
- `Tacmach.sigma` and `Evd.sigma` are aliases but in the .mli files both are present.  I'd lean toward the latter.

2017-05-24 08:32 UTC, maximedenes commented
> Tacmach.sigma and Evd.sigma are aliases but in the .mli files both are present. I'd lean toward the latter.

What banner and license should I put?

2017-05-24 09:45 UTC, Zimmi48 commented
> What banner and license should I put?

You should use the same banner/license in all the plugin.

2017-05-24 10:58 UTC, gares requested changes

2017-05-24 10:58 UTC, gares commented on plugins/ssr/ssreflect.v
> +Global Set Bullet Behavior "None".
Yep, the Global stuff should go away and the refman should eventually document the proof style advocated in mathcomp (that requires bullets having no meaning).

2017-05-24 14:11 UTC, JasonGross commented on plugins/ssr/ssreflect.v
> +Global Set Bullet Behavior "None".
Would it be worth it to have a `ProofStyle.v` file in the plugin that you could import, which has these settings? (It would also make a natural place to document the proof style as well.)

2017-05-24 23:12 UTC, maximedenes commented
Summary of WG discussion: ok to merge, but we need to add the general purpose infrastructure that is in `ssrbool.v` and `ssrfun.v`, and merge what can be in `Bool.v`.

There was still some debate about where the bullet behavior should be modified
(in a mathcomp file, or in Coq's ssreflect.v). @ggonthier do you have a
preference? After thinking more, I'm personally fine either way.

We did not really discuss the file name convention. Personally, after pondering
on this too, I'm ok with any solution. Note that if we include other files (like `ssrfun.v`, we'll need to use the same convention).

2017-05-24 23:19 UTC, Zimmi48 commented
Great to see that the discussion was fruitful. About the name convention, I'm also OK with either solution now that I've seen that `ssrmatching.v` was breaking the otherwise respected but completely implicit former convention of capitalizing the first letter. If the chosen solution is to capitalize, do you think this file could be capitalized as well to re-establish the consistency? (Not a big deal though.)

About moving the global options to a different file like @JasonGross proposed, I would be happy with this solution.
In the longer run though, the discussion we had this morning shows that we must discuss together and design a strict mode that can be satisfactory for SSReflect developers (while if possible being also satisfactory for other users). I propose that we talk about this at the Developers Workshop (some stuff on focusing was already on my TODO-list for this event, cf. the wiki page).

2017-05-25 05:37 UTC, JasonGross commented
I'll cast a vote in favor of keeping the completely uniform convention of the standard library and bundled plugins of capitalizing the first letter of file names.

I'm curious what the argument is in the other direction.

2017-05-25 10:40 UTC, Zimmi48 commented
Note @maximedenes that you did take #454 quite a few times as an example that the current default for bullets doesn't satisfy all users, but you consistently forget math-comp/math-comp#102 which on the other hand shows that the current default imposed by SSReflect doesn't satisfy all users either. (I didn't add this comment to troll or launch the debate again but just because I just finished watching the video and I wasn't there to say this IRL).

In any case, as you can see here https://coq.inria.fr/cocorico/CoqImplementorsWorkshop/CoqIW2017, I'd really like that we find a longer term solution by designing and implementing a strict mode that is satisfying to all and I'm ready to spend time working on it.

2017-05-30 20:06 UTC, maximedenes commented
> (new) files don't have a license banner

@gares Why do `ssrmatching.ml4` and `ssrmatching.v` differ in their header and license?

2017-05-31 09:32 UTC, gares commented
Hum, I guess I forgot to change the one of `ssrmatching.v`

2017-05-31 10:24 UTC, Zimmi48 commented
@gares I think it is wrong to change the license under which a plugin is distributed when integrating it into Coq. From these lines (https://github.com/coq/coq/blob/trunk/CREDITS#L23-L25) I understand that it is supposed to be always the case, but that isn't really justified and in some cases, it even contradicts the licensing information that can be found inside the plugin folder (e.g. https://github.com/coq/coq/blob/trunk/plugins/micromega/LICENSE.sos).
In any case, the inconsistency of the license headers in ssrmatching should be fixed, either by going full LGPL v2, or by going full CeCILL-B. If it is chosen to go full CeCILL-B, the license file should also be added to the folder (and in the ssreflect folder too) and the above mentioned lines in CREDITS should be modified. If the choice is to go full LGPL v2, then this choice should logically apply to ssreflect as well.

2017-05-31 11:35 UTC, maximedenes commented
> I think it is wrong to change the license under which a plugin is distributed when integrating it into Coq.

When legally possible, I think it is on the contrary the right way to do. It makes maintenance of legal metadata and moving code much easier.

For ssrmatching, @gares changed the license claiming that it was made possible following CeCILL-B 5.3.2 (see 7f416bad62c0). @gares can you say if:
1- Georges was made aware of it
2- The legality of this has been confirmed by a jurist at Inria. If not, I'll ask and I expect we get an answer long before the final release.

2017-05-31 12:32 UTC, Zimmi48 commented
@maximedenes Then if you feel that it is the right way to do, just go ahead and do it. AFAIK Microsoft has transferred its copyright to INRIA on this work (this should be checked, of course) so INRIA being the only problem it is possible to relicense whatever the original license says.

2017-05-31 12:33 UTC, Zimmi48 commented
@maximedenes Then if you feel that it is the right way to do, just go ahead and do it. AFAIK Microsoft has transferred its copyright to INRIA on this work (this should be checked, of course) so INRIA being the only problem it is possible to relicense whatever the original license says.

2017-05-31 12:44 UTC, maximedenes commented
> AFAIK Microsoft has transferred its copyright to INRIA on this work

Oh! I didn't know that. That would make the problem trivial. Can you say where you got this information from?

2017-05-31 12:55 UTC, Zimmi48 commented
@maximedenes: I think I got the information from some insider if not Georges himself. In any case, the right way to check this is to ask him directly.

2017-06-01 11:07 UTC, maximedenes commented
@gares I addressed your comments. Can you review the changes and approve them if you're ok? Thanks!

2017-06-01 14:30 UTC, gares commented
I did not ask a lawyer and I'm not one.
I still think the license let us do that.

I know that this sort of things were discussed in the context of the joint lab (make it possible for coq to integrate a patch from the JC and have Inria keep all rights). I think I read it in the agreement between the two institutions (I was still a postdoc at the JC).  So at least the intent was clear.

2017-06-01 14:36 UTC, gares approved these changes
Move the global options away plz

2017-06-01 14:55 UTC, maximedenes commented
> Move the global options away plz

done

2017-06-07 09:21 UTC, maximedenes commented
Tests seem ok here: https://travis-ci.org/maximedenes/coq/builds/240018203

The Fiat and bedrock failures are unrelated, we are waiting for upstream merges.

2017-06-07 09:25 UTC, merged