No whd_both in eqappr.
coq/coq pull request #6733
Opened 2018-02-11 09:33 UTC by SkySkimmer

I don't see how this could be useful.
The coverage report from the 2017 workshop agrees with me https://x80.org/coq2017/report/file0006.html#L336
I expect CI to do so as well.

2018-02-11 09:34 UTC, SkySkimmer commented
This is a benchmark from before I changed the checker to match: https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/317/console
```

┌──────────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                          │      user time [s]      │             CPU cycles              │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                          │                         │                                     │                                       │                          │                 │
│             package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD  PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  437.12  448.87 -2.62 % │ 1216191289821 1249538522002 -2.67 % │  2039434173185  2094628553666 -2.64 % │  719408  727884  -1.16 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  163.87  167.23 -2.01 % │  456183375353  465357475928 -1.97 % │   700902552111   715721047661 -2.07 % │  725060  726720  -0.23 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-unimath │ 1211.40 1234.52 -1.87 % │ 3376224468906 3443035829308 -1.94 % │  5918957162102  6006756596500 -1.46 % │ 1044864 1049004  -0.39 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-geocoq │ 3026.54 3082.02 -1.80 % │ 8448072078721 8596300351637 -1.72 % │ 14085486934152 14309633264297 -1.57 % │ 1248316 1248296  +0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-formal-topology │   33.30   33.91 -1.80 % │   93166854738   93545804327 -0.41 % │   123187257054   123288644239 -0.08 % │  482976  482888  +0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  166.27  168.87 -1.54 % │  462403875655  469148453373 -1.44 % │   655996186445   665681952320 -1.46 % │  588044  587900  +0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  262.15  265.48 -1.25 % │  728711324183  738447286742 -1.32 % │  1080049878462  1090925155276 -1.00 % │  982772  983324  -0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  188.78  190.80 -1.06 % │  524749842995  530202702017 -1.03 % │   764544179580   770307376660 -0.75 % │  709464  710676  -0.17 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   39.76   40.18 -1.05 % │  109603002703  110136230435 -0.48 % │   136093684426   136450096455 -0.26 % │  476644  475596  +0.22 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-vst │ 2722.12 2742.80 -0.75 % │ 7592291626946 7650609344746 -0.76 % │ 11137964274312 11207703366242 -0.62 % │ 2218676 2166888  +2.39 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-color │  560.25  563.78 -0.63 % │ 1566279307341 1575320411825 -0.57 % │  1975600668370  1979541613619 -0.20 % │ 1448756 1441148  +0.53 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1346.64 1353.38 -0.50 % │ 3752418651714 3770986409323 -0.49 % │  6622792823648  6641467095985 -0.28 % │ 1022988 1076768  -4.99 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  649.10  651.80 -0.41 % │ 1817762336867 1824175223491 -0.35 % │  2962014372016  2967846073203 -0.20 % │ 3509288 3512828  -0.10 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-flocq │   58.87   59.10 -0.39 % │  162000799669  162404487091 -0.25 % │   209168022960   209274348203 -0.05 % │  644948  646488  -0.24 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-corn │ 1470.36 1476.06 -0.39 % │ 4102771250165 4120465818884 -0.43 % │  6401241025555  6415055653691 -0.22 % │  919792  802280 +14.65 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-bignums │   74.25   74.46 -0.28 % │  206978333682  207594131274 -0.30 % │   281922443549   281893050383 +0.01 % │  519624  523828  -0.80 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-fiat-core │  100.20  100.46 -0.26 % │  286294765938  286601278452 -0.11 % │   372411458519   372981715791 -0.15 % │  499964  500480  -0.10 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│           coq-coquelicot │   75.00   75.08 -0.11 % │  206203838557  207110448827 -0.44 % │   257595545781   258401779863 -0.31 % │  655580  657620  -0.31 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-compcert │  805.63  805.63 +0.00 % │ 2245687847866 2244653568918 +0.05 % │  3411252594522  3416018472756 -0.14 % │ 1352572 1343592  +0.67 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   60.49   60.43 +0.10 % │  166163089401  166937672720 -0.46 % │   231488454536   233607268632 -0.91 % │  523356  527332  -0.75 % │   0   0  +nan % │
├─────────── [...]

2018-02-11 09:41 UTC, maximedenes commented
@SkySkimmer Can you say why one pass on each term would be sufficient to have both of them in whnf?

2018-02-11 13:50 UTC, ppedrot commented
@SkySkimmer Unluckily, it is possible to reach that situation, although I need to think a bit how to craft an example. The problem was discovered by Georges Gonthier, and it is due to the fact that both sides of the term share the same constant cache, and thus updating a reference in one side might affect the other. If you want to be truly allowed to do that, you need to separate the constant cache between the two invocations of reduction. I had a patch that did that at some point, I can probably unearth it.

2018-02-11 18:14 UTC, maximedenes requested changes
Like @ppedrot, I don't think this is correct with the constant cache shared by LHS and RHS in conversion.

2018-02-15 16:44 UTC, gares commented
I think we should close this one

2018-02-15 17:11 UTC, maximedenes commented
The PR yes, but it would be good to keep the branch so that we test the test case, once we come up with one.

2018-03-09 16:05 UTC, SkySkimmer commented
>The PR yes, but it would be good to keep the branch so that we test the test case, once we come up with one.

It's not as though there's any difficulty redoing this. Or with #6769 it's trivial to re-share the constant caches.

2018-03-09 16:05 UTC, closed without merging