Adding a sanity check on inductive variance subtyping.
coq/coq pull request #6740
Opened 2018-02-12 14:44 UTC by ppedrot

Just in case.

2018-02-12 14:50 UTC, SkySkimmer commented
This means that the following will fail:
```coq
Module Type T.
Parameter t : Type.
Inductive I := C : t -> I.
End T.

Module M : T.
Definition t : Type := nat.
Inductive I := C : t -> I.
End M.
```
(with polymorphism and cumulativity on, possibly slightly different universe annotations)
Is that desired?

2018-02-12 15:02 UTC, ppedrot commented
Oh, so indeed it's possible to trigger the anomaly. What's the expected behaviour? Is it something like:

```
u ≤ v := (sup u v) = v
```

I have nothing against such a feature, as long as the pCuIC set-theoretical model validates it... But there is no such thing as modules in the set model!

2018-02-12 15:05 UTC, SkySkimmer commented
That's what I would expect. I don't know how models are justified so I won't try to BS some explanation for it.

2018-02-12 15:06 UTC, ppedrot commented
We wander on dangerous lands here. We need a more principled justification for this kind of tricky questions. I'd play safe and raise at least an exception for now. WDYT?

2018-02-12 16:02 UTC, ppedrot commented
Here is a version that only checks for variance subtyping. Not justified in any ways, but slightly more robust to future changes, including a test.

2018-02-12 16:04 UTC, SkySkimmer commented on test-suite/modules/cumpoly.v
> +Parameter t@{i|Set <= i} : Type@{i}.
You don't need the `Set <= i` here, every variable verifies that.

2018-02-12 16:05 UTC, ppedrot commented on test-suite/modules/cumpoly.v
> +Parameter t@{i|Set <= i} : Type@{i}.
Well, it doesn't hurt to add it altogether.

2018-02-14 20:15 UTC, SkySkimmer requested changes
Also should have a checker counterpart.

2018-02-14 20:15 UTC, SkySkimmer commented on kernel/subtyping.ml
> +      let () = assert (Array.for_all2 Variance.check_subtype (ACumulativityInfo.variance cumi') (ACumulativityInfo.variance cumi)) in
In non debug mode ocaml will remove this assert, I'd rather use an anomaly.

2018-02-15 17:02 UTC, ppedrot commented
@SkySkimmer Added the test in the checker as well, and turned it into an anomaly.

2018-02-15 17:04 UTC, SkySkimmer approved these changes

2018-02-21 08:57 UTC, maximedenes approved these changes

2018-02-21 18:10 UTC, merged