[ssreflect] Export parsing witnesses in mli file.
coq/coq pull request #6795
Opened 2018-02-20 20:12 UTC by ejgallego

This is needed in order to manipulate/serialize SSR's AST.

A quicker [and maybe better] alternative would be to just remove
`ssrparser.mli`, as there are many grammar entries that still need
exporting.

2018-02-22 14:57 UTC, gares requested changes
I believe `ssrast` defines some of these types.
If not, it is where these types should be defined (not the wit_* but the _genarg ones)

2018-02-22 15:19 UTC, ejgallego commented
Oh indeed, I'll try to reverse-engineer them.

2018-02-22 20:15 UTC, gares commented
> I'll try to reverse-engineer them.

Some work was done in #6700 where I use "nicer" types in `ipats.mli`.

2018-02-27 21:52 UTC, ejgallego commented
Ok, rebased on top of #6700 , I tweaked the types the best I could, let me know if you want some more refactoring.

2018-02-27 22:00 UTC, gares approved these changes

2018-03-06 09:14 UTC, merged