Move VM global tables from C to ML
coq/coq pull request #6908
Opened 2018-03-04 11:40 UTC by ppedrot

This PR moves the VM global tables from the C implementation to the ML implementation. We declare them in ML code and pass them as an argument to the C reduction functions. This is a first step towards being able to synchronize this state with the Coq summary, so as to free unused memory, as well as locally replacing the value of a global, e.g. to implement local opacity in the VM.

This also makes the code slightly cleaner, e.g. automatically properly initializing the rel tables without them containing dummy data.

I was afraid that this might have been slower due to the C compiler performing less optimizations, but it doesn't seem to be the case after all. I guess it makes sense, as the pointer is allocated by the OCaml GC anyways.

Bench:
```
┌──────────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │             CPU cycles              │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                     │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   60.44   60.80 -0.59 % │  166428584127  166896752508 -0.28 % │   231469653541   231593430204 -0.05 % │  529468  529564 -0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1338.04 1343.05 -0.37 % │ 3722799312064 3730030746943 -0.19 % │  6591138192844  6588931938305 +0.03 % │ 1002808 1074176 -6.64 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  262.67  263.37 -0.27 % │  728361468299  730425121020 -0.28 % │  1074466695631  1074665224701 -0.02 % │  984344  984600 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 3047.73 3051.96 -0.14 % │ 8476299150818 8486750182257 -0.12 % │ 13965502296280 13967856271799 -0.02 % │ 1240308 1242196 -0.15 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  814.51  814.76 -0.03 % │ 2273965839896 2272410670086 +0.07 % │  3424265355466  3425603069430 -0.04 % │ 1368320 1369244 -0.07 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  169.31  169.32 -0.01 % │  467079817224  466856454705 +0.05 % │   656166961721   656018828796 +0.02 % │  588608  588768 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  659.88  659.57 +0.05 % │ 1840217524385 1843765680640 -0.19 % │  2957382112931  2958206304060 -0.03 % │ 3374380 3348048 +0.79 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coquelicot │   75.43   75.39 +0.05 % │  207446521549  207965394423 -0.25 % │   259630758430   259967721173 -0.13 % │  660052  656348 +0.56 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   75.10   75.05 +0.07 % │  208687387455  208352870670 +0.16 % │   283223957401   283302640068 -0.03 % │  526356  526552 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-color │  570.68  570.26 +0.07 % │ 1586587466967 1585912435822 +0.04 % │  1989591666968  1990298191910 -0.04 % │ 1438704 1439344 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-hott │  309.40  309.14 +0.08 % │  842513689729  842397799466 +0.01 % │  1375685832726  1376007763700 -0.02 % │  496448  496576 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  165.54  165.34 +0.12 % │  459517066767  458971705800 +0.12 % │   699295227362   699416163376 -0.02 % │  714956  715232 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │   59.36   59.23 +0.22 % │  163587367310  163808903677 -0.14 % │   211527066041   211563117381 -0.02 % │  664056  660820 +0.49 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  441.04  439.72 +0.30 % │ 1223911680284 1220353697453 +0.29 % │  2024761406182  2024961143264 -0.01 % │  713300  713760 -0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-corn │ 1479.40 1474.02 +0.36 % │ 4106968669794 4102830785496 +0.10 % │  6397483028130  6400106610373 -0.04 % │  839512  835800 +0.44 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  190.59  189.75 +0.44 % │  526621150340  526430860914 +0.04 % │   761548805325   761445630119 +0.01 % │  716420  716156 +0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  102.73  102.20 +0.52 % │  290549062565  290036335676 +0.18 % │   378266514772   378135129211 +0.03 % │  500864  501416 -0.11 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   40.70   40.48 +0.54 % │  111612473841  111675287704 -0.06 % │   137656515666   137869727221 -0.15 % │  478660  478812 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────── [...]

2018-03-04 14:35 UTC, maximedenes commented
@ppedrot Do you plan to do other VM cleanups?

2018-03-04 14:59 UTC, ppedrot commented
Not for 8.8, I think. This particular PR shouldn't really interfere with your patches, IIUC, it is quite self-contained and local.

2018-03-06 21:32 UTC, silene commented
I thought the code was using a sane allocation strategy, but now that I am reading your patch, it seems like it is the worst possible one (the quadratic one). Don't you want to fix that issue along the way? Other than that, the patch is fine and welcome.

2018-03-07 04:32 UTC, ppedrot commented
@silene I ran the code with an assertion failure for reallocation first, and it seems that on the stdlib, we never reallocate. I could use a O(1) amortized allocation, but actually I'm not sure this happens often in practice...

(Also, reading it carefully, there are memory leaks in the C code, and probably strict pointer aliasing breaking as well. This is making me worried about the overall safety of the VM code. If there is something I don't trust, C code is well ranked on that list.)

2018-03-07 05:47 UTC, silene commented
>  there are memory leaks in the C code, and probably strict pointer aliasing breaking as well

Is that so? A quick search for `*)` did not bring anything interesting up. I would have thought that the C code always reads or writes OCaml's `value`s in and out of memory. You break pointer aliasing only when you read an object with a pointer that has a type incompatible with the pointer used to write the object.

As for memory leaks, do you mean that the compiled bytecode is not freed on backtrack? Or do you have something else in mind?

2018-03-07 11:43 UTC, ppedrot commented
> As for memory leaks, do you mean that the compiled bytecode is not freed on backtrack? Or do you have something else in mind?

Bytecode is indeed never freed, but also a few globally allocated data that are reallocated on resizing of tables. Have a look at the uses of `coq_stat_alloc`.

2018-03-07 11:55 UTC, ppedrot commented
> Is that so? A quick search for *) did not bring anything interesting up. I would have thought that the C code always reads or writes OCaml's values in and out of memory. You break pointer aliasing only when you read an object with a pointer that has a type incompatible with the pointer used to write the object.

I can find at least one suspicious use in `coq_interp.c`, in the `coq_interprete` function there are a few casts of the form
```
pc = (code_t)(sp[0]);
```
where `pc : code_t` and `sp : value*`. Looking at the OCaml headers, `code_t ≡ int32_t*` and `value ≡ int` or `value ≡ long` depending on the architecture.

2018-03-07 12:25 UTC, ppedrot commented
Forget what I said and let's blame the jetlag, it's just a cast `value ↦ int32_t` and those ones are valid.

2018-03-07 12:51 UTC, silene commented
> Have a look at the uses of `coq_stat_alloc`.

As far as I understand, `coq_makeaccu` is fine, and so is `coq_pushpop`, and so are `init_coq_stack`, `init_coq_vm`, and `realloc_coq_stack`.

The only one leaking memory is `coq_tcode_of_code`, which is responsible for storing the bytecode before execution. I must admit that I don't understand what the point of most of this function is; is it some ultimate check that the bytecode is valid and stays so indefinitely? Anyway, there is at least one thing this function does right, it is its allocation, since it is critical that the bytecode is not stored in a block allocated by the GC!

2018-03-07 12:56 UTC, ppedrot commented
> since it is critical that the bytecode is not stored in a block allocated by the GC!

Why so? Is it because it could be moved by the GC and the addresses are absolute?

2018-03-07 13:07 UTC, silene commented
> Why so? Is it because it could be moved by the GC and the addresses are absolute?

Almost. The addresses stored in the bytecode are not absolute. But `coq_interp.c` was not certainly not written to account for the fact that the `pc` register and all the return addresses stored on the stack might surreptitiously become invalid. Using only relative code pointers might have a huge overhead on register-starved architectures like x86 (since it means using two registers for storing `pc` instead of a single one).

2018-03-07 14:09 UTC, ppedrot commented
All right. I was planning to write a patch to allocate the bytecode through the OCaml GC using simple OCaml strings, but I can simply wrap it into an custom block instead.

2018-03-07 15:06 UTC, ppedrot commented
@silene I adapted the reallocation strategy to be efficient.

2018-03-07 17:27 UTC, silene approved these changes

2018-03-07 17:49 UTC, ppedrot commented
> Almost. The addresses stored in the bytecode are not absolute. But coq_interp.c was certainly not written to account for the fact that the pc register and all the return addresses stored on the stack might surreptitiously become invalid. Using only relative code pointers might have a huge overhead on register-starved architectures like x86 (since it means using two registers for storing pc instead of a single one).

I'm slightly hijacking this thread, but as long as the GC is not called in the interpretation function, this should be safe, right? We never allocate in this function, so there cannot be any memory move nor thread rescheduling. It might be slightly dangerous if the OCaml runtime changes (e.g. because of multicore OCaml), but I guess this would already endanger the current VM...

2018-03-07 20:39 UTC, silene commented
> We never allocate in this function

What gave you that idea? There are about 40 calls to `minor_collection` inside this function!

2018-03-09 08:24 UTC, maximedenes commented
@ppedrot is the segfault in fiat parsers a spurious failure?

2018-03-09 09:45 UTC, silene commented
Yay for automated testing. The patch is indeed wrong on several points. The removal of the following lines should have been a red flag, since if a collection happens, then the pointers to the global and atom tables will become invalid.

```
  (*action)(coq_global_data, &coq_global_data);
  (*action)(coq_atom_tbl, &coq_atom_tbl);
```

2018-03-09 09:46 UTC, maximedenes commented
Ok, so postponing. And indeed, hurrah for CI!

2018-03-09 09:47 UTC, silene requested changes
Make code robust to collections.

2018-03-09 15:11 UTC, ppedrot commented
Hopefully this new version is correct w.r.t. the GC kicking in. It needs to be benchmarked though.

2018-03-10 14:06 UTC, ppedrot commented
New bench:
```
┌──────────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │             CPU cycles              │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                     │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   61.10   61.52 -0.68 % │  168375226602  168961812867 -0.35 % │   234748656173   234736935875 +0.00 % │  589936  591912 -0.33 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  101.58  102.05 -0.46 % │  288653313641  288821725174 -0.06 % │   374159511898   374347859197 -0.05 % │  500456  500972 -0.10 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   75.23   75.52 -0.38 % │  208884953706  209599502199 -0.34 % │   282571744188   282903759493 -0.12 % │  531052  531268 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-hott │  317.30  317.72 -0.13 % │  864723887665  865710344523 -0.11 % │  1391894820726  1392399797137 -0.04 % │  496372  496556 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coquelicot │   76.32   76.38 -0.08 % │  210157006688  210131775032 +0.01 % │   263558865784   264083563480 -0.20 % │  717872  716372 +0.21 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  170.10  170.23 -0.08 % │  471040701379  470254897070 +0.17 % │   659813568431   660137104034 -0.05 % │  646148  646332 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   41.54   41.56 -0.05 % │  113707375482  113749875994 -0.04 % │   141196705429   141303500681 -0.08 % │  537788  538116 -0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  191.96  191.92 +0.02 % │  531514566645  530917879414 +0.11 % │   764861371477   765206731463 -0.05 % │  842260  863808 -2.49 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1374.92 1373.67 +0.09 % │ 3819311487833 3816607889153 +0.07 % │  6665739282275  6665782917437 -0.00 % │ 1362636 1357988 +0.34 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  660.18  659.01 +0.18 % │ 1844261288719 1842156132545 +0.11 % │  2955967070989  2958544240723 -0.09 % │ 3333740 3332300 +0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │   59.60   59.40 +0.34 % │  162937373379  163178710902 -0.15 % │   209767846312   209908646719 -0.07 % │  667136  663728 +0.51 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  266.51  265.56 +0.36 % │  739192738455  736611207479 +0.35 % │  1084808197669  1084993968530 -0.02 % │ 1125300 1125024 +0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-vst │ 2970.06 2959.14 +0.37 % │ 8281566472666 8252741583918 +0.35 % │ 11977448091145 11986158302279 -0.07 % │ 2224116 2226304 -0.10 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  460.79  458.70 +0.46 % │ 1280040237854 1273414803102 +0.52 % │  2108255305822  2108305256396 -0.00 % │  814176  814132 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 3052.51 3036.58 +0.52 % │ 8485497199782 8445451949249 +0.47 % │ 13953265223875 13952255608005 +0.01 % │ 1239988 1241008 -0.08 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  170.18  169.27 +0.54 % │  470591253981  468509016053 +0.44 % │   711268929721   711426671126 -0.02 % │  843044  843156 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  812.17  807.44 +0.59 % │ 2264128677983 2252137125143 +0.53 % │  3409735312472  3411770784728 -0.06 % │ 1349204 1349864 -0.05 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-formal-topology │   34.20   34.00 +0.59 % │   94507289654   94337206187 +0.18 % │   123974915554   124123964380 -0.12 % │  482940  483024 -0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-corn │ 1484.29 1463.27 +1.44 % │ 4114303368086 4081073070433 +0.81 % │  6383028907429  6385039866871 -0.03 % │  829364  825184 +0.51 % │   0   0  +nan % │
└──────────────────────────┴─────────────────────────┴─────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```
Looks OK to me.

2018-03-11 13:13 UTC, ppedrot commented
@silene Do you approve the fixes?

2018-03-11 14:01 UTC, silene commented
I do, but given how sensible the code has proved to be, I no longer think it is a good idea right before the release. So I am instead in favor of merging the pull request right after branching on 8.9.

2018-03-11 21:13 UTC, ppedrot commented
@silene Don't worry, this has been moved to 8.9 milestone.

2018-03-11 21:26 UTC, JasonGross commented
@silene Do you mean "sensitive" instead of "sensible"?

2018-03-12 05:46 UTC, silene commented
> Do you mean "sensitive" instead of "sensible"?

Yes.

2018-03-12 05:46 UTC, silene approved these changes

2018-04-20 15:26 UTC, maximedenes approved these changes
LGTM

2018-04-20 15:27 UTC, merged