gitlab: install num for all 4.06 jobs
coq/coq pull request #6928
Opened 2018-03-06 15:00 UTC by SkySkimmer

Previously it was installed for the compilation jobs causing random
failures when the other jobs got a cache without it.

2018-03-06 15:13 UTC, ejgallego commented
IMHO it is safe to install it unconditionally.

2018-03-07 16:57 UTC, ejgallego requested changes
Install `num` unconditionally in the set of base packages.

2018-03-07 18:52 UTC, SkySkimmer commented
As you wish.

2018-03-07 18:53 UTC, ejgallego approved these changes

2018-03-07 18:54 UTC, ejgallego commented
The reason is that even in 4.02.3 , if using an `ocamlfind'ed` build, `num` has to be registered anyways.

2018-03-08 20:58 UTC, merged