Direct implementation of Ascii.eqb and String.eqb
coq/coq pull request #6948
Opened 2018-03-08 17:16 UTC by letouzey

This is an alternative proposal for #6596 : instead of relying on a future improvement of Scheme Equality (#6794), I've directly written boolean equalities for type `ascii` and `string`, since this isn't so hard. For now, I only provide a `eqb_spec` correctness property, based on `Bool.reflect`, see an example of use in `DecimalString.v`. But the amount of properties around these new `eqb` functions could be extended later. We could also decide someday to implement `ascii_dec` and `string_dec` through these new fonctions plus `Bool.reflect_dec`.

2018-03-08 17:32 UTC, JasonGross approved these changes
It might be nice to have a couple more utility lemmas (e.g., `eqb x y = true <-> x = y`, `eqb x y = true -> x = y`, `eqb x x = true`, `x = y -> eqb x y = true`, `eqb x y = false <-> x <> y`) which should all e straightforwardly provable from `eqb_spec`, but, even without those, LGTM.

2018-03-09 14:10 UTC, maximedenes commented
Pipeline running: https://gitlab.com/maximedenes/coq/pipelines/18653548

2018-03-09 15:59 UTC, maximedenes commented
lambda-rust broken it seems

2018-03-09 18:14 UTC, JasonGross commented
From the error message, my guess that lambda-rust uses an unqualified name (e.g., `eqb`), and should be updated to use a the qualified version ( such as `Bool.eqb`) instead.

2018-03-09 19:34 UTC, letouzey commented
The issue with lambda-rust is actually in the iris-coq repository. The fix is indeed trivial, for instance add a `Import Bool.` after the other `Import` at the top of file `theories/proofmode/coq_tactics.v`. Otherwise there are two `eqb` to turn into `Bool.eqb`.

I'll try to prepare an overlay for this, but that's slightly tedious, since the iris-coq used by the lambda-rust CI is some dev snapshot determined through some `grep` into the `opam` file of `lambda-rust`. Maybe we could directly suggest the authors to integrate this little fix (which is backward compatible).

2018-03-09 19:38 UTC, maximedenes commented
> Maybe we could directly suggest the authors to integrate this little fix (which is backward compatible).

Sure, we use overlays primarily for plugins, where fixes are usually not backward-compatible. If the fix is backward compatible, it's easier to just open a PR and put a pointer here.

2018-03-09 20:29 UTC, letouzey commented
Anyway, I just finished building lambda-rust locally with the previous fix, it goes through without more issues.

2018-03-12 09:45 UTC, letouzey commented
I contacted the `iris-coq` authors : https://gitlab.mpi-sws.org/FP/iris-coq/issues/173

2018-03-12 09:56 UTC, letouzey commented
In the meantime, I see no easy way to use an overlay here, due to the "peculiar" way the dependencies are handled in `ci-iris-lambda-rust.sh`: there's a `grep` in the `opam` file of repo `LambdaRust-coq.git`, producing an opam version (currently `dev.2018-02-23.0`) of `iris-coq`. And then a `opam show ... -f upstream-url` turns that version into a direct commit SHA (and not a branch name we can play with). So simple... Of course, I could go and hack directly in `ci-iris-lambda-rust.sh`, but that seems way overkill.

2018-03-12 12:28 UTC, SkySkimmer commented
We could modify the script to make it use overlays. Something like
```bash
if $stdpp_autodetect
then 
  # mess with grep etc
else
  # do nothing, variables set in overlay
fi
git_checkout $stdpp_branch ...
```
Then an overlay would just have to negate `stdpp_autodetect` in addition to the usual variable setting.

2018-03-12 13:23 UTC, letouzey commented
For this time, no need finally to tweak with `ci-iris-lambda-rust.sh`, since Ralf Jung already integrated the change I proposed in https://gitlab.mpi-sws.org/FP/iris-coq/issues/173. To be sure, I've relaunched this travis job on my account.

2018-03-12 14:08 UTC, letouzey commented
Travis was indeed ok this time : https://travis-ci.org/letouzey/coq-wip/jobs/350918522

2018-04-09 17:08 UTC, JasonGross commented
Is this blocking on something?

2018-04-09 17:12 UTC, JasonGross requested changes
Oh, I think this needs an `Extract Inline Constant` for `Ascii.eqb` in `plugins/extraction/ExtrOcamlString.v` and for `Ascii.eqb` and `String.eqb` in `plugins/extraction/ExtrHashellString.v`

2018-07-25 06:40 UTC, closed without merging