New version of the selective-unfolding PR
coq/coq pull request #703
Opened 2017-05-30 16:23 UTC by Lionel-Rieg

This PR is a reimplementation of PR #200. It introduces the possibility to unset the printing of notations in a more fine grained fashion than Unset Printing Notations. One can unfold notations either individually or by scopes.
This is very useful for debugging purposes when having very large notations that should not be unfolded (UTF8 string comes to mind immediately).

It introduces four new commands to activate/deactivate notation either individually or by scope.  Their current syntax (subject to change) is the following:

    Deactivate Notation Scope scope_name.
    Reactivate Notation Scope scope_name.
    Deactivation Notation notation_string [From Scope scope_name].
    Reactivation Notation notation string [From Scope scope_name].

Notation strings are the displayed notations with variables replaced by "_".

I included most of the feedback from PR #200 with the following exceptions:
+ The names of the commands: I agree that @JasonGross 's suggestion is much better but I am not completely sure what @herbelin means by "an ad hoc vernac entry". Does that simply mean adding commands "Set Printing Notation ..." and Co to the command rules?
+ As this only affects the *printing* of notations and not their parsing, I feel like this design really is mostly for debugging and should not be synchronized but feel free to try to make me change my mind
+ There is currently a small bug that seems to make these functions called twice with only one command thus triggering the warnings for already activated/deactivated notations.  I was not able to track it down.

2017-05-30 17:52 UTC, maximedenes commented
> is mostly for debugging and should not be synchronized

We had a related discussion recently at the working group, and it was not clear to us why debugging options should not be synchronized.

2017-05-30 18:04 UTC, ejgallego commented
Lionel means synchronization of printing and parsing, not of options wrt the document.

2017-05-30 18:15 UTC, maximedenes commented
Oh ok, sorry, I didn't infer the context correctly. Thanks!

2017-05-30 21:12 UTC, Lionel-Rieg commented
No no, you were right Maxime, I did mean synchronization of options.  I guess I really was not clear!
To me, these options fall into the same category as the display options (Set Printing All & Co) and I don't think these are synchronized (although that might be due to the fact that I am using my editor to do it and not explicit Coq commands).
I don't mind having them synchronized if you think this is better but I have no experience doing that.  If it is more complex than adding arguments to freeze/unfreeze functions at the end of interp/notation.ml, I will need some help to do it.

2017-05-30 21:39 UTC, ejgallego commented
Oh I see; your internal state is currently "synchronized" by virtue of the state being saved in the summary, that's why I got confused.

Regarding printing options, the plan is to make the core of "externalization" (which is only used by printing) functional, in that sense your references may become owned by the toplevel / IDE.

What @herbelin indeed means about "adhoc vernac entries" is indeed about using the `GOptions` mechanism to set these options and having `constrextern` read that. In that case the proper place to declare this would be `constrextern.ml`. 

Indeed, after reading the patch more carefully I am not convinced by the approach. IMHO, if you are going to hook after un-interpretation then the code should fully live in Constrextern and not modify `Notation`.

2017-05-30 21:41 UTC, ejgallego commented
> the code should fully live in Constrextern and not modify Notation

See indeed how you define a few functions in `Notation` but are never used in this module but only by the preprinter `Constrextern`.

2017-05-30 21:44 UTC, ejgallego requested changes
- consolidate stateful code into `Constrextern`.
- [optional] remove vernacs in favor of the option mechanism.

2017-05-30 21:49 UTC, ejgallego requested changes

2017-05-30 21:49 UTC, ejgallego commented on vernac/metasyntax.mli
> +val notation_activation :
This API shouldn't be here but as it is a printing option it should go to constrintern.

2017-05-30 21:49 UTC, ejgallego commented on vernac/metasyntax.mli
> +val notation_activation :
Please don't use this kind of options type, but named parameters or records.

2017-05-30 21:49 UTC, ejgallego commented on ide/texmacspp.ml
> +  | VernacNotationActivation (None,None,_) -> assert false
Using the table system in `library/goptions` could save some effort here, and additionally make the life for IDEs wanting to introspect this table much easier.

2017-05-30 23:24 UTC, Lionel-Rieg commented
> Indeed, after reading the patch more carefully I am not convinced by the approach.

What do you mean by that?  Is it the location of the code changes or the design of the PR that is in cause?

> the code should fully live in Constrextern and not modify Notation.

Actually, moving the code from Constrextern to Notation was asked by @herbelin as tables about notations are all stored there. See his comment on PR #200.

2017-05-30 23:30 UTC, Lionel-Rieg commented on vernac/metasyntax.mli
> +val notation_activation :
Moving the code interpreting the commands to metasyntax was asked by @herbelin.

Defining a record is much heavier than these two option types and their meaning is quite clear from the code in metasyntax.  So I am not sure about the benefit of switching to records.

2017-05-30 23:37 UTC, ejgallego commented
> What do you mean by that? Is it the location of the code changes or the design of the PR that is in cause?

Sorry this was phrased too strongly. I meant I am not convinced by the solution of putting stuff in `Notation` if you are gonna hook your filter after un-interpretation. I am fine with this approach, however I would then prefer the code to live in the printing part.

> Actually, moving the code from Constrextern to Notation was asked by @herbelin as tables about notations are all stored there. See his comment on PR #200.

I see, IMVHO it would make sense to have the tables there if they are used. However, as they are "printing-only" tables, IMHO it makes more sense for them to live in `Constrextern`. In fact, once externalization is functional `extern : printing_options -> env -> glob_constr -> constr_expr` there will be no tables anywhere. @herbelin, WDYT?

2017-05-30 23:38 UTC, ejgallego commented
A further argument for the tables living in `Constrextern` given the current implementation is that a toplevel could like to run `extern` twice with different settings (to compare or show to the user both terms), this makes the place of the state clearer to me IMO.

2017-05-30 23:38 UTC, ejgallego commented
Other than my minor remarks about code location and maybe using the tables, I think the PR should be ready for 8.7.

2017-05-31 21:03 UTC, maximedenes commented
Test suite seems broken.

2017-06-02 05:51 UTC, maximedenes commented
@Lionel-Rieg can you have a look at the test-suite failures? If they are not too serious and you can fix them while we integrate the other PRs, we can still try to merge this one.

2017-06-02 13:47 UTC, ejgallego commented
Note that after a bit of thinking, I think this PR should not be merged as is; either we move the code as I suggested or a justification for the current design should appear.

Fortunately, the changes are trivial, I could take care of them if you want.

2017-06-02 15:59 UTC, ejgallego commented on vernac/metasyntax.mli
> +val notation_activation :
The benefit of named parameters is documentation, just from looking at the function type I can't infer what the parameters are and you didn't add documentation. You can indeed do:
```
val notation_activation :
?notation:Constrexpr.notation -> ?scope:Notation_term.scope_name -> bool -> uni
```
and now it becomes clear that we have no clue what the meaning for `notation_activation true` is.

2017-06-02 18:47 UTC, Lionel-Rieg commented
As far as code location is concerned, one argument for leaving it in notation.ml is that this PR can be seen as an intermediate step for a hypothetical bigger project about notation management in which one would have even finer control over which notations / notation scopes are active either for parsing or printing; one could define notations without using right away, define named sets of notations that could be turn on or off all at once and so on.  This code would likely reside in notation.ml, and as a preliminary part of this, this PR should also reside in notation.ml.

2017-06-02 19:02 UTC, ejgallego commented
As I said I would be happy with that approach should the filtering had happened pre-uninterpretation.

But as the code stands now it is not a "intermediate step for a hypothetical bigger project", but a printing option, thus I'd much prefer the state to be contained on the printing side, as to make it easier to functionalize the printing state in 8.8. [Not to say the increase on `mli` pollution]

Once that "hypothetical bigger project" starts, it can make its own design choices.

I also think that at least one vernacular should be replaced by the `GOption` handling (and both if possible)

2017-06-02 19:04 UTC, ejgallego commented
@maximedenes IMHO this is ready for 8.7, once the small code location changes happen. I see no point on delaying it, it is really a flag in the printer.

2017-06-02 19:05 UTC, ejgallego commented
@Lionel-Rieg I'd be happy to tweak the PR if you are busy.

2017-06-02 21:23 UTC, Lionel-Rieg commented on vernac/metasyntax.mli
> +val notation_activation :
OK, I made the requested changes.

2017-06-02 21:28 UTC, ejgallego commented on vernac/metasyntax.mli
> +val notation_activation :
Sorry I am annoying but I still can't understand how this function works from the signature. Would you mind adding a comment?

2017-06-02 21:29 UTC, ejgallego commented
Thanks @Lionel-Rieg , my other comment do still apply thou.

2017-06-02 22:10 UTC, Lionel-Rieg commented
I integrated Emilio suggested change for metasyntax.ml and fixed the stm synchronization.
What basically remains is the Goptions change and the location of the code: either in Notation.ml or in Constrextern.ml.  I don't really have a strong preference so unless @herbelin gives good counter-arguments, let us say that @ejgallego wins by default.

Emilio, if you want ot take care of the Goption change, you are welcome to do it.  You will be much faster than me as you already understand this interface.  In this case, make sure to switch to the syntax suggested by @JasonGross: 
> (Unset|Set) Printing Notation Scope[s] scope_name ... scope_name.
> (Unset|Set) Printing Notation notation_string [: scope_name].

2017-06-02 22:11 UTC, ejgallego commented
Here is a version with the tweaks I proposed, feel free to cherry pick the commit. I decided against using the built-in table support as it has a poor API, but we should eventually switch all that structures to a better API.

https://github.com/ejgallego/coq/tree/Lionel-Rieg-selective-unfolding2

2017-06-02 22:15 UTC, ejgallego commented
> Emilio, if you want ot take care of the Goption change, you are welcome to do it. You will be much faster than me as you already understand this interface. In this case, make sure to switch to the syntax suggested by @JasonGross:
> 
> (Unset|Set) Printing Notation Scope[s] scope_name ... scope_name.
> (Unset|Set) Printing Notation notation_string [: scope_name].

Oh we just crossed our comments, see my commit above. I tweaked a couple of things including the interface so lower stratas have a more robust type. Unfortunately I don't think GOptions can support that syntax, so I left the new vernacs in. I also squashed your three commits and extended the commit message itself.

I think it would be still worth tweaking the current version so `inactive_notations_table` is also an efficient `Set` type, printing is already very expensive as to introduce another potential bottleneck.

I can take care of that one.

2017-06-02 23:07 UTC, Lionel-Rieg commented on vernac/metasyntax.mli
> +val notation_activation :
I guess what you miss is that notation and scope must not be both None.  The comment about that is in the .ml file. As there was no comment in this file, I was not sure whether it was an intentional style choice or not.

2017-06-02 23:14 UTC, ejgallego commented on vernac/metasyntax.mli
> +val notation_activation :
Thanks, finally I tweaked the low-level API to make it safer, see https://github.com/coq/coq/compare/trunk...ejgallego:Lionel-Rieg-selective-unfolding2#diff-a891e1226afa2ea34917c17845229f36R86 , now the bad case is pushed up in the code structure.

2017-06-03 00:21 UTC, JasonGross commented
> Unfortunately I don't think GOptions can support that syntax, so I left the new vernacs in. 

Is it possible to use the vernaculars I suggested, even if you're not using `GOptions` under the hood?

2017-06-03 01:22 UTC, ejgallego commented
> Is it possible to use the vernaculars I suggested, even if you're not using GOptions under the hood?

I had a brief try as I much prefer those, but didn't get anywhere; let me look into that in more depth...

2017-06-03 01:25 UTC, ejgallego commented
Well, I think it is possible with a bit of hacking in `g_vernac.ml4` however I am bit short on time for it, feel free to try.

2017-06-03 01:42 UTC, ejgallego commented
Indeed a rewrite of `Goptions` has been in the table for a while; for instance I think @maximedenes pointed out that it was not enough to handle warning options, etc...

I wouldn't mind doing trying to write a first draft supporting the syntax you requested, however, we are past the freeze so no way that could be in 8.7. So dunno what to do here... Ideas welcome but we should definitively agree on the syntax for this one.

The best I know to do today without tricky parsing hacks is:
```
(Add|Remove) Printing Notation Scope scope_name.
(Unset|Set) Printing Notation "notation_string <sep> scope_name".
```
where `<sep> scope_name` would be an optional part that we could then parse to the proper thing, however this would be tricky as <sep> should not be ever confused with some other symbol appearing in `notation_string`.

2017-06-03 06:00 UTC, JasonGross commented
I would be in favor of merging the code paths without the syntax, and allowing the syntax to be a plugin for 8.7, and have a rewrite of GOptions that allows better syntax in 8.8.

2017-06-03 14:39 UTC, ejgallego commented
> I would be in favor of merging the code paths without the syntax, and allowing the syntax to be a plugin for 8.7, and have a rewrite of GOptions that allows better syntax in 8.8.

IMO that doesn't change a lot, in all cases users will have to adapt to new syntax.

2017-06-04 12:01 UTC, Zimmi48 commented
@ejgallego As I understand @JasonGross' suggestion, he is talking about an external plug-in, not one that is distributed with Coq (as in the case of #714. This means that the feature can be tested externally and that Coq doesn't commit to a syntax just yet. To me, it feels like a good idea.

2017-06-04 16:08 UTC, ejgallego commented
As you want folks, API-only part at https://github.com/ejgallego/coq/tree/Lionel-Rieg-selective-unfolding2_only_core

2017-06-04 16:47 UTC, herbelin commented
Hi, the different options discussed are ok to me.

Are these commands supposed to survive sections or modules? Shall the `Global` and `Local` flags be supported?

If the changes to the reference manual are going to be merged now, I would suggest to unify notations. In the rest of the chapter, the first argument to `Notation` is written `{\str}` rather than `"expression"`.

In general, the convention for vernacular commands is to have auxiliary words lowercase, so `from Scope scope_name` rather than `From Scope scope_name`, as in `Combined Scheme id from id'`. But maybe some `: scope_name` would actually be as well consistent with the rest of the syntax, as proposed in a comment above.

In any case, that's nice.

2017-06-04 17:03 UTC, ejgallego commented
> Are these commands supposed to survive sections or modules? Shall the Global and Local flags be supported?

IMHO, in the current state they should have the semantics than printing options.

But if we merge only the core part, state management would be delayed to the plugin.

2017-06-05 16:27 UTC, Lionel-Rieg commented
It seems reasonable to merge only the API part for now and wait until we can have a good syntax before exposing it officially as a feature.
Yet, I think I probably won't be the one writing the plugin to get access to this feature as this is currently beyond my abilities.

It also gives us time to think about pending questions like the Local/Global flags.  In particular, I am still a bit uncomfortable with the fact that we are exposing the inner representation of notations (the string with _ replacing variables).

Emilio, since you already have a commit implementing these changes, do you prefer to merge yours and I close this PR or should I integrate them here?

2017-06-05 17:07 UTC, ejgallego commented
You make a few interesting points, IMO this PR can stay as for now until we chat next week at the IW.

> It seems reasonable to merge only the API part for now and wait until we can have a good syntax before exposing it officially as a feature.

On the other hand merging only the API is not fully satisfactory, as few people would be able to use it. I am not sure what advantages does the plugin bring vs a more traditional solution.

> It also gives us time to think about pending questions like the Local/Global flags.

As of today these flags should match the `Set Printing Foo` behavior. If the code is added to notations much more complex rules may be needed, as the notation scope is.

> In particular, I am still a bit uncomfortable with the fact that we are exposing the inner representation of notations (the string with _ replacing variables).

Indeed, that is a core pitfall of the notation system, other API's that query notations suffer from the same problem.

2017-06-05 17:25 UTC, Lionel-Rieg commented
> On the other hand merging only the API is not fully satisfactory, as few people would be able to use it. I am not sure what advantages does the plugin bring vs a more traditional solution.

My point is precisely not to make it publicly available.  The plugin approach allows people that really need this feature now to get it but makes it clear that it is not officially supported yet.

2017-06-05 17:31 UTC, ejgallego commented
> The plugin approach allows people that really need this feature now to get it but makes it clear that it is not officially supported yet.

Well if people has to download and install the plugin in order to use the feature, currently this is almost as good as not having it.

2017-06-05 18:35 UTC, Zimmi48 commented
@ejgallego
> Well if people has to download and install the plugin in order to use the feature, currently this is almost as good as not having it.

Do you think so? Nobody expressed such concerns in #714. I am under the impression that these two PRs should be treated the same but I might very well be failing to see an important difference that would be justifying to distinguish them.

2017-06-05 18:59 UTC, herbelin commented
> > In particular, I am still a bit uncomfortable with the fact that we are exposing the inner representation of notations (the string with _ replacing variables).

> Indeed, that is a core pitfall of the notation system, other API's that query notations suffer from the same problem.

I was used to consider that this was the canonical representation of notations (as commonly used e.g. by `Locate`, `Print`, `simpl`, `unfold`, etc.). What would be a better representation?

2017-06-05 19:39 UTC, JasonGross commented
> What would be a better representation?

One alternative is to permit the same notation strings that are used to declare notations, and canonicalize them internally.

> Well if people has to download and install the plugin in order to use the feature, currently this is almost as good as not having it.

No, I disagree; I would download and install the plugin so I could use it in debugging, but would not leave any of the vernaculars in my scripts.  On the other hand, if the syntax were available in trunk, I might start using it in scripts.

2017-06-05 19:59 UTC, ejgallego commented
@Zimmi48 I am not familiar with #714 , however I do agree we should treat them the same.
@JasonGross I'd consider this a core debugging feature, so dunno about making it a plugin.

Anyways I am taking a very different approach to notation debugging as outlined in the last WG, I do plan feed the IDEs with a representation where notations can be unfolded on hover, so such directives shouldn't really be needed in the most common cases.

2017-06-05 20:12 UTC, herbelin commented
> One alternative is to permit the same notation strings that are used to declare notations, and canonicalize them internally.

So if you have:
```coq
Notation "f 'o' g" := (fun x => f (g x)) (at level 55).
```
which ones of say `"f 'o' g"`, `"h 'o' k"`, `"_ 'o' _"`, `"_ o _"`, would you like to be accepted? All, I guess then (but not "f o g" of which the status of "o" would be confusing). Maybe even supporting spaces in between, as in `"f    'o'  k"`. In any case, that would be easy to do.

@ejgallego: Can you tell more? I guess you mean having in the ast attributes which contain the unfolding of the notations? Do you mean every possible unfoldings prepared in advance or do you mean the unfolding job made by the interface?

2017-06-06 08:55 UTC, maximedenes commented
I agree with @Zimmi48 @JasonGross and @Lionel-Rieg here, an external plugin would be better if we plan to stabilize the syntax only afterwards. @ejgallego Can you take care of remaining changes?

2017-06-06 12:00 UTC, ejgallego commented
@Lionel-Rieg is OK for you if I force-push the revised branch in this PR then?

2017-06-06 15:31 UTC, Lionel-Rieg commented
> is OK for you if I force-push the revised branch in this PR then?

Sure! Go ahead.

2017-06-06 19:11 UTC, ejgallego approved these changes

2017-06-06 19:12 UTC, ejgallego commented
Ok, pushed. Thanks!

2017-06-09 11:48 UTC, maximedenes commented
@ejgallego This seems ready, right?

2017-06-09 12:50 UTC, ejgallego commented
It is.

2017-06-13 16:20 UTC, maximedenes commented
This doesn't seem to compile anymore. @ejgallego, could you have a look? Thanks!

2017-06-13 20:11 UTC, ejgallego commented
Let's see now... the problem was that I hadn't push to the proper branch.

2017-06-14 13:20 UTC, merged