Fixes #7100: lost of main file location in case of Ltac failure in other file
coq/coq pull request #7107
Opened 2018-03-28 20:10 UTC by herbelin

**Kind:** bug fix

Fixes / closes #7100

It might be an opportunity to question about whether it is relevant to also report on the exact location of an Ltac failure in the source of the Ltac function.

2018-03-28 20:14 UTC, JasonGross commented
> It might be an opportunity to question about whether it is relevant to also report on the exact location of an Ltac failure in the source of the Ltac function.

For some errors like "No matching clause" (or whatever comes from a `match` statement with no matching branches), I'd find it useful to have both the top-level/file location where the tactic was invoked, and also an indication of which `match` statement (location in the source code) had no matches.

2018-03-28 20:15 UTC, ejgallego commented
Why not to go back to the 8.7 semantics? [At least for the 8.8 fix]. As I wrote in the bug report, I'd rather have something as low-level as `Loc.merge` not throwing an exception.

2018-03-28 20:28 UTC, herbelin commented
@ejgallego: yes for no change in 8.8 and yes for option (but that would be an API change for the second yes :wink:).

2018-03-28 20:33 UTC, herbelin commented
@jasongross: I remember that locating `match` failures was not as easy. But we should try to look again at that at some time. (But I would say that it also depends on what Ltac2 does but I did not closely follow how Ltac2 addresses `match`.)

2018-03-28 22:46 UTC, ejgallego requested changes
On agreement with @herbelin , we prefer to revert the change to `Loc.merge` instead this patch; thus `Loc.merge`  shall merge locations even if coming from different files.

First, making `Loc.merge` throw an exception is very problematic unless you adapt all its users to take that into account, which is not done.

Second, I don't really see the rationale as not to allow merging of two locations coming from different files. While I agree that the stricter semantic makes sense, it is not how's been interpreted in actual use I think.

2018-03-29 08:35 UTC, herbelin commented
@ejgallego: I realize that my message was ambiguous. I'm ok to do that 8.8 displays the same message as 8.7 in #7107. However the bug should be fixed.

The problem with merging from different files is the following:
```coq
cat <<EOF > A.v
Require Import A.
Goal False.
foo.
EOF

cat <<EOF > B.v
Ltac foo := (****                                                                                      
****) apply
I.
EOF
```
where, in 8.7, you get a wrong location (highligting only the `f` of `foo`):
```coq
File "./A.v", line 3, characters 0-1:
Error:
In nested Ltac calls to "foo" and "apply I", last call failed.
Unable to unify "True" with "False".
```

About the exception, a survey of where `merge_opt` is used seems to indicate that only `Tactic_debug` is comparing loc coming from different arbitrary sources, so only the latter is really liable to receive an exception.  Thus a solution could be to have a variant of `merge_loc` only for it. By doing so, you're "safe" that the behavior is modified (and fixed) in 8.8 only for Ltac trace printing.

2018-03-29 12:11 UTC, ejgallego commented
Ummm, I think we should specify more what location merging is. I am OK with any solution that doesn't involve adding a new exception to such a low-level function [as then you have to modify every caller to account for it].

Based on what you say it seems that instead of adding a new location merge function for `Tactic_debug`, a new _check_ `location_from_same_file` should be added there.

2018-04-11 17:32 UTC, maximedenes commented
@herbelin @ejgallego What is the status of this? Is it going to be ready by tomorrow for 8.8.0 inclusion?

2018-04-11 19:14 UTC, herbelin commented
To my eyes, it is ok. A compatible API, reverting changes to `Loc.merge`, as discussed with @ejgallego, using instead an independent function.

2018-04-11 19:14 UTC, ejgallego approved these changes
Looks good to me, thanks!

2018-04-11 19:15 UTC, ejgallego commented
Sorry I missed @herbelin update. This looks good to me [didn't test but I assume Hugo has tested it and it fixes the problem]

We may want to keep evolving error / location handling, but for now the fix is ready for 8.8.

2018-04-11 19:51 UTC, Zimmi48 commented
So now this is waiting action from @ppedrot.

2018-04-11 23:32 UTC, ppedrot approved these changes
I'm not sure I really support location surgery, in particular when trying to make sense of Ltac shenanigans, but at least the current patch seems isolated enough to be integrated without much fuss.

2018-04-12 06:50 UTC, herbelin commented
Why shenanigans? You evaluate a sentence. It contains a tactic, which contains a subcall with arguments to an ltac-defined tactic which try to interpret one of its arguments and interpreting this argument fails. Each of these nested calls is potentially able to locate the expression, but does not do it necessarily (e.g. because the location is not available). Which location(s) do we give? This kind of scenario happens in any kind of tactic or not tactic language? Are you e.g. suggesting printing instead the loc of each step of the call stack?

2018-04-12 09:09 UTC, ppedrot commented
> Are you e.g. suggesting printing instead the loc of each step of the call stack?

That's what virtually all languages all there do, so yes, for uniformity (and somehow clarity of semantics, although such callstacks are nonetheless an artifact of the implementation). But anyways I'm not complaining, let's merge.

2018-04-12 09:11 UTC, merged

2018-04-12 09:17 UTC, herbelin commented
I know that you are not complaining about the PR! I was mainly trying to understand what you had in mind and how to turn it in my own mind into some effective possible directions where to go.

Actually, there are several situations where we would need the ability to visually report about multiple locations.