Option -distrust-sections to retypecheck at section end.
coq/coq pull request #7118
Opened 2018-03-29 18:04 UTC by SkySkimmer

(when the option is set) We call cooking from outside the kernel then translate to a constant entry. This just means messing with futures for opaque constants and getting back the non-abstract universes for polymorphic constants.

Not tested with vio/IDE async.

Closes #6389.

- [ ] Corresponding documentation was added / updated.
- [ ] Entry added in CHANGES.

2018-03-29 18:11 UTC, ejgallego commented
Fantastic.

2018-03-30 11:07 UTC, SkySkimmer commented
That's not so bad, shall we make it the default?
```

┌──────────────────────────┬──────────────────────────┬────────────────────────────────────────┬────────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                          │      user time [s]       │               CPU cycles               │            CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                          │                          │                                        │                                        │                          │                 │
│             package_name │     NEW     OLD  PDIFF   │            NEW            OLD  PDIFF   │            NEW            OLD  PDIFF   │     NEW     OLD  PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-formal-topology │   38.18   37.45  +1.95 % │   103051802990   100835318904  +2.20 % │   129087188395   125578420479  +2.79 % │  489848  483716  +1.27 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-fiat-core │  113.50  111.08  +2.18 % │   315020791442   309025464252  +1.94 % │   386731486686   376974629469  +2.59 % │  504688  502388  +0.46 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-vst │ 4157.06 4061.59  +2.35 % │ 11568323492201 11295102672140  +2.42 % │ 15384741871958 14907137059374  +3.20 % │ 2234612 2226704  +0.36 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│           coq-coquelicot │   83.44   81.31  +2.62 % │   231077639253   224358992442  +2.99 % │   276067621794   265459804248  +4.00 % │  723940  715288  +1.21 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-bignums │   83.24   80.10  +3.92 % │   229961872397   220336889480  +4.37 % │   300020348904   285861854122  +4.95 % │  529316  527412  +0.36 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-corn │ 1660.71 1563.47  +6.22 % │  4596790338084  4326431101795  +6.25 % │  6898879611603  6417229412802  +7.51 % │  912024  874944  +4.24 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   48.49   44.65  +8.60 % │   133078602869   122258958143  +8.85 % │   158856598423   142765509914 +11.27 % │  540628  537688  +0.55 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-compcert │  931.33  856.19  +8.78 % │  2582481162986  2374857367586  +8.74 % │  3700197490198  3428442936592  +7.93 % │ 1324868 1322316  +0.19 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  779.81  703.64 +10.83 % │  2159167700769  1947844488412 +10.85 % │  3326990143418  2975158473326 +11.83 % │ 3524828 3368296  +4.65 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-hott │  369.30  332.06 +11.21 % │  1025713882165   919126203625 +11.60 % │  1595516771032  1426135636140 +11.88 % │  614884  599040  +2.64 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-flocq │   74.58   63.30 +17.82 % │   205775376768   174341780770 +18.03 % │   259424704508   211649918559 +22.57 % │  667828  664008  +0.58 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-geocoq │ 3674.43 3083.38 +19.17 % │ 10198742501764  8551709667057 +19.26 % │ 16714394632037 13800021929654 +21.12 % │ 1217492 1241604  -1.94 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  225.81  185.25 +21.89 % │   624581782687   511511958136 +22.11 % │   869687789966   690017795729 +26.04 % │  661748  646416  +2.37 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   79.28   64.47 +22.97 % │   218434441760   177113143071 +23.33 % │   301759227952   236048322862 +27.84 % │  609092  593088  +2.70 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1782.94 1423.18 +25.28 % │  4954590548148  3952410841352 +25.36 % │  8120272001158  6665162262815 +21.83 % │ 1389496 1411920  -1.59 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  252.84  201.42 +25.53 % │   699704648713   557142390247 +25.59 % │   989752127997   767737127241 +28.92 % │  893852  867084  +3.09 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  229.28  172.85 +32.65 % │   636240407816   477619731984 +33.21 % │   959356040685   700488871145 +36.96 % │  922408  843132  +9.40 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  610.75  460.14 +32.73 % │  1697297125404  1276891056373 +32.92 % │  2783821512018  2061515168600 +35.04 % │  870940  814548  +6.92 % │   0   0  +nan % │
├──────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  386.54  273.94 +41.10 % │  1073066727018   759822072622 +41.23 % │  1582159389888  1081587864330 +46.28 % │ 1234892 1072868 +15.10 % │   0   0  +nan % │
└──────────────────────────┴──────────────────────────┴────────────────────────────────────────┴────────────────────────────────────────┴──────────────────────────┴─────────────────┘

```
^^

2018-03-30 13:38 UTC, ejgallego commented
> That's not so bad, shall we make it the default?

Well, the benchmark is not fair if you don't first disable typechecking inside a section, right?

2018-03-30 13:40 UTC, maximedenes commented
> Well, the benchmark is not fair if you don't first disable typechecking inside sections, right?

But if you do that, you get incorrect universe constraints, and potentially change the behavior of tactics/unification, no?

2018-03-30 15:13 UTC, ejgallego commented
> But if you do that, you get incorrect universe constraints, and potentially change the behavior of tactics/unification, no?

Does `Qed` influence that?

2018-03-30 15:14 UTC, maximedenes commented
I thought so, because the body influences the constraints, in principle. But I'm always wrong on universes, so... :)

2018-03-30 15:20 UTC, SkySkimmer commented
The kernel doesn't generate constraints (for definitions), but it does check them. So you could make a definition which should fail but it waits until the section ends to raise an error (and so you can't test it with Fail etc).
In general if we wait until section end to run the kernel some errors will happen at the wrong location.
What we could do is trust for intermediate sections, ie
```coq
Section Outer.
Section Inner.
Definition foo := bla. (* kernel checks, maybe fails *)
End Inner. (* kernel trusts *)
End Outer. (* kernel checks again, failure not expected *)
```

2018-03-30 15:35 UTC, gares commented
Can you explain me what it does/changes exactly.
I'm not so sure I understand it entirely from the patch, and I want to be sure it is compatible with the (future) plan of discharging everything immediately (just before the Qed) and re-instantiate things inside the section (to behave as we do today).

2018-03-30 15:51 UTC, SkySkimmer commented
If we trust sections the kernel gets a `Cooking.recipe`, runs it through `cook_constant` (which does the discharge stuff) to get a `Cooking.result` then builds the constant info from that.
If we don't trust sections we call `cook_constant` outside the kernel and build a constant entry from that (this is just undoing `abstract_universes` and moving opaque bodies between future boxes). Then the kernel produces the `Cooking.result` by checking the entry.

If this interferes with future changes removing the option should be easy (I think it might just disappear if we discharge early).

2018-04-01 16:49 UTC, ejgallego reviewed
That looks interesting and I approve it, but I'll let people more knowledgeable on the kernel to tick the green mark.

For "timing" fairness, you could indeed add an option to disable type-checking inside the sections when the flag is set.

2018-04-04 13:11 UTC, maximedenes reviewed
A few remarks/questions before I make a more careful review of the kernel code:
- What is the motivation for this option? You write it is for developers, so what benefits are developers expected to get from it?
- The documentation of this option in "usage" should be improved (say what it does, not just that it is meant for developers)
- Documentation is missing in man pages

2018-04-04 13:13 UTC, SkySkimmer commented
>What is the motivation for this option? You write it is for developers, so what benefits are developers expected to get from it?

@ejgallego asked for it, and I wanted to learn about the discharge system.

2018-04-04 13:14 UTC, maximedenes commented
> @ejgallego asked for it, and I wanted to learn about the discharge system.

Sorry, but I didn't mean your personal motivation for implementing it, I meant the motivation for providing this option as part of the system :)

2018-04-04 15:11 UTC, maximedenes commented
> Well, the bug wasn't closed as "not valid", nor even contested, so that's usually make it looks like implicit acceptance of the request.

As far as I'm concerned, silence usually means that I'm busy, rather than I implicitly accept :) It may be different for others.

2018-04-04 15:49 UTC, ejgallego commented
> As far as I'm concerned, silence usually means that I'm busy, rather than I implicitly accept :) It may be different for others.

Well sure, I mean, it looks like nobody opposed to it, that doesn't mean approval of course.

2018-04-05 11:32 UTC, maximedenes commented
I still don't see the point of this option, so I recommend closing this PR.

2018-04-05 13:03 UTC, herbelin commented
About the PR: I did not look closely at the code in `Term_typing`, but discharging is already done in the kernel actually. So why not to add an `infer` at the end of `Term_typing.translated_recipe` (when the distruct option is on) rather than duplicating code for discharging in `Discharge`.

More generally, if the analysis of Lean's [backward step ](https://github.com/coq/coq/issues/6254#issuecomment-377206303) leads to conclude that the "intuitive" model (in the sense of "you manipulate what you see without hidden implicit arguments") is more tractable, why not to keep sections in the kernel, giving a proper "theoretical" status to discharging?

There would be several ways to formally implement a discharge rule. For instance, here is the general idea for a small-step discharging rule:
```
Γ, x:U, Γ', c : T, Γ'' ⊢
-----------------------------------
Γ, x:U, Γ', c : Πx:U.T, Γ''[cx/c] ⊢
```
and we would need similar rules for discharging constraints, universes and local definitions, plus a final rule to erase a declaration which does not occur anywhere else.

Such a small-step rule would not be efficient, but we could as well have e.g. a big-step discharging rule:
```
Γ, Δ ⊢
----------------------------------
Γ, gen(x1..xn,u1..un,w1,..,wn,Δ) ⊢
```
with `Δ` a context  of assumptions, definitions, universes and constraints (i.e. `Δ` ::= empty | `Δ, u:univ` | `Δ, w:constraint` | `Δ, x:=c:t` | `Δ,  x:T)` and `gen(x1..xn,u1..un,w1,..wn,Δ)` denoting the generalization of `Δ` with respect to a given subset of its variables.

No need anymore, then, for the current approach which does a reset and trustfully pushes again constants which travel with no good reasons outside the kernel.

2018-04-05 18:39 UTC, maximedenes commented
Ok, adding a label to reflect that.

2018-04-05 18:41 UTC, maximedenes commented
Can you clarify what kind of input you are expecting from the devs, though? If you want to make progress.

2018-04-05 18:53 UTC, ejgallego commented
> Can you clarify what kind of input you are expecting from the devs, though? If you want to make progress.

In particular I would like to:
- understand why the right fix is to abandon this idea and not for example, to just delay checking,
- why this option is a problem if inactive,
- have time to process @herbelin 's comments, as well as to understand the patch,
- hear more opinions of other experts, of course.

2018-04-05 18:55 UTC, SkySkimmer commented
>   * understand why the right fix is to abandon this idea and not for
 >     example, to just delay checking,

End should never fail.

Gaëtan Gilbert

On 05/04/2018 20:53, Emilio Jesús Gallego Arias wrote:
>     Can you clarify what kind of input you are expecting from the devs,
>     though? If you want to make progress.
> 
> In particular I would like to:
> 
>   * understand why the right fix is to abandon this idea and not for
>     example, to just delay checking,
>   * why this option is a problem if inactive,
>   * have time to process @herbelin <https://github.com/herbelin> 's
>     comments, as well as to understand the patch,
>   * hear more opinions of other experts, of course.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/7118#issuecomment-379040515>, or mute 
> the thread 
> <https://github.com/notifications/unsubscribe-auth/ACWQ7CrLMgj0be_pVCaaljFjdbbFvcKyks5tlmg2gaJpZM4TAv4E>.
>

2018-04-05 18:56 UTC, SkySkimmer commented
Well, section End, modules have subtyping I guess.

Gaëtan Gilbert

2018-04-05 19:02 UTC, ppedrot commented
As far as I'm concerned, I like the patch as an experiment, to see what is actually brought by sections in terms of performance. Nonetheless, I don't quite see the interest of having this directly in Coq, as explained by @maximedenes we already have coqchk. And when the latter doesn't work, well, that means we should put more efforts in it!

2018-04-11 09:02 UTC, gares commented
Delaying the type checking at the end of the section is not desirable: you want errors to be reported ASAP.

I don't see the point of this patch.

2018-04-11 09:02 UTC, gares requested changes
close

2018-04-11 20:02 UTC, herbelin reviewed
Formally validating the "review" button. See above for my comments at this time.

2018-04-30 07:30 UTC, maximedenes commented
Closing this, following the discussion in #6389. Interesting experiment, though.

2018-04-30 07:30 UTC, closed without merging