[ltac] Deprecate nameless fix/cofix.
coq/coq pull request #7200
Opened 2018-04-08 23:42 UTC by ejgallego

LTAC's `fix` and `cofix` do require access to the proof object inside
the tactic monad when used without a name. This is a bit inconvenient
as we aim to make the handling of the proof object purely functional.

Alternatives have been discussed in #7196, and it seems that
deprecating the nameless forms may have the best cost/benefit ratio,
so opening this PR for discussion.

See also #6171.

**Kind:** documentation / bug fix / feature / performance / infrastructure.

Fixes / closes #????

- [ ] Corresponding documentation was added / updated.
- [ ] Entry added in CHANGES.

2018-04-08 23:42 UTC, ejgallego commented
This would really help 8.9; I wonder what you think folks.

2018-04-09 07:27 UTC, gares commented on doc/RecTutorial/RecTutorial.tex
>  hypothesis in the context, named as the current theorem, and with the
This line is wrong

2018-04-09 07:27 UTC, gares requested changes
fix the spec

2018-04-09 07:29 UTC, gares commented
I'm fine with the deprecation

2018-04-09 14:13 UTC, ejgallego commented on doc/RecTutorial/RecTutorial.tex
>  hypothesis in the context, named as the current theorem, and with the
What's the problem @gares ?

2018-04-09 14:14 UTC, ejgallego commented
> fix the spec

Oh indeed !

2018-04-09 16:29 UTC, ejgallego commented on doc/RecTutorial/RecTutorial.tex
>  hypothesis in the context, named as the current theorem, and with the
ah I see, thanks.

2018-04-09 16:31 UTC, ejgallego commented
> I've clarified in my comment above. If the thing is deprecated the doc should say so, and possibly put forward the non-deprecated form of the tactic.

You mean only in that "tutorial" right? Because, AFAICS the "nameless" from is not even documented in the manual.

2018-04-09 16:35 UTC, ppedrot approved these changes
Good to me.

2018-04-09 16:37 UTC, ejgallego commented
This looks ready to me, if it turns out indeed that the form this PR proposes to deprecate is not even documented then IMHO we should go ahead.

Indeed, it seems pretty bad practice that renaming a lemma would break its own proof.

2018-04-11 08:53 UTC, gares approved these changes

2018-04-11 09:09 UTC, ejgallego commented
@gares I see you've set the milestone, what's the rationale?

2018-04-11 11:54 UTC, gares commented
> This would really help 8.9

I thought you wanted to aim at 8.9

2018-04-11 12:09 UTC, ejgallego commented
> I thought you wanted to aim at 8.9

I wanted to remove the syntax for 8.9, so then the deprecation should go into 8.8; it is very late anyways but leaving the decision to the RMs. IMHO not a lot of harm deprecating and discussing the actual removal in #7196

2018-04-11 12:12 UTC, maximedenes commented
How many times is the warning emitted on our CI roughly?

2018-04-11 12:16 UTC, ejgallego commented
> How many times is the warning emitted on our CI roughly?

In #7196 I counted the use of this from to be less than 10 in total.

2018-04-11 12:17 UTC, ejgallego commented
Compcert uses the deprecated form 8 times in a single file.

2018-04-12 13:10 UTC, gares commented
Thanks for reporting: math-comp/math-comp#190

2018-04-12 13:13 UTC, gares commented
I put the milestone back to 8.8, and let the RM postpone if too late then.

2018-04-12 18:33 UTC, maximedenes requested changes
If you want this in 8.8.0, can you move the item to the right place in `CHANGES`?

2018-04-12 18:33 UTC, maximedenes commented
This needs a rebase.

2018-04-13 10:13 UTC, ejgallego commented
Done and done.

2018-04-16 06:40 UTC, maximedenes approved these changes

2018-04-16 06:41 UTC, maximedenes commented
@ppedrot Can you merge this PR this morning? Thanks!

2018-04-16 06:59 UTC, ppedrot commented
@maximedenes For some reason, the merge script is not working currently. I suspect the network I'm on right now (at ESOP) is blocking ssh requests... I don't have much time to find a workaround, could you perform the merge instead?

2018-04-16 07:10 UTC, merged

2018-04-16 19:00 UTC, maximedenes commented
> Hi, maybe not a big deal, but there is still a cofix in Streams.v which raises a warning at compile time. (I can make a PR if noone else has time for it.)

Ah! Yeah, if you can do it, it would be welcome. I'm still working on the final passes on the manual.

2018-04-16 20:12 UTC, herbelin commented
Maybe was it because it was a `cofix` and the grep did not catch it? Anyway, that the advantage of "human continuous integration".