removing uggly error message of #5147
coq/coq pull request #7203
Opened 2018-04-09 10:04 UTC by forestjulien

**Kind:** documentation / bug fix / feature / performance / infrastructure.
King:bugfix

Fixes / closes #5147

2018-04-09 16:19 UTC, gares requested changes
Clarify the error message

2018-04-09 19:29 UTC, forestjulien commented on plugins/funind/functional_principles_types.ml
> +            else user_err Pp.(pr_constr_env (Global.env ()) !evd f ++spc () ++ str "should be a function")
Done

2018-04-10 14:12 UTC, gares approved these changes

2018-04-10 14:14 UTC, gares commented
Assigning to the other owner of this code.

2018-04-11 08:09 UTC, maximedenes commented
@Matafou I believe the failure is unrelated, and was happening because of heavy load on Appveyor's VMs.

2018-04-11 08:48 UTC, merged