[api] Move bullets and goals selectors to `proof/`
coq/coq pull request #7339
Opened 2018-04-24 16:50 UTC by ejgallego

`Vernacexpr` lives conceptually higher than `proof`, however,
datatypes for bullets and goal selectors are in `Vernacexpr`.

In particular, we move:

- `proof_bullet`: to `Proof_bullet`
- `goal_selector`: to a new file `Goal_select`

2018-04-25 07:32 UTC, Zimmi48 approved these changes
I like these changes. The split of the bullets and the goal selectors is what I had suggested when you created this `Proof_bullet` module so I can only approve it. Doesn't this change the dependency order between proof and vernac though?

2018-04-25 08:15 UTC, herbelin reviewed
LGTM

2018-04-25 09:25 UTC, gares commented on printing/ppvernac.ml
> +  let pr_inline = let open Declaremods in function
What is this?

2018-04-25 09:26 UTC, gares requested changes
the `Declaremods` open seems unrelated, the rest is fine

2018-04-25 10:51 UTC, ejgallego commented
> the Declaremods open seems unrelated, the rest is fine

@gares solved.

2018-04-25 11:24 UTC, gares approved these changes

2018-04-30 13:16 UTC, ejgallego commented
Rebased; @Zimmi48 want to take this as the secondary `proofs` maintainer?

2018-04-30 20:13 UTC, Zimmi48 commented
Sure, I can self-assign this, unless @ppedrot does it before me. BTW, it looks like VST is once again failing all over the place.

2018-04-30 20:35 UTC, Zimmi48 commented
Thanks @SkySkimmer! In this case, it looks like it is us who will need to fix our CI.

2018-05-02 13:04 UTC, Zimmi48 commented
CI passed. Changes outside `proofs/` and `pretyping/` are trivial and do not deserve a specific review. Merging.

2018-05-02 13:05 UTC, merged