Updating CI to recent changes in Mtac2 (former MetaCoq)
coq/coq pull request #7350
Opened 2018-04-25 17:31 UTC by beta-ziliani

**Kind:** infrastructure.

Unicoq (mater) and Mtac2 (master-sync) should compile with current coq's HEAD.

2018-04-25 17:34 UTC, ejgallego approved these changes
Looks good to me, waiting for the CI and will merge.

2018-04-25 17:47 UTC, ejgallego requested changes
Please update:
- .gitlab-ci.yml
- .circle-ci/config.yml
- .travis.yml

to add the jobs. Indeed that's is a pain, and the doc may not be up to date.

Changes are very mechanical.

2018-04-25 17:55 UTC, beta-ziliani commented
Done, although I must admit I just copy-pasted and s/x/mtac2 code around, not sure if it's OK

2018-04-25 17:56 UTC, ejgallego approved these changes
That should work, but we will know when the CI runs.

2018-04-25 18:00 UTC, ejgallego commented
Also, you may want to squash these 3 commits, IMHO the belong logically together.

2018-04-25 18:08 UTC, beta-ziliani commented
I do, but how?

2018-04-25 18:12 UTC, ejgallego commented
> I do, but how?

Oh that's a typical git operation:
- rebase interactively, then mark the last two for squash
- force push to this branch

2018-04-25 18:25 UTC, beta-ziliani commented
thanks once again @ejgallego for the git crash course ;-)

2018-04-25 20:07 UTC, SkySkimmer commented on dev/ci/ci-basic-overlay.sh
> +: "${mtac2_CI_BRANCH:=master-sync}"
Is this a for-CI branch?

2018-04-25 20:09 UTC, SkySkimmer commented
Do you have a gitlab run and a full travis run (travis only runs some "core" jobs for PRs so the new job won't appear here) somewhere?
If not I can make them.

2018-04-25 20:13 UTC, SkySkimmer commented on dev/ci/ci-mtac2.sh
> +mtac2_CI_DIR=${CI_BUILD_DIR}/Mtac2
This script could be split in 2 (ie adding a ci-unicoq script). You would have to add the dependency information in Makefile.ci and add a unicoq job and dependency info in the circle CI yml (look at the `requires:` entries).

2018-04-26 11:04 UTC, ejgallego commented
Full builds at:

- https://travis-ci.org/ejgallego/coq/builds/371500832
- https://gitlab.com/ejgallego/coq/pipelines/21124793

I suggest we leave the two contributions together for now, once UniCoq is used by another package we can factor it. It could be even merged in Coq IIUC.

2018-04-26 12:42 UTC, beta-ziliani commented
@SkySkimmer I was told to keep it in one, so for now let's do that.  Thanks you two for the help. I need to plan a major change in Unicoq, I'll talk to @mattam82 .

2018-04-26 12:55 UTC, SkySkimmer approved these changes

2018-04-26 18:12 UTC, ejgallego commented
Pipelines in travis and gitlab passed, will merge as soon as appveyor catches up.

2018-04-26 20:49 UTC, merged