Four new lemmas for lists
coq/coq pull request #7372
Opened 2018-04-27 16:44 UTC by bartavelle

**Kind:** feature

This adds 4 new lemmas for lists, most of them being adaptation of similar lemmas from other places.

The proofs might be clumsy, and I do not know how to name `ext_in_map`, as I do not understand the naming convention behind `map_ext_in`.

2018-04-27 22:36 UTC, anton-trunov commented
Let me give those lemmas a try too :)

Several proofs of the first lemma:
```coq
Lemma ext_in_map:
  forall (A B : Type)(f g:A->B) l, map f l = map g l -> forall a, In a l -> f a = g a.
Proof.
  (* Proof 1 *)
  induction l as [|h l' IHl]; intros Hm ? []; subst; injection Hm; auto.
  Undo.
  (* Proof 2 *)
  induction l; intros Hm ? []; subst; injection Hm; auto.
  Undo.
  (* Proof 3 -- generates the smallest proof term of these three proofs *)
  induction l; intros [=] ? []; subst; auto.
Qed.
```

The second lemma:
```coq
Lemma skipn_all l: skipn (length l) l = nil.
Proof. now induction l. Qed.
```

The third lemma:
```coq
Lemma skipn_app n:
  forall l1 l2,
    skipn n (l1 ++ l2) = (skipn n l1) ++ (skipn (n - length l1) l2).
Proof. induction n; auto; intros [|]; simpl; auto. Qed.
```

The fourth lemma (harmonized names with the surrounding code):
```coq
Lemma seq_last : forall len start,
  seq start (S len) = seq start len ++ [start + len].
Proof.
  induction len as [|len' IHlen]; intros; simpl in *.
  - now rewrite Nat.add_0_r.
  - now rewrite Nat.add_succ_r, IHlen.
Qed.
```

2018-04-27 22:40 UTC, SkySkimmer commented on theories/Lists/List.v
> +    seq s (S l) = seq s l ++ [s + l].
How about restating this one with `l + s`? It should compute better during the proof.

2018-04-28 06:44 UTC, bartavelle commented
I updated the proofs, and added a fifth lemma, which might not be generic enough to warrant inclusion.

2018-04-28 06:45 UTC, bartavelle commented
argh, I somehow added the previous commit in my pr.

2018-04-28 06:46 UTC, bartavelle commented
Well, if someone knows how to prevent it from being in this PR, I am interested!

2018-04-28 07:46 UTC, Zimmi48 commented
> Well, if someone knows how to prevent it from being in this PR, I am interested!

I think you fixed whatever needed to be fixed, right? Because I don't see anything wrong with the commits as they are now.

2018-04-28 08:01 UTC, bartavelle commented
@Zimmi48 yup, I rewrote the whole PR.

2018-04-28 08:43 UTC, anton-trunov commented on theories/Lists/List.v
> +    (x < length l)->
This should be `x <= length l`, right?

2018-04-28 09:53 UTC, anton-trunov commented
Alternative proof for `firstn_skipn_rev` not requiring induction (but probably can be simplified further).
First of all, we need an auxiliary lemma (an analogue of `firstn_length_le`):

```coq
Lemma skipn_length_le :
   forall n l,
   n <= length l -> length (skipn n l) = length l - n.
Proof.
  induction n; intros l Hle.
  - now rewrite Nat.sub_0_r.
  - destruct l; simpl in *; [| apply le_S_n in Hle]; auto.
Qed.
```

Now we can prove `firstn_skipn_rev`:
```coq
Lemma firstn_skipn_rev: forall x l,
    x <= length l ->
    firstn x l = rev (skipn (length l - x) (rev l)).
Proof.
  intros x l Hle.
  rewrite <-(firstn_skipn x l) at 3.
  rewrite rev_app_distr, skipn_app, rev_app_distr, rev_length.
  rewrite (skipn_length_le _ Hle), Nat.sub_diag; simpl; rewrite rev_involutive.
  rewrite (app_nil_end (firstn x l)) at 1; f_equal; symmetry.
  apply length_zero_iff_nil; rewrite rev_length.
  rewrite skipn_length_le; rewrite rev_length, skipn_length_le; auto.
  apply Nat.sub_diag.
Qed.
```

2018-04-28 14:08 UTC, bartavelle commented
@Zimmi48 sure.

2018-04-28 15:06 UTC, Zimmi48 commented
To whom it may concern: Please ignore the GitLab CI failure.

Another remark in passing @bartavelle: in the future, you are advised to open PRs from dedicated topic branch, and not from your master branch. Indeed, it could create trouble if we were to request that you rebase your branch on the latest master for instance. (In the case of this PR, it won't likely be needed though.)

2018-05-01 13:04 UTC, bartavelle commented
@Zimmi48 how is that a problem? I already rebased it when I included the wrong commit.

2018-08-03 17:21 UTC, bartavelle commented
ping! Is this PR going anywhere?

2018-08-03 17:47 UTC, Zimmi48 commented
@bartavelle Sorry about that. Can you rebase once more on the latest master? The previous maintainer for the standard library left the team. Rebasing will allow to ping the new maintainer.

2018-08-05 17:40 UTC, JasonGross commented on theories/Lists/List.v
> +  forall (A B : Type)(f g:A->B) l, map f l = map g l -> forall a, In a l -> f a = g a.
It might be nice to also have an `iff` version of this lemma.

2018-08-16 16:44 UTC, ppedrot reviewed
I don't have an opinion on this PR. Changes to the standard library are subject to the usual cohort of bikeshedding regarding naming and formulating conventions, and AFAICT we did not come up with a consistent set of rules yet. Similarly, it is not clear what should and should not be inside a standard library. So I cannot really take a decision here. Unluckily, I ended up being the main maintainer of this part of the stdlib after Letouzey's leave, so I am now kind of stuck here. Maybe asking @maximedenes who is the main driver of Stdlib2 could be a good thing.

2018-09-26 12:43 UTC, ppedrot commented
@maximedenes ping.

2018-09-26 12:45 UTC, maximedenes commented
@ppedrot I'm not qualified to take editorial decisions on stdlib1. In fact, it is precisely because of this unability that I suggested we started working on a new library. Sorry about that.

2018-09-26 12:48 UTC, ppedrot commented
OK. I think I'll deassign from this PR because I don't know what to do then.

2018-09-26 13:02 UTC, vbgl commented on theories/Lists/List.v
> +
There is a stronger provable result:

```
Lemma length_skipn n :
  forall m, length (skipn n m) = length m - n.
Proof.
  elim n; clear n.
  - intros m; simpl; lia.
  - intros n ih []; simpl; auto.
Qed.
```

2018-09-26 13:04 UTC, anton-trunov commented on theories/Lists/List.v
> +  Lemma seq_last: forall len start,
I'd change it into a stronger thing:

```coq
Lemma seq_app : forall len1 len2 start,
  seq start (len1 + len2) = seq start len1 ++ seq (start + len1) len2.
Proof.
  induction len1 as [|len1' IHlen]; intros; simpl in *.
  - now rewrite Nat.add_0_r.
  - now rewrite Nat.add_succ_r, IHlen.
Qed.
```

because no, `seq_last` is just two rewrites:
```coq
Lemma seq_last : forall len start,
  seq start (S len) = seq start len ++ [start + len].
Proof. now intros; rewrite <-Nat.add_1_r, seq_app. Qed.
```

2018-09-26 13:14 UTC, bartavelle commented on theories/Lists/List.v
> +  Lemma seq_last: forall len start,
It feels like this PR is to be forgotten anyway :(

2018-09-26 13:17 UTC, Zimmi48 commented
If @ppedrot or @maximedenes don't want to take responsibility for merging this PR when it's ready, I'm pretty sure @herbelin will.

2018-09-26 13:58 UTC, maximedenes commented
> If @ppedrot or @maximedenes don't want to take responsibility for merging this PR when it's ready, I'm pretty sure @herbelin will.

In case it was not clear, I'm certainly not opposing.

2018-09-26 19:32 UTC, bartavelle commented on theories/Lists/List.v
> +  forall (A B : Type)(f g:A->B) l, map f l = map g l -> forall a, In a l -> f a = g a.
What would be a good name for this proof?

2018-09-26 19:53 UTC, bartavelle commented
I applied the suggestions, and rebased. I would like a new name suggestion for ext_in_map.

2018-09-26 20:00 UTC, bartavelle commented
I am unable to build coq anymore:

```
$ make
rm -f  
make --warn-undefined-variable --no-builtin-rules -f Makefile.build 
make[1]: Entering directory '/home/bartavelle/tools/coq'
OCAMLC    parsing/g_vernac.ml
File "_none_", line 1:
Error: Unbound module Pcoq.Vernac_
Makefile.build:701: recipe for target 'parsing/g_vernac.cmo' failed
make[1]: *** [parsing/g_vernac.cmo] Error 2
make[1]: Leaving directory '/home/bartavelle/tools/coq'
Makefile:166: recipe for target 'submake' failed
make: *** [submake] Error 2
```

I did `make clean` and `./configure` before that ... I see #7732 and it talks about dune, which seems to be yet another build system. Do I have to use this?

2018-09-26 20:38 UTC, herbelin commented
> I did make clean and ./configure before that ... I see #7732 and it talks about
> dune, which seems to be yet another build system. Do I have to use this?

`make clean` is not "powerful" enough to detect files whose name has changed between two commits.

If you have no unsynchronized file you want to keep in the archive, try `git clean -fxd */*`. But beware that it will erase all files that are not registered, so save the ones you would like to keep somewhere else before.

2018-09-26 21:11 UTC, SkySkimmer commented
NB: if you don't give a path to git clean it applies to the current 
directory so git clean -xfd works too

Gaëtan Gilbert

On 26/09/2018 22:38, Hugo Herbelin wrote:
>  > I did make clean and ./configure before that ... I see #7732 and it 
> talks about
>  > dune, which seems to be yet another build system. Do I have to use this?
> 
> `make clean` is not "powerful" enough to detect files whose name has 
> changed between two commits.
> 
> If you have no unsynchronized file you want to keep in the archive, try 
> `git clean -fxd */*`. But beware that it will erase all files that are 
> not registered, so save the ones you would like to keep somewhere else 
> before.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/7372#issuecomment-424861562>, or mute 
> the thread 
> <https://github.com/notifications/unsubscribe-auth/ACWQ7CJtmHK_J67o2rfuJwhSDK3rzDy9ks5ue-XCgaJpZM4TqsQv>.
>

2018-09-27 06:00 UTC, herbelin requested changes
Looks good to me. See comments.

2018-09-27 06:12 UTC, herbelin commented
I assigned. With respect to @ppedrot's comment:

> Changes to the standard library are subject to the usual cohort of bikeshedding regarding naming and formulating conventions, and AFAICT we did not come up with a consistent set of rules yet. Similarly, it is not clear what should and should not be inside a standard library. So I cannot really take a decision here.

I agree and I don't see another way to make progresses than addressing rules one by one. @maximedenes, what are your plans? For instance, do you plan to open at https://github.com/coq/stdlib2/issues an issue at some time on recommended formatting (e.g. use of spaces, use of `.` vs use of `;`, ...), on the use of bullets, on the naming convention of variables (e.g. preferring the first letter of the type, up to maybe some exceptions).

I mean, it is probably hopeless to have too strict rules, but I feel that we can get a consensus at least on a few key guidelines which shall then allow everyone to contribute in more confidence.

In the meantime, I think that the basic guideline should be the uniformity of style locally to a file.

2018-09-27 06:58 UTC, bartavelle commented on theories/Lists/List.v
> +Qed.
I modified the patchset again, thanks.

2018-09-27 07:00 UTC, bartavelle commented
@maximedenes @herbelin I also noticed space/tabs mixes in this file, messing up the indentation in coqide, so that might be of interest too.

2018-09-27 07:14 UTC, vbgl commented
On 27/09/2018 06:00, Hugo Herbelin wrote:
> Also, the convention is to use `l` for lists rather than `m`.

I wish there were a good font in which 1/l/I would be straightforward to
distinguish.

An other convention I think makes sense is to call `as` a list of `a`s;
but alas, this is forbidden in Coq (and I don’t know why).

2018-09-27 09:36 UTC, herbelin commented
> I wish there were a good font in which 1/l/I would be straightforward to distinguish.

Indeed, that's a general issue.

> An other convention I think makes sense is to call `as` a list of `a`s

Yes, I use this convention often in OCaml code. In the current stdlib, a grep shows only one instance of it (in `Strings`). However, e.g. CompCert (CombineOp.v, ...), MathComp (seq.v, ...), Equations, ... use it occasionally. And color, coccinelle, cpdt, fiat (Common.v), ... seem to use it on a rather systematic way.

> but alas, this is forbidden in Coq (and I don’t know why).

I would have guessed you knew the answer, but if not, it is a keyword.

2018-09-27 13:30 UTC, vbgl commented
>> but alas, this is forbidden in Coq (and I don’t know why).
> I would have guessed you knew the answer, but if not, it is a keyword.

Then you would have understood my question: why is it a keyword?

2018-09-27 13:35 UTC, SkySkimmer commented
for [match term as var with ...] and possibly some other uses

Gaëtan Gilbert

On 27/09/2018 15:30, Vincent Laporte wrote:
>  >> but alas, this is forbidden in Coq (and I don’t know why).
>  > I would have guessed you knew the answer, but if not, it is a keyword.
> 
> Then you would have understood my question: why is it a keyword?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/7372#issuecomment-425092933>, or mute 
> the thread 
> <https://github.com/notifications/unsubscribe-auth/ACWQ7MxQ5Z0BCk5Tlg-hOQ0gzNup_aTSks5ufNL8gaJpZM4TqsQv>.
>

2018-09-28 05:41 UTC, bartavelle commented
So, I wrote the `ext_in_map_iff` proof myself, and I suppose it is a lot clumsier than those that were proposed earlier. Other than that, is there anything else that needs to happen here?

2018-09-28 10:05 UTC, herbelin commented
> So, I wrote the ext_in_map_iff proof myself, and I suppose it is a lot clumsier than those that were proposed earlier. 

Actually, I have a few more recommendations for `ext_map_iff`, the first one being not to skip lines in the proof and to indent the `+` at character 3 (one character more on the right).

To be even more consistent with the general style, you could add a space between the two groups of binders `(A B : Type)(f g:A->B)`, and use the same spacing in both binders, e.g. as in `(A B : Type) (f g : A->B)`.

Also, there is a little specificity of the standard library which is that the colon after the name of the lemma takes a space before, as in `Lemma ext_in_map_iff :`. I know this is not the English convention for colons but we inherited here from the French typographic convention of having a space before colons.

Otherwise, please also move the `forall l1 l2` at the upper line in `skipn_app` as done in other lemmas.

In passing, @maximedenes, what should I do to propose/discuss layout policies for stdlib2?

> Other than that, is there anything else that needs to happen here?

Beside the easy (cosmetic) points above, I think it is all good, since for other questions, such as notations, terminology, order of arguments, style of definitions, style of proofs, etc. it would be anyway subjective questions about which there is, as far as I can see, no strong consensus.

Thanks a lot for having contributed this useful contents!

2018-09-28 10:18 UTC, Zimmi48 commented
>In passing, @maximedenes, what should I do to propose/discuss layout policies for stdlib2?

Open an issue on the stdlib2 repo. From what I understand @maximedenes is still looking principally at the basic infrastructure for the library but whenever the times come, having an open issue on this topic will ensure this is not forgotten.

2018-09-28 11:08 UTC, anton-trunov commented
> So, I wrote the ext_in_map_iff proof myself, and I suppose it is a lot clumsier than those that were proposed earlier. 

It should not be too clumsy since we already have one of the directions, known under the name `map_ext_in`.

Also, why not keep the originally proposed lemma *and* the `iff` version? (at least for symmetry)

```coq
Lemma ext_in_map :
  forall (A B : Type)(f g:A->B) l, map f l = map g l -> forall a, In a l -> f a = g a.
Proof. induction l; intros [=] ? []; subst; auto. Qed.

Lemma map_ext_in_iff :
   forall (A B : Type)(f g:A->B) l, map f l = map g l <-> forall a, In a l -> f a = g a.
Proof. split; [apply ext_in_map | apply map_ext_in]. Qed.
```

Also, `Set Implicit Arguments` does not infer the most convenient set of implicits here. It makes only `A` and `B` implicit here, so something like this seems a bit more reasonable:

```
Arguments ext_in_map [A B f g l].
Arguments map_ext_in_iff [A B f g l].
```

2018-09-28 11:10 UTC, anton-trunov commented
I'd also dropped `seq_last` as it's just two rewrites. I'm not entirely sure it will have sufficiently frequent use cases.

2018-09-28 11:18 UTC, herbelin commented
> Open an issue on the stdlib2 repo. 

OK, I open coq/stdlib#21. It is just for remembering, please reorganize the questions in a more structured way whenever needed.

2018-09-28 13:17 UTC, bartavelle commented
> Also, `Set Implicit Arguments` does not infer the most convenient set of implicits here. It makes only `A` and `B` implicit here, so something like this seems a bit more reasonable:
> 
> ```
> Arguments ext_in_map [A B f g l].
> Arguments map_ext_in_iff [A B f g l].
> ```

I do not understand what that means? You mean I should add the `Arguments ...` lines in the source code? I do not really understand what they mean ...

2018-09-28 13:33 UTC, bartavelle commented
The formatting should hopefully be correct now. I applied @anton-trunov 's suggestions too.

2018-09-28 15:10 UTC, herbelin commented
> with regards to spacing and forall placement, this file is not consistent at all

OK, let's postpone this to a more general systematic uniformization of the file.

> The formatting should hopefully be correct now. I applied @anton-trunov 's suggestions too.

OK, looks good to me. @anton-trunov, @vgbl, ... any more comments? If no, I'm merge on Monday evening.

2018-09-29 08:38 UTC, anton-trunov commented on theories/Lists/List.v
> +  Lemma length_skipn n :
The analogous lemma for `firstn` is called `firstn_length`

2018-09-29 12:57 UTC, anton-trunov commented
Ok, I just took a closer look and realized that `firstn_skipn_rev` does not need the extra condition (`x <= length l`). Also, there is asymmetry between `firstn` lemmas and `skipn` lemmas which is not hard to rectify a bit. Here are some extra lemmas that I'd like to see in the library:

```coq
(* two commutativity lemmas *)
Lemma firstn_skipn_comm : forall m n l,
  firstn m (skipn n l) = skipn n (firstn (n + m) l).
Proof. now intros m; induction n; intros []; simpl; destruct m. Qed.

Lemma skipn_firstn_comm : forall m n l,
  skipn m (firstn n l) = firstn (n - m) (skipn m l).
Proof. now induction m; intros [] []; simpl; rewrite ?firstn_nil. Qed.
```

These are for symmetry:
```coq
(* basic lemmas about skipn, for symmetry with the corresponding lemmas
   for firstn *)
Lemma skipn_O : forall l, skipn 0 l = l.
Proof. reflexivity. Qed.

(* TODO: remove type annotation *)
Lemma skipn_nil : forall n, skipn n ([] : list A) = [].
Proof. now intros []. Qed.

Lemma skipn_cons n a l: skipn (S n) (a::l) = skipn n l.
Proof. reflexivity. Qed.

Lemma skipn_none : forall l, skipn (length l) l = [].
Proof. now induction l. Qed.

Lemma skipn_all2 n: forall l, length l <= n -> skipn n l = [].
Proof.
  intros l L%Nat.sub_0_le; rewrite <-(firstn_all l) at 1.
  now rewrite skipn_firstn_comm, L.
Qed.

(* this is trivial, but there is firstn_le_length *)
(* I still wouldn't include it *)
(* Lemma skipn_le_length n: forall l:list A, length (skipn n l) <= length l - n. *)
(* Proof. now intros; rewrite skipn_length. Qed. *)
```

Now, this is a very useful lemma missing from `Arith` library (it would be great to include it in this PR too, because I'm using it in a proof below) :
```coq
Lemma sub_add_swap p n : p <= n -> forall m, m - (n - p) = m + p - n.
Proof.
  intros H m; rewrite <-(Nat.sub_add _ _ H) at 2.
  now rewrite <-!(Nat.add_comm p), <-minus_plus_simpl_l_reverse.
Qed.
```

The original lemma with no extra condition:

```coq
Lemma firstn_skipn_rev : forall x l,
    firstn x l = rev (skipn (length l - x) (rev l)).
Proof.
  intros x l; rewrite <-(firstn_skipn x l) at 3.
  rewrite rev_app_distr, skipn_app, rev_app_distr, rev_length,
          skipn_length, Nat.sub_diag; simpl; rewrite rev_involutive.
  rewrite <-app_nil_r at 1; f_equal; symmetry; apply length_zero_iff_nil.
  repeat rewrite rev_length, skipn_length; apply Nat.sub_diag.
Qed.
```

And two really useful lemmas based on the previous one (I'd argue the following are even more useful):

```coq
Lemma firstn_rev: forall x l,
    firstn x (rev l) = rev (skipn (length l - x) l).
Proof.
  now intros x l; rewrite firstn_skipn_rev, rev_involutive, rev_length.
Qed.

Lemma skipn_rev: forall x l,
    skipn x (rev l) = rev (firstn (length l - x) l).
Proof.
  intros x l; rewrite firstn_skipn_rev, rev_involutive, <-rev_length.
  destruct (Nat.le_ge_cases (length (rev l)) x) as [L | L].
  - rewrite skipn_all2; [apply Nat.sub_0_le in L | trivial].
    now rewrite L, Nat.sub_0_r, skipn_none.
  - now rewrite (sub_add_swap L), minus_plus.  (* here I'm using that missing arith. lemma *)
Qed.
```

2018-09-29 15:06 UTC, bartavelle commented
@anton-trunov do you really want me to curate those patches? It seems you are much more competent than I will ever be here, and I do not think there is anything left from my original contributions from April. While I can do it, it would probably be much more efficient that you do it directly !

Also, given the amount of bikeshedding this PR has been subjected to, I do not feel like embarking on another month long quest to have a lemma integrated in `Arith` ...

PS: I also would like to have something like `sub_add_swap`. Currently, I have an ugly technique where I `replace ....;try omega` :(

2018-09-29 15:35 UTC, anton-trunov commented
I'm not insisting on the major changes -- let us see what @herbelin thinks about this. The minimum changed I think would be to cut off the unneeded condition.

2018-09-29 15:53 UTC, bartavelle commented
I did the janitorial work, but merged all the commits in a single commit.

2018-09-29 20:44 UTC, herbelin commented
Thanks to the both of you, that expanded nicely. Unless you have something to add, I continue to plan Monday for the janitorial work of merging.

2018-10-01 17:54 UTC, herbelin approved these changes

2018-10-01 17:57 UTC, merged