Gitlab: build docker image in pipeline and use througn registry.
coq/coq pull request #7442
Opened 2018-05-06 16:36 UTC by SkySkimmer

A docker-boot job is added which builds the docker image and pushes it
to the registry, the other jobs running on the image from the
registry.

The boot job reuses the already pushed image if it exists and matches,
this is important to cut down its runtime.

Making a new image takes 30min for all the switches
https://gitlab.com/SkySkimmer/coq/-/jobs/66650546
For testing I removed all jobs except boot and main build, and after
that run I built only the standard switch.

Building 1 switch takes around 20min
https://gitlab.com/SkySkimmer/coq/-/jobs/66656942
When the registry is up to date it takes 2min
https://gitlab.com/SkySkimmer/coq/-/jobs/66658790
(I don't know about all switches but probably no more than 5min)

Each pipeline pushes the image to $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
which is eg registry.gitlab.com/skyskimmer/coq:21557176 and is what
the other jobs use to run themselves.

For caching it pulls from and pushes to a constant name, in this test
$CI_REGISTRY_IMAGE:$CACHEKEY. We might also want to pull from the main
coq repo to avoid redoing work.

The question of having 1 image or 1 image/switch remains open.

Using the gitlab registry doesn't really work for circle CI, so the
dockerhub account would have to remain (or circle could return to an
opam-boot job, or be removed from our CI). There are similar concerns
with travis if we want to move it to docker.

2018-05-06 17:18 UTC, ejgallego commented
I understand there is not a safe way to push to `hub.docker` even for a few contributors?

2018-05-06 17:25 UTC, ejgallego commented
> What's your threat model?

A non-authorized person overwriting a tag there.

Ideally, I'd be cool if I could set up a secret on my own Gitlab repo and that secret would be used in a PR to push to `coqci` [as well as to the Gitlab registry], but I don't know how Gitlab secrets work [yet].

Other than that, I like this patch, will review later today or tomorrow I hope.

2018-05-06 17:27 UTC, SkySkimmer commented
Better question, what's your use case?
Putting a secret in a protected variable on gitlab shares it only with protected branches (ie master) so that would work, but I don't know if it's useful for what you want.

2018-05-06 18:34 UTC, ejgallego commented
> Better question, what's your use case?

Use case is as follows:
1. I update dockerfile.
2. I submit a pull request -> that will trigger a pull request.
3. The CI system detects that I have push rights to `hub.docker.com/coqci`, then it pushes it there.

2018-05-06 23:33 UTC, ejgallego commented
I think this looks good.

2018-05-07 00:51 UTC, ejgallego commented
On the other hand I am not sure this is worth it. How often are we supposed to update the image?

I would say we would update the Docker image very very infrequently, basically only on OCaml releases or maybe new dependencies coming in. Let's say once in a month.

On the other hand, this will add a 3 / 4 minutes job for **all** pipelines. Let's say we have 15 pipelines per day, that's 15*3 = 45 minutes * 30 days, around 1 full day (24h) of time lost per month.

I am not sure it is worth it IMO.

2018-05-07 00:55 UTC, ejgallego commented
Ideally we'd have this job only run when the branch has a special name [we'd need to improve the bot tho]

2018-05-07 01:39 UTC, ejgallego commented
Yeah I have been thinking a bit more about this and IMHO generating a tag for each build seems a bit too much, I am not sure Docker is really designed for that, maybe yes.

Also, I don't see the problem with Circle using gitlab's registry, `docker pull registry.gitlab.com/coq/coq:bionic-V2018-05-06` should work well there, right?

2018-05-07 01:44 UTC, ejgallego commented
So this is what I suggest for now, we add to the job:
```yaml
only:
  - docker-update
```
and we create such branch in the gitlab repository; so any time we want to update the image we have to push to that branch, then do a pull request. WDYT?

2018-05-07 07:05 UTC, Zimmi48 commented
I am very much in favor of this PR because we should avoid to depend on too many external services (like DockerHub). Furthermore, the new Docker based solution is making life harder for new contributors (cf. #6808) so this PR is a big improvement.

However, I agree with @ejgallego that we should try to avoid the wasted build time (if we can). Would it be quicker to have a solution based on whether git detects some change to the Docker image code? Or based on a label put on the PR? Or a comment in a git commit? In any case, I absolutely want to avoid the branch-name-based solution proposed by @ejgallego because branch names can't be changed for already opened PRs and I would prefer to reduce any requirement of a manual action.

2018-05-07 08:42 UTC, ejgallego commented
> a label put on the PR?

That's almost the same than having a regexp for branch name. I don't think that's so bad.

In the end I think that caching will always make the life of new contributors difficult as it involves some trust [or less of caching], so what the right tradeoff is, I don't know.

2018-05-07 08:58 UTC, ejgallego commented
> Furthermore, the new Docker based solution is making life harder for new contributors (cf. #6808) so this PR is a big improvement.

IMHO this event "a new contributor needing to a dependency to the base build system" should be quite rare, of course if it turns out that this is not the case we should reevaluate.

Note that the contributor can also build and push a Docker image without too much problems; only pain is the lack of a single place to put the tag.

2018-05-07 11:25 UTC, ejgallego commented
> No because you can set a label on an open PR, but you can't change the branch name.

So I dunno how this would work? Maybe the bot could map the label to a branch name?

The issue is that Gitlab's conditions don't know about labels.

2018-05-07 11:39 UTC, SkySkimmer commented
We could do
```yml
only:
  - trigger
  - web
```
Then a user can rebuild by starting the pipeline through the web UI, and we can also have a bot watching for github labels or whatever we want.

2018-05-07 11:41 UTC, ejgallego commented
> Then a user can rebuild by starting the pipeline through the web UI, and we can also have a bot watching for github labels or whatever we want.

That'd be also fine to me.

Note that this PR in its current state would be also fine to me, but I'd like more if we could indeed save that boot step.

2018-05-07 11:46 UTC, SkySkimmer commented
>Yeah I have been thinking a bit more about this and IMHO generating a tag for each build seems a bit too much, I am not sure Docker is really designed for that, maybe yes.

I think docker is fine with it but it's not super useful for us so I changed it to using only CACHEKEY.

2018-05-07 11:47 UTC, Zimmi48 commented
I think we are thinking too hard about the build time problem because if we want to save precious minutes of build times, we should start elsewhere (e.g. not recompile Bignums + Math-Classes + Corn several times).

2018-05-07 11:48 UTC, ejgallego commented
> I think docker is fine with it but it's not super useful for us so I changed it to using only CACHEKEY.

My worries were indeed about garbage collection, it wouldn't take long for the registry to have thousand of tags, and I dunno how you can clean that up. Would the regsitry support something such as "expiry" I'd be more comforable with it.

2018-05-07 11:49 UTC, ejgallego commented
> I think we are thinking too hard about the build time problem because if we want to save precious minutes of build times, we should start elsewhere (e.g. not recompile Bignums + Math-Classes + Corn several times).

We try to do as best as we can latency-wise, and given the limitations of Gitlab. So far what we have here is close to optimal latency-wise, how would you layout things?

2018-05-07 11:50 UTC, SkySkimmer commented
>My worries were indeed about garbage collection, it wouldn't take long for the registry to have thousand of tags, and I dunno how you can clean that up. Would the regsitry support something such as "expiry" I'd be more comfortable with it.

Actually I hit delete on one of the tags for the coq/coq registry and it removed all the aliases :v

2018-05-07 11:51 UTC, SkySkimmer commented
>We try to do as best as we can latency-wise, and given the limitations of Gitlab. So far what we have here is close to optimal latency-wise, how would you layout things?

We could remove the mathclasses job since it gets built for formal-topology

2018-05-07 11:51 UTC, ejgallego commented
> Actually I hit delete on one of the tags for the coq/coq registry and it removed all the aliases :v

I don't know if that's good or terrible.

2018-05-12 10:03 UTC, ejgallego commented
Adding a tag as to know when to look at this again. My opinion: we want this in 100%, but it would be great to implement an `only` condition so we save the boot step in the large majority of jobs.

2018-05-12 10:05 UTC, SkySkimmer commented
What kind of `only` do you want?

2018-05-12 10:37 UTC, ejgallego commented
> What kind of only do you want?

Your only proposal looked fine to me, any other method that won't trigger the rebuild job always will be OK to me. If you don't like `only` we could even merge this as is, I dunno, WDYT?

I do prefer to save that 5 minutes, IMHO that's a lot of latency overall for what it will be 2/3 Docker updates per year.

2018-05-14 12:06 UTC, SkySkimmer commented on .gitlab-ci.yml
> +      - $SKIP_DOCKER == "true"
After thinking about it I want the default to just work and that means always running.
So we use a variable to disable the job (we can set the variable in the web UI when manually running to differ from repo policy).

2018-05-14 12:09 UTC, SkySkimmer commented
I removed all the extra `bionic_coq` from paths and variables as they're useless and would be a pain to sync when we upgrade.

2018-05-14 13:13 UTC, Zimmi48 commented
Is the postpush hook still used with this configuration?

2018-05-14 13:14 UTC, SkySkimmer commented
>Is the postpush hook still used with this configuration?

Circle still uses dockerhub.

2018-05-14 13:26 UTC, ejgallego commented
> We can add linux when we have more than 1 dockerfile but bionic is no good.

Why is not good?

I can live with the current `SKIP_DOCKER` policy, however I'm not sure I can take a generic naming, specially when we are open to adding nix images, etc...

2018-05-14 13:27 UTC, SkySkimmer commented
It should be auto enabled.

Gaëtan Gilbert

On 14/05/2018 15:25, Emilio Jesús Gallego Arias wrote:
> *@ejgallego* commented on this pull request.
> 
> ------------------------------------------------------------------------
> 
> In .gitlab-ci.yml 
> <https://github.com/coq/coq/pull/7442#discussion_r187950910>:
> 
>>    # By default, jobs run in the base switch; override to select another switch
>     OPAM_SWITCH: "base"
>     # Used to select special compiler switches such as flambda, 32bits, etc...
>     OPAM_VARIANT: ""
>   
> +docker-boot:
> +  stage: docker
> +  image: docker:stable
> +  services:
> +    - docker:dind
> +  before_script: []
> +  script:
> +    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
> +    - cd dev/ci/docker/bionic_coq/
> +    - if docker pull "$IMAGE"; then echo "Image prebuilt!"; exit 0; fi
> +    - docker build -t "$IMAGE" .
> +    - docker push "$IMAGE"
> +  except:
> +    variables:
> +      - $SKIP_DOCKER == "true"
> 
> Does that force the user to enable the registry on its own repos?
> 
> IMHO Docker seems more targeted at people pulling from a canonical 
> source, so I am not convinced we want this workflow, in particular when 
> users can just pull from Coq's Gitlab registry.
> 
> I think I still prefer the workflow:
> 
>   * docker image build is manually triggered by an specific branch name
>     or action.
>   * users pull from Coq's registry [either in gitlab or in coqci]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/7442#discussion_r187950910>, or mute 
> the thread 
> <https://github.com/notifications/unsubscribe-auth/ACWQ7EDxJ6R_ZEEL0z0tUGgrowuNK9BYks5tyYWugaJpZM4T0GlI>.
>

2018-05-14 13:29 UTC, SkySkimmer commented
OK good point, I'll revert

Gaëtan Gilbert

On 14/05/2018 15:26, Emilio Jesús Gallego Arias wrote:
>     We can add linux when we have more than 1 dockerfile but bionic is
>     no good.
> 
> Why is not good?
> 
> I can live with the current |SKIP_DOCKER| policy, however I'm not sure I 
> can take a generic naming, specially when we are open to adding nix 
> images, etc...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/7442#issuecomment-388815633>, or mute 
> the thread 
> <https://github.com/notifications/unsubscribe-auth/ACWQ7P9gaU_srQ_AfiVAqTdn1tT5xueUks5tyYYKgaJpZM4T0GlI>.
>

2018-05-14 13:36 UTC, ejgallego requested changes
I think documentation `dev/ci/README.md` should be updated to reflect the variable policy.

I'd suggest adding a section "gitlab configuration variables". Windows variables should be there too.

2018-05-14 13:39 UTC, SkySkimmer commented
In what way?

Gaëtan Gilbert

On 14/05/2018 15:36, Emilio Jesús Gallego Arias wrote:
> *@ejgallego* requested changes on this pull request.
> 
> I think documentation |dev/ci/README.md| should be updated.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/7442#pullrequestreview-119835784>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ACWQ7A9oE_kNBwrC58ywC6PWKvumfG1aks5tyYhzgaJpZM4T0GlI>.
>

2018-05-14 13:51 UTC, SkySkimmer commented
>I think documentation dev/ci/README.md should be updated to reflect the variable policy.

Changed.

2018-05-14 13:56 UTC, ejgallego commented on dev/ci/README.md
> +
You need to update the above section to instruct users to enable their private registry as otherwise Gitlab will fail now.

2018-05-14 13:59 UTC, SkySkimmer commented on dev/ci/README.md
> +This means you will need to change its value when the Docker image
>"change its value back to false"

false isn't a default, any non `true` value works.

2018-05-14 14:01 UTC, SkySkimmer commented
Changed further.

2018-05-14 14:08 UTC, ejgallego approved these changes
It looks OK to me so I'll merge once CI gives a positive answer.

2018-05-14 17:56 UTC, ejgallego commented
I am triggering the build with the proper thing set, let's see...

2018-05-14 17:57 UTC, ejgallego commented
https://gitlab.com/coq/coq/pipelines/22002967

2018-05-15 02:06 UTC, ejgallego commented
Umm, why is circle not switched?

AFAICS there is no problem in circle pulling from Docker's registry; so at least let's make its config point to the new official home for the Docker image.

2018-05-15 06:54 UTC, Zimmi48 commented
It would have been less complications if CircleCI had been removed completely.

2018-05-15 09:32 UTC, ejgallego commented
> It would have been less complications if CircleCI had been removed completely.

There is not rush; it is easy to modifiy a line.

2018-05-15 23:46 UTC, ejgallego commented
@SkySkimmer going to merge this soon, but what should we go with Circle?

Do you want to address it in a separate PR? If you want to push the change, rebasing should help with build time thanks to #7503 having been merged.

2018-05-16 01:50 UTC, ejgallego commented
Ok let's get this going and address Circle on a different PR.

2018-05-16 01:51 UTC, merged

2018-05-16 08:57 UTC, Zimmi48 commented
This PR also doesn't update the README about docker. This should probably be done when this is stabilized.