Fix #7421: constr_eq ignores universe constraints.
coq/coq pull request #7491
Opened 2018-05-11 21:40 UTC by SkySkimmer

The test isn't quite the one in #7421 because that use of algebraic
universes is wrong.

Ltac `match` is a different code path, I'll split it to its own issue.

NB: the implementation of the tactic was moved out of the .ml4 as camlp5 barfs on `match with exception`.

2018-05-11 23:13 UTC, JasonGross requested changes
I think that `constr_eq` should not have side effects.  (And `match` to `idtac` should definitely not have side-effects.)  It should check that the universes are compatible, but it should *not* add any induced constraints to the universe graph.

More broadly, there are two sorts of things I might want to do: I might want to check if two things are the same (for various notions of the same) (and fail otherwise), and I might want to enforce that two are the same (for various notions of the same), updating the environment as necessary.  The first is generally what I mean when I write `match`, `constr_eq`, etc; the second is what I mean when I write, e.g., `unify`.

2018-05-11 23:20 UTC, SkySkimmer commented
>I think that constr_eq should not have side effects. (And match to idtac should definitely not have side-effects.) It should check that the universes are compatible, but it should not add any induced constraints to the universe graph.

Makes sense, changed.

2018-05-12 00:28 UTC, andres-erbsen commented
Hmm. `constr_eq` does not consider two evars equal. Both evars and universes are implicitly existentially quantified in some sense, so perhaps constr_eq shouldn't consider two different but compatible universe variables equal either? I am guessing that this is not the functionality what comes in common usage, but given that `constr_eq` is a low-level primitive, it is probably worth taking the time to be principled and not unnecessarily opinionated about it.

2018-05-12 00:48 UTC, JasonGross submitted a review, later dismissed

2018-05-12 00:48 UTC, JasonGross commented on test-suite/bugs/closed/7421.v
> +  constr_eq (Type@{i}) (Type@{j}).
I think the following should also work, and should get tests:
```coq
constr_eq Type Type.
constr_eq Set Set.
constr_eq Prop Prop.
let x := constr:(Type) in constr_eq x x.
lazymatch type of prod with
| ?A -> ?B -> _ => constr_eq A B
end.
lazymatch type of prod with
| ?A -> ?B -> ?C => constr_eq A C
end.
```

2018-05-12 00:48 UTC, JasonGross commented on tactics/tactics.ml
> +        else Tacticals.New.tclFAIL 0 (str "Not equal")
Perhaps this should get a different error message?  (e.g., "Not equal (universe mismatch)")

2018-05-12 00:52 UTC, JasonGross commented
> so perhaps `constr_eq` shouldn't consider two different but compatible universe variables equal either

This doesn't work very well.  For example, this would make `constr_eq Type Type` fail, and if `prod` were universe-polymorphic, it would make `constr_eq prod prod` fail.  The difference between evars and universes is that you have to wrap something in `open_constr` to get fresh implicit evars, but you don't have to do anything special to get fresh implicit universes.  I can see there being a case for having a `constr_eq_strict_universes` tactic, but, so long as the default in Coq is to not write universes, the default should also be to not care too much about universe identity.

2018-05-12 09:56 UTC, SkySkimmer commented
Either `constr_eq Type Type` fails or it has side effects. In the later case if you want the side effect free version you can wrap it in `assert_succeeds`.
So do I make it have side effects or not?

2018-05-12 10:02 UTC, JasonGross commented
I want there to be a tactic called something like `constr_eq_add_constraints` which adds constraints, one called something like `constr_eq_strict_univs` which fails on `Type Type`, and I want the tactic called `constr_eq` to be `assert_succeeds constr_eq_add_constraints` (with correct error messages).

2018-05-12 10:06 UTC, SkySkimmer commented
I definitely don't want the default looking one to add constraints and then forget them. If I say `constr_eq foo bar; baz` I should be able to assume in baz that they're actually equal.

2018-05-12 10:08 UTC, SkySkimmer commented
Meanwhile it seems cross-crypto expects it to add constraints (it probably doesn't care if we forget them though).

2018-05-12 16:11 UTC, andres-erbsen commented
cross-crypto uses constr_eq in tests of Ltac code which is itself experimental. it'll be easy to port those uses to any other mechanism of term equally testing. I think it is much more important to decide on a reasonable semantics for universe variables in Ltac; I will just fix up cross-crypto for whatever we decide here.

I am still of the opinion that universe variables should be treated like other evars. I understand that they're currently not treated that way, but I don't think there is a good reason for why that makes sense. at the very least, keeping evar semantics straight is already hard enough, and I'm worried that treating universe variables differently would result in a whole new can of worms.

2018-05-13 21:03 UTC, ppedrot commented
FTR, I'm deeply convinced that equality on terms is a delicate matter, as witnessed by the vast array of subtly distinct functions in the OCaml codebase. There is no reason such a complexity should not be reflected in the tactic language...

2018-05-14 13:05 UTC, SkySkimmer commented
Updated.

2018-05-25 13:15 UTC, SkySkimmer commented
In 4728.v this bug causes a new error `Error: The reference numgoals was not found in the current environment.`
I don't understand why.

2018-06-04 11:55 UTC, SkySkimmer commented
Any Ltac/parsing experts around?

2018-06-04 12:19 UTC, ppedrot commented
I don't understand how that was parsing before. The `constr_eq` term is expecting two constrs as arguments. I suspect this is due to CAMLP5 being clever and factorizing rules in the previous state of the code, which it cannot do anymore now due to the fact there are two entries in the tactic extension.

2018-06-04 12:34 UTC, SkySkimmer commented
>I don't understand how that was parsing before. The constr_eq term is expecting two constrs as arguments. I suspect this is due to CAMLP5 being clever and factorizing rules in the previous state of the code, which it cannot do anymore now due to the fact there are two entries in the tactic extension.

OK I changed the bug file.

2018-06-04 13:37 UTC, SkySkimmer commented
Added CHANGES.

2018-06-15 12:11 UTC, ppedrot requested changes
Can you split the TACTIC EXTEND entry into two separate ones? This will provide a fully backwards compatible syntax. Then you can revert the change on the test file.

2018-06-15 12:14 UTC, SkySkimmer commented
Done

2018-06-15 12:19 UTC, ppedrot commented
@JasonGross are you at least not objecting to the current state of the PR?

2018-06-15 12:29 UTC, ppedrot approved these changes

2018-06-15 13:57 UTC, JasonGross commented
The variant(s) of `constr_eq` should be documented in the refman and added to the tactic index, but otherwise I am not objecting to the current form of this PR.

2018-06-18 12:17 UTC, SkySkimmer commented
>The variant(s) of constr_eq should be documented in the refman and added to the tactic index, but otherwise I am not objecting to the current form of this PR.

Doc added.

2018-06-18 12:28 UTC, ppedrot commented
There is only one place using `globals`, and it is using in a very hackish way. This code should rather be browsing the module structure rather than the structureless global blob.

Also, making a function available doesn't mean we endorse its use. Often people go to the shortest solution, so that we should strive for easiness of correct code and clumsiness of the undesirable one.

2018-06-18 12:29 UTC, SkySkimmer commented
>There is only one place using globals, and it is using in a very hackish way.

Comment for #7745?

2018-06-18 12:29 UTC, ppedrot commented
Yep sorry!

2018-06-19 14:17 UTC, merged