Fixes bug #5561,#5562 in Windows build system
coq/coq pull request #754
Opened 2017-06-08 17:35 UTC by MSoegtropIMC

5561 was fixed by inserting proper quote handling (resulted in quite a few changes)
5562 was fixed by compiling the previous version of cygwin sed from sources (download from gnu archive + cygwin patch file literally supplied in the patches_coq folder)

2017-06-08 19:42 UTC, JasonGross requested changes

2017-06-08 19:42 UTC, JasonGross commented on dev/build/windows/makecoq_mingw.sh
> +      /*)
I think you should also check for relative paths here, `./*)`.  (I'm trying to set up CI testing, and don't have easy access to the absolute path before cygwin is installed.)

2017-06-08 20:21 UTC, JasonGross requested changes
`wget` fails to get `sed`: https://ci.appveyor.com/project/JasonGross/coq/build/appveyor~33#L1024
```
 wget https://ftp.gnu.org/gnu/sed//sed-4.2.2.tar.gz
Error parsing proxy URL http://: Invalid host name.
+ '[' '!' sed-4.2.2.tar.gz == sed-4.2.2.tar.gz ']'
+ mv sed-4.2.2.tar.gz /build/tarballs
mv: cannot stat 'sed-4.2.2.tar.gz': No such file or directory
+ '[' -d /cygdrive/c/projects/coq/dev/build/windows/source_cache ']'
+ cp /build/tarballs/sed-4.2.2.tar.gz /cygdrive/c/projects/coq/dev/build/windows/source_cache
cp: cannot stat '/build/tarballs/sed-4.2.2.tar.gz': No such file or directory
+ '[' 1 -eq 1 ']'
+ rm -f -r sed-4.2.2
+ mkdir -p sed-4.2.2
+ cd sed-4.2.2
+ '[' tar.gz == zip ']'
+ logn untar tar xvaf /build/tarballs/sed-4.2.2.tar.gz --strip 1
+ LOGTARGETEX=untar
+ shift
+ tar xvaf /build/tarballs/sed-4.2.2.tar.gz --strip 1
+ display_log 2 /build/buildlogs/sed-4.2.2-untar.log /build/buildlogs/sed-4.2.2-untar.err
+ RV=2
+ echo stdout:
stdout:
+ cat /build/buildlogs/sed-4.2.2-untar.log
+ echo stderr:
stderr:
+ cat /build/buildlogs/sed-4.2.2-untar.err
tar: /build/tarballs/sed-4.2.2.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
+ exit 2
++ '[' 1 = 1 ']'
++ '[' -x /usr/bin/clear ']'
++ /usr/bin/clear
[H[J
C:\projects\coq\dev\build\windows>ECHO ERROR MakeCoq_MinGW.bat failed 
ERROR MakeCoq_MinGW.bat failed
```

2017-06-09 08:37 UTC, MSoegtropIMC commented
Dear Jason,

strange works for me. But I have to live behind a proxy and the proxy might do some odd translation. Can you check if it works with http or ftp rather than https? I somehow have to rely on you to find a path to this file which works for outside of the intel proxy world. It should be easy to find. I can also check today evening from home.

Best regards,

Michael

From: Jason Gross [mailto:notifications@github.com]
Sent: Thursday, June 08, 2017 10:22 PM
To: coq/coq
Cc: Soegtrop, Michael; Author
Subject: Re: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)


@JasonGross requested changes on this pull request.

wget fails to get tar: https://ci.appveyor.com/project/JasonGross/coq/build/appveyor~33#L1024<https://ci.appveyor.com/project/JasonGross/coq/build/appveyor%7E33#L1024>

 wget https://ftp.gnu.org/gnu/sed//sed-4.2.2.tar.gz<https://ftp.gnu.org/gnu/sed/sed-4.2.2.tar.gz>

Error parsing proxy URL http://: Invalid host name.

+ '[' '!' sed-4.2.2.tar.gz == sed-4.2.2.tar.gz ']'

+ mv sed-4.2.2.tar.gz /build/tarballs

mv: cannot stat 'sed-4.2.2.tar.gz': No such file or directory

+ '[' -d /cygdrive/c/projects/coq/dev/build/windows/source_cache ']'

+ cp /build/tarballs/sed-4.2.2.tar.gz /cygdrive/c/projects/coq/dev/build/windows/source_cache

cp: cannot stat '/build/tarballs/sed-4.2.2.tar.gz': No such file or directory

+ '[' 1 -eq 1 ']'

+ rm -f -r sed-4.2.2

+ mkdir -p sed-4.2.2

+ cd sed-4.2.2

+ '[' tar.gz == zip ']'

+ logn untar tar xvaf /build/tarballs/sed-4.2.2.tar.gz --strip 1

+ LOGTARGETEX=untar

+ shift

+ tar xvaf /build/tarballs/sed-4.2.2.tar.gz --strip 1

+ display_log 2 /build/buildlogs/sed-4.2.2-untar.log /build/buildlogs/sed-4.2.2-untar.err

+ RV=2

+ echo stdout:

stdout:

+ cat /build/buildlogs/sed-4.2.2-untar.log

+ echo stderr:

stderr:

+ cat /build/buildlogs/sed-4.2.2-untar.err

tar: /build/tarballs/sed-4.2.2.tar.gz: Cannot open: No such file or directory

tar: Error is not recoverable: exiting now

+ exit 2

++ '[' 1 = 1 ']'

++ '[' -x /usr/bin/clear ']'

++ /usr/bin/clear

�[H�[J

C:\projects\coq\dev\build\windows>ECHO ERROR MakeCoq_MinGW.bat failed

ERROR MakeCoq_MinGW.bat failed

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coq/coq/pull/754#pullrequestreview-43002873>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHh50r5u-o1EoCiB1ep7MsCR315TDXIAks5sCFfPgaJpZM4N0ZGU>.
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-09 08:43 UTC, JasonGross commented
Running `wget` bare on my laptop works fine.  I haven't tested running it inside the script on my laptop, but maybe it has something to do with the `HTTP_PROXY` check where you set `PROXY`?  It's quite strange that it `http://` as the proxy when it's trying to download something at `https://`, no?  I'm going to go to sleep, but I told appveyor to try it with http here: https://ci.appveyor.com/project/JasonGross/coq/build/appveyor~35

2017-06-09 08:46 UTC, MSoegtropIMC commented
Dear Jason,

how do you want the relative path to be interpreted? I mean what should be the root path? Since the path from which I call tar doesn’t even exist when you specify the relative path, this is not so obvious. I could e.g. remember the DOS path from which MakeCoq_MinGW.bat was called and use this translated to cygwin format as root path for the relative path. Would this be ok? I discussed this with Maxime before and he said that the path would be outside of the cygwin folder I create.

One more note: I tar the folder and expand it again (for backup reasons). It would be nice to tar with --exclude-vcs --exclude-vcs-ignores, but the latter strips a required coqdoc.sty file. This file is in git, but it is also in gitignore. If you are sure that nothing was ever built in the source folder, it is fine to tar with just the --exclude-vcs option. If the folder is not clean, cogdoc.sty should be removed from gitignore. I assume that during build coqdoc.sty is copied somewhere and just these copies should be excluded in .gitignore.

Best regards,

Michael

From: Jason Gross [mailto:notifications@github.com]
Sent: Thursday, June 08, 2017 9:42 PM
To: coq/coq
Cc: Soegtrop, Michael; Author
Subject: Re: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)


@JasonGross requested changes on this pull request.

________________________________

In dev/build/windows/makecoq_mingw.sh<https://github.com/coq/coq/pull/754#discussion_r120980511>:

>      case $COQ_VERSION in

-      git-*) build_prep https://github.com/coq/coq/archive ${COQ_VERSION##git-} zip 1 coq-${COQ_VERSION} ;;

-      *)     build_prep https://coq.inria.fr/distrib/V$COQ_VERSION/files coq-$COQ_VERSION tar.gz ;;

+      # e.g. git-v8.6 => download from https://github.com/coq/coq/archive/v8.6.zip

+      # e.g. git-trunk => download from https://github.com/coq/coq/archive/trunk.zip

+      git-*)

+        COQ_BUILD_PATH=/build/coq-${COQ_VERSION}

+        build_prep https://github.com/coq/coq/archive ${COQ_VERSION##git-} zip 1 coq-${COQ_VERSION}

+        ;;

+

+      # e.g. /cygdrive/d/coqgit

+      /*)

I think you should also check for relative paths here, ./*). (I'm trying to set up CI testing, and don't have easy access to the absolute path before cygwin is installed.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coq/coq/pull/754#pullrequestreview-42992901>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHh50s0ECboCjZLz7X3RSgk7gG2kDzImks5sCE6OgaJpZM4N0ZGU>.
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-09 08:50 UTC, JasonGross commented
>  I could e.g. remember the DOS path from which MakeCoq_MinGW.bat was called and use this translated to cygwin format as root path for the relative path. Would this be ok? I discussed this with Maxime before and he said that the path would be outside of the cygwin folder I create.

Sure.  Or just use the directory of MakeCoq_MinGW.bat as the root path.  The use case I have is that I need to be able to say "if `MakeCoq_MinGW.bat` is in `somedir/dev/build/windows`, then the source for the version of Coq that I'm building lives in `somedir/`"  (That is, if I make a fresh clone of Coq, I want to be able to use that clone as the source, without moving `MakeCoq_MinGW.bat`.)

2017-06-09 08:55 UTC, MSoegtropIMC commented
Dear Jason,

let my familiarize myself with appveyor, so that I can fix this myself – doesn’t look to complicated.

Unfortunately I need all this proxy crap and I cannot test what happens without it except at home, but there I use Linux. Appveyor seems to be a good solution for this.

Best regards,

Michael

From: Jason Gross [mailto:notifications@github.com]
Sent: Friday, June 09, 2017 10:44 AM
To: coq/coq
Cc: Soegtrop, Michael; Author
Subject: Re: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)


Running wget bare on my laptop works fine. I haven't tested running it inside the script on my laptop, but maybe it has something to do with the HTTP_PROXY check where you set PROXY? It's quite strange that it http:// as the proxy when it's trying to download something at https://, no? I'm going to go to sleep, but I told appveyor to try it with http here: https://ci.appveyor.com/project/JasonGross/coq/build/appveyor~35<https://ci.appveyor.com/project/JasonGross/coq/build/appveyor%7E35>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coq/coq/pull/754#issuecomment-307331973>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHh50g6PYMxa0GySinjHnhrW4JdMZDcqks5sCQW9gaJpZM4N0ZGU>.
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-09 13:02 UTC, MSoegtropIMC commented
Dear Jason,

I fixed the bug with the proxy setting.

Regarding relative paths: I could do this, but the following build script for appvejor works for me (it doesn’t need an init or install script) works. It uses a slightly different folder layout than yours, but for sure you can change the cygwin and result folder in any way. But it is not a good idea to call the scripts directly from the git folder, because by default all the cygwin and source packages go into subfolders of it. So I copy this folder to a new folder.

Best regards,

Michael

SET GITDIR_WFMT=%CD%
SET GITDIR_MFMT=%GITDIR_WFMT:\=/%
SET GITDIR_CFMT=%GITDIR_MFMT:C:/=/cygdrive/c/%
SET GITDIR_CFMT=%GITDIR_CFMT:D:/=/cygdrive/d/%
SET GITDIR_CFMT=%GITDIR_CFMT:E:/=/cygdrive/e/%
ECHO %GITDIR_WFMT%
ECHO %GITDIR_CFMT%

CD ..

SET ROOTDIR_WFMT=%CD%
SET ROOTDIR_MFMT=%ROOTDIR_WFMT:\=/%
SET ROOTDIR_CFMT=%ROOTDIR_MFMT:C:/=/cygdrive/c/%
SET ROOTDIR_CFMT=%ROOTDIR_CFMT:D:/=/cygdrive/d/%
SET ROOTDIR_CFMT=%ROOTDIR_CFMT:E:/=/cygdrive/e/%
ECHO %ROOTDIR_WFMT%
ECHO %ROOTDIR_CFMT%

MKDIR cygwin
MKDIR result
MKDIR build

XCOPY %GITDIR_WFMT%\dev\build\windows build /S

CD build
DIR /S

SET COQREGTESTING=Y

SET H
SET U

appveyor DownloadFile http://cygwin.com/setup-x86_64.exe

MakeCoq_MinGW.bat -arch=64 -installer=Y -coqver=%GITDIR_CFMT% -destcyg="%ROOTDIR_WFMT%\cygwin" -destcoq="%ROOTDIR_WFMT%\result"

IF %ERRORLEVEL% NEQ 0 (
  ECHO MakeCoq failed with error code %ERRORLEVEL%
  EXIT /b %ERRORLEVEL%
)


From: Jason Gross [mailto:notifications@github.com]
Sent: Friday, June 09, 2017 10:51 AM
To: coq/coq
Cc: Soegtrop, Michael; Author
Subject: Re: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)


I could e.g. remember the DOS path from which MakeCoq_MinGW.bat was called and use this translated to cygwin format as root path for the relative path. Would this be ok? I discussed this with Maxime before and he said that the path would be outside of the cygwin folder I create.

Sure. Or just use the directory of MakeCoq_MinGW.bat as the root path. The use case I have is that I need to be able to say "if MakeCoq_MinGW.bat is in somedir/dev/build/windows, then the source for the version of Coq that I'm building lives in somedir/" (That is, if I make a fresh clone of Coq, I want to be able to use that clone as the source, without moving MakeCoq_MinGW.bat.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coq/coq/pull/754#issuecomment-307333513>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHh50o91Dhw7OWfpLTP-e27ja8Ha9EKwks5sCQdZgaJpZM4N0ZGU>.
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-09 14:20 UTC, MSoegtropIMC commented
P.S.: the appveyor server is too slow to get even one build through within the time limit of one hour. I got a time out while it was running coq make all. But otherwise it seems to work.

Best regards,

Michael

From: Soegtrop, Michael
Sent: Friday, June 09, 2017 3:03 PM
To: 'coq/coq'; coq/coq
Cc: Author
Subject: RE: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)

Dear Jason,

I fixed the bug with the proxy setting.

Regarding relative paths: I could do this, but the following build script for appvejor works for me (it doesn’t need an init or install script) works. It uses a slightly different folder layout than yours, but for sure you can change the cygwin and result folder in any way. But it is not a good idea to call the scripts directly from the git folder, because by default all the cygwin and source packages go into subfolders of it. So I copy this folder to a new folder.

Best regards,

Michael

SET GITDIR_WFMT=%CD%
SET GITDIR_MFMT=%GITDIR_WFMT:\=/%
SET GITDIR_CFMT=%GITDIR_MFMT:C:/=/cygdrive/c/%
SET GITDIR_CFMT=%GITDIR_CFMT:D:/=/cygdrive/d/%
SET GITDIR_CFMT=%GITDIR_CFMT:E:/=/cygdrive/e/%
ECHO %GITDIR_WFMT%
ECHO %GITDIR_CFMT%

CD ..

SET ROOTDIR_WFMT=%CD%
SET ROOTDIR_MFMT=%ROOTDIR_WFMT:\=/%
SET ROOTDIR_CFMT=%ROOTDIR_MFMT:C:/=/cygdrive/c/%
SET ROOTDIR_CFMT=%ROOTDIR_CFMT:D:/=/cygdrive/d/%
SET ROOTDIR_CFMT=%ROOTDIR_CFMT:E:/=/cygdrive/e/%
ECHO %ROOTDIR_WFMT%
ECHO %ROOTDIR_CFMT%

MKDIR cygwin
MKDIR result
MKDIR build

XCOPY %GITDIR_WFMT%\dev\build\windows build /S

CD build
DIR /S

SET COQREGTESTING=Y

SET H
SET U

appveyor DownloadFile http://cygwin.com/setup-x86_64.exe

MakeCoq_MinGW.bat -arch=64 -installer=Y -coqver=%GITDIR_CFMT% -destcyg="%ROOTDIR_WFMT%\cygwin" -destcoq="%ROOTDIR_WFMT%\result"

IF %ERRORLEVEL% NEQ 0 (
  ECHO MakeCoq failed with error code %ERRORLEVEL%
  EXIT /b %ERRORLEVEL%
)


From: Jason Gross [mailto:notifications@github.com]
Sent: Friday, June 09, 2017 10:51 AM
To: coq/coq
Cc: Soegtrop, Michael; Author
Subject: Re: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)


I could e.g. remember the DOS path from which MakeCoq_MinGW.bat was called and use this translated to cygwin format as root path for the relative path. Would this be ok? I discussed this with Maxime before and he said that the path would be outside of the cygwin folder I create.

Sure. Or just use the directory of MakeCoq_MinGW.bat as the root path. The use case I have is that I need to be able to say "if MakeCoq_MinGW.bat is in somedir/dev/build/windows, then the source for the version of Coq that I'm building lives in somedir/" (That is, if I make a fresh clone of Coq, I want to be able to use that clone as the source, without moving MakeCoq_MinGW.bat.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coq/coq/pull/754#issuecomment-307333513>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHh50o91Dhw7OWfpLTP-e27ja8Ha9EKwks5sCQdZgaJpZM4N0ZGU>.
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-09 18:33 UTC, JasonGross commented
@MSoegtropIMC Thanks!  Also, could you merge https://github.com/MSoegtropIMC/coq/pull/1, so it gets added to this PR?

Regarding appveyor timeouts, is there a way to make your scripts not duplicate work if things already exist / are already downloaded?  Or to split up the work so that there's one set of commands to build all the dependencies, and another set of commands to pick up from where those left off and install Coq?  I want to set it up so that I can have appveyor cache all of the build dependencies on one run, and use the cache on subsequent runs to build Coq.

2017-06-09 21:15 UTC, JasonGross commented
Hm, still doesn't build on appveyor for me: https://ci.appveyor.com/project/JasonGross/coq/build/appveyor~41
```
In file included from ml_gtksourceview2.c:24:0:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/gtksourceview-2.0/gtksourceview/gtksourceview.h:216:12: note: declared here
 GdkPixbuf *gtk_source_view_get_mark_category_pixbuf
            ^
Unknown option -Wl,-luuid
File "_none_", line 1:
Error: Error on dynamically loaded library: .\dlllablgtk2.dll: %1 is not a valid Win32 application.
make[1]: *** [Makefile:276: lablgtktop] Error 2
make: *** [Makefile:5: world] Error 2
+ exit 2
++ '[' 1 = 1 ']'
++ '[' -x /usr/bin/clear ']'
++ /usr/bin/clear
[H[J
C:\build>ECHO ERROR MakeCoq_MinGW.bat failed 
ERROR MakeCoq_MinGW.bat failed
C:\build>EXIT /b 1 
```

2017-06-09 21:26 UTC, MSoegtropIMC commented
Dear Jason,

Coq make all starts 16 minutes after the start of the build and takes itself longer than 45 minutes – I think to be safe one would have to split up Coq make all.

I wonder if it wouldn’t make more sense to do this on Amazon AWS EC2. Even if I run an EC2 instance 24/7 it is just 10$/month and I even have systems where I start and stop the EC2 machines as needed via lambda processes . Also one can access all build artefacts and logs (one has full root access), archive stuff in S3 and so on. I would rather donate the cost for 5 years than spending a lot of effort to tweak a system which is hardly suitable for our needs.

If you want to give it a try I can create an instance on my account with a separate ssh/root certificate and send it to you.

Best regards,

Michael

Michael Soegtrop
Principal Engineer
ADG (Autonomous Driving Group)
Vulcan Tech Stream 12 (Simulation) Lead

Phone: +49 (0)89 99 8853-60431
Mobile: +49 (0)172 81 62 56 2
michael.soegtrop@intel.com<mailto:michael.soegtrop@intel.com>

From: Jason Gross [mailto:notifications@github.com]
Sent: Friday, June 09, 2017 8:34 PM
To: coq/coq
Cc: Soegtrop, Michael; Author
Subject: Re: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)


@msoegtropimc Thanks! Also, could you merge MSoegtropIMC#1<https://github.com/MSoegtropIMC/coq/pull/1>, so it gets added to this PR?

Regarding appveyor timeouts, is there a way to make your scripts not duplicate work if things already exist / are already downloaded? Or to split up the work so that there's one set of commands to build all the dependencies, and another set of commands to pick up from where those left off and install Coq? I want to set it up so that I can have appveyor cache all of the build dependencies on one run, and use the cache on subsequent runs to build Coq.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coq/coq/pull/754#issuecomment-307466475>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHh50p8ip8cJb2a2MsNBsxzFLkLNPXgRks5sCZAYgaJpZM4N0ZGU>.
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-09 21:34 UTC, MSoegtropIMC commented
Dear Jason,

see Cavetas.txt. I have only seen this when OCAMLLIB is defined and points somewhere odd. The configure_profile.sh should clear it in the bash profile file.

I haven’t seen this issue- it did run to a timeout.

Best regards,

Michael

From: Jason Gross [mailto:notifications@github.com]
Sent: Friday, June 09, 2017 11:15 PM
To: coq/coq
Cc: Soegtrop, Michael; Author
Subject: Re: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)


Hm, still doesn't build on appveyor for me: https://ci.appveyor.com/project/JasonGross/coq/build/appveyor~41<https://ci.appveyor.com/project/JasonGross/coq/build/appveyor%7E41>

In file included from ml_gtksourceview2.c:24:0:

/usr/x86_64-w64-mingw32/sys-root/mingw/include/gtksourceview-2.0/gtksourceview/gtksourceview.h:216:12: note: declared here

 GdkPixbuf *gtk_source_view_get_mark_category_pixbuf

            ^

Unknown option -Wl,-luuid

File "_none_", line 1:

Error: Error on dynamically loaded library: .\dlllablgtk2.dll: %1 is not a valid Win32 application.

make[1]: *** [Makefile:276: lablgtktop] Error 2

make: *** [Makefile:5: world] Error 2

+ exit 2

++ '[' 1 = 1 ']'

++ '[' -x /usr/bin/clear ']'

++ /usr/bin/clear

�[H�[J

C:\build>ECHO ERROR MakeCoq_MinGW.bat failed

ERROR MakeCoq_MinGW.bat failed

C:\build>EXIT /b 1

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coq/coq/pull/754#issuecomment-307501646>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHh50rfISeJYUX-N3mChBpegSN2ZY1NKks5sCbXlgaJpZM4N0ZGU>.
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-13 07:47 UTC, MSoegtropIMC commented
Dear Jason,

It looks like a random issue – I have seen it once in about 20 build runs. I am repeating the exact the same build in the same location to find out what the issue is. Possibly some make targets cannot handle the –j 8.

Best regards,

Michael

From: Jason Gross [mailto:notifications@github.com]
Sent: Friday, June 9, 2017 11:15 PM
To: coq/coq <coq@noreply.github.com>
Cc: Soegtrop, Michael <michael.soegtrop@intel.com>; Author <author@noreply.github.com>
Subject: Re: [coq/coq] Fixes bug #5561,#5562 in Windows build system (#754)


Hm, still doesn't build on appveyor for me: https://ci.appveyor.com/project/JasonGross/coq/build/appveyor~41<https://ci.appveyor.com/project/JasonGross/coq/build/appveyor%7E41>

In file included from ml_gtksourceview2.c:24:0:

/usr/x86_64-w64-mingw32/sys-root/mingw/include/gtksourceview-2.0/gtksourceview/gtksourceview.h:216:12: note: declared here

 GdkPixbuf *gtk_source_view_get_mark_category_pixbuf

            ^

Unknown option -Wl,-luuid

File "_none_", line 1:

Error: Error on dynamically loaded library: .\dlllablgtk2.dll: %1 is not a valid Win32 application.

make[1]: *** [Makefile:276: lablgtktop] Error 2

make: *** [Makefile:5: world] Error 2

+ exit 2

++ '[' 1 = 1 ']'

++ '[' -x /usr/bin/clear ']'

++ /usr/bin/clear

�[H�[J

C:\build>ECHO ERROR MakeCoq_MinGW.bat failed

ERROR MakeCoq_MinGW.bat failed

C:\build>EXIT /b 1

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/coq/coq/pull/754#issuecomment-307501646>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHh50rfISeJYUX-N3mChBpegSN2ZY1NKks5sCbXlgaJpZM4N0ZGU>.
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-14 07:19 UTC, MSoegtropIMC commented
Dear Jason,

I can hardly believe it, but I have strong evidence that the lablgtk failure is an effect of your logging changes. I have 25 successful runs without your logging changes and 6 failing runs with your logging changes. It has nothing to do with the spacing changes.

Only I have not the slightest clue what mechanism this is. All log files are identical (except camp5 which is –j 8) up to the point of failure and I cannot imagine how your logging changes should influence the lablgtk build.

I will look into the build artifacts. Maybe I find something there.

Best regards,

Michael
Intel Deutschland GmbH
Registered Address: Am Campeon 10-12, 85579 Neubiberg, Germany
Tel: +49 89 99 8853-0, www.intel.de
Managing Directors: Christin Eisenschmid, Christian Lamprechter
Chairperson of the Supervisory Board: Nicole Lau
Registered Office: Munich
Commercial Register: Amtsgericht Muenchen HRB 186928

2017-06-23 07:40 UTC, maximedenes commented
I also got the error reported by Jason, when running the script on a fresh VM. Will try with only the original `sed` and mirror fixes (the two first commits of this PR).

2017-06-26 06:37 UTC, maximedenes commented
I cherry-picked the first two commits to 8.6, so that I can build the Windows packages for 8.6.1. It seems to work fine.

2017-07-27 16:51 UTC, closed without merging

2017-07-27 16:52 UTC, MSoegtropIMC commented
Most of this has already been cherry picked by Maxime.
I meanwhile fixed the lablgtk issue, but I will create a new pull request.