[vernac] Fix unneeded mutual references in Obligations
coq/coq pull request #762
Opened 2017-06-11 14:03 UTC by ejgallego

We remove the need to set a forward reference in `Obligations`, see the commit for more details. No actual code was changed [modulo typos], but just moved.

2017-06-19 07:41 UTC, maximedenes commented
@mattam82 ping

2017-06-19 21:22 UTC, maximedenes commented
@mattam82 Should I merge this as is?

2017-06-20 08:12 UTC, mattam82 requested changes
I'm not super happy with the name "BaseDef", maybe DeclareDef would be more explicit, otherwise I'm fine with the change.

2017-06-20 09:23 UTC, ejgallego commented
@mattam82 done; indeed I could have put the functionality in `Obligations` but IMHO it made more sense as a separate module.

2017-06-23 15:10 UTC, merged