[Makefile] New target “install-merlin”
coq/coq pull request #7633
Opened 2018-05-29 13:15 UTC by vbgl

Building this target installs the files that are used by merlin:
 -  .merlin files (.merlin);
 -  bin-annot files (.cmt, .cmti);
 -  source files (.ml, .mli).

Plug-in developers can thus work with an “installed” version of Coq.

2018-05-29 13:18 UTC, SkySkimmer commented
How is installing .merlin useful?

2018-05-29 13:20 UTC, Zimmi48 commented
To know about Coq's dependencies, I suppose.

2018-05-29 14:02 UTC, ejgallego commented
Installing `.merlin` does look suspicious indeed.

2018-05-29 14:04 UTC, vbgl commented
> How is installing .merlin useful?

This enables using merlin on the Coq source files. E.g., from the plug-in sources you “jump to definition” into the Coq source files; then, it would be annoying if merlin stopped working there (e.g., jumping-to-definition again).

Did I test it wrong?

2018-05-29 18:47 UTC, gares approved these changes

2018-05-29 18:49 UTC, gares requested changes
CMT files are generated only when some conf flags are given. I suspect install Merlin fails in that case. You can use find there too imho.

2018-05-29 21:05 UTC, gares approved these changes
I did not spot `$(wildcard` on my mobile, sorry for the noise

2018-05-29 22:10 UTC, ejgallego commented
No idea about installing .merlin then, it makes sense but I am not sure what other tools do. Cmt is fine. Ml are usually installed in a separate for, will try to learn more

2018-05-29 22:39 UTC, SkySkimmer commented
Does dune have a story about installing dev files? Or do we have to specify it manually like with make?

2018-05-29 23:33 UTC, ejgallego commented
@SkySkimmer Dune installs a standard dev file set, including the `.ml` and `cmt` files already. No `.merlin` tho so I wonder why.

2018-05-30 07:07 UTC, rgrinberg commented
There's no need to install .merlin files for merlin to lookup definitions in external packages. I'm pretty sure merlin just relies on the cmt{,i} and ml{,i} being available for external packages.

2018-05-30 07:58 UTC, ejgallego commented
Whst about merlin working on installed 'ml' files @rgrinberg ?

2018-05-30 08:06 UTC, rgrinberg commented
I think we might be talking about the same thing. By external packages, I mean those installed via opam/findlib. Merlin indeed requires those to be present for go to definition to function. Consequently, dune installs those. For example:

```
$ ls ~/.opam/4.06.1/lib/re/*.ml*
/Users/rgrinberg/.opam/4.06.1/lib/re/automata.ml        /Users/rgrinberg/.opam/4.06.1/lib/re/emacs.mli          /Users/rgrinberg/.opam/4.06.1/lib/re/pmark.mli
/Users/rgrinberg/.opam/4.06.1/lib/re/automata.mli       /Users/rgrinberg/.opam/4.06.1/lib/re/fmt.ml             /Users/rgrinberg/.opam/4.06.1/lib/re/posix.ml
/Users/rgrinberg/.opam/4.06.1/lib/re/category.ml        /Users/rgrinberg/.opam/4.06.1/lib/re/glob.ml            /Users/rgrinberg/.opam/4.06.1/lib/re/posix.mli
/Users/rgrinberg/.opam/4.06.1/lib/re/category.mli       /Users/rgrinberg/.opam/4.06.1/lib/re/glob.mli           /Users/rgrinberg/.opam/4.06.1/lib/re/re.ml
/Users/rgrinberg/.opam/4.06.1/lib/re/core.ml            /Users/rgrinberg/.opam/4.06.1/lib/re/pcre.ml            /Users/rgrinberg/.opam/4.06.1/lib/re/re__.ml-gen
/Users/rgrinberg/.opam/4.06.1/lib/re/core.mli           /Users/rgrinberg/.opam/4.06.1/lib/re/pcre.mli           /Users/rgrinberg/.opam/4.06.1/lib/re/str.ml
/Users/rgrinberg/.opam/4.06.1/lib/re/cset.ml            /Users/rgrinberg/.opam/4.06.1/lib/re/perl.ml            /Users/rgrinberg/.opam/4.06.1/lib/re/str.mli
/Users/rgrinberg/.opam/4.06.1/lib/re/cset.mli           /Users/rgrinberg/.opam/4.06.1/lib/re/perl.mli
/Users/rgrinberg/.opam/4.06.1/lib/re/emacs.ml           /Users/rgrinberg/.opam/4.06.1/lib/re/pmark.ml
```

2018-05-30 08:18 UTC, vbgl commented
When I don’t install the `.merlin` files, I observe the following behavior.

From the plug-in code, I jump-to-definition inside `coqlib.ml` (source code of Coq); from here, if I try to jump-to-definition of `Libnames.make_path`, merlin fails with the following message:

```
merlin: Error: Unit Coqlib imports from Libnames, which uses recursive types.
       The compilation flag -rectypes is required
```

2018-05-30 09:46 UTC, rgrinberg commented
Hmm, that's a good point. I guess when you're changing compile flags you need this. I'd have to bring this up with the merlin team, but I suppose there's no harm in installing .merlin files. Dune could do this too (if proven useful)

2018-05-30 14:14 UTC, ejgallego commented
Thanks @rgrinberg

2018-05-31 08:06 UTC, merged

2018-05-31 14:48 UTC, vbgl commented
@Zimmi48 I think it is worth porting this to 8.8. Thanks.