make clean: remove g_*.ml files
coq/coq pull request #7802
Opened 2018-06-13 21:28 UTC by SkySkimmer

People keep running into issues with these since the one PR which moved them. This isn't a very general solution but it's better than nothing.

Since our CI cleans before building it will detect if someone adds a non-generated file named g_foo.ml.

NB: g_*.ml is already in our gitignore.

2018-06-25 10:48 UTC, SkySkimmer commented
@gares can you take this since @letouzey is inactive?

2018-06-25 11:22 UTC, gares commented
Given the extension (also belonging to real files) I prefer the pattern to be based on first finding .ml4 files and then removing the corresponding ml one. You could try something like this (but I think we already have  a list of ML4 files around):
```make
rm -f (addsuffix .ml,$(basename $(wildcard */g_*.ml4 plugins/*/g_*.ml4)))
```

2018-06-25 11:34 UTC, Zimmi48 commented
@gares This is supposed to work around a problem that many users have encountered after they did `git pull` and a `.ml4` file had moved. So your solution won't work.

2018-06-25 11:37 UTC, SkySkimmer commented
I think @gares means we can delete any ml file which has the name of a ml4 file.

2018-06-25 14:15 UTC, gares commented
Make clean should remove what was generated by the Makefile, if you `make` then `git pull` then `git clean` I don't expect it to clean renamed files.

What I don't like about this patch is that `make clean` may remove `.ml` files that are not generated (by the old or current Makefile). Again, it is not a big deal for `.cmx`, say, but `.ml` if what I produce as a human.

I know `git clean -dfx` is dangerous, so I don't run it in the middle of my dev (before a commit).
I don't think `make clean` should be dangerous.

I've just checked the makefile, just use `rm -f $(ML4FILES:.ml4=.ml)`.

2018-06-25 14:16 UTC, SkySkimmer commented
>Make clean should remove what was generated by the Makefile, if you make then git pull then git clean I don't expect it to clean renamed files.

The goal is to clean files that were generated by files which are now renamed.

2018-06-25 14:17 UTC, gares commented
Then put `git clean -dfx` in your CI.

2018-06-25 14:17 UTC, gares requested changes
use git clean

2018-06-25 14:18 UTC, SkySkimmer commented
It's not for CI, it's for users who pull and get a broken working directory.

2018-06-25 14:23 UTC, gares commented
I don't like this change.
The generated files are confused with the non-generated ones, this is the problem,
otherwise alienclean could deal with this.

I think we should rename the `.ml` (generated) in `.mlwhatever`.
Then I'd be fine with a `find ... -delete` since `.mlwhatever` would be *always* safe to delete.

2018-06-25 14:25 UTC, gares requested changes
To safely detect which files come from renamed `.ml4` files, make the extension of pre-processed `.ml4` files *different* from `.ml`, eg `.mlexpanded`

2018-06-25 14:33 UTC, gares commented
One not knowing this convention may call a file `g_something.ml`.
He may not call it `something.mlexpanded`.
IMHO, they are fundamentally different.

2018-06-25 15:10 UTC, ejgallego commented
> make the extension of pre-processed .ml4 files different from .ml, eg .mlexpanded

Please _don't_, if your build system is a mess don't make the life of saner people painful, using non-standard suffixes and breaking editor support among other things.

2018-06-25 15:34 UTC, gares commented
Generated files don't even need to exist in the first place. This is how CoqMakefile deals with .ml4.
In the Makefile of Coq the choice to save on disk the intermediate data (mashalled AST) with extension .ml.

These .ml file are not .ml files, they are generated and your editor is not letting you edit them.
If you use READABLE_ML4 then these .ml become readable (a debugging feature).

In Dune these problems don't exist, and `git clean dfx` can be replaced by `rm -rf _build`.
I don't see how cleaning up the mess above would make the life of others harder.

2018-07-12 11:49 UTC, closed without merging

2018-07-12 11:50 UTC, maximedenes commented
The real fix for this pb is a hygienic build.