Towards listing the critical bugs of the history of Coq.
coq/coq pull request #7805
Opened 2018-06-13 23:41 UTC by herbelin

This is a very first try at listing the critical bugs of the history of Coq. Without counting the 3 pending critical bugs, I collected 16 bugs (4 about `match`, `fix`, `cofix`, 3 about universes, 2 about prim. proj., 4 `vm_compute` or `native_compute`, 3 conflicts with the "intended model"), but I feel there are a couple more.

In particular, I let open several questions regarding fixes made to the kernel but which I could not decide easily from the description or patch if they were critical/exploitable.

I skipped what seemed to have been bugs in beta-releases.

Need double-checks, decision about the format, etc. In particular, I put quite a lot of details, which I agree are not necessary for a quick reading. On the other side, if someone has more information on the "essence" of the bugs, that would certainly be useful. 

**Kind:** documentation

Closes #7604

There a lot of `?` in the text. Don't hesitate to update and push to this PR.

2018-06-14 07:19 UTC, Zimmi48 commented on dev/doc/critical-bugs
> +  fixed in: master (c9f3a6cbe5c41, 12 Feb 2018, PR#6713, Dénès), v8.7 (c058a4182, 15 Feb 2018, Zimmermann), v8.6 (a2cc54c6, 21 Feb 2018, Herbelin), v8.5 (d4d550d0f1a, 21 Feb 2018, Herbelin)
I'm just the committer for this commit. The listed author is Maxime Dénès.

2018-06-14 10:09 UTC, herbelin commented on dev/doc/critical-bugs
> +  fixed in: master (c9f3a6cbe5c41, 12 Feb 2018, PR#6713, Dénès), v8.7 (c058a4182, 15 Feb 2018, Zimmermann), v8.6 (a2cc54c6, 21 Feb 2018, Herbelin), v8.5 (d4d550d0f1a, 21 Feb 2018, Herbelin)
I clarified your role by adding the mention "backport" (here and everywhere else relevant). That'd be ok?

2018-06-14 11:19 UTC, Zimmi48 commented on dev/doc/critical-bugs
> +  fixed in: master (c9f3a6cbe5c41, 12 Feb 2018, PR#6713, Dénès), v8.7 (c058a4182, 15 Feb 2018, Zimmermann), v8.6 (a2cc54c6, 21 Feb 2018, Herbelin), v8.5 (d4d550d0f1a, 21 Feb 2018, Herbelin)
Yes

2018-06-14 14:37 UTC, JasonGross commented
Could we make this a `.md` file, and have the "exploit" be a link to the actual file in the test-suite?
(Something like (untested) `sed s',exploit: \([^\.]*\.v\)$,exploit: [\1](../../\1),g' -i`)

2018-06-14 15:20 UTC, JasonGross requested changes

2018-06-14 15:20 UTC, JasonGross commented on dev/doc/critical-bugs
> +  exploit: lost?
I think this one might actually be 244d7a9aafe7ad613dd2095ca3126560cb3ea1d0, which includes the exploit in the commit message?

> `Unicode.ascii_of_ident` is now truly injective
>
> A non-ASCII char is now converted to `_UUxxxx_` with xxxx being its unicode index
 in hexa. And any preexisting `_UU` substring in the ident is converted to `_UUU`.
 The switch from `__Uxxxx_` to `_UUxxxx_` is cosmetic, it just helps the extraction
 (less __ in names). But the other part of the patch (detection of preexisting
 `_UU` substrings) is critical to make `ascii_of_ident` truly injective and avoid
 the following kind of proof of False via native_compute :
>
>      Definition α := 1.
>      Definition __U03b1_ := 2.
>      Lemma oups : False.
>      Proof.
>       assert (α = __U03b1_). { native_compute. reflexivity. }
>       discriminate.
>      Qed.

I think the commit you're pointing at (a91d15dcb4) is just cosmetic?

2018-06-14 15:28 UTC, JasonGross submitted a review, later dismissed

2018-06-14 15:28 UTC, JasonGross commented on dev/doc/critical-bugs
> +  fixed by constraining the guard condition: bac7079739, 28 Oct 2004, Barras, Dénès
bac7079739 is 
> Set devient predicatif par defaut
>
> git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/trunk@4726 85f007b7-540e-0410-9357-904b9bb8a0f7

by @herbelin committed on Oct 28, 2003...

Also, is this the one whose proof is
```coq
Axiom ext : (False -> False) = True.
Fixpoint oops (x : True) : False
  := match x with
     | I => oops (match ext in (_ = T) return T with
                  | eq_refl => fun absurd => match absurd with end
                  end)
     end.
```
which is still present as late as 8.4pl6?

2018-06-14 20:16 UTC, herbelin commented on dev/doc/critical-bugs
> +  fixed by constraining the guard condition: bac7079739, 28 Oct 2004, Barras, Dénès
Bad copy-paste. I changed for a more relevant commit, but I'm not sure it was fixed by only  one commit and if one commit exactly this one. I'm unaware of the exact history and if @maximedenes could give the needed clarifications and fill the missing bits, that would be wonderful.

2018-06-14 20:17 UTC, herbelin commented on dev/doc/critical-bugs
> +  exploit: lost?
Right. Fixed. Thanks.

2018-06-14 20:20 UTC, herbelin commented
> Could we make this a .md file, and have the "exploit" be a link to the actual file in the test-suite?
(Something like (untested) sed s',exploit: \([^\.]*\.v\)$,exploit: [\1](../../\1),g' -i)

We can certainly eventually do that. As a first step, my idea was to help with the historical digging, to get confirmation by the authors that these was critical bugs. I dont' know what was the idea of @ppedrot at the beginning when he opened #7604.

2018-06-15 10:09 UTC, herbelin commented
> @herbelin If you think that you want to stop there, we can also consider merging as it is right now and let other people like @JasonGross open new PRs to propose a different format.

I shall not really have time to work more on it now. So, your proposal is ok to me if it is ok for others.

2018-06-15 10:32 UTC, maximedenes commented
I like the idea of tracking critical bugs, and use it as a way of showing we are taking them seriously. It would be good to add a number to identify each of the listed soundness bug, in the spirit of CVE. Maybe like CSB-2018-XXX (CSB = Coq Soundness Bug).

We should also document what needs to be done when a new soundness bug is discovered.

2018-06-15 11:21 UTC, herbelin commented
Ideally, someone with "physical access" to @barras should ask him if among the various bugs he fixed in the kernel along the years, there are still some not in my list which were critical.

2018-06-15 12:57 UTC, Zimmi48 commented
OK then I shall merge this in the beginning of next week. Anyone should feel free to push commits on top of this branch in the meantime. Also, maybe it would make sense to add an entry in CHANGES to mention the existence of this new document?

2018-06-20 12:31 UTC, gares commented
Dear Hugo, I think this is also a critical bug (that I don't find in the list). This is a commit fixing it in 8.2 c1d988904483eb1f3a8917ea08fced1240e3844b IIRC it was not there in 8.1. I think I did fix it also in 8.3, 8.4 and 8.5

2018-06-22 12:59 UTC, gares commented
component: modules
summary: universe constraints for module subtyping not stored in vo files
introduced: 8.2 (b3d3b566c5b)
impacted released versions: 8.2, 8.3, 8.4
impacted development branches: v8.5
impacted coqchk versions: none
fixed in: v8.2 (c1d9889), v8.3 (8056d02), v8.4 (a07deb4ea), trunk (0cd0a3ecdc7) Mar 5, 2014, Tassi
found by: Tassi by running coqchk on the mathematical components library
exploit: requires multiple files, no test provided
GH issue number: #3243
risk: could be exploited by mistake

2018-06-22 13:01 UTC, gares commented
I'm not 100% sure about the commit that introduced it (I'm not an expert of this code).

2018-06-22 13:30 UTC, gares commented
I also don't see the bug fixed with this commit a8b034513e0c03ceb7e154

2018-06-24 13:43 UTC, herbelin commented
@gares: I added #3243. Thanks so much.

About Georges' bug in the lazy machine, there was indeed a 6-line exploit. I added it an entry for it. Thanks also very much.

2018-06-24 17:02 UTC, Zimmi48 approved these changes
I'll merge this now and I'll let whoever wants to change the format to a Markdown file do it in a subsequent PR.

2018-06-24 17:04 UTC, merged

2018-06-25 08:04 UTC, gares commented
> I added it an entry for it.

Sorry but I don't see that

2018-06-25 08:14 UTC, gares commented
@Zimmi48

2018-06-25 08:42 UTC, gares commented
I think @herbelin can just open another PR with the extra commits by rebasing his `master+history-critical-bugs` on today's master.

2018-06-25 09:06 UTC, herbelin commented
Explanation: I had renamed the branch and pushed to the wrong name. Sorry about that. See #7917 for the two extra items.