Remove Emacs modes
coq/coq pull request #7843
Opened 2018-06-16 14:12 UTC by Zimmi48

On top of #7836 to avoid conflicts.

2018-06-16 15:29 UTC, ejgallego commented
Just let me note that some time ago I think people were using to integrate Coq with `org-mode`, maybe it was @Matafou ? Just in case.

2018-06-18 07:47 UTC, Matafou commented
Not me, it was Alan Shmitt. I don't know if he is still interested in this.

2018-06-20 13:06 UTC, gares commented
> Not me, it was Alan Shmitt. I don't know if he is still interested in this.

I think @Zimmi48 should mention this in CHANGES.

2018-06-20 13:16 UTC, Zimmi48 commented
Good point. Added.

2018-06-20 13:52 UTC, ejgallego commented
Maybe we should ping Alan? He could be interested in maintaining it.

2018-07-04 08:34 UTC, gares approved these changes

2018-07-04 08:37 UTC, gares commented
Even if the file is maintained, I don't see why it should be in Coq proper. PG is not in Coq, for example.

2018-07-04 09:09 UTC, Matafou commented
Maybe this should go in melpa as a coq-light-mode package?

2018-07-04 09:32 UTC, Zimmi48 commented
If there are users, we can help us set an external repository to maintain this (for instance as part of https://github.com/coq-community) and publish a MELPA package from there. But it doesn't really make sense to keep it part of Coq source code.
If you want, I can extend the CHANGES notes to say exactly what I've just said.

2018-07-04 11:59 UTC, Matafou commented
Fair enough. If it happens that this thing has users we may decide to make Coq-light-mode a sub-distribution of pg itself. With a good hope that it will sync better with Coq.

2018-07-04 12:04 UTC, Zimmi48 commented
So should I add a note?

2018-07-04 13:18 UTC, Matafou commented
Yes you should IMHO.

Le mer. 4 juil. 2018 à 14:04, Théo Zimmermann
<notifications@github.com> a écrit :
>
> So should I add a note?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-07-04 16:14 UTC, Zimmi48 commented
Done and rebased.

2018-07-05 10:03 UTC, ejgallego approved these changes
Configure changes are fine.

2018-07-06 07:01 UTC, Zimmi48 commented
Ready to go. Who's self-assigning?

2018-07-07 16:48 UTC, maximedenes approved these changes

2018-07-07 16:50 UTC, maximedenes requested changes
typo to be fixed and quick rebase needed

2018-07-07 16:50 UTC, maximedenes commented on CHANGES
> +- The Emacs modes distributed with Coq where removed. You are advised to
where -> were

2018-07-07 22:15 UTC, Zimmi48 commented
Fixed and rebased.

2018-07-08 08:10 UTC, maximedenes approved these changes

2018-07-08 08:12 UTC, merged