Fix #7704: Launching coqide through PATH fails.
coq/coq pull request #7860
Opened 2018-06-18 12:27 UTC by SkySkimmer

2018-06-18 23:25 UTC, ejgallego requested changes
Please document this issue properly, in most cases `exe_name` is set to `argv[0]` in `startup.c`, so why is that not enough?

2018-06-20 13:54 UTC, ejgallego commented
To be clear I am not asking for a code change but for a better commit message.

2018-06-22 12:01 UTC, SkySkimmer commented
Updated (and added test).

2018-06-22 12:25 UTC, gares submitted a review, later dismissed

2018-06-22 12:43 UTC, Zimmi48 commented
Emilio's request was about the commit message, which has been improved.

2018-06-22 13:16 UTC, SkySkimmer commented on test-suite/Makefile
> +	  export COQBIN="$(BIN)"; \
Changed for just BIN.

2018-06-24 19:23 UTC, ejgallego commented
Umm, still something is puzzling me, I am not sure this is not a bug in OCaml. Let's take this program:

```ocaml
let _ =
  Format.printf "%s,%s\n%!" Sys.argv.(0) Sys.executable_name
```
Adding `k` to my path and using `ocamlc`:
```
/home/egallego/my/lib/shell/k,/home/egallego/my/lib/shell/k
```
however using `ocamlopt`:
```
k,/home/egallego/my/lib/shell/k
```
gives a different result. Ummm, I am not sure I like this discrepancy here, even if I understand the reason behind it.

Anyways I shall merge I think but IMHO we should document this ocaml problem better.

2018-06-25 04:06 UTC, ejgallego commented
Another question I do have is why do we need a normalized argument name for a path call.

As far as I can see, if the user calls `coqtop` from path, `coqidetop` for example should be also searched using PATH, right?

What is the problem we are having here? Why is coqtop in path but not the rest of the proper toplevels?

The original implementaton indeed tried to rely on path for that; I guess using the canonical one is not a problem but I'd like to understand what the problem is in the first place.

2018-06-25 17:05 UTC, SkySkimmer commented
Here's a log of launching coqide through PATH with debug printing
~~~
(Spawn  ,21597) EXEC: coqidetop -main-channel stdfds --xml_format=Ppcmds -async-proofs on
(Spawn  ,21597) PID 21604
Welcome to Coq debian-hibiki:/home/gaetan/dev/coq/coq,def-const-nosubst (efb27a1bbdda4d4b36ece4e6fa4359bfeddc9549)
(Spawn  ,21604) EXEC: ./coqproofworker.opt -main-channel stdfds --xml_format=Ppcmds -worker-id proofworker:0 -async-proofs-worker-priority low
(Spawn  ,21604) PID 21607
Handshake with proofworker:0 failed: End_of_file
(Spawn  ,21597) EXEC: coqidetop -main-channel stdfds --xml_format=Ppcmds -async-proofs on
(Spawn  ,21597) PID 21609
(Spawn  ,21597) This process is already dead
Welcome to Coq debian-hibiki:/home/gaetan/dev/coq/coq,def-const-nosubst (efb27a1bbdda4d4b36ece4e6fa4359bfeddc9549)
(Spawn  ,21609) EXEC: ./coqproofworker.opt -main-channel stdfds --xml_format=Ppcmds -worker-id proofworker:0 -async-proofs-worker-priority low
(Spawn  ,21609) PID 21613
Handshake with proofworker:0 failed: End_of_file
~~~
When argv.(0) is unqualified the dirname in System.get_toplevel_path returns ./ which is not what we want.
coqidetop gets launched correctly because https://github.com/coq/coq/blob/a1fc621b943dbf904705dc88ed27c26daf4c5e72/ide/ideutils.ml#L295-L304 falls back to PATH when the file doesn't exist, but for the proofworker there is no such fallback so it calls spawn with ./coqproofworker.opt (as we can see in the log).

2018-06-25 17:07 UTC, SkySkimmer commented
>Ummm, I am not sure I like this discrepancy here, even if I understand the reason behind it.

What is the reason?

2018-06-25 17:07 UTC, SkySkimmer commented
>When argv.(0) is unqualified the dirname in System.get_toplevel_path returns ./ which is not what we want.

We could handle that on our side but using `executable_name` does it for us so let's go with it.

2018-06-25 18:02 UTC, ejgallego commented
Thanks for the explanation.

> What is the reason?

The reason for the discrepancy is that for bytecode programs, `argv.(0)` is `ocamlrun` so the runtime tries some normalization. But now I see what the problem is:

> When argv.(0) is unqualified the dirname in System.get_toplevel_path returns ./ which is not what we want.
> coqidetop gets launched correctly because

Oh that's indeed a bug in the code, but I am not sure if we should use the canonical name or just check the name better and still allow for the path to override the install. Let me think for a minute.

2018-06-27 15:20 UTC, ejgallego commented
> Let me think for a minute.

So WDYT @SkySkimmer ? Should we allow PATH to override file-path based resolution [and thus modify the code], or should we take the canonical, but less flexible approach?

The spirit of the buggy code was 1) , anyways, IMHO the code needs a comment.

2018-06-28 15:17 UTC, maximedenes commented
This is a very serious bug. Can we merge this?

If this really requires more work before being merged (I doubt it), I suggest we revert the commit that introduced this regression.

2018-06-28 15:50 UTC, ejgallego commented
> Canonical. Feel free to add a comment.

We will indeed have to modify the whole setup, but let's merge for now.

2018-06-28 15:50 UTC, ejgallego approved these changes

2018-06-28 15:58 UTC, merged

2018-09-05 12:43 UTC, ejgallego commented
Indeed we need to further tweak the strategy here as this creates problems when Coq is installed using symlinks, such as in Dune builds [which seems essential to save disk space]

I think the strategy here should be way simpler, take `argv.[0]` and extract the directory, then append the proper subbinary name.