Remove omega and romega.
coq/coq pull request #7878
Opened 2018-06-20 22:21 UTC by maximedenes

We move `zify` to `micromega` and rebind `omega` and `romega` to `lia`.

Lia cannot be boostrapped in exactly the same way as omega, so the
stdlib will have to be adapted so as not to rely on lia inside ZArith.
Laurent Théry offered to remove the admits there.

This is work in progress, but it is looking good: CompCert has around 3000 calls to `omega` and requires only a 4-line patch.

2018-06-20 22:22 UTC, ppedrot commented
I'd be curious to see a bench also!

2018-06-20 23:58 UTC, andres-erbsen commented
If other benchmarks look promising, please benchmark this change on https://github.com/mit-plv/bedrock2 and dependencies even though these are not normally a part of CI/benchmarks. Or just tell me when and how I should do it. Thanks!

2018-06-21 03:09 UTC, JasonGross commented
Maybe we should add bedrock2 to opam and the CI?

2018-06-21 03:15 UTC, JasonGross requested changes
As codeowner of the Compat files (is that all I'm requested for here?  Is there a way to get GitHub to tell me?), I approve.

Separately, this needs updates to the documentation.  Also maybe `omega` and `romega` should emit deprecation warnings?  Also is it worth keeping `romega` alive as a separate plugin on opam?  (Do we know where `romega` and `lia` don't overlap?)

2018-06-21 03:19 UTC, JasonGross commented
@andres-erbsen  Note that bedrock2 cannot currently be benched because it will fail to build (by construction) for any `coqc` not reporting as 8.7.2.

2018-06-21 06:16 UTC, maximedenes commented
> Separately, this needs updates to the documentation. Also maybe omega and romega should emit deprecation warnings? Also is it worth keeping romega alive as a separate plugin on opam? (Do we know where romega and lia don't overlap?)

Sure, this is in progress as indicated by the corresponding label.

2018-06-22 10:10 UTC, fajb commented on plugins/btauto/Algebra.v
> +  destruct (Pos.compare_spec x y); try (exfalso; lia)
In exfalso; lia, exfalso is redundant for lia. This would only be an optimisation if the conclusion is a complex arithmetic formula.

2018-06-22 10:13 UTC, fajb commented on plugins/btauto/Algebra.v
>  Hint Extern 5 =>
This whole tactic can be optimised away and directly replaced by lia.
My guess is that zify improved and is now dealing with Pos.max

2018-06-22 10:13 UTC, fajb approved these changes
This is a bold move but that could be the time to make it. 
As I told @maximedenes  in a private message both omega and lia have known shortcoming -- meaning they are incomplete for linear arithmetics.

Having a drop-in replacement will require some work and extensive benchmarking.

2018-06-23 07:43 UTC, thery commented
Ok I think I've removed all the "admit"

2018-06-23 14:48 UTC, maximedenes commented
@thery Impressive! Thanks a lot for your help :)

2018-06-23 16:46 UTC, herbelin reviewed
Same remarks as for `fourier`. There has been work, sweat, passion put in developing the different plugins. Whatever decision is taken so as to combine the respective strengthes of every work in a common framework, so as to simplify the pedagogy, so as to simplify the maintainance, so as to improve our understanding of the underlying techniques, I wish that it is done in a way respectful of the work of everyone done in the past.

2018-06-24 10:16 UTC, Zimmi48 commented
> I wish that it is done in a way respectful of the work of everyone done in the past.

More than the initial author, the one who could be bothered by the removal of `romega` at this point is @letouzey who has taken time to clean it up last summer. But he's already said:

> So for now I'd vote for romega, even if the actual winner will probably be the one able to replace omega without too much drama.

(cf. https://github.com/coq/coq/issues/7872#issuecomment-398814289)

2018-06-24 10:16 UTC, Zimmi48 commented
Here as well, if deemed valuable, `romega` could continue being maintained as part of https://github.com/coq-community...

2018-06-28 14:51 UTC, bollu commented
For some more context, I actually benchmarked on the files linked by @maximedenes , and here were the results on my machine:

```
(** With  lia **)
╭─bollu@cantordust ~/work/dependence-analysis-coq/dependence-loop  ‹master*›
╰─$ time coqc proof.v
coqc proof.v  6.41s user 0.17s system 99% cpu 6.583 total

(** Stash changes **)
╭─bollu@cantordust ~/work/dependence-analysis-coq/dependence-loop  ‹master*›
╰─$ git stash
Saved working directory and index state WIP on master: 814382e add example of creating a _coinductionn principle_ from gitter
HEAD is now at 814382e add example of creating a _coinductionn principle_ from gitter

(** run with omega **)
╭─bollu@cantordust ~/work/dependence-analysis-coq/dependence-loop  ‹master*›
╰─$ time coqc proof.v
coqc proof.v  2.80s user 0.17s system 99% cpu 2.971 total
```

This is embedded in the commit message https://github.com/bollu/dependence-analysis-coq/commit/bfa4d23f93817cb71088599699e28cff0189489f

2018-07-16 10:00 UTC, ppedrot approved these changes

2018-07-23 20:00 UTC, gares approved these changes
makefile changes are ok

2018-07-25 15:34 UTC, Zimmi48 commented
Rebase when you push. Your branch is not up-to-date with master so in order to avoid various problem, GitLab CI won't start. See also #8079.

2018-07-27 07:11 UTC, samuelgruetter commented
@maximedenes why do you have to make PRs to many repos on the CI? Do you want this to be a breaking change with the next Coq version? That is, will all projects updating to the next Coq version have to do diffs of the form

```
-Require Import Coq.omega.Omega.
+Require Import Coq.micromega.Lia.
```

in all their files? Why do you not keep a file that I can import with `Require Import Coq.omega.Omega.` which defines `omega` as an alias for `lia`, and emits a deprecation warning?

2018-07-27 07:15 UTC, maximedenes commented
@smauelgruetter Good question :) That's not the most common diff, in fact I usually replace : `Require Import Coq.omega.Omega.` with `Require Import Coq.ZArith.ZArith.`. I think it is a sound change anyway.

We have no machinery to emit a deprecation warning at `Require`, so unfortunately I couldn't proceed as you suggest.

But anyway, many patches I'm submitting are fixing scripts that relied on incompleteness bugs of `omega` (basically, I have to remove a few lines of script here and there).

2018-07-28 07:29 UTC, maximedenes commented
I guess we could, but it will leave some noise in our `Makefile`, and I'm not sure what it would bring since:
- we won't have a way to generate a deprecation warning, so the problem of removing this file will just be delayed, not solved
- the change from `Require Coq.omega.Omega` to `Require Coq.ZArith.ZArith` is backward compatible, so I don't see why it couldn't be done now downstream.

2018-07-28 16:14 UTC, samuelgruetter commented
Here's a way to emit a deprecation warning: https://github.com/maximedenes/coq/pull/62
What do people think about it?

2018-07-30 14:14 UTC, herbelin commented
In passing, after so many years, it is great that an observational superset of `omega`, `romega` of `lia` is finally found, which integrates the best of what we know how to provide. Hats off.

2018-07-30 15:05 UTC, Zimmi48 commented
>I don't think this is doable because external developments precisely rely on what the standard library does, through leakage of hints...

I only meant removing the dependency on `omega` in opaque proofs, not in hint definitions or such.

2018-09-02 13:58 UTC, herbelin commented
What is the status of this PR? Is this 8.9 milestone? Also, omega and romega do not occur anymore in the CODEOWNERS file, am I supposed to be the assignee? Can someone make a summary of what it changes user side in practice?

2018-09-02 14:29 UTC, Zimmi48 commented
Given how close the branching is now I would recommend only deprecating omega / romega in 8.9 and doing the actual removal (without compatibility layer) after the branching.

2018-09-04 14:09 UTC, silene commented
While experimenting with the replacement of `omega` by `lia`, I have encountered yet another issue with `zify`, namely #8399 . While I am in favor of removing `omega` and `romega`, we cannot replace them with `lia` until the issues with `zify` are fixed. Perhaps an intermediate solution would be to replace them by

```
Ltac omega := unfold Z.succ in * ; unfold Z.pred in * ; xlia zchecker.
```

which is `lia` without `zify`.

2019-09-25 11:26 UTC, pi8027 commented
Now, `lia` seems to be able to solve all the problems that `omega` can solve. https://github.com/coq/coq/labels/part%3A%20micromega

2019-09-25 12:15 UTC, Zimmi48 commented
Maybe it's time to officially deprecate omega then (in 8.11 I suppose, because Coq 8.10 did not receive all the recent lia improvements).

2019-09-25 12:49 UTC, pi8027 commented
> Given how close the branching is now I would recommend only deprecating omega / romega in 8.9 and doing the actual removal (without compatibility layer) after the branching.

> Maybe it's time to officially deprecate omega then (in 8.11 I suppose, because Coq 8.10 did not receive all the recent lia improvements).

@Zimmi48 I agree with you. If we deprecate them without actual removal, we could receive new issues with detailed comparisons of `lia`, `omega`, and `romega`, like #9921. If we remove `omega` and `romega` silently, we will lose a chance to identify hidden issues of Micromega.

2019-09-25 15:05 UTC, Zimmi48 commented
`romega` has already been removed silently though

2020-01-28 20:40 UTC, ppedrot commented
Isn't this basically superseded by #11286? The rebase of the current PR looks like it's going to be a mess...

2021-01-22 18:50 UTC, Zimmi48 commented
Superseded by #13741.

2021-01-22 18:50 UTC, closed without merging