Reimplement Store using Dyn
coq/coq pull request #7881
Opened 2018-06-21 03:30 UTC by whitequark

**Kind:** cleanup.

This PR reimplements Store with Dyn as requested in https://github.com/coq/coq/pull/7850#issuecomment-398415569. It depends on (and includes) #7880, though can be decoupled with no large work.

2018-06-21 08:55 UTC, ppedrot commented
You should probably rebase to clearly see the new commits w.r.t. #7880.

2018-06-21 09:34 UTC, ppedrot commented
GitHub is pretty dumb when it comes to PRs depending on other PRs.

2018-06-21 09:36 UTC, ppedrot requested changes
This doesn't solve the soundness problem of `Store`, which is that the index for a given store entry depends on the link order. They should be given using a really absolute name instead.

2018-06-21 09:46 UTC, whitequark commented
> This doesn't solve the soundness problem of Store, which is that the index for a given store entry depends on the link order. They should be given using a really absolute name instead.

Indeed, but doesn't `Dyn` always have the same soundness problem, just in slightly different conditions, then? Absolute names are not sufficient if code can change, e.g.:
  1. module A defines `let x : int Dyn.tag = Dyn.create "x"`
  2. module A serializes `let bytes = Marshal.to_bytes [] Dyn.Dyn (x, 1)`
  3. `bytes` is saved to disk, Coq is stopped
  4. Coq is started, `bytes` are loaded from disk
  5. module A defines `let x : string Dyn.tag = Dyn.create "x"`
  6. module A deserializes `print_string (Marshal.of_bytes bytes)`
  7. oops.

2018-06-21 09:51 UTC, ppedrot commented
It's true, but in the current architecture I don't see how you could deserialize the data without having linked the plugin first. That said, we should probably serialize the table of dynamic types in vo files to work around this kind of problem.

2018-06-21 09:53 UTC, whitequark commented
I propose to solve this by:
  * enabling serialization of closures globally
  * adding a sentinel to each instance of Dyn, which would be an empty closure defined in the *same module* as the field (there might be some way to enforce this, but it should be robust enough even by convention)
  * using this sentinel as the integral value of the tag, sans high bits

If this is done, we handle every possible case.
  * If the field was defined in some loadable module that was loaded before but isn't loaded now, then input_value will raise an exception (since module is missing).
  * If the field was defined in some loadable module that was changed and so maybe the type of the field is different now, then input_value will raise an exception (since md5 differs and so the module is "missing").
  * All tags are guaranteed to be unique with no need for manual explicit specification of absolute paths, although they of course can still be specified.

2018-06-21 12:12 UTC, ppedrot commented
@whitequark If you have a working POC somewhere I'd be happy to see it.

2018-06-21 19:52 UTC, whitequark commented
> If you have a working POC somewhere I'd be happy to see it.

Sure. https://github.com/whitequark/ocaml-cavalry. Clone then `make demo`. Code and comments should be well sufficient.

You're welcome to try and break it in any way whatsoever (without Obj).

2018-09-06 09:27 UTC, ppedrot commented
FTR I launched a bench on a rebase of this branch at https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/507/.

2018-10-08 08:46 UTC, ppedrot commented
There is a slight slowdown in VST, and this was kind of expected. There is one file in this development that is somewhat teratologic and is very sensitive to accessing evar additional information. Not sure whether this is important though. In any case, if we accept this PR we should rather replace all the uses of `Store` by `Dyn` directly so as to ensure non-interference of generated uids and simpler API.

2018-10-08 08:49 UTC, whitequark commented
> In any case, if we accept this PR we should rather replace all the uses of `Store` by `Dyn` directly so as to ensure non-interference of generated uids and simpler API.

What about my solution in https://github.com/coq/coq/pull/7881#issuecomment-399044965 ?

2018-10-08 09:10 UTC, ppedrot commented
I think that there used to be a consensus against serialization of closures in Coq. I don't know why, maybe @gares remembers.

2018-10-08 09:12 UTC, ppedrot commented
Also note that my comment is orthogonal to your proposal: we can separately unify Dyn and Store while implementing Dyn in a type-safe way.

2018-10-08 12:30 UTC, mattam82 commented
I thought ideally we’d remove Store and use Dyn maps directly as well.
What’s happening when marshaling the closures? Is that well-specified?
Le lun. 8 oct. 2018 à 11:12, Pierre-Marie Pédrot <notifications@github.com>
a écrit :

> Also note that my comment is orthogonal to your proposal: we can
> separately unify Dyn and Store while implementing Dyn in a type-safe way.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/coq/coq/pull/7881#issuecomment-427767219>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAGARfu8olaFlR-us1JL3nWBwPZTtS0_ks5uixbngaJpZM4UxV_r>
> .
>

2018-10-08 12:35 UTC, ppedrot commented
BTW, I'd bet that #8671 would make the slowdown on VST disappear.

2018-10-08 15:44 UTC, whitequark commented
> What’s happening when marshaling the closures? Is that well-specified?

Yes, it's well-specified. An md5 sum of the code fragment to which the closure belongs, plus the closure offset from the code fragment, is included in the marshalled data, and I use these as a kind of unique identifier that changes across recompilations, which is how `Dyn` is made safe.

2018-11-17 15:10 UTC, ppedrot approved these changes
On second thought, this PR is already an improvement in itself, as it removes dangerous code by reusing Dyn. Since the removal of the per-evar store, this is likely not to cause any performance issue. I'll run a bench and if it shows not slowdown I'll merge the PR.

2018-11-17 15:46 UTC, ejgallego commented
It should be possible to remove `Store` at all from Coq; which wouldn't be a bad step.

2018-11-18 12:40 UTC, ppedrot commented
The bench looks pretty good:
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬─────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │       mem faults        │
│                        │                         │                                             │                                             │                               │                         │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW     OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│           coq-compcert │  882.18  892.90 -1.20 % │     2445842210177     2472645764423 -1.08 % │     3558374269137     3560239213365 -0.05 % │    1330284    1330584 -0.02 % │     210     407 -48.40 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│    coq-formal-topology │   60.07   60.51 -0.73 % │      164711413969      165221730054 -0.31 % │      250672051166      250989606589 -0.13 % │     480128     480084 +0.01 % │       0       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│             coq-geocoq │ 2009.76 2024.04 -0.71 % │     5579593187487     5622220868057 -0.76 % │     8119547374738     8125872533598 -0.08 % │    1294096    1217388 +6.30 % │     579     190 +204.74 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│              coq-flocq │  592.02  596.14 -0.69 % │     1644976885422     1659656951182 -0.88 % │     2416090293910     2416223393372 -0.01 % │    1774552    1774992 -0.02 % │     570     516 +10.47 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│  coq-mathcomp-solvable │  216.92  218.42 -0.69 % │      603033411888      605500931482 -0.41 % │      855033374730      855033339621 +0.00 % │     868060     865328 +0.32 % │     306       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│   coq-mathcomp-algebra │  185.36  186.28 -0.49 % │      515167900138      516969760473 -0.35 % │      702296664306      702851527357 -0.08 % │     643580     643800 -0.03 % │       5     284 -98.24 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│ coq-mathcomp-odd-order │ 1396.29 1402.87 -0.47 % │     3886994128361     3907181516494 -0.52 % │     6484448474269     6487600954232 -0.05 % │    1370348    1369084 +0.09 % │       1       1 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│          coq-fiat-core │  137.32  137.96 -0.46 % │      380963977752      381937788852 -0.25 % │      511352285561      511965792096 -0.12 % │     501072     501056 +0.00 % │     563     180 +212.78 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│       coq-fiat-parsers │  716.66  719.89 -0.45 % │     1987215666693     1996087998034 -0.44 % │     3038208837961     3039600867193 -0.05 % │    2869840    2910516 -1.40 % │     444     683 -34.99 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│             coq-sf-vfa │   49.05   49.26 -0.43 % │      136079281191      136461783533 -0.28 % │      219245869021      219635521724 -0.18 % │     537464     537268 +0.04 % │      30       6 +400.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│       coq-math-classes │  252.42  253.47 -0.41 % │      694877147634      697579812448 -0.39 % │      910721706705      911481425388 -0.08 % │     525912     525588 +0.06 % │      86      84 +2.38 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│         coq-coquelicot │  105.69  106.12 -0.41 % │      292396127624      293560836573 -0.40 % │      395921797416      396389114469 -0.12 % │     711872     712108 -0.03 % │     281      13 +2061.54 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│     coq-mathcomp-field │  260.92  261.98 -0.40 % │      725205138639      728403892194 -0.44 % │     1098229724920     1099048387730 -0.07 % │     757896     757608 +0.04 % │      13       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│            coq-unimath │ 1337.16 1342.38 -0.39 % │     3714024436348     3727213803551 -0.35 % │     6228919645424     6230731227231 -0.03 % │    1084092    1094848 -0.98 % │     362      19 +1805.26 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│  coq-mathcomp-fingroup │   84.42   84.74 -0.38 % │      233349418353      234333696418 -0.42 % │      346684225504      346940778633 -0.07 % │     586852     587456 -0.10 % │       8      12 -33.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│                coq-vst │ 2992.68 3002.83 -0.34 % │     8324149694537     8353648439036 -0.35 % │    11453795581508    11467756650370 -0.12 % │    2221324    2223048 -0.08 % │     479     846 -43.38 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│ coq-mathcomp-character │  280.99  281.92 -0.33 % │      780918443332      784481797306 -0.45 % │     1122742201872     1123302707576 -0.05 % │    1094904    1093556 +0.12 % │       6       7 -14.29 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│        coq-lambda-rust │ 2328 [...]

2018-11-19 08:24 UTC, merged