Generic syntax for attributes
coq/coq pull request #7920
Opened 2018-06-25 14:48 UTC by vbgl

Any vernacular command can be decorated with “attributes”.

An attribute has a name (an identifier) and may have a value. This value is either an unparsed string or a list of attributes.

The concrete syntax is inspired by [Rust’s attribute system](https://doc.rust-lang.org/reference/attributes.html).

Current limitation: only known attributes are accepted.

This PR also introduces a new flag/attribute for deprecation, as required by #7907.

TODO:
- [ ] Added / updated test-suite
- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in CHANGES.

2018-06-25 15:12 UTC, ejgallego approved these changes
The parts I care about [all but parsing] look OK to me.

2018-06-25 15:19 UTC, gares commented on vernac/vernacexpr.ml
> +type vernac_flags = (Names.Id.t * vernac_flag_value) list
Why `Id.t` ? It seem your code fights this choice all along.

2018-06-25 15:20 UTC, gares commented on vernac/g_vernac.ml4
> +  decorated_vernac:
indentation here is funny, and not consistent with the rest of the file

2018-06-25 15:22 UTC, gares commented on vernac/g_vernac.ml4
> +  [[ "#[" ; a = attribute_list ; "]" -> a
In camlp5 slang this means that `#[` is now a keyword.
I think CI will tell if `"#" "["` is preferable, I've no clue if people have notations using `#` and `[` separately and use both in the same expression.

2018-06-25 15:24 UTC, gares requested changes
`Id.t` -> `string` seems to improve the code.

2018-06-25 15:31 UTC, Zimmi48 commented
> Id.t -> string seems to improve the code.

If your suggestion means that the syntax will require quotes `" "` between braces `[ ]`, I'd rather keep things as they currently are.

2018-06-25 16:00 UTC, gares commented
I m talking about the ML data type, no change to the syntax

2018-06-25 16:06 UTC, gares commented
The ml data type for the name of the attributes, like "polymorphic"

2018-06-25 20:15 UTC, gares approved these changes

2018-06-26 08:33 UTC, Zimmi48 commented
Well, for starters the grammar of commands should be extended for sure, i.e. this https://coq.inria.fr/refman/language/gallina-specification-language.html#the-vernacular.
It's already pretty incomplete and inconsistent but this is no excuse to make it more incomplete.
Ideally, we would go further and introduce a new type of declaration for attributes, as there is for commands or tactics but I guess that this is too much to ask for the current PR, so just documenting commands with their possible attributes will be enough.
BTW we can't keep two concurrent syntax for two long. At some point, we should deprecate `Polymorphic` `Monomorphic` `Local` `Global`, etc.

2018-06-27 17:39 UTC, vbgl commented
Regarding tokens, I’ve tried both `"#["` and `"#" ; "["`. Both break the following example:

```
Notation "'#' '[' hello ']'" := (hello).

Check #[ nat ].
```

Any hint whether it’s a big deal, which version, if any, is preferable?

2018-06-27 17:42 UTC, ppedrot commented
As far as I am concerned, I prefer `#[` as a single token because it defers the decision to the lexer and furthermore it prevents spaces in between. So it's less likely to introduce incompatibilities.

2018-07-02 09:30 UTC, maximedenes commented
@vbgl can you let me know if you have time to work on documentation or not? Either way is fine, I simply need to adjust my own schedule. Thank you!

2018-07-02 15:17 UTC, Zimmi48 reviewed
In this chapter, there is somewhere a list of reserved tokens. You should add `#[` to this list.

2018-07-02 15:17 UTC, Zimmi48 commented on doc/sphinx/language/gallina-specification-language.rst
> +Sentences may be *decorated* with so-called *attributes*,
You could use ```:token:`attributes` ``` here if you want that would add a direct link to their definition in the grammar.

2018-07-02 15:17 UTC, Zimmi48 commented on doc/sphinx/language/gallina-specification-language.rst
> +        Defined.
What about some example were `program` is doing something, like:
```
From Coq Require Program.

#[program] Definition one : nat := _.
Obligation 1.
  exact (S 0).
Defined.
```

2018-07-02 15:17 UTC, Zimmi48 commented on doc/sphinx/language/gallina-specification-language.rst
> +        Ltac foo := idtac.
What about showing the warning print in an example below?

2018-07-02 15:22 UTC, maximedenes commented
> reserved tokens

@Zimmi48 what is a "reserved token"?

2018-07-02 15:52 UTC, Zimmi48 commented
I meant special tokens (see https://coq.inria.fr/refman/language/gallina-specification-language.html#lexical-conventions). But I am such a noob in parsing that I might be misinterpreting what this means and whether `#[` should be listed there.

2018-07-03 16:14 UTC, Zimmi48 commented
@vbgl You should rebase to have CI correctly go through.

2018-07-03 16:15 UTC, ejgallego commented
This also has conflicts.

2018-07-03 16:25 UTC, vbgl commented
Currently working on the rebase. That’s quite fun.

It seems that when `coqpp` fails (e.g., syntax error), this is treated as a warning and the build goes on (but fails much later, with an unrelated error message). Is that right?

2018-07-03 16:38 UTC, ppedrot commented
@vbgl I don't think so, it does die quickly for me.

2018-07-03 16:49 UTC, vbgl commented
Indeed, I can’t manage to reproduce the issue…

Rebased.

2018-07-04 01:44 UTC, ejgallego commented
I have no better suggestion, but the syntax does look uglyyy...

2018-07-04 07:49 UTC, Zimmi48 commented
> I have no better suggestion, but the syntax does look uglyyy...

It's less ugly than the initial proposal in coq/ceps#31 and that it's borrowed from Rust and not reinvented is a pretty strong argument (not saying that Rust is right but we should definitely not invent our own new syntax for this).

2018-07-04 10:41 UTC, herbelin commented
> but the syntax does look uglyyy...

Could someone (@vgbl?) give a list of the various proposals around, together with a list of the technical or maybe even aesthetical constraints?

2018-07-04 10:45 UTC, maximedenes commented
> Could someone (@vgbl?) give a list of the various proposals around, together with a list of the technical or maybe even aesthetical constraints?

Such discussions on syntax typically never converge, and this is a long awaited and very useful feature, so I suggest we don't block this PR. We can have the discussion on aesthetics in parallel, nothing will prevent to change the syntax (say before the release) if there's a consensus.

2018-07-04 10:47 UTC, gares commented
Who gets this PR? Should i?

2018-07-04 10:49 UTC, maximedenes commented
> Who gets this PR? Should i?

This is a vernac change, so in principle @mattam82 or me. But I'm very busy, so if you have a bit of time, @gares you are very welcome to assign yourself.

2018-07-04 11:40 UTC, ejgallego commented
> Could someone (@vbgl?) give a list of the various proposals around, together with a list of the technical or maybe even aesthetical constraints?

Indeed aesthetics are not to be treated as an afterthought IMHO, it would be good to have some discussion about them either here or in a different bug.

2018-07-04 11:51 UTC, Zimmi48 commented
> Indeed aesthetics are not to be treated as an afterthought IMHO, it would be good to have some discussion about them either here or in a different bug.

Yes, in a separate issue please. Let's not delay further this PR that we have waited for so long.

2018-07-05 12:31 UTC, gares commented
I'll merge it next week

2018-07-05 22:03 UTC, herbelin commented
> this is a long awaited and very useful feature, so I suggest we don't block this PR.

It is not my intent to block the PR (nor other long awaited features...)!

> Such discussions on syntax typically never converge

I see no reason to assert this a priori. First, there are objective facts in syntax (like parsing constraints), and, second, when we try to analyse the reasons why we like or not a syntax, one often discovers that there are objective reasons behind, e.g. because of similarities with programming languages we like, because it echoes to some aesthetics we may have built in our education, etc., etc. When we develop the V8 syntax, we made several round trips and we did not have problems to converge to what we can consider to be at the end a consistent and scalable syntax of terms.

> We can have the discussion on aesthetics in parallel, nothing will prevent to change the syntax (say before the release) if there's a consensus.

Let's be optimistic in our capabilities to find a consensus on the factual advantages of this or that syntax. Of course, saying that "it is ugly" without giving reasons is not going to help, but I believe that the participants to the discussion shall eventually make argumented enough proposals so that it converges.

Anyway, I can collect proposals myself, together with the pros and cons of each proposal, if noone is otherwise interested to do it.

To start with, I have the following questions:
- do we accept only known attributes or not? @vgbl seems to intend in his first comment above that it expects that non-registered attributes are allowed but that this is not what he implemented.  What would be the advantages of non-registered attributes? Would that be useful for plugins?
- what to do with the syntaxes already existing for attributes?

2018-07-06 04:54 UTC, Zimmi48 commented
> Would that be useful for plugins?

I think this is the idea indeed. But another solution could be to use an extensible type so that only attributes defined in Coq or in a loaded plugin can be used.

> what to do with the syntaxes already existing for attributes?

I am of the opinion that they should be deprecated and eventually removed. I think the learning of the Coq language will be (a little bit) easier with uniform attribute syntax. We are not obliged to hurry in deprecating them though.

> Let's be optimistic in our capabilities to find a consensus on the factual advantages of this or that syntax. 

I think you are right that such discussion could converge in the time we got before the release if it is will coordinated, like you propose to do. I was just making sure that the PR doesn't wait for the syntax discussion to converge before getting merged to avoid the awful cycle of endless rebasing, and also so that we can start taking advantage of attributes in other PRs ASAP.

2018-07-06 20:19 UTC, herbelin commented
This PR is long awaited for sure and it is great that it is here. But I just looked at how the `attribute-syntax.v` test file looks, and, please don't take it bad, it gave me an impression of dissonance.

The contrast between the capitalized sentence and the lowercase letters in the `#[...]` is strange. It is strange when on the same line, but actually also when on the previous line. For instance, as much I find `Program Definition` clear (a definition for the "Program" feature, or a definition for the construction of a "program"), as much I find
```coq
#[program]
Fixpoint f (n: nat) {wf lt n} : nat := _.
```
pretty bizarre. What means `program` here? The perception that `Program` is a qualifier is lost and I can't feel for the benefit of what it is lost. If the point is to avoid the current way to give attributes, namely as a list of adjectives coming before the main keyword, I believe that it should at least be motivated by somehow giving a refreshing look at the now old syntax of Coq, but this is not what I feel when seeing the examples.

The current syntax has constraints: it requires the list of attributes to be known at the time of parsing. But I understand from @Zimmi48 that this would not be necessary, even for plugins. After all, we already need to load plugins prior to parsing so as to know the notations defined in the module. So, the problem does not seem different for attributes.

Incidentally, there was an idea at some time in coq/ceps#31 to support sub-attributes. Is it still something in the air, or no significant application has been found?

Well, I would have liked to see a proposal providing with a refreshing look at the syntax, but my personal attempts to elaborate on variants of `#[`, e.g. without `#`, or with uppercase, did not convince me at the current time that it would be more appealing than the current syntax.

How to proceed? Am I the only one with @ejgallego to have this kind of feeling on the proposed syntax, or is it shared? Do we try to collect other proposals or, as suggest @maximedenes and @zimmi48, we try to converge quickly, and, I would dare to say that keeping the existing syntax seems then to me the shortest path.

2018-07-06 21:10 UTC, Zimmi48 commented
The main advantages of attributes that I can see are:
- it's a generic mechanism (less hacks in the parser);
- you can provide them in whatever order you want.

The first point is a win for the developers (and when you see Pierre-Marie's complaints in other PRs it seems that it is a huge win).
The second point is a huge win for users.

> Incidentally, there was an idea at some time in coq/ceps#31 to support sub-attributes. Is it still something in the air, or no significant application has been found?

This is supported by the current PR, see the `deprecated` attribute.

> Do we try to collect other proposals or, as suggest @maximedenes and @Zimmi48, we try to converge quickly, and, I would dare to say that keeping the existing syntax seems then to me the shortest path.

I did not suggest that we converge quickly on the syntax discussion, I suggested that we merge the PR *as it currently is* without waiting for the syntax discussion to converge, and that we put you in charge of making sure that the syntax discussion happens before the next release. And this is to satisfy your will to discuss the syntax because I'm personally completely fine with the current proposal (as I said above I was less fine with the initial syntax proposal in the CEP).

There are two ways of interpreting your proposal of "keeping the existing syntax": keep it as it is in the PR, or keep it as it is in master. I'm afraid that your proposal is the second one and in that case, I'm afraid that it defeats the purpose of attributes (I'm not a crack at parsing but IIUC there is no way to achieve the same properties while keeping the current non-parenthesized syntax, @ppedrot @aspiwack and @vbgl can probably confirm).

In any case, you were saying above that we could find objective ways of discussing the syntax but your concern about an inconsistency between capitalized and non-capitalized seems a bit weak to me.
And I know you hate when we take paths just because they are "modern" but notice how the world of programming has changed toward less capitalized words, from the early ALL CAPS BASIC, to a current situation where capital letters are used sparingly in most programming languages (for module names for instance). Coq has had a similar evolution with the change in the syntax of tactics. Now, we are taking one step further, passing from `Local Cumulative Polymorphic Definition` to `#[local, cumulative, polymorphic] Definition`. And since you like comparisons to natural languages, you can notice that it makes it clearer which is the "adjective" (the attribute) and which is the "noun" `Definition` or the "verb" if we apply attributes to a tactic.

2018-07-06 21:32 UTC, maximedenes commented
I would  be ok to resolve the "discrepancy" by removing the capitals for commands (which I think bring nothing). But it does not seem required to me.

This PR is an obvious improvement on the current status quo, which requires to know in which order to write stuff. How is a user supposed to guess how they can make a polymorphic local program definition ?

2018-07-07 06:16 UTC, Zimmi48 commented
I would also be in favor of a general reworking of the syntax, but this can probably wait 8.9 while attribute can't wait that long.

2018-07-07 09:49 UTC, herbelin commented
@zimmi48: OK, I'm taking note that you don't feel a dissonance with the proposed syntax. More generally, making things objective is also about synchronizing the subjectivity of everyone, so can we try to collect more perceptions about it?

> you can provide them in whatever order you want.

When I'm talking about the current syntax, it is of course with a support of attributes in any order (i.e. not like now), which we know how to do.

To be honest, I just discovered yesterday evening the `deprecated` attribute. Where can I find more information about examples using it?

Otherwise, another idea which might be worth to be considered is to use comments, like in OCaml, e.g. `(** deprecated since 8.3 *)`. This could also be a way to distinguish between the attributes that have a semantic effect (like `Global`, `Polymorphic`) and those that have a purely informative role.

Sorry if I expressed a strong opinion. I did not imagine that you would have liked the proposed syntax more than the current one. In particular, I thought that the only reason for a different syntax was that it was believed that the 3 points mentioned at the top of coq/ceps#31 had not solutions, i.e. a case of XY problem. (The latter point should also answer @maximedenes' last message.)

2018-07-07 11:45 UTC, ejgallego commented
I think @herbelin has made an excellent summary of what I feel about syntax; I do indeed have the same "dissonance" problem, and whereas `Program Definition` reads naturally, I have problems connecting the attributes in the new syntax.

In fact it is a good example we mention OCaml, IMHO their attributes syntax is superior; first, it allows arbitrary payload; second, it can attach to different levels `[@` vs `[@@`, etc..., and lastly it **attachs**, so, while not perfectly, I tend to get a better sense of the scope the attribute is acting on, something that seems harder in the current proposal.

2018-07-07 15:02 UTC, gares commented
> Program Definition reads naturally

Please read it for me, cause I really don't know how to read it.

The operational meaning is "Like Definition but with the program flag set to true" that is what `#[program=true]` reads (and `=true` is implicit). This is pretty much in line what the concrete syntax of attributes convoys.

2018-07-07 15:07 UTC, ppedrot commented
> and lastly it attachs, so, while not perfectly, I tend to get a better sense of the scope the attribute is acting on

Let me mention that I feel exactly the opposite with OCaml syntax. I always have a hard time telling apart the difference between `@@` and `@@@` and thus the scope over which an attribute is acting, up to the point I need to compile the file to check which is what.

2018-07-07 15:13 UTC, gares commented
> those that have a purely informative role.

deprecation is semantic: you want it to generate a warning (at the use site) and if you pass "-warn error" then you want compilation to fail.

2018-07-07 15:29 UTC, maximedenes commented
Guys, could we put some order on the discussion? I have no strong opinion about the syntax, but I have a lot of work waiting for this in order to be made ready and integrated : #7907 #7878 #7897 #186. So can @herbelin and @ejgallego say if yes or no, they are ok with this being merged as it is and the syntax discussion to be happening in parallel? If not, I'll delay my work on all these PRs and schedule something else.

Thanks!

2018-07-07 15:53 UTC, maximedenes approved these changes

2018-07-07 17:38 UTC, Zimmi48 commented
> To be honest, I just discovered yesterday evening the deprecated attribute. Where can I find more information about examples using it?

The documentation that is included in this PR contains an example already but it might be a bit light to show how it interacts with Ltac definitions.

2018-07-07 21:46 UTC, herbelin commented
@maximedenes: I guess that it depends also on the plans of @vbgl.

@vbgl, what are your plans with this PR? You seemed to indicate that you chose Rust syntax by imitation? Does it mean that you don't have a particular opinion on the syntax and that a syntax which is compatible with the existing syntax of attributes would be ok for you?

If the answer is that the question of which exact syntax is chosen does not matter for you, or if a syntax which is compatible with the existing and which avoids a deprecation phase seems better to you, then, I could implement such as syntax by a few days. It could for instance be:

```
venac_control ::= IDENT "Deprecated"; IDENT "since"; version; string; "["; vernac_control; "]"
vernac_control ::= LIST0 attribute; vernac
attribute ::= IDENT "Polymorphic" | IDENT "Local" | ...
```

But I feel that this makes sense only if I have a support of the rest of the team, otherwise, I guess that we are back to having to first find a consensus (which I'm still ready to coordinate if noone else volunteers).

@gares:
> deprecation is semantic: you want it to generate a warning (at the use site) and if you pass "-warn error" then you want compilation to fail.

Well, good point.

@zimmi48:
> The documentation that is included in this PR contains an example already but it might be a bit light to show how it interacts with Ltac definitions.

OK

In any case, I'm ok to apply any (reasonable) rule regarding merging or delaying PRs. However, we have to apply these rules in a consistent way and if we consider that it is worth to merge this PR even knowing that the syntax shall change, then, the same policy shall apply to PRs about which we know that further changes are expected later.

2018-07-07 22:00 UTC, Zimmi48 commented
> In any case, I'm ok to apply any (reasonable) rule regarding merging or delaying PRs. However, we have to apply these rules in a consistent way and if we consider that it is worth to merge this PR even knowing that the syntax shall change, then, the same policy shall apply to PRs about which we know that further changes are expected later.

:+1: consistency in our merging process is definitely something that we can improve. Of course, when we decide that a PR is important enough to be merged without some expected later improvements, it must be a reasonable judgement of the pros and the cons (importance of the feature, size of the expected fixes, importance of the problems...).

As for this particular PR, even if I personally prefer the syntax proposal by @vbgl, I am completely OK following the suggestion by @herbelin if it helps get a consensus and this PR merged quicker. Furthermore, if consistency of the general style is to be preferred but at the same time we long for having less capital letters, that could be addressed in a general revision of the syntax for 9.0.

My only concern with this proposal is that it does not provide a generic mechanism for "sub-attributes" (the Deprecated attribute is hard-coded) but that's only a minor concern given that we don't know yet what would be the other applications.

I'm especially interested in learning @ppedrot's opinion about this alternative syntax proposal.

2018-07-08 00:12 UTC, ppedrot commented
> I'm especially interested in learning @ppedrot's opinion about this alternative syntax proposal.

This looks to me like a reenactment of the horrible situation we are in currently. We need a grammar for attributes that is generic enough to handle both arbitrary structured payload inside attributes and commands. @herbelin's proposal doesn't fit the bill because
1. there is no static way to separate the vernac command from the attributes, so that it is not stable by vernac extension
2. similarly syntax hardcodes structure for the deprecated attribute only.

This seems like a recipee for disaster to me. I don't particularly care about the precise syntax for attributes like the use of `#[` tokens and the like, but it definely needs to provide the two features mentioned above, which requires at the same time some form of well-bracketing and generic recursive structure.

2018-07-08 08:09 UTC, maximedenes commented
> @maximedenes: I guess that it depends also on the plans of @vbgl.

@herbelin Vincent is on holidays until September 1st. So is your answer a yes (we can merge as it is and discuss syntax separately) or a no?

2018-07-08 10:33 UTC, Zimmi48 commented
@herbelin Would a possible middle ground be to just put capital letters in the attribute names again and no commas? E.g.

```
#[ Local Deprecated("8.8", "use foo instead") Polymorphic Instance ] Definition
```

2018-07-08 10:54 UTC, maximedenes commented
> Would a possible middle ground be to just put capital letters in the attribute names again and no commas? E.g.

Could we pause the discussion and first answer my question about whether we should have the discussion now? I'd like to schedule my work... Thank you!

2018-07-08 10:59 UTC, vbgl commented
What I care about is the abstract syntax (rose trees).

Regarding the concrete syntax, whether attributes are separated by semi-colons or ZWNJ (U+200C), whether identifiers are capitalized or compared using a home-brew collation, etc, what I believe is that there is always someone who will find it ugly and that practice will tell if it is convenient to write and pleasant to read.

2018-07-08 12:33 UTC, Zimmi48 commented
> practice will tell if it is convenient to write and pleasant to read

One more reason to merge ASAP.

2018-07-08 12:53 UTC, ppedrot commented
I personally consider this PR top priority. We have been waiting for too long the attribute system to implement user-facing features that would benefit to everyone. If this misses the 8.9 release, we will just look like idiots.

2018-07-08 17:01 UTC, ejgallego commented
What about having a postfix attribute syntax? I personally don't find convincing any of the two current proposals [for the reasons stated]

2018-07-08 21:22 UTC, maximedenes commented
> Could we pause the discussion and first answer my question about whether we should have the discussion now? I'd like to schedule my work... Thank you!

@ejgallego and @herbelin independently told me offline that they would be ok with merging this and having the syntax discussion in parallel.

If I misunderstood, please let me know. Otherwise, Enrico or I will merge early next week. Rebasing on a new syntax if a consensual alternative is found will be easy.

2018-07-08 21:38 UTC, ejgallego commented
I am OK with merging indeed but I am not sure you are gonna have "so many advantages" in the current status of this PR; it seems to me that quite a lot of design choices are missing or incomplete.

2018-07-09 08:28 UTC, herbelin commented
@ppedrot: My main concerns are:
- why to bother users with a change of syntax? how do you convince them that it is necessary?
- are we sure that, among all our users, computer scientists and mathematicians, beginners and experts, a `#[`-based syntax is the most appealing syntax we can imagine for the proposed feature?
- (a secondary concern is that I wonder whether it is worth to consider a "deprecation" annotation at the same level as say a "Polymorphic" modifier; but even if not considered of same nature, they could share the same syntax and this is why I'm saying that this is a secondary concern)

@maximedenes: I believe you can simply proceed with your work using @vbgl's syntax (or whatever syntax you'd like to see) [excerpt from a live discussion after the Coq workshop].

To @vbgl:
> what I believe is that there is always someone who will find it ugly

I precisely hope no. (Or at least not "ugly" without further details, and without also admitting the value of the reasons why others may not find it ugly.)

> and that practice will tell if it is convenient to write and pleasant to read.

In passing, while you are it, what about providing a `only 8.x` (or `8.x-only`, or whatever) attribute? That could be a way to ease writing code compatible over several versions.

2018-07-09 11:28 UTC, vbgl commented
>   * why to bother users with a change of syntax? how do you convince
>     them that it is necessary?

There is no change of syntax yet. There is a new syntax for a new feature.

In the future, if we think the new syntax is a good replacement of (and
not only complement to) the old syntax, then we can deprecate and then
remove the old syntax.

>   * are we sure that, among all our users, computer scientists and
>     mathematicians, beginners and experts, a |#[|-based syntax is the
>     most appealing syntax we can imagine for the proposed feature?

We need parentheses and separators. Should we use ⟨ | ⟩ to appeal to
linear algebraists?

> In passing, while you are it, what about providing a |only 8.x| (or
> |8.x-only|, or whatever) attribute? That could be a way to ease writing
> code compatible over several versions.

I guess you should open a dedicated issue on this topic.

2018-07-09 15:36 UTC, herbelin commented
> We need parentheses and separators.

Well, this seems to be one of the questions which makes the current discussion a miscommunication. I thought that parentheses were not needed but I guess it is also about what we want to do with attributes.

In particular, maybe am I missing some cases, but I thought that the only limitation with the current attribute syntax with no parentheses is that users cannot define a tactic named `Program` or `Polymorphic`? Even in a future with more attributes available (`No-Induction-Scheme`, `With-Case-Scheme`, ...?) do we want to let the possibility for users to name tactics after such a name? Even in a future with attribute names possibly colliding with existing commands (say `Hint`, `Coercion`, `Opaque`, ...), which would start to pose some problems, do we really want not to give a priority to compatibility over finding another solution?

> @ejgallego and @herbelin independently told me offline that they would be ok with merging this and having the syntax discussion in parallel.

Yes. And in the same offline discussion, I proposed that we be more consistent in the rules governing delaying and merging PRs. How to do with PRs about which we know that more discussion is needed. Do we revert them at the time of the release if the discussion did not converge on time? Do we postpone the release? 

The past showed that we need decisions be taken peacefully, not by giving the feeling that a discussion has been bypassed (remember the `pat/constr` discussion). Again, let's be optimistic, why wouldn't we be successful in explaining our motivations in a convincing way?

My initial question [above](https://github.com/coq/coq/pull/7920#issuecomment-402440916) was just basic ("could someone give a list of the various proposals around"). Why did the discussion degenerate? Why can't the question be answered in a simple way? Am I asking too much? Arguments can be given to justify a `#[` syntax, so let's just advertise them, let's prepare our arguments in front of who would blame us for changing things without caring enough about compatibility, or for multiplying different syntaxes and different syntax styles for essentially the same feature.

> Should we use ⟨ | ⟩ to appeal to linear algebraists?

A typical general-user question I can imagine, in the option with parentheses, is: what does the `#` bring?

2018-07-09 15:46 UTC, Zimmi48 commented
I don't think the discussion degenerated. The main point is the question of the need for parentheses (see in particular, @ppedrot's comment https://github.com/coq/coq/pull/7920#issuecomment-403251457 to which you didn't react).

> what does the # bring?

The main point in favor of this symbol was just the reuse of an existing syntax in another programming language. If you absolutely want to reinvent a different syntax, fine.

2018-07-09 15:50 UTC, ejgallego commented
Nobody seems to care about prefix/postfix? Does that mean that people do prefer prefixed attrs?

2018-07-09 16:06 UTC, Zimmi48 commented
> Nobody seems to care about prefix/postfix? Does that mean that people do prefer prefixed attrs?

Not necessarily but it seemed that the alternatives weren't really practicable in the context of Coq. If you think that's doable, I would be interested to learn more.

2018-07-09 16:07 UTC, herbelin commented
> Nobody seems to care about prefix/postfix? Does that mean that people do prefer prefixed attrs?

To have a postfix syntax, I don't see how we could avoid to hard-wire the parsing of attributes in each given different rule of the grammar. This is certainly feasible but a bit more constraining, compared to a situation where the parsing of attributes can be factorized once for all.

2018-07-09 16:11 UTC, ejgallego commented
Couldn't it be done in a generic way using lookahead? The rule would be for example:
```
vernac ::= prim_vernac @@[attrs]
```
but indeed it should maybe be done using the camlp5 extension function as to avoid factorization issues.

2018-07-09 16:20 UTC, herbelin commented
> I don't think the discussion degenerated. The main point is the question of the need for parentheses (see in particular, @ppedrot's comment #7920 (comment) to which you didn't react).

My comment [above](https://github.com/coq/coq/pull/7920#issuecomment-403521854) is reacting to the comment from @ppedrot that you are pointing: I'm basically asking there about what "the bill" is, and about what "vernac extension" means.

> The main point in favor of this symbol was just the reuse of an existing syntax in another programming language. If you absolutely want to reinvent a different syntax, fine.

I don't want to reinvent a different syntax. I mean, when I was learning new languages, I remember that I had spontaneously more sympathy for syntaxes which do not look too esoteric or hackish.

On the other side, maybe, Rust is enough popular these days so that we can expect newcomers in Coq to feel at ease at once without having to care to use a more "universal" kind of language.

2018-07-09 16:32 UTC, maximedenes commented
> Nobody seems to care about prefix/postfix? Does that mean that people do prefer prefixed attrs?

I prefer prefix. Especially if parsing is simpler.

2018-07-09 16:33 UTC, maximedenes commented
I'm going to merge this and open an issue to collect alternative proposals.

2018-07-09 16:46 UTC, mattam82 commented
Same here, I prefer prefix. We need a generic syntax indeed and no specific grammar rules (e.g. so that Equations can use this to implement its own options). I believe we could settle on introducing the new syntax (or something more consensual than #[ if that's possible), let the users play with it and ask for feedback if we can deprecate `Program Polymorphic Definition foo` in favor of `#[program,polymorphic] Definition foo` in the following version for a smooth transition path. In principle we could keep the special cases for Polymorphism/Program/Local flags indefinitely in the parser while making the rest of the implementation use the generic attribute structure, right?

2018-07-09 17:05 UTC, maximedenes commented
> Same here, I prefer prefix. We need a generic syntax indeed and no specific grammar rules (e.g. so that Equations can use this to implement its own options). I believe we could settle on introducing the new syntax (or something more consensual than #[ if that's possible), let the users play with it and ask for feedback if we can deprecate Program Polymorphic Definition foo in favor of #[program,polymorphic] Definition foo in the following version for a smooth transition path. In principle we could keep the special cases for Polymorphism/Program/Local flags indefinitely in the parser while making the rest of the implementation use the generic attribute structure, right?

Yes, deprecating the existing syntax is not urgent, and should be discussed separately. What is urgent is to make it possible for new syntax extensions (like #7907 for now, and in a second step also for plugins) to not contribute to the combinatorial explosion of parsing rules.

2018-07-09 17:44 UTC, herbelin commented
> I'm going to merge this and open an issue to collect alternative proposals.

Am I the only one to read here an ability to derive a proof of false when combined with other policies defended in similar occasions?

2018-07-09 18:05 UTC, Zimmi48 commented
> Am I the only one to read here an ability to derive a proof of false when combined with other policies defended in similar occasions?

I don't know what you mean but it's still time to formally oppose using the red button. One thing that is sometimes annoying is that you are not making it clear enough what you want and then we go against your opinion without realizing.

2018-07-09 18:43 UTC, ejgallego commented
Indeed I know what @herbelin means; Hugo, indeed Théo has a point that you seem to have given explicit approval of this PR; I have given so too, but the more time we spend discussing the more convinced I become that maybe we should indeed block this PR and do at least a more complete list of use cases including warnings, guards, etc...

It is of little use to have an inmature proposal in.

2018-07-09 18:46 UTC, maximedenes commented
> Indeed I know what @herbelin means; Hugo, indeed Théo has a point that you seem to have given explicit approval of this PR; I have given so too, but the more time we spend discussing the more convinced I become that maybe we should indeed block this PR and do at least a more complete list of use cases including warnings, guards, etc...

Pffffffffff. You're making it impossible for other people to schedule their work. Do you block this PR or not? Yes or no? Same question for @herbelin. I will merge tonight 10PM if  no answer by then, note that the deadline was this week and not only you did not block, but you even said it could go in.

2018-07-09 18:50 UTC, maximedenes commented
> tonight 10PM

(Paris time)

2018-07-09 18:57 UTC, maximedenes commented
In case I haven't repeated myself enough, I'm not trying to make this PR go through against opinions of other developers. I'm trying to know if this PR is being blocked or not, and so far I didn't hear any clear opposition. It is still time to do it, but do it now.

2018-07-09 18:58 UTC, ejgallego commented
> You're making it impossible for other people to schedule their work. Do you block this PR or not?

Welcome to an open and collaborative model of development. In fact, welcome to software development in general. People make proposals, flaws are discovered, schedules get affected. News at 11.

I am still OK with this going in, as I trust the developers in charge to aim for technical excellence and I see this just a step in a large path.

However attitudes like the one in the message are making me _very_ worried, first, becuase I don't see a satisfactory answer to several technical questions [like how is this proposal supposed to work with warnings, 3rd time I ask], and second because it seems technical excellence may have taken a role too lessened to my taste.

In that sense @herbelin is right, we are not applying the same measuring rule to all PRs; personally I am fine with it as I don't believe it is possible to achieve and decision making should be heterogeneous. However, my initial satisfaction wrt this PR has vaned away as I've been a witness of the way the comments have been addressed.

2018-07-09 19:02 UTC, maximedenes commented
> attitudes like the one in the message

which message?

> how is this proposal supposed to work with warnings

Rust has: `#[allow(warning_name)]` to disable a warning. That's one option.

2018-07-09 19:03 UTC, ejgallego commented
> It is still time to do it, but do it now.

Well, this seems to me to be close to `needs: discussion`. Maybe if we would spend the time actually discussing the technical points instead of handwaving about "schedules" we would have already make progress.

I think both @herbelin and me understand the strategic importance of this PR and we are not willing to block this PR in any way, as we have stated. However, given the reaction to our mostly technical comments is to avoid actual discussion but instead you chose to focus on the "merging" part of the PR [which I couldn't care less], seems to erode our trust in that the discussion in the issue will be productive and we won't end with a suboptimal, unproven attribute system in the codebase.

Let's go back to actual discussion, I deem the content in the CEP insufficient, and certainly the commit message is fairly scarce. I'd like to understand better [here or in a further document] what concrete uses cases is this system meant to address. What about payloads? etc...

2018-07-09 19:10 UTC, maximedenes commented
> mostly technical comments

You mean like "I have no better suggestion, but the syntax does look uglyyy..." ?

But ok, I feel your strange dance between not wanting to delay the PR but still wanting to discuss it means we should delay it until the questions are addressed and we find a syntax that pleases everybody. And @herbelin is probably feeling the same. So I won't merge it.

I don't know which "attitude" you were alluding to, but I don't see anything wrong in clarifying what discussion was required before we can merge this PR.

2018-07-09 19:15 UTC, ejgallego commented
> which message?

The message of "this will be merged tomorrow at 21:12:012ms" Between not blocking, and having a strict deadline on the discussion it seems to me that there exists quite a large gap. If we need to discuss for a couple of days more it is not the end of the world. You can also merge and move the discussion as we stated, but that message doesn't add anything to the actual PR discussion.

> Rust has: #[allow(warning_name)] to disable a warning. That's one option.

Interesting, and here we have IMHO [a minor] problem, indeed there is tension between the `Warnings` vernacular and the attribute, and IMO we should avoid a syntax conflict here. Rust seems a very odd choice to me, of course, it is a matter of taste, but I'd rather have gone the OCaml way.

A couple more of comments:
- what is the story with scope? What's the intended meaning of `#[allow(warning_name)] Module Foo.`
- related to that, what is the story for inheritance? Is the current syntax meant to be vernac-only. What will happen when we want expression level attributes? Will the current approach still workable?

2018-07-09 19:21 UTC, ejgallego commented
> I don't know which "attitude" you were alluding to,

I mean the complain "I can't schedule my work, pffff", that leads nowhere.

> we should delay it until the questions are addressed and we find a syntax that pleases everybody

As I said I think the tradeoff is in favor of merging, even if the whole attribute thing has to be declared experimental so don't put more meaning to my words than they have.

My concern is that questions are answered with "I merge / I do not merge", like above; I don't care. What I do care is to understand how the system is supposed to look and work, and so far I am struggling with that.

2018-07-09 19:23 UTC, ejgallego commented
And indeed note that my review for this PR still holds, but we certainly need to improve the dicussion and design process of this whole attribute thing if we want to ship something sensible.

2018-07-09 20:07 UTC, ejgallego commented
yeah I'm not sure were we lost the track, I think we made it clear that the PR can be merged now and no need to put a deadline or whatever.

Note that merging is perfectly compatible with being not yet satisfied with the status of the discussion about some of the design choices.

2018-07-09 20:08 UTC, ejgallego commented
I mean you are handwaving in the sense of "merge, merge, not merge, merge"; to me the merge issue was solved the moment I put the green mark, so I don't understand what's the point of replying to other questions with "merge, merge"

2018-07-09 20:15 UTC, maximedenes commented
> I think we made it clear that the PR can be merged now and no need to put a deadline or whatever

Ok thanks, sorry, I was a bit slow to understand that.

2018-07-09 20:17 UTC, merged

2018-07-09 20:18 UTC, maximedenes commented
Merged. For further discussion, I suggest we split the discussion on concrete syntax (for which I'll open a specific issue), and on remaining design questions (how to make it extensible, unify with the `Warnings` vernacular, etc) which could happen in the CEP.

2018-07-09 20:19 UTC, ejgallego commented
I am also fine waiting until September to discuss more on the design; I will collect my comments as a single entry in the issue.

> Am I the only one to read here an ability to derive a proof of false when combined with other policies defended in similar occasions?

I guess the logic here is kind of "fuzzy valued" so any merge function will be of type `PR -> [0,1]`; thus you only have the possibility of a proof of false :) But you have a point, we are not consistent and it is clear that we, as humans, are influenced by many social and historical factors as to be consistent.

2018-07-09 20:24 UTC, ejgallego commented
> I suggest we split the discussion on concrete syntax (for which I'll open a specific issue), and on remaining design questions (how to make it extensible, unify with the Warnings vernacular, etc) which could happen in the CEP.

I am not sure the split is a good idea; there certainly is some feedback between the syntax and semantics of any language as to maybe that style of discussion to be useful. IMVHO, the issue should clearly define all the expected use cases and then showcase how the syntax and intended semantics do look.

Once that is done, implementation strategy would be a non-trivial 3rd step.

p.s: `#[meta note]` I tend to find the CEP format horrible for discussion, and on top of that it is redudant as we will surely rediscuss when a PR is made. My preference is to discuss in a general attributes issue, then on the particular PRs, but yeah, if people want to update the CEP that will also work I guess, but the risk of surprises at PR time seems still high.

2018-07-09 20:44 UTC, maximedenes commented
> I am not sure the split is a good idea; there certainly is some feedback between the syntax and semantics of any language as to maybe that style of discussion to be useful. IMVHO, the issue should clearly define all the expected use cases and then showcase how the syntax and intended semantics do look.

Ok, I'll open a more general issue, then.

2018-07-10 06:55 UTC, Zimmi48 commented
Thanks @ejgallego for explaining @herbelin's words.

2018-07-10 09:52 UTC, herbelin commented
@Zimmi48: 
> I don't know what you mean but it's still time to formally oppose using the red button. One thing that is sometimes annoying is that you are not making it clear enough what you want and then we go against your opinion without realizing.

Were the following still-no-answered questions not clear enough?

"Yes. And in the same offline discussion, I proposed that we be more consistent in the rules governing delaying and merging PRs. How to do with PRs about which we know that more discussion is needed. Do we revert them at the time of the release if the discussion did not converge on time? Do we postpone the release? (*)

The past showed that we need decisions be taken peacefully, not by giving the feeling that a discussion has been bypassed (remember the `pat/constr` discussion)."

> Maybe you missed an earlier comment in this discussion, but @vbgl is on (well
deserved) holidays until September. 

I saw @vbgl Sunday in a professional context. I saw him again yesterday in a professional context. He posted yesterday. Can you explain the inconsistency?

Can you also explain in which sense @vbgl is needed for merging?

> Pffffffffff. You're making it impossible for other people to schedule their work.

Many of us have PRs depending on unmerged PRs. This is not an argument.

> Merged. For further discussion, I suggest we split the discussion on concrete syntax (for which I'll open a specific issue), and on remaining design questions (how to make it extensible, unify with the Warnings vernacular, etc) which could happen in the CEP.

I consider this accelerated merge as an attempt to force through without answering the pending questions (starting with (*)), as an emotional reaction without real urgency and justified by fallacious arguments (I can't work w/o this PR being merged, @vbgl is off). This is not the idea I have of a development team respectful of the need for discussion, and this shall not help to have a serene question on the syntax. I'm giving to @maximedenes a yellow card for non respecting the basic rules of a fair communication and I'm going to revert this force-through tonight at 10pm Paris time so that the discussion can restart normally. We all want the feature but we also need a vision, "kein bricolage" made on irrelevant or emotional arguments.

2018-07-10 11:01 UTC, Zimmi48 commented
@herbelin I'd like to talk to you in person ASAP. I think you have a serious communication problem that you need to solve and you can't reject the fault on other people who are not in your head.

2018-07-10 11:21 UTC, maximedenes commented
> Were the following still-no-answered questions not clear enough?

No, they were not. You told me live at Floc that you were ok with merging and continuing the discussion on those questions, and you failed to answer clearly each time I asked it on this PR...

If you revert the change, at least it will be clear, for once. So it will be progress.

> I'm giving to @maximedenes a yellow card

It is not your role to distribute cards to your colleagues. And if a referee was issuing cards, my guess is you'd have received a red long time ago.

> I saw @vbgl Sunday in a professional context. I saw him again yesterday in a professional context. He posted yesterday. Can you explain the inconsistency?

Vincent is attending Floc with Gilles, his current employer. Then he goes immediately on holidays. My point was that we should not expect him to be working on refining this design until September.

In case I didn't repeat it enough times, I did not necessarily want a merge of this PR now, I wanted to know if we could merge now and keep discussing the open questions, or not. I can easily adjust either way, to precisely avoid stacking up PRs during this summer.

The only time I thought I got a clear answer from you was at a dinner at Floc, and I thought it was a yes. I found your communication with me there fairly aggressive and unclear, so of course some confusion may have arisen, but certainly not intentionally on my part.

2018-07-10 19:05 UTC, herbelin commented
@Zimmi48:
> @herbelin I'd like to talk to you in person ASAP. I think you have a serious communication problem that you need to solve and you can't reject the fault on other people who are not in your head.

If I try to read between the lines, you feel that I'm not explicit enough about my thoughts? Is that correct? Anyway, we can talk tomorrow.

@maximedenes:
> No, they were not. You told me live at Floc that you were ok with merging and continuing the discussion on those questions, and you failed to answer clearly each time I asked it on this PR...

When we talked at the dinner, I told you that I was ok with the merging but I also told you that I was expecting that consistent merging rules are applied. I actually don't know if you even let me finish my sentence: you quickly turned to @gares and asked him if he was ok to merge the PR this week (or maybe next week, I don't remember). By the way, what justifies that you subitely wanted to merge yourself without even leaving a time for me to read my mail?

What I wanted to say at the dinner and that I felt you barely paid attention to, I repeated it in my comment above. I was expecting that consistent rules are applied, and I did not get an answer.

> It is not your role to distribute cards to your colleagues. And if a referee was issuing cards, my guess is you'd have received a red long time ago.

I'm maintaining what I said. I feel that the basic rules for a fair communication have not been respected. I feel that a decision has been taken individually by you in urgency while it was planned differently. I have not been convinced by the arguments that you were using. I feel that the merging rights have not been used wisely.

I consider to be part of my role to ensure that everyone feels respected in the team. I consider to be part of my role that a fair communication, leaving time for everyone to clarify his/her thoughts is given, as it is common to see in scientific contexts. I consider to be part of my role, in the absence of someone else willing to develop clear policies, to ensure that clear rules are used.

Now, if ever you feel in turn unrespected, I'm ready to hear about it. If you have red cards to issue, please do it so that the discussion makes progresses. I'm not claiming to do everything right and I'd be delighted to hear about how I can improve my own action.

I'm now going to revert the PR. Not because I think the PR is bad, but because, as explained, I consider that there is a procedural irregularity, which de facto created a feeling that the discussion was confiscated.

I'm on the other side grateful to you to have opened #8027.

2018-07-10 20:05 UTC, maximedenes commented
> I'm now going to revert the PR. Not because I think the PR is bad, but because, as explained, I consider that there is a procedural irregularity, which de facto created a feeling that the discussion was confiscated.

This is not our normal operation procedure, so please first ask @mattam82 if he thinks this is the appropriate thing to do. If he says so, I will of course accept his judgement.

Note that I did follow the standard procedure, since all owners had approved the PR, and not request for changes was made.

2018-07-10 21:37 UTC, ejgallego commented
Hey guys calm down this is leading nowhere; online communication is difficult and indeed it is not productive to respond to rushed decisions with more rushed decisions.

For now I propose let's leave things like they are, let's give this feature a rest, and let's restart the discussion about attributes in September, hopefully with more clear ideas and a WG that should allow us to talk in person.

So if in the WG we consider the feature not yet to be ship-able we can revert/disable in time for 8.9

2018-07-10 22:22 UTC, Zimmi48 commented
> Are you chickening out?

@herbelin This behavior is completely unacceptable and needs to stop immediately. You are behaving like a bully and bullies are not welcome in our team. I and @mattam82 will talk to you in person tomorrow since you didn't give us the chance today.

2018-07-11 00:05 UTC, herbelin commented
@ejgallego: My wish is to have a "normal" relation with @maximedenes. A relation where I'm not interrupted when I'm talking. A relation where, when I'm writing a comment, this comment is not excessively ignored. A relation where, when a rule is used to justify a decision, an effort is done to use this rule consistently. I'd be happy to hear what hurts @maximedenes with me. I appreciate your frankness. I appreciate @zimmi48's frankness which helps the two of us to understand each other, which helps me to understand what is maybe wrong with my way of communicating.

Why would it be impossible to resolve misunderstandings? I don't see what could have to be feared in telling what we have on heart, for the benefit of a more fluid relation afterwards. @maximedenes is telling me that he does not believe he made something wrong by merging. I'm ready to believe that it did not realize what for me was wrong, but I also have not to remain silent on what was wrong for me, since otherwise, we would continue not to understand each other, and that's not my wish.

2018-07-11 06:59 UTC, maximedenes commented
> For now I propose let's leave things like they are, let's give this feature a rest, and let's restart the discussion about attributes in September, hopefully with more clear ideas and a WG that should allow us to talk in person.

I think it would be interesting to collect alternative proposals (in terms of concrete syntax and design choices) in the issue, in order to prepare a WG discussion. This technical part of the discussion does not seem to be what generates tension here, so it should be fine.

2018-07-11 07:40 UTC, Zimmi48 commented
> how do you suggest I should behave so that my words are not ignored?

I seriously suggest you just take a break from online interaction until you can talk to us and understand how your behavior is not appropriate.

> PS: Would 1:30pm tomorrow be ok for you for a meeting, say in the round building?

Yes.

2018-07-15 21:23 UTC, maximedenes commented
> On the meta-discussion, can we reach some conclusion?

I guess the conclusion will be given by @mattam82 and @Zimmi48. Meanwhile, here's my view:

- I did not want to force the merge of this PR (in which I'm not especially involved), or do it in a hurry. What I asked for many times was a clarification on what was considered blocking and what was not. In both cases, I had scheduled work accordingly (see above), so no special pressure. I struggled a lot to understand the answers. It may be my fault, or the answers may have been unclear, or both.

- A miscommunication happened later around this PR, and I'm very sorry about that. @ejgallego since then clarified that by "I think we made it clear that the PR can be merged now" he meant "as it is, in the current state", not "at this moment in time". I misinterpreted it and also what @herbelin told me at the dinner, which I really thought was we could merge and keep discussing. I don't remember interrupting any sentence, though. I believe it is exaggerated, but anyway could have been fixed easily since we kept discussing after that.

In short, @Zimmi48 perfectly summarized my feeling:

> I don't know what you mean but it's still time to formally oppose using the red button. One thing that is sometimes annoying is that you are not making it clear enough what you want and then we go against your opinion without realizing.

- I feel you overreacted to the merge, and got past what is appropriate communication in the context of the Coq project. But I doubt this is the right place to discuss it.

In any case, I think we should encourage people to pursue the technical discussion in #8027.