Make Travis faster by removing more builds.
coq/coq pull request #7991
Opened 2018-07-04 07:23 UTC by Zimmi48

We remove all the testing of external projects from Travis. The current state was inconsistent anyways.
We keep the matrix of test-suite / validate / warnings / doc targets with different OCaml versions.
If people want to do more thorough testing on their personal branches, they will have to setup GitLab CI as explained in dev/ci/README.md. It's not difficult to setup.

The motivation is that yesterday it look longer for just the linter than for the full GitLab CI test suite to run on some PRs, due to a high number of recently merged PRs.

2018-07-05 10:01 UTC, ejgallego commented
> The current state was inconsistent anyways.

What do you mean by inconsistent?

> The motivation is that yesterday it look longer for just the linter than for the full GitLab CI test suite to run on some PRs, due to a high number of recently merged PRs.

Well, that's not strong enough IMHO; it is normal that some times CI systems are overloaded from time to time.

For now, I'd like to keep some actual CI testing in Travis.

2018-07-05 10:05 UTC, ejgallego requested changes
I'd like the testing to remain for a while more.

So either we can close this PR, or if you want I'd be OK with removing `fcsl-pcm` and `math-classes`.

2018-07-05 11:32 UTC, Zimmi48 commented
I'll do what you propose as it's better than nothing.

2018-07-05 11:34 UTC, Zimmi48 commented
Compared to your proposal, I've also removed bignums since it's already tested in color anyways.

2018-07-05 12:40 UTC, ejgallego approved these changes
Ok we can take this. As for general CI testing in Travis, I'd like to keep it functioning for now; Travis has scheduled some improvements and we don't know for sure we'll stop using it.

2018-07-05 14:18 UTC, Zimmi48 commented
> Travis has scheduled some improvements and we don't know for sure we'll stop using it.

Indeed, I'm planning to continue using Travis for CI testing in coq-community so I may have some feedback to give about new goodies (like the new "Checks" feature).

2018-07-05 15:59 UTC, merged

2018-07-09 12:39 UTC, Zimmi48 commented
I don't think we can expect any serious use of Travis in the future until they resolve their fetching bug IMHO. I'm restarting such failed jobs all the time, here is one instance I did not restart: https://travis-ci.org/coq/coq/builds/401436863

2018-07-09 14:12 UTC, ejgallego commented
If what worries you is the red light let's just remove it from the readme. IMHO keeping the build jobs for now costs very little and allows for some experiments if we want.

2018-07-09 15:02 UTC, Zimmi48 commented
No, I want the green light because there is stuff that is tested only on Travis.

2018-07-09 15:14 UTC, ejgallego commented
> No, I want the green light because there is stuff that is tested only on Travis.

Only the linter, right?

2018-07-09 15:40 UTC, Zimmi48 commented
Also the macOS tests (basically, what is described in the CI documentation).

2018-07-09 15:49 UTC, ejgallego commented
Ah, indeed the OSX migration to Gitlab is still not done.

2018-07-09 16:09 UTC, Zimmi48 commented
No, but @maximedenes is going to work on this really soon (but we'll probably keep the test-suite on Travis, like we did with AppVeyor).

2018-07-09 17:01 UTC, JasonGross commented
You can pass the option that allows installation of unauthenticated packages, and that seems to get rid of the fetching issues for me.