Put plugin exports in the right compatibility file
coq/coq pull request #800
Opened 2017-06-15 22:40 UTC by JasonGross

This closes [bug #5607](https://coq.inria.fr/bugs/show_bug.cgi?id=5607).

PR #220 put the exports in the wrong compat files, presumably because it
was originally targeted to version 8.6, and this wasn't updated when it
was retargeted to version 8.7.

2017-06-15 22:49 UTC, Zimmi48 requested changes
LGTM modulo the remark about fixing overlays.

2017-06-15 22:49 UTC, Zimmi48 commented on dev/ci/ci-user-overlay.sh
> -    fiat_crypto_CI_GITURL=https://github.com/letouzey/fiat-crypto.git
This is not something you should care about. Fix `ci-basic-overlay.sh` instead.

2017-06-16 00:41 UTC, JasonGross commented on dev/ci/ci-user-overlay.sh
> -    fiat_crypto_CI_GITURL=https://github.com/letouzey/fiat-crypto.git
Oh, oops, I reverted the wrong commit

2017-06-16 00:42 UTC, JasonGross commented on dev/ci/ci-user-overlay.sh
> -    fiat_crypto_CI_GITURL=https://github.com/letouzey/fiat-crypto.git
Should I edit just the basic-overlay, or also this one?

2017-06-16 07:50 UTC, Zimmi48 approved these changes
To have this PR properly tested by Travis, you should probably add to this PR the commit from #792.

2017-06-16 07:50 UTC, Zimmi48 commented on dev/ci/ci-user-overlay.sh
> -    fiat_crypto_CI_GITURL=https://github.com/letouzey/fiat-crypto.git
This one you can leave unchanged. But it doesn't matter actually.

2017-06-16 21:58 UTC, JasonGross commented
The overlay reverting depends on #792; should I cherry-pick the relevant bits into this PR?

2017-06-19 21:27 UTC, JasonGross commented
Rebased, now on top of commits cherry-picked from #792

2017-06-20 07:38 UTC, maximedenes commented
@JasonGross Could you rebase now that #792 has been merged? The history is going to look a bit messy otherwise. Thanks!

2017-06-20 12:16 UTC, JasonGross commented
I've rebased to drop the conflicting change to `ci-user-overlay`, but, @maximedenes , #792 was on v8.6, and this is on trunk, so rebasing won't help there until you (or someone) merges v8.6 into trunk again.

2017-07-07 07:55 UTC, merged