make-both-single-timing-files: fix --sort-by=diff
coq/coq pull request #8002
Opened 2018-07-05 13:44 UTC by RalfJung

**Kind:** bug fix.

Previously, "sorted" output could look like this:
```
After     | Code                                                          | Before    || Change    | % Change 
--------------------------------------------------------------------------------------------------------------
3m23.75s  | Total                                                         | 2m38.35s  || +0m45.40s | +28.67%  
--------------------------------------------------------------------------------------------------------------
0m32.08s  | Chars 60026 - 60035 [End~code.]                               | 0m23.932s || +0m08.14s | +34.04%  
0m19.326s | Chars 60021 - 60025 [Qed.]                                    | 0m15.875s || +0m03.45s | +21.73%  
0m04.327s | Chars 44373 - 44377 [Qed.]                                    | 0m03.119s || +0m01.20s | +38.73%  
0m06.806s | Chars 19856 - 19860 [Qed.]                                    | 0m05.006s || +0m01.79s | +35.95%  
0m07.917s | Chars 09831 - 10013 [(constructor;~~~solve_proper_c...]       | 0m05.942s || +0m01.97s | +33.23%  
0m04.843s | Chars 32121 - 32125 [Qed.]                                    | 0m03.479s || +0m01.36s | +39.20%  
0m04.099s | Chars 09048 - 09052 [Qed.]                                    | 0m02.538s || +0m01.56s | +61.50%  
0m04.826s | Chars 48906 - 48910 [Qed.]                                    | 0m03.514s || +0m01.31s | +37.33%  
0m03.844s | Chars 26074 - 26078 [Qed.]                                    | 0m02.719s || +0m01.12s | +41.37%  
0m00.003s | Chars 15737 - 15747 [iModIntro.]                              | 0m00.001s || +0m00.00s | +200.00% 
0m00.074s | Chars 31688 - 31816 [(<ssreflect_plugin::ssrtclseq@...]       | 0m00.12s  || -0m00.04s | -38.33%  
0m00.107s | Chars 46605 - 46611 [wp_op.]                                  | 0m00.072s || +0m00.03s | +48.61%  
0m00.s    | Chars 47297 - 47298 [{]                                       | 0m00.s    || +0m00.00s | N/A
```
Not very sorted, if you ask me.

2018-07-05 22:44 UTC, JasonGross requested changes
Thanks for fixing this!

I'd prefer having all the different sorts of sorters (`get_key_diff`, `get_key_abs`, `get_key_diff_int`) defined before the branches, so they're easier to compare/read/understand, but I'm not attached to this change, and if others think it's better like this, I'm happy to have it merged like this.

2018-07-06 21:53 UTC, RalfJung commented
Sure, I don't care strongly. Done.

2018-07-07 11:01 UTC, JasonGross approved these changes
LGTM when the ci is happy

2018-07-07 17:40 UTC, RalfJung commented
What do those tests do? The error
```
FAILURES
0m01.19s  | Compilers/Z/Bounds/Pipeline                    | 0m01.04s  || +0m00.14s | +14.42% 0m01.19s  | Compilers/Z/Bounds/Pipeline                       coq-makefile/timing/run.sh...Error!
```
does not say anything about what went wrong.

2018-07-07 17:52 UTC, jashug commented
It looks like
```
cat time-of-build-both.log
After    | File Name | Before   || Change    | % Change
-------------------------------------------------------
0m00.62s | Total     | 0m00.63s || -0m00.01s | -1.56%  
-------------------------------------------------------
0m00.06s | Fast      | 0m00.58s || -0m00.52s | -89.65% 
0m00.57s | Slow      | 0m00.06s || +0m00.51s | +850.00%
--- time-of-build-both.log.desired.processed	2018-07-06 22:10:01.000000000 +0000
+++ time-of-build-both.log.processed	2018-07-06 22:10:01.000000000 +0000
@@ -2,5 +2,5 @@
 ------
 ms | Total | ms || +ms | +%
 ------
-ms | Slow | ms || -ms | -%
 ms | Fast | ms || -ms | -%
+ms | Slow | ms || -ms | -%
==========> FAILURE <==========
    coq-makefile/timing/run.sh...Error!
```
is the actual error, and the line
```0m01.19s  | Compilers/Z/Bounds/Pipeline                    | 0m01.04s  || +0m00.14s | +14.42% 0m01.19s  | Compilers/Z/Bounds/Pipeline                       coq-makefile/timing/run.sh...Error!```
is a problem with output interleaving?

2018-07-07 18:38 UTC, Zimmi48 commented
On GitLab, you can get the log through the artifacts BTW.

2018-07-07 21:57 UTC, JasonGross approved these changes

2018-07-11 08:06 UTC, merged

2018-07-11 08:06 UTC, JasonGross commented
Oops, thanks for the reminder. Merged now.