Only check overlay extensions on git-tracked files
coq/coq pull request #8069
Opened 2018-07-14 12:42 UTC by JasonGross

This way, when editors leave over temporary files from editing
user-overlays, we don't prevent commits unless they are added to git.

**Kind:** feature / infrastructure.

2018-07-14 13:57 UTC, Zimmi48 commented
@SkySkimmer It looks like you are not listed as official owner for this file.

2018-07-16 11:23 UTC, SkySkimmer requested changes
This actually breaks the pre commit hook when committing through magit, because magit calls git with --literal-pathspecs (disabling interpretation of *) which also applies in the hook.
I think the easiest solution is to just `git ls-files "dev/ci/user-overlays/"`.

2018-07-16 13:29 UTC, JasonGross commented
> `git ls-files "dev/ci/user-overlays/"`

Changed

2018-07-16 14:25 UTC, SkySkimmer approved these changes

2018-07-16 14:30 UTC, merged