Do not run 32-bit Windows builds on pull requests.
coq/coq pull request #8136
Opened 2018-07-24 15:02 UTC by Zimmi48

I have never seen this build fail without the 64-bit Windows build failing as well. So it is just a waste of time to test it on every pull request and we are short in Windows test machines.

**Kind:** infrastructure.

2018-07-24 16:22 UTC, ejgallego commented
Ummm, we are not short on windows runners AFAICT, it is just that we haven't enabled them.

2018-07-25 13:51 UTC, Zimmi48 commented
> Ummm, we are not short on windows runners AFAICT, it is just that we haven't enabled them.

Indeed, I've been wondering why we only had three Windows jobs running at the same time, on the following runners:
- windows-untrusted5
- windows-untrusted-i02
- INRIACI-UO50J28

while we have way more VMs that report as up and that are registered as runners. Do you understand what's going on?

Anyways, even if we can fix this (we could do it by deleting existing non-functioning VMs and creating and registering them again if there is no better way), I still believe that the present PR should be merged: as I said I've never seen a Windows 32 bit build fail without the Windows 64 bit build failing as well, so it still looks like a loss of energy to do this test on every PR. Furthermore (and more importantly), I'd like to get rid of AppVeyor (#8078) but the limiting factor is our capacity on GitLab CI, so removing this one job would allow to put a Windows test-suite job instead.

2018-07-25 16:30 UTC, ejgallego commented
> while we have way more VMs that report as up and that are registered as runners. Do you understand what's going on?

I don't; in the past we had 6 runners, but it seems that the CI handling is done quite opaquely. [Not even an action log AFAICS, but there could be one in the admin console]

As long as we plan to distribute both 32 and 64 bit versions for Windows I'd like to see both jobs remain active. Removing Appveyor is an orthogonal thing and poses different kind of challenges AFAICT.

2018-07-25 17:05 UTC, ejgallego requested changes
My preliminary position here is that as long as we are shipping a 32bit windows build I'd rather keep the job in place.

@SkySkimmer ?

2018-07-25 17:37 UTC, SkySkimmer commented
I don't know.
Maybe @maximedenes or @MSoegtropIMC have an opinion.

2018-07-25 17:39 UTC, ejgallego commented
Certainly the missing Windows runners should be restored ASAP @maximedenes

2018-07-25 18:23 UTC, MSoegtropIMC commented
As far as I know many "power Coq users" prefer the 32 bit version because it is faster (pointers are smaller and need lass cache space and Coq data is likely mostly pointers). So I would say that both, the 32 bit and the 64 bit version are important.

On the other hand I tend to agree that testing both 10x a day is a waste of resources (think of Coq's CO2 footprint ;-) But if we disable one or the other, I would insist on having e.g. a daily build which tests more things, which I think is anyway a good idea. Both are required, and I think the last thing @maximedenes wants when doing a release is a not working windows installer.

One more note: in case we have a daily build, I would add a test which actually installs Coq from the installer and runs a few regression tests to see if it actually works.

2018-07-25 18:31 UTC, Zimmi48 commented
> But if we disable one or the other, I would insist on having e.g. a daily build which tests more things, which I think is anyway a good idea.

Not that this PR only removes the test on pull requests, but keeps it in the master branch, so each time a pull request is merged, the build is still tested. The only (very low) risk that this PR could pose would be to find out that we have broken the build after a PR was merged. But there wouldn't be any risk of discovering the problem at release time.

2018-07-25 18:55 UTC, MSoegtropIMC commented
@Zimmi48 : thanks, I am good to go then.

off topic: Would you recommend to add the "test if the installer is not just a bunch of random bytes" test in the same way, e.g. run only on a PR? It might not take so long - I wouldn't run a largish regression test, just some tests that it makes sense and that the included addons are accessible. Total run time might be 10 minutes or so.

2018-07-25 19:11 UTC, Zimmi48 commented
Yes, I would recommend adding this test to all packaging jobs, including the ones that run on a PR.

2018-08-01 16:00 UTC, Zimmi48 commented
@ejgallego I suggest to go ahead and merge this PR. We are back to having 6 Windows runners which is better, but this is still the limiting factor of our CI, and it will become even more so once we add the macOS packaging job.

2018-08-02 07:07 UTC, MSoegtropIMC commented
I agree. Without a test that the installer actually does something useful, this CI test is not so useful anyway.

2018-08-06 16:40 UTC, ejgallego approved these changes
Merging as @Zimmi48 requested.

2018-08-06 16:41 UTC, ejgallego commented
Please rebase so the CI runs again.

2018-08-13 12:26 UTC, Zimmi48 commented
Done.

2018-08-20 15:32 UTC, merged