Fix #7887: Lia struggles with goals in `Type`
coq/coq pull request #8140
Opened 2018-07-25 05:21 UTC by maximedenes

Credits to @ppedrot for the Ltac tricks.

- [X] Added / updated test-suite

2018-07-26 08:07 UTC, maximedenes commented
Any takers? @ppedrot @gares ?

2018-07-26 09:34 UTC, ppedrot commented
Isn't it a bit strange that the tactic will do two different things depending whether the goal is a proposition or a type? The current situation seems better than before, but couldn't we try to handle more stuff in zify?

2018-07-26 09:35 UTC, Zimmi48 commented
@maximedenes Seems to me that you didn't give enough time to the code owner (@fajb) to react before asking for someone else to take this...

2018-07-26 09:36 UTC, maximedenes commented
> Seems to me that you didn't give enough time to the code owner (@fajb) to react before asking for someone else to take this...

Ok, what is the recommended time?

2018-07-26 09:36 UTC, ppedrot commented
I can step down if @fajb wants to take over, let him change the assignee if so.

2018-07-26 09:38 UTC, maximedenes commented
> The current situation seems better than before, but couldn't we try to handle more stuff in zify?

We could, maybe. But this PR is a strict improvement, and `zify` is already a bottleneck on many examples, so I'd prefer to not push too much stuff there. Also, if the goal is already on `Z`, I don't think `zify` should do anything.

2018-07-26 09:42 UTC, Zimmi48 commented
> Ok, what is the recommended time?

I don't know. In #8098, I put 5 working days. This seemed reasonable...

2018-07-27 07:57 UTC, fajb approved these changes
This is good to me: this prevents a low-level error and increases the applicability of the tactic.

2018-07-30 13:20 UTC, maximedenes commented
@fajb would you mind merging this? Thanks!

2018-07-30 14:42 UTC, JasonGross commented on plugins/micromega/Lia.v
> +  | _ => exfalso; zify ; unfold Z.succ in * ; unfold Z.pred in *
What's the reason to duplicate the branches, rather than write
```coq
match s with
| Prop => idtac
| _ => (* we can't solve non-Prop goals except by proving False *) exfalso
end;
zify ; unfold Z.succ in * ; unfold Z.pred in *.
```
?

2018-07-30 14:43 UTC, maximedenes commented on plugins/micromega/Lia.v
> +  | _ => exfalso; zify ; unfold Z.succ in * ; unfold Z.pred in *
If that's equivalent, I prefer your version indeed.

2018-07-30 14:43 UTC, JasonGross requested changes
I would suggest changing the branches as I suggest (or at least turn `match s` into `lazymatch s`), or else if you end up with a case where `zify` fails on a `Prop` goal, this will mask it, and if `zify` is failing on the context, it will take twice as long to fail.

2018-07-30 14:45 UTC, JasonGross commented on plugins/micromega/Lia.v
> +  | _ => exfalso; zify ; unfold Z.succ in * ; unfold Z.pred in *
It's almost equivalent.  The current version will backtrack across failures of `zify` in the first branch.  If this is the behavior you want, then I'd suggest leaving it and making a note of such.  In cases where `zify` succeeds, the two versions are equivalent.

2018-07-30 14:46 UTC, maximedenes commented on plugins/micromega/Lia.v
> +  | _ => exfalso; zify ; unfold Z.succ in * ; unfold Z.pred in *
No, you're right, it's probably not what we want.

2018-07-30 14:46 UTC, JasonGross commented on plugins/micromega/Lia.v
> +  | _ => exfalso; zify ; unfold Z.succ in * ; unfold Z.pred in *
Well, almost equivalent.  If `Z.succ` or `Z.pred` shows up only in the goal, and also the user issues `Opaque Z.succ` or `Opaque Z.pred` before calling this tactic, then the version I suggest will not backtrack across the unfolding failure, while the verseion currently in this PR will.  But, again, I think this backtracking behavior is not the behavior you want `lia` to have.

2018-09-13 09:29 UTC, ppedrot commented
@maximedenes Are you willing to implement the changes proposed above?

2018-10-11 09:09 UTC, ppedrot commented
@maximedenes ping.

2018-10-11 09:16 UTC, maximedenes commented
> Are you willing to implement the changes proposed above?

I won't have time until a while (we made sure this was no longer on the critical path for `Coqlib`), so feel free to take over. Also I'm an Ltac beginner...

2019-09-16 06:32 UTC, ppedrot commented
@maximedenes Is this superseded by #9856?

2019-09-16 06:33 UTC, maximedenes commented
Yes, it should be.

2019-09-16 06:34 UTC, maximedenes commented
But please confirm it before closing this.

2019-09-16 07:43 UTC, fajb commented
I confirm #9856 handles goals in Type.

2019-09-16 09:34 UTC, closed without merging