Handle diffs better for the "Undo" command.
coq/coq pull request #8182
Opened 2018-07-28 16:30 UTC by jfehrle

**Kind:** bug fix / feature.

(I'll file a bug report if that's really needed, but this is on the borderline between a bug and a feature.  Hypothetically if the spec says "Coq crashes if you do X", then it's not a bug--just a (probably) dumb spec.)

Current code shows diffs between the current proof state and the proof state before the last command/tactic was applied.  That's probably not what the user wants to see if they enter an `Undo` command--they want to see the diffs that were previously displayed for that proof state.  Diffs should really be between the resulting proof state and the proof state for the last tactic applied before that.

Here's what you get now: the first and third diffs correspond to the same proof state but the diff info is not the same--not helpful.

![bad undo](https://user-images.githubusercontent.com/1253341/43358374-80fa3650-925e-11e8-9f9e-30f2e64f1d0f.PNG)

And here is the improved behavior; the first and third diffs are the same.  Much better.

![image](https://user-images.githubusercontent.com/1253341/43358379-933636c0-925e-11e8-9d75-bdb0dd146a1e.png)

The "Back" command doesn't keep enough info to allow finding the correct prior proof state.  Not planning to address that unless someone else wants to provide the necessary data.  I'm not seeing how "Back" is a particularly useful command.

This change also handles going backward in CoqIDE using the "Backward One Command" button.

Note there are other cases where the diffs should use different data.  For example, `all: swap 1 2` only changes the proof view, not the underlying proof state.  More on that later...

2018-07-28 16:41 UTC, jfehrle commented
@gares Perhaps you should review first since the most significant changes are in Stm.ml.

2018-07-31 08:30 UTC, gares requested changes

2018-07-31 08:30 UTC, gares commented on stm/stm.mli
> +val get_prev_proof : doc:doc -> Proof.t option
I don't like the API to be aware of the current state, or at least, this is where ae are going with the entire API so the new code should not be stateful.
I think you should take in input the `Stateid.t` and use `Stm.get_current_state` at call site (and the comment needs to be fixed accordingly).

2018-08-01 01:08 UTC, jfehrle commented
@gares, I made the changes you suggested.  @ejgallego and @ppedrot, would you look at your parts--very small changes.  Thanks,

2018-08-01 02:09 UTC, jfehrle commented
The test failure appears random and unrelated to the changes.

2018-08-01 08:55 UTC, Zimmi48 commented
Yes, apparently someone broke OPAM and this is the reason for the failing Windows test.

2018-08-01 09:19 UTC, gares approved these changes

2018-08-01 09:22 UTC, merged

2018-08-01 13:55 UTC, jfehrle commented
Thanks for your help!

2018-08-01 14:19 UTC, Zimmi48 commented
Yes @gares, the failure occurred at artifact uploading. I have some code that is supposed to handle this kind of failures (https://github.com/coq/bot/blob/b2cd2b70920b86b86138c04878433b78b6962dc0/bot.ml#L516-L535) but apparently not all of them (in this case it failed silently). I'll try to improve this.