Remove romega in favor of lia
coq/coq pull request #8419
Opened 2018-09-06 09:06 UTC by vbgl

This is a subset of #7878. This should lead to fewer compatibility issues than its equivalent with omega because `romega` relies on `zify`, just like `lia`.

One motivation is to reduce the work for coqlib (#186).

- [x] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in CHANGES.

2018-09-06 09:35 UTC, vbgl commented
@ejgallego This breaks the dune build: there is no .ml file in the (now nearly empty) `romega` plugin. Should there still be a `plugin_base.dune` file? If so, what should be in it?

2018-09-06 09:54 UTC, ejgallego commented
@vbgl the current coq_dune code assumes that every directory in `plugins` includes a `.base` ml-config file. Just leaving an empty file (or with a comment there) should do the trick until the code is improved.

2018-09-06 09:54 UTC, ejgallego commented
> If so, what should be in it?

Usually there you add the configuration of the ml-part of the plugin. Given that the plugin has no ml part just leaving it empty will work.

2018-09-06 09:56 UTC, ejgallego approved these changes
META is OK

2018-09-06 10:40 UTC, Zimmi48 requested changes
Please do as I recommended @maximedenes in the previous PR: do a small 8.9 PR deprecating `romega` and remove completely (no compatibility layer) in 8.10. That is: make the present PR target 8.10. Given that the branching should happen tomorrow, this shouldn't be a problem for you.

2018-09-06 11:19 UTC, gares approved these changes
makefile changes ok

2018-09-06 12:35 UTC, ppedrot approved these changes

2018-09-11 13:14 UTC, Zimmi48 approved these changes

2018-09-11 13:16 UTC, Zimmi48 commented
@vbgl Apart for the entry in CHANGES, this seems ready to me. `romega` didn't have a code owner, so who shall merge?

2018-09-11 14:18 UTC, vbgl commented
It breaks the test suite and bignums. I’m working on both.

2018-09-13 08:03 UTC, vbgl commented
Bignums and other external libraries have been updated. So only the test-suite is still broken. The only case of failure that is introduced should be addressed by #8462.

2018-09-24 09:43 UTC, vbgl commented
CI failure is spurious (opam 2 related). This PR is ready for merging; thanks.

2018-09-24 18:47 UTC, Zimmi48 reviewed
Since no one is an owner for most of these files, I'll take this PR. Assuming my suggestions are implemented, I'll merge this PR on Wednesday, barring further comments.

2018-09-24 18:47 UTC, Zimmi48 commented on doc/sphinx/addendum/micromega.rst
> +:cite:`TheOmegaPaper`.
Please indent this paragraph.

2018-09-24 18:47 UTC, Zimmi48 commented on test-suite/success/ROmega.v
> +Require Import ZArith Lia.
Add a comment explaining the historical reason for this test-suite file being called "ROmega"

2018-09-24 18:47 UTC, Zimmi48 commented on test-suite/success/ROmega0.v
> +(* Pierre L: examples gathered while debugging lia. *)
I'd rather keep the historical comment as-is but add another one explaining the name of the file.
The renaming of the test cases below is not a problem but not strictly necessary.

2018-09-24 18:47 UTC, Zimmi48 commented on test-suite/success/ROmega2.v
> +(* First a simplified version used during debug of lia on Test46 *)
Keep comment as-is but add another historical comment.

2018-09-24 18:47 UTC, Zimmi48 commented on test-suite/success/ROmega3.v
> +Require Import ZArith Lia.
Add comment.

2018-09-24 18:47 UTC, Zimmi48 commented on test-suite/success/ROmegaPre.v
> +Require Import ZArith Nnat Lia.
Add comment.

2018-09-26 11:11 UTC, Zimmi48 approved these changes
That's funny to have put a slightly different comment in each test file :laughing:

2018-09-26 11:14 UTC, merged