Deprecate romega in favor of lia
coq/coq pull request #8425
Opened 2018-09-06 16:12 UTC by vbgl

#8419 removes the romega tactics, which is too big of a change. This PR only deprecates it.

- [x] Entry added in CHANGES.

NB: this branch is based on #8423.

2018-09-06 21:49 UTC, herbelin approved these changes
Looks making sense, very good.

Like for [fourier/lra](https://github.com/coq/coq/pull/7897#issuecomment-399696815), I wonder about what is the best name for the semantical superset of lia, omega and romega. Somehow, even if not reflecting what it does, `omega` has become a popular name among users. On the other side, my feeling is that less people are attached to the name `romega`, but one would need to ask to know. The name `lia` is very good to express what it does, but pretty cryptic if one does not know in advance what the acronym denotes. I wonder whether we should think at something more immediately clear, especially for newcomers, like `arith`, or `larith`. At the same time, `omega` has become popular without denoting anything particular at first, so one may get used to `lia`. Moreover, in contrast with `lra` which (at least me) I easily mispells, `lia` is pronouncable and easier to remember for me. Thus, I probably would lean by default towards keeping `lia` as well as `omega` aliasing to it, but I'd be curious to hear user feedback on this question, before really making up a personal opinion.

Side question: why twice `nia` (whose name is cryptic as well for a newcomer) in `Remainder_equiv`?

2018-09-07 07:29 UTC, vbgl commented
Thanks for the comments. Indeed, `nia` was not needed there.

2018-09-07 08:42 UTC, Zimmi48 approved these changes
Thanks. A good first step indeed for 8.9.

2018-09-07 12:07 UTC, maximedenes commented
@vbgl can you rebase now that #8423 is merged?

2018-09-07 16:49 UTC, Zimmi48 requested changes
Sorry I forgot about this earlier: this PR should also modify the doc (which mentions `romega` more than it documents it) to add a `.. deprecated::` directive (search for other uses of this directive in the manual for examples). The PR removing romega should also be updated to remove all mentions from the manual.

2018-09-10 08:03 UTC, Zimmi48 approved these changes
Perfect, thanks!

2018-09-11 09:25 UTC, ppedrot approved these changes

2018-09-11 09:34 UTC, Zimmi48 commented
Everyone approved. Who merges? @ppedrot?

2018-09-11 09:47 UTC, merged