Print Universes Subgraph
coq/coq pull request #8451
Opened 2018-09-10 16:13 UTC by SkySkimmer

This adds an optional [Subgraph] part to the Print Universes command,
eg [Print Universes Subgraph(i j)] to print only constraints related
to i and j (and Prop/Set).

Hopefully this is helpful when researching universe inconsistencies in a monomorphic context.

I feel like there should also be some syntax to include all universes related to some constant or module but I'm not sure about the details. Notably it's currently impossible to tell it to include any unnamed universes making it not so useful.

2018-09-11 12:28 UTC, SkySkimmer commented
The order of printing is different in 32bits? How?

2018-09-11 12:30 UTC, ppedrot commented
A difference in hashing, probably.

2018-10-09 11:46 UTC, SkySkimmer commented
The dependency on hashing order should be gone since #8475 so let's see what a rebase tells us.

2018-10-09 13:44 UTC, SkySkimmer commented
I was wrong, the hash order is used by the map fold used when printing.

2018-11-13 14:42 UTC, SkySkimmer commented
Should work now.

2018-11-13 18:45 UTC, ppedrot requested changes
It's a feature, so you should advertise it in the CHANGES.

2018-11-14 12:41 UTC, SkySkimmer commented
Added CHANGES and a simple fix for `Print Universes "foo.dot".`

2018-11-16 16:41 UTC, ppedrot approved these changes
Will merge quickly if nobody complains.

2018-11-19 08:41 UTC, merged

2018-11-20 09:29 UTC, Zimmi48 commented on doc/sphinx/language/gallina-extensions.rst
> +Prints the graph restricted to the requested names (adjusting
This block should have been properly indented.