Extraction TestCompile
coq/coq pull request #859
Opened 2017-07-05 09:47 UTC by letouzey

This introduce a new command for extraction + ocamlc.
```
  Extraction TestCompile foo
```
 is equivalent to:
```
  Extraction "/tmp/testextraction1234.ml" foo
  ocamlfind ocamlc -I /tmp -c /tmp/testextraction1234.mli /tmp/testextraction1234.ml
```
 This command isn't meant for the end user, but rather as an helper
 for test-suite scripts. It only works with extraction to OCaml,
 and the generated code should be standalone.

2017-07-05 12:13 UTC, gares requested changes
I think the patch is good, but I think it deserves to come with a test in the test-suite.

2017-07-20 18:26 UTC, letouzey commented
@gares : This PR was made in order to add some `Extraction TestCompile` into our test-suite files,
for instance the test-suite files added in #857. I should also adapt older test-suite files such as
`test-suite/succes/extraction.v` but that remains to be done.

2017-07-21 15:05 UTC, maximedenes commented
@gares can I merge this PR? It will make it possible to have test cases for e.g. #909.

2017-07-26 11:36 UTC, gares approved these changes

2017-07-26 12:35 UTC, merged

2017-07-26 20:25 UTC, Zimmi48 commented
This is a feature but @maximedenes you added the `needs: backport` flag. Does it mean that you think that because it is very lightweight and useful only for testing there should be an exception for this? No opposition to this, just asking for clarification.

2017-07-28 16:05 UTC, maximedenes commented
I tagged it for backport in anticipation of extraction fixes whose test case will depend on this feature. I think you even already backported such fixes.

2017-07-28 16:39 UTC, Zimmi48 commented
No the PRs I backported do not add test-suite files which depend on this feature.

2017-07-28 16:42 UTC, Zimmi48 commented
But if there were a PR both fixing a bug and adding such test file, I could always backport the bugfix only (that would be just a tad more complicated). So really, I would like some opinions before deciding what to do with this PR. Both options look fine to me.

2017-08-01 15:55 UTC, Zimmi48 commented
OK so if no one really cares, I won't backport this. If you do care, speak up before the beta release (which could be in just a few days).

2017-08-02 09:32 UTC, letouzey commented
@Zimmi48 @maximedenes : well, I do care. Adding this `Extraction TestCompile` to 8.7 isn't something of paramount importance, and I could live without it. But even if that would be a "feature-freeze" exception, I think it definitively worths it. This code is small (30 lines), it's strictly an extra feature, that does not interfere with anything else in Coq, it is ready and working well, it is documented (see #925), it is meant primarily for internal use (our test-suite) and most importantly it helps tracking potential regressions of the extraction, and clearly that may concerns 8.7 as well. Up to you, guys...

2017-08-02 09:42 UTC, maximedenes commented
I think it is fine to merge it in 8.7, since the risk is low and it will make it easier to track down regressions during the life of 8.7. But it is @Zimmi48 's call.

2017-08-02 12:06 UTC, Zimmi48 commented
Thanks, that's all I needed ;-)
I will backport this PR and the associated ones then.

2017-08-03 09:54 UTC, Zimmi48 commented
Done.

2017-08-03 19:50 UTC, letouzey commented
Thanks