Some cleanups after cumulativity for inductive types
coq/coq pull request #864
Opened 2017-07-07 14:43 UTC by amintimany

This pull request makes Coq issue an error whenever an attempt is made to introduce a monomorphic cumulative inductive type. It also improves the documentation of cumumulativity. These were discussed in #613.

2017-07-07 14:46 UTC, amintimany commented
This PR also closed Bug 5611 in Buzilla. I added the suggested test in the tes-suite I'm not sure if it should be put in the docs!?

2017-07-07 15:12 UTC, JasonGross requested changes
I think the funext example should go in the refman, as an example justifying the usefulness or power of cumulatively.

2017-07-07 15:12 UTC, JasonGross commented on doc/refman/Universes.tex
> +inductive types and the like can be enforced to be
Add a comma after "set", otherwise I parse it as "set inductive types" and get confused

2017-07-07 15:12 UTC, JasonGross commented on doc/refman/Universes.tex
> +error is issued whenever the user inputs such monomorphic and
I think "such" doesn't agree with "type".  Perhaps "such a"?

2017-07-07 16:00 UTC, amintimany commented
@JasonGross I added the example with some small changes. Btw, why is this example called ```fun_ext_down```?

2017-07-07 16:28 UTC, JasonGross commented
It's a proof that funext is "downward closed"; if you think of the universe hierarchy as nested universes, then this is a proof that if funext holds in one universe, then it holds in all universes below that one.

2017-07-07 16:28 UTC, JasonGross approved these changes

2017-07-07 16:31 UTC, amintimany commented
@JasonGross oh, I see. that makes sense. I misread the constraint as ```e < e'``` and was confused :-).

2017-07-07 17:35 UTC, SkySkimmer commented
Why not make it 3 valued, so you have `Monomorphic` `Polymorphic` and `Cumulative Polymorphic` and something analogous for the global setting?

2017-07-10 07:30 UTC, amintimany commented
@Zimmi48 In that case I don't think error is suitable when ```Cumulative``` prefix is used. Maybe we should issue a warning saying that the ``` Cumulative``` prefix is being ignored!

2017-07-10 07:32 UTC, amintimany commented
@SkySkimmer ```Polymorphic``` and ```Monomorphic``` prefix are not exclusive to inductive types and can be used on other constructions, e.g., ```Polymorphic Definition ...``` or ```Monomorphic Lemma ....```

2017-07-10 09:37 UTC, Zimmi48 commented
> In that case I don't think error is suitable when Cumulative prefix is used. Maybe we should issue a warning saying that the Cumulative prefix is being ignored!

I'm not sure I understand what case you are talking about.

My suggestion was the following:

```
Cumulative Inductive foo := ... (* error: the Cumulative prefix can only be used in a polymorphic context *)
NonCumulative Inductive foo := ... (* error: the NonCumulative prefix can only be used in a polymorphic context  *)

Set Inductive Cumulativity.
Inductive foo := ... (* non polymorphic non cumulative no warning no error *)
Polymorphic Inductive bar := ... (* polymorphic cumulative *)
NonCumulative Polymorphic Inductive foobar := (* polymorphic non cumulative *)
NonCumulative Inductive barfoo := ... (* error: the NonCumulative prefix can only be used in a polymorphic context *)

Set Universe Polymorphism.
Inductive foobarfoo := ... (* cumulative polymorphic *)
NonCumulative foobarbar := ... (* non cumulative polymorphic *)
Monomorphic barfoobar := ... (* non cumulative non polymorphic *)

Unset Inductive Cumulativity.
Cumulative Inductive foofoofoo := ... (* cumulative polymorphic *)
```

2017-07-11 06:24 UTC, amintimany commented
@Zimmi48 This is a bit counter intuitive to me. Intuitively, when you set the option ```Set Universe Polymorphism``` it behaves as though every definition, lemma, etc. is preceded by ```Polymorphic``` prefix. Intuitively I would also want ```Set Inductive Cumulativity``` to behave as though every inductive definition is preceded by a ```Cumulative``` prefix. Don't you agree?

2017-07-11 06:47 UTC, Zimmi48 commented
But it is also a bit counter intuitive that `Set Inductive Cumulativity` is preventing the use of `Inductive` without a prefix. Moreover what I'm suggesting corresponds to what you initially had. It's just that my suggestion to raise an error when `Cumulative` is used in a monomorphic context only holds when the prefix is used explicitly. 

The whole problem stems from the fact that the visible switch for cumulativity still reflects the initial implementation you had and not the current three-valued one.

Maybe you should follow @SkySkimmer's proposal for the local setting and have a `Set Polymorphic Inductive Cumulativity` option which implies polymorphism for inductive types only.

2017-07-28 12:10 UTC, silene commented on doc/refman/Universes.tex
>  there is an option \texttt{Set Inductive Cumulativity} which when set,
Missing `Polymorphic`?

2017-08-01 07:45 UTC, amintimany commented
@maximedenes: I have implemented the idea of ```Set Polymorphic Inductive Cumulativity``` as suggested above by @Zimmi48. I think this PR should be ready for merging unless there is any other issue we need to discuss!?

2017-08-01 18:13 UTC, Zimmi48 approved these changes
I'm very happy about the new state of the documentation and the behavior of the commands.

2017-08-01 18:13 UTC, Zimmi48 commented on doc/refman/Universes.tex
> +\texttt{NonCumulative} prefix in a monomorphic contexts.
plural problem here, either remove "a" or "s".

2017-08-01 18:13 UTC, Zimmi48 commented on doc/refman/Universes.tex
> +That is, this optiotion, when set, makes all subsequent \emph{polymorphic}
typo here

2017-08-01 18:13 UTC, Zimmi48 commented on doc/refman/Universes.tex
> +inductive declarations cumulative (unless, of course if the \texttt{NonCumulative} prefix is used)
I think you can remove the word "if"

2017-08-01 18:13 UTC, Zimmi48 commented on doc/refman/Universes.tex
> +Fail Monomorphic NonCumulative Inductive Unit := unit.
You can also remove the `Fail` keyword, in which case, the manual will still print the error, but without the "The command has indeed failed..." part.

2017-08-01 18:18 UTC, Zimmi48 commented
Quick note: as this is changing the user access to inductive cumulativity, this PR *must* be merged before the beta release.

2017-08-02 07:47 UTC, amintimany commented
@Zimmi48: Thanks, I fixed the typos. Note however that this PR is not only documentation as it also changes some options and their behavior.

2017-08-02 12:32 UTC, Zimmi48 commented
Yes, I know and my use of the label might be deemed ambiguous, thus I just removed it.

2017-08-16 07:50 UTC, merged