[Numeral notations] Use Coqlib registered constants
coq/coq pull request #8720
Opened 2018-10-12 12:34 UTC by vbgl

Fixes #8564.

2018-10-15 07:34 UTC, SkySkimmer commented on theories/Init/Decimal.v
> +Variant int := Pos (d:uint) | Neg (d:uint).
Why this change?

2018-10-15 07:52 UTC, vbgl commented on theories/Init/Decimal.v
> +Variant int := Pos (d:uint) | Neg (d:uint).
I agree it’s unrelated. But since I was already touching this file, I took the opportunity to tidy it a bit…

2018-10-15 17:33 UTC, JasonGross requested changes
Thanks!

2018-10-15 17:33 UTC, JasonGross commented on plugins/syntax/numeral.ml
> +     fnl () ++ str "Instead of Decimal.int, the types Decimal.uint or Z could be used.")
What is the reason for dropping the parenthetical?  You could instead augment it to say `require BinNums or Register a constant as ... first`.

Either way, please also update the documentation to match the updated error message.

2018-10-16 08:14 UTC, vbgl commented
I’ve just updated the error messages and the corresponding documentation.

2018-10-16 08:39 UTC, Zimmi48 approved these changes

2018-10-16 09:40 UTC, JasonGross requested changes

2018-10-16 09:40 UTC, JasonGross commented on plugins/syntax/numeral.ml
> +     str "Instead of Decimal.int, the types Decimal.uint or Z could be used (you may need to require BinNums or Decimal first).")
I think you should only display the part about `Require ` if the types don't resolve / aren't registered.  But I don't object strongly.

2018-10-31 08:11 UTC, vbgl commented
This PR breaks HoTT; the overlay is ready but would break the compatibility of HoTT with Coq 8.9. Thus we wait: 1. that Coq 8.9 is released (or at least the β); 2. that a version of HoTT compatible with said version of Coq is officially tagged; 3. that HoTT merges the overlay.

No need to hurry.

2018-11-17 12:46 UTC, ppedrot reviewed
I'll let people more knowledgeable comment.

2018-12-13 22:20 UTC, SkySkimmer commented
>needs: merge of dependency

What's the dependency?

2018-12-14 10:32 UTC, SkySkimmer commented
I've only seen that tag used for other Coq PRs before but I guess nothing else fits better.

2019-01-25 09:50 UTC, vbgl commented
HoTT has been updated, so this PR is ready now.

2019-01-25 18:04 UTC, JasonGross approved these changes
My requests about error messages stand, but I'm not going to block this PR on that basis, and it would be nice to see this land.

2019-01-27 16:35 UTC, ejgallego commented
Taking this as part of @coq/parsing-maintainers

2019-01-27 16:51 UTC, ejgallego approved these changes
Look pretty straightforward, will merge soon if not further comments.

2019-01-31 00:23 UTC, merged