Opaqueproof+simplify fetch
coq/coq pull request #8788
Opened 2018-10-21 17:17 UTC by ejgallego

**Kind:** documentation / bug fix / feature / performance / infrastructure.

Fixes / closes #????

- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in CHANGES.md.

2018-11-17 12:52 UTC, ppedrot reviewed
This is a *cavalier législatif*, this PR also includes #8783... Can't we do that independently?

2018-11-20 17:17 UTC, gares commented on kernel/opaqueproof.mli
> +val get_cst : DiskData.t -> opaquetab -> opaque -> (constr * Univ.ContextSet.t) Future.computation
Why `_cst`? It is both the proof and the constraints, while cst seems to refer only to constraints

2018-11-20 17:20 UTC, gares requested changes
It is a nice simplification, but I'm not so happy with the name of the new API.
I'd say `_proof` is ok (I could live with the proof being "implemented" by a term and a constraints set), `_proof_cst` also.

I also think there is a type combinator for the pair `('a * Cuniv.ContextSet.t)` somewhere.

I'm reviewing only the last commit.

2019-05-21 16:46 UTC, ejgallego commented
This is not needed anymore after some changes in master.

2019-05-21 16:46 UTC, closed without merging