Added two proofs to the Lists library. The first, Forall_inv_tail, ex…
coq/coq pull request #8807
Opened 2018-10-23 14:47 UTC by llee454

Added two new theorems to the List library: Exists_impl and Forall_inv_tail. Exists_impl provides a theorem analogous to Forall_impl. Forall_inv_tail naturally extends Forall_inv.

Exists_impl accepts two predicates, [P] and [Q], and a list, [xs], and proves that, if [P -> Q], and there exists an element in [xs] for which [P] is true, then there exists an element in [xs] for which [Q] is true. This is analogous to the existing Forall_impl theorem, which, given similar arguments, proves that [Q] is true for all elements in [xs]. Adding Exists_impl fills a natural gap in the existing library.

Forall_inv_tail accepts a predicate, [P], and a list, [x0 :: xs], and proves that if [P] is true for every element in [x0 :: xs], then [P] is true for every element in [xs]. This theorem naturally complements the Forall_inv which takes similar arguments and proves that [P x0] is true. Again, adding Forall_inv_tail fills a natural gap in the existing library.

This is my first contribution to the standard library. I had previously submitted these changes in https://github.com/coq/coq/pull/8757 but had to delete the associated Git branch when a Git rebase command crashed.  Please let me know if there is anything else you need from me.

**Kind:** feature.

- Larry

2018-10-23 14:55 UTC, Zimmi48 commented
>This is my first contribution to the standard library. I had previously submitted these changes in #8757 but had to delete the associated Git branch when a Git rebase command crashed.

There is always another way. Next time you have trouble with git, feel free to ask for help in the PR thread.

2018-10-31 12:52 UTC, ppedrot requested changes
Reopening the usual point people don't agree on, I think that these theorems should be made Qed-opaque rather than defined transparently. The usual (questionable) arguments apply, but in addition in this precise case it is more uniform with the rest of the Forall / Exist related lemmas.

2018-10-31 18:04 UTC, llee454 commented
Thanks ppedrot, I will revise the proofs so that they are opaque rather than transparent.

2018-10-31 20:35 UTC, llee454 commented
The commands I executed were:

```
git rebase upstream/master <--- rebased my branch with upstream master
vim theories/Lists/List.v <--- added opaque commands
git add theories/Lists/List.v
git commit -m 'Revised the List module declaring Forall_inv_tail and Exists_impl as opaque.'
git push origin new-list-functions <--- failed due to an unexpected conflict
git pull origin new-list-functions <--- generated an unexpected confict
vim theories/Lists/List.v <--- resolved conflicts - origin did not have the opaque commands, but I did not see any other differences.
git add theories/Lists/List.v
git commit -m 'Revised the List module declaring Forall_inv_tail and Exists_impl as opaque.' <--- merged unexpected conflict with origin
git push origin new-list-functions
vim theories/Lists/List.v <--- corrected the strange text line in List.v
git add theories/Lists/List.v
git commit -m 'Minor syntax correction.'
```

2018-10-31 20:36 UTC, llee454 commented
The changes I made were trivial. I'm willing to manually reapply them, if you can tell me how to cleanly undo what was done.

2018-10-31 20:57 UTC, SkySkimmer commented
>`git push origin new-list-functions <--- failed due to an unexpected conflict`

Right, you need to push with force `-f` (or `--force-with-lease` but that's a pain to type when you use the command line git) after rewriting history (such as with rebase).
To fix `git reset -h 96385b4023` then redo the "corrected the strange text line in List.v" step should work. As above you will need to `push -f`.

2018-10-31 21:01 UTC, SkySkimmer commented
>redo the "corrected the strange text line in List.v" step

BTW commit this with `--amend` and no `-m` argument to avoid a pointless commit.

2018-10-31 21:12 UTC, llee454 commented
Thanks for the detailed technical help. I'll try to make these changes this evening.

2018-11-02 15:05 UTC, llee454 commented
Thanks for resolving the git issue. I've updated my local copy and see your changes.

2018-11-07 13:05 UTC, ppedrot commented
@llee454 Can you turn the definition into Qed-terminated lemmas?

2018-11-07 18:16 UTC, llee454 commented
Yes. I'll convert them and push my updates this evening.

2018-11-11 03:49 UTC, llee454 commented
I've updated the proofs for `Forall_inv_tail` and `Exists_impl`. Both are now Qed opaque.

2018-11-12 12:55 UTC, ppedrot commented
If I remember correctly, we were going to deprecate the `Proof term` syntax. @Zimmi48 I think you took part in this debate, am I right that we shouldn't use this syntax anymore?

2018-11-12 13:01 UTC, SkySkimmer requested changes
Please:
- Don't copy the type in a comment.
- Use automatic introduction and tactics consistently with the rest of the file.

2018-11-12 13:02 UTC, ejgallego commented
> am I right that we shouldn't use this syntax anymore?

Yes, the main problem is not that we are going to deprecate it, but that it is broken for example under Backtrack in CoqIDE etc...

2018-11-17 10:48 UTC, SkySkimmer approved these changes
Thanks!

You may want to use bullets so that you have only 1 goal focused at a time (see eg the proof of Forall_dec earlier in the file).

Also please squash your commits.

2018-11-28 06:11 UTC, llee454 commented
Hey SkySimmer, I squashed my commits and pushed my changes to GitHub. Thanks for all of the feedback and assistance getting this addition in!

2018-11-30 15:42 UTC, Zimmi48 commented
ping @ppedrot

2018-11-30 16:45 UTC, ppedrot approved these changes

2018-11-30 16:46 UTC, merged