Turning clearing of unused section variables on.
coq/coq pull request #883
Opened 2017-07-16 14:42 UTC by herbelin

By default, option `Proof Using Clear Unused` is off. This PR proposes to turn it on by default as this looks to me like the intuitive expectation (even if source of incompatibilities, which I suspect was the reason for having it off).

This depends on #882 for the existence of version number 8.7 (so that the option is on only from 8.8).

2017-07-16 14:48 UTC, JasonGross commented
I think this a bad idea.  The reason to have this off is that if it's on, there's no way to automatically transform a file to make use of `Proof using` via `Set Suggest Proof Using`.

2017-07-16 19:36 UTC, herbelin commented
You mean that `Set Suggest Proof Using` can be useful even when `Proof using` is already there?

2017-07-16 19:47 UTC, herbelin commented
By the way, I'm wondering about `Set Suggest Proof Using`. It is a very valuable feature but is there any reason it is in the kernel? In addition from being useless for checking, this has the drawback that the proper printers for kernel names are not available and one sees a debugging-style printing of the form `Top#A#foo`. At least, only the basename should be printed.

Another not so nice thing is that `Proof using` can be issued even after having already given tactics. Wouldn't it be more natural to enforce that it comes before any tactic application?

2017-07-16 19:49 UTC, JasonGross commented
It is, but that's not what I mean.  Say you have `Proof. clear x. auto. Qed.` as your proof.  `Set Suggest Proof Using` will give you a list that does not include `x`, and then your `clear x` will fail if this option is set.

2017-07-16 19:50 UTC, Zimmi48 commented
> Another not so nice thing is that Proof using can be issued even after having already given tactics. Wouldn't it be more natural to enforce that it comes before any tactic application?

Indeed, @herbelin and this is a more general issue than that. `Proof` (a no-op) and `Proof term.` can also be used after having given some tactics (although in the latter case, this has completely undefined behavior).

2017-07-16 20:17 UTC, herbelin commented
@JasonGross: but if for automatic purpose, why not to unset `Proof Using Clear Unused` in those files which are translated automatically. In interactive use, it seems natural that the default is not to see what we assert is useless, and not to have a `clear` manually, no?

2017-07-18 06:18 UTC, silene commented
As far as I remember, the option was turned off by default because clearing a section variable is the source of all evil (in Coq). I don't know whether sufficiently many bugs have been fixed so that users won't encounter that dreaded issue too often.

2017-07-18 16:12 UTC, gares reviewed
The value is off because too many things are broken when it is on. For example all Hints are still available even if they are cleared... Oh, and there are also name captures, i.e. you can re-introduce a local variable using a cleared section variable name, but with a different type. This breaks many things, for example the hint you use is now re-typed in a context where one of the variables it uses changed type...

2017-07-18 16:19 UTC, gares requested changes
Unless all issue related to clearing section variables are fixed, the only safe default is off.

I agree the desired, intuitive, behavior is the one where "Proof using A" removes from the context all but "A", but flipping this boolean is only making more bugs apparent.

2017-07-18 16:55 UTC, herbelin commented
@gares. Right, but since `Proof using` is (relatively) new, there is no problem of compatibility a priori to consider. So, I would advocate for giving priority to expected new interactive uses over compatibility with already done development, for which the option can anyway be unset. For instance, in the proofs I was looking at in `FMapPositive` (#885), I get a nicer naming of induction variables if a `clear` on the expected unused section variable is done.

Wrt to hints, I tried to find again an example, but in all cases, whether the option is on or not, it eventually fails, even if the time is different:
```coq
Section A. Variable H:False. Set Proof Using Clear Unused.
Proof using. auto. (* fails *)
```
```coq
Section A. Variable H:False. Unset Proof Using Clear Unused.
Proof using. auto. (* succeeds *). Qed. (* fails *)
```
@silene: Thanks for raising the issue. I'll prepare by a couple of days a summary on section variables trying to balance the advantages and drawbacks of clearing section variables.

2017-07-19 09:28 UTC, gares commented
`Print Hint` tells me that `clear` is not removing the hint associated to the cleared hyp from the db.

```
Section A.
Variable H : 0 = 0.
Hint Extern 0 => apply H.
Goal (forall A : Prop, A -> A) -> 0 = 1.
Proof.
Print Hint. (* H is there *)
clear H. Print Hint. (* H is still there *)
intro H. (* H is now different *)
debug eauto.
(*
1 depth=5 
1.1 depth=4 (*external*) (apply H)
1.1.1 depth=3 (*external*) (apply H)
1.1.1.1 depth=2 (*external*) (apply H)
1.1.1.1.1 depth=1 (*external*) (apply H)
1.1.1.1.1.1 depth=0 (*external*) (apply H)
*)
```

So, to me, automatically clearing section variables is just looking for troubles, especially because `intros` can do the capture for you.

2017-07-19 11:24 UTC, herbelin commented
@gares: You are raising the question of clearing section variables for which the interaction in a goal with global objects referring to these section variables is indeed "fragile". One solution is obviously to forbid clearing of section variables in general, but with that, we lose also the benefits of clearing. Is that really what we want?

Also your example does not use `Proof using`. Are you saying that because of global objects referring to section variables we should "polluate" the goal context with section variables which the `using` clause precisely asked to exclude?

2017-07-19 11:50 UTC, silene commented
No, I believe Enrico's point is exactly the same as mine. I think everyone agrees with you that the intuitive behavior is to clear these variables. It is just that, until all the bugs related to clearing section variables are fixed, we should refrain from automatically clearing section variables _by default_.

2017-07-19 17:14 UTC, herbelin commented
>  I think everyone agrees with you that the intuitive behavior is to clear these variables.

@silene: If so, let's indeed concentrate on how to get what we want. As far as I understand things at the current point, there is only one true "bug", namely that we lose track of what goal variables bind to section variables (the `clear H; intro H` section variable name capture [bug](https://coq.inria.fr/bugs/show_bug.cgi?id=2514)) for which I actually have a branch basically fixing it.

If I'm postponing the publication of this branch, it is because I fail to evaluate what is the optimal thing to do in situations such as reports [#4092](https://coq.inria.fr/bugs/show_bug.cgi?id=4092) and [#2215](https://coq.inria.fr/bugs/show_bug.cgi?id=2215). Namely, when a section variable is cleared,
- do we mean hidding it from the goal context but continuing providing, say, a qualified name to it and to its dependencies, since after all clearing is only about visibility, not about really clearing the objects 
- or do we mean fully clearing it and making unreferencable all what depends on it?

2017-07-19 18:07 UTC, JasonGross commented
> Namely, when a section variable is cleared,

I'd like to be able to choose which I mean.  I think the former is more useful than the latter, though `Proof using ` needs the latter kind.

2017-07-19 21:40 UTC, silene commented
As Jason said, with `Proof using`, it is best to prevent tactics from accessing any erased section variable as well as all the constants that depend on it. Otherwise the user gets at best an error message "foo depends on the variable bar which is not declared in the context" and at worst an ill-formed term that later blows up. I don't have a strong opinion on how `clear` should behave, though, since both behaviors kind of make sense. For backward-compatibility purpose, however, we might want `clear` on a section variable to behave like `Proof using`.

2017-07-20 10:15 UTC, herbelin commented
Then comes a critical question. To fix the `clear H; intro H` bug, and to properly report messages about dependencies on cleared section variables, we need to keep this information in the environment, which means in the kernel so that kernel functions such as `lookup_named`, `conv`, `type_of_inductive`, etc. have access to this information.

Basically, this means having a way to tell for each variable of the `named_context` whether it derives (by possible renaming, or conversion in body or conversion in type) from a section variable or not, and, for each original section variable if has been cleared, and if cleared (in order to issue an appropriate message) by an initial `Proof using` or by a `clear`.

Are we ready for such a `named_context` change (whatever the way the needed information is added)?

2017-07-20 11:14 UTC, mattam82 commented
I'm not sure how that will play out. What would happen with your proposed change on a clear H; intro H, an error because H is cleared but that only means it is tagged as such in the named context so the intro fails? Similarly, when trying to use a hint we would first check it's not referring to a H that is tagged as cleared in the current named context?

2017-07-20 11:36 UTC, herbelin commented
No failure on `clear H; intro H`, but the status of `H` changes. Before the `clear` it is indicated to derive from section variable `H`. After the `intro H`, the `H` does not get back its indication that it derives from section variable `H` (since it has another source).

When a hint or any other global objects referring to section variable `H` is considered, it is checked whether `H` has a variable in the named_context which derives from it. If yes, fine, and if not, an error of the form `foo depends on the section variable H which has been cleared in the current context` is issued, as it is currently.

(If we want it to work as in @Jasongross' [comment](https://github.com/coq/coq/pull/883#issuecomment-316470031), or as in bug reports [#4092](https://coq.inria.fr/bugs/show_bug.cgi?id=4092) and [#2215](https://coq.inria.fr/bugs/show_bug.cgi?id=2215), this would require more changes, however, as we would need to introduce a new way to refer a section variable different than `Var H`, so it is less clear whether such an extension is worth the feature.)

2017-07-20 11:40 UTC, mattam82 commented
I don't see how that will be represented in the named_context, after the clear H; intro H it would contain just one binding for H and information on the side about the cleared section variable H?

2017-07-20 11:54 UTC, herbelin commented
I don't see how to do it without some overhead in the complexity of structures. What I did at the current time is to have three tables:
- the `named_context` as we know it
- a `section_context`, also of type `Context.Named.t`, which contains the section variables as originally declared
- an extra set collecting those variables of the `named_context` which derive from a section variable, with the invariant that for any variable of this set, there is a corresponding convertible variable in the `section_context`

Maybe this can be simplified, depending on what features we exactly want to offer, but being able to track if a `H` in the goal directly derives or not from a section variable seem unavoidable to me in order to fix the `clear H; intro H` section variable bug.

2017-07-20 12:11 UTC, silene commented
I see the point of the extra set (by the way, shouldn't it be a map instead?), but I don't understand why you need `section_context`. Which operation will access it?

2017-07-20 12:15 UTC, mattam82 commented
For hints and other global objects declared outside of the proof context, I think it's enough indeed to just know if the Var H we stored still refer to the same section variable in the current context or not.

2017-07-20 13:28 UTC, gares commented
Not to be pessimistic, but section variable names percolate everywhere.

You can use them in notations, for example.  After you clear `H` what does `Notation H1 := H` mean?
You can declare them as instances, use them to type a canonical structure declaration.
They can be coercions.

It is not all about "intro H" replacing a section variable (even if my example was about it).
And indeed I agree with @silene , as long as these bugs are there, clearing section variables should be considered to be dangerous, it can't be a sane default.

2017-07-20 13:31 UTC, ejgallego commented
Shouldn't we just "deprecate/freeze" sections and work instead in a cooking-free replacement in the lines of what we discusses at the IM ?

2017-07-20 13:52 UTC, mattam82 commented
I would think that if we have a correct criterion to decide that a global object depends on a cleared section variable, we just consider it ill-scoped and do not allow its use under this context, be it a constant, hint, notation or instance/cs declaration.

2017-07-20 14:15 UTC, herbelin commented
@silene: A map, yes, probably to get better message in case of renaming. The `section_context` can probably be removed if we want to address [#4092](https://coq.inria.fr/bugs/show_bug.cgi?id=4092) and [#2215](https://coq.inria.fr/bugs/show_bug.cgi?id=2215) by the negative.

@ejgallego: I don't see deprecating the section feature as realistic. They are pervasively used and convenient. If you are referring to keeping the list of section variables outside of the kernel and to do the discharge on the fly at definition time, this would have some benefit such as the ability to instantiate a constant defined in a section with arbitrary arguments already before the section is closed, but this would not solve the `clear H; intro H` problem since you would still have to identify how goal variables relates to section variables.

@gares: Being pessimistic would be to believe that we cannot succeed in getting what we aim. On the contrary, collecting the issues to check is very constructive!

For some reason `Notation H1 := H` does not already work (even without a `clear`). A similar notation referring indirectly to `H` already gives `H1 depends on the variable H which is not declared in the context`, so this would just be the same, but without the `intro` capture bug. A coercion referring to a variable gives `No such section variable or assumption`. This means that it does not check that it refers to the proper section variable. Then, this would have to be checked, and besides that, it will behave the same but without the `intro` capture bug.

These last examples are actually what pushes me to give a proper name distinct from `Var H` to section variables (maybe `Const S.H`, I'm not fully clear yet about it). We do have global objects referring to section variables (hints, notations, coercions, canonical structures, ...) and we do need to be able to refer to these section variables even in goals where they are renamed or cleared.

2017-07-20 14:23 UTC, ejgallego commented
> @ejgallego: I don't see deprecating the section feature as realistic. They are pervasively used and convenient.

OTOH I think the current design has important problems, and I am not positive they can be really solved. So maybe instead of patching a non-optimal design, I wonder if we should aim to just live with the current state of section and focus dev efforts on providing a new "Contexts" feature that doesn't suffer from the problems sections do.

2017-07-20 14:58 UTC, herbelin commented
A "Context" feature? What do you have in mind?

2017-07-20 15:18 UTC, herbelin commented
Ah, I guess you mean something like `Context Γ := (A:Type) (a a':A)`, then `Lemma f Γ : a = a'`??

But, what would you do with existing developments which typically do `Section A. Variable A:Type. Variables a a' a'':A. Lemma refl : a = a. Lemma sym : a = a' -> a' = a. Lemma trans : a = a' -> a' = a'' -> a = a''.` etc. You would need 3 different contexts, or you would reintroduce a `Proof using` feature to extract subsets of contexts as we already have.

Or is the point to forbid notations, coercions, canonical structures, etc. referring to variables from contexts? But isn't the ability to bind notations, coercions, etc. to section variables precisely a bonus?

I would even go the other way round. I remember having wanted notations or implicit arguments for goal variables locally to a proof and I'm sure this makes sense for proofs involving big terms which we want to abbreviate locally.

2017-07-20 16:58 UTC, ejgallego commented
I mean a context that can be _partially_ fulfilled, in the sense of implicit arguments. Contexts are first-class so no need for proof using; for faster checking you would need a cache.

We had some discussion at the IM, the key point of the context is that the type is invariant from the proof, and indeed, I don't see why they should not support notations, etc...

2017-07-20 17:00 UTC, ejgallego commented
The key point for me is that once your types are proof-invariants, the rest of proof using can be done by Coq automatically and thus liberating the user of this burden.

2017-07-21 08:00 UTC, herbelin commented
@ejgallego: I'm now a bit confused. Are such "contexts" a direction that you'd like to explore now? Or that you would like that someone explore now? Or In the longer term?

I was not at the Implementor Meeting discussion. What were the conclusions? How would it combine with the existing? Or at least, how would the transition be made?

Shortly, is it worth that we think more about it right now? 

At the current time, do you object to resolving the problems of sections as they are? And how do you welcome the idea that we keep a handle on section variables to be able to refer to them even after them being cleared (if not using `Proof using`?). Knowing that this is in no way an obstacle to explore other directions in the future.

2017-07-21 11:49 UTC, ejgallego commented
@herbelin what I wonder is if the problems with sections are really solvable; would they be, of course we should solve them. But given the design based on "cooking" it is not clear to me how to solve some of the critical problems they have.

"contexts" are something I have been thinking of since a while and I'd like to explore them more some day. The discussion was informal and no clear conclusion was reached other than "we should think more about this". I think both systems would be different and would have to live together for while.

> Shortly, is it worth that we think more about it right now?

Hard to say; are the problems with sections solvable? Would we ever be able to get rid of "cooking". What are the semantics of Section Variables?

Regarding your question about the handle I am not sure I understand the intended semantics of clearing a section variable well; I tend to think of clear more as putting hypotheses in a "purgatory" were ltac won't see them than really removing them. It seems that such mechanism should live at the proof tactic level but all in all looks like a very complicated problem where talking is easy, coding not so much.

2017-07-21 14:42 UTC, herbelin commented
> Would we ever be able to get rid of "cooking". 

If we still want to interpret text such as `Section A. Variable n:nat. Definition p:=n=n. ... End A`, cooking shall have to be done at a time or another. 

Abstraction over section variables and re-instantiation of previous constants of the section can be done at the end of the section as it is now.

Or abstraction can be done at definition time of constants in a section and re-instantiation at use time of previous constants of the section.

The former has the advantage to me of "intuitiveness" (we see what we mean). The second has the advantage that we can dynamically reuse a constant of the section with different arguments than the current set of section variables, with "intuitiveness" maybe still simulable with a smart use of implicit arguments.

Wrt kernel isolation, the current implementation is lame. Part of it is in the kernel and the other part outside. It should either be totally outside (we don't push section variables in the kernel and push only discharged constants) or totally inside (the kernel provides an operation to abstract a global environment over a given set of global definitions, as it is done in [chapter 4](https://coq.inria.fr/refman/Reference-Manual006.html#sec210) of the reference manual, where section variables are just seen as ordinary global declarations).

Now, if your point is to replace the current user API of sections, that's another question.

> What are the semantics of Section Variables?

I don't know what kind of semantics you expect. Personally, I tend to see them as locally global declarations which are additionally replicated in the initial state of goals. But we can also see them as an implicit context of variables to be shared by the forthcoming definitions.

Currently, they share with global declarations that notations, hints, coercions, etc. can be attached to them, but if we generalize the ability to declare notations, hints, coercions, etc. to arbitrary goal variables, then it does not matter so much any more whether we consider them as global or local.

> what I wonder is if the problems with sections are really solvable

If the problems are the `clear; intro` bug and the lame cooking, I would say yes. What other specific problems do we have?

> I tend to think of clear more as putting hypotheses in a "purgatory" were ltac won't see them than really removing them.

I'm quite ready to share this view. The question is a bit similar to how to refer to the different former values of a variable in say Hoare's logic: we have a `H:P(n)`, we do induction and get `H:P(n')`, the old `H` is still there somewhere in the context of the proof term and the question seems to me to be a lot about how to refer to it, after its name has been hidden by a new `H`.

2017-07-21 18:26 UTC, ejgallego commented
Hi @herbelin thanks for your comments:

> If we still want to interpret text such as Section A. Variable n:nat. Definition p:=n=n. ... End A, cooking shall have to be done at a time or another.

I don't see why; `p` should have type `p : Ctx A [:= {n : nat}...] n = n` where `n` may be optional. As you point out, this is very related to implicit arguments. In fact, even the printing problems could be solved if we treated implicits as "lazy".

> Abstraction over section variables and re-instantiation of previous constants of the section can be done at the end of the section as it is now.
>
> Or abstraction can be done at definition time of constants in a section and re-instantiation at use time of previous constants of the section.

Indeed, but the point I try to make is that abstraction shouldn't depend on the contents of an opaque proof.

>> What are the semantics of Section Variables?
> I don't know what kind of semantics you expect. Personally, I tend to see them as locally global declarations which are additionally replicated in the initial state of goals. But we can also see them as an implicit context of variables to be shared by the forthcoming definitions.

I would expect a semantics as in a typical λ-calculus typing taking into account opaqueness. Now, typing is a bit weird when proofs are not available, but maybe I am reading wrong chapter 4. Is the interaction between the opaque proofs system the global declarations written down somewhere?

> If the problems are the clear; intro bug and the lame cooking, I would say yes. What other specific problems do we have?

Sorry if I got lost on this, what is the plan to remove cooking?

>> I tend to think of clear more as putting hypotheses in a "purgatory" were ltac won't see them than really removing them.
> I'm quite ready to share this view. The question is a bit similar to how to refer to the different former values of a variable in say Hoare's logic: we have a H:P(n), we do induction and get H:P(n'), the old H is still there somewhere in the context of the proof term and the question seems to me to be a lot about how to refer to it, after its name has been hidden by a new H.

Indeed, context bracketing may need some kind of namespacing and it is not trivial to design so.

2017-07-21 19:52 UTC, herbelin commented
> Is the interaction between the opaque proofs system the global declarations written down somewhere?

The documentation on `Qed` is indeed pretty scarce. In [Section 1.3.5, Remark 4](https://coq.inria.fr/refman/Reference-Manual003.html#Vernacular), one can read "Proofs ended by Qed are declared opaque. Their content cannot be unfolded". One could certainly say more.

Or are you talking specifically about opaque proofs in section?

> Sorry if I got lost on this, what is the plan to remove cooking?

What do you call cooking exactly? If one defines cooking to be the processs of abstraction and generalization done by the section mechanism, independently of the question of whether it is done on the fly or at the end of a section, removing cooking means removing the section mechanism. Is that what you mean? If yes, I don't have an answer to your question. Is there any demand to remove the section mechanism?

> I don't see why; p should have type p : Ctx A [:= {n : nat}...] n = n where n may be optional. As you point out, this is very related to implicit arguments. In fact, even the printing problems could be solved if we treated implicits as "lazy".

What denotes your `p : Ctx A [:= {n : nat}...] n = n`? Is it a new kernel construction for abstracting over contexts? Is it an intermediate model to implement `Section` on top of it? Is it a new user-level 
syntax for replacing sections?

> Indeed, but the point I try to make is that abstraction shouldn't depend on the contents of an opaque proof.

Do you mean what `Proof using` is exactly designed for?

2017-07-21 22:08 UTC, ejgallego commented
Hi Hugo, thanks for the comments (and patience),

> Or are you talking specifically about opaque proofs in section?

Indeed I was thinking of opaque proofs and sections, and how do those
interact. Think about it, if we want to process files in parallel, but
the type of lemmas depends on the proof, we have a bad situation.

In a sense, I think it is "morally" wrong that a proof changes the
type of an statement. I can live with universes checked later, but
with different types, that's a different story.

> Do you mean what Proof using is exactly designed for?

I am sorry but `Proof using` just doesn't cut it for me. Apart from
being a pain to the user, think of large proofs, for example in
mathematical contents, this app

Maybe I am naive but I would expect `Proof using` to be taken care of
by Coq, not to have to add expensive manual annotations.

>> Sorry if I got lost on this, what is the plan to remove cooking?
>
> What do you call cooking exactly? If one defines cooking to be the processs of abstraction and generalization done by the section mechanism, independently of the question of whether it is done on the fly or at the end of a section, removing cooking means removing the section mechanism. Is that what you mean? If yes, I don't have an answer to your question.

I call "cooking" to that process indeed. And indeed I'd like something
with similar functionality to sections (declare a "proof ambient") but that don't need to recheck every computed proof.

> Is there any demand to remove the section mechanism?

Apart from the problems with changing types and lack of parallel
processing, some users have reported large Section closing times. Also, cooking grows the trusted base.

> What denotes your p : Ctx A [:= {n : nat}...] n = n? Is it a new kernel construction for abstracting over contexts? Is it an intermediate model to implement Section on top of it? Is it a new user-level
> syntax for replacing sections?

Indeed you could think of `Ctx A` as a set of optional implicit
arguments, that indeed is known by the kernel. So the tradeoff here
would be to remove sections and cooking and instead replace them by
the kernel having knowledge of non-fulfilled constants.

So when the kernel checks an implicit `hyp : A` which doesn't have a
body yet, it must mark the proof as checked but with a pending context
of `{hyp}`. Then users can provide it or not, otherwise when you do
print assumptions it should say that a part of the context is
unfulfilled. This is really implicit arguments if you want to think of
it.

Something I'd like thou is that all the management is automatic. For
example, if I have a context Γ' ⊇ Γ in scope, then Γ is automatically
fulfilled. The tricky part is that you need to get back from proof
workers the information on the part of the context that needs to be
fullfilled for each lemma (and saved in the vo file), but they user should never know.

Some time ago we discussed a bit with @Zimmi48 and @ggonthier but I am not sure I understood
all the details, but it was the lack of parallel processing and the
annoyance of `Proof using` that got me interested on this.

2017-07-22 09:09 UTC, herbelin commented
> Indeed I was thinking of opaque proofs and sections, and how do those interact. Think about it, if we want to process files in parallel, but the type of lemmas depends on the proof, we have a bad situation.

I agree that `Qed` of a `Let` has an ambiguous semantics, as reported by @ppedrot.
- It behaves as an opaque declaration when used in another proof of the section.
- It currently does not but should morally behave as an opaque declaration when used in a definition or statement of the section (the absence of an opaque flag in the `name_context`, as you mentioned)
- I don't see how it can behave in another way than expanded at discharge time. We would need a notion of opaque `let in` in `constr`/`Constr.t` to do otherwise (but why not, after all, this would reflect in the term level what exists in the global context). In particular, as it is now, it means from the point of view of parallel evaluation that a `Qed` in a section should be seen as a `Defined` from the point of view of every command occurring after the end of the section.

> I am sorry but Proof using just doesn't cut it for me. Apart from being a pain to the user, think of large proofs, for example in mathematical contents, this app ... Maybe I am naive but I would expect Proof using to be taken care of by Coq, not to have to add expensive manual annotations.

I'm missing something there. I thought `Proof using` was precisely the way to support parallel evaluation of `Qed` proofs in sections. I never heard someone telling it was a pain until now. What's the problems with it? (Moreover, it is not mandatory, so I don't understand how it could be a pain, since it can only be an optional bonus.)

> some users have reported large Section closing times.

There may be efficiency issues, but probably not in the cooking of global declarations which is basically linear in the size of expressions. Inefficiency can come from re-computing implicit arguments for instance.

> Also, cooking grows the trusted base.

That's right.

> Indeed you could think of Ctx A as a set of optional implicit arguments, that indeed is known by the kernel.

The point of view is different (dependence in section variables vs dependence in implicit arguments) but, technically, isn't it the same as what already exists with the `const_hyps` and `mind_hyps` fields, inclusion being provided by `check_hyps_inclusion`?

2017-08-29 12:21 UTC, herbelin commented
Hi, I remain unclear about how to make progresses on section variables (and, incidentally, on this PR). I did not re-read carefully all comments but the general idea seems to be well-represented by this comment from @silene: « the intuitive behavior is to clear these variables. It is just that, until all the bugs related to clearing section variables are fixed, we should refrain from automatically clearing section variables by default. »

So, how to step further and to eventually address the clearing section variables bugs, one way or another? Shall we think at a different model, e.g. based on contexts? With which transition strategy?

Shall we first move sections out of the kernel with on-the-fly generalization of the constants? But with which semantics for clearing a section variable? Forbidden? Allowed, but cutting all dependencies of the cleared variables in global objects?

More generally, is the dependency of notations, implicit arguments, hints, etc. in section variables a problem, or, on the opposite, we would like to eventually associate notations, or implicit arguments, etc. also to goal variables (think e.g. at a local polymorphic function which we just `pose`d in the context and to which we would like to set implicit arguments and define an infix notation).

Depending on what we want, different models can be considered. For instance, we could invent a systematic way to refer to goal variables which were cleared (since after all, they are still there somewhere in the spine of lambdas of the current proof being constructed). Or, to control the effect of a `clear`, we could imagine that we maintain a table telling for each goal variable in which other objects it depends in.

So, shortly, it seems to me that it is first a lot about what user model we'd like to eventually propose, and that once the model is clear the technical constraints will resolve by themselves.

Any comments?

2018-04-24 14:39 UTC, herbelin commented
> This PR is trivial and not going to be merged any time soon. Can we close it in favor of discussion at #6254?

I'm a bit lost in the discussions and in who is planning to do what and with which ETA, but I'd prefer to keep this open.

2018-07-25 14:41 UTC, ppedrot commented
@herbelin I agree with @Zimmi48 that we should close this PR for the time being. It relies on bug fixes that are not happening any time soon, and the current patch is trivial enough that there is no point in leaving this PR opened around. Are you more convinced?

2018-07-25 16:13 UTC, herbelin commented
> Are you more convinced?

If I understand correctly your point, you'd like to reduce the number of PRs which have no clear agenda. But then, where to indicate that the issue addressed by this PR shall still have to be addressed at some time, and that a PR going in this direction already exists?

Alternatively, if I tell you that I can allocate time to globally address issues with sections in Fall, would you find it ok to leave the PR open?

2018-07-25 16:19 UTC, mattam82 commented
@herbelin I'd suggest using a Project to gather those closed PRs in a common space.

2018-07-25 16:39 UTC, herbelin commented
> I'd suggest using a Project to gather those closed PRs in a common space.

I have no experience with projects, but ok to go this way. May I ask for help for doing it or for telling how to do it?

2018-07-25 16:43 UTC, ppedrot commented
> Alternatively, if I tell you that I can allocate time to globally address issues with sections in Fall, would you find it ok to leave the PR open?

@herbelin not that I underestimate your skills, but sections are well-known for being a rabbit hole from which nobody came back alive or mentally sane (let alone having fixed the corresponding bugs). Any schedule on that matter that is not on the scale of years is most likely unrealistic.

2018-07-25 16:54 UTC, herbelin commented
> Any schedule on that matter that is not on the scale of years is most likely unrealistic.

Not sure I agree... My analysis is rather that we lacked a consensus on what to do, and this is what took years.

2018-07-25 16:55 UTC, ppedrot commented
@herbelin I did not claim that all of the issues were technical :)

2018-07-25 16:59 UTC, herbelin commented
> I did not claim that all of the issues were technical :)

Let's not be pessimistic...

2018-07-25 17:52 UTC, Zimmi48 commented
> I have no experience with projects, but ok to go this way. May I ask for help for doing it or for telling how to do it?

It is really easy to use but if you need help I can give you tips.

2018-07-25 18:15 UTC, herbelin commented
You mean that I can just take the responsibility of clicking on `New project` in the `Project` tab? Then, if it is clear that noone shall object, I can try to do that.

2018-07-25 18:33 UTC, Zimmi48 commented
> You mean that I can just take the responsibility of clicking on New project in the Project tab?

Oh yes, feel free to take on this responsibility. And if you don't like it in the end, you can even delete it afterwards. GitHub will propose you a standard automation To Do / In Progress / Done. This is generally good enough to start with.

2018-07-29 08:55 UTC, herbelin commented
I opened a [sections/discharge](https://github.com/coq/coq/projects/28) project and add this PR to the project. The project is rudimentary yet (too short in time to do better now) but hopefully it will help to centralize things.

Now closing this one until some progress is made.

2018-07-29 08:55 UTC, closed without merging