[Docker] Update OCaml (4.07.1) and camlp5 (7.07-almost)
coq/coq pull request #8868
Opened 2018-10-31 08:07 UTC by vbgl

I’m hitting an OCaml compiler bug in CI. The issues seems unique to 4.07.0 (i.e., not there neither with 4.06.1 nor with 4.07.1), hence this update.

2018-10-31 08:57 UTC, silene commented
> I’m hitting an OCaml compiler bug in CI.

Is it due to a specific PR? (Just so that I keep track that I need to regenerate the Docker image for 8.9 if I backport it.)

2018-10-31 08:59 UTC, vbgl commented
Thanks Guillaume. This is for PR #6914. I believe it is not going to be back-ported to 8.9.

2018-10-31 09:10 UTC, ejgallego reviewed
That's fine, but please add details about the compiler bug you are facing. That could potentially impact users so we need to document it.

2018-10-31 12:50 UTC, ejgallego commented
@vbgl , note that a cool trick that I didn't try but in theory now possible is to compose the build of the OCaml compiler itself with the Coq build [using Dune for both]

That should allow you to perform a painless bisect on OCaml.

2018-10-31 13:02 UTC, vbgl commented
Said bug is unrelated to Coq: it’s valid OCaml code generated by Coq extraction.

2018-11-05 02:17 UTC, ejgallego commented
> Said bug is unrelated to Coq: it’s valid OCaml code generated by Coq extraction.

Even so I'd like to properly document the bug in the log please. The fact that is not a Coq bug doesn't mean it won't affect Coq users [such as the intel CPU bug did]

2018-11-05 02:18 UTC, ejgallego commented
Also, I've realized the commits do look wrong, submitting a new review.

2018-11-05 02:19 UTC, ejgallego requested changes
Please:
- squash the commits: the imagine with 4.07.1 won't build due to wrong camlp5 version,
- update the `dev/dune-workspace.all` file,
- document in the commit log the OCaml bug you have found and how it affected Coq.

2018-11-07 08:58 UTC, vbgl commented
Emilio, I think I addressed your comments.

Did you expect more detail concerning the OCaml bug? It’s a bit tricky to minimize and report.

2018-11-07 11:07 UTC, ejgallego approved these changes
That's more than enough IMHO @vbgl , thanks! The idea is that if someone else finds the bug we have somehow a trace of it in the log.

Merging as soon as CI is OK.

2018-11-07 11:19 UTC, merged