Stronger kernel types
coq/coq pull request #888
Opened 2017-07-17 10:51 UTC by ppedrot

We enforce a few properties in the kernel by relying on stronger typing invariants, as well as using dedicated types to represent data. Namely:

- Universes in constant entries now use a ADT similar to the one of inductive types.
- Result of entry inference uses a dedicated record type.
- Entries now enforce the fact they contain side-effects by typing, thanks to the use of simple GADTs. This has been used track them and get rid of a horrible hack in the Declare module that was using mutability to work around the API.

2017-07-17 11:42 UTC, mattam82 commented
LGTM, it follows the move to use more explicit types in general, and it's nice to remove the mutable field of cst_decl for sure.

2017-07-17 12:25 UTC, SkySkimmer commented
Maybe add the last line of #783 to 80fba6c ?

2017-07-17 12:42 UTC, ppedrot commented
@SkySkimmer Yep, you're right, I actually saw it and forgot about it. Or instead we can merge #783 first and remove the top commit of this PR.

2017-07-17 13:10 UTC, SkySkimmer commented
@ppedrot got it merged, which is probably what the conflict is.

2017-07-17 14:27 UTC, ppedrot commented
Rebased on @SkySkimmer's patch.

2017-07-18 16:42 UTC, ppedrot commented
I've added a more precise type for inlined entries out of the kernel, that allows to trivially get rid of assertions in upper layers.

2017-07-19 09:06 UTC, gares requested changes
Could you please write comments that help reviewing the changes?

> a horrible hack in the Declare module that was using mutability to work around the API

which one?

2017-07-19 09:06 UTC, gares commented on API/API.ml
> -                                   const_entry_polymorphic : bool;
This change is gratuitous, the only 2 uses of this field do turn it into a boolean (dropping the universes) or into a pair (the boolean and the universes).  I quite don't get what you gain.

2017-07-19 09:51 UTC, ppedrot commented on API/API.ml
> -                                   const_entry_polymorphic : bool;
Indeed, the goal is even to get nothing in the monomorphic case, and an abstract context in the polymorphic case.

2017-07-19 09:52 UTC, ppedrot commented on kernel/term_typing.ml
> +          | SideEffects trust ->
Well, that was to minimize the diff so that one can recognize easily the previous code. But if you want it gone, I can indeed do that.

2017-07-19 09:54 UTC, ppedrot commented
@gares This:

```
type constant_obj = {
  cst_decl : global_declaration;
  cst_hyps : Dischargedhypsmap.discharged_hyps;
  cst_kind : logical_kind;
  cst_locl : bool;
  mutable cst_exported : Safe_typing.exported_private_constant list;
  (* mutable: to avoid change the libobject API, since cache_function
   * does not return an updated object *)
  mutable cst_was_seff : bool
}
```

One of the invariant we try to enforce is that there is no mutable structure in the libstack, and this object violates it. Normally, this shouldn't matter, but if we really aim for a crazily parallel code, it may.

2017-07-19 10:09 UTC, ppedrot commented
@gares Which part would you like to see detailed? The changes are rather simple, and the commit comments are pretty much self-explanatory...

2017-07-19 12:06 UTC, ppedrot commented
@gares Implemented you suggestion about aliasing.

2017-07-20 10:08 UTC, ppedrot commented
@gares Ping?

2017-07-20 12:38 UTC, maximedenes commented
> One of the invariant we try to enforce is that there is no mutable structure in the libstack, and this object violates it.

If not already done, could you add a comment in libstack making this invariant explicit? Thanks!

2017-07-20 12:42 UTC, ppedrot commented
@maximedenes In this PR? It is semantically unrelated. Should I open another PR and mark it as documentation?

2017-07-20 12:47 UTC, maximedenes commented
Yeah maybe another PR, I'll merge it immediately.

2017-07-20 13:20 UTC, gares approved these changes

2017-07-20 13:26 UTC, ppedrot commented
Rebased on trunk, ready to merge.

2017-07-20 13:28 UTC, ppedrot commented
On the good trunk...

2017-07-28 16:23 UTC, maximedenes approved these changes
Had a quick look, seems very good!

2017-07-28 22:55 UTC, merged