[dune] Add flag to drop dependency of `.vo` files on coqtop.
coq/coq pull request #8916
Opened 2018-11-06 12:51 UTC by ejgallego

In #8900 there was a lot of discussion about having a fast-path that
skips `.vo` integrity checks by allowing to rebuild `coqtop` but not
the `.vo` that depend on it.

We thus add a flag for such adventurous users so they can manually
control the build. Note that using this may create all kind of havoc,
for example if you haven't build `coqtop` Dune could well pick the one
in your PATH, etc...

This can be improved, but in the end it will put a lot of burden on
the user to check for consistency.

2018-11-06 14:05 UTC, ejgallego commented
@rgrinberg also suggested that `coqtop` could actually exit quickly in the fast-path mode.

That seems like an interesting alternative.

2018-11-06 14:10 UTC, Zimmi48 requested changes
Interesting trick but this requires some documentation somewhere in `dev/doc`. In particular, the idea is that people will change the hard-coded value of `skip_vo_integrity`. I think it's a good way to highlight that this is a debugging only setting.

2018-11-06 14:11 UTC, Zimmi48 commented
>coqtop could actually exit quickly in the fast-path mode.

Not sure what that means.

2018-11-06 15:00 UTC, ejgallego commented
> Not sure what that means.

That would mean that `coqc -skip foo.v` will do `exit 0` if `foo.vo` does exist. Thus, you would reach the problematic `.vo` pretty quick.

2018-11-06 15:05 UTC, ejgallego commented
Ok, bit of info added. Still this flag is not very useful until the patch that makes `coq_dune` work with 3rd party libs arrives, but that should happen soon.

2018-11-06 15:39 UTC, Zimmi48 approved these changes
I'll leave some time to comment. It seems that @gares is not perfectly happy with this solution.

2018-11-06 15:40 UTC, ejgallego commented on tools/coq_dune.ml
> +let skip_vo_integrity = false
It's a bit more handy than that as you just tweak the flags and the "regular" build target will take care of everything.

This should turn into a proper flag / profile soon, when coq dune understands dune files for coq, but that patch is still not ready.

2018-11-06 15:43 UTC, ejgallego commented
I am ok waiting to merge this until coq_dune gets support for flags / build profiles. Note that this is a feature that the make system doesn't offer as far as I understand so I am not sure how well it will work in practice.

2018-11-06 15:45 UTC, ejgallego commented
Note that Dune devs where far from entusiashtic with this kind of hack, likewise I feel that it will create more pain than gain but hey, why not?

2018-11-06 15:54 UTC, gares commented
I think that having to edit a source file in order to activate a flag is not an option.

2018-11-06 16:57 UTC, ejgallego commented
This is too messy to work well, it seems `cutoff` points may be implemented directly in Dune thus this wouldn't be necessary.

2018-11-06 19:29 UTC, SkySkimmer commented
>This is too messy to work well, it seems cutoff points may be implemented directly in Dune thus this wouldn't be necessary.

What kind of ETA can we expect?
In fact where do you get dune news?

2018-11-06 20:58 UTC, ejgallego commented
> What kind of ETA can we expect?

I don't know, this is low priority for me personally as the same trick than the one used currently in make can be made to work in Dune.

> In fact where do you get dune news?

There are channels in OCamllab's Slack and Discord's OCaml.

2019-02-12 02:05 UTC, ejgallego commented
This should be implemented in Dune itself.

2019-02-12 02:05 UTC, closed without merging