Bump camlp5 minimal version and use its safe API.
coq/coq pull request #8923
Opened 2018-11-06 14:50 UTC by ppedrot

This PR makes the Coq parsing API rely on the type-safe camlp5 API, that was first introduced in camlp5 7.06.

This requires first to bump up the minimal camlp5 version. I did that in the opam file but I am pretty sure the code base is littered with version checks I don't know about. Also not sure about the process of bumping up camlp5 versions, so let's ask here.

2018-11-06 14:55 UTC, SkySkimmer commented
configure is still thinking that camlp5 6.06 is enough.
INSTALL should be updated.
I think that's it.

2018-11-06 15:06 UTC, ejgallego commented
The dockerfile too

2018-11-06 16:17 UTC, ejgallego commented
I am OK with the dependency bump for 8.10, this should be ok for most users. Debian / Ubuntu have basically abandoned their Coq packages so I don't think that's a problem.

2018-11-06 16:47 UTC, ejgallego requested changes
Fix:
- configure
- docker
- INSTALL
- travis
- windows?

2018-11-07 10:14 UTC, Zimmi48 commented
Windows IIRC is using the edge compiler, not the minimum version.

2018-11-07 10:36 UTC, ppedrot commented
I think I have updated the relevant parts. Note that the current master configure is completely outdated w.r.t. the supported camlp5 version, and Travis seems to be already using 7.06.

2018-11-07 10:50 UTC, ppedrot commented
It seems that the Gitlab environment is still out of date. I guess I have to push a docker instance myself, but I have no idea on how to do that (and I'm not too fond of having to install the Docker *usine-à-gaz* on my own computer). Anybody more skilled around?

2018-11-07 10:52 UTC, ejgallego commented
It is fairly well-documented in the README @ppedrot , you need to raise the image version and the request a build in the Gitlab web interface with `SKIP_DOCKER` set to `foo`.

2018-11-07 10:53 UTC, ejgallego commented
Basically grep for `CACHEKEY`, raise it, and the rest we can take care of, gitlab will build the Docker image.

2018-11-07 11:01 UTC, Zimmi48 approved these changes
Trivially OK for my part.

2018-11-07 11:58 UTC, SkySkimmer commented
>windows?

Windows says 
>  if build_prep https://github.com/camlp5/camlp5/archive rel706 tar.gz 1 camlp5-rel706; then

so should be OK.

2018-11-07 12:06 UTC, ejgallego commented
On a more general note about camlp5, we are ready to drop the dependency as soon as we do the porting of the CI contribs. I am not sure it is worth keeping the infrastructure in 8.10, given what our compat policy for plugins is, and given that I am implementing state handling in coqpp following the path we did on attributes, so commands have to declare what state they read/modify.

2018-11-07 12:08 UTC, ppedrot commented
@ejgallego I submitted a few PRs for the CI developments, but the least we can say is that maintainers (probably us, most of the time) are not quite reactive. Also, before removing camlp5 entirely, we should first provide the camlp5 grammar.cma macro as a separate library depending on camlp5.

2018-11-07 12:12 UTC, SkySkimmer commented
Manual pipeline running.

2018-11-07 12:37 UTC, Zimmi48 commented
@ppedrot You only changed the CACHEKEY in the GitLab config and not in the Dockerfile! Pipeline cancelled.

2018-11-07 12:40 UTC, SkySkimmer commented
The one in the dockerfile doesn't actually do anything, I think we should just remove it. @ejgallego WDYT?

2018-11-07 12:59 UTC, ejgallego commented
> The one in the dockerfile doesn't actually do anything, I think we should just remove it. @ejgallego WDYT?

We discussed implementing a check. IMHO it is important to have this information as we have to keep consistency manually. It is fairly easy to forget which version the Dockerfile is.

2018-11-07 13:00 UTC, ejgallego commented
> but the least we can say is that maintainers (probably us, most of the time) are not quite reactive.

What do you mean? AFAICT your PRs got merged, right?

> Also, before removing camlp5 entirely, we should first provide the camlp5 grammar.cma macro as a separate library depending on camlp5.

Why do we need that? It is already a separate library depending on camlp5 AFAICT.

2018-11-07 13:01 UTC, ejgallego approved these changes
Looks good to me.

2018-11-07 13:02 UTC, ppedrot commented
> What do you mean? AFAICT your PRs got merged, right?

Not all of them yet, and I had to ping for this to happen.

> Why do we need that? It is already a separate library depending on camlp5 AFAICT.

Hum, how do we distribute it to users requiring the legacy macro?

2018-11-07 13:05 UTC, ejgallego commented
> Not all of them yet, and I had to ping for this to happen.

If CI maintainers are not reasonably reactive we can take some action indeed. Let us know if someone is unreasonably slow.

> Hum, how do we distribute it to users requiring the legacy macro?

IMHO we should just drop support for `.ml4` files. Porting is very easy, and anyways for ml developments intra-version compatibility is just not there. Also, I am preparing a `coqpp` patch that will add systematic handling of state inspired in the way we handle attributes; this will surely mean `.ml4` won't be able to function anymore.

2018-11-07 20:30 UTC, merged

2018-11-07 23:14 UTC, JasonGross commented
Please revert this change.  I don't want to package camlp5 myself, and there is *no* Ubuntu version that supports this version of OCaml (the only supported version is 7.01, in cosmic, as far as I can tell from https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=Camlp5&searchon=names).  So this change breaks the usage of the apt packages on Travis for HoTT, fiat, fiat-crypto, etc.

Also, I'd prefer to have more than just one day to notice and comment on PRs that bump version dependencies in the future.

2018-11-07 23:15 UTC, JasonGross commented
(Btw, if this is not reverted soon, I'm going to have to stop testing fiat-crypto against Coq master, because it's built in stages due to Travis timeouts and the failure of any one version of Coq in a state will prevent the other stages from running.)

2018-11-08 09:55 UTC, ppedrot commented
Let's revert indeed, I was not expecting this PR to get merged so quickly, and was thinking there would have been a little bit of discussion precisely to avoid this kind of situation.

2018-11-19 02:19 UTC, ejgallego commented
@ppedrot you should reopen this PR.

2018-11-19 06:18 UTC, ppedrot commented
@ejgallego I'm waiting for #8945 to go in, I don't like having chains of dependencies in my PRs.