Remove convoluted error logic from obligations
coq/coq pull request #8981
Opened 2018-11-12 23:13 UTC by maximedenes

I hit a case where the error is silently dropped, leading to an
inconsistent state.

This logic seems to be a conscious choice, introduce for example by https://github.com/coq/coq/commit/07bd9c28f37b9ec390e5e3dcacdfd8183056be88 but I don't understand it. So I'm not sure if removing it is the right fix.

2018-11-12 23:21 UTC, ejgallego commented
@maximedenes I tried to tweak this exact same code a few weeks ago; the problem we are facing here is one of callback with possibly the wrong printing (that is to say, notations, etc...) state; I didn't manage to understand the code enough as to move forward as the flow in this part is a very tricky jump-game from the stm to proof_terminators.

2018-11-13 00:16 UTC, maximedenes commented
I restricted the patch to what I needed. There are other suspicious pieces of error logic in obligations, though.

2018-11-13 00:37 UTC, ejgallego commented on vernac/obligations.ml
> +    | e -> None (* FIXME really ? *)
I guess the refactoring to option is fine, however I think you should strengthen the semantics here [CI permitting] and either:

- turn the `tclCOMPLETE` into a real exception.
- or even better remote `tclCOMPLETE` at all, it should be close_proof the one in charge of owning this logic. Let me have indeed a go at it.

2018-11-13 11:55 UTC, ejgallego requested changes
Can you tell mor e why this change helps and what "case" are you getting this error?

I am not sure I can understand how your change does make a semantic difference.

2018-11-13 12:05 UTC, maximedenes commented
> I am not sure I can understand how your change does make a semantic difference.

Before this patch, the code incorrectly catches any exception raised by `declare_obligation` and treat it as if it had been raised by the tactic execution. This patch solves it by restricting the scope of the `try` block. I think it is a sound change. One can go further in the clean-up, but I'd like to get this in.

2018-11-13 12:11 UTC, ejgallego commented
> One can go further in the clean-up, but I'd like to get this in.

Ok, you should amend the PR title / description, I didn't realize the commit had the right message.

I can assign this PR if you want.

Out of curiosity, what kind of exceptions does `declare_obligation` raise?

2018-11-13 12:11 UTC, ejgallego approved these changes

2018-11-13 12:13 UTC, maximedenes commented
> Ok, you should amend the PR title / description, I didn't realize the commit had the right message.

Indeed, I forgot to update it when I changed the content.

> 
> I can assign this PR if you want.
> 
> Out of curiosity, what kind of exceptions does `declare_obligation` raise?

Well, any call to a user error there will show the problem. The error will not appear and put the obligations system in an inconsistent state.

In my case, `declare_obligation` was emitting a warning when it was declaring a hint database. With `-w +all`, the warning became an error, hence the exception...

2018-11-13 12:17 UTC, maximedenes commented
For the record, I think we should scan all unrestricted exceptions catching in the codebase. After loosing an hour on this one, I lost another hour because of https://github.com/coq/coq/blob/0b816e4df10d961cce082894f5e4087dc1c95f01/pretyping/pretyping.ml#L268

2018-11-13 12:18 UTC, maximedenes commented
Are the failures real?

2018-11-13 12:19 UTC, ejgallego commented
> In my case, `declare_obligation` was emitting a warning when it was declaring a hint database. With `-w +all`, the warning became an error, hence the exception...

Ah, I finally understand; this is what I was missing.

2018-11-13 12:20 UTC, ejgallego commented
> Are the failures real?

Spurious TTBOMK

2018-11-14 06:59 UTC, maximedenes commented
@mattam82 can you be the assignee? Thanks!

2018-11-14 10:00 UTC, gares approved these changes
but I've no idea what the code was trying to do

2018-11-14 10:58 UTC, mattam82 commented
Fine with me. I think you analyzed the problem right, it’s about printing the error in the right global state, but indeed the catchall is too strong. I guess I didn’t know which exceptions should be fatal for Solve Obligations and which shouldn’t be. In retrospect, I think only the ones of complete / control_only_guard should be catched. Or we could use give_up and force the user to explicitly add an `|| give_up` tactic to signal that the tactic given might not solve all obligations.

2018-11-14 12:42 UTC, ejgallego commented
@mattam82 see also #8982 where indeed a stronger restriction is implemented for Solve Obligations.

2018-11-14 13:02 UTC, maximedenes commented
> @mattam82 can you be the assignee? Thanks!

ping

2018-11-17 18:12 UTC, ppedrot commented
Following the discussion in #8982, let's close this PR.

2018-11-17 18:12 UTC, closed without merging