Fix signals_are_pending linking error with ocaml trunk (4.08)
coq/coq pull request #9260
Opened 2018-12-20 21:52 UTC by SkySkimmer

`signals_are_pending` got renamed into `signals_might_be_pending` in ocaml/ocaml@1c82c481a5b33987e05012be61893c03f59ef361

2018-12-20 21:57 UTC, SkySkimmer commented on dune
> +         -ccopt -Dcaml_signals_are_pending=caml_signals_might_be_pending)))
Not sure if this will actually work, I wanted to put a c_flags entry but that's not allowed (ocaml/dune#1124 / ocaml/dune#1073)

2018-12-20 21:57 UTC, SkySkimmer commented
If anyone knows a better way to do this, suggestions welcome.

2018-12-20 22:18 UTC, ejgallego requested changes
I don't like this. Either:
- have upstream update `caml/compatiblity.h` and include it,
- add a conditional preprocessing line to coq_interp.c mathching on any of the values defined in `caml/version.h`

2018-12-21 15:42 UTC, closed without merging

2018-12-21 16:38 UTC, ejgallego commented
What is the reason to close the PR?

2018-12-21 16:43 UTC, SkySkimmer commented
It looks like the ocaml change will be reverted.

2018-12-21 18:13 UTC, ejgallego commented
Thanks for the info!