Remove monomorphic/polymorphic distinction in the kernel
coq/coq pull request #9380
Opened 2019-01-22 18:12 UTC by SkySkimmer

We still have to track polymorphism outside the kernel for the following:
~~~coq
Polymorphic Inductive foo : Set := bar.
~~~
The universe of the predicate in `foo_rect` should be polymorphic. In current master this is done by imitating the polymorphism of the inductive. If we don't track polymorphism then there is no trace of having used `Polymorphic` (foo has no universes).
We could try passing the polymorphism attribute explicitly to scheme functions but that gets pretty heavy, see unfinished commit 24a59c4a262ab770e85e606dc5c8a3df147c143f
We could revert having to access the polymorphism option through an attribute, but that's kinda messy.
We could try just making all _rect universes polymorphic. If we just pass poly:true in schemes we get an assertion failure from https://github.com/SkySkimmer/coq/blob/bd96a3ff6e906f828530f3aa5f68a838dee533ec/kernel/term_typing.ml#L52 so I'm not sure how feasible it would be.

Some other places are calling is_polymorphic, they didn't have an issue with the implementation `= not (is_empty polymorphic_univs)` but I haven't reviewed them.

I put XXX/TODO in various places which need a look, I'll point them out through the github UI.

Backward compat seems fine (aside from the usual plugin breaking).

This probably introduces bugs when the ability to combine monomorphic and polymorphic universes is used, especially in sections. Accordingly I'm not sure if we want to do this.

2019-01-23 16:08 UTC, ppedrot requested changes
I really find this PR is going the wrong way. I don't have much time to comment, but I am leaving this change request here so that it doesn't get merged without a *serious* discussion.

2019-01-23 16:10 UTC, maximedenes commented
Maybe a good topic the WG, then? It looks very technical, so some live explanations would be welcome :)

2019-01-29 15:52 UTC, SkySkimmer commented on interp/declare.ml
> -      let () = Global.push_context_set (not poly) univs in
Why is this inverted from the usual?

2019-01-29 15:54 UTC, SkySkimmer commented on kernel/mod_typing.ml
> -              c, Reduction.infer_conv env' (Environ.universes env') c c'
Seems like this breaks the assumption that we only convert terms which have a common type.

2019-01-29 15:55 UTC, SkySkimmer commented on vernac/obligations.ml
>            Some (TermObl (it_mkLambda_or_LetIn_or_clean (mkApp (mkConst constant, args)) ctx))
Why do we branch on polymorphism here? @mattam82

2019-01-29 15:57 UTC, SkySkimmer commented
We probably want to work on detaching monomorphic universes from constants before doing this. I pointed out the XXX which may still have some interest aside from this PR.

2019-01-29 15:57 UTC, closed without merging

2019-01-29 15:58 UTC, JasonGross commented
> We could try just making all _rect universes polymorphic. If we just pass poly:true in schemes we get an assertion failure from 

This interacts badly with the fact that it's currently forbidden to mix monomorphic and polymorphic variables in sections.