Remove Keep objects
coq/coq pull request #9408
Opened 2019-01-25 15:36 UTC by maximedenes

This is a step towards simplifying the libobject API.

I'm not sure to grasp 100% of the subtleties of Keep vs Substitutive, but for the part
I understand, this change should be ok. Let's rely on testing.

2019-01-25 21:42 UTC, gares approved these changes
ssr changes are OK, for what that matters

2019-01-25 21:45 UTC, SkySkimmer commented on library/libobject.ml
> +  classify_function = (fun obj -> Dispose);
I'd prefer to make this anomaly "$s isn't classified" or some such thing.

2019-01-27 16:32 UTC, ejgallego approved these changes
Parsing part is trivial.

2019-02-22 14:33 UTC, SkySkimmer requested changes
Please force people to pick a classification in default object by making the default an anomaly.

2019-04-08 14:41 UTC, SkySkimmer commented
@maximedenes ping

2019-04-08 14:43 UTC, maximedenes commented
> @maximedenes ping

I'm working on other parts of this simplification plan at the moment. Any reason why you ping this particular PR?

2019-04-08 14:45 UTC, SkySkimmer commented
I was looking through random unassigned PRs.

2019-04-08 14:48 UTC, ppedrot commented
I didn't comment at the time, but I am seizing the opportunity of @SkySkimmer's ping to do so.

The question is the following: without Keep objects, how are we going to be able to create libobjects tied to a functorized definition? Currently, you can define an object that is somewhat global respectively to a kernel entry living inside a functor. With only Substitute objects, their initialization only happens when the functor is instantiated.

A typical example, which is somewhat broken currently, is a definition-attached data that shouldn't go in the kernel, e.g. whether a one-constructor inductive should be treated as a record by the upper layers. Currently we store this info in the kernel, but the only real user, if we except user display, is extraction. Bloating the kernel with irrelevant data should be frowned upon, but without (fixed up) Keep objects, I don't see how to do that.

2021-06-07 11:16 UTC, SkySkimmer commented
Future of this is unclear, also dead PR so closing.

2021-06-07 11:16 UTC, closed without merging