Universe Polymorphism with Prop (WIP)
coq/coq pull request #9444
Opened 2019-01-30 18:22 UTC by mattam82

This branch explores a redesign of universes supporting to instantiate polymorphic universe binders with Prop and using this to fix #9294 The easy part is allowing Prop, and this works already. The harder part is emulating template-polymorphism using cumulative inductives while keeping compatibility as much as possible.

**Kind:** bug fix / feature

Fixes / closes #????

Current setup:
- First, allow to set a global lower bound on universes (Prop for standard Coq, can be set to Set for HoTT). This allows i such that Prop < i < Set. At least without Set impredicative, I don't see any issue with that (Set is just a name for a specific level).
- Adapt minimization etc... to comply with this (done)
- Try and emulate template-polymorphic inductives with cumulative ones (WIP).

- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in CHANGES.md.

2019-01-30 18:54 UTC, mattam82 commented on kernel/environ.ml
> +  env_universes_lbound : Univ.Level.t;
That can be done as well.

2019-01-30 18:59 UTC, mattam82 commented
Thinking a bit out loud here but. On top of the first commit, which is not too invasive,  we could implement a restriction of template polymorphism that would already give us soundness I believe: 
- only levels l that are introduced by the inductive declaration and on which no constraint except lbound <= l apply can be instantiated by template polymorphism.

This ensures that any substitution for l results in a typable copy of the inductive, which is how I interpret a template instantiation.

2019-02-02 19:19 UTC, JasonGross requested changes

2019-02-02 19:19 UTC, JasonGross commented on test-suite/bugs/closed/HoTT_coq_120.v
> +Inductive paths@{i} {A : Type@{i}} (a : A) : A -> Type@{i} :=
If I explicitly use `Type`, it should not be minimized to `Prop`.  Or, at least, there should be `Unset Universe Minimization ToProp ` to cause this behavior.  Then this line should not need to be changed.

2019-02-02 19:19 UTC, JasonGross commented on test-suite/bugs/closed/bug_4287.v
> +Definition down (x : Type) : Prop := box x.
This should fail, I think, at least with `Unset Universe Minimization ToProp ` or whatever.  Rigid universes should not be auto-minimized to `Prop`

2019-02-02 19:19 UTC, JasonGross commented on test-suite/bugs/closed/bug_4301.v
> +  Definition U := True : Type@{i}.
Why does this need to be changed?

2019-02-02 19:19 UTC, JasonGross commented on test-suite/bugs/closed/bug_8951.v
> +  Polymorphic Definition t@{i} := True.
What's up with this change?

2019-02-28 20:59 UTC, Janno commented
I've been trying out this branch and I am reasonably sure that it would allow me to rip out at least one very annoying hack from Mtac2. And that's just some low-hanging fruit. I haven't even had time to see if we can remove our implementation of sort polymorphism with this branch.

I just want to say that I would very much appreciate the current stage of this PR landing soon (even without the whole template polymorphism business, although that would also be super awesome!).

2019-03-08 07:03 UTC, gares commented
Btw wasn't this pr, or a part of it, meant to solve the sounds issue of 8.9? Where are we with that?

2019-03-08 07:14 UTC, maximedenes commented
> Btw wasn't this pr, or a part of it, meant to solve the sounds issue of 8.9? Where are we with that?

I haven't made progress on it, but still hope to help @mattam82 with it.

2019-04-02 16:07 UTC, gares commented
My understanding of this PR, or better a part of it, is that it was supposed to fix the soundness bug that affects 8.9, but if we don't progress on this PR it will also affect 8.10 :-(

2019-08-09 19:02 UTC, ppedrot commented
Shouldn't we close this in favour of #9918?

2019-09-25 12:49 UTC, ppedrot commented
No answer from author, taking the liberty to close this PR. The various features introduced in this PR need to be reworked cleanly anyways.

2019-09-25 12:49 UTC, closed without merging