Print name of open section/module
coq/coq pull request #954
Opened 2017-08-05 17:25 UTC by tchajed

Fixes [bug 5597](https://coq.inria.fr/bugs/show_bug.cgi?id=5597).

If desired, I can improve this patch to print the sequence of open sections/modules/module types.

2017-08-05 19:16 UTC, JasonGross commented
Nice!  I think printing the sequence would be nicer; it means you don't need multiple runs of Coq to fix the issue.

2017-08-05 20:55 UTC, tchajed commented
Done. The error message now looks like the following:

```
Error: The section Baz, module type Bar and module Foo need to be closed.
```

I changed the wording since the blocks are listed in the order they should be closed, not the order they were opened in. If you think they should be reversed I'd be happy to switch.

2017-08-05 23:46 UTC, JasonGross requested changes

2017-08-05 23:46 UTC, JasonGross commented on library/lib.ml
> +  str "The " ++ pr_enum open_block_name es ++ str " need to be closed."
Is there a way to make this say `needs` iff there's only one element of the list?

2017-08-06 08:10 UTC, herbelin commented on library/lib.ml
> +  str "The " ++ pr_enum open_block_name es ++ str " need to be closed."
There is `CString.conjugate_verb_to_be : int -> string` but a similar function for other verbs is missing. I don't know English well enough to know whether the general rule is easy to implement (at least for American English).

Probably the simplest to do is to work on a per message basis, with a `if String.length ...`.

2017-08-06 08:32 UTC, tchajed commented on library/lib.ml
> +  str "The " ++ pr_enum open_block_name es ++ str " need to be closed."
I implemented this with a simple check on the length.

We shouldn't have a generic function. Here's a pluralizer for English: https://github.com/clips/pattern/blob/master/pattern/text/en/inflect.py#L107-L443. It's 300 lines of Python and achieves 95% accuracy.

2017-08-06 08:35 UTC, tchajed commented on library/lib.ml
> +  str "The " ++ pr_enum open_block_name es ++ str " need to be closed."
Actually that's only for nouns, but English verbs aren't any better.

2017-08-07 13:11 UTC, herbelin commented on library/lib.ml
> +  str "The " ++ pr_enum open_block_name es ++ str " need to be closed."
@tchajed: Yes, let's be realistic. Maybe, eventually, Coq will embed more and more natural language knowledge (starting e.g. with grammatically correct i18n), but let's not look too far in the future at the current time.

And thanks for the link, and, indirectly, for http://www.csse.monash.edu.au/~damian/papers/HTML/Plurals.html.

2017-08-07 17:03 UTC, JasonGross approved these changes

2017-08-16 07:50 UTC, merged