Don't use print for sys.stdout
coq/coq pull request #9766
Opened 2019-03-14 07:09 UTC by JasonGross

This should fix #9705

I'm kind-of cargo-cult coding here, from things like
https://docs.python.org/3/library/sys.html#sys.displayhook and
https://github.com/coq/coq/issues/9705#issuecomment-471996313, but
hopefully this fixes the issue without breaking anything.  (I am really
a novice when it comes to the str/bytes distinction in python3.)

**Kind:** bug fix

Fixes / closes #9705

- [ ] Added / updated test-suite (not sure what the right test-case is, possibly not worth testing?)

2019-03-14 09:36 UTC, vbgl commented
Is it related to the current failure of bedrock?
~~~
  File "/builds/coq/coq/tools/TimeFileMaker.py", line 47, in get_times
    lines = f.read()
  File "/usr/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 52285: invalid start byte
~~~

2019-03-14 19:49 UTC, jashug requested changes
You should also encode in the plain stdout case. Other than that, looks good to me.
I suppose that print must have been sending a string to the buffer?
Using write directly, you will also lose the newline that print appends, so may want to `write(encode(table + "\n").

2019-03-14 20:47 UTC, JasonGross commented
@vbgl it is related only in the sense that both of these are issues with needing to carefully track encodings of bytes in python3 in a way that was not necessary in python2.  This change will not impact that failure; see also https://github.com/coq/coq/issues/9767

@jashug thanks for the pointer about the trailing newline.  I'm not so sure regarding encoding in the else case; can you explain why https://docs.python.org/3/library/sys.html#sys.displayhook explicitly decodes bytes to text before writing to sys.stdout in a way that's compatible with us having to encode here?  (My model is that sys.stdout.buffer is opened in wb mode and is for bytes-writing, while sys.stdout is opened in w mode and is for text writing.)

2019-03-14 20:48 UTC, JasonGross commented
I will fix the trailing newline issue when I'm next at a computer

2019-03-14 22:05 UTC, jashug commented
In Python 3, the displayhook decodes bytes to string before writing to `sys.stdout` because in Python 3 you are correct, `stdout` is for text writing while `stdout.buffer` is for text writing. Since we always want to output a UTF8 encoded bytestream, in Python 3 we can directly write to `stdout.buffer`.

In Python 2, `stdout.buffer` does not exist, but that is OK because we can write a byte stream directly to stdout in Python 2. We can also write a unicode object (which is the type of `table` in Python 2) to `stdout` and let `stdout` do the encoding for us, but this becomes dependent on what encoding the python system guesses for `stdout`. If we always want to output a UTF8 bytestream, we need to do the encoding ourselves.

The displayhook psuedocode you linked to is only for Python 3, and first writes the text as text to `stdout`, using whatever encoding is guessed. If that encoding fails (not all encodings support all unicode characters), the text is encoded with the same encoding but using a backslash escaping system to support unsupported characters. Then it writes that bytestream to `stdout.buffer`. If, however, someone has sneakily replaced `stdout` with some other file-like object which doesn't have a binary interface buffer, then we turn those bytes back into a string and write that as text to `stdout`, this time with any invalid characters replaced with backslashes. So the whole dance is to support the full range of unicode even with restrictive encodings and even after `stdout` has been replaced by a mere file.

In our case, we don't expect anyone to replace stdout from within python (but they should be able to redirect it, in which case the encoding python guesses for stdout may change), and we always want to use UTF8, so we don't have to worry about invalid characters. Instead, we do have to worry about Python 2 behavior, under which we still get the most consistent results by specifying the encoding ourselves rather than leaving it up to a guess.

2019-03-15 09:35 UTC, fakusb commented
Why do we even try to support both python2 and python3? We could just add `#!/usr/bin/env python3` to the called `.py`-file?

2019-03-15 14:17 UTC, vbgl commented
@JasonGross Thanks for the clarification.

2019-03-31 14:58 UTC, JasonGross commented
Who should be assignee on this?

2019-03-31 22:43 UTC, merged