inferCumulativity: shortcut for all-Invariant inductives
coq/coq pull request #9775
Opened 2019-03-15 13:36 UTC by SkySkimmer

The 0 universe case is certainly useful, but if that's the only one that comes up in practice we could go with a much smaller commit.
Submitting so I don't forget about it.

2019-03-15 13:37 UTC, SkySkimmer commented
ping @Janno

2019-03-27 22:17 UTC, ejgallego commented
@SkySkimmer why is this a draft? Should a tag be set?

2019-03-28 12:04 UTC, SkySkimmer commented
I guess we can merge it, it's not that complex.

2019-03-28 13:04 UTC, ejgallego commented
> I guess we can merge it, it's not that complex.

Cool, please set a milestone.

2019-03-28 13:14 UTC, SkySkimmer commented
Isn't it better to let the assignee set the milestone when they merge?

2019-03-28 13:15 UTC, ejgallego commented
> Isn't it better to let the assignee set the milestone when they merge?

I was thinking that setting a milestone may help finding an assignee sometimes tho.

2019-04-25 12:59 UTC, ppedrot requested changes

2019-04-25 12:59 UTC, ppedrot commented on pretyping/inferCumulativity.ml
> +  match LMap.set u Variance.Invariant variances.v with
This looks pretty fragile to me. If ever we break the invariant that adding the same data in a map results in physical equality, this code is broken. I'd rather check the current value, even if that incurs one more access, or use the `modify` function.

2019-04-25 12:59 UTC, ppedrot commented on pretyping/inferCumulativity.ml
> +  if variances.v == v' then variances
Same remark.

2019-04-25 13:01 UTC, ppedrot commented
@SkySkimmer please don't use physical equality for control. You can use it as an approximation for fast-path, with the invariant that `x == y` implies `x = y`, but that's about it. Other uses are really sources of very subtle bugs you don't want to have to find out painfully.

2019-04-25 13:22 UTC, SkySkimmer commented
New version. The idea is that we only keep the non-Invariant universes in the map, so making a universe Invariant is just Map.remove and instead of keeping a count of non-invariant universes we just check if the map is empty.

2019-04-25 15:18 UTC, ppedrot approved these changes

2019-04-25 15:18 UTC, ppedrot commented
Can we get a bench on polymorphism-using devs?

2019-04-25 15:45 UTC, SkySkimmer commented
It's cumulativity not polymorphism, and it only has an effect when declaring inductives, so I don't think we would see any effect.

2019-04-25 18:45 UTC, ppedrot commented
No developments are using cumulativity?

2019-04-27 11:11 UTC, mattam82 commented
Coq-HoTT will be using it soon, for equality, and I remember we had one case there where switching cumulativity on for everything made cumulativity inference  take ages for one record declaration (to finally show that all universes were invariant). Equations Type variant uses cumulativity for inductives heavily, but there are not so many inductive declarations. Amin Timany’s category-theory library uses it more intensively but is not part of CI I believe. Maybe MTac2 has some examples?

2019-04-27 20:19 UTC, ppedrot commented
OK. In absence of a comprehensive bench, I guess we can safely merge this. I can't be worse than what is implemented currently, so...

2019-04-29 14:36 UTC, merged