Fix make sphinx failure on Windows
coq/coq pull request #9819
Opened 2019-03-23 04:51 UTC by jfehrle

**Kind:** infrastructure.

We'll see if the change needs to be conditional on Windows.

Fixes / closes #9818

2019-03-23 12:28 UTC, Zimmi48 commented
It seems like the change did not break the normal Linux build but it did break the build on Nix. I have no idea how this Makefile works, so I can't really help here.

2019-03-25 18:15 UTC, jfehrle commented
@ejgallego Can you review/merge this small fix sometime soon?
Or perhaps @Zimmi48?

2019-03-25 18:17 UTC, ejgallego commented
I am not the right person for this; maybe @gares ?

2019-03-26 07:10 UTC, gares commented
Why not calling cygpath -w as you do in the bugreport? I don't recall why we set Coqlib, but there must have been a reason, so I'd rather keep it but fix the format.

2019-03-26 08:57 UTC, Zimmi48 commented
Indeed, not me. I'd gladly delegate to @gares here.

2019-03-26 09:54 UTC, gares requested changes

2019-03-26 09:54 UTC, gares commented on Makefile.doc
> +SPHINXENV:=COQBIN="$(CURDIR)/bin/"
I think we should keep the COQLIB, but fix its format by callyng `cygpath -w`

2019-03-26 09:57 UTC, SkySkimmer commented
This seems like the same issue that led to using ocaml_pwd in the test suite, should we use it here too?

2019-03-26 10:02 UTC, gares commented
You mean, for the value of `CURDIR` ?

2019-03-26 10:05 UTC, SkySkimmer commented
yes

Gaëtan Gilbert

On 26/03/2019 11:02, Enrico wrote:
> You mean, for the value of |CURDIR| ?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/coq/coq/pull/9819#issuecomment-476554141>, or mute 
> the thread 
> <https://github.com/notifications/unsubscribe-auth/ACWQ7FtKEkOVkrjL_nUI6DebIPTi6Bv9ks5vafBDgaJpZM4cEtmB>.
>

2019-03-26 18:36 UTC, jfehrle commented
> This seems like the same issue that led to using ocaml_pwd in the test suite, should we use it here too?

Good thought, but no, ocaml_pwd generates a Cygwin path when a Windows path is needed.

```
$ ocaml test-suite/ocaml_pwd.ml .
/cygdrive/c/Users/Jim.DESKTOP-MMPNVGH/Documents/coqSource/coq
```

@gares Please take another look after the build completes.

2019-03-26 21:23 UTC, gares commented
LGTM

2019-03-26 21:23 UTC, gares approved these changes

2019-03-27 13:41 UTC, merged