coq_makefile install target: error if any file is missing
coq/coq pull request #9906
Opened 2019-04-04 12:37 UTC by SkySkimmer

This makes failure reliable instead of failing when the last file to install based on the _CoqProject order is missing and succeeding otherwise even if other files are missing.

2019-04-04 14:06 UTC, gares requested changes

2019-04-04 14:06 UTC, gares commented on tools/CoqMakefile.in
> +	done; exit $$code
I've the impression this makes the install target exit too early

2019-04-04 14:11 UTC, gares approved these changes

2019-04-20 16:42 UTC, merged

2019-04-23 17:03 UTC, Zimmi48 commented
Note that until 8.10+beta1 is actually released, the 8.10.0 milestone doesn't make sense for a PR that is about to be merged.